import { equalContractValue as same, FrontendContractError } from "./neyviaFrontendContracts.js";
const list=value=>Array.isArray(value)?value:[],text=value=>String(value||"").trim();
const requiresSeal=trial=>trial?.capabilityKind==="skill"&&["branch","repair","merge"].includes(String(trial?.action||""));
const sealed=trial=>Boolean(trial?.candidate?.schema==="neyvia.sealed_skill_candidate.v1"&&trial.candidate.state==="sealed"&&trial.candidate.packageDigest&&trial.candidate.skillMarkdown&&trial.candidate.openaiYaml&&trial.candidate.activated===false);
const runBundle=value=>Boolean(value&&typeof value==="object"&&!Array.isArray(value)&&value.schema==="neyvia.capability-run-bundle/v2"&&text(value.appFactoryJobId)&&text(value.appId)&&value.candidateActivated===false&&value.transcriptsIncluded===false&&list(value.runs).length>0&&value.runs.length<=100&&value.runs.every(run=>run?.schema==="neyvia.capability-run/v2"&&run.status==="sealed"&&/^[0-9a-f]{64}$/i.test(String(run.receiptDigest||""))&&run.candidateActivated===false&&run.transcriptsIncluded===false));
const eligible=snapshot=>list(snapshot?.receiptComparisons?.candidates).filter(row=>row?.eligible===true&&row.schema==="neyvia.receipt_measurement.v1"&&row.turnId);
const replayCandidates=trial=>list(trial?.evidence).filter(row=>Boolean(row?.runId&&row.transcriptsIncluded===false&&row.receiptPair?.schema==="neyvia.receipt_comparison.v1"&&row.receiptPair.sameContractConfirmed===true&&row.receiptPair.transcriptsIncluded===false&&row.receiptPair.baseline?.authorityRecorded===true&&row.receiptPair.baseline.authority?.recorded===true&&row.receiptPair.candidate?.authorityRecorded===true&&row.receiptPair.candidate.authority?.recorded===true&&(!requiresSeal(trial)||sealed(trial)&&row.candidatePackageDigest===String(trial.candidate.packageDigest)&&row.receiptPair.candidatePackageDigest===String(trial.candidate.packageDigest)))).slice(-6);
const paths=value=>[...new Set(String(value||"").split(/\r?\n/).map(item=>item.trim().replaceAll("\\","/")).filter(Boolean))].slice(0,12);
const recoveryReady=row=>row?.schema==="neyvia.capability_recovery_mission.v1"&&row.state==="review_required"&&row.humanApprovalRequired===true&&row.candidateActivated!==true&&row.published!==true&&text(row.prompt);
function recommendationCompare(a,b){const order={repair:0,branch:1,prove:2,merge:3,quarantine:4,retire:5,promote_to_app:6},usage=row=>Number(row?.evidenceSummary?.frictionCount||row?.evidenceSummary?.appRunCount||row?.evidenceSummary?.usageCount||0);return Number(b?.status==="trial_active")-Number(a?.status==="trial_active")||Number(a?.priority??9)-Number(b?.priority??9)||(order[a?.action]??99)-(order[b?.action]??99)||usage(b)-usage(a);}
export function checkCapabilityAction(name,args,result){
  const [input,options={}] = args;let expected,valid;
  switch(name){
    case 'capabilityCommands': valid=result.snapshot==='get_capability_evolution_command'&&result.acceptOutcome==='accept_constellation_outcome_command'&&result.buildForge==='build_capability_counterfactual_forge_command'&&result.sealCandidate==='seal_capability_skill_candidate_command'&&result.materializeSkill==='materialize_capability_skill_command'&&result.establishProofLease==='establish_capability_proof_lease_command'&&result.renewProofLease==='renew_capability_proof_lease_command'&&result.importAppOutcomes==='import_capability_run_bundle_command';break;
    case 'capabilityActionLabel': expected=({prove:'Prove',branch:'Branch',repair:'Repair',merge:'Merge',quarantine:'Quarantine',retire:'Retire',promote_to_app:'Make app'})[String(input||'')]||'Review';break;
    case 'selectCapabilityRecommendation': expected=[...list(input?.appOutcomeLearning?.proposals),...list(input?.recommendations)].sort(recommendationCompare)[0]||null;break;
    case 'selectCapabilityRecovery': expected=list(input?.capabilityTreasury?.recoveries).filter(recoveryReady).sort((a,b)=>Number(a?.priority??99)-Number(b?.priority??99)||Number(b?.evidenceCount||0)-Number(a?.evidenceCount||0)||String(a?.title||'').localeCompare(String(b?.title||'')))[0]||null;break;
    case 'buildCapabilityRecoveryPayload': if(!recoveryReady(input)||!text(input.recoveryId))expected=null;else{const route=input.recommendedRoute&&typeof input.recommendedRoute==='object'?input.recommendedRoute:{};expected={recoveryId:String(input.recoveryId),title:String(input.title||'Review prior work'),prompt:String(input.prompt),recommendedLaneId:String(input.recommendedLaneId||''),route:{runtime:String(route.runtime||''),provider:String(route.provider||''),model:String(route.model||''),effort:String(route.effort||''),availability:String(route.availability?.state||route.availability||'')}};}break;
    case 'buildCapabilityTrialPayload': expected=!input?.capabilityId?null:{lineageId:input.lineageId||'',capabilityId:input.capabilityId,capabilityKind:input.capabilityKind||'skill',label:input.label||input.capabilityId,origin:input.origin||'neyvia',action:input.action||'prove',title:input.title||`Prove ${input.label||input.capabilityId}`,reason:input.reason||'',context:{conversationId:options.conversationId??'',missionId:options.missionId??'',intent:'bounded_baseline_candidate_comparison',discoverySource:input.origin||'neyvia',mutationBrief:input.mutationBrief||''},baseline:{source:'current_lineage',...input.evidenceSummary},candidate:{status:'mutation_brief',intent:input.mutationBrief||input.title||'',activated:false},successContract:input.successContract||{},createdBy:'operator'};break;
    case 'isCapabilityRunBundle':expected=runBundle(input);break;
    case 'buildCapabilityRunImportPayload':expected=!runBundle(input)||options.reviewConfirmed!==true?null:{bundle:input,reviewConfirmed:true,importedBy:String(options.importedBy||'operator')};break;
    case 'skillCandidateRequiresSeal':expected=requiresSeal(input);break;
    case 'skillCandidateIsSealed':expected=sealed(input);break;
    case 'skillCandidateCanCompare':expected=!requiresSeal(input)||sealed(input);break;
    case 'buildSkillCandidateMarkdown': {const id=text(input?.candidate?.targetSkillId),description=String(options.description||'').replace(/\s+/g,' ').trim(),instructions=text(options.instructions);expected=!id||!description||!instructions?'':['---',`name: ${id}`,`description: ${JSON.stringify(description)}`,'---','',`# ${text(input?.candidate?.displayName||input?.label||id)}`,'','## Goal','',description,'','## Workflow','',instructions,''].join('\n');break;}
    case 'buildSkillCandidateSealPayload': {const description=String(options.description||'').replace(/\s+/g,' ').trim(),instructions=text(options.instructions),id=text(input?.candidate?.targetSkillId);if(!input?.trialId||!requiresSeal(input)||sealed(input)||options.reviewConfirmed!==true||list(input.evidence).length||!id||!description||!instructions)expected=null;else{const sentence=description[0].toLowerCase()+description.slice(1);valid=result?.trialId===input.trialId&&result.reviewConfirmed===true&&result.sealedBy===String(options.sealedBy||'operator')&&result.skillMarkdown.includes(`name: ${id}\n`)&&result.skillMarkdown.includes(instructions)&&result.defaultPrompt===`Use $${String(input.candidate.targetSkillId)} to ${sentence.replace(/\.$/,'')}.`;}break;}
    case 'synthesisCanEnterLearning':expected=Boolean(input?.synthesis?.synthesisId&&input.synthesis.status==='ready'&&input.synthesis.evidence?._contract?.ready===true);break;
    case 'eligibleReceiptCandidates':expected=eligible(input);break;
    case 'proofLeaseReceiptCandidates':expected=eligible(input).filter(row=>row.verificationStatus==='passed'&&row.authorityRecorded===true);break;
    case 'receiptOptionLabel': {if(!input?.turnId)expected='Unknown receipt';else{const count=Number(input.proofArtifactCount||0);expected=[[input.runtime,input.model].filter(Boolean).join(' · ')||'Recorded run',String(input.verificationStatus||input.status||'recorded').replaceAll('_',' '),`${count} proof artifact${count===1?'':'s'}`].join(' · ');}break;}
    case 'buildReceiptComparisonPayload':expected=!input?.trialId||requiresSeal(input)&&!sealed(input)||!options.conversationId||!options.baselineTurnId||!options.candidateTurnId||options.baselineTurnId===options.candidateTurnId||options.sameContractConfirmed!==true||!['candidate_better','about_the_same','baseline_better'].includes(options.operatorValue)?null:{trialId:input.trialId,conversationId:options.conversationId,missionId:options.missionId??'',baselineTurnId:options.baselineTurnId,candidateTurnId:options.candidateTurnId,sameContractConfirmed:true,operatorValue:options.operatorValue,operatorNote:text(options.operatorNote),recordedBy:'operator'};break;
    case 'counterfactualReplayCandidates':expected=replayCandidates(input);break;
    case 'counterfactualCaseLabel':{const lift=Number(input?.deltas?.outcomeLift);expected=`${String(input?.receiptPair?.baseline?.turnId||'baseline')} → ${String(input?.receiptPair?.candidate?.turnId||'candidate')} · ${Number.isFinite(lift)?`${Math.round(lift*100)}% lift`:'lift unmeasured'}`;break;}
    case 'buildCounterfactualForgePayload':{const available=replayCandidates(input),ids=[...new Set(Array.isArray(options.caseRunIds)?options.caseRunIds.filter(Boolean):available.map(row=>row.runId))].slice(0,6),required=Math.max(1,Number(input?.successContract?.requiredComparableRuns||1));expected=!input?.trialId||options.reviewConfirmed!==true||!['branch','repair','merge','promote_to_app'].includes(input.action)||ids.length<required||ids.some(id=>!available.some(row=>row.runId===id))?null:{trialId:input.trialId,caseRunIds:ids,reviewConfirmed:true,reviewedBy:String(options.reviewedBy||'operator')};break;}
    case 'counterfactualForgeCanApprove':{const forge=input?.verdict?.counterfactualForge;expected=Boolean(input?.state==='evidence_ready'&&(!requiresSeal(input)||sealed(input)&&forge?.candidatePackageDigest===input.candidate.packageDigest)&&forge?.schema==='neyvia.counterfactual_skill_forge.v1'&&forge.reviewConfirmed===true&&forge.reviewGatePassed===true&&forge.recommendedDecision==='accept'&&forge.candidateActivated===false);break;}
    case 'selectSkillMaterializationReview':{const leaseRank=row=>({held:0,reproof_required:1,review_due:2,retirement_review:3,unestablished:4,current:5,withdrawn:6})[String(row?.proofLease?.state||'')]??7;expected=list(input?.skillMaterializationReviews).slice().sort((a,b)=>(a?.state==='review_required'?0:2)-(b?.state==='review_required'?0:2)||leaseRank(a)-leaseRank(b))[0]||null;break;}
    case 'buildSkillMaterializationPayload':expected=!input?.trialId||!input.candidateDigest||input.state!=='review_required'||input.canMaterialize!==true||options.reviewConfirmed!==true?null:{trialId:input.trialId,candidateDigest:input.candidateDigest,reviewConfirmed:true,materializedBy:String(options.materializedBy||'operator')};break;
    case 'buildSkillMaterializationRollbackPayload':{const record=input?.materialization||input;expected=!record?.materializationId||!record.candidateDigest||record.state!=='materialized_inactive'||options.reviewConfirmed!==true?null:{materializationId:record.materializationId,candidateDigest:record.candidateDigest,reviewConfirmed:true,rolledBackBy:String(options.rolledBackBy||'operator'),reason:text(options.reason)};break;}
    case 'proofLeaseDependencyPaths':expected=paths(input);break;
    case 'buildProofLeaseEstablishPayload':{const record=input?.materialization||input,lease=input?.proofLease||{},goal=String(options.goalStatement||'').replace(/\s+/g,' ').trim(),days=Number(options.reviewAfterDays??30);expected=!record?.materializationId||record.state!=='materialized_inactive'||lease.state!=='unestablished'||lease.canEstablish!==true||goal.length<12||!Number.isInteger(days)||days<1||days>365||options.reviewConfirmed!==true?null:{materializationId:record.materializationId,goalStatement:goal,dependencyPaths:paths(options.dependencyPaths),reviewAfterDays:days,reviewConfirmed:true,issuedBy:String(options.issuedBy||'operator')};break;}
    case 'buildProofLeaseRenewalPayload':{const record=input?.materialization||input;expected=!record?.materializationId||!record.candidateDigest||record.state!=='materialized_inactive'||input?.proofLease?.canRenew!==true||!options.conversationId||!options.turnId||options.goalStillMatches!==true||options.operatorValue!=='still_useful'||options.reviewConfirmed!==true?null:{materializationId:record.materializationId,candidateDigest:record.candidateDigest,conversationId:options.conversationId,turnId:options.turnId,goalStillMatches:true,operatorValue:'still_useful',reviewConfirmed:true,renewedBy:String(options.renewedBy||'operator')};break;}
    case 'buildProofLeaseDispositionPayload':{const record=input?.materialization||input,lease=String(input?.proofLease?.state||'');expected=!record?.materializationId||!lease||['unestablished','withdrawn'].includes(lease)||!['needs_repair','no_longer_needed'].includes(options.disposition)||options.reviewConfirmed!==true?null:{materializationId:record.materializationId,disposition:options.disposition,note:text(options.note),reviewConfirmed:true,recordedBy:String(options.recordedBy||'operator')};break;}
    case 'buildCapabilityAppPrompt':{const count=Number(options?.verdict?.comparableRunCount||input?.evidenceSummary?.feedbackCount||0);valid=!input?.capabilityId?result==='':typeof result==='string'&&result.includes(`Preserve capability ID ${input.capabilityId}`)&&result.includes(count?`Use ${count} comparable evidence run${count===1?'':'s'}`:'Do not claim the flow is proven')&&result.includes('installation review-gated, expose rollback, and return App Factory proof.');break;}
    default:throw new FrontendContractError('capability.'+name);
  }
  if(valid===undefined)valid=same(result,expected);
  if(!valid)throw new FrontendContractError('capability.'+name);
  return result;
}
