CL 1
L app-sdk v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Generate, inspect and prove an app through one user and agent state"}},"clVersion":"1.1","id":"app-sdk","kind":"environment","schema":"neyvia.manual.v1","schemas":{"neyvia.app_sdk.action":"t1","neyvia.app_sdk.build":"t2","neyvia.app_sdk.describe":"t3","neyvia.app_sdk.new":"t4","neyvia.app_sdk.preview":"t5","neyvia.app_sdk.state":"t3","neyvia.app_sdk.toolchain":"t6","neyvia.app_sdk.verify":"t7"},"tool_metadata":{"neyvia.app_sdk.action":{"mutability_class":"external_action"},"neyvia.app_sdk.build":{"mutability_class":"artifact_write"},"neyvia.app_sdk.describe":{"mutability_class":"read"},"neyvia.app_sdk.new":{"mutability_class":"artifact_write"},"neyvia.app_sdk.preview":{"mutability_class":"none"},"neyvia.app_sdk.state":{"mutability_class":"read"},"neyvia.app_sdk.toolchain":{"mutability_class":"read"},"neyvia.app_sdk.verify":{"mutability_class":"external_action"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\"},\"clSource\":{\"type\":\"string\"},\"native\":{\"type\":\"object\"}},\"required\":[\"project\",\"url\",\"name\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"url\":{\"not\":{\"enum\":[\"\"]}},\"name\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"platform\":{\"enum\":[\"web\",\"pwa\",\"expo\",\"desktop\",\"ios\",\"android\"]}},\"required\":[\"project\",\"platform\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"kind\":{\"enum\":[\"web\",\"pwa\",\"expo\",\"desktop\"]}},\"required\":[\"path\",\"name\",\"kind\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}},\"name\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"device\":{\"type\":\"string\"},\"port\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":65535}},\"required\":[\"project\",\"port\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{platform:"android"|"ios" project?:str ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"},\"clSource\":{\"type\":\"string\"},\"native\":{\"type\":\"object\"},\"steps\":{\"type\":\"array\",\"items\":{\"type\":\"object\"}}},\"required\":[\"project\",\"url\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8{project:str}
T t9 json:"{\"type\":\"object\"}"
T t10{ok:true ..}
T t11{path:str name:str kind:"web"|"pwa"|"expo"|"desktop" ..}
T t12{project:str url:str name:str ..}
T t13{project:str platform:"web"|"pwa"|"expo"|"desktop"|"ios"|"android" ..}
T t14{}
L app-sdk.overview v1 -- Generate, inspect and prove an app through one user and agent state
-- @record {"chapter":"overview","data":{"args":{"project":{"$input":"project"}},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.app_sdk.state"},"key":"app","section":"state"}
S app-sdk.app:json:"{\"type\":\"object\"}"=neyvia.app_sdk.state(project:project)
-- @record {"chapter":"overview","data":{"effect":"Generate an app with a CL 1.1 manual, shared user/agent state and executable running-app goals. Does not install dependencies.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.app_sdk.new","tool":"neyvia.app_sdk.new"},"key":"sdk.new","section":"actions"}
A neyvia.app_sdk.new(path:str name:str kind:"web"|"pwa"|"expo"|"desktop") -> json:"{\"type\":\"object\"}" ! -- Generate an app with a CL 1.1 manual, shared user/agent state and executable running-app goals. Does not install dependencies.
F verify-sdk-new "No authored observer check is bound to neyvia.app_sdk.new" -> ask operator blocks:neyvia.app_sdk.new
-- @record {"chapter":"overview","data":{"effect":"Read an SDK app's manual, platforms and current build/verification receipts.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.app_sdk.describe","tool":"neyvia.app_sdk.describe"},"key":"sdk.describe","section":"actions"}
A neyvia.app_sdk.describe(project:str) -> json:"{\"type\":\"object\"}" -- Read an SDK app's manual, platforms and current build/verification receipts.
F verify-sdk-describe "No authored observer check is bound to neyvia.app_sdk.describe" -> ask operator blocks:neyvia.app_sdk.describe
-- @record {"chapter":"overview","data":{"effect":"Read the app's persisted shared state; the user UI and agents use this exact store.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.app_sdk.state","tool":"neyvia.app_sdk.state"},"key":"sdk.state","section":"actions"}
A neyvia.app_sdk.state(project:str) -> json:"{\"type\":\"object\"}" -- Read the app's persisted shared state; the user UI and agents use this exact store.
F verify-sdk-state "No authored observer check is bound to neyvia.app_sdk.state" -> ask operator blocks:neyvia.app_sdk.state
-- @record {"chapter":"overview","data":{"effect":"Apply a typed app action through its exact running reducer using T18; the same shared state updates the user UI.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.app_sdk.action","tool":"neyvia.app_sdk.action"},"key":"sdk.action","section":"actions"}
A neyvia.app_sdk.action(project:str url:str name:str arguments?:json:"{\"type\":\"object\"}" clSource?:str native?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Apply a typed app action through its exact running reducer using T18; the same shared state updates the user UI.
F verify-sdk-action "No authored observer check is bound to neyvia.app_sdk.action" -> ask operator blocks:neyvia.app_sdk.action
-- @record {"chapter":"overview","data":{"effect":"Run the app's goals through T18 web perception and optional T16 native inspection; failed goals refuse completion. Uses an explicit running-app URL.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.app_sdk.verify","tool":"neyvia.app_sdk.verify"},"key":"sdk.verify","section":"actions"}
A neyvia.app_sdk.verify(project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]) -> {ok:true ..} ! -- Run the app's goals through T18 web perception and optional T16 native inspection; failed goals refuse completion. Uses an explicit running-app URL.
F verify-sdk-verify "No authored observer check is bound to neyvia.app_sdk.verify" -> ask operator blocks:neyvia.app_sdk.verify
-- @record {"chapter":"overview","data":{"effect":"Open an SDK app in Mobile Studio's existing phone frame. port is the explicit running Neyvia backend port.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.app_sdk.preview","tool":"neyvia.app_sdk.preview"},"key":"sdk.preview","section":"actions"}
A neyvia.app_sdk.preview(project:str device?:str port:1..65535) -> json:"{\"type\":\"object\"}" ! -- Open an SDK app in Mobile Studio's existing phone frame. port is the explicit running Neyvia backend port.
F verify-sdk-preview "No authored observer check is bound to neyvia.app_sdk.preview" -> ask operator blocks:neyvia.app_sdk.preview
-- @record {"chapter":"overview","data":{"effect":"Build an SDK app using installed local tools. Offline web builds carry source hashes; unavailable native toolchains are reported, never installed.","pre":"Explicit scoped project; runtime actions use an explicit running URL; builds use installed tools only","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.app_sdk.build","tool":"neyvia.app_sdk.build"},"key":"sdk.build","section":"actions"}
A neyvia.app_sdk.build(project:str platform:"web"|"pwa"|"expo"|"desktop"|"ios"|"android") -> json:"{\"type\":\"object\"}" ! -- Build an SDK app using installed local tools. Offline web builds carry source hashes; unavailable native toolchains are reported, never installed.
F verify-sdk-build "No authored observer check is bound to neyvia.app_sdk.build" -> ask operator blocks:neyvia.app_sdk.build
-- @record {"chapter":"overview","data":{"effect":"Observe the exact native build owner toolchain without starting adb, an emulator or downloads","pre":"Selected installed native platform; project optional for Android","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.app_sdk.toolchain","tool":"neyvia.app_sdk.toolchain"},"key":"native-toolchain","section":"actions"}
A neyvia.app_sdk.toolchain(platform:"android"|"ios" project?:str) -> json:"{\"type\":\"object\"}" -- Observe the exact native build owner toolchain without starting adb, an emulator or downloads
C neyvia.app_sdk.toolchain android-ready:neyvia.app_sdk.toolchain(platform:"android") .ready == true
-- @record {"chapter":"overview","data":{"args":{"platform":"android"},"expect":{"op":"eq","path":"ready","value":true},"tool":"neyvia.app_sdk.toolchain"},"key":"android-ready","section":"checks"}
C neyvia.app_sdk.toolchain android-ready:neyvia.app_sdk.toolchain(platform:"android") .ready == true
-- @record {"chapter":"overview","data":{"goal":"Read the generated app manual and shared state","inputs":{"$cl_type":"t8"},"steps":[{"action":"sdk.describe","args":{"project":{"$input":"project"}},"save":"manual"},{"action":"sdk.state","args":{"project":{"$input":"project"}},"save":"state"}]},"key":"inspect","section":"procedures"}
P inspect(project:str):manual=neyvia.app_sdk.describe(project:project); state=neyvia.app_sdk.state(project:project) -- Read the generated app manual and shared state
V P inspect -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t11"},"steps":[{"action":"sdk.new","args":{"kind":{"$input":"kind"},"name":{"$input":"name"},"path":{"$input":"path"}},"save":"effect"}]},"key":"verify-effect-sdk-new","section":"procedures"}
P verify-effect-sdk-new(path:str name:str kind:"web"|"pwa"|"expo"|"desktop"):effect=neyvia.app_sdk.new(kind:kind name:name path:path) -- Verify the actual effect through fresh owning observers
V P verify-effect-sdk-new -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t12"},"steps":[{"action":"sdk.action","args":{"name":{"$input":"name"},"project":{"$input":"project"},"url":{"$input":"url"}},"save":"effect"}]},"key":"verify-effect-sdk-action","section":"procedures"}
P verify-effect-sdk-action(project:str url:str name:str):effect=neyvia.app_sdk.action(name:name project:project url:url) -- Verify the actual effect through fresh owning observers
V P verify-effect-sdk-action -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t13"},"steps":[{"action":"sdk.build","args":{"platform":{"$input":"platform"},"project":{"$input":"project"}},"save":"effect"}]},"key":"verify-effect-sdk-build","section":"procedures"}
P verify-effect-sdk-build(project:str platform:"web"|"pwa"|"expo"|"desktop"|"ios"|"android"):effect=neyvia.app_sdk.build(platform:platform project:project) -- Verify the actual effect through fresh owning observers
V P verify-effect-sdk-build -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Prove Android App Factory prerequisites from the existing build owner; this does not claim an APK build or device installation","inputs":{"$cl_type":"t14"},"steps":[{"action":"native-toolchain","args":{"platform":"android"},"check":"android-ready","save":"android"}]},"key":"inspect-android-toolchain","section":"procedures"}
P inspect-android-toolchain():android=neyvia.app_sdk.toolchain(platform:"android") C android-ready -- Prove Android App Factory prerequisites from the existing build owner; this does not claim an APK build or device installation
V P inspect-android-toolchain -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"App goal check fails","recovery":"Read exact failed goal and live receipt, repair source, rebuild and re-run; never weaken the goal to mark done"},"key":"0","section":"pitfalls"}
X App goal check fails -> Read exact failed goal and live receipt, repair source, rebuild and re-run; never weaken the goal to mark done
-- @record {"chapter":"overview","data":{"failure":"Native toolchain is unavailable","recovery":"Read needsPaul; never install or silently substitute a web build for a native build"},"key":"1","section":"pitfalls"}
X Native toolchain is unavailable -> Read needsPaul; never install or silently substitute a web build for a native build
-- @record {"chapter":"overview","data":"Expo native packaging, device installs and signed release delivery depend on local toolchains and separate authorization","key":"0","section":"frontier"}
F Expo native packaging, device installs and signed release delivery depend on local toolchains and separate authorization
-- @record {"chapter":"overview","data":"Generated app CL1.1 manuals define state, typed actions, runtime goal checks and procedures.","key":"0","section":"guidance"}
M app-sdk "Generated app CL1.1 manuals define state, typed actions, runtime goal checks and procedures." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Autopilot callers set appGoal and scope neyvia.app_sdk.verify; it re-runs the live journey before completed.","key":"1","section":"guidance"}
M app-sdk "Autopilot callers set appGoal and scope neyvia.app_sdk.verify; it re-runs the live journey before completed." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"app_sdk.verify and app_sdk.action mutate the explicitly scoped app; they are external actions.","key":"2","section":"guidance"}
M app-sdk "app_sdk.verify and app_sdk.action mutate the explicitly scoped app; they are external actions." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Every generation/build/action/verification claims its project in the work board and releases the claim after returning.","key":"3","section":"guidance"}
M app-sdk "Every generation/build/action/verification claims its project in the work board and releases the claim after returning." src:"authored manual" state:verified
