CL 1
L autopilot v1 -- Authored executable manual
-- @manual {"chapters":{"fixcl3-local":{"title":"Exact retained local admission and supervision"},"fixcl4-real":{"title":"Actual provider and manual completion"},"overview":{"title":"Autopilot: intent to verified checklist"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"}},"clVersion":"1.1","id":"autopilot","kind":"workflow","proofs":{"area":"proofs-e-models","manifests":["config/proofs/proofs-e-models.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.autopilot.get":"t1","neyvia.autopilot.list":"t2","neyvia.autopilot.resume":"t3","neyvia.autopilot.start":"t4","neyvia.autopilot.stop":"t1","proofs-e-models.status":"t2"},"tool_metadata":{"neyvia.autopilot.get":{},"neyvia.autopilot.list":{},"neyvia.autopilot.resume":{},"neyvia.autopilot.start":{},"neyvia.autopilot.stop":{},"neyvia.verify.status":{}}}
-- @proof {"id":"autopilot.live-manual-selection","phase":"invariant","claim":"Plan and frontier schemas enumerate live scoped manual IDs. Unique aliases, typos or exact chapter/procedure matches resolve before execution; an unresolvable selection gets one budgeted catalog retry without replaying effects.","checkedAt":["src/grant_agent/neyvia_autopilot.py:selection_model","src/grant_agent/neyvia_autopilot.py:resolve_manual_id","src/grant_agent/neyvia_autopilot.py:checked_selection"],"impact":["Autopilot plan and frontier manual selection"]}
-- @proof {"checkedAt":["web/src/neyvia/next/nxAutopilotModel.js:scopeTools -> checkedProofsEModel"],"claim":"Unknown scopes are read-only; edit adds only workspace.write","id":"autopilot.scopeTools","impact":["autopilot frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxAutopilotModel.js:scopeOf -> checkedProofsEModel"],"claim":"Only a named CAS workspace.write grants edit scope","id":"autopilot.scopeOf","impact":["autopilot frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxAutopilotModel.js:attributeCalls -> checkedProofsEModel"],"claim":"Every observed model call stays visible once, with its measured tokens, and judgement/frontier calls follow item order","id":"autopilot.attributeCalls","impact":["autopilot frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxAutopilotModel.js:shapeRun -> checkedProofsEModel"],"claim":"Item routes preserve receipts; completed manual/script counts and total tokens come only from durable observations","id":"autopilot.shapeRun","impact":["autopilot frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxAutopilotModel.js:checkLine -> checkedProofsEModel"],"claim":"Final verification text names the real tool, target, observed path and exact operation/value","id":"autopilot.checkLine","impact":["autopilot frontend model consumers"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"runId\":{\"type\":\"string\"}},\"required\":[\"runId\"],\"allOf\":[{\"properties\":{\"runId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2{..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"runId\":{\"type\":\"string\"},\"background\":{\"type\":\"boolean\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"runId\"],\"allOf\":[{\"properties\":{\"runId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4{requestId:str#1..160 text:str#1..40000 sessionId?:str scopeTools:[str]#1..100 background?:bool efficiency?:bool appGoal?:{project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]} maxModelCalls?:1..50 maxSeconds?:10..3600 ..}
T t5 json:"{\"type\":\"object\"}"
T t6{runId:str}
T t7 json:"{\"type\":\"object\",\"properties\":{\"requestId\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},\"text\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":40000},\"sessionId\":{\"type\":\"string\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1,\"maxItems\":100},\"background\":{\"type\":\"boolean\"},\"efficiency\":{\"type\":\"boolean\"},\"appGoal\":{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"},\"clSource\":{\"type\":\"string\"},\"native\":{\"type\":\"object\"},\"steps\":{\"type\":\"array\",\"items\":{\"type\":\"object\"}}},\"required\":[\"project\",\"url\"],\"additionalProperties\":false},\"maxModelCalls\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":50},\"maxSeconds\":{\"type\":\"integer\",\"minimum\":10,\"maximum\":3600}},\"required\":[\"requestId\",\"text\",\"scopeTools\",\"appGoal\",\"background\",\"efficiency\",\"maxModelCalls\",\"maxSeconds\",\"sessionId\"]}"
T t8{runId:str background:bool scopeTools:[str] ..}
T t9 json:"{\"type\":\"object\",\"required\":[\"run\"]}"
T t10{ok:bool ..}
T t11 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L autopilot.fixcl3-local v1 -- Exact retained local admission and supervision
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained autopilot.stop","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t5"},"reversible":true,"schema":"neyvia.autopilot.stop","tool":"neyvia.autopilot.stop"},"key":"neyvia.autopilot.stop","section":"actions"}
A neyvia.autopilot.stop(runId:str) -> json:"{\"type\":\"object\"}" ! -- Exact retained autopilot.stop
C neyvia.autopilot.stop autopilot-stop-observed:neyvia.autopilot.get(runId:runId) .run.status == "stopped"
-- @record {"chapter":"fixcl3-local","data":{"args":{"runId":{"$input":"runId"}},"expect":{"op":"eq","path":"run.status","value":"stopped"},"tool":"neyvia.autopilot.get"},"key":"autopilot-stop-observed","section":"checks"}
C neyvia.autopilot.get autopilot-stop-observed:neyvia.autopilot.get(runId:runId) .run.status == "stopped"
-- @record {"chapter":"fixcl3-local","data":{"goal":"Requested local autopilot.stop matches fresh owner observation","inputs":{"$cl_type":"t6"},"steps":[{"action":"neyvia.autopilot.stop","args":{"runId":{"$input":"runId"}},"check":"autopilot-stop-observed","save":"effect"}]},"key":"retain-autopilot-stop","section":"procedures"}
P retain-autopilot-stop(runId:str):effect=neyvia.autopilot.stop(runId:runId) C autopilot-stop-observed -- Requested local autopilot.stop matches fresh owner observation
V P retain-autopilot-stop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"fixcl3-local","data":{"failure":"Fresh owner state differs from this action subject","recovery":"Reconcile the specific retained effect; never replay an uncertain launch."},"key":"0","section":"pitfalls"}
X Fresh owner state differs from this action subject -> Reconcile the specific retained effect; never replay an uncertain launch.
-- @record {"chapter":"fixcl3-local","data":"Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.","key":"0","section":"frontier"}
F Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.
-- @record {"chapter":"fixcl3-local","data":"CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes.","key":"0","section":"guidance"}
M autopilot "CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes." src:"authored manual" state:verified
L autopilot.fixcl4-real v1 -- Actual provider and manual completion
-- @record {"chapter":"fixcl4-real","data":{"effect":"Complete an intent through scoped manuals and executable checks; models only decide branches. Retry requestId safely.","pre":"Explicit selected provider, original caller tool scope and bounded owned workspace","returns":{"$cl_type":"t5"},"reversible":false,"schema":"neyvia.autopilot.start","tool":"neyvia.autopilot.start"},"key":"autopilot.start","section":"actions"}
A neyvia.autopilot.start(requestId:str#1..160 text:str#1..40000 sessionId?:str scopeTools:[str]#1..100 background?:bool efficiency?:bool appGoal?:{project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]} maxModelCalls?:1..50 maxSeconds?:10..3600) -> json:"{\"type\":\"object\"}" ! -- Complete an intent through scoped manuals and executable checks; models only decide branches. Retry requestId safely.
F verify-autopilot-start "No authored observer check is bound to neyvia.autopilot.start" -> ask operator blocks:neyvia.autopilot.start
-- @record {"chapter":"fixcl4-real","data":{"effect":"Continue a stopped run without replaying completed or uncertain effects; original scope cannot widen.","pre":"Explicit selected provider, original caller tool scope and bounded owned workspace","returns":{"$cl_type":"t5"},"reversible":false,"schema":"neyvia.autopilot.resume","tool":"neyvia.autopilot.resume"},"key":"autopilot.resume","section":"actions"}
A neyvia.autopilot.resume(runId:str background?:bool scopeTools?:[str]) -> json:"{\"type\":\"object\"}" ! -- Continue a stopped run without replaying completed or uncertain effects; original scope cannot widen.
F verify-autopilot-resume "No authored observer check is bound to neyvia.autopilot.resume" -> ask operator blocks:neyvia.autopilot.resume
-- @record {"chapter":"fixcl4-real","data":{"goal":"Complete an intent through scoped manuals and executable checks; models only decide branches. Retry requestId safely.","inputs":{"$cl_type":"t7"},"steps":[{"action":"autopilot.start","args":{"appGoal":{"$input":"appGoal"},"background":{"$input":"background"},"efficiency":{"$input":"efficiency"},"maxModelCalls":{"$input":"maxModelCalls"},"maxSeconds":{"$input":"maxSeconds"},"requestId":{"$input":"requestId"},"scopeTools":{"$input":"scopeTools"},"sessionId":{"$input":"sessionId"},"text":{"$input":"text"}},"save":"effect"}]},"key":"verify-autopilot-start","section":"procedures"}
P verify-autopilot-start(requestId:str#1..160 text:str#1..40000 sessionId:str scopeTools:[str]#1..100 background:bool efficiency:bool appGoal:{project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]} maxModelCalls:1..50 maxSeconds:10..3600):effect=neyvia.autopilot.start(appGoal:appGoal background:background efficiency:efficiency maxModelCalls:maxModelCalls maxSeconds:maxSeconds requestId:requestId scopeTools:scopeTools sessionId:sessionId text:text) -- Complete an intent through scoped manuals and executable checks; models only decide branches. Retry requestId safely.
V P verify-autopilot-start -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"fixcl4-real","data":{"goal":"Continue a stopped run without replaying completed or uncertain effects; original scope cannot widen.","inputs":{"$cl_type":"t8"},"steps":[{"action":"autopilot.resume","args":{"background":{"$input":"background"},"runId":{"$input":"runId"},"scopeTools":{"$input":"scopeTools"}},"save":"effect"}]},"key":"verify-autopilot-resume","section":"procedures"}
P verify-autopilot-resume(runId:str background:bool scopeTools:[str]):effect=neyvia.autopilot.resume(background:background runId:runId scopeTools:scopeTools) -- Continue a stopped run without replaying completed or uncertain effects; original scope cannot widen.
V P verify-autopilot-resume -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"fixcl4-real","data":{"failure":"A queued admission or provider call is called completed","recovery":"Read the retained owner and require actual terminal provider/manual receipts and fresh acceptance."},"key":"0","section":"pitfalls"}
X A queued admission or provider call is called completed -> Read the retained owner and require actual terminal provider/manual receipts and fresh acceptance.
-- @record {"chapter":"fixcl4-real","data":"Selected provider unavailability or model refusal is retained as a failure; no provider substitution or fabricated output.","key":"0","section":"frontier"}
F Selected provider unavailability or model refusal is retained as a failure; no provider substitution or fabricated output.
-- @record {"chapter":"fixcl4-real","data":"Reuse the exact request identity and original scope. Completed resumes verify retained effects without replaying completed work.","key":"0","section":"guidance"}
M autopilot "Reuse the exact request identity and original scope. Completed resumes verify retained effects without replaying completed work." src:"authored manual" state:verified
-- @record {"chapter":"fixcl4-real","data":"Select NEYVIA_AUTOPILOT_SMALL_MODEL explicitly for this process before starting a run. Supported routes are gpt-6-luna and gpt-6.1-sol; an unknown route fails before inference. Provider receipts retain the actual model and token usage.","key":"1","section":"guidance"}
M autopilot "Select NEYVIA_AUTOPILOT_SMALL_MODEL explicitly for this process before starting a run. Supported routes are gpt-6-luna and gpt-6.1-sol; an unknown route fails before inference. Provider receipts retain the actual model and token usage." src:"authored manual" state:verified
L autopilot.overview v1 -- Autopilot: intent to verified checklist
-- @record {"chapter":"overview","data":{"args":{"runId":{"$input":"runId"}},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t9"},"tool":"neyvia.autopilot.get"},"key":"run","section":"state"}
S autopilot.run:json:"{\"type\":\"object\",\"required\":[\"run\"]}"=neyvia.autopilot.get(runId:runId)
-- @record {"chapter":"overview","data":{"effect":"Read authoritative durable receipts","pre":"Returned runId in this workspace","returns":{"$cl_type":"t5"},"reversible":true,"schema":"neyvia.autopilot.get","tool":"neyvia.autopilot.get"},"key":"inspect","section":"actions"}
A neyvia.autopilot.get(runId:str) -> json:"{\"type\":\"object\"}" ! -- Read authoritative durable receipts
C neyvia.autopilot.get completed:neyvia.autopilot.get(runId:runId) .run.status == "completed"
-- @record {"chapter":"overview","data":{"effect":"Run synchronously through the Native gateway or start background owner HTTP; every ask gets checked receipts","pre":"Explicit intent/requestId and exact scopeTools; caller already holds every nested grant","returns":{"$cl_type":"t5"},"reversible":false,"schema":"neyvia.autopilot.start","tool":"neyvia.autopilot.start"},"key":"start","section":"actions"}
A neyvia.autopilot.start(requestId:str#1..160 text:str#1..40000 sessionId?:str scopeTools:[str]#1..100 background?:bool efficiency?:bool appGoal?:{project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]} maxModelCalls?:1..50 maxSeconds?:10..3600) -> json:"{\"type\":\"object\"}" ! -- Run synchronously through the Native gateway or start background owner HTTP; every ask gets checked receipts
F verify-start "No authored observer check is bound to neyvia.autopilot.start" -> ask operator blocks:neyvia.autopilot.start
-- @record {"chapter":"overview","data":{"effect":"Read durable run states","pre":"Selected workspace","returns":{"$cl_type":"t5"},"reversible":true,"schema":"neyvia.autopilot.list","tool":"neyvia.autopilot.list"},"key":"list","section":"actions"}
A neyvia.autopilot.list() -> json:"{\"type\":\"object\"}" ! -- Read durable run states
F verify-list "No authored observer check is bound to neyvia.autopilot.list" -> ask operator blocks:neyvia.autopilot.list
-- @record {"chapter":"overview","data":{"effect":"Stop at next action boundary; preserve newest progress and source bytes","pre":"Returned runId","returns":{"$cl_type":"t5"},"reversible":true,"schema":"neyvia.autopilot.stop","tool":"neyvia.autopilot.stop"},"key":"stop","section":"actions"}
A neyvia.autopilot.stop(runId:str) -> json:"{\"type\":\"object\"}" ! -- Stop at next action boundary; preserve newest progress and source bytes
F verify-stop "No authored observer check is bound to neyvia.autopilot.stop" -> ask operator blocks:neyvia.autopilot.stop
-- @record {"chapter":"overview","data":{"effect":"Continue retained progress; completed children are never repeated","pre":"Original scope, worker quiesced, no unknown effects or unresolved authority","returns":{"$cl_type":"t5"},"reversible":false,"schema":"neyvia.autopilot.resume","tool":"neyvia.autopilot.resume"},"key":"resume","section":"actions"}
A neyvia.autopilot.resume(runId:str background?:bool scopeTools?:[str]) -> json:"{\"type\":\"object\"}" ! -- Continue retained progress; completed children are never repeated
F verify-resume "No authored observer check is bound to neyvia.autopilot.resume" -> ask operator blocks:neyvia.autopilot.resume
-- @record {"chapter":"overview","data":{"args":{"runId":{"$input":"runId"}},"expect":{"op":"eq","path":"run.status","value":"completed"},"tool":"neyvia.autopilot.get"},"key":"completed","section":"checks"}
C neyvia.autopilot.get completed:neyvia.autopilot.get(runId:runId) .run.status == "completed"
-- @record {"chapter":"overview","data":{"goal":"Verify that all autopilot asks have executable completion receipts","inputs":{"$cl_type":"t6"},"steps":[{"action":"inspect","args":{"runId":{"$input":"runId"}},"check":"completed","save":"run"}]},"key":"verify-run","section":"procedures"}
P verify-run(runId:str):run=neyvia.autopilot.get(runId:runId) C completed -- Verify that all autopilot asks have executable completion receipts
V P verify-run -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"Interrupted effect or verifier failure","recovery":"Inspect receipt and reconcile; never restart the same write as a new request."},"key":"0","section":"pitfalls"}
X Interrupted effect or verifier failure -> Inspect receipt and reconcile; never restart the same write as a new request.
-- @record {"chapter":"overview","data":{"failure":"Nesting start inside manual.run","recovery":"Call autopilot.start directly through the owning gateway; the controller owns manual execution locks."},"key":"1","section":"pitfalls"}
X Nesting start inside manual.run -> Call autopilot.start directly through the owning gateway; the controller owns manual execution locks.
-- @record {"chapter":"overview","data":"Automatic execution currently supports local observations and saved-source CAS text edits; external/irreversible actions require separate approval.","key":"0","section":"frontier"}
F Automatic execution currently supports local observations and saved-source CAS text edits; external/irreversible actions require separate approval.
-- @record {"chapter":"overview","data":"Quarantined mapping patches are proposed by exploration, never promoted by autopilot.","key":"1","section":"frontier"}
F Quarantined mapping patches are proposed by exploration, never promoted by autopilot.
-- @record {"chapter":"overview","data":"Start with exact scopeTools; scope restricts caller authority and grants nothing.","key":"0","section":"guidance"}
M autopilot "Start with exact scopeTools; scope restricts caller authority and grants nothing." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Luna selects manual procedures and decides explicit JUDGE points; explicit gpt-6.1-sol handles disagreement/frontier.","key":"1","section":"guidance"}
M autopilot "Luna selects manual procedures and decides explicit JUDGE points; explicit gpt-6.1-sol handles disagreement/frontier." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Compiled scripts are reused only for current hashes and identical learned inputs; changed guards return to JUDGE.","key":"2","section":"guidance"}
M autopilot "Compiled scripts are reused only for current hashes and identical learned inputs; changed guards return to JUDGE." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Background runs belong to owner HTTP POST /api/ui/autopilot; tool starts run synchronously.","key":"3","section":"guidance"}
M autopilot "Background runs belong to owner HTTP POST /api/ui/autopilot; tool starts run synchronously." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Same requestId retries return retained state. Stop is cooperative at the next action; poll get/list for proof.","key":"4","section":"guidance"}
M autopilot "Same requestId retries return retained state. Stop is cooperative at the next action; poll get/list for proof." src:"authored manual" state:verified
L autopilot.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t10"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S autopilot.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t11"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" ! -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"autopilot.scopeTools: Unknown scopes are read-only; edit adds only workspace.write","key":"0","section":"guidance"}
M autopilot "autopilot.scopeTools: Unknown scopes are read-only; edit adds only workspace.write" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"autopilot.scopeOf: Only a named CAS workspace.write grants edit scope","key":"1","section":"guidance"}
M autopilot "autopilot.scopeOf: Only a named CAS workspace.write grants edit scope" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"autopilot.attributeCalls: Every observed model call stays visible once, with its measured tokens, and judgement/frontier calls follow item order","key":"2","section":"guidance"}
M autopilot "autopilot.attributeCalls: Every observed model call stays visible once, with its measured tokens, and judgement/frontier calls follow item order" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"autopilot.shapeRun: Item routes preserve receipts; completed manual/script counts and total tokens come only from durable observations","key":"3","section":"guidance"}
M autopilot "autopilot.shapeRun: Item routes preserve receipts; completed manual/script counts and total tokens come only from durable observations" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"autopilot.checkLine: Final verification text names the real tool, target, observed path and exact operation/value","key":"4","section":"guidance"}
M autopilot "autopilot.checkLine: Final verification text names the real tool, target, observed path and exact operation/value" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"5","section":"guidance"}
M autopilot "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
-- @record {"chapter":"overview","section":"guidance","key":"5","data":"Choose only IDs from the current scoped catalog. The host resolves unique normalized aliases, close spelling and exact chapter/procedure ownership, records corrections, and retries one unresolvable selection before effects. Ambiguous or absent routes require a new grounded choice; scope, CAS and acceptance checks still apply."}
M autopilot "Choose only IDs from the current scoped catalog. The host resolves unique normalized aliases, close spelling and exact chapter/procedure ownership, records corrections, and retries one unresolvable selection before effects. Ambiguous or absent routes require a new grounded choice; scope, CAS and acceptance checks still apply." src:"authored manual" state:verified
