CL 1
L awareness v1 -- Authored executable manual
T realbugs0 {agent:str ..}
-- @manual {"chapters":{"overview":{"title":"Work board (who changes which files), impact map, intent checklist"},"prompt-amplification":{"title":"Preserve rough-prompt asks without model tokens"},"proofs-e-release":{"title":"Release and capability observations (PROOFS-e)"},"realbugs-lifecycle":{"title":"Run-scoped exclusive claims and terminal cleanup"}},"clVersion":"1.1","id":"awareness","kind":"environment","proofs":{"area":"awareness","manifests":["config/proofs/proofs-e-release.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.impact":"t1","neyvia.intent.checklist":"t2","neyvia.prompt.amplify":"t3","neyvia.prompt.edit":"t4","neyvia.prompt.get":"t5","neyvia.work.claim":"t6","neyvia.work.list":"t7","neyvia.work.release":"t5","realbugs_work_list":"realbugs0"},"tool_metadata":{"neyvia.impact":{"mutability_class":"none"},"neyvia.intent.checklist":{"mutability_class":"none"},"neyvia.prompt.amplify":{"mutability_class":"artifact_write"},"neyvia.prompt.edit":{"mutability_class":"artifact_write"},"neyvia.prompt.get":{"mutability_class":"read"},"neyvia.work.claim":{"mutability_class":"none"},"neyvia.work.list":{"mutability_class":"read"},"neyvia.work.release":{"mutability_class":"none"}}}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.overlaps","grant_agent.proofs_awareness.check_overlap"],"claim":"Case-insensitive paths overlap only at complete folder/file boundaries; absolute and relative forms match at complete suffix/contained component boundaries.","id":"awareness.paths.overlap","impact":["work board claim collisions","filtered work observer"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.claim inside _FileLock","grant_agent.proofs_awareness.after"],"claim":"A successful new claim persists exactly its agent/chat/intent and normalized unique paths, without changing unrelated claims or release history.","id":"awareness.claim.persisted","impact":[".neyvia/work-board.json","other agents' claimed files"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.claim inside _FileLock","grant_agent.proofs_awareness.after"],"claim":"The same agent/chat/path set refreshes the existing id and original since/files while updating intent and activity timestamp; other claims stay untouched.","id":"awareness.claim.refresh","impact":["claim identity","advisory coordination","stale activity"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.claim inside _FileLock","grant_agent.proofs_awareness.after"],"claim":"The claim receipt includes exactly other agents/chats whose persisted paths overlap the requested paths and includes exactly their shared paths.","id":"awareness.claim.overlaps","impact":["cross-agent coordination","overlap receipts"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.release inside _FileLock","grant_agent.proofs_awareness.after"],"claim":"Release removes exactly the selected active claim and archives it without changing other active entries or the last 29 archived claims; receipt returns removed paths.","id":"awareness.release.persisted","impact":["active claim visibility","recoverable claim history"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.board_list","grant_agent.proofs_awareness.check_list"],"claim":"The observer returns exactly the persisted claims matching files/agent filters, sorted by since, with correct count, stale total and latest five releases.","id":"awareness.list.projection","impact":["work board UI","agent awareness"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_awareness.claim","grant_agent.neyvia_awareness.board_list","grant_agent.proofs_awareness._view_contract"],"claim":"Age derives from the original since timestamp; stale derives from updatedAt (or since) at the 12-hour boundary. Refresh preserves age and makes an old active claim current.","id":"awareness.claim.staleness","impact":["stale work indicators","claim lineage"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_impact.find_gaps","grant_agent.proofs_awareness.check_gaps"],"claim":"UI/handler/bridge/Tauri gap categories equal their exact set relations; handler caller review leads distinguish static scripts/tests from absent callers.","id":"awareness.impact.gaps","impact":["impact review","wiring omissions","dead-code decisions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_impact._command_row","grant_agent.proofs_awareness.check_command"],"claim":"Each command impact receipt exactly projects UI, handler, bridge, Tauri, tests, manuals and missing ends from the real parsed dependency graph.","id":"awareness.impact.command","impact":["changed-file dependency proof","desktop/UI wiring"],"phase":"post"}
-- @proof {"checkedAt":["src/grant_agent/runtime_capability_inventory.py:build_runtime_capability_inventory -> check_runtime_inventory"],"claim":"Capability inventory exports safe readiness metadata, enabled instruction linkage and honest native activation without raw commands, URLs or environment values","id":"runtime.capability-metadata","impact":["awareness production observations"],"phase":"post"}
T t1{paths?:[str] gaps?:bool ..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\"}},\"required\":[\"text\"],\"allOf\":[{\"properties\":{\"text\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\"},\"requestId\":{\"type\":\"string\"},\"sessionId\":{\"type\":\"string\"},\"context\":{\"type\":\"object\"},\"mode\":{\"type\":\"string\",\"enum\":[\"auto\",\"review\"]},\"variant\":{\"type\":\"string\",\"enum\":[\"raw\",\"minimal\",\"full\"]}},\"required\":[\"text\",\"requestId\"],\"allOf\":[{\"properties\":{\"text\":{\"not\":{\"enum\":[\"\"]}},\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"revision\":{\"type\":\"integer\"},\"requestId\":{\"type\":\"string\"},\"text\":{\"type\":\"string\"}},\"required\":[\"id\",\"revision\",\"requestId\",\"text\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"requestId\":{\"not\":{\"enum\":[\"\"]}},\"text\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\",\"properties\":{\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1,\"maxItems\":100},\"intent\":{\"type\":\"string\"},\"agent\":{\"type\":\"string\"},\"chat\":{\"type\":\"string\"},\"app\":{\"type\":\"string\"}},\"required\":[\"files\",\"intent\"],\"allOf\":[{\"properties\":{\"intent\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7{files?:[str] agent?:str ..}
T t8{}
T t9{claims:json:"{\"type\":\"array\"}" count:int stale:int ..}
T t10{claim:{id:str ..} ..}
T t11 json:"{\"type\":\"object\"}"
T t12{files:[str]#1..100 intent:str}
T t13{files:[str]#1..100 intent:str ..}
T t14{id:str ..}
T t15 json:"{\"type\":\"object\",\"properties\":{\"amplification\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}}}}}"
T t16{text:str requestId:str}
L awareness.overview v1 -- Work board (who changes which files), impact map, intent checklist
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.work.list"},"key":"current","section":"state"}
S awareness.current:{claims:json:"{\"type\":\"array\"}" count:int stale:int ..}=neyvia.work.list()
-- @record {"chapter":"overview","data":{"effect":"Read active claims, overlap/staleness metadata; board grants no filesystem permission","pre":"Selected workspace board readable; optional files/agent filters","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.work.list","tool":"neyvia.work.list"},"key":"work.list","section":"actions"}
A neyvia.work.list(files?:[str] agent?:str) -> {claims:json:"{\"type\":\"array\"}" count:int stale:int ..} -- Read active claims, overlap/staleness metadata; board grants no filesystem permission
F verify-work-list "No authored observer check is bound to neyvia.work.list" -> ask operator blocks:neyvia.work.list
-- @record {"chapter":"overview","data":{"effect":"Persist advisory claim and return overlaps; same agent/chat/path set refreshes intent, no requestId field","pre":"1–100 nonblank normalized paths <400 chars; intent 1–300 chars; board capacity <=200; agent/chat identify ownership","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.work.claim","tool":"neyvia.work.claim"},"key":"work.claim","section":"actions"}
A neyvia.work.claim(files:[str]#1..100 intent:str agent?:str chat?:str app?:str) -> {claim:{id:str ..} ..} ! -- Persist advisory claim and return overlaps; same agent/chat/path set refreshes intent, no requestId field
F verify-work-claim "No authored observer check is bound to neyvia.work.claim" -> ask operator blocks:neyvia.work.claim
-- @record {"chapter":"overview","data":{"effect":"Remove active claim, retain newest 30 release receipts; does not revert files or stop worker","pre":"ID from an active claim; already-released IDs are refused","returns":{"$cl_type":"t11"},"reversible":false,"schema":"neyvia.work.release","tool":"neyvia.work.release"},"key":"work.release","section":"actions"}
A neyvia.work.release(id:str) -> json:"{\"type\":\"object\"}" ! -- Remove active claim, retain newest 30 release receipts; does not revert files or stop worker
F verify-work-release "No authored observer check is bound to neyvia.work.release" -> ask operator blocks:neyvia.work.release
-- @record {"chapter":"overview","data":{"effect":"Return command/tool/UI/bridge/test/manual connections and missing wiring; no execution or repair","pre":"Named repository-relative paths; static repository index available","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.impact","tool":"neyvia.impact"},"key":"impact","section":"actions"}
A neyvia.impact(paths?:[str] gaps?:bool) -> json:"{\"type\":\"object\"}" -- Return command/tool/UI/bridge/test/manual connections and missing wiring; no execution or repair
F verify-impact "No authored observer check is bound to neyvia.impact" -> ask operator blocks:neyvia.impact
-- @record {"chapter":"overview","data":{"effect":"Return prompt template and typed checklist schema; model must fill decisions, no hidden model call","pre":"Nonblank dictated text <=40000 chars","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.intent.checklist","tool":"neyvia.intent.checklist"},"key":"intent.checklist","section":"actions"}
A neyvia.intent.checklist(text:str) -> json:"{\"type\":\"object\"}" -- Return prompt template and typed checklist schema; model must fill decisions, no hidden model call
F verify-intent-checklist "No authored observer check is bound to neyvia.intent.checklist" -> ask operator blocks:neyvia.intent.checklist
-- @record {"chapter":"overview","data":{"goal":"Claim intended paths, inspect overlap and wiring, release immediately if ownership conflicts","inputs":{"$cl_type":"t12"},"steps":[{"action":"work.list","args":{},"save":"board"},{"action":"work.claim","args":{"files":{"$input":"files"},"intent":{"$input":"intent"}},"save":"claimed"},{"action":"impact","args":{"paths":{"$input":"files"}},"save":"impact"},{"judge":"overlap"},{"action":"work.release","args":{"id":{"$result":"claimed.claim.id"}},"save":"released","when":{"judge":"overlap","option":"release"}}]},"key":"claim-and-review","section":"procedures"}
P claim-and-review(files:[str]#1..100 intent:str):board=neyvia.work.list(); claimed=neyvia.work.claim(files:files intent:intent); impact=neyvia.impact(paths:files); J overlap=release; released=neyvia.work.release(id:claimed.claim.id) -- Claim intended paths, inspect overlap and wiring, release immediately if ownership conflicts
V P claim-and-review -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t13"},"steps":[{"action":"work.claim","args":{"files":{"$input":"files"},"intent":{"$input":"intent"}},"save":"effect"}]},"key":"verify-effect-work-claim","section":"procedures"}
P verify-effect-work-claim(files:[str]#1..100 intent:str):effect=neyvia.work.claim(files:files intent:intent) -- Verify the actual effect through fresh owning observers
V P verify-effect-work-claim -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t14"},"steps":[{"action":"work.release","args":{"id":{"$input":"id"}},"save":"effect"}]},"key":"verify-effect-work-release","section":"procedures"}
P verify-effect-work-release(id:str):effect=neyvia.work.release(id:id) -- Verify the actual effect through fresh owning observers
V P verify-effect-work-release -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Compare returned overlaps against exact file scope; claims are advisory and do not lock files. Coordinate conflicting ownership before proceed; released claim remains historical.","options":["proceed","release"],"question":"Can this claimed work proceed without conflicting with existing owners?"},"key":"overlap","section":"judge"}
J overlap proceed|release:"Can this claimed work proceed without conflicting with existing owners?" -- Compare returned overlaps against exact file scope; claims are advisory and do not lock files. Coordinate conflicting ownership before proceed; released claim remains historical.
V J overlap -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Read original text and preserve corrections; template is not a completed checklist. Resolve target/authority ambiguity before mutation; local formatting choices need no extra approval.","options":["ready","clarify"],"question":"Does the generated checklist schema leave a decision-changing ambiguity?"},"key":"intent","section":"judge"}
J intent ready|clarify:"Does the generated checklist schema leave a decision-changing ambiguity?" -- Read original text and preserve corrections; template is not a completed checklist. Resolve target/authority ambiguity before mutation; local formatting choices need no extra approval.
V J intent -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Claim overlaps another worker","recovery":"Inspect overlap paths/intent and coordinate; board is not a lock or authorization"},"key":"0","section":"pitfalls"}
X Claim overlaps another worker -> Inspect overlap paths/intent and coordinate; board is not a lock or authorization
-- @record {"chapter":"overview","data":{"failure":"Claim looks old but worker may still be running","recovery":"Check owner evidence; staleness is advisory, never automatically release others"},"key":"1","section":"pitfalls"}
X Claim looks old but worker may still be running -> Check owner evidence; staleness is advisory, never automatically release others
-- @record {"chapter":"overview","data":{"failure":"Impact map reports handler but no UI/bridge/manual","recovery":"Inspect named wiring before claiming complete; static matches do not prove runtime"},"key":"2","section":"pitfalls"}
X Impact map reports handler but no UI/bridge/manual -> Inspect named wiring before claiming complete; static matches do not prove runtime
-- @record {"chapter":"overview","data":{"failure":"Checklist returned prompt/schema only","recovery":"Have model fill schema from actual asks; do not display template as completed plan"},"key":"3","section":"pitfalls"}
X Checklist returned prompt/schema only -> Have model fill schema from actual asks; do not display template as completed plan
-- @record {"chapter":"overview","data":"Runtime-import/dynamic command wiring cannot be established from static impact matching","key":"0","section":"frontier"}
F Runtime-import/dynamic command wiring cannot be established from static impact matching
-- @record {"chapter":"overview","data":"No scheduler or conflict-enforcement mechanism on the advisory board","key":"1","section":"frontier"}
F No scheduler or conflict-enforcement mechanism on the advisory board
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_awareness.py; src/grant_agent/neyvia_impact.py; tests/test_neyvia_awareness.py.","key":"0","section":"guidance"}
M awareness "Source: src/grant_agent/neyvia_awareness.py; src/grant_agent/neyvia_impact.py; tests/test_neyvia_awareness.py." src:"authored manual" state:verified
L awareness.prompt-amplification v1 -- Preserve rough-prompt asks without model tokens
-- @record {"chapter":"prompt-amplification","data":{"args":{"id":{"$input":"id"}},"inputs":{"$cl_type":"t14"},"shape":{"$cl_type":"t11"},"tool":"neyvia.prompt.get"},"key":"saved","section":"state"}
S awareness.saved:json:"{\"type\":\"object\"}"=neyvia.prompt.get(id:id)
-- @record {"chapter":"prompt-amplification","data":{"effect":"Retain original, exact-span checklist and coverage in the card; selected default sends only reversible inline mishear/reference readings; zero model calls","pre":"Selected owner workspace; bounded text; edit requires current revision","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.prompt.amplify","tool":"neyvia.prompt.amplify"},"key":"amplify","section":"actions"}
A neyvia.prompt.amplify(text:str requestId:str sessionId?:str context?:json:"{\"type\":\"object\"}" mode?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"review\"]}" variant?:json:"{\"type\":\"string\",\"enum\":[\"raw\",\"minimal\",\"full\"]}") -> json:"{\"type\":\"object\",\"properties\":{\"amplification\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}}}}}" ! -- Retain original, exact-span checklist and coverage in the card; selected default sends only reversible inline mishear/reference readings; zero model calls
C neyvia.prompt.amplify coverage:neyvia.prompt.get(id:result.amplification.id) .amplification.coverage.ok == true
-- @record {"chapter":"prompt-amplification","data":{"effect":"Read saved prompt revision","pre":"Selected owner workspace; bounded text; edit requires current revision","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.prompt.get","tool":"neyvia.prompt.get"},"key":"get","section":"actions"}
A neyvia.prompt.get(id:str) -> json:"{\"type\":\"object\",\"properties\":{\"amplification\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}}}}}" -- Read saved prompt revision
F verify-get "No authored observer check is bound to neyvia.prompt.get" -> ask operator blocks:neyvia.prompt.get
-- @record {"chapter":"prompt-amplification","data":{"effect":"Save exact owner edit; retain evidence without automatic model drafting","pre":"Selected owner workspace; bounded text; edit requires current revision","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.prompt.edit","tool":"neyvia.prompt.edit"},"key":"edit","section":"actions"}
A neyvia.prompt.edit(id:str revision:int requestId:str text:str) -> json:"{\"type\":\"object\",\"properties\":{\"amplification\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}}}}}" ! -- Save exact owner edit; retain evidence without automatic model drafting
F verify-edit "No authored observer check is bound to neyvia.prompt.edit" -> ask operator blocks:neyvia.prompt.edit
-- @record {"chapter":"prompt-amplification","data":{"args":{"id":{"$result":"prompt.amplification.id"}},"expect":{"op":"eq","path":"amplification.coverage.ok","value":true},"tool":"neyvia.prompt.get"},"key":"coverage","section":"checks"}
C neyvia.prompt.get coverage:neyvia.prompt.get(id:prompt.amplification.id) .amplification.coverage.ok == true
-- @record {"chapter":"prompt-amplification","data":{"goal":"Prepare a lossless reading aid; refuse uncovered sentences","inputs":{"$cl_type":"t16"},"steps":[{"action":"amplify","args":{"requestId":{"$input":"requestId"},"text":{"$input":"text"}},"check":"coverage","save":"prompt"}]},"key":"prepare","section":"procedures"}
P prepare(text:str requestId:str):prompt=neyvia.prompt.amplify(requestId:requestId text:text) C coverage -- Prepare a lossless reading aid; refuse uncovered sentences
V P prepare -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompt-amplification","data":{"failure":"Original sentence has no exact-span item or proven chatter marker","recovery":"Coverage refuses preparation/submission; repair parser without dropping text"},"key":"0","section":"pitfalls"}
X Original sentence has no exact-span item or proven chatter marker -> Coverage refuses preparation/submission; repair parser without dropping text
-- @record {"chapter":"prompt-amplification","data":{"failure":"Costly reference has multiple or no candidates","recovery":"Review target before submission; context grants no permission"},"key":"1","section":"pitfalls"}
X Costly reference has multiple or no candidates -> Review target before submission; context grants no permission
-- @record {"chapter":"prompt-amplification","data":"Conservative spans are reading aids, not proof of semantic interpretation.","key":"0","section":"frontier"}
F Conservative spans are reading aids, not proof of semantic interpretation.
-- @record {"chapter":"prompt-amplification","data":"Model extraction and automatic edit-learning are disabled.","key":"1","section":"frontier"}
F Model extraction and automatic edit-learning are disabled.
-- @record {"chapter":"prompt-amplification","data":"Open files and recent work need bounded supplied context; chat comes from selected broker.","key":"2","section":"frontier"}
F Open files and recent work need bounded supplied context; chat comes from selected broker.
-- @record {"chapter":"prompt-amplification","data":"References outside the bounded chat projection can remain unresolved; a candidate is not an exact target.","key":"3","section":"frontier"}
F References outside the bounded chat projection can remain unresolved; a candidate is not an exact target.
-- @record {"chapter":"prompt-amplification","data":"Original text remains saved verbatim; later corrections affect only named asks.","key":"0","section":"guidance"}
M awareness "Original text remains saved verbatim; later corrections affect only named asks." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"Offsets are Unicode code points. Unknown clauses remain visible context.","key":"1","section":"guidance"}
M awareness "Offsets are Unicode code points. Unknown clauses remain visible context." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"Minimal is the measured C14f default. Agent text contains only original wording with marked heard/ref readings; inlineEdits holds exact source spans and before/after text for reversal.","key":"2","section":"guidance"}
M awareness "Minimal is the measured C14f default. Agent text contains only original wording with marked heard/ref readings; inlineEdits holds exact source spans and before/after text for reversal." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"Checklist, checks, constraints, assumptions, questions and CL context pointers stay in the saved prompt.get record and Paul card; they are not appended on automatic sends.","key":"3","section":"guidance"}
M awareness "Checklist, checks, constraints, assumptions, questions and CL context pointers stay in the saved prompt.get record and Paul card; they are not appended on automatic sends." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"Raw and full remain explicit variant options for audited comparison. Full uses the historical CL reading aid; raw emits the original unchanged.","key":"4","section":"guidance"}
M awareness "Raw and full remain explicit variant options for audited comparison. Full uses the historical CL reading aid; raw emits the original unchanged." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"A trailing not remains a visible card assumption and cannot cancel another explicit ask. Consequential ambiguous targets still block sends.","key":"5","section":"guidance"}
M awareness "A trailing not remains a visible card assumption and cannot cancel another explicit ask. Consequential ambiguous targets still block sends." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"An owner card edit appends only fields Paul explicitly changed and answered questions; unchanged card fields never become prompt overhead.","key":"6","section":"guidance"}
M awareness "An owner card edit appends only fields Paul explicitly changed and answered questions; unchanged card fields never become prompt overhead." src:"authored manual" state:verified
-- @record {"chapter":"prompt-amplification","data":"C14f five tasks twice: strict intent minimal17/raw16/full14 of22; consumer tokens153139/181006/168734. Small reused panel with four unchanged task prompts is not population or causal gain evidence.","key":"7","section":"guidance"}
M awareness "C14f five tasks twice: strict intent minimal17/raw16/full14 of22; consumer tokens153139/181006/168734. Small reused panel with four unchanged task prompts is not population or causal gain evidence." src:"authored manual" state:verified
L awareness.proofs-e-release v1 -- Release and capability observations (PROOFS-e)
-- @record {"chapter":"proofs-e-release","data":{"failure":"Metadata readiness or a scoped proof is mistaken for external execution or a published release","recovery":"Inspect the observed boundary and use the owning real activation or publication procedure"},"key":"0","section":"pitfalls"}
X Metadata readiness or a scoped proof is mistaken for external execution or a published release -> Inspect the observed boundary and use the owning real activation or publication procedure
-- @record {"chapter":"proofs-e-release","data":"No installer build, installation, publication, download or private signing-key provisioning is claimed.","key":"0","section":"frontier"}
F No installer build, installation, publication, download or private signing-key provisioning is claimed.
-- @record {"chapter":"proofs-e-release","data":"Enabled plugin metadata and native instruction linkage do not prove external MCP/plugin execution.","key":"1","section":"frontier"}
F Enabled plugin metadata and native instruction linkage do not prove external MCP/plugin execution.
-- @record {"chapter":"proofs-e-release","data":"The impact index proves static command wiring; it does not execute backend or desktop commands.","key":"2","section":"frontier"}
F The impact index proves static command wiring; it does not execute backend or desktop commands.
-- @record {"chapter":"proofs-e-release","data":"Capability inventory exports safe readiness metadata, enabled instruction linkage and honest native activation without raw commands, URLs or environment values","key":"0","section":"guidance"}
M awareness "Capability inventory exports safe readiness metadata, enabled instruction linkage and honest native activation without raw commands, URLs or environment values" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Self-check: neyvia verify --area proofs-e-release; scoped actual signing, scanner, metadata and static impact actions.","key":"1","section":"guidance"}
M awareness "Self-check: neyvia verify --area proofs-e-release; scoped actual signing, scanner, metadata and static impact actions." src:"authored manual" state:verified
L awareness.realbugs-lifecycle v1 -- Run-scoped exclusive claims and terminal cleanup
-- @record {"chapter":"realbugs-lifecycle","section":"actions","key":"work.list","data":{"effect":"Read the owning lifecycle state from the selected workspace.","pre":"Owned proof session; observer does not launch or cancel any provider.","returns":{"type":"object"},"reversible":true,"schema":"realbugs_work_list","tool":"neyvia.work.list"}}
A neyvia.work.list(agent:str) -> json:"{\"type\":\"object\"}" -- Read the owning lifecycle state from the selected workspace.
C neyvia.work.list live-claim-retained: matches(neyvia.work.list(agent:agent),{properties:{count:{const:1} stale:{const:0}} required:["count" "stale"] type:"object"})
C neyvia.work.list ended-claim-released: neyvia.work.list(agent:agent).count==0
-- @record {"chapter":"realbugs-lifecycle","section":"checks","key":"live-claim-retained","data":{"args":{"agent":{"$input":"agent"}},"expect":{"op":"schema","path":"","schema":{"properties":{"count":{"const":1},"stale":{"const":0}},"required":["count","stale"],"type":"object"}},"tool":"neyvia.work.list"}}
C neyvia.work.list live-claim-retained: matches(neyvia.work.list(agent:agent),{properties:{count:{const:1} stale:{const:0}} required:["count" "stale"] type:"object"})
-- @record {"chapter":"realbugs-lifecycle","section":"checks","key":"ended-claim-released","data":{"args":{"agent":{"$input":"agent"}},"expect":{"op":"eq","path":"count","value":0},"tool":"neyvia.work.list"}}
C neyvia.work.list ended-claim-released: neyvia.work.list(agent:agent).count==0
-- @record {"chapter":"realbugs-lifecycle","section":"procedures","key":"live-claim-retained","data":{"goal":"Run-scoped exclusive claims and terminal cleanup: live-claim-retained","inputs":{"type":"object","properties":{"agent":{"type":"string"}},"required":["agent"]},"steps":[{"action":"work.list","args":{"agent":{"$input":"agent"}},"check":"live-claim-retained","save":"observed"}]}}
P live-claim-retained(agent:str): observed=neyvia.work.list(agent:agent) C live-claim-retained -- Run-scoped exclusive claims and terminal cleanup: live-claim-retained
V P live-claim-retained -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"realbugs-lifecycle","section":"procedures","key":"ended-claim-released","data":{"goal":"Run-scoped exclusive claims and terminal cleanup: ended-claim-released","inputs":{"type":"object","properties":{"agent":{"type":"string"}},"required":["agent"]},"steps":[{"action":"work.list","args":{"agent":{"$input":"agent"}},"check":"ended-claim-released","save":"observed"}]}}
P ended-claim-released(agent:str): observed=neyvia.work.list(agent:agent) C ended-claim-released -- Run-scoped exclusive claims and terminal cleanup: ended-claim-released
V P ended-claim-released -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"0","data":"Run on one isolated real Claude Code terminal session: observe the claim while the parent waits for input, then observe after completed, failed, stopped or process-gone recovery. Live claims remain exclusive."}
M awareness "Run on one isolated real Claude Code terminal session: observe the claim while the parent waits for input, then observe after completed, failed, stopped or process-gone recovery. Live claims remain exclusive." src:"authored manual" state:verified
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"1","data":"Mod and broker edit claims carry runId. Terminal cleanup releases only that run; persisted owner state and PID-start identity expire legacy/dead claims even after restart. Unknown owners retain the 12-hour lease."}
M awareness "Mod and broker edit claims carry runId. Terminal cleanup releases only that run; persisted owner state and PID-start identity expire legacy/dead claims even after restart. Unknown owners retain the 12-hour lease." src:"authored manual" state:verified
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"2","data":"A completed transport or a screenshot is not evidence that a claim was live and then released; retain both observer receipts and the actual provider event trail."}
M awareness "A completed transport or a screenshot is not evidence that a claim was live and then released; retain both observer receipts and the actual provider event trail." src:"authored manual" state:verified
