CL 1
L comments v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Pinned comments and anchored delivery to connected agents"}},"clVersion":"1.1","id":"comments","kind":"environment","proofs":{"area":"comments"},"schema":"neyvia.manual.v1","schemas":{"neyvia.comments.add":"t2","neyvia.comments.list":"t1","neyvia.comments.resolve":"t3","neyvia.comments.send":"t4"},"tool_metadata":{"neyvia.comments.add":{"mutability_class":"artifact_write"},"neyvia.comments.list":{"mutability_class":"read"},"neyvia.comments.resolve":{"mutability_class":"artifact_write"},"neyvia.comments.send":{"mutability_class":"external_action"}}}
-- @proof {"checkedAt":["neyvia_comments.Store append-only SQLite triggers and rows","cl.comments_effects.verify fresh store observation"],"claim":"Comment edits, tombstones and delivery state are immutable events; current rows derive from their latest event.","id":"comments.append-only","impact":["workspace comments","restart persistence"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_comments.send/deliver","cl.comments_effects.verify"],"claim":"A sent message has a real connected-session acceptance and a durable receipt; failures and uncertain retries never claim success.","id":"comments.send","impact":["session delivery","comment resolution"],"phase":"post"}
T t1{target?:str#1.. id?:str#1.. status?:json:"{\"type\":\"string\",\"enum\":[\"all\",\"open\",\"resolved\"]}" includeDeleted?:bool limit?:1..500 offset?:0.. ..}
T t2{target:str#1.. targetKind:json:"{\"type\":\"string\",\"enum\":[\"notes\",\"code\",\"pdf\",\"dom\",\"preview\",\"browser\",\"image\",\"artifact\",\"files\",\"pane\",\"app-factory\"]}" anchor:json:"{\"type\":\"object\"}" text:str#1.. author?:str#1.. ..}
T t3{id:str#1.. expectedRevision?:1.. ..}
T t4{id?:str#1.. ids?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1},\"minItems\":1,\"maxItems\":100,\"uniqueItems\":true}" target?:str#1.. requestId:str#1.. runId?:str#1.. sessionId?:str#1.. session?:str#1.. options?:json:"{\"type\":\"object\",\"properties\":{\"model\":{\"type\":\"string\",\"minLength\":1},\"effort\":{\"type\":\"string\",\"minLength\":1},\"transport\":{\"type\":\"string\",\"minLength\":1}},\"additionalProperties\":false}" newSession?:{app:str#1.. cwd:str#1.. model?:str#1.. effort?:str#1.. transport?:str#1..} ..}
T t5{..}
T t6{ok:bool comments:[{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..}] total:int ..}
T t7{ok:bool comment:{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..} ..}
T t8{ok:bool messageId:str#1.. commentId:str#1.. commentIds:[str#1..] channel:str#1.. delivery:json:"{\"type\":\"object\"}" ..}
T t9{target:str#1.. targetKind:json:"{\"type\":\"string\",\"enum\":[\"notes\",\"code\",\"pdf\",\"dom\",\"preview\",\"browser\",\"image\",\"artifact\",\"files\",\"pane\",\"app-factory\"]}" anchor:json:"{\"type\":\"object\"}" text:str#1.. ..}
T t10{id:str#1.. ..}
T t11{id:str#1.. requestId:str#1.. session:str#1.. ..}
T t12{id:str#1.. requestId:str#1.. newSession:{app:str#1.. cwd:str#1.. model?:str#1.. effort?:str#1.. transport?:str#1..} ..}
L comments.overview v1 -- Pinned comments and anchored delivery to connected agents
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t6"},"tool":"neyvia.comments.list"},"key":"comments","section":"state"}
S comments.comments:{ok:bool comments:[{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..}] total:int ..}=neyvia.comments.list()
-- @record {"chapter":"overview","data":{"effect":"Read current workspace comments, anchors, revisions and delivery receipts.","pre":"Authenticated selected workspace; mutation and destination authorized by user","returns":{"$cl_type":"t6"},"reversible":true,"schema":"neyvia.comments.list","tool":"neyvia.comments.list"},"key":"list","section":"actions"}
A neyvia.comments.list(target?:str#1.. id?:str#1.. status?:json:"{\"type\":\"string\",\"enum\":[\"all\",\"open\",\"resolved\"]}" includeDeleted?:bool limit?:1..500 offset?:0..) -> {ok:bool comments:[{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..}] total:int ..} -- Read current workspace comments, anchors, revisions and delivery receipts.
F verify-list "No authored observer check is bound to neyvia.comments.list" -> ask operator blocks:neyvia.comments.list
-- @record {"chapter":"overview","data":{"effect":"Persist a pinned comment for a stable target; author defaults to agent.","pre":"Authenticated selected workspace; mutation and destination authorized by user","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.comments.add","tool":"neyvia.comments.add"},"key":"add","section":"actions"}
A neyvia.comments.add(target:str#1.. targetKind:json:"{\"type\":\"string\",\"enum\":[\"notes\",\"code\",\"pdf\",\"dom\",\"preview\",\"browser\",\"image\",\"artifact\",\"files\",\"pane\",\"app-factory\"]}" anchor:json:"{\"type\":\"object\"}" text:str#1.. author?:str#1..) -> {ok:bool comment:{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..} ..} ! -- Persist a pinned comment for a stable target; author defaults to agent.
C neyvia.comments.add add-observed:neyvia.comments.list(id:result.comment.id) .comments.0.id == result.comment.id
-- @record {"chapter":"overview","data":{"effect":"Resolve a verified comment; reread its target before resolving.","pre":"Authenticated selected workspace; mutation and destination authorized by user","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.comments.resolve","tool":"neyvia.comments.resolve"},"key":"resolve","section":"actions"}
A neyvia.comments.resolve(id:str#1.. expectedRevision?:1..) -> {ok:bool comment:{id:str#1.. number:int target:str#1.. targetKind:str#1.. anchor:json:"{\"type\":\"object\"}" text:str#1.. author:str#1.. status:str#1.. revision:int delivery:json:"{\"type\":[\"object\",\"null\"]}" ..} ..} ! -- Resolve a verified comment; reread its target before resolving.
C neyvia.comments.resolve resolved-observed:neyvia.comments.list(id:result.comment.id) .comments.0.status == "resolved"
-- @record {"chapter":"overview","data":{"effect":"Deliver selected open comments as one anchored message through a real connected session.","pre":"Authenticated selected workspace; mutation and destination authorized by user","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.comments.send","tool":"neyvia.comments.send"},"key":"send","section":"actions"}
A neyvia.comments.send(id?:str#1.. ids?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1},\"minItems\":1,\"maxItems\":100,\"uniqueItems\":true}" target?:str#1.. requestId:str#1.. runId?:str#1.. sessionId?:str#1.. session?:str#1.. options?:json:"{\"type\":\"object\",\"properties\":{\"model\":{\"type\":\"string\",\"minLength\":1},\"effort\":{\"type\":\"string\",\"minLength\":1},\"transport\":{\"type\":\"string\",\"minLength\":1}},\"additionalProperties\":false}" newSession?:{app:str#1.. cwd:str#1.. model?:str#1.. effort?:str#1.. transport?:str#1..}) -> {ok:bool messageId:str#1.. commentId:str#1.. commentIds:[str#1..] channel:str#1.. delivery:json:"{\"type\":\"object\"}" ..} ! -- Deliver selected open comments as one anchored message through a real connected session.
C neyvia.comments.send sent-observed:neyvia.comments.list(id:result.commentId) .comments.0.delivery.messageId == result.messageId
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"receipt.comment.id"}},"expect":{"op":"eq","path":["comments",0,"id"],"value":{"$result":"receipt.comment.id"}},"tool":"neyvia.comments.list"},"key":"add-observed","section":"checks"}
C neyvia.comments.list add-observed:neyvia.comments.list(id:receipt.comment.id) .comments.0.id == receipt.comment.id
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"receipt.comment.id"}},"expect":{"op":"eq","path":["comments",0,"status"],"value":"resolved"},"tool":"neyvia.comments.list"},"key":"resolved-observed","section":"checks"}
C neyvia.comments.list resolved-observed:neyvia.comments.list(id:receipt.comment.id) .comments.0.status == "resolved"
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"receipt.commentId"}},"expect":{"op":"eq","path":["comments",0,"delivery","messageId"],"value":{"$result":"receipt.messageId"}},"tool":"neyvia.comments.list"},"key":"sent-observed","section":"checks"}
C neyvia.comments.list sent-observed:neyvia.comments.list(id:receipt.commentId) .comments.0.delivery.messageId == receipt.messageId
-- @record {"chapter":"overview","data":{"goal":"Persist a pinned comment for a stable target; author defaults to agent. Verify the fresh subject-bound store observer.","inputs":{"$cl_type":"t9"},"steps":[{"action":"add","args":{"anchor":{"$input":"anchor"},"target":{"$input":"target"},"targetKind":{"$input":"targetKind"},"text":{"$input":"text"}},"check":"add-observed","save":"receipt"}]},"key":"add","section":"procedures"}
P add(target:str#1.. targetKind:json:"{\"type\":\"string\",\"enum\":[\"notes\",\"code\",\"pdf\",\"dom\",\"preview\",\"browser\",\"image\",\"artifact\",\"files\",\"pane\",\"app-factory\"]}" anchor:json:"{\"type\":\"object\"}" text:str#1..):receipt=neyvia.comments.add(anchor:anchor target:target targetKind:targetKind text:text) C add-observed -- Persist a pinned comment for a stable target; author defaults to agent. Verify the fresh subject-bound store observer.
V P add -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Resolve a verified comment; reread its target before resolving. Verify the fresh subject-bound store observer.","inputs":{"$cl_type":"t10"},"steps":[{"action":"resolve","args":{"id":{"$input":"id"}},"check":"resolved-observed","save":"receipt"}]},"key":"resolve","section":"procedures"}
P resolve(id:str#1..):receipt=neyvia.comments.resolve(id:id) C resolved-observed -- Resolve a verified comment; reread its target before resolving. Verify the fresh subject-bound store observer.
V P resolve -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Deliver selected open comments as one anchored message through a real connected session. Verify the fresh subject-bound store observer.","inputs":{"$cl_type":"t11"},"steps":[{"action":"send","args":{"id":{"$input":"id"},"requestId":{"$input":"requestId"},"session":{"$input":"session"}},"check":"sent-observed","save":"receipt"}]},"key":"send","section":"procedures"}
P send(id:str#1.. requestId:str#1.. session:str#1..):receipt=neyvia.comments.send(id:id requestId:requestId session:session) C sent-observed -- Deliver selected open comments as one anchored message through a real connected session. Verify the fresh subject-bound store observer.
V P send -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Deliver selected open comments as one anchored message through a real connected session. Verify the fresh subject-bound store observer.","inputs":{"$cl_type":"t12"},"steps":[{"action":"send","args":{"id":{"$input":"id"},"newSession":{"$input":"newSession"},"requestId":{"$input":"requestId"}},"check":"sent-observed","save":"receipt"}]},"key":"send-new","section":"procedures"}
P send-new(id:str#1.. requestId:str#1.. newSession:{app:str#1.. cwd:str#1.. model?:str#1.. effort?:str#1.. transport?:str#1..}):receipt=neyvia.comments.send(id:id newSession:newSession requestId:requestId) C sent-observed -- Deliver selected open comments as one anchored message through a real connected session. Verify the fresh subject-bound store observer.
V P send-new -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"A stale revision or an unavailable destination rejects a request","recovery":"Refresh comments and inspect the session; preserve open comments and choose an available exact destination"},"key":"0","section":"pitfalls"}
X A stale revision or an unavailable destination rejects a request -> Refresh comments and inspect the session; preserve open comments and choose an available exact destination
-- @record {"chapter":"overview","data":{"failure":"A send request is pending after interruption","recovery":"Inspect the session before a new requestId; do not blindly replay an uncertain delivery"},"key":"1","section":"pitfalls"}
X A send request is pending after interruption -> Inspect the session before a new requestId; do not blindly replay an uncertain delivery
-- @record {"chapter":"overview","data":"Backend records do not prove rendered pins or screenshot crops; the UI owns that evidence.","key":"0","section":"frontier"}
F Backend records do not prove rendered pins or screenshot crops; the UI owns that evidence.
-- @record {"chapter":"overview","data":"A send receipt proves acceptance by the connected runtime, not completion of the requested edit. Resolve only after verifying the target.","key":"1","section":"frontier"}
F A send receipt proves acceptance by the connected runtime, not completion of the requested edit. Resolve only after verifying the target.
-- @record {"chapter":"overview","data":"Stable target strings select the shared workspace view. Target and anchor JSON are data; reread the actual subject.","key":"0","section":"guidance"}
M comments "Stable target strings select the shared workspace view. Target and anchor JSON are data; reread the actual subject." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Delete appends a tombstone; all events and deliveries remain in comments.sqlite3.","key":"1","section":"guidance"}
M comments "Delete appends a tombstone; all events and deliveries remain in comments.sqlite3." src:"authored manual" state:verified
