CL 1
L computer-use v1 -- Authored executable manual
-- @manual {"chapters":{"adaptation":{"title":"C1: first-use adaptation and verified background flows"},"deadline-driver":{"title":"C1b: bounded native observation and verified delivery"},"drive":{"title":"Drive a native Windows app in the background through the computer-use driver (cua-driver tool shape), with Paul watching in the preview"},"private-journey":{"title":"Integrated private-desktop journey: open an allowed app on the agent desktop, perceive it, type and click, verify each effect"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"proofs-e-wz":{"title":"PROOFS-e W-Z: live contracts and scratch self-checks"},"test-loop":{"title":"The test loop: build, launch, drive and check the app while Paul pokes at it in the same preview, then continue from what he did"}},"clVersion":"1.1","id":"computer-use","kind":"environment","proofs":{"area":"computer-use","manifests":["config/proofs/proofs-e-models.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.cua.action":"t1","neyvia.cua.adapt":"t2","neyvia.cua.capture":"t3","neyvia.cua.flow":"t4","neyvia.cua.inspect":"t5","neyvia.cua.log":"t6","neyvia.cua.state":"t7","neyvia.cua.verify":"t8","neyvia.cua.wait":"t9","neyvia.cua.windows":"t10","neyvia.pane.show":"live_schema_30","proofs-e-models.status":"t12"},"tool_metadata":{"neyvia.cua.action":{"mutability_class":"external_action"},"neyvia.cua.adapt":{"mutability_class":"artifact_write"},"neyvia.cua.flow":{"mutability_class":"external_action"},"neyvia.cua.inspect":{"mutability_class":"read"},"neyvia.cua.log":{"mutability_class":"read"},"neyvia.cua.wait":{"mutability_class":"read"},"neyvia.pane.show":{"mutability_class":"none"},"neyvia.verify.status":{"mutability_class":"none"}}}
T live_schema_30 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str ..}
T live_schema_29 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:toCapture -> checkedProofsEModel"],"claim":"Frame clicks map from shown pixels to capture pixels and outside/empty frames are refused","id":"cua.toCapture","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:keyToInput -> checkedProofsEModel"],"claim":"Characters, named keys and chords retain exact modifiers; dead/modifier keys never send input","id":"cua.keyToInput","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:wheelToScroll -> checkedProofsEModel"],"claim":"Dominant axis determines direction; gesture amount is 1â€“10 lines with pixel/line/page conversion","id":"cua.wheelToScroll","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:elementAt -> checkedProofsEModel"],"claim":"Choose the smallest containing observed element, preserve first match on equal area","id":"cua.elementAt","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:pickSession -> checkedProofsEModel"],"claim":"Named sessions must exist; otherwise the most recent live session wins, with ended fallback","id":"cua.pickSession","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxCuaModel.js:mergeLog -> checkedProofsEModel"],"claim":"Updates preserve entry identity and data; new rows are sequence sorted and bounded","id":"cua.mergeLog","impact":["cua frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.subprocess_utils.hidden_windows_subprocess_kwargs","grant_agent.proofs_e_wz.check_hidden_kwargs","grant_agent.proofs_e_wz.self_check"],"claim":"Windows background process options include CREATE_NO_WINDOW, optional process group and hidden startup info; non-Windows receives no Windows kwargs.","id":"proofs-e-wz.hidden-options","impact":["owned child processes","console-window behavior"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.subprocess_utils._hidden_popen_init","grant_agent.proofs_e_wz.check_spawn_flags","grant_agent.proofs_e_wz.self_check","grant_agent.subprocess_utils.install_hidden_subprocess_default"],"claim":"Every Popen invocation through the installed Windows safety net receives CREATE_NO_WINDOW when flags are missing/zero, while explicit keyword/positional flags and other arguments remain exact; installation is idempotent and off Windows does nothing.","id":"proofs-e-wz.hidden-default","impact":["all Popen-based background launchers","interactive login consoles"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cua_upstream.runtime_status","grant_agent.cua_upstream.install_runtime","scripts/uifix2_contracts.py:c2_cua_helper_plain_and_shared"],"claim":"The screen-control helper resolves from NEYVIA_CUA_DRIVER_DIR, the shared per-user runtime, then the checkout; a missing helper is reported in plain words with a hash-checked setup offer and never staged unverified","id":"cua.helper-resolution","impact":["Preview pane setup state","UpstreamDriver start","LAYA driver readiness"],"phase":"post"}
T t1{sessionId?:str tool:json:"{\"type\":\"string\",\"enum\":[\"click\",\"double_click\",\"right_click\",\"type_text\",\"press_key\",\"hotkey\",\"scroll\",\"drag\",\"set_value\",\"invoke_menu\",\"launch_app\"]}" args:json:"{\"type\":\"object\"}" ..}
T t2{sessionId?:str window_id:int visual?:bool ..}
T t3{sessionId?:str window_id:int ..}
T t4{sessionId?:str window_id:int steps:[{selector:json:"{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"automationId\":{\"type\":\"string\"},\"className\":{\"type\":\"string\"}},\"minProperties\":1,\"additionalProperties\":false}" tool:"click"|"type_text"|"set_value"|"press_key"|"scroll" args?:json:"{\"type\":\"object\"}" expect:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":8}"}]#1..16 ..}
T t5{sessionId?:str window_id:int query?:str diff_only?:bool previousHandle?:str reset?:bool max_elements?:1..2000 ..}
T t6 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"since_seq\":{\"type\":\"integer\",\"minimum\":0}}}"
T t7 json:"{\"type\":\"object\",\"properties\":{}}"
T t8{sessionId?:str window_id:int expect:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":8}" timeout_ms?:0..10000 ..}
T t9{sessionId?:str timeout_ms:0..600000 ..}
T t10 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"}}}"
T t11{kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
T t12{..}
T t13{sessionId:str window_id:int}
T t14 json:"{\"type\":\"object\"}"
T t15{}
T t16{driver:json:"{\"type\":\"object\"}" sessions:json:"{\"type\":\"array\"}" ..}
T t17{windows:json:"{\"type\":\"array\"}" ..}
T t18{pid:int window_id:int capture_id?:str elements?:json:"{\"type\":\"array\"}" element_count?:int ..}
T t19{effect:json:"{\"type\":\"string\",\"enum\":[\"confirmed\",\"partial\",\"unverifiable\",\"suspected_noop\",\"refused\"]}" route:str delivery?:json:"{\"type\":\"object\"}" evidence?:json:"{\"type\":\"array\"}" summary?:str error?:json:"{\"type\":\"object\"}" escalation?:json:"{\"type\":\"object\"}" ..}
T t20 json:"{\"type\":\"object\",\"properties\":{\"control\":{\"type\":\"string\"},\"note\":{\"type\":\"string\"},\"paulActions\":{\"type\":\"array\"},\"timedOut\":{\"type\":\"boolean\"}}}"
T t21{session?:str entries:json:"{\"type\":\"array\"}" next_seq:int ..}
T t22{window_id:int element_token:str label:str expected:str role?:str=""}
T t23{path:str}
T t24{window_id:int text:str label:str typed:str role?:str="Edit"}
T t25{window_id:int button:str label:str composed:str role?:str="Edit"}
T t26{ok:bool ..}
T t27 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
T t28{app:str window_id:int label:str expected:str role?:str=""}
L computer-use.adaptation v1 -- C1: first-use adaptation and verified background flows
-- @record {"chapter":"adaptation","data":{"args":{"sessionId":{"$input":"sessionId"},"window_id":{"$input":"window_id"}},"inputs":{"$cl_type":"t13"},"shape":{"$cl_type":"t14"},"tool":"neyvia.cua.inspect"},"key":"window","section":"state"}
S computer-use.window:json:"{\"type\":\"object\"}"=neyvia.cua.inspect(sessionId:sessionId window_id:window_id)
-- @record {"chapter":"adaptation","data":{"effect":"Read-only probing writes a quarantined CL draft; visual=true invokes T18 only for poor UIA","pre":"Owner-approved active CUA session and one allowed window","returns":{"$cl_type":"t14"},"reversible":true,"schema":"neyvia.cua.adapt","tool":"neyvia.cua.adapt"},"key":"adapt","section":"actions"}
A neyvia.cua.adapt(sessionId?:str window_id:int visual?:bool) -> json:"{\"type\":\"object\"}" ! -- Read-only probing writes a quarantined CL draft; visual=true invokes T18 only for poor UIA
F verify-adapt "No authored observer check is bound to neyvia.cua.adapt" -> ask operator blocks:neyvia.cua.adapt
-- @record {"chapter":"adaptation","data":{"effect":"Resolve fresh unique controls, act and check every step; promote verified use locally; compile after three grounded runs","pre":"Owner-approved active CUA session and one allowed window","returns":{"$cl_type":"t14"},"reversible":false,"schema":"neyvia.cua.flow","tool":"neyvia.cua.flow"},"key":"flow","section":"actions"}
A neyvia.cua.flow(sessionId?:str window_id:int steps:[{selector:json:"{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"automationId\":{\"type\":\"string\"},\"className\":{\"type\":\"string\"}},\"minProperties\":1,\"additionalProperties\":false}" tool:"click"|"type_text"|"set_value"|"press_key"|"scroll" args?:json:"{\"type\":\"object\"}" expect:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":8}"}]#1..16) -> json:"{\"type\":\"object\"}" ! -- Resolve fresh unique controls, act and check every step; promote verified use locally; compile after three grounded runs
F verify-flow "No authored observer check is bound to neyvia.cua.flow" -> ask operator blocks:neyvia.cua.flow
-- @record {"chapter":"adaptation","data":{"failure":"Selector is missing or ambiguous","recovery":"Inspect again and choose a unique role/label/automationId/className selector"},"key":"0","section":"pitfalls"}
X Selector is missing or ambiguous -> Inspect again and choose a unique role/label/automationId/className selector
-- @record {"chapter":"adaptation","data":{"failure":"Action outcome is unknown or explicit preview takeover occurred","recovery":"Stop; inspect actual state before any deliberate retry"},"key":"1","section":"pitfalls"}
X Action outcome is unknown or explicit preview takeover occurred -> Stop; inspect actual state before any deliberate retry
-- @record {"chapter":"adaptation","data":{"failure":"Opaque coordinates lack a matching captured frame","recovery":"Use adapt visual=true or capture; refresh changed pixels; opaque actions retain approval"},"key":"2","section":"pitfalls"}
X Opaque coordinates lack a matching captured frame -> Use adapt visual=true or capture; refresh changed pixels; opaque actions retain approval
-- @record {"chapter":"adaptation","data":"C11g (scripts/evidence/C11g.json) meets the local latency and breadth targets: 15 different applications each completed a learned zero-token task, 12 of 12 gates passed, native atomic p50 was 114 ms including sent failures and accepted runs had zero input disturbance. Matched competitor arms are prepared in scripts/C1-comparison-run.json but their provider arms have not been executed, so no comparative claim stands","key":"0","section":"frontier"}
F C11g (scripts/evidence/C11g.json) meets the local latency and breadth targets: 15 different applications each completed a learned zero-token task, 12 of 12 gates passed, native atomic p50 was 114 ms including sent failures and accepted runs had zero input disturbance. Matched competitor arms are prepared in scripts/C1-comparison-run.json but their provider arms have not been executed, so no comparative claim stands
-- @record {"chapter":"adaptation","data":"Apps that reject background messages retain their native refusal. Isolated native foreground fallback and SendInput are disabled; model arguments and owner foreground flags cannot enable them.","key":"1","section":"frontier"}
F Apps that reject background messages retain their native refusal. Isolated native foreground fallback and SendInput are disabled; model arguments and owner foreground flags cannot enable them.
-- @record {"chapter":"adaptation","data":"Visual extraction is model-dependent and may be slow or unavailable","key":"2","section":"frontier"}
F Visual extraction is model-dependent and may be slow or unavailable
-- @record {"chapter":"adaptation","data":"Flow steps use selector/tool/args/expect. UIA checks: element.selector plus value_equals, label_equals, enabled_equals or exists.","key":"0","section":"guidance"}
M computer-use "Flow steps use selector/tool/args/expect. UIA checks: element.selector plus value_equals, label_equals, enabled_equals or exists." src:"authored manual" state:verified
-- @record {"chapter":"adaptation","data":"Visual checks use visual.text_contains; uncertain OCR never verifies success. Exact captured pixels must remain unchanged across extraction.","key":"1","section":"guidance"}
M computer-use "Visual checks use visual.text_contains; uncertain OCR never verifies success. Exact captured pixels must remain unchanged across extraction." src:"authored manual" state:verified
-- @record {"chapter":"adaptation","data":"The first successful use promotes the quarantined workspace draft. Later calls use manual.run; after three verified traces, manual.compile and manual.script.run take over.","key":"2","section":"guidance"}
M computer-use "The first successful use promotes the quarantined workspace draft. Later calls use manual.run; after three verified traces, manual.compile and manual.script.run take over." src:"authored manual" state:verified
-- @record {"chapter":"adaptation","data":"Tools: neyvia.cua.adapt, neyvia.cua.flow; backend/desktop: cua_adapt_command, cua_flow_command; MCP: adapt_app, run_flow.","key":"3","section":"guidance"}
M computer-use "Tools: neyvia.cua.adapt, neyvia.cua.flow; backend/desktop: cua_adapt_command, cua_flow_command; MCP: adapt_app, run_flow." src:"authored manual" state:verified
L computer-use.deadline-driver v1 -- C1b: bounded native observation and verified delivery
-- @record {"chapter":"deadline-driver","data":{"args":{"sessionId":{"$input":"sessionId"},"window_id":{"$input":"window_id"}},"inputs":{"$cl_type":"t13"},"shape":{"$cl_type":"t14"},"tool":"neyvia.cua.inspect"},"key":"window","section":"state"}
S computer-use.window:json:"{\"type\":\"object\"}"=neyvia.cua.inspect(sessionId:sessionId window_id:window_id)
-- @record {"chapter":"deadline-driver","data":{"failure":"UIA provider does not return by its deadline","recovery":"Use admitted Win32/MSAA controls; resolve new fallback tokens. No desktop-root search or process cleanup."},"key":"0","section":"pitfalls"}
X UIA provider does not return by its deadline -> Use admitted Win32/MSAA controls; resolve new fallback tokens. No desktop-root search or process cleanup.
-- @record {"chapter":"deadline-driver","data":{"failure":"A dispatched action times out","recovery":"Do not send another action. Wait for its native lane to finish and verify actual state before a deliberate retry."},"key":"1","section":"pitfalls"}
X A dispatched action times out -> Do not send another action. Wait for its native lane to finish and verify actual state before a deliberate retry.
-- @record {"chapter":"deadline-driver","data":{"failure":"Input desktop differs from the process desktop","recovery":"Background actions require the isolated native driver and an input-desktop attribution guard. Foreground input is disabled; an unavailable guard refuses launch or action."},"key":"2","section":"pitfalls"}
X Input desktop differs from the process desktop -> Background actions require the isolated native driver and an input-desktop attribution guard. Foreground input is disabled; an unavailable guard refuses launch or action.
-- @record {"chapter":"deadline-driver","data":{"failure":"Field protection metadata is missing or a field became disabled/read-only","recovery":"Unknown metadata refuses unbound fields. A token-labelled, job-owned disposable document has its own file identity scope; known password, disabled and read-only fields still refuse. Never infer ownership from an old token."},"key":"3","section":"pitfalls"}
X Field protection metadata is missing or a field became disabled/read-only -> Unknown metadata refuses unbound fields. A token-labelled, job-owned disposable document has its own file identity scope; known password, disabled and read-only fields still refuse. Never infer ownership from an old token.
-- @record {"chapter":"deadline-driver","data":"C1b breadth, atomic latency and active-desktop preservation are proven by C11g on local disposable targets; its 3 historical guard-failure records are retained and the whole-session guard flag stays false, so a passing final run does not erase them","key":"0","section":"frontier"}
F C1b breadth, atomic latency and active-desktop preservation are proven by C11g on local disposable targets; its 3 historical guard-failure records are retained and the whole-session guard flag stays false, so a passing final run does not erase them
-- @record {"chapter":"deadline-driver","data":"Real UIA cached-pattern/event-diff, general MSAA traversal and T18 model fallback require their own native runs. Isolated native SendInput is disabled.","key":"1","section":"frontier"}
F Real UIA cached-pattern/event-diff, general MSAA traversal and T18 model fallback require their own native runs. Isolated native SendInput is disabled.
-- @record {"chapter":"deadline-driver","data":"T18 image-to-CL remains the existing explicit visual adaptation route; this change proves bounded PrintWindow capture, not an automatic model decision.","key":"2","section":"frontier"}
F T18 image-to-CL remains the existing explicit visual adaptation route; this change proves bounded PrintWindow capture, not an automatic model decision.
-- @record {"chapter":"deadline-driver","data":"A Bureau launch needs a unique new window, token ownership and verified membership on a noncurrent virtual desktop before action admission. Windows may refuse Shell view registration for contained windows; this is an isolation-unavailable frontier, not missing owner permission. Never show a window on the input desktop or reuse an existing singleton to bypass it.","key":"3","section":"frontier"}
F A Bureau launch needs a unique new window, token ownership and verified membership on a noncurrent virtual desktop before action admission. Windows may refuse Shell view registration for contained windows; this is an isolation-unavailable frontier, not missing owner permission. Never show a window on the input desktop or reuse an existing singleton to bypass it.
-- @record {"chapter":"deadline-driver","data":"C11f (nine apps, four learned flows) is superseded by C11g (15 apps). C11g re-enables visibility diagnostics and proves inactive Bureau placement on Explorer Default even when input is Screen-saver. Calculator CoreWindow lacks injected hook coverage and is refused; shared broker adoption and general Office rendered preview remain unproven. The 15 apps are COM/headless application-native flows plus private UIA/CDP on local disposable targets; that is not universal pixel interaction, and apps that reject background messages keep their native refusal.","key":"4","section":"frontier"}
F C11f (nine apps, four learned flows) is superseded by C11g (15 apps). C11g re-enables visibility diagnostics and proves inactive Bureau placement on Explorer Default even when input is Screen-saver. Calculator CoreWindow lacks injected hook coverage and is refused; shared broker adoption and general Office rendered preview remain unproven. The 15 apps are COM/headless application-native flows plus private UIA/CDP on local disposable targets; that is not universal pixel interaction, and apps that reject background messages keep their native refusal.
-- @record {"chapter":"deadline-driver","data":"Windows discovery uses EnumWindows and skips IsHungAppWindow. A persistent in-process MTA UIA client uses ConnectionTimeout 50 ms and TransactionTimeout 80 ms.","key":"0","section":"guidance"}
M computer-use "Windows discovery uses EnumWindows and skips IsHungAppWindow. A persistent in-process MTA UIA client uses ConnectionTimeout 50 ms and TransactionTimeout 80 ms." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Every UIA/MSAA call runs in a single bounded lane. A busy lane rejects new work immediately; no growing worker pool or PowerShell action process.","key":"1","section":"guidance"}
M computer-use "Every UIA/MSAA call runs in a single bounded lane. A busy lane rejects new work immediately; no growing worker pool or PowerShell action process." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Target-scoped CacheRequest snapshots keep properties and patterns. Property events update cached nodes; structure events refresh only their changed branch. Event buffering is bounded.","key":"2","section":"guidance"}
M computer-use "Target-scoped CacheRequest snapshots keep properties and patterns. Property events update cached nodes; structure events refresh only their changed branch. Event buffering is bounded." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Isolated native routing uses cached UI Automation patterns, admitted background native messages or MSAA. Foreground input and SendInput are disabled regardless of session flags.","key":"3","section":"guidance"}
M computer-use "Isolated native routing uses cached UI Automation patterns, admitted background native messages or MSAA. Foreground input and SendInput are disabled regardless of session flags." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Paul's physical input remains independent of isolated native actions. Explicit preview Take over pauses this session; Give back resumes it with the user's note.","key":"4","section":"guidance"}
M computer-use "Paul's physical input remains independent of isolated native actions. Explicit preview Take over pauses this session; Give back resumes it with the user's note." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Observation source, nativeRevision, nativeDiff and degradedReason describe the actual route. Win32 readback and application file effects establish native results.","key":"5","section":"guidance"}
M computer-use "Observation source, nativeRevision, nativeDiff and degradedReason describe the actual route. Win32 readback and application file effects establish native results." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"No new public command: existing cua.inspect/action/verify/adapt/flow and preview APIs use the same NativeWorker facade. cycle is an internal benchmark/native operation.","key":"6","section":"guidance"}
M computer-use "No new public command: existing cua.inspect/action/verify/adapt/flow and preview APIs use the same NativeWorker facade. cycle is an internal benchmark/native operation." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Create a fresh task-local target whose path contains a random 32-character hexadecimal token. launch_app args may include disposable_target {path,token}; the driver binds it only after independent new-window job/desktop ownership and an observed token in its title. Existing broker windows cannot be adopted by this argument.","key":"7","section":"guidance"}
M computer-use "Create a fresh task-local target whose path contains a random 32-character hexadecimal token. launch_app args may include disposable_target {path,token}; the driver binds it only after independent new-window job/desktop ownership and an observed token in its title. Existing broker windows cannot be adopted by this argument." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Fresh Chrome, Edge and VS Code profiles may expose a task-reserved CDP endpoint on an explicit owned port. The DOM route verifies the local document URL or the token-bearing VS Code page before every evaluation, changes real fields, dispatches their application events and reads fresh values. It never attaches to a user's profile or sends desktop input.","key":"8","section":"guidance"}
M computer-use "Fresh Chrome, Edge and VS Code profiles may expose a task-reserved CDP endpoint on an explicit owned port. The DOM route verifies the local document URL or the token-bearing VS Code page before every evaluation, changes real fields, dispatches their application events and reads fresh values. It never attaches to a user's profile or sends desktop input." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"The native fallback projects actual SysTreeView32 items and owned menu commands. Tree expansion and selection use bounded native messages and fresh affected-item readback; MSAA tree/list roles remain distinct from generic controls.","key":"9","section":"guidance"}
M computer-use "The native fallback projects actual SysTreeView32 items and owned menu commands. Tree expansion and selection use bounded native messages and fresh affected-item readback; MSAA tree/list roles remain distinct from generic controls." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"The active task panel is config/cua-everyday-tasks.json. It excludes system administration; older frozen panels are historical receipts only. Use disposable notes, generated images, documents and local files.","key":"10","section":"guidance"}
M computer-use "The active task panel is config/cua-everyday-tasks.json. It excludes system administration; older frozen panels are historical receipts only. Use disposable notes, generated images, documents and local files." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Brokered installed binaries have an explicit Bureau route, suspended job launch and a before-launch HWND inventory. Admit only new owned HWNDs with verified noncurrent membership; never adopt an existing user window or activate an uncontained alias. Explorer /n receives a token-named disposable folder and /separate; shared broker HWND ownership remains unproven.","key":"11","section":"guidance"}
M computer-use "Brokered installed binaries have an explicit Bureau route, suspended job launch and a before-launch HWND inventory. Admit only new owned HWNDs with verified noncurrent membership; never adopt an existing user window or activate an uncontained alias. Explorer /n receives a token-named disposable folder and /separate; shared broker HWND ownership remains unproven." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Notepad skips when an existing instance could reuse a user window. Paint and Calculator use installed binaries and a new owned process; a hidden launch does not prove Bureau membership.","key":"12","section":"guidance"}
M computer-use "Notepad skips when an existing instance could reuse a user window. Paint and Calculator use installed binaries and a new owned process; a hidden launch does not prove Bureau membership." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Office tasks use a new hidden COM instance with PID/birth ownership and save/reopen/package checks. Registered neyvia.nativeapp.open/edit/persist/observe/close drive the native-applications manual. Three grounded runs feed manual.compile; replay uses manual.script.run with fresh checks and zero model tokens. These are application-native tool flows, not UIA or pixel workflows.","key":"13","section":"guidance"}
M computer-use "Office tasks use a new hidden COM instance with PID/birth ownership and save/reopen/package checks. Registered neyvia.nativeapp.open/edit/persist/observe/close drive the native-applications manual. Three grounded runs feed manual.compile; replay uses manual.script.run with fresh checks and zero model tokens. These are application-native tool flows, not UIA or pixel workflows." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"scripts/prove_c11f_shell.py performs actual CREATE_NO_WINDOW file tasks with independent file and ZIP readback. It cannot change system configuration. C11f.json records these lanes separately from the native manual-compiler cohort.","key":"14","section":"guidance"}
M computer-use "scripts/prove_c11f_shell.py performs actual CREATE_NO_WINDOW file tasks with independent file and ZIP readback. It cannot change system configuration. C11f.json records these lanes separately from the native manual-compiler cohort." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Bureau uses Explorer Default, not the current input desktop, which can be Screen-saver. The guard observes both desktops continuously. Private desktop windows need no lease. Only a new owned HWND receives one nonrenewable move lease, capped at three seconds.","key":"15","section":"guidance"}
M computer-use "Bureau uses Explorer Default, not the current input desktop, which can be Screen-saver. The guard observes both desktops continuously. Private desktop windows need no lease. Only a new owned HWND receives one nonrenewable move lease, capped at three seconds." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"New Bureau windows are held hidden before launch resumes. Token-bearing documents must finish loading before admission. Registration stays offscreen with native focus vetoes; pixels reach normal bounds only after actual target GUID membership and DWM Shell cloak are independently verified. DeleteTab is forbidden after placement because it destroys the Shell view and membership.","key":"16","section":"guidance"}
M computer-use "New Bureau windows are held hidden before launch resumes. Token-bearing documents must finish loading before admission. Registration stays offscreen with native focus vetoes; pixels reach normal bounds only after actual target GUID membership and DWM Shell cloak are independently verified. DeleteTab is forbidden after placement because it destroys the Shell view and membership." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Preview images are immutable by advertised sequence and capture identity. The pane swaps loaded pixels and their metadata together. Coordinates and forwarded input use the displayed frame; expired frames and foreign windows refuse. Identical pixels may retain earlier semantic controls, but each selected control is freshly validated before dispatch.","key":"17","section":"guidance"}
M computer-use "Preview images are immutable by advertised sequence and capture identity. The pane swaps loaded pixels and their metadata together. Coordinates and forwarded input use the displayed frame; expired frames and foreign windows refuse. Identical pixels may retain earlier semantic controls, but each selected control is freshly validated before dispatch." src:"authored manual" state:verified
-- @record {"chapter":"deadline-driver","data":"Preview scroll resolves the observed scrollable ancestor. Classic owned ListBox scroll uses bounded WM_VSCROLL and fresh LB_GETTOPINDEX effect readback. A degraded observation may be retried as a read only; an uncertain dispatched action is never retried.","key":"18","section":"guidance"}
M computer-use "Preview scroll resolves the observed scrollable ancestor. Classic owned ListBox scroll uses bounded WM_VSCROLL and fresh LB_GETTOPINDEX effect readback. A degraded observation may be retried as a read only; an uncertain dispatched action is never retried." src:"authored manual" state:verified
L computer-use.drive v1 -- Drive a native Windows app in the background through the computer-use driver (cua-driver tool shape), with Paul watching in the preview
-- @record {"chapter":"drive","data":{"args":{},"inputs":{"$cl_type":"t15"},"shape":{"$cl_type":"t16"},"tool":"neyvia.cua.state"},"key":"driver","section":"state"}
S computer-use.driver:{driver:json:"{\"type\":\"object\"}" sessions:json:"{\"type\":\"array\"}" ..}=neyvia.cua.state()
-- @record {"chapter":"drive","data":{"args":{},"inputs":{"$cl_type":"t15"},"shape":{"$cl_type":"t17"},"tool":"neyvia.cua.windows"},"key":"windows","section":"state"}
S computer-use.windows:{windows:json:"{\"type\":\"array\"}" ..}=neyvia.cua.windows()
-- @record {"chapter":"drive","data":{"effect":"Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot","pre":"window_id from neyvia.cua.windows of the same session; the app is allowed","returns":{"type":"object","properties":{"pid":{"type":"integer"},"window_id":{"type":"integer"},"capture_id":{"type":"string"},"elements":{"type":"array","items":{"type":"object","properties":{"element_token":{"type":"string"}}}},"element_count":{"type":"integer"}},"required":["pid","window_id"]},"reversible":true,"schema":"neyvia.cua.inspect","tool":"neyvia.cua.inspect"},"key":"cua.inspect","section":"actions"}
A neyvia.cua.inspect(sessionId?:str window_id:int query?:str diff_only?:bool previousHandle?:str reset?:bool max_elements?:1..2000) -> {pid:int window_id:int capture_id?:str elements?:[json:"{\"type\":\"object\",\"properties\":{\"element_token\":{\"type\":\"string\"}}}"] element_count?:int ..} -- Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot
F verify-cua-inspect "No authored observer check is bound to neyvia.cua.inspect" -> ask operator blocks:neyvia.cua.inspect
-- @record {"chapter":"drive","data":{"effect":"Send one cua-driver action (click/type_text/press_key/hotkey/scroll/drag/set_value/invoke_menu/launch_app) to the background window; delivery_mode background by default (no focus or cursor change); returns cua ActionResult plus _meta neyvia/preview {paulActions, note}; irreversible targets wait up to 120 s for Paul's Allow","pre":"Active session whose allow-list holds the target app; Paul has not taken over; element_token comes from the latest inspect of that window (snapshot-bound) or x,y are pixels of a capture_id","returns":{"$cl_type":"t19"},"reversible":false,"schema":"neyvia.cua.action","tool":"neyvia.cua.action"},"key":"cua.action","section":"actions"}
A neyvia.cua.action(sessionId?:str tool:json:"{\"type\":\"string\",\"enum\":[\"click\",\"double_click\",\"right_click\",\"type_text\",\"press_key\",\"hotkey\",\"scroll\",\"drag\",\"set_value\",\"invoke_menu\",\"launch_app\"]}" args:json:"{\"type\":\"object\"}") -> {effect:json:"{\"type\":\"string\",\"enum\":[\"confirmed\",\"partial\",\"unverifiable\",\"suspected_noop\",\"refused\"]}" route:str delivery?:json:"{\"type\":\"object\"}" evidence?:json:"{\"type\":\"array\"}" summary?:str error?:json:"{\"type\":\"object\"}" escalation?:json:"{\"type\":\"object\"}" ..} ! -- Send one cua-driver action (click/type_text/press_key/hotkey/scroll/drag/set_value/invoke_menu/launch_app) to the background window; delivery_mode background by default (no focus or cursor change); returns cua ActionResult plus _meta neyvia/preview {paulActions, note}; irreversible targets wait up to 120 s for Paul's Allow
C neyvia.cua.action value-is:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:expected}}] timeout_ms:3000 window_id:before.window_id) .status == "satisfied"
-- @record {"chapter":"drive","data":{"effect":"Block until Paul gives control back (or timeout); returns his give-back note and every action he did in the preview meanwhile","pre":"Use after a paused_by_user refusal or when you asked Paul to try something","returns":{"$cl_type":"t20"},"reversible":true,"schema":"neyvia.cua.wait","tool":"neyvia.cua.wait"},"key":"cua.wait","section":"actions"}
A neyvia.cua.wait(sessionId?:str timeout_ms:0..600000) -> json:"{\"type\":\"object\",\"properties\":{\"control\":{\"type\":\"string\"},\"note\":{\"type\":\"string\"},\"paulActions\":{\"type\":\"array\"},\"timedOut\":{\"type\":\"boolean\"}}}" -- Block until Paul gives control back (or timeout); returns his give-back note and every action he did in the preview meanwhile
F verify-cua-wait "No authored observer check is bound to neyvia.cua.wait" -> ask operator blocks:neyvia.cua.wait
-- @record {"chapter":"drive","data":{"effect":"Read the shared log (agent and Paul): who, tool, element, ActionResult, approvals, notes","pre":"Session exists; since_seq from a previous next_seq to read only what is new","returns":{"$cl_type":"t21"},"reversible":true,"schema":"neyvia.cua.log","tool":"neyvia.cua.log"},"key":"cua.log","section":"actions"}
A neyvia.cua.log(sessionId?:str since_seq?:0..) -> {session?:str entries:json:"{\"type\":\"array\"}" next_seq:int ..} -- Read the shared log (agent and Paul): who, tool, element, ActionResult, approvals, notes
F verify-cua-log "No authored observer check is bound to neyvia.cua.log" -> ask operator blocks:neyvia.cua.log
-- @record {"chapter":"drive","data":{"effect":"Open the live preview on Paul's stage: the window, the element you act on outlined before each action, the shared log, Take over/Give back and the allow-list","pre":"kind preview; target is the session id, or empty for the newest active session","returns":{"type":"object"},"reversible":true,"schema":"neyvia.pane.show","tool":"neyvia.pane.show"},"key":"pane.show","section":"actions"}
A neyvia.pane.show(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str) -> json:"{\"type\":\"object\"}" ! -- Open the live preview on Paul's stage: the window, the element you act on outlined before each action, the shared log, Take over/Give back and the allow-list
F verify-pane-show "No authored observer check is bound to neyvia.pane.show" -> ask operator blocks:neyvia.pane.show
-- @record {"chapter":"drive","data":{"effect":"Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot","pre":"window_id from neyvia.cua.windows of the same session; the app is allowed","returns":{"type":"object","properties":{"pid":{"type":"integer"},"window_id":{"type":"integer"},"capture_id":{"type":"string"},"elements":{"type":"array","items":{"type":"object","properties":{"element_token":{"type":"string"}}}},"element_count":{"type":"integer"}},"required":["pid","window_id"]},"reversible":true,"schema":"neyvia.cua.inspect","tool":"neyvia.cua.inspect"},"key":"cua.inspect-field","section":"actions"}
A neyvia.cua.inspect(sessionId?:str window_id:int query?:str diff_only?:bool previousHandle?:str reset?:bool max_elements?:1..2000) -> {pid:int window_id:int capture_id?:str elements?:[json:"{\"type\":\"object\",\"properties\":{\"element_token\":{\"type\":\"string\"}}}"] element_count?:int ..} -- Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot
F verify-cua-inspect-field "No authored observer check is bound to neyvia.cua.inspect" -> ask operator blocks:neyvia.cua.inspect
-- @record {"chapter":"drive","data":{"args":{"expect":[{"element":{"selector":{"label_contains":{"$input":"label"},"role":{"$input":"role"}},"value_equals":{"$input":"expected"}}}],"timeout_ms":3000,"window_id":{"$result":"before.window_id"}},"expect":{"op":"eq","path":"status","value":"satisfied"},"tool":"neyvia.cua.verify"},"key":"value-is","section":"checks"}
C neyvia.cua.verify value-is:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:expected}}] timeout_ms:3000 window_id:before.window_id) .status == "satisfied"
-- @record {"chapter":"drive","data":{"args":{},"expect":{"op":"eq","path":"driver.available","value":true},"tool":"neyvia.cua.state"},"key":"driver-ready","section":"checks"}
C neyvia.cua.state driver-ready:neyvia.cua.state() .driver.available == true
-- @record {"chapter":"drive","data":{"goal":"Show the owned preview, inspect and review one field, resolve it afresh, set and independently verify its value","inputs":{"$cl_type":"t22"},"steps":[{"action":"pane.show","args":{"kind":"preview","target":""},"save":"shown"},{"action":"cua.inspect-field","args":{"query":{"$input":"label"},"window_id":{"$input":"window_id"}},"save":"before"},{"judge":"right-element"},{"action":"cua.action","args":{"args":{"element_token":{"$result":"before.elements.0.element_token"},"value":{"$input":"expected"}},"tool":"set_value"},"check":"value-is","save":"set","when":{"judge":"right-element","option":"act"}}]},"key":"set-field-and-verify","section":"procedures"}
P set-field-and-verify(window_id:int element_token:str label:str expected:str role?:json:"{\"type\":\"string\",\"default\":\"\"}"):shown=neyvia.pane.show(kind:"preview" target:""); before=neyvia.cua.inspect(query:label window_id:window_id); J right-element=act; set=neyvia.cua.action(args:{element_token:before.elements.0.element_token value:expected} tool:"set_value") C value-is -- Show the owned preview, inspect and review one field, resolve it afresh, set and independently verify its value
V P set-field-and-verify -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"drive","data":{"constraints":"Tokens are snapshot-bound: use only tokens from the latest inspect of this window. If two elements share the label, pick by role and position or ask Paul. Never act on a window Paul did not allow.","options":["act","look-again"],"question":"Is the element token the field the task means (role, label and position in the inspect result), in an allowed app?"},"key":"right-element","section":"judge"}
J right-element act|look-again:"Is the element token the field the task means (role, label and position in the inspect result), in an allowed app?" -- Tokens are snapshot-bound: use only tokens from the latest inspect of this window. If two elements share the label, pick by role and position or ask Paul. Never act on a window Paul did not allow.
V J right-element -> human:operator why:"explicit choice required"
-- @record {"chapter":"drive","data":{"failure":"effect refused, error.code paused_by_user","recovery":"Paul took over in the preview. Call neyvia.cua.wait; read his note and paulActions; continue from the new state, do not repeat old steps blindly"},"key":"0","section":"pitfalls"}
X effect refused, error.code paused_by_user -> Paul took over in the preview. Call neyvia.cua.wait; read his note and paulActions; continue from the new state, do not repeat old steps blindly
-- @record {"chapter":"drive","data":{"failure":"effect refused, error.code app_not_allowed","recovery":"Ask with launch_app (creates an approval) or tell Paul in chat which app and why; never work around the allow-list"},"key":"1","section":"pitfalls"}
X effect refused, error.code app_not_allowed -> Ask with launch_app (creates an approval) or tell Paul in chat which app and why; never work around the allow-list
-- @record {"chapter":"drive","data":{"failure":"effect refused, error.code background_unavailable","recovery":"The target drops background input. Try an observed UI Automation pattern or admitted native message. Isolated native foreground delivery and SendInput remain disabled; report the actual refusal."},"key":"2","section":"pitfalls"}
X effect refused, error.code background_unavailable -> The target drops background input. Try an observed UI Automation pattern or admitted native message. Isolated native foreground delivery and SendInput remain disabled; report the actual refusal.
-- @record {"chapter":"drive","data":{"failure":"effect refused, error.code stale_element_token","recovery":"The window changed. Inspect again and take the token from the new snapshot"},"key":"3","section":"pitfalls"}
X effect refused, error.code stale_element_token -> The window changed. Inspect again and take the token from the new snapshot
-- @record {"chapter":"drive","data":{"failure":"effect unverifiable or suspected_noop","recovery":"Neither failure nor success. Verify with neyvia.cua.verify or a fresh inspect before moving on"},"key":"4","section":"pitfalls"}
X effect unverifiable or suspected_noop -> Neither failure nor success. Verify with neyvia.cua.verify or a fresh inspect before moving on
-- @record {"chapter":"drive","data":{"failure":"effect refused, error.code denied_by_user or approval_timeout","recovery":"Paul said no (or was away) to an irreversible action. Do not retry the same action; explain in chat and pick a reversible path"},"key":"5","section":"pitfalls"}
X effect refused, error.code denied_by_user or approval_timeout -> Paul said no (or was away) to an irreversible action. Do not retry the same action; explain in chat and pick a reversible path
-- @record {"chapter":"drive","data":{"failure":"Frame shows minimized or protected","recovery":"The driver cannot see minimized or capture-protected windows; ask Paul to restore it, never un-minimize with foreground tricks"},"key":"6","section":"pitfalls"}
X Frame shows minimized or protected -> The driver cannot see minimized or capture-protected windows; ask Paul to restore it, never un-minimize with foreground tricks
-- @record {"chapter":"drive","data":"Canvas and custom-drawn surfaces with no UI Automation peer can only be driven by pixel clicks on a capture; the driver has no OCR (the AGPL perception extension is never used)","key":"0","section":"frontier"}
F Canvas and custom-drawn surfaces with no UI Automation peer can only be driven by pixel clicks on a capture; the driver has no OCR (the AGPL perception extension is never used)
-- @record {"chapter":"drive","data":"Isolated native sessions ignore Paul's independent physical input. Preview Take over pauses this session explicitly.","key":"1","section":"frontier"}
F Isolated native sessions ignore Paul's independent physical input. Preview Take over pauses this session explicitly.
-- @record {"chapter":"drive","data":"Contract: plans/15-handoff.md ## T16 (Session, Frame, LogEntry, refusal codes). Tool shape: trycua/cua libs/cua-driver contract/manifest.json and docs/action-result-contract.md.","key":"0","section":"guidance"}
M computer-use "Contract: plans/15-handoff.md ## T16 (Session, Frame, LogEntry, refusal codes). Tool shape: trycua/cua libs/cua-driver contract/manifest.json and docs/action-result-contract.md." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"MCP agents use the same session through python -m grant_agent.neyvia_cua_mcp with cua-driver's tool names (click, type_text, get_window_state, ...); Neyvia models use neyvia.cua.*.","key":"1","section":"guidance"}
M computer-use "MCP agents use the same session through python -m grant_agent.neyvia_cua_mcp with cua-driver's tool names (click, type_text, get_window_state, ...); Neyvia models use neyvia.cua.*." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"Snapshot before every action: inspect, act with a token from that inspect, verify. Prefer element tokens over coordinates.","key":"2","section":"guidance"}
M computer-use "Snapshot before every action: inspect, act with a token from that inspect, verify. Prefer element tokens over coordinates." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"In CL use cua.windows(), then cua.inspect(w1), then cua.action(tool=\"set_value\", args={element:e1, value:\"text\"}). The host fills the driver token and binds value-is to the observed window, role, label and requested value. element_token:e1 is also accepted; literal tokens and stale or foreign refs are refused. Author G from cua.verify before mutation; unsupported observer checks remain frontier.","key":"3","section":"guidance"}
M computer-use "In CL use cua.windows(), then cua.inspect(w1), then cua.action(tool=\"set_value\", args={element:e1, value:\"text\"}). The host fills the driver token and binds value-is to the observed window, role, label and requested value. element_token:e1 is also accepted; literal tokens and stale or foreign refs are refused. Author G from cua.verify before mutation; unsupported observer checks remain frontier." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"User side: pane.show preview (web/src/neyvia/next/NxPreviewPane.jsx) shows the window, outlines the element before each action, and lists every action of yours and Paul's.","key":"4","section":"guidance"}
M computer-use "User side: pane.show preview (web/src/neyvia/next/NxPreviewPane.jsx) shows the window, outlines the element before each action, and lists every action of yours and Paul's." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"Connected Language: inspect with diff_only=true returns a full window state and handle first; pass previousHandle for scoped changes. reset=true requests a new full state. Handles remain bound to this session and window.","key":"5","section":"guidance"}
M computer-use "Connected Language: inspect with diff_only=true returns a full window state and handle first; pass previousHandle for scoped changes. reset=true requests a new full state. Handles remain bound to this session and window." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"C11 background work uses UI Automation patterns or admitted PostMessage on the agent desktop. Preview input uses this same driver; browser input in headless proof does not inject Windows input.","key":"6","section":"guidance"}
M computer-use "C11 background work uses UI Automation patterns or admitted PostMessage on the agent desktop. Preview input uses this same driver; browser input in headless proof does not inject Windows input." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"Zero-disturbance proof attributes foreground changes and visible windows to agent process trees, and requires zero LLMHF_INJECTED mouse events and zero LLKHF_INJECTED keyboard events on the input desktop. Paul's independent activity does not invalidate the run.","key":"7","section":"guidance"}
M computer-use "Zero-disturbance proof attributes foreground changes and visible windows to agent process trees, and requires zero LLMHF_INJECTED mouse events and zero LLKHF_INJECTED keyboard events on the input desktop. Paul's independent activity does not invalidate the run." src:"authored manual" state:verified
-- @record {"chapter":"drive","data":"Flow step args.observation_timeout_ms accepts 0..10000 milliseconds for bounded read-only initialization and fresh protection observations. Missing/unknown observations may retry; ambiguity refuses immediately. Verification requires two adjacent fresh satisfied observations. No mutation is retried.","key":"8","section":"guidance"}
M computer-use "Flow step args.observation_timeout_ms accepts 0..10000 milliseconds for bounded read-only initialization and fresh protection observations. Missing/unknown observations may retry; ambiguity refuses immediately. Verification requires two adjacent fresh satisfied observations. No mutation is retried." src:"authored manual" state:verified
L computer-use.private-journey v1 -- Integrated private-desktop journey: open an allowed app on the agent desktop, perceive it, type and click, verify each effect
-- @record {"chapter":"private-journey","data":{"effect":"Start the owner-allowed app on Neyvia's private agent desktop (launch_app with its installed path); nothing appears on Paul's screen","pre":"Paul allowed this app for the chat's session; the executable family has a verified private launch route","returns":{"$cl_type":"t19"},"reversible":false,"schema":"neyvia.cua.action","tool":"neyvia.cua.action"},"key":"launch","section":"actions"}
A neyvia.cua.action(sessionId?:str tool:json:"{\"type\":\"string\",\"enum\":[\"click\",\"double_click\",\"right_click\",\"type_text\",\"press_key\",\"hotkey\",\"scroll\",\"drag\",\"set_value\",\"invoke_menu\",\"launch_app\"]}" args:json:"{\"type\":\"object\"}") -> {effect:json:"{\"type\":\"string\",\"enum\":[\"confirmed\",\"partial\",\"unverifiable\",\"suspected_noop\",\"refused\"]}" route:str delivery?:json:"{\"type\":\"object\"}" evidence?:json:"{\"type\":\"array\"}" summary?:str error?:json:"{\"type\":\"object\"}" escalation?:json:"{\"type\":\"object\"}" ..} ! -- Start the owner-allowed app on Neyvia's private agent desktop (launch_app with its installed path); nothing appears on Paul's screen
C neyvia.cua.action desktop-undisturbed:neyvia.cua.state() .agentDesktop.guard.ok == true
-- @record {"chapter":"private-journey","data":{"effect":"Read the selected private window's elements (role, label, value, element_token); query narrows by label or role","pre":"cua.windows() then cua.inspect(wN) selected the window this journey acts on","returns":{"type":"object","properties":{"pid":{"type":"integer"},"window_id":{"type":"integer"},"capture_id":{"type":"string"},"elements":{"type":"array","items":{"type":"object","properties":{"element_token":{"type":"string"}}}},"element_count":{"type":"integer"}},"required":["pid","window_id"]},"reversible":true,"schema":"neyvia.cua.inspect","tool":"neyvia.cua.inspect"},"key":"observe","section":"actions"}
A neyvia.cua.inspect(sessionId?:str window_id:int query?:str diff_only?:bool previousHandle?:str reset?:bool max_elements?:1..2000) -> {pid:int window_id:int capture_id?:str elements?:[json:"{\"type\":\"object\",\"properties\":{\"element_token\":{\"type\":\"string\"}}}"] element_count?:int ..} -- Read the selected private window's elements (role, label, value, element_token); query narrows by label or role
F verify-observe "No authored observer check is bound to neyvia.cua.inspect" -> ask operator blocks:neyvia.cua.inspect
-- @record {"chapter":"private-journey","data":{"effect":"Type into or click one element from the latest observe of the selected window, as background messages on the private desktop","pre":"element_token comes from the observe step just before this one","returns":{"$cl_type":"t19"},"reversible":false,"schema":"neyvia.cua.action","tool":"neyvia.cua.action"},"key":"act","section":"actions"}
A neyvia.cua.action(sessionId?:str tool:json:"{\"type\":\"string\",\"enum\":[\"click\",\"double_click\",\"right_click\",\"type_text\",\"press_key\",\"hotkey\",\"scroll\",\"drag\",\"set_value\",\"invoke_menu\",\"launch_app\"]}" args:json:"{\"type\":\"object\"}") -> {effect:json:"{\"type\":\"string\",\"enum\":[\"confirmed\",\"partial\",\"unverifiable\",\"suspected_noop\",\"refused\"]}" route:str delivery?:json:"{\"type\":\"object\"}" evidence?:json:"{\"type\":\"array\"}" summary?:str error?:json:"{\"type\":\"object\"}" escalation?:json:"{\"type\":\"object\"}" ..} ! -- Type into or click one element from the latest observe of the selected window, as background messages on the private desktop
C neyvia.cua.action typed-value:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:typed}}] timeout_ms:3000 window_id:field.window_id) .status == "satisfied"
C neyvia.cua.action composed-value:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:composed}}] timeout_ms:3000 window_id:target.window_id) .status == "satisfied"
-- @record {"chapter":"private-journey","data":{"args":{},"expect":{"op":"eq","path":"agentDesktop.guard.ok","value":true},"tool":"neyvia.cua.state"},"key":"desktop-undisturbed","section":"checks"}
C neyvia.cua.state desktop-undisturbed:neyvia.cua.state() .agentDesktop.guard.ok == true
-- @record {"chapter":"private-journey","data":{"args":{"expect":[{"element":{"selector":{"label_contains":{"$input":"label"},"role":{"$input":"role"}},"value_equals":{"$input":"typed"}}}],"timeout_ms":3000,"window_id":{"$result":"field.window_id"}},"expect":{"op":"eq","path":"status","value":"satisfied"},"tool":"neyvia.cua.verify"},"key":"typed-value","section":"checks"}
C neyvia.cua.verify typed-value:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:typed}}] timeout_ms:3000 window_id:field.window_id) .status == "satisfied"
-- @record {"chapter":"private-journey","data":{"args":{"expect":[{"element":{"selector":{"label_contains":{"$input":"label"},"role":{"$input":"role"}},"value_equals":{"$input":"composed"}}}],"timeout_ms":3000,"window_id":{"$result":"target.window_id"}},"expect":{"op":"eq","path":"status","value":"satisfied"},"tool":"neyvia.cua.verify"},"key":"composed-value","section":"checks"}
C neyvia.cua.verify composed-value:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:composed}}] timeout_ms:3000 window_id:target.window_id) .status == "satisfied"
-- @record {"chapter":"private-journey","data":{"goal":"Launch an allowed app on the private agent desktop and confirm Paul's desktop saw no foreground, window or injected-input change","inputs":{"$cl_type":"t23"},"steps":[{"action":"launch","args":{"args":{"path":{"$input":"path"}},"tool":"launch_app"},"check":"desktop-undisturbed","save":"launched"}]},"key":"open-on-agent-desktop","section":"procedures"}
P open-on-agent-desktop(path:str):launched=neyvia.cua.action(args:{path:path} tool:"launch_app") C desktop-undisturbed -- Launch an allowed app on the private agent desktop and confirm Paul's desktop saw no foreground, window or injected-input change
V P open-on-agent-desktop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"private-journey","data":{"goal":"In the selected private window, type text into the field and verify the field's value","inputs":{"$cl_type":"t24"},"steps":[{"action":"observe","args":{"query":{"$input":"role"},"window_id":{"$input":"window_id"}},"save":"field"},{"action":"act","args":{"args":{"element_token":{"$result":"field.elements.0.element_token"},"text":{"$input":"text"}},"tool":"type_text"},"check":"typed-value","save":"typed_step"}]},"key":"type-and-verify","section":"procedures"}
P type-and-verify(window_id:int text:str label:str typed:str role?:json:"{\"type\":\"string\",\"default\":\"Edit\"}"):field=neyvia.cua.inspect(query:role window_id:window_id); typed_step=neyvia.cua.action(args:{element_token:field.elements.0.element_token text:text} tool:"type_text") C typed-value -- In the selected private window, type text into the field and verify the field's value
V P type-and-verify -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"private-journey","data":{"goal":"In the selected private window, click the named button and verify the field's resulting value","inputs":{"$cl_type":"t25"},"steps":[{"action":"observe","args":{"query":{"$input":"button"},"window_id":{"$input":"window_id"}},"save":"target"},{"action":"act","args":{"args":{"element_token":{"$result":"target.elements.0.element_token"}},"tool":"click"},"check":"composed-value","save":"clicked"}]},"key":"click-and-verify","section":"procedures"}
P click-and-verify(window_id:int button:str label:str composed:str role?:json:"{\"type\":\"string\",\"default\":\"Edit\"}"):target=neyvia.cua.inspect(query:button window_id:window_id); clicked=neyvia.cua.action(args:{element_token:target.elements.0.element_token} tool:"click") C composed-value -- In the selected private window, click the named button and verify the field's resulting value
V P click-and-verify -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"private-journey","data":{"failure":"launch refused with isolated_launch_unavailable or app_not_allowed","recovery":"Brokered, Store or singleton apps (Notepad, Calculator, Paint on Windows 11) have no proven private route; ask Paul for an allowed classic app, never a visible launch"},"key":"0","section":"pitfalls"}
X launch refused with isolated_launch_unavailable or app_not_allowed -> Brokered, Store or singleton apps (Notepad, Calculator, Paint on Windows 11) have no proven private route; ask Paul for an allowed classic app, never a visible launch
-- @record {"chapter":"private-journey","data":{"failure":"cua.windows lists untitled helper windows next to the app","recovery":"Select the titled main window with cua.inspect(wN) before each procedure; a procedure acts on the window of the latest observation"},"key":"1","section":"pitfalls"}
X cua.windows lists untitled helper windows next to the app -> Select the titled main window with cua.inspect(wN) before each procedure; a procedure acts on the window of the latest observation
-- @record {"chapter":"private-journey","data":{"failure":"typed-value or composed-value is unsatisfied","recovery":"Inspect again and read the field's actual value; the app decides where a click inserts (Character Map's Select inserts at the caret). Do not repeat the click blindly"},"key":"2","section":"pitfalls"}
X typed-value or composed-value is unsatisfied -> Inspect again and read the field's actual value; the app decides where a click inserts (Character Map's Select inserts at the caret). Do not repeat the click blindly
-- @record {"chapter":"private-journey","data":"Proven on Character Map (classic Win32) through the authenticated backend, CL procedures, an independent separate-process WM_GETTEXT readback and the agent-view time-lapse (scripts/prove_rx_cua_journey.py). Saving a document through a private-desktop file dialog is not yet proven.","key":"0","section":"frontier"}
F Proven on Character Map (classic Win32) through the authenticated backend, CL procedures, an independent separate-process WM_GETTEXT readback and the agent-view time-lapse (scripts/prove_rx_cua_journey.py). Saving a document through a private-desktop file dialog is not yet proven.
-- @record {"chapter":"private-journey","data":"The proven journey's task is issued through neyvia.cl on the owner's HTTP route. prove_rx_cua_journey.py --arm claude gives the same task to a Claude Code chat whose only tools are Neyvia's computer-use MCP; that arm has not completed yet (the local Claude CLI sign-in had expired).","key":"1","section":"frontier"}
F The proven journey's task is issued through neyvia.cl on the owner's HTTP route. prove_rx_cua_journey.py --arm claude gives the same task to a Claude Code chat whose only tools are Neyvia's computer-use MCP; that arm has not completed yet (the local Claude CLI sign-in had expired).
-- @record {"chapter":"private-journey","data":"Journey: run cua.open-on-agent-desktop(path=...), then cua.windows() and cua.inspect(wN) on the titled window, run cua.type-and-verify(...), cua.inspect(wN) again (an action retires the previous observation), then run cua.click-and-verify(...). Every action sits behind a check; the desktop guard is part of the launch check.","key":"0","section":"guidance"}
M computer-use "Journey: run cua.open-on-agent-desktop(path=...), then cua.windows() and cua.inspect(wN) on the titled window, run cua.type-and-verify(...), cua.inspect(wN) again (an action retires the previous observation), then run cua.click-and-verify(...). Every action sits behind a check; the desktop guard is part of the launch check." src:"authored manual" state:verified
-- @record {"chapter":"private-journey","data":"Paul allows the app for the chat first (preview allow-list); the chat identity of an owner HTTP CL call is http-owner:<session>.","key":"1","section":"guidance"}
M computer-use "Paul allows the app for the chat first (preview allow-list); the chat identity of an owner HTTP CL call is http-owner:<session>." src:"authored manual" state:verified
-- @record {"chapter":"private-journey","data":"The agent view mirrors the session: every action gets an 'after' keyframe in the time-lapse at /api/ui/agentview/timeline.","key":"2","section":"guidance"}
M computer-use "The agent view mirrors the session: every action gets an 'after' keyframe in the time-lapse at /api/ui/agentview/timeline." src:"authored manual" state:verified
L computer-use.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t26"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S computer-use.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t27"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t12"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"cua.toCapture: Frame clicks map from shown pixels to capture pixels and outside/empty frames are refused","key":"0","section":"guidance"}
M computer-use "cua.toCapture: Frame clicks map from shown pixels to capture pixels and outside/empty frames are refused" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"cua.keyToInput: Characters, named keys and chords retain exact modifiers; dead/modifier keys never send input","key":"1","section":"guidance"}
M computer-use "cua.keyToInput: Characters, named keys and chords retain exact modifiers; dead/modifier keys never send input" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"cua.wheelToScroll: Dominant axis determines direction; gesture amount is 1â€“10 lines with pixel/line/page conversion","key":"2","section":"guidance"}
M computer-use "cua.wheelToScroll: Dominant axis determines direction; gesture amount is 1â€“10 lines with pixel/line/page conversion" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"cua.elementAt: Choose the smallest containing observed element, preserve first match on equal area","key":"3","section":"guidance"}
M computer-use "cua.elementAt: Choose the smallest containing observed element, preserve first match on equal area" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"cua.pickSession: Named sessions must exist; otherwise the most recent live session wins, with ended fallback","key":"4","section":"guidance"}
M computer-use "cua.pickSession: Named sessions must exist; otherwise the most recent live session wins, with ended fallback" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"cua.mergeLog: Updates preserve entry identity and data; new rows are sequence sorted and bounded","key":"5","section":"guidance"}
M computer-use "cua.mergeLog: Updates preserve entry identity and data; new rows are sequence sorted and bounded" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"6","section":"guidance"}
M computer-use "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L computer-use.proofs-e-wz v1 -- PROOFS-e W-Z: live contracts and scratch self-checks
-- @record {"chapter":"proofs-e-wz","data":{"failure":"A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement","recovery":"Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion"},"key":"0","section":"pitfalls"}
X A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement -> Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion
-- @record {"chapter":"proofs-e-wz","data":"Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.","key":"0","section":"frontier"}
F Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.
-- @record {"chapter":"proofs-e-wz","data":"Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.","key":"1","section":"frontier"}
F Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.
-- @record {"chapter":"proofs-e-wz","data":"Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.","key":"2","section":"frontier"}
F Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.
-- @record {"chapter":"proofs-e-wz","data":"The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.","key":"3","section":"frontier"}
F The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.
-- @record {"chapter":"proofs-e-wz","data":"Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz","key":"0","section":"guidance"}
M computer-use "Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action.","key":"1","section":"guidance"}
M computer-use "Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection.","key":"2","section":"guidance"}
M computer-use "Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection." src:"authored manual" state:verified
L computer-use.test-loop v1 -- The test loop: build, launch, drive and check the app while Paul pokes at it in the same preview, then continue from what he did
-- @record {"chapter":"test-loop","data":{"args":{},"inputs":{"$cl_type":"t15"},"shape":{"$cl_type":"t21"},"tool":"neyvia.cua.log"},"key":"log","section":"state"}
S computer-use.log:{session?:str entries:json:"{\"type\":\"array\"}" next_seq:int ..}=neyvia.cua.log()
-- @record {"chapter":"test-loop","data":{"effect":"Open the live preview on Paul's stage: the window, the element you act on outlined before each action, the shared log, Take over/Give back and the allow-list","pre":"kind preview; target is the session id, or empty for the newest active session","returns":{"type":"object"},"reversible":true,"schema":"neyvia.pane.show","tool":"neyvia.pane.show"},"key":"pane.show","section":"actions"}
A neyvia.pane.show(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str) -> json:"{\"type\":\"object\"}" ! -- Open the live preview on Paul's stage: the window, the element you act on outlined before each action, the shared log, Take over/Give back and the allow-list
F verify-pane-show "No authored observer check is bound to neyvia.pane.show" -> ask operator blocks:neyvia.pane.show
-- @record {"chapter":"test-loop","data":{"effect":"Send one cua-driver action (click/type_text/press_key/hotkey/scroll/drag/set_value/invoke_menu/launch_app) to the background window; delivery_mode background by default (no focus or cursor change); returns cua ActionResult plus _meta neyvia/preview {paulActions, note}; irreversible targets wait up to 120 s for Paul's Allow","pre":"Active session whose allow-list holds the target app; Paul has not taken over; element_token comes from the latest inspect of that window (snapshot-bound) or x,y are pixels of a capture_id","returns":{"$cl_type":"t19"},"reversible":false,"schema":"neyvia.cua.action","tool":"neyvia.cua.action"},"key":"cua.action","section":"actions"}
A neyvia.cua.action(sessionId?:str tool:json:"{\"type\":\"string\",\"enum\":[\"click\",\"double_click\",\"right_click\",\"type_text\",\"press_key\",\"hotkey\",\"scroll\",\"drag\",\"set_value\",\"invoke_menu\",\"launch_app\"]}" args:json:"{\"type\":\"object\"}") -> {effect:json:"{\"type\":\"string\",\"enum\":[\"confirmed\",\"partial\",\"unverifiable\",\"suspected_noop\",\"refused\"]}" route:str delivery?:json:"{\"type\":\"object\"}" evidence?:json:"{\"type\":\"array\"}" summary?:str error?:json:"{\"type\":\"object\"}" escalation?:json:"{\"type\":\"object\"}" ..} ! -- Send one cua-driver action (click/type_text/press_key/hotkey/scroll/drag/set_value/invoke_menu/launch_app) to the background window; delivery_mode background by default (no focus or cursor change); returns cua ActionResult plus _meta neyvia/preview {paulActions, note}; irreversible targets wait up to 120 s for Paul's Allow
F verify-cua-action "No authored observer check is bound to neyvia.cua.action" -> ask operator blocks:neyvia.cua.action
-- @record {"chapter":"test-loop","data":{"effect":"Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot","pre":"window_id from neyvia.cua.windows of the same session; the app is allowed","returns":{"type":"object","properties":{"pid":{"type":"integer"},"window_id":{"type":"integer"},"capture_id":{"type":"string"},"elements":{"type":"array","items":{"type":"object","properties":{"element_token":{"type":"string"}}}},"element_count":{"type":"integer"}},"required":["pid","window_id"]},"reversible":true,"schema":"neyvia.cua.inspect","tool":"neyvia.cua.inspect"},"key":"cua.inspect","section":"actions"}
A neyvia.cua.inspect(sessionId?:str window_id:int query?:str diff_only?:bool previousHandle?:str reset?:bool max_elements?:1..2000) -> {pid:int window_id:int capture_id?:str elements?:[json:"{\"type\":\"object\",\"properties\":{\"element_token\":{\"type\":\"string\"}}}"] element_count?:int ..} -- Read the window's accessibility elements (role, label, value, actions, element_token, screenshot_frame) and its capture_id; tokens expire on the next snapshot
C neyvia.cua.inspect value-is: neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:expected}}] timeout_ms:3000 window_id:window_id).status=="satisfied"
-- @record {"chapter":"test-loop","data":{"effect":"Block until Paul gives control back (or timeout); returns his give-back note and every action he did in the preview meanwhile","pre":"Use after a paused_by_user refusal or when you asked Paul to try something","returns":{"$cl_type":"t20"},"reversible":true,"schema":"neyvia.cua.wait","tool":"neyvia.cua.wait"},"key":"cua.wait","section":"actions"}
A neyvia.cua.wait(sessionId?:str timeout_ms:0..600000) -> json:"{\"type\":\"object\",\"properties\":{\"control\":{\"type\":\"string\"},\"note\":{\"type\":\"string\"},\"paulActions\":{\"type\":\"array\"},\"timedOut\":{\"type\":\"boolean\"}}}" -- Block until Paul gives control back (or timeout); returns his give-back note and every action he did in the preview meanwhile
F verify-cua-wait "No authored observer check is bound to neyvia.cua.wait" -> ask operator blocks:neyvia.cua.wait
-- @record {"chapter":"test-loop","data":{"effect":"Read the shared log (agent and Paul): who, tool, element, ActionResult, approvals, notes","pre":"Session exists; since_seq from a previous next_seq to read only what is new","returns":{"$cl_type":"t21"},"reversible":true,"schema":"neyvia.cua.log","tool":"neyvia.cua.log"},"key":"cua.log","section":"actions"}
A neyvia.cua.log(sessionId?:str since_seq?:0..) -> {session?:str entries:json:"{\"type\":\"array\"}" next_seq:int ..} -- Read the shared log (agent and Paul): who, tool, element, ActionResult, approvals, notes
F verify-cua-log "No authored observer check is bound to neyvia.cua.log" -> ask operator blocks:neyvia.cua.log
-- @record {"chapter":"test-loop","data":{"args":{"expect":[{"element":{"selector":{"label_contains":{"$input":"label"},"role":{"$input":"role"}},"value_equals":{"$input":"expected"}}}],"timeout_ms":3000,"window_id":{"$input":"window_id"}},"expect":{"op":"eq","path":"status","value":"satisfied"},"tool":"neyvia.cua.verify"},"key":"value-is","section":"checks"}
C neyvia.cua.verify value-is:neyvia.cua.verify(expect:[{element:{selector:{label_contains:label role:role} value_equals:expected}}] timeout_ms:3000 window_id:window_id) .status == "satisfied"
-- @record {"chapter":"test-loop","data":{"goal":"Open the freshly built app in the background, show it live, check one visible value, then hand it to Paul and continue from his note and actions","inputs":{"$cl_type":"t28"},"steps":[{"action":"cua.action","args":{"args":{"app":{"$input":"app"}},"tool":"launch_app"},"save":"launched"},{"action":"pane.show","args":{"kind":"preview","target":""},"save":"shown"},{"action":"cua.inspect","args":{"window_id":{"$input":"window_id"}},"check":"value-is","save":"first"},{"judge":"ready-for-paul"},{"action":"cua.wait","args":{"timeout_ms":600000},"save":"paul","when":{"judge":"ready-for-paul","option":"hand-over"}},{"action":"cua.log","args":{},"save":"after","when":{"judge":"ready-for-paul","option":"hand-over"}}]},"key":"launch-check-handoff","section":"procedures"}
P launch-check-handoff(app:str window_id:int label:str expected:str role?:json:"{\"type\":\"string\",\"default\":\"\"}"):launched=neyvia.cua.action(args:{app:app} tool:"launch_app"); shown=neyvia.pane.show(kind:"preview" target:""); first=neyvia.cua.inspect(window_id:window_id) C value-is; J ready-for-paul=hand-over; paul=neyvia.cua.wait(timeout_ms:600000); after=neyvia.cua.log() -- Open the freshly built app in the background, show it live, check one visible value, then hand it to Paul and continue from his note and actions
V P launch-check-handoff -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"test-loop","data":{"constraints":"Say in chat what to try and that he can click and type in the preview; he takes over with the button and gives back with a note. Fix obvious breakage first; never hand over a crash.","options":["hand-over","fix-first"],"question":"Is the app in a state worth Paul's time (launched, the main screen shows, your own check passed)?"},"key":"ready-for-paul","section":"judge"}
J ready-for-paul hand-over|fix-first:"Is the app in a state worth Paul's time (launched, the main screen shows, your own check passed)?" -- Say in chat what to try and that he can click and type in the preview; he takes over with the button and gives back with a note. Fix obvious breakage first; never hand over a crash.
V J ready-for-paul -> human:operator why:"explicit choice required"
-- @record {"chapter":"test-loop","data":{"failure":"Paul's actions are missing from your view","recovery":"They arrive in _meta neyvia/preview paulActions of your next call and in neyvia.cua.log; read the log since your last next_seq before deciding"},"key":"0","section":"pitfalls"}
X Paul's actions are missing from your view -> They arrive in _meta neyvia/preview paulActions of your next call and in neyvia.cua.log; read the log since your last next_seq before deciding
-- @record {"chapter":"test-loop","data":{"failure":"The rebuilt app is a new process with a new window_id","recovery":"List windows again after each relaunch; old tokens and window ids are void"},"key":"1","section":"pitfalls"}
X The rebuilt app is a new process with a new window_id -> List windows again after each relaunch; old tokens and window ids are void
-- @record {"chapter":"test-loop","data":{"failure":"Paul is still typing when you act","recovery":"Actions serialize per window, but read the log first; if his last action is under 5 s old, wait or ask"},"key":"2","section":"pitfalls"}
X Paul is still typing when you act -> Actions serialize per window, but read the log first; if his last action is under 5 s old, wait or ask
-- @record {"chapter":"test-loop","data":"No automatic replay of Paul's actions as a test script yet; copy them from the log into a procedure if they should be repeated","key":"0","section":"frontier"}
F No automatic replay of Paul's actions as a test script yet; copy them from the log into a procedure if they should be repeated
-- @record {"chapter":"test-loop","data":"Pairs with the app's own manual when it has one (windows[].manual): that manual says which states and actions exist, this one how to observe and act; the preview shows both sides to Paul.","key":"0","section":"guidance"}
M computer-use "Pairs with the app's own manual when it has one (windows[].manual): that manual says which states and actions exist, this one how to observe and act; the preview shows both sides to Paul." src:"authored manual" state:verified
