CL 1
L connections v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Every way Neyvia reaches a model, honest state and a proven one-click connect"}},"clVersion":"1.1","id":"connections","kind":"environment","proofs":{"area":"connections","manifests":["config/proofs/connections.json"]},"schema":"neyvia.manual.v1","schemas":{"click":"live_schema_7","inspect":"live_schema_8","install":"live_schema_9"},"tool_metadata":{"neyvia.connections.connect":{"mutability_class":"external_action"},"neyvia.connections.inspect":{"mutability_class":"read"},"neyvia.connections.install":{"mutability_class":"external_action"},"neyvia.connections.prove":{"mutability_class":"external_action"}}}
T live_schema_7 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"fromClick\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"fromClick\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_8 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"force\":{\"type\":\"boolean\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_9 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"approvalId\":{\"type\":\"string\"},\"consent\":{\"type\":\"boolean\"},\"fromClick\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"fromClick\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
-- @proof {"checkedAt":["grant_agent.neyvia_connections.check_cards","grant_agent.neyvia_connections.status","grant_agent.proofs_connections.self_check"],"claim":"Every connection has an honest state, a plain reason and a next step. Sign-in uses the provider's own flow: Claude, Codex and OpenCode in their terminal, Kimi's native browser flow. A test receipt only counts while connected; account material never reaches the card.","id":"conn.screen.invariants","impact":["Runtime page and first-run Connect step"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.connections_install.install","grant_agent.connections_install.run_hidden","grant_agent.connections_install.install_package","grant_agent.neyvia_connections.check_cards"],"claim":"No install starts before the exact consent; fixed official package routes run hidden, stream progress, install missing prerequisites, and verify the version before success. Failure or restart offers Retry.","id":"conn.install.lifecycle","impact":["Connections install and Retry"],"phase":"post"}
T t1{id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}" fromClick:bool ..}
T t2{id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}" force?:bool ..}
T t3{id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}" approvalId?:str consent?:bool fromClick:bool ..}
T t4 json:"{\"type\":\"object\",\"additionalProperties\":true}"
T t5{id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}" approvalId:str ..}
T t6{id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"}
L connections.overview v1 -- Every way Neyvia reaches a model, honest state and a proven one-click connect
-- @record {"chapter":"overview","data":{"effect":"Observe the real card and latest installation, sign-in and proof state.","pre":"Install, sign-in and Test it require the explicit person click. Installation also needs this exact pending approval. Observe completion separately.","returns":{"type":"object","additionalProperties":true},"reversible":false,"schema":"inspect","tool":"neyvia.connections.inspect"},"key":"inspect","section":"actions"}
A neyvia.connections.inspect(id:str force?:bool) -> json:"{\"type\":\"object\",\"additionalProperties\":true}" -- Observe the real card and latest installation, sign-in and proof state.
C neyvia.connections.inspect installed: neyvia.connections.inspect(id:id).installed==true
C neyvia.connections.inspect signed-in: neyvia.connections.inspect(id:id).state=="connected"
C neyvia.connections.inspect round-trip: neyvia.connections.inspect(id:id).proof.ok==true
-- @record {"chapter":"overview","data":{"effect":"Run the consented install and prerequisites hidden; stream package progress, verify --version, retain a receipt and expose Retry on failure.","pre":"Install, sign-in and Test it require the explicit person click. Installation also needs this exact pending approval. Observe completion separately.","returns":{"type":"object","additionalProperties":true},"reversible":false,"schema":"install","tool":"neyvia.connections.install"},"key":"install","section":"actions"}
A neyvia.connections.install(id:str approvalId?:str consent?:bool fromClick:bool) -> json:"{\"type\":\"object\",\"additionalProperties\":true}" ! -- Run the consented install and prerequisites hidden; stream package progress, verify --version, retain a receipt and expose Retry on failure.
F verify-install "No authored observer check is bound to neyvia.connections.install" -> ask operator blocks:neyvia.connections.install
-- @record {"chapter":"overview","data":{"effect":"Open the provider-owned sign-in; poll its status until the card is signed in.","pre":"Install, sign-in and Test it require the explicit person click. Installation also needs this exact pending approval. Observe completion separately.","returns":{"type":"object","additionalProperties":true},"reversible":false,"schema":"click","tool":"neyvia.connections.connect"},"key":"connect","section":"actions"}
A neyvia.connections.connect(id:str fromClick:bool) -> json:"{\"type\":\"object\",\"additionalProperties\":true}" ! -- Open the provider-owned sign-in; poll its status until the card is signed in.
F verify-connect "No authored observer check is bound to neyvia.connections.connect" -> ask operator blocks:neyvia.connections.connect
-- @record {"chapter":"overview","data":{"effect":"Run a real tiny chat with a file-tool round trip and retain the result.","pre":"Install, sign-in and Test it require the explicit person click. Installation also needs this exact pending approval. Observe completion separately.","returns":{"type":"object","additionalProperties":true},"reversible":false,"schema":"click","tool":"neyvia.connections.prove"},"key":"prove","section":"actions"}
A neyvia.connections.prove(id:str fromClick:bool) -> json:"{\"type\":\"object\",\"additionalProperties\":true}" ! -- Run a real tiny chat with a file-tool round trip and retain the result.
F verify-prove "No authored observer check is bound to neyvia.connections.prove" -> ask operator blocks:neyvia.connections.prove
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"installed","value":true},"tool":"neyvia.connections.inspect"},"key":"installed","section":"checks"}
C neyvia.connections.inspect installed:neyvia.connections.inspect(id:id) .installed == true
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"state","value":"connected"},"tool":"neyvia.connections.inspect"},"key":"signed-in","section":"checks"}
C neyvia.connections.inspect signed-in:neyvia.connections.inspect(id:id) .state == "connected"
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"proof.ok","value":true},"tool":"neyvia.connections.inspect"},"key":"round-trip","section":"checks"}
C neyvia.connections.inspect round-trip:neyvia.connections.inspect(id:id) .proof.ok == true
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"install.state","value":"installing"},"tool":"neyvia.connections.inspect"},"key":"install-started","section":"checks"}
C neyvia.connections.inspect install-started:neyvia.connections.inspect(id:id) .install.state == "installing"
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"schema","path":"version","schema":{"minLength":1,"type":"string"}},"tool":"neyvia.connections.inspect"},"key":"version-verified","section":"checks"}
C neyvia.connections.inspect version-verified:matches(neyvia.connections.inspect(id:id) .version {minLength:1 type:"string"})
-- @record {"chapter":"overview","data":{"goal":"After the person clicks Allow install on this exact approval, install without asking them to type. Poll inspect until installed; a failed job offers Retry.","inputs":{"$cl_type":"t5"},"steps":[{"action":"install","args":{"approvalId":{"$input":"approvalId"},"consent":true,"fromClick":true,"id":{"$input":"id"}},"save":"started"}]},"key":"install-harness","section":"procedures"}
P install-harness(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}" approvalId:str):started=neyvia.connections.install(approvalId:approvalId consent:true fromClick:true id:id) -- After the person clicks Allow install on this exact approval, install without asking them to type. Poll inspect until installed; a failed job offers Retry.
V P install-harness -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Observe version-verified completion after installation. Installing or failure does not satisfy this check.","inputs":{"$cl_type":"t6"},"steps":[{"action":"inspect","args":{"id":{"$input":"id"}},"check":"installed","save":"card"}]},"key":"check-installed","section":"procedures"}
P check-installed(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"):card=neyvia.connections.inspect(id:id) C installed -- Observe version-verified completion after installation. Installing or failure does not satisfy this check.
V P check-installed -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"After the person clicks Sign in, open the provider flow. Keep polling inspect until signed-in; never type commands or handle credentials for them.","inputs":{"$cl_type":"t6"},"steps":[{"action":"connect","args":{"fromClick":true,"id":{"$input":"id"}},"save":"opened"}]},"key":"sign-in-harness","section":"procedures"}
P sign-in-harness(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"):opened=neyvia.connections.connect(fromClick:true id:id) -- After the person clicks Sign in, open the provider flow. Keep polling inspect until signed-in; never type commands or handle credentials for them.
V P sign-in-harness -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Observe the completed provider sign-in. A waiting card does not satisfy this check.","inputs":{"$cl_type":"t6"},"steps":[{"action":"inspect","args":{"force":true,"id":{"$input":"id"}},"check":"signed-in","save":"card"}]},"key":"check-signed-in","section":"procedures"}
P check-signed-in(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"):card=neyvia.connections.inspect(force:true id:id) C signed-in -- Observe the completed provider sign-in. A waiting card does not satisfy this check.
V P check-signed-in -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"After the person clicks Test it, start a real round trip. Poll inspect for the completed receipt.","inputs":{"$cl_type":"t6"},"steps":[{"action":"prove","args":{"fromClick":true,"id":{"$input":"id"}},"save":"started"}]},"key":"test-connection","section":"procedures"}
P test-connection(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"):started=neyvia.connections.prove(fromClick:true id:id) -- After the person clicks Test it, start a real round trip. Poll inspect for the completed receipt.
V P test-connection -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"A connection is tested only when its real tool-and-answer receipt passed and it remains signed in.","inputs":{"$cl_type":"t6"},"steps":[{"action":"inspect","args":{"id":{"$input":"id"}},"check":"round-trip","save":"card"}]},"key":"check-round-trip","section":"procedures"}
P check-round-trip(id:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\",\"kimi-code\",\"gptme\"]}"):card=neyvia.connections.inspect(id:id) C round-trip -- A connection is tested only when its real tool-and-answer receipt passed and it remains signed in.
V P check-round-trip -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"Installation fails or Neyvia restarts mid-install.","recovery":"Show the plain reason and Retry. Never claim installation succeeded before the version command passes."},"key":"0","section":"pitfalls"}
X Installation fails or Neyvia restarts mid-install. -> Show the plain reason and Retry. Never claim installation succeeded before the version command passes.
-- @record {"chapter":"overview","data":{"failure":"Sign-in has not completed.","recovery":"Keep polling the provider status; do not infer success from opening its flow."},"key":"1","section":"pitfalls"}
X Sign-in has not completed. -> Keep polling the provider status; do not infer success from opening its flow.
-- @record {"chapter":"overview","data":"A provider login, account permission or API-key choice must still be completed by the person. A signed-in card is not a passed round trip. Long-chat compaction checks are available on broker-backed Claude, Codex and OpenCode; Kimi and gptme use their existing isolated read-only CLI bridge.","key":"0","section":"frontier"}
F A provider login, account permission or API-key choice must still be completed by the person. A signed-in card is not a passed round trip. Long-chat compaction checks are available on broker-backed Claude, Codex and OpenCode; Kimi and gptme use their existing isolated read-only CLI bridge.
-- @record {"chapter":"overview","data":"gptme upstream documents WSL or Docker for Windows CLI use; a successful native version check does not establish that all of its tools work on Windows.","key":"1","section":"frontier"}
F gptme upstream documents WSL or Docker for Windows CLI use; a successful native version check does not establish that all of its tools work on Windows.
-- @record {"chapter":"overview","data":"The requested uv Kimi route uses kimi-cli 1.51.0, the last functional legacy release. Version 1.52 is a migration stub; updates to it are blocked. The current Node-based Kimi Code CLI is a separate migration and is not substituted silently.","key":"2","section":"frontier"}
F The requested uv Kimi route uses kimi-cli 1.51.0, the last functional legacy release. Version 1.52 is a migration stub; updates to it are blocked. The current Node-based Kimi Code CLI is a separate migration and is not substituted silently.
-- @record {"chapter":"overview","data":"Install asks once for permission to download the harness and missing Node/npm or uv/Python prerequisites. The app runs installers hidden and shows Installing with the latest log line, then Not signed in or Ready after a successful version command. Missing npm uses silent winget Node.js LTS, or the official checksum-verified portable Node distribution when App Installer is absent; missing uv uses winget or the backend Python bootstrap. Neither needs a terminal command from the person.","key":"0","section":"guidance"}
M connections "Install asks once for permission to download the harness and missing Node/npm or uv/Python prerequisites. The app runs installers hidden and shows Installing with the latest log line, then Not signed in or Ready after a successful version command. Missing npm uses silent winget Node.js LTS, or the official checksum-verified portable Node distribution when App Installer is absent; missing uv uses winget or the backend Python bootstrap. Neither needs a terminal command from the person." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Sign in opens the provider-owned flow with one click. Authentication remains the provider's responsibility; the card detects completion automatically and offers Test it. Stop waiting only stops watching, not the provider flow.","key":"1","section":"guidance"}
M connections "Sign in opens the provider-owned flow with one click. Authentication remains the provider's responsibility; the card detects completion automatically and offers Test it. Stop waiting only stops watching, not the provider flow." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Automatic harness updates use the existing hourly tool updater, owner Settings policy, NEYVIA_TOOL_AUTO_UPDATE and busy-process checks. Cards show when updates are paused. Managed npm updates retain the previous verified package; Python harnesses use isolated uv environments. Existing user uv and pipx installations are detected and upgraded in place only when present. Legacy uv Kimi is pinned to 1.51.0 and honestly labelled as no longer updated by its provider.","key":"2","section":"guidance"}
M connections "Automatic harness updates use the existing hourly tool updater, owner Settings policy, NEYVIA_TOOL_AUTO_UPDATE and busy-process checks. Cards show when updates are paused. Managed npm updates retain the previous verified package; Python harnesses use isolated uv environments. Existing user uv and pipx installations are detected and upgraded in place only when present. Legacy uv Kimi is pinned to 1.51.0 and honestly labelled as no longer updated by its provider." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"The desktop updater is separate. Its private GitHub release feed returns 404 without authenticated access. It needs an accessible signed update manifest and signed platform bundles, or an authenticated distribution service. Do not embed a GitHub credential in the app.","key":"3","section":"guidance"}
M connections "The desktop updater is separate. Its private GitHub release feed returns 404 without authenticated access. It needs an accessible signed update manifest and signed platform bundles, or an authenticated distribution service. Do not embed a GitHub credential in the app." src:"authored manual" state:verified
