CL 1
L creative-records v1 -- Authored executable manual
-- @manual {"chapters":{"local-records":{"title":"Task proposals and reported representation experiments"}},"clVersion":"1.1","id":"creative-records","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"attention.create":"t1","attention.observe":"t1","situation.define":"t2"},"tool_metadata":{"attention.create":{"mutability_class":"artifact_write"},"attention.observe":{"mutability_class":"artifact_write"},"situation.define":{"mutability_class":"artifact_write"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\"}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"task\":{\"type\":\"string\"},\"constraints\":{\"type\":\"array\"},\"acceptance\":{\"type\":\"array\"},\"expectedRevision\":{\"type\":\"integer\"}},\"required\":[\"workId\",\"task\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}},\"task\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\"}"
T t4{workId:str task:str constraints:json:"{\"type\":\"array\"}" acceptance:json:"{\"type\":\"array\"}" expectedRevision:int ..}
T t5{workId:str arguments:json:"{\"type\":\"object\"}" ..}
L creative-records.local-records v1 -- Task proposals and reported representation experiments
-- @record {"chapter":"local-records","data":{"effect":"Persist the exact scoped proposal or unverified observation and conserve unrelated records","pre":"Selected work identity and exact requested record fields; local owner state must be intact","returns":{"$cl_type":"t3"},"reversible":false,"schema":"situation.define","tool":"situation.define"},"key":"situation-define","section":"actions"}
A situation.define(workId:str task:str constraints?:json:"{\"type\":\"array\"}" acceptance?:json:"{\"type\":\"array\"}" expectedRevision?:int) -> json:"{\"type\":\"object\"}" ! -- Persist the exact scoped proposal or unverified observation and conserve unrelated records
F verify-situation-define "No authored observer check is bound to situation.define" -> ask operator blocks:situation.define
-- @record {"chapter":"local-records","data":{"effect":"Persist the exact scoped proposal or unverified observation and conserve unrelated records","pre":"Selected work identity and exact requested record fields; local owner state must be intact","returns":{"$cl_type":"t3"},"reversible":false,"schema":"attention.create","tool":"attention.create"},"key":"attention-create","section":"actions"}
A attention.create(workId:str arguments:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Persist the exact scoped proposal or unverified observation and conserve unrelated records
F verify-attention-create "No authored observer check is bound to attention.create" -> ask operator blocks:attention.create
-- @record {"chapter":"local-records","data":{"effect":"Persist the exact scoped proposal or unverified observation and conserve unrelated records","pre":"Selected work identity and exact requested record fields; local owner state must be intact","returns":{"$cl_type":"t3"},"reversible":false,"schema":"attention.observe","tool":"attention.observe"},"key":"attention-observe","section":"actions"}
A attention.observe(workId:str arguments:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Persist the exact scoped proposal or unverified observation and conserve unrelated records
F verify-attention-observe "No authored observer check is bound to attention.observe" -> ask operator blocks:attention.observe
-- @record {"chapter":"local-records","data":{"goal":"Save an exact task proposal, constraints and acceptance criteria under one work identity","inputs":{"$cl_type":"t4"},"steps":[{"action":"situation-define","args":{"acceptance":{"$input":"acceptance"},"constraints":{"$input":"constraints"},"expectedRevision":{"$input":"expectedRevision"},"task":{"$input":"task"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-situation-define","section":"procedures"}
P record-situation-define(workId:str task:str constraints:json:"{\"type\":\"array\"}" acceptance:json:"{\"type\":\"array\"}" expectedRevision:int):saved=situation.define(acceptance:acceptance constraints:constraints expectedRevision:expectedRevision task:task workId:workId) -- Save an exact task proposal, constraints and acceptance criteria under one work identity
V P record-situation-define -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"local-records","data":{"goal":"Freeze a bounded local representation experiment; no model call occurs","inputs":{"$cl_type":"t5"},"steps":[{"action":"attention-create","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-attention-create","section":"procedures"}
P record-attention-create(workId:str arguments:json:"{\"type\":\"object\"}"):saved=attention.create(arguments:arguments workId:workId) -- Freeze a bounded local representation experiment; no model call occurs
V P record-attention-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"local-records","data":{"goal":"Append one caller-reported API observation without claiming it was independently verified","inputs":{"$cl_type":"t5"},"steps":[{"action":"attention-observe","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-attention-observe","section":"procedures"}
P record-attention-observe(workId:str arguments:json:"{\"type\":\"object\"}"):saved=attention.observe(arguments:arguments workId:workId) -- Append one caller-reported API observation without claiming it was independently verified
V P record-attention-observe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"local-records","data":{"failure":"A caller-reported route or response is mistaken for independently verified model evidence","recovery":"Treat attention observations as unverified data; run and cite a separate authorized provider evaluation."},"key":"0","section":"pitfalls"}
X A caller-reported route or response is mistaken for independently verified model evidence -> Treat attention observations as unverified data; run and cite a separate authorized provider evaluation.
-- @record {"chapter":"local-records","data":{"failure":"A situation revision or attention experiment ID is stale","recovery":"Read the selected owner state and retry with the current revision or a fresh experiment ID."},"key":"1","section":"pitfalls"}
X A situation revision or attention experiment ID is stale -> Read the selected owner state and retry with the current revision or a fresh experiment ID.
-- @record {"chapter":"local-records","data":"These records do not launch a provider, prove model improvement, or verify API responses.","key":"0","section":"frontier"}
F These records do not launch a provider, prove model improvement, or verify API responses.
-- @record {"chapter":"local-records","data":"Browser action, operator preference, and public promotion need separate authority and observation.","key":"1","section":"frontier"}
F Browser action, operator preference, and public promotion need separate authority and observation.
-- @record {"chapter":"local-records","data":"Use one workId consistently. Keep task contracts explicit and budget representation experiments.","key":"0","section":"guidance"}
M creative-records "Use one workId consistently. Keep task contracts explicit and budget representation experiments." src:"authored manual" state:verified
-- @record {"chapter":"local-records","data":"Preserve failed, missing, or route-mismatched observations rather than promoting a preferred variant.","key":"1","section":"guidance"}
M creative-records "Preserve failed, missing, or route-mismatched observations rather than promoting a preferred variant." src:"authored manual" state:verified
