CL 1
L critique-review v1 -- Authored executable manual
-- @manual {"chapters":{"workflow":{"title":"Executable critique-review method: chronological mechanism and measured quality"}},"clVersion":"1.1","id":"critique-review","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"neyvia.workflow.check":"t1","neyvia.workflow.record":"t1"},"tool_metadata":{"neyvia.workflow.check":{"mutability_class":"read"},"neyvia.workflow.record":{"mutability_class":"artifact_write"}}}
T t1{manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t2{report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"
L critique-review.workflow v1 -- Executable critique-review method: chronological mechanism and measured quality
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"critique-review","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.workflow.check"},"key":"adherence","section":"state"}
S critique-review.adherence:json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"=neyvia.workflow.check(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens)
-- @record {"chapter":"workflow","data":{"effect":"Validate ordered workflow evidence","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t3"},"reversible":true,"schema":"neyvia.workflow.check","tool":"neyvia.workflow.check"},"key":"check","section":"actions"}
A neyvia.workflow.check(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" -- Validate ordered workflow evidence
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"effect":"Persist a validated workflow receipt under the selected task root","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t3"},"reversible":false,"schema":"neyvia.workflow.record","tool":"neyvia.workflow.record"},"key":"record","section":"actions"}
A neyvia.workflow.record(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" ! -- Persist a validated workflow receipt under the selected task root
C neyvia.workflow.record adhered:neyvia.workflow.check(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"critique-review","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"expect":{"op":"eq","path":"accepted","value":true},"tool":"neyvia.workflow.check"},"key":"adhered","section":"checks"}
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"goal":"Verify defining workflow mechanism against host evidence and persist the acceptance receipt","inputs":{"$cl_type":"t2"},"steps":[{"action":"check","args":{"evidence":{"$input":"evidence"},"manual":"critique-review","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"verified"},{"action":"record","args":{"evidence":{"$input":"evidence"},"manual":"critique-review","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"recorded"}]},"key":"verify-and-record","section":"procedures"}
P verify-and-record(report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..):verified=neyvia.workflow.check(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered; recorded=neyvia.workflow.record(evidence:evidence manual:"critique-review" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered -- Verify defining workflow mechanism against host evidence and persist the acceptance receipt
V P verify-and-record -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"workflow","data":{"constraints":"Use an independent frozen host quality judge; self-reported quality is not evidence.","evidence":["artifact"],"kind":"model","options":["accept","revise"],"question":"Does the outcome satisfy the actual task, beyond recorded adherence?"},"key":"quality","section":"judge"}
J quality accept|revise:"Does the outcome satisfy the actual task, beyond recorded adherence?" -- Use an independent frozen host quality judge; self-reported quality is not evidence.
V J quality -> model:large evidence:artifact why:"model judgment bound to current evidence"
-- @record {"chapter":"workflow","data":{"failure":"A model writes its own successful receipt, outcome score or token count","recovery":"The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail"},"key":"0","section":"pitfalls"}
X A model writes its own successful receipt, outcome score or token count -> The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail
-- @record {"chapter":"workflow","data":"Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.","key":"0","section":"frontier"}
F Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.
-- @record {"chapter":"workflow","data":"Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.","key":"1","section":"frontier"}
F Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.
-- @record {"chapter":"workflow","data":"Compare the delivered result with the plan defining mechanism, rather than the name or appearance of a feature.","key":"0","section":"guidance"}
M critique-review "Compare the delivered result with the plan defining mechanism, rather than the name or appearance of a feature." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Attack your own result: record at least two failure paths and the evidence behind each; identify what was not shown.","key":"1","section":"guidance"}
M critique-review "Attack your own result: record at least two failure paths and the evidence behind each; identify what was not shown." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Verification references actual host receipts. Do not claim done while a required mechanism remains missing or any linked receipt failed.","key":"2","section":"guidance"}
M critique-review "Verification references actual host receipts. Do not claim done while a required mechanism remains missing or any linked receipt failed." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Report shape: {events:[{stage,data}],result:object}. Required chronological stages: plan, attack, verify, decision","key":"3","section":"guidance"}
M critique-review "Report shape: {events:[{stage,data}],result:object}. Required chronological stages: plan, attack, verify, decision" src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"plan{mechanism}; attack{risks:[{failure,evidence}]>=2}; verify{receipts:[host receipt IDs]}; decision{done:boolean,missing:[strings]}. Verification receipts have success:boolean.","key":"4","section":"guidance"}
M critique-review "plan{mechanism}; attack{risks:[{failure,evidence}]>=2}; verify{receipts:[host receipt IDs]}; decision{done:boolean,missing:[strings]}. Verification receipts have success:boolean." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified.","key":"5","section":"guidance"}
M critique-review "Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below.","key":"6","section":"guidance"}
M critique-review "Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"plan\",\"data\":{\"mechanism\":\"observable full task completion\"}},{\"stage\":\"attack\",\"data\":{\"risks\":[{\"failure\":\"main output lacks required wiring\",\"evidence\":\"observed source path missing\"},{\"failure\":\"failure case lacks recovery\",\"evidence\":\"captured failed journey\"}]}},{\"stage\":\"verify\",\"data\":{\"receipts\":[\"verification\"]}},{\"stage\":\"decision\",\"data\":{\"done\":false,\"missing\":[\"required wiring absent\"]}}],\"result\":{\"decision\":\"task-specific actual answer\"}}","key":"7","section":"guidance"}
M critique-review "Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"plan\",\"data\":{\"mechanism\":\"observable full task completion\"}},{\"stage\":\"attack\",\"data\":{\"risks\":[{\"failure\":\"main output lacks required wiring\",\"evidence\":\"observed source path missing\"},{\"failure\":\"failure case lacks recovery\",\"evidence\":\"captured failed journey\"}]}},{\"stage\":\"verify\",\"data\":{\"receipts\":[\"verification\"]}},{\"stage\":\"decision\",\"data\":{\"done\":false,\"missing\":[\"required wiring absent\"]}}],\"result\":{\"decision\":\"task-specific actual answer\"}}" src:"authored manual" state:verified
