CL 1
-- MODREL auth-read contract: unchanged session lookups use concurrent read snapshots.
-- Renewal, last-use, legacy upgrade and invalidation reread under a writer transaction;
-- revocation or account changes between snapshots must never resurrect a session.
L cross-pc v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Paired PCs: bounded reads and verified copies"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"proofs-e-wz":{"title":"PROOFS-e W-Z: live contracts and scratch self-checks"}},"clVersion":"1.1","id":"cross-pc","kind":"environment","proofs":{"area":"cross-pc","manifests":["config/proofs/proofs-e-models.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.devices.files.fetch":"t1","neyvia.devices.files.list":"t2","neyvia.devices.files.read":"t3","neyvia.devices.files.send":"t1","neyvia.devices.files.stat":"t4","neyvia.devices.list":"t5","neyvia.devices.transfers":"t6","neyvia.files.stat":"t7","proofs-e-models.status":"t5"},"tool_metadata":{"neyvia.devices.files.fetch":{"mutability_class":"artifact_write"},"neyvia.devices.files.list":{"mutability_class":"read"},"neyvia.devices.files.read":{"mutability_class":"read"},"neyvia.devices.files.send":{"mutability_class":"external_action"},"neyvia.devices.files.stat":{"mutability_class":"read"},"neyvia.devices.list":{"mutability_class":"read"},"neyvia.devices.transfers":{"mutability_class":"read"},"neyvia.files.stat":{"mutability_class":"read"},"neyvia.verify.status":{}}}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:dropIntent -> checkedProofsEModel"],"claim":"Only local move, remote take and local-to-remote send are offered; remote-to-remote is refused","id":"devices.dropIntent","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:sendTarget -> checkedProofsEModel"],"claim":"Remote writes require inbox, writable share or explicit write-anywhere permission","id":"devices.sendTarget","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:transferFraction -> checkedProofsEModel"],"claim":"Known byte progress clamps to 0..1; unknown sizes stay unknown except completed transfers","id":"devices.transferFraction","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:pcTarget -> checkedProofsEModel"],"claim":"Other-PC navigation preserves path delimiters","id":"devices.pcTarget","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:parsePcTarget -> checkedProofsEModel"],"claim":"Only pc: identifiers are decoded, splitting device once and preserving all path bars","id":"devices.parsePcTarget","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDevicesModel.js:transferLine -> checkedProofsEModel"],"claim":"Transfer labels preserve bytes, file counts, failure reason, measured speed and rounded remaining time","id":"devices.transferLine","impact":["devices frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_auth_sessions.WebAuthSessions.issue","grant_agent.proofs_e_wz.check_session_issued","grant_agent.proofs_e_wz.self_check"],"claim":"Issuance stores a 64-character token digest, exactly the requested normalized account identity/name/role and bounded device metadata, the selected creation/expiry times and every prior live session unchanged inside the SQLite write transaction; bearer tokens never become SQL values.","id":"proofs-e-wz.auth-issuance","impact":["web login","parallel browser sign-in","session database"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_auth_sessions.WebAuthSessions.lookup","grant_agent.proofs_e_wz.check_session_lookup","grant_agent.proofs_e_wz.self_check"],"claim":"Accepted lookup preserves account fields and creation time, upgrades an accepted legacy identity when needed, renews expiration only past the daily renewal threshold, and persists last-use updates atomically.","id":"proofs-e-wz.auth-renewal","impact":["long-lived web login","session expiry"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_auth_sessions.WebAuthSessions.lookup","grant_agent.proofs_e_wz.check_session_rejected","grant_agent.proofs_e_wz.self_check","grant_agent.web_auth_sessions.WebAuthSessions.revoke"],"claim":"Expired, invalid-account and invalid-role sessions are removed before lookup returns no user; explicit logout removes the token digest.","id":"proofs-e-wz.auth-rejection","impact":["password changes","idle expiry","logout"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend_serving.HttpServingMixin.serve_artifact","grant_agent.proofs_e_wz.check_artifact_access","grant_agent.proofs_e_wz.self_check","grant_agent.web_backend.FluxioWebBackend.web_auth_sessions","grant_agent.web_backend.FluxioWebBackend.authenticated_session"],"claim":"Private artifact file bytes are served only with a currently authenticated session; cookie validation reads the durable per-account fingerprint so backend recreation preserves valid sessions and password changes/logout revoke access.","id":"proofs-e-wz.auth-artifact","impact":["private media","preview iframe","backend recreation"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend._json_response","grant_agent.proofs_e_wz.check_json_response","grant_agent.proofs_e_wz.self_check"],"claim":"JSON wire bytes remain compact and exact through compression; gzip is used only for accepted encodings above the existing minimum response size.","id":"proofs-e-wz.http-json","impact":["browser transport","large chat responses"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend._read_json_body","grant_agent.proofs_e_wz.check_request_body","grant_agent.proofs_e_wz.self_check"],"claim":"Gzip request decoding never exceeds the configured maximum decompressed JSON bytes; over-limit inputs reject before dispatch.","id":"proofs-e-wz.http-request","impact":["phone transcript upload","bounded allocation"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.web_backend._extend_io_timeout","grant_agent.proofs_e_wz.check_io_timeout","grant_agent.proofs_e_wz.self_check"],"claim":"After a request starts, its socket uses the longer request IO timeout rather than the accept-time handshake timeout, allowing a paused reader to receive the full response.","id":"proofs-e-wz.http-io-timeout","impact":["slow phone readers","large transfers"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend_serving.HttpServingMixin.serve_file","grant_agent.proofs_e_wz.check_static_response","grant_agent.proofs_e_wz.self_check"],"claim":"Static files remain jailed in the selected build root and return exact file bytes; only approved desktop origins receive CORS for non-page assets. Entry pages/service workers stay uncached and embedded pages retain their supported framing policy.","id":"proofs-e-wz.desktop-shell","impact":["desktop loader","current build assets","browser security headers"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend_serving.HttpServingMixin.serve_desktop_update","grant_agent.proofs_e_wz.check_update_response","grant_agent.proofs_e_wz.self_check"],"claim":"Successful desktop update responses are allowlisted files strictly inside the update folder and contain the exact selected file bytes; unknown or escaping names cannot select a file.","id":"proofs-e-wz.desktop-update","impact":["public signed update feed","path confinement"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"device\":{\"type\":\"string\"},\"from\":{\"type\":\"string\"},\"to\":{\"type\":\"string\"},\"wait\":{\"type\":\"number\"}},\"required\":[\"device\",\"from\"],\"allOf\":[{\"properties\":{\"device\":{\"not\":{\"enum\":[\"\"]}},\"from\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"device\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"showHidden\":{\"type\":\"boolean\"}},\"required\":[\"device\"],\"allOf\":[{\"properties\":{\"device\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"device\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"offset\":{\"type\":\"integer\"},\"length\":{\"type\":\"integer\"}},\"required\":[\"device\",\"path\"],\"allOf\":[{\"properties\":{\"device\":{\"not\":{\"enum\":[\"\"]}},\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"device\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"preview\":{\"type\":\"boolean\"},\"hash\":{\"type\":\"boolean\"}},\"required\":[\"device\",\"path\"],\"allOf\":[{\"properties\":{\"device\":{\"not\":{\"enum\":[\"\"]}},\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{..}
T t6{id?:str ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"preview\":{\"type\":\"boolean\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8{}
T t9{here:json:"{\"type\":\"object\"}" devices:json:"{\"type\":\"array\"}" requests:json:"{\"type\":\"array\"}" transfers:json:"{\"type\":\"array\"}" tailnet:str ..}
T t10{transfers:json:"{\"type\":\"array\"}" ..}
T t11 json:"{\"type\":\"object\"}"
T t12{transfer:{id:str status:str sha256:str device:str from:str to:str size:int done:int ..} ..}
T t13{device:str from:str to:str}
T t14{device:str from:str}
T t15{id:str to:str size:int}
T t16{ok:bool ..}
T t17 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L cross-pc.overview v1 -- Paired PCs: bounded reads and verified copies
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.devices.list"},"key":"devices","section":"state"}
S cross-pc.devices:{here:json:"{\"type\":\"object\"}" devices:json:"{\"type\":\"array\"}" requests:json:"{\"type\":\"array\"}" transfers:json:"{\"type\":\"array\"}" tailnet:str ..}=neyvia.devices.list()
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t10"},"tool":"neyvia.devices.transfers"},"key":"transfers","section":"state"}
S cross-pc.transfers:{transfers:json:"{\"type\":\"array\"}" ..}=neyvia.devices.transfers()
-- @record {"chapter":"overview","data":{"effect":"Read saved PCs/requests/newest 30 transfers and cached tailnet status; online may be stale","pre":"Selected root peer store readable; no discovery/probing required","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.devices.list","tool":"neyvia.devices.list"},"key":"devices.list","section":"actions"}
A neyvia.devices.list() -> json:"{\"type\":\"object\"}" -- Read saved PCs/requests/newest 30 transfers and cached tailnet status; online may be stale
F verify-devices-list "No authored observer check is bound to neyvia.devices.list" -> ask operator blocks:neyvia.devices.list
-- @record {"chapter":"overview","data":{"effect":"Read remote places or folder entries (max 2000); refresh advertised theyShare when returned","pre":"Device ID is paired, reachable with DPAPI-protected pair token; path absent for places or inside remote shared folder/inbox","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.devices.files.list","tool":"neyvia.devices.files.list"},"key":"devices.files.list","section":"actions"}
A neyvia.devices.files.list(device:str path?:str showHidden?:bool) -> json:"{\"type\":\"object\"}" -- Read remote places or folder entries (max 2000); refresh advertised theyShare when returned
F verify-devices-files-list "No authored observer check is bound to neyvia.devices.files.list" -> ask operator blocks:neyvia.devices.files.list
-- @record {"chapter":"overview","data":{"effect":"Read remote kind/size/mime, optional 64 KiB text preview and SHA-256","pre":"Paired reachable PC; existing path inside its shares/inbox; hash only files <=2 GiB","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.devices.files.stat","tool":"neyvia.devices.files.stat"},"key":"devices.files.stat","section":"actions"}
A neyvia.devices.files.stat(device:str path:str preview?:bool hash?:bool) -> json:"{\"type\":\"object\"}" -- Read remote kind/size/mime, optional 64 KiB text preview and SHA-256
F verify-devices-files-stat "No authored observer check is bound to neyvia.devices.files.stat" -> ask operator blocks:neyvia.devices.files.stat
-- @record {"chapter":"overview","data":{"effect":"Read bounded remote bytes, UTF-8 text or base64, size/eof; no local copy","pre":"Paired reachable PC; shared existing file; nonnegative offset and length 0..1 MiB","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.devices.files.read","tool":"neyvia.devices.files.read"},"key":"devices.files.read","section":"actions"}
A neyvia.devices.files.read(device:str path:str offset?:int length?:int) -> json:"{\"type\":\"object\"}" -- Read bounded remote bytes, UTF-8 text or base64, size/eof; no local copy
F verify-devices-files-read "No authored observer check is bound to neyvia.devices.files.read" -> ask operator blocks:neyvia.devices.files.read
-- @record {"chapter":"overview","data":{"effect":"Create destination folder if missing and start chunk-verified Take; collision gets unique path; wait may return unfinished; use transfer.to","pre":"Paired reachable PC and shared source; safe local destination is/createable as a folder; <=5000 files/50 GiB; artifact-write authority","returns":{"$cl_type":"t12"},"reversible":false,"schema":"neyvia.devices.files.fetch","tool":"neyvia.devices.files.fetch"},"key":"devices.files.fetch","section":"actions"}
A neyvia.devices.files.fetch(device:str from:str to?:str wait?:num) -> {transfer:{id:str status:str sha256:str device:str from:str to:str size:int done:int ..} ..} ! -- Create destination folder if missing and start chunk-verified Take; collision gets unique path; wait may return unfinished; use transfer.to
C neyvia.devices.files.fetch fresh-fetch-complete:neyvia.devices.transfers(id:result.transfer.id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"effect":"Start chunk/hash-verified Send without overwrite; wait may return pending; transfer.to is actual received path","pre":"Paired reachable PC; local readable source; remote existing inbox/writable folder; owner grants devices:send:<id>; <=5000 files/50 GiB","returns":{"$cl_type":"t12"},"reversible":false,"schema":"neyvia.devices.files.send","tool":"neyvia.devices.files.send"},"key":"devices.files.send","section":"actions"}
A neyvia.devices.files.send(device:str from:str to?:str wait?:num) -> {transfer:{id:str status:str sha256:str device:str from:str to:str size:int done:int ..} ..} ! -- Start chunk/hash-verified Send without overwrite; wait may return pending; transfer.to is actual received path
C neyvia.devices.files.send fresh-send-complete:neyvia.devices.transfers(id:result.transfer.id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"effect":"Read newest 30 matching transfers with progress/status/error and end-to-end SHA-256","pre":"Selected root transfer store readable; optional id selects retained transfer","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.devices.transfers","tool":"neyvia.devices.transfers"},"key":"devices.transfers","section":"actions"}
A neyvia.devices.transfers(id?:str) -> json:"{\"type\":\"object\"}" -- Read newest 30 matching transfers with progress/status/error and end-to-end SHA-256
C neyvia.devices.transfers transfer-done:neyvia.devices.transfers(id:id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"effect":"Return kind/size/openWith; preview=true reads first 64 KiB only for text/notes","pre":"Existing guarded path inside a Files place outside protected tree","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.files.stat","tool":"neyvia.files.stat"},"key":"files.stat","section":"actions"}
A neyvia.files.stat(path:str preview?:bool) -> json:"{\"type\":\"object\"}" -- Return kind/size/openWith; preview=true reads first 64 KiB only for text/notes
C neyvia.files.stat received-size:neyvia.files.stat(path:to) .size == size
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"transfers.0.status","value":"done"},"tool":"neyvia.devices.transfers"},"key":"transfer-done","section":"checks"}
C neyvia.devices.transfers transfer-done:neyvia.devices.transfers(id:id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"args":{"path":{"$path":"to"}},"expect":{"op":"eq","path":"size","value":{"$input":"size"}},"tool":"neyvia.files.stat"},"key":"received-size","section":"checks"}
C neyvia.files.stat received-size:neyvia.files.stat(path:to) .size == size
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"copied.transfer.id"}},"expect":{"op":"eq","path":"transfers.0.status","value":"done"},"tool":"neyvia.devices.transfers"},"key":"fresh-fetch-complete","section":"checks"}
C neyvia.devices.transfers fresh-fetch-complete:neyvia.devices.transfers(id:copied.transfer.id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"copied.transfer.id"}},"expect":{"op":"eq","path":"transfers.0.status","value":"done"},"tool":"neyvia.devices.transfers"},"key":"fresh-send-complete","section":"checks"}
C neyvia.devices.transfers fresh-send-complete:neyvia.devices.transfers(id:copied.transfer.id) .transfers.0.status == "done"
-- @record {"chapter":"overview","data":{"goal":"Inspect remote file and copy into existing local folder without overwrite; inspect newest transfers and retain the matching returned ID for separate completion verification","inputs":{"$cl_type":"t13"},"steps":[{"action":"devices.files.stat","args":{"device":{"$input":"device"},"path":{"$input":"from"}},"save":"source"},{"judge":"take-or-stop"},{"action":"devices.files.fetch","args":{"device":{"$input":"device"},"from":{"$input":"from"},"to":{"$path":"to"}},"save":"copied","when":{"judge":"take-or-stop","option":"take"}},{"action":"devices.transfers","args":{},"save":"progress","when":{"judge":"take-or-stop","option":"take"}}]},"key":"take-file","section":"procedures"}
P take-file(device:str from:str to:str):source=neyvia.devices.files.stat(device:device path:from); J take-or-stop=take; copied=neyvia.devices.files.fetch(device:device from:from to:to); progress=neyvia.devices.transfers() -- Inspect remote file and copy into existing local folder without overwrite; inspect newest transfers and retain the matching returned ID for separate completion verification
V P take-file -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Inspect local source and remote shares, then send a requested file to default inbox; inspect newest transfers and retain the matching returned ID for separate completion verification","inputs":{"$cl_type":"t14"},"steps":[{"action":"files.stat","args":{"path":{"$path":"from"}},"save":"local"},{"action":"devices.files.list","args":{"device":{"$input":"device"}},"save":"places"},{"judge":"send-destination"},{"action":"devices.files.send","args":{"device":{"$input":"device"},"from":{"$path":"from"}},"save":"copied","when":{"judge":"send-destination","option":"send-inbox"}},{"action":"devices.transfers","args":{},"save":"progress","when":{"judge":"send-destination","option":"send-inbox"}}]},"key":"send-to-inbox","section":"procedures"}
P send-to-inbox(device:str from:str):local=neyvia.files.stat(path:from); places=neyvia.devices.files.list(device:device); J send-destination=send-inbox; copied=neyvia.devices.files.send(device:device from:from); progress=neyvia.devices.transfers() -- Inspect local source and remote shares, then send a requested file to default inbox; inspect newest transfers and retain the matching returned ID for separate completion verification
V P send-to-inbox -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Inspect a saved Take transfer, confirm done and verify actual received file size","inputs":{"$cl_type":"t15"},"steps":[{"action":"devices.transfers","args":{"id":{"$input":"id"}},"save":"progress"},{"judge":"copy-status"},{"action":"devices.transfers","args":{"id":{"$input":"id"}},"check":"transfer-done","save":"done","when":{"judge":"copy-status","option":"verify-done"}},{"action":"devices.transfers","args":{"id":{"$input":"id"}},"save":"digest","when":{"judge":"copy-status","option":"verify-done"}},{"action":"files.stat","args":{"path":{"$path":"to"}},"check":"received-size","save":"received","when":{"judge":"copy-status","option":"verify-done"}}]},"key":"verify-taken-file","section":"procedures"}
P verify-taken-file(id:str to:str size:int):progress=neyvia.devices.transfers(id:id); J copy-status=verify-done; done=neyvia.devices.transfers(id:id) C transfer-done; digest=neyvia.devices.transfers(id:id); received=neyvia.files.stat(path:to) C received-size -- Inspect a saved Take transfer, confirm done and verify actual received file size
V P verify-taken-file -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Copy an already paired explicitly requested regular file <=64 MiB into an explicit folder; conserve source, refuse overwrite, and verify fresh bytes at both endpoints","inputs":{"$cl_type":"t13"},"steps":[{"action":"devices.files.fetch","args":{"device":{"$input":"device"},"from":{"$input":"from"},"to":{"$input":"to"},"wait":30},"check":"fresh-fetch-complete","save":"copied"}]},"key":"copy-file-fetch-verified","section":"procedures"}
P copy-file-fetch-verified(device:str from:str to:str):copied=neyvia.devices.files.fetch(device:device from:from to:to wait:30) C fresh-fetch-complete -- Copy an already paired explicitly requested regular file <=64 MiB into an explicit folder; conserve source, refuse overwrite, and verify fresh bytes at both endpoints
V P copy-file-fetch-verified -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Copy an already paired explicitly requested regular file <=64 MiB into an explicit folder; conserve source, refuse overwrite, and verify fresh bytes at both endpoints","inputs":{"$cl_type":"t13"},"steps":[{"action":"devices.files.send","args":{"device":{"$input":"device"},"from":{"$input":"from"},"to":{"$input":"to"},"wait":30},"check":"fresh-send-complete","save":"copied"}]},"key":"copy-file-send-verified","section":"procedures"}
P copy-file-send-verified(device:str from:str to:str):copied=neyvia.devices.files.send(device:device from:from to:to wait:30) C fresh-send-complete -- Copy an already paired explicitly requested regular file <=64 MiB into an explicit folder; conserve source, refuse overwrite, and verify fresh bytes at both endpoints
V P copy-file-send-verified -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Use device ID, not hostname. list is cached and online can be stale; refresh shares via files.list. Pair/revoke/share/discover and transfer controls belong to owner UI. Do not probe other services or reconfigure tailnet.","options":["read","stop"],"question":"Is this the intended paired and reachable PC with the required share?"},"key":"remote-identity","section":"judge"}
J remote-identity read|stop:"Is this the intended paired and reachable PC with the required share?" -- Use device ID, not hostname. list is cached and online can be stale; refresh shares via files.list. Pair/revoke/share/discover and transfer controls belong to owner UI. Do not probe other services or reconfigure tailnet.
V J remote-identity -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"For one-off bounded text use read-remote-range. Take when another app needs real file or more than a bounded range. Folder copies require explicit folder request, <=5000 files/50 GiB; this procedure verifies one file only.","options":["take","stop"],"question":"Is this remote item needed as a local file?"},"key":"take-or-stop","section":"judge"}
J take-or-stop take|stop:"Is this remote item needed as a local file?" -- For one-off bounded text use read-remote-range. Take when another app needs real file or more than a bounded range. Folder copies require explicit folder request, <=5000 files/50 GiB; this procedure verifies one file only.
V J take-or-stop -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Read saved transfer status. running/verifying/paused/failed is pending and cannot be called success; poll transfers(id), do not invoke fetch/send again. Owner UI handles pause/resume/cancel. For verify-taken-file, id/to/size must come from the same saved direction=take transfer; compare SHA-256 to remote source if integrity matters.","options":["verify-done","pending"],"question":"Has the saved transfer completed with end-to-end SHA-256?"},"key":"copy-status","section":"judge"}
J copy-status verify-done|pending:"Has the saved transfer completed with end-to-end SHA-256?" -- Read saved transfer status. running/verifying/paused/failed is pending and cannot be called success; poll transfers(id), do not invoke fetch/send again. Owner UI handles pause/resume/cancel. For verify-taken-file, id/to/size must come from the same saved direction=take transfer; compare SHA-256 to remote source if integrity matters.
V J copy-status -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Default inbox is preferred. First model Send returns approval_required and owner must approve devices:send:<id>. A named writable share requires observed write:true/writeAnywhere; do not infer consent from pairing.","options":["send-inbox","stop"],"question":"Send to the paired PC inbox or defer until destination is clarified?"},"key":"send-destination","section":"judge"}
J send-destination send-inbox|stop:"Send to the paired PC inbox or defer until destination is clarified?" -- Default inbox is preferred. First model Send returns approval_required and owner must approve devices:send:<id>. A named writable share requires observed write:true/writeAnywhere; do not infer consent from pairing.
V J send-destination -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Unpaired/revoked token or PC unreachable","recovery":"Stop and name the device; owner pairs/unpairs or turns PC on through Accounts. Do not reconfigure network"},"key":"0","section":"pitfalls"}
X Unpaired/revoked token or PC unreachable -> Stop and name the device; owner pairs/unpairs or turns PC on through Accounts. Do not reconfigure network
-- @record {"chapter":"overview","data":{"failure":"Destination collision changes name","recovery":"Use saved transfer.to; receiver chooses name (2).ext and never overwrites"},"key":"1","section":"pitfalls"}
X Destination collision changes name -> Use saved transfer.to; receiver chooses name (2).ext and never overwrites
-- @record {"chapter":"overview","data":{"failure":"Send returns approval_required","recovery":"Owner approves exact peer scope; reconcile failed manual run, then begin a new reviewed procedure after grant"},"key":"2","section":"pitfalls"}
X Send returns approval_required -> Owner approves exact peer scope; reconcile failed manual run, then begin a new reviewed procedure after grant
-- @record {"chapter":"overview","data":{"failure":"Source changes or hash/range mismatch while copying","recovery":"Inspect failed receipt/partial; do not claim complete; a new intent after source reconciliation is required"},"key":"3","section":"pitfalls"}
X Source changes or hash/range mismatch while copying -> Inspect failed receipt/partial; do not claim complete; a new intent after source reconciliation is required
-- @record {"chapter":"overview","data":{"failure":"Backend restart pauses transfer","recovery":"Owner resumes from verified chunks; poll retained ID, never duplicate copy"},"key":"4","section":"pitfalls"}
X Backend restart pauses transfer -> Owner resumes from verified chunks; poll retained ID, never duplicate copy
-- @record {"chapter":"overview","data":{"failure":"Read UTF-8 range splits multibyte character","recovery":"Offsets are bytes and decoder replaces incomplete sequences; fetch full file for exact Unicode"},"key":"5","section":"pitfalls"}
X Read UTF-8 range splits multibyte character -> Offsets are bytes and decoder replaces incomplete sequences; fetch full file for exact Unicode
-- @record {"chapter":"overview","data":{"failure":"Remote path outside share or inbox","recovery":"List shared places and use remote full path; no traversal or local path translation"},"key":"6","section":"pitfalls"}
X Remote path outside share or inbox -> List shared places and use remote full path; no traversal or local path translation
-- @record {"chapter":"overview","data":"No remote delete/rename/move/live sync; copies are one-off","key":"0","section":"frontier"}
F No remote delete/rename/move/live sync; copies are one-off
-- @record {"chapter":"overview","data":"No direct other-PC-to-other-PC transfer; Take here then Send","key":"1","section":"frontier"}
F No direct other-PC-to-other-PC transfer; Take here then Send
-- @record {"chapter":"overview","data":"Phones/NAS are not peers of this PC feature","key":"2","section":"frontier"}
F Phones/NAS are not peers of this PC feature
-- @record {"chapter":"overview","data":"Model transfer controls/pairing/discovery are unavailable; owner UI only","key":"3","section":"frontier"}
F Model transfer controls/pairing/discovery are unavailable; owner UI only
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_devices.py (peer, scoped, call_devices, _start_transfer, _copy_worker). Original docs/manuals/cross-pc.md converted in place.","key":"0","section":"guidance"}
M cross-pc "Source: src/grant_agent/neyvia_devices.py (peer, scoped, call_devices, _start_transfer, _copy_worker). Original docs/manuals/cross-pc.md converted in place." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Checks for Send: transfers(id).status == done, then devices.files.stat(device, transfer.to).size == transfer.size; compare verified transfer.sha256 when required.","key":"1","section":"guidance"}
M cross-pc "Checks for Send: transfers(id).status == done, then devices.files.stat(device, transfer.to).size == transfer.size; compare verified transfer.sha256 when required." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Continue reads with offset += returned.length until eof; never advance by requested length after a short read.","key":"2","section":"guidance"}
M cross-pc "Continue reads with offset += returned.length until eof; never advance by requested length after a short read." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Local scratch validation reads saved peer state only; it does not discover PCs, access port 47881 or touch Tailscale.","key":"3","section":"guidance"}
M cross-pc "Local scratch validation reads saved peer state only; it does not discover PCs, access port 47881 or touch Tailscale." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Durable gateway mutations may wrap data under toolResult. After launching Take/Send, transfers() lists retained IDs; select matching device/from/direction/by, then verify that ID. Never pick the first row blindly or relaunch to obtain an ID.","key":"4","section":"guidance"}
M cross-pc "Durable gateway mutations may wrap data under toolResult. After launching Take/Send, transfers() lists retained IDs; select matching device/from/direction/by, then verify that ID. Never pick the first row blindly or relaunch to obtain an ID." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"CL paired-file copy effects require an explicit destination folder and regular file <=64 MiB; directory/large copies remain native-only frontier; queued status never means complete.","key":"5","section":"guidance"}
M cross-pc "CL paired-file copy effects require an explicit destination folder and regular file <=64 MiB; directory/large copies remain native-only frontier; queued status never means complete." src:"authored manual" state:verified
L cross-pc.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t16"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S cross-pc.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t17"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" ! -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t5"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"devices.dropIntent: Only local move, remote take and local-to-remote send are offered; remote-to-remote is refused","key":"0","section":"guidance"}
M cross-pc "devices.dropIntent: Only local move, remote take and local-to-remote send are offered; remote-to-remote is refused" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"devices.sendTarget: Remote writes require inbox, writable share or explicit write-anywhere permission","key":"1","section":"guidance"}
M cross-pc "devices.sendTarget: Remote writes require inbox, writable share or explicit write-anywhere permission" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"devices.transferFraction: Known byte progress clamps to 0..1; unknown sizes stay unknown except completed transfers","key":"2","section":"guidance"}
M cross-pc "devices.transferFraction: Known byte progress clamps to 0..1; unknown sizes stay unknown except completed transfers" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"devices.pcTarget: Other-PC navigation preserves path delimiters","key":"3","section":"guidance"}
M cross-pc "devices.pcTarget: Other-PC navigation preserves path delimiters" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"devices.parsePcTarget: Only pc: identifiers are decoded, splitting device once and preserving all path bars","key":"4","section":"guidance"}
M cross-pc "devices.parsePcTarget: Only pc: identifiers are decoded, splitting device once and preserving all path bars" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"devices.transferLine: Transfer labels preserve bytes, file counts, failure reason, measured speed and rounded remaining time","key":"5","section":"guidance"}
M cross-pc "devices.transferLine: Transfer labels preserve bytes, file counts, failure reason, measured speed and rounded remaining time" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"6","section":"guidance"}
M cross-pc "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L cross-pc.proofs-e-wz v1 -- PROOFS-e W-Z: live contracts and scratch self-checks
-- @record {"chapter":"proofs-e-wz","data":{"failure":"A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement","recovery":"Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion"},"key":"0","section":"pitfalls"}
X A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement -> Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion
-- @record {"chapter":"proofs-e-wz","data":"Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.","key":"0","section":"frontier"}
F Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.
-- @record {"chapter":"proofs-e-wz","data":"Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.","key":"1","section":"frontier"}
F Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.
-- @record {"chapter":"proofs-e-wz","data":"Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.","key":"2","section":"frontier"}
F Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.
-- @record {"chapter":"proofs-e-wz","data":"The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.","key":"3","section":"frontier"}
F The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.
-- @record {"chapter":"proofs-e-wz","data":"Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz","key":"0","section":"guidance"}
M cross-pc "Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action.","key":"1","section":"guidance"}
M cross-pc "Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection.","key":"2","section":"guidance"}
M cross-pc "Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection." src:"authored manual" state:verified
