CL 1
L dictation v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Local speech engine: availability and authorized file transcription"},"prompts":{"title":"Prompt dictation in the composer, new chat and Notes: live words, spoken commands, language routing, names"}},"clVersion":"1.1","id":"dictation","kind":"environment","proofs":{"area":"dictation"},"schema":"neyvia.manual.v1","schemas":{"neyvia.dictation.names":"t1","neyvia.dictation.process":"t2","neyvia.dictation.status":"t3","neyvia.dictation.transcribe":"t4"},"tool_metadata":{"neyvia.dictation.names":{"mutability_class":"none"},"neyvia.dictation.process":{"mutability_class":"none"},"neyvia.dictation.status":{"mutability_class":"read"},"neyvia.dictation.transcribe":{"mutability_class":"none"}}}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation.names","grant_agent.proofs_dictation.after"],"claim":"Name add/remove persists exactly the requested aliases and the names observer reports persisted plus built-in aliases.","id":"dictation.names.persisted","impact":[".neyvia/dictation-names.json","dictation.process","dictation stream/finalization"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation.names","grant_agent.proofs_dictation.after","grant_agent.proofs_dictation.self_check"],"claim":"Names are read and written only under the selected state root; a name taught in one workspace does not change another workspace's prompt policy.","id":"dictation.names.scoped","impact":["workspace dictation policy","other workspaces"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_prompt_dictation.process_prompt","grant_agent.neyvia_dictation.process","grant_agent.proofs_dictation.check_prompt"],"claim":"The prompt is assembled only from ordered text segments; preview is required and stable/provisional match finality. An unfinished hypothesis is literal and has no editor commands.","id":"dictation.prompt.structure","impact":["composer preview","Notes prompt","desktop and HTTP dictation"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_prompt_dictation.process_prompt","grant_agent.proofs_dictation.check_prompt"],"claim":"Known whole and terminal spoken commands become ordered command segments instead of prompt words; emitted commands equal the command segments. Quoted text remains literal in scratch procedures.","id":"dictation.prompt.commands","impact":["editor spoken commands","send preview"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_prompt_dictation.process_prompt","grant_agent.proofs_dictation.check_prompt"],"claim":"French and mixed utterances select qwen, while English and unknown select phonon2; the French utterance goal is exercised by the shared parser.","id":"dictation.prompt.route","impact":["speech engine routing","local fallback availability"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation.stream","grant_agent.proofs_dictation.validate_stream"],"claim":"Unknown stream operations, invalid ids, oversized chunks, odd PCM and negative sequences are rejected before any settings lookup, session allocation, timer or speech-engine call.","id":"dictation.stream.preallocation","impact":["stream sessions","PCM memory","speech engine calls"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation_providers.Transcript","grant_agent.neyvia_dictation.stream","grant_agent.proofs_dictation.provider_checks"],"claim":"Live words from a streaming provider only grow in order: deltas of the segment being heard stay provisional, a segment locks only when it and every earlier one are complete, and a locked segment is never edited. Checked with the recorded sample fed in 250 ms pieces to a scripted provider.","id":"dictation.provider.partials","impact":["live dictation words","stable/grey split","Voice settings provider choice"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation_providers.OpenAIStream.finish","grant_agent.neyvia_dictation.stream","grant_agent.proofs_dictation.provider_checks"],"claim":"Release commits the provider's audio, waits for the completed segments, and returns one final text that still goes through the prompt policy and preview.","id":"dictation.provider.finalise","impact":["final dictation text","send preview"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_dictation_providers.choose","grant_agent.neyvia_dictation._stream_step","grant_agent.proofs_dictation.provider_checks"],"claim":"A provider that is not usable (no key, local-only on, address not api.openai.com, Codex signed in with a ChatGPT plan, or a connection that drops mid-dictation) never loses speech: the local engine takes over with all audio heard so far, numbered from zero, and one plain sentence says so.","id":"dictation.provider.fallback","impact":["dictation provider choice","local engine","network policy"],"phase":"invariant"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationReveal.js:wordsShown -> checkedDictationAction -> DICTATION_CONTRACTS.wordsShown"],"claim":"Paced words never go backwards or past the engine's answer, the first word of a batch shows at once, and the whole batch shows by the next answer.","id":"dictation.reveal","impact":["live dictation strip","composer ghost text"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationProviders.js:providerChoices -> checkedDictationAction -> DICTATION_CONTRACTS.providerChoices"],"claim":"Settings lists local first as the default, an unavailable provider always carries one plain reason, and at most the chosen provider is selected.","id":"dictation.providers","impact":["Voice settings"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:shiftAnchor -> checkedDictationAction -> DICTATION_CONTRACTS.shiftAnchor"],"claim":"Insertion at/before the caret follows typing; edits after it retain the prefix anchor","id":"dictation.anchor","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:endsMidSentence -> checkedDictationAction -> DICTATION_CONTRACTS.endsMidSentence"],"claim":"Only an unterminated nonblank line continues a sentence","id":"dictation.sentence-state","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:joinSpoken -> checkedDictationAction -> DICTATION_CONTRACTS.joinSpoken"],"claim":"Preserve the field prefix, sentence capitalization, names and punctuation spacing","id":"dictation.join","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:lastSentenceStart -> checkedDictationAction -> DICTATION_CONTRACTS.lastSentenceStart"],"claim":"The last sentence starts after the latest complete terminator or line boundary","id":"dictation.sentence-boundary","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:dropLastPhrase -> checkedDictationAction -> DICTATION_CONTRACTS.dropLastPhrase"],"claim":"Scratch removes only the final phrase and its joining horizontal spaces","id":"dictation.scratch","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:dropLastSentence -> checkedDictationAction -> DICTATION_CONTRACTS.dropLastSentence"],"claim":"Delete only the final sentence, preserving prior lines","id":"dictation.delete-sentence","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:applySegments -> checkedDictationAction -> DICTATION_CONTRACTS.applySegments"],"claim":"Execute segments in order; preserve suffix; cancel restores original; caller owns send/undo/history","id":"dictation.edit","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:previewParts -> checkedDictationAction -> DICTATION_CONTRACTS.previewParts"],"claim":"Preview uses commit spacing/capitalization while retaining stable/provisional separation","id":"dictation.preview","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:withoutOverlap -> checkedDictationAction -> DICTATION_CONTRACTS.withoutOverlap"],"claim":"Remove the longest settled suffix or complete decode prefix, preserving fresh words","id":"dictation.overlap","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:normalizeAnswer -> checkedDictationAction -> DICTATION_CONTRACTS.normalizeAnswer"],"claim":"Legacy partial/final text remains usable; current stable words and command segments survive normalization","id":"dictation.answer","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxDictationEdit.js:liveCommands -> checkedDictationAction -> DICTATION_CONTRACTS.liveCommands"],"claim":"Command chips contain only decided commands in stream order","id":"dictation.commands","impact":["prompt composer text/caret","Notes dictation text","stream provisional overlay"],"phase":"post"}
T t1{action?:json:"{\"type\":\"string\",\"enum\":[\"list\",\"add\",\"remove\"]}" to?:str from?:json:"{\"type\":[\"string\",\"array\"],\"items\":{\"type\":\"string\"}}" ..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\"},\"history\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"maxItems\":20},\"final\":{\"type\":\"boolean\"}},\"required\":[\"text\"],\"allOf\":[{\"properties\":{\"text\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{start?:bool ..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"engine\":{\"type\":\"string\",\"enum\":[\"auto\",\"phonon2\",\"qwen\"]},\"history\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"maxItems\":20}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{}
T t6{state:str engine:str enabled:bool ..}
T t7 json:"{\"type\":\"object\"}"
T t8{path:str engine:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"phonon2\",\"qwen\"]}"}
T t9{state:str device?:any url?:str engines?:json:"{\"type\":\"object\"}" recentLanguage?:any ..}
T t10{names:[json:"{\"type\":\"object\",\"properties\":{\"to\":{\"type\":\"string\"},\"from\":{\"type\":\"array\"},\"builtin\":{\"type\":\"boolean\"}}}"] ..}
T t11{state:str ..}
T t12{text:str segments:json:"{\"type\":\"array\"}" commands:json:"{\"type\":\"array\"}" fixes:json:"{\"type\":\"array\"}" language:str route:str requiresPreview?:bool ..}
T t13{names:json:"{\"type\":\"array\"}" ..}
T t14{text:str ..}
T t15{heard:str aliases:json:"{\"type\":[\"string\",\"array\"],\"items\":{\"type\":\"string\"}}" name:str}
T t16{text:str op:str}
T t17{text:str}
T t18{action:json:"{\"enum\":[\"list\",\"add\",\"remove\"],\"type\":\"string\"}" from:json:"{\"items\":{\"type\":\"string\"},\"type\":[\"string\",\"array\"]}" to:str ..}
T t19 json:"{\"properties\":{\"final\":{\"type\":\"boolean\"},\"history\":{\"items\":{\"type\":\"string\"},\"maxItems\":20,\"type\":\"array\"},\"text\":{\"type\":\"string\"}},\"required\":[\"text\",\"final\",\"history\"],\"type\":\"object\"}"
L dictation.overview v1 -- Local speech engine: availability and authorized file transcription
-- @record {"chapter":"overview","data":{"args":{"start":false},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t6"},"tool":"neyvia.dictation.status"},"key":"engine","section":"state"}
S dictation.engine:{state:str engine:str enabled:bool ..}=neyvia.dictation.status(start:false)
-- @record {"chapter":"overview","data":{"effect":"Read missing/off/starting/ready/error and configured engine; start=true may launch it","pre":"start=false for observation; start=true only with authorization to launch the configured local engine","returns":{"$cl_type":"t6"},"reversible":false,"schema":"neyvia.dictation.status","tool":"neyvia.dictation.status"},"key":"dictation.status","section":"actions"}
A neyvia.dictation.status(start?:bool) -> {state:str engine:str enabled:bool ..} -- Read missing/off/starting/ready/error and configured engine; start=true may launch it
F verify-dictation-status "No authored observer check is bound to neyvia.dictation.status" -> ask operator blocks:neyvia.dictation.status
-- @record {"chapter":"overview","data":{"effect":"Return text, selected engine, language guess and timings from the existing shared speech service","pre":"Readable audio file; configured engine installed; permission to use or start the local speech engine; qwen requires its service","returns":{"$cl_type":"t7"},"reversible":false,"schema":"neyvia.dictation.transcribe","tool":"neyvia.dictation.transcribe"},"key":"dictation.transcribe","section":"actions"}
A neyvia.dictation.transcribe(path:str engine?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"phonon2\",\"qwen\"]}" history?:[str]#..20) -> json:"{\"type\":\"object\"}" -- Return text, selected engine, language guess and timings from the existing shared speech service
F verify-dictation-transcribe "No authored observer check is bound to neyvia.dictation.transcribe" -> ask operator blocks:neyvia.dictation.transcribe
-- @record {"chapter":"overview","data":{"args":{"start":false},"expect":{"op":"eq","path":"state","value":"ready"},"tool":"neyvia.dictation.status"},"key":"ready","section":"checks"}
C neyvia.dictation.status ready:neyvia.dictation.status(start:false) .state == "ready"
-- @record {"chapter":"overview","data":{"goal":"Inspect engine availability and transcribe an authorized audio file with the chosen engine","inputs":{"$cl_type":"t8"},"steps":[{"action":"dictation.status","args":{"start":false},"save":"status"},{"judge":"engine-choice"},{"action":"dictation.transcribe","args":{"engine":{"$input":"engine"},"path":{"$input":"path"}},"save":"transcript","when":{"judge":"engine-choice","option":"transcribe"}}]},"key":"transcribe-file","section":"procedures"}
P transcribe-file(path:str engine:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"phonon2\",\"qwen\"]}"):status=neyvia.dictation.status(start:false); J engine-choice=transcribe; transcript=neyvia.dictation.transcribe(engine:engine path:path) -- Inspect engine availability and transcribe an authorized audio file with the chosen engine
V P transcribe-file -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Phonon-2 is the English prompt path; qwen needs the configured service for French/mixed audio. Stop on missing dependencies or unapproved service launch.","options":["transcribe","stop"],"question":"Is the installed selected engine appropriate and authorized for this audio?"},"key":"engine-choice","section":"judge"}
J engine-choice transcribe|stop:"Is the installed selected engine appropriate and authorized for this audio?" -- Phonon-2 is the English prompt path; qwen needs the configured service for French/mixed audio. Stop on missing dependencies or unapproved service launch.
V J engine-choice -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Engine missing, disabled, or fails to start","recovery":"Read status.error; check saved engine paths. Do not install, download, restart another service, or substitute a provider silently."},"key":"0","section":"pitfalls"}
X Engine missing, disabled, or fails to start -> Read status.error; check saved engine paths. Do not install, download, restart another service, or substitute a provider silently.
-- @record {"chapter":"overview","data":{"failure":"Wrong language path or failed audio decode","recovery":"Choose the explicit supported engine and a readable audio file; preserve the original audio."},"key":"1","section":"pitfalls"}
X Wrong language path or failed audio decode -> Choose the explicit supported engine and a readable audio file; preserve the original audio.
-- @record {"chapter":"overview","data":"Actual microphone WER and release-to-text latency require reviewed recordings and live UI proof; validation alone proves neither.","key":"0","section":"frontier"}
F Actual microphone WER and release-to-text latency require reviewed recordings and live UI proof; validation alone proves neither.
-- @record {"chapter":"overview","data":"User side: mic in the composer, new chat and Notes. Click to talk, click again to insert; hold the mic or Ctrl+Shift+Space to talk while held; Esc cancels.","key":"0","section":"guidance"}
M dictation "User side: mic in the composer, new chat and Notes. Click to talk, click again to insert; hold the mic or Ctrl+Shift+Space to talk while held; Esc cancels." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"While talking the words appear in the box: settled words in the normal colour, the newest grey. Settled words never jump; a late change shimmers and never moves the caret.","key":"1","section":"guidance"}
M dictation "While talking the words appear in the box: settled words in the normal colour, the newest grey. Settled words never jump; a late change shimmers and never moves the caret." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Commands: new line, new paragraph, scratch that (anywhere); undo that, cancel (alone); delete the last sentence, send it (alone or at the end). French: à la ligne, nouveau paragraphe, efface ça, annule ça, supprime la dernière phrase, envoie, annule. 'literally new line' types the words.","key":"2","section":"guidance"}
M dictation "Commands: new line, new paragraph, scratch that (anywhere); undo that, cancel (alone); delete the last sentence, send it (alone or at the end). French: à la ligne, nouveau paragraphe, efface ça, annule ça, supprime la dernière phrase, envoie, annule. 'literally new line' types the words." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Source: web/src/neyvia/next/NxDictation.jsx, nxDictation.js, nxDictationEdit.js (UI); src/grant_agent/neyvia_dictation.py, neyvia_prompt_dictation.py (backend). Human view: docs/manuals/dictation.md.","key":"3","section":"guidance"}
M dictation "Source: web/src/neyvia/next/NxDictation.jsx, nxDictation.js, nxDictationEdit.js (UI); src/grant_agent/neyvia_dictation.py, neyvia_prompt_dictation.py (backend). Human view: docs/manuals/dictation.md." src:"authored manual" state:verified
L dictation.prompts v1 -- Prompt dictation in the composer, new chat and Notes: live words, spoken commands, language routing, names
-- @record {"chapter":"prompts","data":{"args":{},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t9"},"tool":"neyvia.dictation.status"},"key":"engine","section":"state"}
S dictation.engine:{state:str device?:any url?:str engines?:json:"{\"type\":\"object\"}" recentLanguage?:any ..}=neyvia.dictation.status()
-- @record {"chapter":"prompts","data":{"args":{"action":"list"},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t10"},"tool":"neyvia.dictation.names"},"key":"names","section":"state"}
S dictation.names:{names:[json:"{\"type\":\"object\",\"properties\":{\"to\":{\"type\":\"string\"},\"from\":{\"type\":\"array\"},\"builtin\":{\"type\":\"boolean\"}}}"] ..}=neyvia.dictation.names(action:"list")
-- @record {"chapter":"prompts","data":{"effect":"Starts the local engine hidden when it is off; ready in ~30-55 s on GPU, ~3-4 min on CPU (measured 3 Oct: 189-237 s); it exits after 20 idle minutes","pre":"start=true; the engine (Phonon-2) is installed (state is not missing)","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.dictation.status","tool":"neyvia.dictation.status"},"key":"dictation.start","section":"actions"}
A neyvia.dictation.status(start?:bool) -> {state:str ..} -- Starts the local engine hidden when it is off; ready in ~30-55 s on GPU, ~3-4 min on CPU (measured 3 Oct: 189-237 s); it exits after 20 idle minutes
C neyvia.dictation.status engine-ready:neyvia.dictation.status() .state == "ready"
-- @record {"chapter":"prompts","data":{"effect":"Same prompt policy as live dictation: cleaned text, ordered segments (text / command op), language, route, name fixes. Never sends or edits anything","pre":"Text of one utterance as heard; history optional (recent languages)","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.dictation.process","tool":"neyvia.dictation.process"},"key":"dictation.process","section":"actions"}
A neyvia.dictation.process(text:str history?:[str]#..20 final?:bool) -> {text:str segments:json:"{\"type\":\"array\"}" commands:json:"{\"type\":\"array\"}" fixes:json:"{\"type\":\"array\"}" language:str route:str requiresPreview?:bool ..} -- Same prompt policy as live dictation: cleaned text, ordered segments (text / command op), language, route, name fixes. Never sends or edits anything
C neyvia.dictation.process name-written:neyvia.dictation.process(text:heard) .text has name
C neyvia.dictation.process command-parsed:neyvia.dictation.process(text:text) .commands has {op:op}
C neyvia.dictation.process stays-text:neyvia.dictation.process(text:text) .commands == []
-- @record {"chapter":"prompts","data":{"effect":"Reads or changes Paul's sound-alike list in .neyvia/dictation-names.json; the next dictation uses it","pre":"action list|add|remove; add needs from (heard) and to (written); built-ins cannot be removed","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.dictation.names","tool":"neyvia.dictation.names"},"key":"dictation.names","section":"actions"}
A neyvia.dictation.names(action?:json:"{\"type\":\"string\",\"enum\":[\"list\",\"add\",\"remove\"]}" to?:str from?:json:"{\"type\":[\"string\",\"array\"],\"items\":{\"type\":\"string\"}}") -> {names:json:"{\"type\":\"array\"}" ..} -- Reads or changes Paul's sound-alike list in .neyvia/dictation-names.json; the next dictation uses it
F verify-dictation-names "No authored observer check is bound to neyvia.dictation.names" -> ask operator blocks:neyvia.dictation.names
-- @record {"chapter":"prompts","data":{"effect":"Plain text of the file; no commands applied","pre":"A local wav/flac/ogg file; engine ready","returns":{"$cl_type":"t14"},"reversible":true,"schema":"neyvia.dictation.transcribe","tool":"neyvia.dictation.transcribe"},"key":"dictation.transcribe","section":"actions"}
A neyvia.dictation.transcribe(path:str engine?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"phonon2\",\"qwen\"]}" history?:[str]#..20) -> {text:str ..} -- Plain text of the file; no commands applied
F verify-dictation-transcribe "No authored observer check is bound to neyvia.dictation.transcribe" -> ask operator blocks:neyvia.dictation.transcribe
-- @record {"chapter":"prompts","data":{"args":{},"expect":{"op":"eq","path":"state","value":"ready"},"tool":"neyvia.dictation.status"},"key":"engine-ready","section":"checks"}
C neyvia.dictation.status engine-ready:neyvia.dictation.status() .state == "ready"
-- @record {"chapter":"prompts","data":{"args":{"text":{"$input":"heard"}},"expect":{"op":"contains","path":"text","value":{"$input":"name"}},"tool":"neyvia.dictation.process"},"key":"name-written","section":"checks"}
C neyvia.dictation.process name-written:neyvia.dictation.process(text:heard) .text has name
-- @record {"chapter":"prompts","data":{"args":{"text":{"$input":"text"}},"expect":{"op":"contains","path":"commands","value":{"op":{"$input":"op"}}},"tool":"neyvia.dictation.process"},"key":"command-parsed","section":"checks"}
C neyvia.dictation.process command-parsed:neyvia.dictation.process(text:text) .commands has {op:op}
-- @record {"chapter":"prompts","data":{"args":{"text":{"$input":"text"}},"expect":{"op":"eq","path":"commands","value":[]},"tool":"neyvia.dictation.process"},"key":"stays-text","section":"checks"}
C neyvia.dictation.process stays-text:neyvia.dictation.process(text:text) .commands == []
-- @record {"chapter":"prompts","data":{"goal":"Make dictation write a name Paul uses when it hears a sound-alike (aliases: the heard words, one or a list), and prove an utterance with them now gets the name","inputs":{"$cl_type":"t15"},"steps":[{"action":"dictation.names","args":{"action":"list"},"save":"before"},{"judge":"add-name"},{"action":"dictation.names","args":{"action":"add","from":{"$input":"aliases"},"to":{"$input":"name"}},"save":"added","when":{"judge":"add-name","option":"add"}},{"action":"dictation.process","args":{"text":{"$input":"heard"}},"check":"name-written","save":"after","when":{"judge":"add-name","option":"add"}}]},"key":"teach-a-name","section":"procedures"}
P teach-a-name(heard:str aliases:json:"{\"type\":[\"string\",\"array\"],\"items\":{\"type\":\"string\"}}" name:str):before=neyvia.dictation.names(action:"list"); J add-name=add; added=neyvia.dictation.names(action:"add" from:aliases to:name); after=neyvia.dictation.process(text:heard) C name-written -- Make dictation write a name Paul uses when it hears a sound-alike (aliases: the heard words, one or a list), and prove an utterance with them now gets the name
V P teach-a-name -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"goal":"Confirm a spoken phrase is done as the expected command (not typed)","inputs":{"$cl_type":"t16"},"steps":[{"action":"dictation.process","args":{"text":{"$input":"text"}},"check":"command-parsed","save":"parsed"}]},"key":"check-a-command","section":"procedures"}
P check-a-command(text:str op:str):parsed=neyvia.dictation.process(text:text) C command-parsed -- Confirm a spoken phrase is done as the expected command (not typed)
V P check-a-command -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"goal":"Confirm a sentence that contains a command phrase mid-sentence is typed, not done","inputs":{"$cl_type":"t17"},"steps":[{"action":"dictation.process","args":{"text":{"$input":"text"}},"check":"stays-text","save":"parsed"}]},"key":"check-stays-text","section":"procedures"}
P check-stays-text(text:str):parsed=neyvia.dictation.process(text:text) C stays-text -- Confirm a sentence that contains a command phrase mid-sentence is typed, not done
V P check-stays-text -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"goal":"Start the speech engine before Paul dictates and confirm it is ready","inputs":{"$cl_type":"t5"},"steps":[{"action":"dictation.start","args":{"start":true},"save":"started"},{"judge":"engine-wait"},{"action":"dictation.start","args":{"start":false},"check":"engine-ready","save":"ready","when":{"judge":"engine-wait","option":"check-now"}}]},"key":"warm-engine","section":"procedures"}
P warm-engine():started=neyvia.dictation.status(start:true); J engine-wait=check-now; ready=neyvia.dictation.status(start:false) C engine-ready -- Start the speech engine before Paul dictates and confirm it is ready
V P warm-engine -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"goal":"Add or remove custom aliases and read exact merged names","inputs":{"$cl_type":"t18"},"steps":[{"action":"dictation.names","args":{"action":{"$input":"action"},"from":{"$input":"from"},"to":{"$input":"to"}},"save":"observed"}]},"key":"edit-local-names","section":"procedures"}
P edit-local-names(action:json:"{\"enum\":[\"list\",\"add\",\"remove\"],\"type\":\"string\"}" from:json:"{\"items\":{\"type\":\"string\"},\"type\":[\"string\",\"array\"]}" to:str):observed=neyvia.dictation.names(action:action from:from to:to) -- Add or remove custom aliases and read exact merged names
V P edit-local-names -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"goal":"Clean an English prompt and observe its exact language history append","inputs":{"$cl_type":"t19"},"steps":[{"action":"dictation.process","args":{"final":{"$input":"final"},"history":{"$input":"history"},"text":{"$input":"text"}},"save":"observed"}]},"key":"process-local-prompt","section":"procedures"}
P process-local-prompt(final:bool history:[str]#..20 text:str):observed=neyvia.dictation.process(final:final history:history text:text) -- Clean an English prompt and observe its exact language history append
V P process-local-prompt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"prompts","data":{"constraints":"Add only when Paul never means the heard words literally (nevia → Neyvia). Skip common words (layer, queen, tory) unless Paul asked; the list rewrites every prompt.","options":["add","skip"],"question":"Should these heard words always be written as the name?"},"key":"add-name","section":"judge"}
J add-name add|skip:"Should these heard words always be written as the name?" -- Add only when Paul never means the heard words literally (nevia → Neyvia). Skip common words (layer, queen, tory) unless Paul asked; the list rewrites every prompt.
V J add-name -> human:operator why:"explicit choice required"
-- @record {"chapter":"prompts","data":{"constraints":"GPU start ~30-55 s, CPU ~3-4 min. Don't poll in a tight loop; check again after the wait, or let Paul's first press record while it loads: the UI holds the whole recording in memory, waits up to 10 min (cancellable) and writes it when the engine is ready.","options":["check-now","later"],"question":"Is the engine likely ready now?"},"key":"engine-wait","section":"judge"}
J engine-wait check-now|later:"Is the engine likely ready now?" -- GPU start ~30-55 s, CPU ~3-4 min. Don't poll in a tight loop; check again after the wait, or let Paul's first press record while it loads: the UI holds the whole recording in memory, waits up to 10 min (cancellable) and writes it when the engine is ready.
V J engine-wait -> human:operator why:"explicit choice required"
-- @record {"chapter":"prompts","data":{"constraints":"Only Paul decides. \"Send it\" shows a 2 s preview with Stop (Esc); editing the text stops it. A model never sends a dictated prompt on its own.","options":["send","stop"],"question":"Send the dictated prompt?"},"key":"send","section":"judge"}
J send send|stop:"Send the dictated prompt?" -- Only Paul decides. "Send it" shows a 2 s preview with Stop (Esc); editing the text stops it. A model never sends a dictated prompt on its own.
V J send -> human:operator why:"explicit choice required"
-- @record {"chapter":"prompts","data":{"failure":"French or mixed speech written as English-looking words","recovery":"There is no French speech engine yet: the note says so in plain words (\"Neyvia has no French speech engine on this PC yet, so the English engine wrote its best guess\") with Undo. Check the text or type it; the mic tooltip says English only while status.languages lacks fr"},"key":"0","section":"pitfalls"}
X French or mixed speech written as English-looking words -> There is no French speech engine yet: the note says so in plain words ("Neyvia has no French speech engine on this PC yet, so the English engine wrote its best guess") with Undo. Check the text or type it; the mic tooltip says English only while status.languages lacks fr
-- @record {"chapter":"prompts","data":{"failure":"Undo says the text changed since","recovery":"Paul typed after the dictation; undo by hand. One-tap Undo only restores an untouched insert"},"key":"1","section":"pitfalls"}
X Undo says the text changed since -> Paul typed after the dictation; undo by hand. One-tap Undo only restores an untouched insert
-- @record {"chapter":"prompts","data":{"failure":"A command phrase was typed as words","recovery":"undo, cancel and send count only alone or at the end of an utterance; say them after a pause. Test with procedure check-a-command"},"key":"2","section":"pitfalls"}
X A command phrase was typed as words -> undo, cancel and send count only alone or at the end of an utterance; say them after a pause. Test with procedure check-a-command
-- @record {"chapter":"prompts","data":{"failure":"Mic gives nothing on a phone or another PC","recovery":"The browser mic needs https or localhost: use the :8443 address over Tailscale"},"key":"3","section":"pitfalls"}
X Mic gives nothing on a phone or another PC -> The browser mic needs https or localhost: use the :8443 address over Tailscale
-- @record {"chapter":"prompts","data":{"failure":"Engine state missing","recovery":"phonon2_engine.py or the dictation Python wasn't found; set engineDir/python in .neyvia/dictation.json via dictation_settings_command"},"key":"4","section":"pitfalls"}
X Engine state missing -> phonon2_engine.py or the dictation Python wasn't found; set engineDir/python in .neyvia/dictation.json via dictation_settings_command
-- @record {"chapter":"prompts","data":{"failure":"First press after the engine idled out (or while it loads): no grey words","recovery":"Expected: the strip turns amber (\"The speech model is starting. Keep talking\"), every word is held and written once the engine is ready; after release it shows elapsed time and the usual start time. Esc or X drops the recording"},"key":"5","section":"pitfalls"}
X First press after the engine idled out (or while it loads): no grey words -> Expected: the strip turns amber ("The speech model is starting. Keep talking"), every word is held and written once the engine is ready; after release it shows elapsed time and the usual start time. Esc or X drops the recording
-- @record {"chapter":"prompts","data":{"failure":"Dictation failed after release (backend restarted, engine crashed)","recovery":"The recording stays in memory: the note offers Try again, which waits for the engine and decodes it again. A new dictation replaces it"},"key":"6","section":"pitfalls"}
X Dictation failed after release (backend restarted, engine crashed) -> The recording stays in memory: the note offers Try again, which waits for the engine and decodes it again. A new dictation replaces it
-- @record {"chapter":"prompts","data":{"failure":"Grey words lag on a CPU engine","recovery":"Partials come every few seconds on CPU; the final text is still complete. Prefer the GPU engine (device cuda)"},"key":"7","section":"pitfalls"}
X Grey words lag on a CPU engine -> Partials come every few seconds on CPU; the final text is still complete. Prefer the GPU engine (device cuda)
-- @record {"chapter":"prompts","data":"Late re-decode with Qwen needs a local recognizer that accepts PCM (no audio on disk); until one runs, French gets a route_note instead of a rewrite","key":"0","section":"frontier"}
F Late re-decode with Qwen needs a local recognizer that accepts PCM (no audio on disk); until one runs, French gets a route_note instead of a rewrite
-- @record {"chapter":"prompts","data":"Engine word confidences are not used; stability is agreement between partials plus committed pieces","key":"1","section":"frontier"}
F Engine word confidences are not used; stability is agreement between partials plus committed pieces
-- @record {"chapter":"prompts","data":"Code dictation (identifiers, symbols) and structural edits beyond the seven commands are not mapped","key":"2","section":"frontier"}
F Code dictation (identifiers, symbols) and structural edits beyond the seven commands are not mapped
-- @record {"chapter":"prompts","data":"Desktop (Tauri) stream path is wired through the bridge but proven only in the browser so far","key":"3","section":"frontier"}
F Desktop (Tauri) stream path is wired through the bridge but proven only in the browser so far
-- @record {"chapter":"prompts","data":"A held recording over 28 s is decoded on the one-shot path (no sid), so it cannot get a later French re-decode","key":"4","section":"frontier"}
F A held recording over 28 s is decoded on the one-shot path (no sid), so it cannot get a later French re-decode
-- @record {"chapter":"prompts","data":"The engine's idle timer counts its own load time: with idleExitMinutes shorter than a CPU load it exits before ready (the UI then starts it again)","key":"5","section":"frontier"}
F The engine's idle timer counts its own load time: with idleExitMinutes shorter than a CPU load it exits before ready (the UI then starts it again)
-- @record {"chapter":"prompts","data":"User side: mic in the composer, new chat and Notes. Click to talk, click again to insert; hold the mic or Ctrl+Shift+Space to talk while held; Esc cancels.","key":"0","section":"guidance"}
M dictation "User side: mic in the composer, new chat and Notes. Click to talk, click again to insert; hold the mic or Ctrl+Shift+Space to talk while held; Esc cancels." src:"authored manual" state:verified
-- @record {"chapter":"prompts","data":"While talking the words appear in the box: settled words in the normal colour, the newest grey. Settled words never jump; a late change shimmers and never moves the caret.","key":"1","section":"guidance"}
M dictation "While talking the words appear in the box: settled words in the normal colour, the newest grey. Settled words never jump; a late change shimmers and never moves the caret." src:"authored manual" state:verified
-- @record {"chapter":"prompts","data":"Commands: new line, new paragraph, scratch that (anywhere); undo that, cancel (alone); delete the last sentence, send it (alone or at the end). French: à la ligne, nouveau paragraphe, efface ça, annule ça, supprime la dernière phrase, envoie, annule. 'literally new line' types the words.","key":"2","section":"guidance"}
M dictation "Commands: new line, new paragraph, scratch that (anywhere); undo that, cancel (alone); delete the last sentence, send it (alone or at the end). French: à la ligne, nouveau paragraphe, efface ça, annule ça, supprime la dernière phrase, envoie, annule. 'literally new line' types the words." src:"authored manual" state:verified
-- @record {"chapter":"prompts","data":"Source: web/src/neyvia/next/NxDictation.jsx, nxDictation.js, nxDictationEdit.js (UI); src/grant_agent/neyvia_dictation.py, neyvia_prompt_dictation.py (backend). Human view: docs/manuals/dictation.md.","key":"3","section":"guidance"}
M dictation "Source: web/src/neyvia/next/NxDictation.jsx, nxDictation.js, nxDictationEdit.js (UI); src/grant_agent/neyvia_dictation.py, neyvia_prompt_dictation.py (backend). Human view: docs/manuals/dictation.md." src:"authored manual" state:verified
