CL 1
L documents v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Study documents: Paul's six-block template, Tectonic build, outcome checks and page renders"}},"clVersion":"1.1","id":"documents","kind":"workflow","proofs":{"area":"documents"},"schema":"neyvia.manual.v1","schemas":{"neyvia.documents.build":"live_schema_9","neyvia.documents.check":"live_schema_10","neyvia.documents.create":"live_schema_11","neyvia.documents.glance":"live_schema_12","neyvia.documents.render":"live_schema_13"},"tool_metadata":{"neyvia.documents.build":{"mutability_class":"artifact_write"},"neyvia.documents.check":{"mutability_class":"read"},"neyvia.documents.create":{"mutability_class":"artifact_write"},"neyvia.documents.glance":{"mutability_class":"read"},"neyvia.documents.render":{"mutability_class":"artifact_write"}}}
T live_schema_9 {path:str#1.. ..}
T live_schema_10 {path:str#1.. maxPages?:1..2000 require?:str~"^[1-6]{1,6}$" ..}
T live_schema_11 {path:str#1.. variant:json:"{\"type\":\"string\",\"enum\":[\"course\",\"sheet\"]}" title:str#1.. chapters:[str#1..]#1..40 subtitle?:str#1.. sourcePrefix?:str overwrite?:bool ..}
T live_schema_12 {path:str#1.. pages?:str~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$" ..}
T live_schema_13 {path:str#1.. pages?:str~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$" dpi?:40..300 ..}
-- @proof {"checkedAt":["grant_agent.neyvia_documents.run","grant_agent.study_docs.create","grant_agent.study_docs.build","grant_agent.proofs_documents.self_check"],"claim":"documents.create writes a course document with one concept per chapter; documents.build compiles it with Tectonic and the PDF shows the six labelled blocks and every chapter.","id":"documents.create.course","impact":["templates/latex/neyvia-study/neyvia-study.cls","documents.create","documents.build"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.study_docs.check","grant_agent.proofs_documents.self_check"],"claim":"On a clean document every outcome check passes from the produced files: no TeX errors, no undefined references, no overfull box over 1 pt, Inter embedded, blocks in order with tags, page count within the limit.","id":"documents.checks.pass","impact":["documents.check"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.study_docs.check","grant_agent.study_docs.concepts","grant_agent.proofs_documents.self_check"],"claim":"A document with blocks out of order, an untagged concept, an undefined reference and an overfull line still compiles but fails the blocks, references and overfull checks, each naming the fault.","id":"documents.checks.catch","impact":["documents.check","neyvia-study.cls aux records"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.study_docs.build","grant_agent.proofs_documents.self_check"],"claim":"The sheet variant builds from the same source, prints method and reflex and drops traps and practice.","id":"documents.sheet.variant","impact":["templates/latex/neyvia-study/neyvia-study.cls"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.study_docs.render","grant_agent.proofs_documents.self_check"],"claim":"documents.render writes the requested page as a non-blank PNG under D:/NeyviaRuns/docs.","id":"documents.render.pages","impact":["documents.render"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.study_docs.glance","grant_agent.proofs_documents.self_check"],"claim":"Without an attached LAYA judge documents.glance reports not available and never passes.","id":"documents.glance.pending","impact":["documents.glance","LAYA page glance"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_workspace_tools.tool_specs","grant_agent.study_docs.toolchain","grant_agent.proofs_documents.self_check"],"claim":"The five documents tools are workspace tools and the toolchain (Tectonic binary and bundled Inter) is present.","id":"documents.tools.registered","impact":["neyvia.documents.*"],"phase":"invariant"}
T t1{path:str#1.. variant:json:"{\"type\":\"string\",\"enum\":[\"course\",\"sheet\"]}" title:str#1.. chapters:[str#1..]#1..40 subtitle?:str#1.. sourcePrefix?:str overwrite?:bool}
T t2{path:str#1..}
T t3{path:str#1.. maxPages?:1..2000 require?:str ~"^[1-6]{1,6}$"}
T t4{path:str#1.. pages?:str ~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$" dpi?:40..300}
T t5{path:str#1.. pages?:str ~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$"}
T t6{ok:bool passed:int total:int ..}
T t7 json:"{\"type\":\"object\"}"
T t8{path:str#1.. variant:json:"{\"type\":\"string\",\"enum\":[\"course\",\"sheet\"]}" title:str#1.. chapters:[str#1..]#1..40}
L documents.overview v1 -- Study documents: Paul's six-block template, Tectonic build, outcome checks and page renders
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t6"},"tool":"neyvia.documents.check"},"key":"document","section":"state"}
S documents.document:{ok:bool passed:int total:int ..}=neyvia.documents.check(path:path)
-- @record {"chapter":"overview","data":{"effect":"Create a study document on Paul's neyvia-study template: course (six blocks per concept) or sheet (formula, method, reflex); one chapter per title.","pre":"A workspace path for a new .tex file; overwrite only when asked","returns":{"type":"object"},"reversible":true,"schema":"neyvia.documents.create","tool":"neyvia.documents.create"},"key":"documents.create","section":"actions"}
A neyvia.documents.create(path:str#1.. variant:json:"{\"type\":\"string\",\"enum\":[\"course\",\"sheet\"]}" title:str#1.. chapters:[str#1..]#1..40 subtitle?:str#1.. sourcePrefix?:str overwrite?:bool) -> json:"{\"type\":\"object\"}" ! -- Create a study document on Paul's neyvia-study template: course (six blocks per concept) or sheet (formula, method, reflex); one chapter per title.
F verify-documents-create "No authored observer check is bound to neyvia.documents.create" -> ask operator blocks:neyvia.documents.create
-- @record {"chapter":"overview","data":{"effect":"Compile a study document with Tectonic (XeTeX, Inter bundled); returns the PDF, log, seconds and page count.","pre":"An existing .tex on the neyvia-study class; Tectonic installed (study_docs.py setup)","returns":{"type":"object"},"reversible":true,"schema":"neyvia.documents.build","tool":"neyvia.documents.build"},"key":"documents.build","section":"actions"}
A neyvia.documents.build(path:str#1..) -> json:"{\"type\":\"object\"}" ! -- Compile a study document with Tectonic (XeTeX, Inter bundled); returns the PDF, log, seconds and page count.
C neyvia.documents.build compiles: neyvia.documents.check(path:path).compiles==true
-- @record {"chapter":"overview","data":{"effect":"Run the outcome checks on a built study document: compiles, references, overfull boxes, Inter embedded, block order and source tags, page count.","pre":"The document was built by documents.build","returns":{"type":"object"},"reversible":true,"schema":"neyvia.documents.check","tool":"neyvia.documents.check"},"key":"documents.check","section":"actions"}
A neyvia.documents.check(path:str#1.. maxPages?:1..2000 require?:str~"^[1-6]{1,6}$") -> json:"{\"type\":\"object\"}" ! -- Run the outcome checks on a built study document: compiles, references, overfull boxes, Inter embedded, block order and source tags, page count.
C neyvia.documents.check blocks: neyvia.documents.check(path:path).blocks==true
C neyvia.documents.check references: neyvia.documents.check(path:path).references==true
C neyvia.documents.check overfull: neyvia.documents.check(path:path).overfull==true
C neyvia.documents.check inter-embedded: neyvia.documents.check(path:path).interEmbedded==true
C neyvia.documents.check blocks: neyvia.documents.check(path:path).blocks==true
C neyvia.documents.check pages: neyvia.documents.check(path:path).pages==true
-- @record {"chapter":"overview","data":{"effect":"Render pages of a built study document to PNG files on D:/NeyviaRuns/docs.","pre":"The document was built by documents.build","returns":{"type":"object"},"reversible":true,"schema":"neyvia.documents.render","tool":"neyvia.documents.render"},"key":"documents.render","section":"actions"}
A neyvia.documents.render(path:str#1.. pages?:str~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$" dpi?:40..300) -> json:"{\"type\":\"object\"}" ! -- Render pages of a built study document to PNG files on D:/NeyviaRuns/docs.
F verify-documents-render "No authored observer check is bound to neyvia.documents.render" -> ask operator blocks:neyvia.documents.render
-- @record {"chapter":"overview","data":{"effect":"Ask the attached LAYA page-glance judge whether rendered pages look broken; reports not available until a judge is attached.","pre":"The document was built; a LAYA judge attached through NEYVIA_LAYA_GLANCE","returns":{"type":"object"},"reversible":true,"schema":"neyvia.documents.glance","tool":"neyvia.documents.glance"},"key":"documents.glance","section":"actions"}
A neyvia.documents.glance(path:str#1.. pages?:str~"^(all|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*)$") -> json:"{\"type\":\"object\"}" -- Ask the attached LAYA page-glance judge whether rendered pages look broken; reports not available until a judge is attached.
F verify-documents-glance "No authored observer check is bound to neyvia.documents.glance" -> ask operator blocks:neyvia.documents.glance
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"compiles","value":true},"tool":"neyvia.documents.check"},"key":"compiles","section":"checks"}
C neyvia.documents.check compiles:neyvia.documents.check(path:path) .compiles == true
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"references","value":true},"tool":"neyvia.documents.check"},"key":"references","section":"checks"}
C neyvia.documents.check references:neyvia.documents.check(path:path) .references == true
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"overfull","value":true},"tool":"neyvia.documents.check"},"key":"overfull","section":"checks"}
C neyvia.documents.check overfull:neyvia.documents.check(path:path) .overfull == true
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"interEmbedded","value":true},"tool":"neyvia.documents.check"},"key":"inter-embedded","section":"checks"}
C neyvia.documents.check inter-embedded:neyvia.documents.check(path:path) .interEmbedded == true
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"blocks","value":true},"tool":"neyvia.documents.check"},"key":"blocks","section":"checks"}
C neyvia.documents.check blocks:neyvia.documents.check(path:path) .blocks == true
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"pages","value":true},"tool":"neyvia.documents.check"},"key":"pages","section":"checks"}
C neyvia.documents.check pages:neyvia.documents.check(path:path) .pages == true
-- @record {"chapter":"overview","data":{"goal":"Create a document from Paul's template, build it, check every outcome and render pages to look at","inputs":{"$cl_type":"t8"},"steps":[{"action":"documents.create","args":{"chapters":{"$input":"chapters"},"path":{"$input":"path"},"title":{"$input":"title"},"variant":{"$input":"variant"}},"save":"created"},{"action":"documents.build","args":{"path":{"$input":"path"}},"check":"compiles","save":"built"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"blocks","save":"checked"},{"action":"documents.render","args":{"path":{"$input":"path"}},"save":"pages"},{"action":"documents.glance","args":{"path":{"$input":"path"}},"save":"glance"},{"judge":"pages-look-right"}]},"key":"new-document","section":"procedures"}
P new-document(path:str#1.. variant:json:"{\"type\":\"string\",\"enum\":[\"course\",\"sheet\"]}" title:str#1.. chapters:[str#1..]#1..40):created=neyvia.documents.create(chapters:chapters path:path title:title variant:variant); built=neyvia.documents.build(path:path) C compiles; checked=neyvia.documents.check(path:path) C blocks; pages=neyvia.documents.render(path:path); glance=neyvia.documents.glance(path:path); J pages-look-right -- Create a document from Paul's template, build it, check every outcome and render pages to look at
V P new-document -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Rebuild an edited document and prove it still compiles cleanly with every concept in block order","inputs":{"$cl_type":"t2"},"steps":[{"action":"documents.build","args":{"path":{"$input":"path"}},"check":"compiles","save":"built"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"references","save":"checked"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"overfull","save":"layout"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"inter-embedded","save":"fonts"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"blocks","save":"concepts"},{"action":"documents.check","args":{"path":{"$input":"path"}},"check":"pages","save":"length"},{"action":"documents.render","args":{"path":{"$input":"path"}},"save":"pages"},{"action":"documents.glance","args":{"path":{"$input":"path"}},"save":"glance"},{"judge":"pages-look-right"}]},"key":"build-and-check","section":"procedures"}
P build-and-check(path:str#1..):built=neyvia.documents.build(path:path) C compiles; checked=neyvia.documents.check(path:path) C references; layout=neyvia.documents.check(path:path) C overfull; fonts=neyvia.documents.check(path:path) C inter-embedded; concepts=neyvia.documents.check(path:path) C blocks; length=neyvia.documents.check(path:path) C pages; pages=neyvia.documents.render(path:path); glance=neyvia.documents.glance(path:path); J pages-look-right -- Rebuild an edited document and prove it still compiles cleanly with every concept in block order
V P build-and-check -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"The pluggable LAYA page glance (documents.glance) answers this once attached; until then a person looks at the PNGs from documents.render. A missing judge is never a pass.","kind":"human","options":["looks-fine","looks-broken"],"question":"Do the rendered pages look right: no clipped boxes, overlapping text, empty or half-empty pages?"},"key":"pages-look-right","section":"judge"}
J pages-look-right looks-fine|looks-broken:"Do the rendered pages look right: no clipped boxes, overlapping text, empty or half-empty pages?" -- The pluggable LAYA page glance (documents.glance) answers this once attached; until then a person looks at the PNGs from documents.render. A missing judge is never a pass.
V J pages-look-right -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Tectonic is missing","recovery":"Run python scripts/study_docs.py setup --install: it fetches the official GitHub release (about 21 MB) to D:/NeyviaRuns/tectonic/bin."},"key":"0","section":"pitfalls"}
X Tectonic is missing -> Run python scripts/study_docs.py setup --install: it fetches the official GitHub release (about 21 MB) to D:/NeyviaRuns/tectonic/bin.
-- @record {"chapter":"overview","data":{"failure":"A package is not in the cache","recovery":"documents.build retries online once and Tectonic fetches only that package into D:/NeyviaRuns/tectonic/cache; later builds run offline."},"key":"1","section":"pitfalls"}
X A package is not in the cache -> documents.build retries online once and Tectonic fetches only that package into D:/NeyviaRuns/tectonic/cache; later builds run offline.
-- @record {"chapter":"overview","data":{"failure":"Inter is not embedded","recovery":"The class loads Inter by file name from templates/latex/neyvia-study/fonts, which the build puts on the search path; elsewhere set \\studyfontpath{dir/}."},"key":"2","section":"pitfalls"}
X Inter is not embedded -> The class loads Inter by file name from templates/latex/neyvia-study/fonts, which the build puts on the search path; elsewhere set \studyfontpath{dir/}.
-- @record {"chapter":"overview","data":{"failure":"Overfull box over 1 pt","recovery":"Split the long formula over several \\step or \\dline lines, one transformation per line; never shrink the font."},"key":"3","section":"pitfalls"}
X Overfull box over 1 pt -> Split the long formula over several \step or \dline lines, one transformation per line; never shrink the font.
-- @record {"chapter":"overview","data":{"failure":"Blocks out of order or a concept without a tag","recovery":"Reorder to definition, method, reflex, worked, traps, practice and give \\begin{concept}{title}{tag} the source page and column."},"key":"4","section":"pitfalls"}
X Blocks out of order or a concept without a tag -> Reorder to definition, method, reflex, worked, traps, practice and give \begin{concept}{title}{tag} the source page and column.
-- @record {"chapter":"overview","data":{"failure":"Undefined reference","recovery":"Fix the \\ref label; a second build pass never hides a missing label."},"key":"5","section":"pitfalls"}
X Undefined reference -> Fix the \ref label; a second build pass never hides a missing label.
-- @record {"chapter":"overview","data":"The LAYA page glance is a pluggable step: documents.glance hands the page PNGs to the command in NEYVIA_LAYA_GLANCE and reports not available until another component attaches it.","key":"0","section":"frontier"}
F The LAYA page glance is a pluggable step: documents.glance hands the page PNGs to the command in NEYVIA_LAYA_GLANCE and reports not available until another component attaches it.
-- @record {"chapter":"overview","data":"The six-part format is the same structure Scroll Study card packs use (paul-seven-part.v1): definition = FORMULA with WHEN?, method = WHAT DO I WRITE?, reflex = PATTERN, worked = COURSE EXAMPLE, practice = YOUR EXERCISE, traps = VARIATIONS/TRAPS. One source can feed both; the converter is not built yet.","key":"1","section":"frontier"}
F The six-part format is the same structure Scroll Study card packs use (paul-seven-part.v1): definition = FORMULA with WHEN?, method = WHAT DO I WRITE?, reflex = PATTERN, worked = COURSE EXAMPLE, practice = YOUR EXERCISE, traps = VARIATIONS/TRAPS. One source can feed both; the converter is not built yet.
-- @record {"chapter":"overview","data":"Paul's own Complete Course has concepts with no method (19 of 199) or no worked example (41 of 199), so the block check requires definition and reflex and reports the others; require 1234 makes it strict.","key":"2","section":"frontier"}
F Paul's own Complete Course has concepts with no method (19 of 199) or no worked example (41 of 199), so the block check requires definition and reflex and reports the others; require 1234 makes it strict.
-- @record {"chapter":"overview","data":"Ports of chapter 1 of the Complete Course and the Formula & Method Sheet onto the class place all 58 concept headings at the original page and position; scripts/study_docs.py port and compare reproduce it.","key":"3","section":"frontier"}
F Ports of chapter 1 of the Complete Course and the Formula & Method Sheet onto the class place all 58 concept headings at the original page and position; scripts/study_docs.py port and compare reproduce it.
-- @record {"chapter":"overview","data":"Template: templates/latex/neyvia-study/neyvia-study.cls, \\documentclass[course] or [sheet]; examples in examples/. Writing rules: plugins/neyvia/skills/neyvia-study-docs/SKILL.md.","key":"0","section":"guidance"}
M documents "Template: templates/latex/neyvia-study/neyvia-study.cls, \\documentclass[course] or [sheet]; examples in examples/. Writing rules: plugins/neyvia/skills/neyvia-study-docs/SKILL.md." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"A concept is \\begin{concept}{title}{source tag} with blocks definition, method{caption}, reflex, worked{caption}, traps, practice in that order. The sheet keeps 1-3 and drops 4-6, so one source builds both.","key":"1","section":"guidance"}
M documents "A concept is \\begin{concept}{title}{source tag} with blocks definition, method{caption}, reflex, worked{caption}, traps, practice in that order. The sheet keeps 1-3 and drops 4-6, so one source builds both." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Lines: \\step{...} one transformation per line (a leading Let, Assume, Then, Take, Check, We look for is coloured), \\dline{maths}, \\result{maths}, \\trap{...}, \\try{...} with \\answer{...}. Quantifiers \\forall \\exists \\exists! colour themselves.","key":"2","section":"guidance"}
M documents "Lines: \\step{...} one transformation per line (a leading Let, Assume, Then, Take, Check, We look for is coloured), \\dline{maths}, \\result{maths}, \\trap{...}, \\try{...} with \\answer{...}. Quantifiers \\forall \\exists \\exists! colour themselves." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Builds and renders go to D:/NeyviaRuns/docs; never put PDFs or PNGs in the workspace.","key":"3","section":"guidance"}
M documents "Builds and renders go to D:/NeyviaRuns/docs; never put PDFs or PNGs in the workspace." src:"authored manual" state:verified
