CL 1
L effectcraft v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Agent-usable EffectCraft (ArtCraft/storytold, an After Effects-style compositor in Rust) through its headless CLI: commands, comps and layers as a CL Scene, scripted edits, frames and renders."}},"clVersion":"1.1","id":"effectcraft","kind":"environment","schema":"neyvia.manual.v1","schemas":{"neyvia.mod.effectcraft.commands":"live_schema_9","neyvia.mod.effectcraft.frame":"live_schema_10","neyvia.mod.effectcraft.info":"live_schema_11","neyvia.mod.effectcraft.render":"live_schema_12","neyvia.mod.effectcraft.run":"live_schema_13","neyvia.mod.effectcraft.verify":"live_schema_14"},"tool_metadata":{"neyvia.mod.effectcraft.commands":{"mutability_class":"read"},"neyvia.mod.effectcraft.frame":{"mutability_class":"artifact_write"},"neyvia.mod.effectcraft.info":{"mutability_class":"read"},"neyvia.mod.effectcraft.render":{"mutability_class":"artifact_write"},"neyvia.mod.effectcraft.run":{"mutability_class":"artifact_write"},"neyvia.mod.effectcraft.verify":{"mutability_class":"artifact_write"}}}
T live_schema_9 {filter?:str#..200 ..}
T live_schema_10 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"comp\":{\"type\":\"string\",\"maxLength\":4000},\"time\":{\"type\":\"number\",\"minimum\":0},\"out\":{\"type\":\"string\",\"maxLength\":4000}},\"required\":[\"out\"],\"allOf\":[{\"properties\":{\"out\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_11 {project?:str#..4000 ..}
T live_schema_12 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"comp\":{\"type\":\"string\",\"maxLength\":4000},\"out\":{\"type\":\"string\",\"maxLength\":4000},\"format\":{\"type\":\"string\",\"maxLength\":20},\"start\":{\"type\":\"number\"},\"end\":{\"type\":\"number\"}},\"required\":[\"out\"],\"allOf\":[{\"properties\":{\"out\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_13 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"steps\":{\"type\":\"array\",\"maxItems\":500,\"items\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\",\"maxLength\":200},\"params\":{\"type\":\"object\"}},\"required\":[\"id\"]}},\"saveAs\":{\"type\":\"string\",\"maxLength\":4000}},\"required\":[\"steps\",\"saveAs\"],\"allOf\":[{\"properties\":{\"saveAs\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_14 {..}
T t1{filter?:str#..200}
T t2{project?:str#..4000}
T t3{project?:str#..4000 steps:[{id:str#..200 params?:json:"{\"type\":\"object\"}" ..}]#..500 saveAs:str#..4000}
T t4{project?:str#..4000 comp?:str#..4000 time?:json:"{\"type\":\"number\",\"minimum\":0}" out:str#..4000}
T t5{project?:str#..4000 comp?:str#..4000 out:str#..4000 format?:str#..20 start?:num end?:num}
T t6{}
T t7 json:"{\"type\":\"object\"}"
T t8 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
L effectcraft.overview v1 -- Agent-usable EffectCraft (ArtCraft/storytold, an After Effects-style compositor in Rust) through its headless CLI: commands, comps and layers as a CL Scene, scripted edits, frames and renders.
-- @record {"chapter":"overview","data":{"effect":"List EffectCraft engine commands matching a filter.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":true,"schema":"neyvia.mod.effectcraft.commands","tool":"neyvia.mod.effectcraft.commands"},"key":"mod.effectcraft.commands","section":"actions"}
A neyvia.mod.effectcraft.commands(filter?:str#..200) -> json:"{\"type\":\"object\"}" -- List EffectCraft engine commands matching a filter.
F verify-mod-effectcraft-commands "No authored observer check is bound to neyvia.mod.effectcraft.commands" -> ask operator blocks:neyvia.mod.effectcraft.commands
-- @record {"chapter":"overview","data":{"effect":"Observe a project as a CL Scene: every comp, and the active comp's layers with their effects and keyframed properties.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":true,"schema":"neyvia.mod.effectcraft.info","tool":"neyvia.mod.effectcraft.info"},"key":"mod.effectcraft.info","section":"actions"}
A neyvia.mod.effectcraft.info(project?:str#..4000) -> json:"{\"type\":\"object\"}" -- Observe a project as a CL Scene: every comp, and the active comp's layers with their effects and keyframed properties.
F verify-mod-effectcraft-info "No authored observer check is bound to neyvia.mod.effectcraft.info" -> ask operator blocks:neyvia.mod.effectcraft.info
-- @record {"chapter":"overview","data":{"effect":"Run engine commands in order on a project (the built-in demo when omitted) and save it.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.effectcraft.run","tool":"neyvia.mod.effectcraft.run"},"key":"mod.effectcraft.run","section":"actions"}
A neyvia.mod.effectcraft.run(project?:str#..4000 steps:[{id:str#..200 params?:json:"{\"type\":\"object\"}" ..}]#..500 saveAs:str#..4000) -> json:"{\"type\":\"object\"}" ! -- Run engine commands in order on a project (the built-in demo when omitted) and save it.
F verify-mod-effectcraft-run "No authored observer check is bound to neyvia.mod.effectcraft.run" -> ask operator blocks:neyvia.mod.effectcraft.run
-- @record {"chapter":"overview","data":{"effect":"Render one composition frame to PNG.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.effectcraft.frame","tool":"neyvia.mod.effectcraft.frame"},"key":"mod.effectcraft.frame","section":"actions"}
A neyvia.mod.effectcraft.frame(project?:str#..4000 comp?:str#..4000 time?:json:"{\"type\":\"number\",\"minimum\":0}" out:str#..4000) -> json:"{\"type\":\"object\"}" ! -- Render one composition frame to PNG.
F verify-mod-effectcraft-frame "No authored observer check is bound to neyvia.mod.effectcraft.frame" -> ask operator blocks:neyvia.mod.effectcraft.frame
-- @record {"chapter":"overview","data":{"effect":"Render a composition to a file and check the outcome contracts.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.effectcraft.render","tool":"neyvia.mod.effectcraft.render"},"key":"mod.effectcraft.render","section":"actions"}
A neyvia.mod.effectcraft.render(project?:str#..4000 comp?:str#..4000 out:str#..4000 format?:str#..20 start?:num end?:num) -> json:"{\"type\":\"object\"}" ! -- Render a composition to a file and check the outcome contracts.
F verify-mod-effectcraft-render "No authored observer check is bound to neyvia.mod.effectcraft.render" -> ask operator blocks:neyvia.mod.effectcraft.render
-- @record {"chapter":"overview","data":{"effect":"Real round trip on a real Neyvia capture: new comp, import, keyframed push-in, a title with Drop Shadow and a fade, observe as a Scene, one frame, a 3 s H.264 render, then the outcome contracts on the decoded file.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object","properties":{"passed":{"const":true}},"required":["passed"]},"reversible":false,"schema":"neyvia.mod.effectcraft.verify","tool":"neyvia.mod.effectcraft.verify"},"key":"mod.effectcraft.verify","section":"actions"}
A neyvia.mod.effectcraft.verify() -> {passed:true ..} ! -- Real round trip on a real Neyvia capture: new comp, import, keyframed push-in, a title with Drop Shadow and a fade, observe as a Scene, one frame, a 3 s H.264 render, then the outcome contracts on the decoded file.
F verify-mod-effectcraft-verify "No authored observer check is bound to neyvia.mod.effectcraft.verify" -> ask operator blocks:neyvia.mod.effectcraft.verify
-- @record {"chapter":"overview","data":{"goal":"Run the real round trip and check its outcome contracts","inputs":{"type":"object","properties":{},"additionalProperties":false},"steps":[{"action":"mod.effectcraft.verify","args":{},"save":"verified"}]},"key":"verify-effectcraft","section":"procedures"}
P verify-effectcraft(): verified=neyvia.mod.effectcraft.verify() -- Run the real round trip and check its outcome contracts
V P verify-effectcraft -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"The local tool is missing","recovery":"Build or point the NEYVIA_* path at it; the action refuses rather than downloading anything."},"key":"0","section":"pitfalls"}
X The local tool is missing -> Build or point the NEYVIA_* path at it; the action refuses rather than downloading anything.
-- @record {"chapter":"overview","data":{"failure":"A render exists but is wrong","recovery":"Read the outcome block (duration, frames, black/frozen runs, clipping); never call a render good from its exit code."},"key":"1","section":"pitfalls"}
X A render exists but is wrong -> Read the outcome block (duration, frames, black/frozen runs, clipping); never call a render good from its exit code.
-- @record {"chapter":"overview","data":"Built from source (effectcraft 0.3.1, needs Rust 1.95 or newer) with a Rust 1.99 toolchain kept on D:/NeyviaRuns/toolchains into D:/NeyviaRuns/video/track-video/target/effectcraft; set NEYVIA_EFFECTCRAFT_CLI to use another build.","key":"0","section":"frontier"}
F Built from source (effectcraft 0.3.1, needs Rust 1.95 or newer) with a Rust 1.99 toolchain kept on D:/NeyviaRuns/toolchains into D:/NeyviaRuns/video/track-video/target/effectcraft; set NEYVIA_EFFECTCRAFT_CLI to use another build.
-- @record {"chapter":"overview","data":"Adapted, not forked: every action runs the unmodified upstream program. EffectCraft by the ArtCraft team, MIT OR Apache-2.0, https://github.com/storytold/effectcraft.","key":"1","section":"frontier"}
F Adapted, not forked: every action runs the unmodified upstream program. EffectCraft by the ArtCraft team, MIT OR Apache-2.0, https://github.com/storytold/effectcraft.
-- @record {"chapter":"overview","data":"Comps and layers are addressed by id or name; properties by path (mod.effectcraft.info lists them).","key":"0","section":"guidance"}
M effectcraft "Comps and layers are addressed by id or name; properties by path (mod.effectcraft.info lists them)." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"A run step is an engine command id with JSON params, e.g. comp.new {name,width,height,frameRate,duration}, file.import {paths}, layer.addItem {item,time,duration}, layer.newText {text,name,size,fill,position}, effect.apply {effect,layers}, prop.addKey {layer,path,time,value}; find others with mod.effectcraft.commands.","key":"1","section":"guidance"}
M effectcraft "A run step is an engine command id with JSON params, e.g. comp.new {name,width,height,frameRate,duration}, file.import {paths}, layer.addItem {item,time,duration}, layer.newText {text,name,size,fill,position}, effect.apply {effect,layers}, prop.addKey {layer,path,time,value}; find others with mod.effectcraft.commands." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Use frames for quick looks and render for the outcome contracts.","key":"2","section":"guidance"}
M effectcraft "Use frames for quick looks and render for the outcome contracts." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Installs switched off from Marketplace > Apps & mods; read this manual and the declared permissions, then enable it.","key":"3","section":"guidance"}
M effectcraft "Installs switched off from Marketplace > Apps & mods; read this manual and the declared permissions, then enable it." src:"authored manual" state:verified
