CL 1
L efficiency v1 -- Authored executable manual
-- @manual {"chapters":{"cascade":{"title":"Validated answers and successful executable memory"},"laya":{"title":"LAYA by default: the 0.95 gate, receipts, hosting, routing and the fast verify call"},"learned-capabilities":{"title":"Calibrated LAYA capabilities and separate personal conditioning"},"workflow":{"title":"Executable efficiency method: chronological mechanism and measured quality"},"filmbugs":{"title":"Launch film behavior contracts"}},"clVersion":"1.1","id":"efficiency","kind":"workflow","proofs":{"area":"context-config-journey","manifests":["config/proofs/context-config-journey.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.efficiency.extract":"t1","neyvia.efficiency.laya_experience":"t2","neyvia.efficiency.laya_forget":"t3","neyvia.efficiency.laya_ingest":"t4","neyvia.efficiency.laya_learn":"t5","neyvia.efficiency.laya_outcome":"t6","neyvia.efficiency.laya_query":"t7","neyvia.efficiency.laya_route":"t8","neyvia.efficiency.laya_selfcheck":"t9","neyvia.efficiency.laya_status":"t4","neyvia.efficiency.laya_training":"t4","neyvia.efficiency.laya_verify":"t10","neyvia.efficiency.metrics":"t4","neyvia.efficiency.transitions":"t4","neyvia.workflow.check":"t11","neyvia.workflow.record":"t11"},"tool_metadata":{"neyvia.efficiency.extract":{"mutability_class":"none"},"neyvia.efficiency.laya_experience":{"mutability_class":"none"},"neyvia.efficiency.laya_forget":{"mutability_class":"none"},"neyvia.efficiency.laya_ingest":{"mutability_class":"none"},"neyvia.efficiency.laya_learn":{"mutability_class":"none"},"neyvia.efficiency.laya_outcome":{"mutability_class":"none"},"neyvia.efficiency.laya_query":{"mutability_class":"none"},"neyvia.efficiency.laya_route":{"mutability_class":"none"},"neyvia.efficiency.laya_selfcheck":{"mutability_class":"none"},"neyvia.efficiency.laya_status":{"mutability_class":"none"},"neyvia.efficiency.laya_training":{"mutability_class":"none"},"neyvia.efficiency.laya_verify":{"mutability_class":"read"},"neyvia.efficiency.metrics":{"mutability_class":"none"},"neyvia.efficiency.transitions":{"mutability_class":"none"},"neyvia.workflow.check":{"mutability_class":"read"},"neyvia.workflow.record":{"mutability_class":"artifact_write"}}}
-- @proof {"id":"efficiency.laya-zero-savings","phase":"invariant","claim":"LAYA strip retains answered/asked counts and service tone, and shows estimated token savings only when positive. Zero or unavailable savings do not appear as a savings claim.","checkedAt":["web/src/neyvia/next/nxLayaModel.js:stripView"],"impact":["Launch film behavior"]}
T t1 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"field\":{\"type\":\"string\"},\"strategy\":{\"type\":\"string\",\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"]},\"useScript\":{\"type\":\"boolean\"}},\"required\":[\"path\",\"field\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}},\"field\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000},\"input\":{},\"signal\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"string\",\"maxLength\":16000},\"user\":{\"type\":\"string\",\"maxLength\":16000},\"value\":{},\"elapsedSeconds\":{\"type\":\"number\"}},\"required\":[\"domain\",\"input\",\"signal\",\"source\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}},\"input\":{\"not\":{\"enum\":[null,\"\"]}},\"signal\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"source\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"source\"],\"allOf\":[{\"properties\":{\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4{..}
T t5 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000},\"input\":{},\"label\":{},\"source\":{\"type\":\"string\",\"maxLength\":16000},\"user\":{\"type\":\"string\",\"maxLength\":16000},\"layer\":{\"type\":\"string\",\"enum\":[\"personal\",\"corrective\"]},\"weight\":{\"type\":\"number\",\"exclusiveMinimum\":0,\"maximum\":1},\"evidence\":{\"type\":\"object\"}},\"required\":[\"domain\",\"input\",\"label\",\"source\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}},\"input\":{\"not\":{\"enum\":[null,\"\"]}},\"label\":{\"not\":{\"enum\":[null,\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{receipt:json:"{\"type\":\"object\"}" ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000},\"input\":{},\"user\":{\"type\":\"string\",\"maxLength\":16000},\"labels\":{\"type\":\"array\"}},\"required\":[\"domain\",\"input\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}},\"input\":{\"not\":{\"enum\":[null,\"\"]}}}}]}"
T t8 json:"{\"type\":\"object\",\"properties\":{\"intent\":{\"type\":\"string\",\"maxLength\":16000},\"consultLaya\":{\"type\":\"boolean\"}},\"required\":[\"intent\"],\"allOf\":[{\"properties\":{\"intent\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9{part:json:"{\"type\":\"string\",\"enum\":[\"gate\",\"ledger\",\"host\",\"ui\",\"preview\",\"route\",\"shutdown\",\"instant\"]}" ..}
T t10{question:json:"{\"type\":\"string\",\"enum\":[\"taste_triage\",\"page_done\",\"cl_route\",\"repair_retention\"]}" candidate?:any evidence:json:"{\"type\":\"object\"}" ..}
T t11{manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t12 json:"{\"type\":\"object\"}"
T t13 json:"{\"type\":\"object\",\"properties\":{\"answer\":{\"type\":\"object\",\"properties\":{\"valueJson\":{\"type\":\"string\"},\"sourceSha256\":{\"type\":\"string\"}}},\"route\":{\"type\":\"string\"}}}"
T t14{path:str field:str expectedJson:str}
T t15{}
T t16 json:"{\"properties\":{\"field\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"strategy\":{\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"],\"type\":\"string\"},\"useScript\":{\"type\":\"boolean\"}},\"required\":[\"path\",\"field\",\"strategy\",\"useScript\"],\"type\":\"object\"}"
T t17{answer:any confidence:any escalate:bool agrees:any ..}
T t18{question:json:"{\"type\":\"string\",\"enum\":[\"taste_triage\",\"page_done\",\"cl_route\",\"repair_retention\"]}" evidence:json:"{\"type\":\"object\"}"}
T t19 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t20 json:"{\"type\":\"object\",\"properties\":{}}"
T t21{report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t22 json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"
L efficiency.cascade v1 -- Validated answers and successful executable memory
-- @record {"chapter":"cascade","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t12"},"tool":"neyvia.efficiency.metrics"},"key":"latency","section":"state"}
S efficiency.latency:json:"{\"type\":\"object\"}"=neyvia.efficiency.metrics()
-- @record {"chapter":"cascade","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t12"},"tool":"neyvia.efficiency.transitions"},"key":"learned","section":"state"}
S efficiency.learned:json:"{\"type\":\"object\"}"=neyvia.efficiency.transitions()
-- @record {"chapter":"cascade","data":{"effect":"Return an exact source value checked against a fresh native read; retain route, actual model usage and latency receipt","pre":"Complete JSON source within caller's workspace and an exact JSON Pointer","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.efficiency.extract","tool":"neyvia.efficiency.extract"},"key":"extract","section":"actions"}
A neyvia.efficiency.extract(path:str field:str strategy?:json:"{\"type\":\"string\",\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"]}" useScript?:bool) -> json:"{\"type\":\"object\",\"properties\":{\"answer\":{\"type\":\"object\",\"properties\":{\"valueJson\":{\"type\":\"string\"},\"sourceSha256\":{\"type\":\"string\"}}},\"route\":{\"type\":\"string\"}}}" -- Return an exact source value checked against a fresh native read; retain route, actual model usage and latency receipt
C neyvia.efficiency.extract exact-value:neyvia.efficiency.extract(field:field path:path) .answer.valueJson == expectedJson
-- @record {"chapter":"cascade","data":{"effect":"Inspect measured samples, hardware, cold/warm quantiles and overruns","pre":"Selected workspace","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.metrics","tool":"neyvia.efficiency.metrics"},"key":"metrics","section":"actions"}
A neyvia.efficiency.metrics() -> json:"{\"type\":\"object\"}" -- Inspect measured samples, hardware, cold/warm quantiles and overruns
F verify-metrics "No authored observer check is bound to neyvia.efficiency.metrics" -> ask operator blocks:neyvia.efficiency.metrics
-- @record {"chapter":"cascade","data":{"effect":"Inspect scoped learned rows and receipt provenance","pre":"Selected workspace","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.transitions","tool":"neyvia.efficiency.transitions"},"key":"transitions","section":"actions"}
A neyvia.efficiency.transitions() -> json:"{\"type\":\"object\"}" -- Inspect scoped learned rows and receipt provenance
F verify-transitions "No authored observer check is bound to neyvia.efficiency.transitions" -> ask operator blocks:neyvia.efficiency.transitions
-- @record {"chapter":"cascade","data":{"args":{"field":{"$input":"field"},"path":{"$input":"path"}},"expect":{"op":"eq","path":"answer.valueJson","value":{"$input":"expectedJson"}},"tool":"neyvia.efficiency.extract"},"key":"exact-value","section":"checks"}
C neyvia.efficiency.extract exact-value:neyvia.efficiency.extract(field:field path:path) .answer.valueJson == expectedJson
-- @record {"chapter":"cascade","data":{"goal":"Extract a JSON value with every digit, identifier, date and UI value preserved and prove it against an expected canonical JSON value","inputs":{"$cl_type":"t14"},"steps":[{"action":"extract","args":{"field":{"$input":"field"},"path":{"$input":"path"}},"check":"exact-value","save":"extraction"}]},"key":"extract-and-confirm","section":"procedures"}
P extract-and-confirm(path:str field:str expectedJson:str):extraction=neyvia.efficiency.extract(field:field path:path) C exact-value -- Extract a JSON value with every digit, identifier, date and UI value preserved and prove it against an expected canonical JSON value
V P extract-and-confirm -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cascade","data":{"goal":"Inspect actual cascade latency samples and successful transition provenance","inputs":{"$cl_type":"t15"},"steps":[{"action":"metrics","args":{},"save":"latency"},{"action":"transitions","args":{},"save":"learned"}]},"key":"inspect-cost","section":"procedures"}
P inspect-cost():latency=neyvia.efficiency.metrics(); learned=neyvia.efficiency.transitions() -- Inspect actual cascade latency samples and successful transition provenance
V P inspect-cost -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cascade","data":{"goal":"Extract exact JSON source through the script cascade and verify real receipt, cache and telemetry","inputs":{"$cl_type":"t16"},"steps":[{"action":"extract","args":{"field":{"$input":"field"},"path":{"$input":"path"},"strategy":{"$input":"strategy"},"useScript":{"$input":"useScript"}},"save":"observed"}]},"key":"extract-local-json","section":"procedures"}
P extract-local-json(field:str path:str strategy:json:"{\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"],\"type\":\"string\"}" useScript:bool):observed=neyvia.efficiency.extract(field:field path:path strategy:strategy useScript:useScript) -- Extract exact JSON source through the script cascade and verify real receipt, cache and telemetry
V P extract-local-json -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cascade","data":{"constraints":"Never accept schema or confidence alone. Any mismatch, conflicting verified rows, changed source or incomplete observation requires escalation or an explicit failure.","options":["accept-checked-answer","escalate"],"question":"Does this answer have a fresh executable source check?"},"key":"evidence","section":"judge"}
J evidence accept-checked-answer|escalate:"Does this answer have a fresh executable source check?" -- Never accept schema or confidence alone. Any mismatch, conflicting verified rows, changed source or incomplete observation requires escalation or an explicit failure.
V J evidence -> human:operator why:"explicit choice required"
-- @record {"chapter":"cascade","data":{"failure":"Fuzzy reuse changes digits, IDs, dates or UI values","recovery":"Use exact source scripts and exact scoped preconditions; reject changed hashes"},"key":"0","section":"pitfalls"}
X Fuzzy reuse changes digits, IDs, dates or UI values -> Use exact source scripts and exact scoped preconditions; reject changed hashes
-- @record {"chapter":"cascade","data":{"failure":"Memory has expired, conflicting or altered provenance","recovery":"Refuse reuse and escalate; do not execute a disputed transition"},"key":"1","section":"pitfalls"}
X Memory has expired, conflicting or altered provenance -> Refuse reuse and escalate; do not execute a disputed transition
-- @record {"chapter":"cascade","data":{"failure":"A model is unavailable or its answer fails the executable check","recovery":"Retain actual usage/failure and escalate through the explicitly named routes; never silently substitute a provider"},"key":"2","section":"pitfalls"}
X A model is unavailable or its answer fails the executable check -> Retain actual usage/failure and escalate through the explicitly named routes; never silently substitute a provider
-- @record {"chapter":"cascade","data":{"failure":"A replayed operation lacks current authority or known effects","recovery":"Retain the original native grant, exact scope, manual hash and observer checks; never replay uncertain effects"},"key":"3","section":"pitfalls"}
X A replayed operation lacks current authority or known effects -> Retain the original native grant, exact scope, manual hash and observer checks; never replay uncertain effects
-- @record {"chapter":"cascade","data":"LAYA System 1 uses NEYVIA_LAYA_URL for Boolean or finite-choice decisions and fully required flat objects of those fields. Other schemas or an unavailable service abstain; confidence and host semantic checks still govern acceptance. The shipped T15-r2 browser client grants no execution authority.","key":"0","section":"frontier"}
F LAYA System 1 uses NEYVIA_LAYA_URL for Boolean or finite-choice decisions and fully required flat objects of those fields. Other schemas or an unavailable service abstain; confidence and host semantic checks still govern acceptance. The shipped T15-r2 browser client grants no execution authority.
-- @record {"chapter":"cascade","data":"Local quantization, speculative decoding and model-weight inference passes from plan 02 are separate from this system-level cascade","key":"1","section":"frontier"}
F Local quantization, speculative decoding and model-weight inference passes from plan 02 are separate from this system-level cascade
-- @record {"chapter":"cascade","data":"Latency quantiles report actual sample counts and observed hardware; provider startup and network variability are included","key":"2","section":"frontier"}
F Latency quantiles report actual sample counts and observed hardware; provider startup and network variability are included
-- @record {"chapter":"cascade","data":"Autopilot runs use the same validated cascade by default; efficiency=false retains the explicit paired baseline","key":"0","section":"guidance"}
M efficiency "Autopilot runs use the same validated cascade by default; efficiency=false retains the explicit paired baseline" src:"authored manual" state:verified
-- @record {"chapter":"cascade","data":"Route order is script, successful scoped memory, System 1, exact cache, GPT-6 Luna, GPT-6.1 Sol","key":"1","section":"guidance"}
M efficiency "Route order is script, successful scoped memory, System 1, exact cache, GPT-6 Luna, GPT-6.1 Sol" src:"authored manual" state:verified
-- @record {"chapter":"cascade","data":"Positive transitions carry typed goals, preconditions, operations, effects, failures and receipt hashes; composites are learned only from completely verified journeys","key":"2","section":"guidance"}
M efficiency "Positive transitions carry typed goals, preconditions, operations, effects, failures and receipt hashes; composites are learned only from completely verified journeys" src:"authored manual" state:verified
L efficiency.laya v1 -- LAYA by default: the 0.95 gate, receipts, hosting, routing and the fast verify call
-- @record {"chapter":"laya","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t12"},"tool":"neyvia.efficiency.laya_status"},"key":"laya","section":"state"}
S efficiency.laya:json:"{\"type\":\"object\"}"=neyvia.efficiency.laya_status()
-- @record {"chapter":"laya","data":{"effect":"Read whether the Neyvia-owned LAYA service is running (and why not), answered and handed-up decisions per task, latency, estimated tokens saved and computer-use activity","pre":"Selected workspace","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_status","tool":"neyvia.efficiency.laya_status"},"key":"status","section":"actions"}
A neyvia.efficiency.laya_status() -> json:"{\"type\":\"object\"}" -- Read whether the Neyvia-owned LAYA service is running (and why not), answered and handed-up decisions per task, latency, estimated tokens saved and computer-use activity
F verify-status "No authored observer check is bound to neyvia.efficiency.laya_status" -> ask operator blocks:neyvia.efficiency.laya_status
-- @record {"chapter":"laya","data":{"effect":"Ask LAYA to confirm a candidate answer; escalate is true unless LAYA is above the 0.95 gate, and then the big-model check runs as before","pre":"taste_triage, page_done or cl_route with the evidence that question needs","returns":{"$cl_type":"t17"},"reversible":true,"schema":"neyvia.efficiency.laya_verify","tool":"neyvia.efficiency.laya_verify"},"key":"verify","section":"actions"}
A neyvia.efficiency.laya_verify(question:json:"{\"type\":\"string\",\"enum\":[\"taste_triage\",\"page_done\",\"cl_route\",\"repair_retention\"]}" candidate?:any evidence:json:"{\"type\":\"object\"}") -> {answer:any confidence:any escalate:bool agrees:any ..} -- Ask LAYA to confirm a candidate answer; escalate is true unless LAYA is above the 0.95 gate, and then the big-model check runs as before
C neyvia.efficiency.laya_verify verify-shape:matches(neyvia.efficiency.laya_verify(candidate:true evidence:{} question:"page_done") {properties:{escalate:{const:true}} required:["answer" "confidence" "escalate" "agrees"] type:"object"})
-- @record {"chapter":"laya","data":{"effect":"Observe one part of LAYA against stand-ins; returns flat facts","pre":"Selected workspace","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_selfcheck","tool":"neyvia.efficiency.laya_selfcheck"},"key":"selfcheck","section":"actions"}
A neyvia.efficiency.laya_selfcheck(part:json:"{\"type\":\"string\",\"enum\":[\"gate\",\"ledger\",\"host\",\"ui\",\"preview\",\"route\",\"shutdown\",\"instant\"]}") -> json:"{\"type\":\"object\"}" -- Observe one part of LAYA against stand-ins; returns flat facts
C neyvia.efficiency.laya_selfcheck gate-holds:matches(neyvia.efficiency.laya_selfcheck(part:"gate") {additionalProperties:true properties:{acceptedConfidentAnswer:{const:true} belowGateEscalates:{const:true} conflictEscalates:{const:true} incompleteChecksEscalate:{const:true} ledgerAnswered:{const:1} ledgerEscalated:{const:2} noReceiptSummary:{const:""} receiptSummary:{const:"clicked save"} sentCheckHitCount:{const:true} sentSetAndScope:{const:true} verifyAgrees:{const:true} verifyDisagrees:{const:true} verifyEscalatesWhenUnsure:{const:true} verifyUnknownQuestionEscalates:{const:true}} required:["acceptedConfidentAnswer" "belowGateEscalates" "conflictEscalates" "incompleteChecksEscalate" "ledgerAnswered" "ledgerEscalated" "noReceiptSummary" "receiptSummary" "sentCheckHitCount" "sentSetAndScope" "verifyAgrees" "verifyDisagrees" "verifyEscalatesWhenUnsure" "verifyUnknownQuestionEscalates"] type:"object"})
C neyvia.efficiency.laya_selfcheck routing-holds:matches(neyvia.efficiency.laya_selfcheck(part:"route") {additionalProperties:true properties:{askedLayerAndVocabulary:{const:true} confirmedClearCandidate:{const:true} hostIgnoresUnknownLayer:{const:true} hostRoutesWhenConfirmed:{const:true} hostRoutingSwitchedOff:{const:true} hostSilentWithoutLaya:{const:true} layaNoIsNotARoute:{const:true} noCandidateEscalates:{const:true} tieEscalates:{const:true} verifyRouteNo:{const:true} verifyRouteYes:{const:true}} required:["askedLayerAndVocabulary" "confirmedClearCandidate" "hostIgnoresUnknownLayer" "hostRoutesWhenConfirmed" "hostRoutingSwitchedOff" "hostSilentWithoutLaya" "layaNoIsNotARoute" "noCandidateEscalates" "tieEscalates" "verifyRouteNo" "verifyRouteYes"] type:"object"})
C neyvia.efficiency.laya_selfcheck receipts-hold:matches(neyvia.efficiency.laya_selfcheck(part:"ledger") {additionalProperties:true properties:{agentDesktopBackground:{const:true} browserEscalateIsHandedUp:{const:true} browserPostcheckIsAnswered:{const:true} browserUnavailable:{const:true} cascadeExactValuesBypass:{const:true} cascadeReceipt:{const:true} cascadeRoute:{const:"system1"} computerUse:{const:[3 2 1 1 1]} tasteBlockingStaysDeterministic:{const:true} tasteCleanShips:{const:true} tasteGreyZoneAnswered:{const:true} tasteLedger:{const:[1 1 2]} tasteUnsureEscalates:{const:true} triageAnswered:{const:1} triageEscalated:{const:2} triageRoutes:{const:["laya" "escalate" "escalate" "unavailable"]} triageTokensSaved:{const:true} triageUnavailable:{const:1}} required:["agentDesktopBackground" "browserEscalateIsHandedUp" "browserPostcheckIsAnswered" "browserUnavailable" "cascadeExactValuesBypass" "cascadeReceipt" "cascadeRoute" "computerUse" "tasteBlockingStaysDeterministic" "tasteCleanShips" "tasteGreyZoneAnswered" "tasteLedger" "tasteUnsureEscalates" "triageAnswered" "triageEscalated" "triageRoutes" "triageTokensSaved" "triageUnavailable"] type:"object"})
C neyvia.efficiency.laya_selfcheck hosting-holds:matches(neyvia.efficiency.laya_selfcheck(part:"host") {additionalProperties:true properties:{childStopsWithHost:{const:true} degradesWithReason:{const:{missingRuntime:true portTaken:true reservedPort:true switchedOff:true}} endpointFollowsOwnedService:{const:true} endpointRefusesWithoutService:{const:true} ownedChild:{const:true} restartsAfterCrash:{const:true} startsAndIsReady:{const:true} statusExplainsAbsence:{const:true} statusReportsOwnedReady:{const:true}} required:["childStopsWithHost" "degradesWithReason" "endpointFollowsOwnedService" "endpointRefusesWithoutService" "ownedChild" "restartsAfterCrash" "startsAndIsReady" "statusExplainsAbsence" "statusReportsOwnedReady"] type:"object"})
C neyvia.efficiency.laya_selfcheck ui-models-hold:matches(neyvia.efficiency.laya_selfcheck(part:"ui") {additionalProperties:true properties:{changeWaitsOneTick:{const:true} computerUse:{const:{actions:5 disturbanceTone:"green" line:"Computer use is set up." ready:true used:true workflows:"2 of 3 LAYA workflow runs checked out"}} formats:{const:["950" "—" "42 ms" "2.3 s"]} keepsChangingStopsWaiting:{const:true} liveLabels:{const:["Live" "Live · just updated" "Live · updated 10 s ago" "Live · updated 3 min ago"]} quietNeverReloads:{const:true} row:{const:{answerRate:"67%" answered:2 escalated:1 key:"browser|browser.decide" p50:"31 ms" path:"browser.decide" saved:"400" task:"browser" unavailable:0}} serviceReason:{const:true} serviceTones:{const:["idle" "red" "green"]} stripLive:{const:["LAYA 7/10 · ~12.4k tok saved" "green"]} stripOff:{const:"LAYA off"} stripOffline:{const:"LAYA offline"} stripUnread:{const:"LAYA —"}} required:["changeWaitsOneTick" "computerUse" "formats" "keepsChangingStopsWaiting" "liveLabels" "quietNeverReloads" "row" "serviceReason" "serviceTones" "stripLive" "stripOff" "stripOffline" "stripUnread"] type:"object"})
C neyvia.efficiency.laya_selfcheck preview-marker-holds:matches(neyvia.efficiency.laya_selfcheck(part:"preview") {additionalProperties:true properties:{missingIsExplicit:{const:true} openCarriesSameMarker:{const:true} pageEditChangesMarker:{const:true} statReadsNoContent:{const:true} stylesheetEditChangesMarker:{const:true} unchangedKeepsMarker:{const:true}} required:["missingIsExplicit" "openCarriesSameMarker" "pageEditChangesMarker" "statReadsNoContent" "stylesheetEditChangesMarker" "unchangedKeepsMarker"] type:"object"})
C neyvia.efficiency.laya_selfcheck warmup-holds:matches(neyvia.efficiency.laya_selfcheck(part:"ui") {additionalProperties:true properties:{healthWarming:{const:"LAYA is warming up"} stripReady:{const:"LAYA ready"} stripWarming:{const:"LAYA warming up"} warmupAbstains:{const:true} warmupReason:{const:"LAYA is warming up"} warmupReport:{const:true} warmupStates:{const:{idle:true loading:false partial:true ready:true waiting:false warming:false}}} required:["stripWarming" "healthWarming" "stripReady" "warmupAbstains" "warmupReason" "warmupReport" "warmupStates"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"gate"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"acceptedConfidentAnswer":{"const":true},"belowGateEscalates":{"const":true},"conflictEscalates":{"const":true},"incompleteChecksEscalate":{"const":true},"ledgerAnswered":{"const":1},"ledgerEscalated":{"const":2},"noReceiptSummary":{"const":""},"receiptSummary":{"const":"clicked save"},"sentCheckHitCount":{"const":true},"sentSetAndScope":{"const":true},"verifyAgrees":{"const":true},"verifyDisagrees":{"const":true},"verifyEscalatesWhenUnsure":{"const":true},"verifyUnknownQuestionEscalates":{"const":true}},"required":["acceptedConfidentAnswer","belowGateEscalates","conflictEscalates","incompleteChecksEscalate","ledgerAnswered","ledgerEscalated","noReceiptSummary","receiptSummary","sentCheckHitCount","sentSetAndScope","verifyAgrees","verifyDisagrees","verifyEscalatesWhenUnsure","verifyUnknownQuestionEscalates"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"gate-holds","section":"checks"}
C neyvia.efficiency.laya_selfcheck gate-holds:matches(neyvia.efficiency.laya_selfcheck(part:"gate") {additionalProperties:true properties:{acceptedConfidentAnswer:{const:true} belowGateEscalates:{const:true} conflictEscalates:{const:true} incompleteChecksEscalate:{const:true} ledgerAnswered:{const:1} ledgerEscalated:{const:2} noReceiptSummary:{const:""} receiptSummary:{const:"clicked save"} sentCheckHitCount:{const:true} sentSetAndScope:{const:true} verifyAgrees:{const:true} verifyDisagrees:{const:true} verifyEscalatesWhenUnsure:{const:true} verifyUnknownQuestionEscalates:{const:true}} required:["acceptedConfidentAnswer" "belowGateEscalates" "conflictEscalates" "incompleteChecksEscalate" "ledgerAnswered" "ledgerEscalated" "noReceiptSummary" "receiptSummary" "sentCheckHitCount" "sentSetAndScope" "verifyAgrees" "verifyDisagrees" "verifyEscalatesWhenUnsure" "verifyUnknownQuestionEscalates"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"route"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"askedLayerAndVocabulary":{"const":true},"confirmedClearCandidate":{"const":true},"hostIgnoresUnknownLayer":{"const":true},"hostRoutesWhenConfirmed":{"const":true},"hostRoutingSwitchedOff":{"const":true},"hostSilentWithoutLaya":{"const":true},"layaNoIsNotARoute":{"const":true},"noCandidateEscalates":{"const":true},"tieEscalates":{"const":true},"verifyRouteNo":{"const":true},"verifyRouteYes":{"const":true}},"required":["askedLayerAndVocabulary","confirmedClearCandidate","hostIgnoresUnknownLayer","hostRoutesWhenConfirmed","hostRoutingSwitchedOff","hostSilentWithoutLaya","layaNoIsNotARoute","noCandidateEscalates","tieEscalates","verifyRouteNo","verifyRouteYes"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"routing-holds","section":"checks"}
C neyvia.efficiency.laya_selfcheck routing-holds:matches(neyvia.efficiency.laya_selfcheck(part:"route") {additionalProperties:true properties:{askedLayerAndVocabulary:{const:true} confirmedClearCandidate:{const:true} hostIgnoresUnknownLayer:{const:true} hostRoutesWhenConfirmed:{const:true} hostRoutingSwitchedOff:{const:true} hostSilentWithoutLaya:{const:true} layaNoIsNotARoute:{const:true} noCandidateEscalates:{const:true} tieEscalates:{const:true} verifyRouteNo:{const:true} verifyRouteYes:{const:true}} required:["askedLayerAndVocabulary" "confirmedClearCandidate" "hostIgnoresUnknownLayer" "hostRoutesWhenConfirmed" "hostRoutingSwitchedOff" "hostSilentWithoutLaya" "layaNoIsNotARoute" "noCandidateEscalates" "tieEscalates" "verifyRouteNo" "verifyRouteYes"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"ledger"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"agentDesktopBackground":{"const":true},"browserEscalateIsHandedUp":{"const":true},"browserPostcheckIsAnswered":{"const":true},"browserUnavailable":{"const":true},"cascadeExactValuesBypass":{"const":true},"cascadeReceipt":{"const":true},"cascadeRoute":{"const":"system1"},"computerUse":{"const":[3,2,1,1,1]},"tasteBlockingStaysDeterministic":{"const":true},"tasteCleanShips":{"const":true},"tasteGreyZoneAnswered":{"const":true},"tasteLedger":{"const":[1,1,2]},"tasteUnsureEscalates":{"const":true},"triageAnswered":{"const":1},"triageEscalated":{"const":2},"triageRoutes":{"const":["laya","escalate","escalate","unavailable"]},"triageTokensSaved":{"const":true},"triageUnavailable":{"const":1}},"required":["agentDesktopBackground","browserEscalateIsHandedUp","browserPostcheckIsAnswered","browserUnavailable","cascadeExactValuesBypass","cascadeReceipt","cascadeRoute","computerUse","tasteBlockingStaysDeterministic","tasteCleanShips","tasteGreyZoneAnswered","tasteLedger","tasteUnsureEscalates","triageAnswered","triageEscalated","triageRoutes","triageTokensSaved","triageUnavailable"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"receipts-hold","section":"checks"}
C neyvia.efficiency.laya_selfcheck receipts-hold:matches(neyvia.efficiency.laya_selfcheck(part:"ledger") {additionalProperties:true properties:{agentDesktopBackground:{const:true} browserEscalateIsHandedUp:{const:true} browserPostcheckIsAnswered:{const:true} browserUnavailable:{const:true} cascadeExactValuesBypass:{const:true} cascadeReceipt:{const:true} cascadeRoute:{const:"system1"} computerUse:{const:[3 2 1 1 1]} tasteBlockingStaysDeterministic:{const:true} tasteCleanShips:{const:true} tasteGreyZoneAnswered:{const:true} tasteLedger:{const:[1 1 2]} tasteUnsureEscalates:{const:true} triageAnswered:{const:1} triageEscalated:{const:2} triageRoutes:{const:["laya" "escalate" "escalate" "unavailable"]} triageTokensSaved:{const:true} triageUnavailable:{const:1}} required:["agentDesktopBackground" "browserEscalateIsHandedUp" "browserPostcheckIsAnswered" "browserUnavailable" "cascadeExactValuesBypass" "cascadeReceipt" "cascadeRoute" "computerUse" "tasteBlockingStaysDeterministic" "tasteCleanShips" "tasteGreyZoneAnswered" "tasteLedger" "tasteUnsureEscalates" "triageAnswered" "triageEscalated" "triageRoutes" "triageTokensSaved" "triageUnavailable"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"host"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"childStopsWithHost":{"const":true},"degradesWithReason":{"const":{"missingRuntime":true,"portTaken":true,"reservedPort":true,"switchedOff":true}},"endpointFollowsOwnedService":{"const":true},"endpointRefusesWithoutService":{"const":true},"ownedChild":{"const":true},"restartsAfterCrash":{"const":true},"startsAndIsReady":{"const":true},"statusExplainsAbsence":{"const":true},"statusReportsOwnedReady":{"const":true}},"required":["childStopsWithHost","degradesWithReason","endpointFollowsOwnedService","endpointRefusesWithoutService","ownedChild","restartsAfterCrash","startsAndIsReady","statusExplainsAbsence","statusReportsOwnedReady"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"hosting-holds","section":"checks"}
C neyvia.efficiency.laya_selfcheck hosting-holds:matches(neyvia.efficiency.laya_selfcheck(part:"host") {additionalProperties:true properties:{childStopsWithHost:{const:true} degradesWithReason:{const:{missingRuntime:true portTaken:true reservedPort:true switchedOff:true}} endpointFollowsOwnedService:{const:true} endpointRefusesWithoutService:{const:true} ownedChild:{const:true} restartsAfterCrash:{const:true} startsAndIsReady:{const:true} statusExplainsAbsence:{const:true} statusReportsOwnedReady:{const:true}} required:["childStopsWithHost" "degradesWithReason" "endpointFollowsOwnedService" "endpointRefusesWithoutService" "ownedChild" "restartsAfterCrash" "startsAndIsReady" "statusExplainsAbsence" "statusReportsOwnedReady"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"ui"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"changeWaitsOneTick":{"const":true},"computerUse":{"const":{"actions":5,"disturbanceTone":"green","line":"Computer use is set up.","ready":true,"used":true,"workflows":"2 of 3 LAYA workflow runs checked out"}},"formats":{"const":["950","—","42 ms","2.3 s"]},"keepsChangingStopsWaiting":{"const":true},"liveLabels":{"const":["Live","Live · just updated","Live · updated 10 s ago","Live · updated 3 min ago"]},"quietNeverReloads":{"const":true},"row":{"const":{"answerRate":"67%","answered":2,"escalated":1,"key":"browser|browser.decide","p50":"31 ms","path":"browser.decide","saved":"400","task":"browser","unavailable":0}},"serviceReason":{"const":true},"serviceTones":{"const":["idle","red","green"]},"stripLive":{"const":["LAYA 7/10 · ~12.4k tok saved","green"]},"stripOff":{"const":"LAYA off"},"stripOffline":{"const":"LAYA offline"},"stripUnread":{"const":"LAYA —"}},"required":["changeWaitsOneTick","computerUse","formats","keepsChangingStopsWaiting","liveLabels","quietNeverReloads","row","serviceReason","serviceTones","stripLive","stripOff","stripOffline","stripUnread"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"ui-models-hold","section":"checks"}
C neyvia.efficiency.laya_selfcheck ui-models-hold:matches(neyvia.efficiency.laya_selfcheck(part:"ui") {additionalProperties:true properties:{changeWaitsOneTick:{const:true} computerUse:{const:{actions:5 disturbanceTone:"green" line:"Computer use is set up." ready:true used:true workflows:"2 of 3 LAYA workflow runs checked out"}} formats:{const:["950" "—" "42 ms" "2.3 s"]} keepsChangingStopsWaiting:{const:true} liveLabels:{const:["Live" "Live · just updated" "Live · updated 10 s ago" "Live · updated 3 min ago"]} quietNeverReloads:{const:true} row:{const:{answerRate:"67%" answered:2 escalated:1 key:"browser|browser.decide" p50:"31 ms" path:"browser.decide" saved:"400" task:"browser" unavailable:0}} serviceReason:{const:true} serviceTones:{const:["idle" "red" "green"]} stripLive:{const:["LAYA 7/10 · ~12.4k tok saved" "green"]} stripOff:{const:"LAYA off"} stripOffline:{const:"LAYA offline"} stripUnread:{const:"LAYA —"}} required:["changeWaitsOneTick" "computerUse" "formats" "keepsChangingStopsWaiting" "liveLabels" "quietNeverReloads" "row" "serviceReason" "serviceTones" "stripLive" "stripOff" "stripOffline" "stripUnread"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"preview"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"missingIsExplicit":{"const":true},"openCarriesSameMarker":{"const":true},"pageEditChangesMarker":{"const":true},"statReadsNoContent":{"const":true},"stylesheetEditChangesMarker":{"const":true},"unchangedKeepsMarker":{"const":true}},"required":["missingIsExplicit","openCarriesSameMarker","pageEditChangesMarker","statReadsNoContent","stylesheetEditChangesMarker","unchangedKeepsMarker"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"preview-marker-holds","section":"checks"}
C neyvia.efficiency.laya_selfcheck preview-marker-holds:matches(neyvia.efficiency.laya_selfcheck(part:"preview") {additionalProperties:true properties:{missingIsExplicit:{const:true} openCarriesSameMarker:{const:true} pageEditChangesMarker:{const:true} statReadsNoContent:{const:true} stylesheetEditChangesMarker:{const:true} unchangedKeepsMarker:{const:true}} required:["missingIsExplicit" "openCarriesSameMarker" "pageEditChangesMarker" "statReadsNoContent" "stylesheetEditChangesMarker" "unchangedKeepsMarker"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"candidate":true,"evidence":{},"question":"page_done"},"expect":{"op":"schema","path":"","schema":{"properties":{"escalate":{"const":true}},"required":["answer","confidence","escalate","agrees"],"type":"object"}},"tool":"neyvia.efficiency.laya_verify"},"key":"verify-shape","section":"checks"}
C neyvia.efficiency.laya_verify verify-shape:matches(neyvia.efficiency.laya_verify(candidate:true evidence:{} question:"page_done") {properties:{escalate:{const:true}} required:["answer" "confidence" "escalate" "agrees"] type:"object"})
-- @record {"chapter":"laya","data":{"args":{"part":"ui"},"expect":{"op":"schema","path":"","schema":{"additionalProperties":true,"properties":{"healthWarming":{"const":"LAYA is warming up"},"stripReady":{"const":"LAYA ready"},"stripWarming":{"const":"LAYA warming up"},"warmupAbstains":{"const":true},"warmupReason":{"const":"LAYA is warming up"},"warmupReport":{"const":true},"warmupStates":{"const":{"idle":true,"loading":false,"partial":true,"ready":true,"waiting":false,"warming":false}}},"required":["stripWarming","healthWarming","stripReady","warmupAbstains","warmupReason","warmupReport","warmupStates"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"warmup-holds","section":"checks"}
C neyvia.efficiency.laya_selfcheck warmup-holds:matches(neyvia.efficiency.laya_selfcheck(part:"ui") {additionalProperties:true properties:{healthWarming:{const:"LAYA is warming up"} stripReady:{const:"LAYA ready"} stripWarming:{const:"LAYA warming up"} warmupAbstains:{const:true} warmupReason:{const:"LAYA is warming up"} warmupReport:{const:true} warmupStates:{const:{idle:true loading:false partial:true ready:true waiting:false warming:false}}} required:["stripWarming" "healthWarming" "stripReady" "warmupAbstains" "warmupReason" "warmupReport" "warmupStates"] type:"object"})
-- @record {"chapter":"laya","data":{"goal":"Prove LAYA's gate, receipts, hosting, routing, UI models, live-preview marker and verify call with observed facts","inputs":{"$cl_type":"t15"},"steps":[{"action":"selfcheck","args":{"part":"gate"},"check":"gate-holds","save":"observed_gate"},{"action":"selfcheck","args":{"part":"route"},"check":"routing-holds","save":"observed_route"},{"action":"selfcheck","args":{"part":"ledger"},"check":"receipts-hold","save":"observed_ledger"},{"action":"selfcheck","args":{"part":"host"},"check":"hosting-holds","save":"observed_host"},{"action":"selfcheck","args":{"part":"ui"},"check":"ui-models-hold","save":"observed_ui"},{"action":"selfcheck","args":{"part":"preview"},"check":"preview-marker-holds","save":"observed_preview"},{"action":"verify","args":{"candidate":true,"evidence":{},"question":"page_done"},"check":"verify-shape","save":"verdict"},{"action":"status","args":{},"save":"laya"}]},"key":"prove-laya","section":"procedures"}
P prove-laya():observed_gate=neyvia.efficiency.laya_selfcheck(part:"gate") C gate-holds; observed_route=neyvia.efficiency.laya_selfcheck(part:"route") C routing-holds; observed_ledger=neyvia.efficiency.laya_selfcheck(part:"ledger") C receipts-hold; observed_host=neyvia.efficiency.laya_selfcheck(part:"host") C hosting-holds; observed_ui=neyvia.efficiency.laya_selfcheck(part:"ui") C ui-models-hold; observed_preview=neyvia.efficiency.laya_selfcheck(part:"preview") C preview-marker-holds; verdict=neyvia.efficiency.laya_verify(candidate:true evidence:{} question:"page_done") C verify-shape; laya=neyvia.efficiency.laya_status() -- Prove LAYA's gate, receipts, hosting, routing, UI models, live-preview marker and verify call with observed facts
V P prove-laya -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"laya","data":{"goal":"Ask LAYA to confirm a low-confidence answer before spending a big-model check","inputs":{"$cl_type":"t18"},"steps":[{"action":"verify","args":{"evidence":{"$input":"evidence"},"question":{"$input":"question"}},"save":"verdict"}]},"key":"verify-with-laya","section":"procedures"}
P verify-with-laya(question:json:"{\"type\":\"string\",\"enum\":[\"taste_triage\",\"page_done\",\"cl_route\",\"repair_retention\"]}" evidence:json:"{\"type\":\"object\"}"):verdict=neyvia.efficiency.laya_verify(evidence:evidence question:question) -- Ask LAYA to confirm a low-confidence answer before spending a big-model check
V P verify-with-laya -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"laya","data":{"goal":"Prove request abstention and honest UI status while instant encoders warm, without loading encoders or starting a service","inputs":{"$cl_type":"t15"},"steps":[{"action":"selfcheck","args":{"part":"ui"},"check":"ui-models-hold","save":"observed_ui"},{"action":"selfcheck","args":{"part":"ui"},"check":"warmup-holds","save":"observed_warmup"}]},"key":"prove-warmup","section":"procedures"}
P prove-warmup():observed_ui=neyvia.efficiency.laya_selfcheck(part:"ui") C ui-models-hold; observed_warmup=neyvia.efficiency.laya_selfcheck(part:"ui") C warmup-holds -- Prove request abstention and honest UI status while instant encoders warm, without loading encoders or starting a service
V P prove-warmup -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"laya","data":{"failure":"LAYA is unavailable, below the 0.95 gate or its answers conflict","recovery":"verify returns escalate true; run the big-model check as before and never treat silence as agreement"},"key":"0","section":"pitfalls"}
X LAYA is unavailable, below the 0.95 gate or its answers conflict -> verify returns escalate true; run the big-model check as before and never treat silence as agreement
-- @record {"chapter":"laya","data":{"failure":"A cheap check is treated as authority for an irreversible step","recovery":"LAYA is advisory; the executable observer checks still decide"},"key":"1","section":"pitfalls"}
X A cheap check is treated as authority for an irreversible step -> LAYA is advisory; the executable observer checks still decide
-- @record {"chapter":"laya","data":"LAYA answers only questions it was calibrated on (taste_triage, page_done, cl_route); calibration numbers are in docs/evidence/laya-calibration.json","key":"0","section":"frontier"}
F LAYA answers only questions it was calibrated on (taste_triage, page_done, cl_route); calibration numbers are in docs/evidence/laya-calibration.json
-- @record {"chapter":"laya","data":"Token savings are an estimate; docs/evidence/laya-savings.json holds the measured time and tokens against the big-model check","key":"1","section":"frontier"}
F Token savings are an estimate; docs/evidence/laya-savings.json holds the measured time and tokens against the big-model check
-- @record {"chapter":"laya","data":"A model that is unsure of its output calls verify first; only an escalate result pays for the big-model check","key":"0","section":"guidance"}
M efficiency "A model that is unsure of its output calls verify first; only an escalate result pays for the big-model check" src:"authored manual" state:verified
-- @record {"chapter":"laya","data":"prove-laya runs the whole contract set; the host part takes about half a minute because it restarts a stand-in service after a crash","key":"1","section":"guidance"}
M efficiency "prove-laya runs the whole contract set; the host part takes about half a minute because it restarts a stand-in service after a crash" src:"authored manual" state:verified
L efficiency.learned-capabilities v1 -- Calibrated LAYA capabilities and separate personal conditioning
-- @record {"chapter":"learned-capabilities","data":{"effect":"Write a local episode immediately; explicit replay is separate from calibrated novel-case admission.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_learn","tool":"neyvia.efficiency.laya_learn"},"key":"laya_learn","section":"actions"}
A neyvia.efficiency.laya_learn(domain:str#..16000 input:any label:any source:str#..16000 user?:str#..16000 layer?:json:"{\"type\":\"string\",\"enum\":[\"personal\",\"corrective\"]}" weight?:json:"{\"type\":\"number\",\"exclusiveMinimum\":0,\"maximum\":1}" evidence?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Write a local episode immediately; explicit replay is separate from calibrated novel-case admission.
C neyvia.efficiency.laya_learn instant-first:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .answer == false
C neyvia.efficiency.laya_learn instant-second:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .answer == true
-- @record {"chapter":"learned-capabilities","data":{"effect":"Query personal then corrective episodes, abstaining on conflicting or uncalibrated regions.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_query","tool":"neyvia.efficiency.laya_query"},"key":"laya_query","section":"actions"}
A neyvia.efficiency.laya_query(domain:str#..16000 input:any user?:str#..16000 labels?:json:"{\"type\":\"array\"}") -> json:"{\"type\":\"object\"}" -- Query personal then corrective episodes, abstaining on conflicting or uncalibrated regions.
F verify-laya_query "No authored observer check is bound to neyvia.efficiency.laya_query" -> ask operator blocks:neyvia.efficiency.laya_query
-- @record {"chapter":"learned-capabilities","data":{"effect":"Append a provenance tombstone, removing matching episodes from subsequent decisions.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_forget","tool":"neyvia.efficiency.laya_forget"},"key":"laya_forget","section":"actions"}
A neyvia.efficiency.laya_forget(source:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Append a provenance tombstone, removing matching episodes from subsequent decisions.
C neyvia.efficiency.laya_forget instant-forgotten:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .escalate == true
-- @record {"chapter":"learned-capabilities","data":{"effect":"Ingest local Paul votes and incoming label files with idempotent provenance.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_ingest","tool":"neyvia.efficiency.laya_ingest"},"key":"laya_ingest","section":"actions"}
A neyvia.efficiency.laya_ingest() -> json:"{\"type\":\"object\"}" -- Ingest local Paul votes and incoming label files with idempotent provenance.
F verify-laya_ingest "No authored observer check is bound to neyvia.efficiency.laya_ingest" -> ask operator blocks:neyvia.efficiency.laya_ingest
-- @record {"chapter":"learned-capabilities","data":{"effect":"Record weak kept/reverted, edit, acceptance, reask, route and verifier signals; never self-certifies a prediction.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_experience","tool":"neyvia.efficiency.laya_experience"},"key":"laya_experience","section":"actions"}
A neyvia.efficiency.laya_experience(domain:str#..16000 input:any signal:str#..16000 source:str#..16000 user?:str#..16000 value?:any elapsedSeconds?:num) -> json:"{\"type\":\"object\"}" -- Record weak kept/reverted, edit, acceptance, reask, route and verifier signals; never self-certifies a prediction.
F verify-laya_experience "No authored observer check is bound to neyvia.efficiency.laya_experience" -> ask operator blocks:neyvia.efficiency.laya_experience
-- @record {"chapter":"learned-capabilities","data":{"effect":"Retrieve learned manual/action/check/procedure candidates. Abstain unless independent calibration admits the route; no execution authority.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_route","tool":"neyvia.efficiency.laya_route"},"key":"laya_route","section":"actions"}
A neyvia.efficiency.laya_route(intent:str#..16000 consultLaya?:bool) -> json:"{\"type\":\"object\"}" -- Retrieve learned manual/action/check/procedure candidates. Abstain unless independent calibration admits the route; no execution authority.
C neyvia.efficiency.laya_route unknown-abstains:neyvia.efficiency.laya_route(intent:"zzqvxtp") .escalate == true
-- @record {"chapter":"learned-capabilities","data":{"effect":"Estimate a step outcome from receipt evidence with a separately calibrated learned head. Never establishes completion authority.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_outcome","tool":"neyvia.efficiency.laya_outcome"},"key":"laya_outcome","section":"actions"}
A neyvia.efficiency.laya_outcome(receipt:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Estimate a step outcome from receipt evidence with a separately calibrated learned head. Never establishes completion authority.
C neyvia.efficiency.laya_outcome no-evidence-abstains:neyvia.efficiency.laya_outcome(receipt:{}) .reason == "missing-independent-receipt-proof"
-- @record {"chapter":"learned-capabilities","data":{"effect":"Read learned corpus coverage, held-out metrics and current artifact fingerprints. Does not start training.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_training","tool":"neyvia.efficiency.laya_training"},"key":"laya_training","section":"actions"}
A neyvia.efficiency.laya_training() -> json:"{\"type\":\"object\"}" -- Read learned corpus coverage, held-out metrics and current artifact fingerprints. Does not start training.
C neyvia.efficiency.laya_training gate-is-frozen:neyvia.efficiency.laya_training() .gate == 0.95
C neyvia.efficiency.laya_training encoder-unchanged:neyvia.efficiency.laya_training() .baseWeightsChanged == false
-- @record {"chapter":"learned-capabilities","data":{"effect":"Observe LAYA's gate, receipts, hosting, routing, UI models and live-preview marker against stand-ins; returns flat facts for the manual's contracts. Touches no real service.","pre":"Task-local learned artifacts exist","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.efficiency.laya_selfcheck","tool":"neyvia.efficiency.laya_selfcheck"},"key":"laya_selfcheck","section":"actions"}
A neyvia.efficiency.laya_selfcheck(part:json:"{\"type\":\"string\",\"enum\":[\"gate\",\"ledger\",\"host\",\"ui\",\"preview\",\"route\",\"shutdown\",\"instant\"]}") -> json:"{\"type\":\"object\"}" -- Observe LAYA's gate, receipts, hosting, routing, UI models and live-preview marker against stand-ins; returns flat facts for the manual's contracts. Touches no real service.
C neyvia.efficiency.laya_selfcheck shutdown-during-timeout:neyvia.efficiency.laya_selfcheck(part:"shutdown") .staysStoppedAfterTimeout == true
C neyvia.efficiency.laya_selfcheck shutdown-during-ready:neyvia.efficiency.laya_selfcheck(part:"shutdown") .staysStoppedAfterReady == true
C neyvia.efficiency.laya_selfcheck instant-effects:matches(neyvia.efficiency.laya_selfcheck(part:"instant") {properties:{atomicImportCommits:{const:true} atomicImportRollback:{const:true} calibratesOnWrite:{const:true} contradictionAbstains:{const:true} correctionChangesNextAnswer:{const:true} evaluationHoldoutExcluded:{const:true} forgetRecalibrates:{const:true} forgetRemovesAnswer:{const:true} forgetResolvesConflict:{const:true} holdoutSupersedesTrainingRevision:{const:true} incrementalMatchesRebuild:{const:true} manualTriageUsesRoutingEpisodes:{const:true} novelAbstains:{const:true} novelCrossConformalAnswer:{const:true} personalVotesPreserveTieAndAbstention:{const:true} personalWins:{const:true} survivesReopen:{const:true} toolVerifyUsesOutcomeEpisodes:{const:true} triageUsesEpisodes:{const:true} userIsolated:{const:true} verifyUsesEpisodes:{const:true} weakNeverExactAuthority:{const:true} writeChangesNextAnswer:{const:true}} required:["writeChangesNextAnswer" "correctionChangesNextAnswer" "survivesReopen" "contradictionAbstains" "forgetResolvesConflict" "personalWins" "userIsolated" "novelAbstains" "weakNeverExactAuthority" "triageUsesEpisodes" "verifyUsesEpisodes" "forgetRemovesAnswer" "calibratesOnWrite" "novelCrossConformalAnswer" "evaluationHoldoutExcluded" "forgetRecalibrates" "atomicImportRollback" "atomicImportCommits" "personalVotesPreserveTieAndAbstention" "holdoutSupersedesTrainingRevision" "incrementalMatchesRebuild" "manualTriageUsesRoutingEpisodes" "toolVerifyUsesOutcomeEpisodes"] type:"object"})
-- @record {"chapter":"learned-capabilities","data":{"args":{"intent":"zzqvxtp"},"expect":{"op":"eq","path":"escalate","value":true},"tool":"neyvia.efficiency.laya_route"},"key":"unknown-abstains","section":"checks"}
C neyvia.efficiency.laya_route unknown-abstains:neyvia.efficiency.laya_route(intent:"zzqvxtp") .escalate == true
-- @record {"chapter":"learned-capabilities","data":{"args":{"receipt":{}},"expect":{"op":"eq","path":"reason","value":"missing-independent-receipt-proof"},"tool":"neyvia.efficiency.laya_outcome"},"key":"no-evidence-abstains","section":"checks"}
C neyvia.efficiency.laya_outcome no-evidence-abstains:neyvia.efficiency.laya_outcome(receipt:{}) .reason == "missing-independent-receipt-proof"
-- @record {"chapter":"learned-capabilities","data":{"args":{},"expect":{"op":"eq","path":"gate","value":0.95},"tool":"neyvia.efficiency.laya_training"},"key":"gate-is-frozen","section":"checks"}
C neyvia.efficiency.laya_training gate-is-frozen:neyvia.efficiency.laya_training() .gate == 0.95
-- @record {"chapter":"learned-capabilities","data":{"args":{},"expect":{"op":"eq","path":"baseWeightsChanged","value":false},"tool":"neyvia.efficiency.laya_training"},"key":"encoder-unchanged","section":"checks"}
C neyvia.efficiency.laya_training encoder-unchanged:neyvia.efficiency.laya_training() .baseWeightsChanged == false
-- @record {"chapter":"learned-capabilities","data":{"args":{"part":"shutdown"},"expect":{"op":"eq","path":"staysStoppedAfterTimeout","value":true},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"shutdown-during-timeout","section":"checks"}
C neyvia.efficiency.laya_selfcheck shutdown-during-timeout:neyvia.efficiency.laya_selfcheck(part:"shutdown") .staysStoppedAfterTimeout == true
-- @record {"chapter":"learned-capabilities","data":{"args":{"part":"shutdown"},"expect":{"op":"eq","path":"staysStoppedAfterReady","value":true},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"shutdown-during-ready","section":"checks"}
C neyvia.efficiency.laya_selfcheck shutdown-during-ready:neyvia.efficiency.laya_selfcheck(part:"shutdown") .staysStoppedAfterReady == true
-- @record {"chapter":"learned-capabilities","data":{"args":{"part":"instant"},"expect":{"op":"schema","path":"","schema":{"properties":{"atomicImportCommits":{"const":true},"atomicImportRollback":{"const":true},"calibratesOnWrite":{"const":true},"contradictionAbstains":{"const":true},"correctionChangesNextAnswer":{"const":true},"evaluationHoldoutExcluded":{"const":true},"forgetRecalibrates":{"const":true},"forgetRemovesAnswer":{"const":true},"forgetResolvesConflict":{"const":true},"holdoutSupersedesTrainingRevision":{"const":true},"incrementalMatchesRebuild":{"const":true},"manualTriageUsesRoutingEpisodes":{"const":true},"novelAbstains":{"const":true},"novelCrossConformalAnswer":{"const":true},"personalVotesPreserveTieAndAbstention":{"const":true},"personalWins":{"const":true},"survivesReopen":{"const":true},"toolVerifyUsesOutcomeEpisodes":{"const":true},"triageUsesEpisodes":{"const":true},"userIsolated":{"const":true},"verifyUsesEpisodes":{"const":true},"weakNeverExactAuthority":{"const":true},"writeChangesNextAnswer":{"const":true}},"required":["writeChangesNextAnswer","correctionChangesNextAnswer","survivesReopen","contradictionAbstains","forgetResolvesConflict","personalWins","userIsolated","novelAbstains","weakNeverExactAuthority","triageUsesEpisodes","verifyUsesEpisodes","forgetRemovesAnswer","calibratesOnWrite","novelCrossConformalAnswer","evaluationHoldoutExcluded","forgetRecalibrates","atomicImportRollback","atomicImportCommits","personalVotesPreserveTieAndAbstention","holdoutSupersedesTrainingRevision","incrementalMatchesRebuild","manualTriageUsesRoutingEpisodes","toolVerifyUsesOutcomeEpisodes"],"type":"object"}},"tool":"neyvia.efficiency.laya_selfcheck"},"key":"instant-effects","section":"checks"}
C neyvia.efficiency.laya_selfcheck instant-effects:matches(neyvia.efficiency.laya_selfcheck(part:"instant") {properties:{atomicImportCommits:{const:true} atomicImportRollback:{const:true} calibratesOnWrite:{const:true} contradictionAbstains:{const:true} correctionChangesNextAnswer:{const:true} evaluationHoldoutExcluded:{const:true} forgetRecalibrates:{const:true} forgetRemovesAnswer:{const:true} forgetResolvesConflict:{const:true} holdoutSupersedesTrainingRevision:{const:true} incrementalMatchesRebuild:{const:true} manualTriageUsesRoutingEpisodes:{const:true} novelAbstains:{const:true} novelCrossConformalAnswer:{const:true} personalVotesPreserveTieAndAbstention:{const:true} personalWins:{const:true} survivesReopen:{const:true} toolVerifyUsesOutcomeEpisodes:{const:true} triageUsesEpisodes:{const:true} userIsolated:{const:true} verifyUsesEpisodes:{const:true} weakNeverExactAuthority:{const:true} writeChangesNextAnswer:{const:true}} required:["writeChangesNextAnswer" "correctionChangesNextAnswer" "survivesReopen" "contradictionAbstains" "forgetResolvesConflict" "personalWins" "userIsolated" "novelAbstains" "weakNeverExactAuthority" "triageUsesEpisodes" "verifyUsesEpisodes" "forgetRemovesAnswer" "calibratesOnWrite" "novelCrossConformalAnswer" "evaluationHoldoutExcluded" "forgetRecalibrates" "atomicImportRollback" "atomicImportCommits" "personalVotesPreserveTieAndAbstention" "holdoutSupersedesTrainingRevision" "incrementalMatchesRebuild" "manualTriageUsesRoutingEpisodes" "toolVerifyUsesOutcomeEpisodes"] type:"object"})
-- @record {"chapter":"learned-capabilities","data":{"args":{"domain":"cl-instant","input":"next answer"},"expect":{"op":"eq","path":"answer","value":false},"tool":"neyvia.efficiency.laya_query"},"key":"instant-first","section":"checks"}
C neyvia.efficiency.laya_query instant-first:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .answer == false
-- @record {"chapter":"learned-capabilities","data":{"args":{"domain":"cl-instant","input":"next answer"},"expect":{"op":"eq","path":"answer","value":true},"tool":"neyvia.efficiency.laya_query"},"key":"instant-second","section":"checks"}
C neyvia.efficiency.laya_query instant-second:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .answer == true
-- @record {"chapter":"learned-capabilities","data":{"args":{"domain":"cl-instant","input":"next answer"},"expect":{"op":"eq","path":"escalate","value":true},"tool":"neyvia.efficiency.laya_query"},"key":"instant-forgotten","section":"checks"}
C neyvia.efficiency.laya_query instant-forgotten:neyvia.efficiency.laya_query(domain:"cl-instant" input:"next answer") .escalate == true
-- @record {"chapter":"learned-capabilities","data":{"goal":"Verify unknown routing, missing receipt proof and the frozen confidence gate through real native tools","inputs":{"$cl_type":"t19"},"steps":[{"action":"laya_route","args":{"intent":"zzqvxtp"},"check":"unknown-abstains","save":"observed0"},{"action":"laya_outcome","args":{"receipt":{}},"check":"no-evidence-abstains","save":"observed1"},{"action":"laya_training","args":{},"check":"gate-is-frozen","save":"observed2"},{"action":"laya_training","args":{},"check":"encoder-unchanged","save":"observed3"},{"action":"laya_selfcheck","args":{"part":"shutdown"},"check":"shutdown-during-timeout","save":"observed4"},{"action":"laya_selfcheck","args":{"part":"shutdown"},"check":"shutdown-during-ready","save":"observed5"}]},"key":"prove-learned-abstention","section":"procedures"}
P prove-learned-abstention():observed0=neyvia.efficiency.laya_route(intent:"zzqvxtp") C unknown-abstains; observed1=neyvia.efficiency.laya_outcome(receipt:{}) C no-evidence-abstains; observed2=neyvia.efficiency.laya_training() C gate-is-frozen; observed3=neyvia.efficiency.laya_training() C encoder-unchanged; observed4=neyvia.efficiency.laya_selfcheck(part:"shutdown") C shutdown-during-timeout; observed5=neyvia.efficiency.laya_selfcheck(part:"shutdown") C shutdown-during-ready -- Verify unknown routing, missing receipt proof and the frozen confidence gate through real native tools
V P prove-learned-abstention -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"learned-capabilities","data":{"goal":"Write a real label and correction; next answer changes durably, conflicts abstain and forgetting removes its effect","inputs":{"$cl_type":"t20"},"steps":[{"action":"laya_learn","args":{"domain":"cl-instant","input":"next answer","label":false,"source":"cl-write-effect"},"check":"instant-first","save":"first"},{"action":"laya_learn","args":{"domain":"cl-instant","input":"next answer","label":true,"source":"cl-write-effect"},"check":"instant-second","save":"second"},{"action":"laya_forget","args":{"source":"cl-write-effect"},"check":"instant-forgotten","save":"forgotten"},{"action":"laya_selfcheck","args":{"part":"instant"},"check":"instant-effects","save":"instant"}]},"key":"prove-instant-learning","section":"procedures"}
P prove-instant-learning():first=neyvia.efficiency.laya_learn(domain:"cl-instant" input:"next answer" label:false source:"cl-write-effect") C instant-first; second=neyvia.efficiency.laya_learn(domain:"cl-instant" input:"next answer" label:true source:"cl-write-effect") C instant-second; forgotten=neyvia.efficiency.laya_forget(source:"cl-write-effect") C instant-forgotten; instant=neyvia.efficiency.laya_selfcheck(part:"instant") C instant-effects -- Write a real label and correction; next answer changes durably, conflicts abstain and forgetting removes its effect
V P prove-instant-learning -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"learned-capabilities","data":{"failure":"Similarity, a draft, static lint or caller-supplied render measurements are mistaken for quality proof","recovery":"Keep escalation; require fresh rendering and independent calibrated evidence"},"key":"0","section":"pitfalls"}
X Similarity, a draft, static lint or caller-supplied render measurements are mistaken for quality proof -> Keep escalation; require fresh rendering and independent calibrated evidence
-- @record {"chapter":"learned-capabilities","data":"Frozen LAYA weights are unchanged. Sparse retrieval and original grammar composition are explicitly identified; uncalibrated areas abstain.","key":"0","section":"frontier"}
F Frozen LAYA weights are unchanged. Sparse retrieval and original grammar composition are explicitly identified; uncalibrated areas abstain.
-- @record {"chapter":"learned-capabilities","data":"Personal identity votes remain context, never quality labels. Rendered component novelty has not been rated by Paul.","key":"1","section":"frontier"}
F Personal identity votes remain context, never quality labels. Rendered component novelty has not been rated by Paul.
-- @record {"chapter":"learned-capabilities","data":"These same native tools are available to agents, App Factory and the taste loop. They never publish or execute generated code.","key":"0","section":"guidance"}
M efficiency "These same native tools are available to agents, App Factory and the taste loop. They never publish or execute generated code." src:"authored manual" state:verified
-- @record {"chapter":"learned-capabilities","data":"LAYA Instant: efficiency.laya_learn writes domain/input/label/source with layer personal and user paul for taste; efficiency.laya_query reads it, efficiency.laya_forget removes a source. Service callers use triage(task=manual-routing) with manual ID options, or verify(question=tool_outcome) with a toolId/result receipt and success/failure candidate, under the same selected workspace root. Explicit replay is not a statistical guarantee. Novel inputs use store leave-one-out scores, an out-of-fold agreement filter and a singleton cross-conformal set at nominal 0.95. Scores update on each write. This is empirical admission, not a selective accuracy guarantee; independently held-out families must measure at least 0.95 selective accuracy. Evaluation holdouts never enter neighbours, calibration or exact replay. Duplicate vectors do not multiply support. Image cold encoding is measured separately from warm text writes. Never convert author guesses into quality labels.","key":"1","section":"guidance"}
M efficiency "LAYA Instant: efficiency.laya_learn writes domain/input/label/source with layer personal and user paul for taste; efficiency.laya_query reads it, efficiency.laya_forget removes a source. Service callers use triage(task=manual-routing) with manual ID options, or verify(question=tool_outcome) with a toolId/result receipt and success/failure candidate, under the same selected workspace root. Explicit replay is not a statistical guarantee. Novel inputs use store leave-one-out scores, an out-of-fold agreement filter and a singleton cross-conformal set at nominal 0.95. Scores update on each write. This is empirical admission, not a selective accuracy guarantee; independently held-out families must measure at least 0.95 selective accuracy. Evaluation holdouts never enter neighbours, calibration or exact replay. Duplicate vectors do not multiply support. Image cold encoding is measured separately from warm text writes. Never convert author guesses into quality labels." src:"authored manual" state:verified
L efficiency.workflow v1 -- Executable efficiency method: chronological mechanism and measured quality
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"efficiency","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"inputs":{"$cl_type":"t21"},"shape":{"$cl_type":"t22"},"tool":"neyvia.workflow.check"},"key":"adherence","section":"state"}
S efficiency.adherence:json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"=neyvia.workflow.check(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens)
-- @record {"chapter":"workflow","data":{"effect":"Validate ordered workflow evidence","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t22"},"reversible":true,"schema":"neyvia.workflow.check","tool":"neyvia.workflow.check"},"key":"check","section":"actions"}
A neyvia.workflow.check(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" -- Validate ordered workflow evidence
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"effect":"Persist a validated workflow receipt under the selected task root","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t22"},"reversible":false,"schema":"neyvia.workflow.record","tool":"neyvia.workflow.record"},"key":"record","section":"actions"}
A neyvia.workflow.record(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" ! -- Persist a validated workflow receipt under the selected task root
C neyvia.workflow.record adhered:neyvia.workflow.check(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"efficiency","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"expect":{"op":"eq","path":"accepted","value":true},"tool":"neyvia.workflow.check"},"key":"adhered","section":"checks"}
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"goal":"Verify defining workflow mechanism against host evidence and persist the acceptance receipt","inputs":{"$cl_type":"t21"},"steps":[{"action":"check","args":{"evidence":{"$input":"evidence"},"manual":"efficiency","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"verified"},{"action":"record","args":{"evidence":{"$input":"evidence"},"manual":"efficiency","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"recorded"}]},"key":"verify-and-record","section":"procedures"}
P verify-and-record(report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..):verified=neyvia.workflow.check(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered; recorded=neyvia.workflow.record(evidence:evidence manual:"efficiency" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered -- Verify defining workflow mechanism against host evidence and persist the acceptance receipt
V P verify-and-record -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"workflow","data":{"constraints":"Use an independent frozen host quality judge; self-reported quality is not evidence.","options":["accept","revise"],"question":"Does the outcome satisfy the actual task, beyond recorded adherence?"},"key":"quality","section":"judge"}
J quality accept|revise:"Does the outcome satisfy the actual task, beyond recorded adherence?" -- Use an independent frozen host quality judge; self-reported quality is not evidence.
V J quality -> human:operator why:"explicit choice required"
-- @record {"chapter":"workflow","data":{"failure":"A model writes its own successful receipt, outcome score or token count","recovery":"The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail"},"key":"0","section":"pitfalls"}
X A model writes its own successful receipt, outcome score or token count -> The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail
-- @record {"chapter":"workflow","data":"Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.","key":"0","section":"frontier"}
F Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.
-- @record {"chapter":"workflow","data":"Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.","key":"1","section":"frontier"}
F Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.
-- @record {"chapter":"workflow","data":"Available paths are script, memory, small-model, big-model in that order. The production T14 engine also validates System1/cache results between these paths.","key":"0","section":"guidance"}
M efficiency "Available paths are script, memory, small-model, big-model in that order. The production T14 engine also validates System1/cache results between these paths." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Use the cheapest available path. Escalation requires host evidence of failure for every cheaper available path, never mere model preference.","key":"1","section":"guidance"}
M efficiency "Use the cheapest available path. Escalation requires host evidence of failure for every cheaper available path, never mere model preference." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Measure actual usage tokens and elapsed latency from receipts, then link the measurement to the research ledger. Compare cost at equal outcome quality.","key":"2","section":"guidance"}
M efficiency "Measure actual usage tokens and elapsed latency from receipts, then link the measurement to the research ledger. Compare cost at equal outcome quality." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Report shape: {events:[{stage,data}],result:object}. Required chronological stages: paths, attempt, measure, log","key":"3","section":"guidance"}
M efficiency "Report shape: {events:[{stage,data}],result:object}. Required chronological stages: paths, attempt, measure, log" src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"paths{available:[script,memory,small-model,big-model]}; attempt{path,reason,receipt}; measure{receipt}; log{receipt}. Attempt evidence has path,cheaperFailures; measure evidence has path,tokens,latencyMs; ledger evidence has kind=research-ledger,measurement=measure receipt ID.","key":"4","section":"guidance"}
M efficiency "paths{available:[script,memory,small-model,big-model]}; attempt{path,reason,receipt}; measure{receipt}; log{receipt}. Attempt evidence has path,cheaperFailures; measure evidence has path,tokens,latencyMs; ledger evidence has kind=research-ledger,measurement=measure receipt ID." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified.","key":"5","section":"guidance"}
M efficiency "Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below.","key":"6","section":"guidance"}
M efficiency "Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"paths\",\"data\":{\"available\":[\"script\",\"memory\",\"small-model\",\"big-model\"]}},{\"stage\":\"attempt\",\"data\":{\"path\":\"script\",\"reason\":\"deterministic extraction suffices\",\"receipt\":\"attempt\"}},{\"stage\":\"measure\",\"data\":{\"receipt\":\"measurement\"}},{\"stage\":\"log\",\"data\":{\"receipt\":\"log\"}}],\"result\":{\"decision\":\"task-specific actual answer\"}}","key":"7","section":"guidance"}
M efficiency "Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"paths\",\"data\":{\"available\":[\"script\",\"memory\",\"small-model\",\"big-model\"]}},{\"stage\":\"attempt\",\"data\":{\"path\":\"script\",\"reason\":\"deterministic extraction suffices\",\"receipt\":\"attempt\"}},{\"stage\":\"measure\",\"data\":{\"receipt\":\"measurement\"}},{\"stage\":\"log\",\"data\":{\"receipt\":\"log\"}}],\"result\":{\"decision\":\"task-specific actual answer\"}}" src:"authored manual" state:verified
-- @proof {"checkedAt":["grant_agent.proofs_context_config_journey.self_check","grant_agent.proofs_context_config_journey._journey","grant_agent.neyvia_agent.build_neyvia_agent","grant_agent.compaction_policy.resolve_policy","grant_agent.session_compaction.SessionCompactor.compact","grant_agent.model_usage.stream_sdk_usage"],"claim":"A selected route's context policy reaches the Native agent SDK output reservation, compaction trigger and observed usage event; an authored request beyond the remaining context receives the bounded compaction refusal, and an invalid mode is rejected during agent construction before that attempt can call the provider.","id":"context.config.runtime-budget","impact":["Native model output reservation","route context and input budget","visible context usage and oversized-request refusal","invalid route policy admission"],"phase":"post"}
L efficiency.filmbugs v1 -- Launch film behavior contracts
-- @record {"chapter":"filmbugs","section":"guidance","key":"0","data":"LAYA strip retains answered/asked counts and service tone, and shows estimated token savings only when positive. Zero or unavailable savings do not appear as a savings claim."}
M efficiency "LAYA strip retains answered/asked counts and service tone, and shows estimated token savings only when positive. Zero or unavailable savings do not appear as a savings claim." src:"authored manual" state:verified
