CL 1
L evolve v1 -- Plan-25 evolving engine: one spec, a population, real judges, a growing move library and an adversary; no training
A evolve.run(task:str, budget:object) -> summary -- Library, Luna and big-model mutations; episode pre-filter; layered judges; MAP-Elites archive and Pareto set; a receipt per evaluation
A evolve.adversary(task:str) -> round -- Exploit rewrites hunt for score-high/fail-real candidates; each exploit becomes a predicate and a promoted cheap check
A evolve.verify(task:str, winner:object) -> proof -- Final paired timing, cold timing, the target's CL contracts and one model look; the patch is a proposal for the owner
P speed-up-gate(budget): evolve.run("gate-plan", budget); evolve.run("cl-compile", budget); evolve.verify("gate-plan", winner); evolve.verify("cl-compile", winner)
P control(budget): evolve.run("cl-compile", budget) -- same task, empty learned library and empty episodes: what the first task taught
-- Spec once (plan 25 step 1). Authored by the lead model from Paul's request "make gate.py faster"; Paul confirms. A goal that cannot be measured cannot evolve.
-- @spec {"task":"gate-plan","kind":"python-speed","target":"track/p22 scripts/gate.py -> grant_agent.contract_gate (+contract_coverage, durability)","objective":{"metric":"wallSeconds","direction":"min","cases":["release-HEAD~5 (warm module cache)","cold-commit-HEAD~1 (cold module cache)"],"secondary":["footprintLines"]},"constraints":["byte-identical normalised gate receipt on every train, held-out and perturbation check","p22 fast-contracts witnessed by the gate's own worker","never edit track/p22; the result is a patch"],"budget":{"generations":4,"perGeneration":6,"lunaPerGeneration":2,"lunaCalls":40,"bigModelCalls":10,"maxSeconds":14400},"confirmedBy":null}
-- @spec {"task":"gate-plan-latest","kind":"python-speed","target":"track/p22 8af3037d8 scripts/gate.py -> grant_agent.contract_gate (+coverage, measurements, diff, durability)","objective":{"metric":"wallSeconds","direction":"min","cases":["commit-HEAD~5 (warm module cache, skip-build)","cold-commit-HEAD~3 (cold module cache)"],"secondary":["footprintLines"]},"constraints":["byte-identical normalised gate receipt on every train, held-out and perturbation check","p22 fast-contracts witnessed by the gate's own worker","never edit track/p22; the result is a patch"],"budget":{"generations":3,"perGeneration":6,"lunaPerGeneration":2,"lunaCalls":40,"bigModelCalls":10,"maxSeconds":10800},"confirmedBy":null}
-- @spec {"task":"cl-compile","kind":"python-speed","target":"track/p22 scripts/cl_compile_manuals.py --check (the gate's critical-path step)","objective":{"metric":"wallSeconds","direction":"min","cases":["check"],"secondary":["footprintLines"]},"constraints":["byte-identical stdout, receipt and raised error on the check and every perturbation","p22 fast-contracts witnessed by the gate's own worker","never edit track/p22; the result is a patch"],"budget":{"generations":4,"perGeneration":6,"lunaPerGeneration":2,"lunaCalls":40,"bigModelCalls":10,"maxSeconds":14400},"confirmedBy":null}
-- Judge vocabulary (scene_core predicates over one node per check). Exploits found by the adversary are appended below as exploit-* predicates.
-- @predicate {"id":"output-differs","condition":{"all":[{"field":"kind","op":"eq","value":"check"},{"field":"measurements.identical","op":"eq","value":false}]},"severity":"error","evidence":["measurements.identical","attributes.check"],"fix":{"action":"evolve.reject","arguments":{}},"means":"A must-hold output changed"}
-- @predicate {"id":"run-failed","condition":{"all":[{"field":"kind","op":"eq","value":"check"},{"field":"measurements.status","op":"matches","value":"^(crash|timeout|missing)$"}]},"severity":"error","evidence":["measurements.status"],"fix":{"action":"evolve.reject","arguments":{}},"means":"The measured process crashed or timed out"}
-- @predicate {"id":"nondeterministic","condition":{"all":[{"field":"kind","op":"eq","value":"check"},{"field":"measurements.nondeterministic","op":"eq","value":true}]},"severity":"error","evidence":["measurements.nondeterministic"],"fix":{"action":"evolve.reject","arguments":{}},"means":"Two identical runs disagreed"}
-- @predicate {"id":"exploit-edit-import","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"edit-import"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found by adversary candidate ad9794d2c393 (exploit:stale-cache): source edits keep the old import edges"}
-- @predicate {"id":"exploit-rename","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"rename"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found by adversary candidate 416bbf342606 (exploit:drop-renames): moved sources lose their owner path"}
-- @predicate {"id":"exploit-release-HEAD~12","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"release-HEAD~12"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found by adversary candidate d2edb8163533 (exploit:luna-2abe44): Caching the tracked source-file list by HEAD makes repeated calls faster, but misses untracked files added after the cache is built; those files' import edges are then omitted until HEAD changes."}
-- @predicate {"id":"exploit-cold-release-HEAD~12","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"cold-release-HEAD~12"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found after the search by the stronger final check: step 6cf615dfb20d (fewer-allocations) passed every warm check but changed cold-release-HEAD~12"}
-- @predicate {"id":"exploit-edit-source","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"edit-source"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found by adversary candidate 396ea611de00 (exploit:disk-memo): repository edits after the first run are ignored"}
-- @predicate {"id":"exploit-invalid-schema","severity":"error","evidence":["measurements.identical","measurements.status"],"condition":{"all":[{"field":"attributes.check","op":"eq","value":"invalid-schema"},{"any":[{"field":"measurements.identical","op":"eq","value":false},{"field":"measurements.nondeterministic","op":"eq","value":true}]}]},"fix":{"action":"evolve.reject","arguments":{}},"means":"Found by adversary candidate ddd6ead297b6 (exploit:skip-validation): invalid schemas compile"}
C evolve.verify identical: proof.outputsIdentical == true -- block every winner gives byte-identical outputs on all train, held-out and perturbation checks
C evolve.verify contracts: proof.contractsPass == true -- block the gate's own fast-contracts are witnessed with each final patch
C evolve.verify gate-faster: proof.gatePlanSpeedup >= 1.05 -- block measured paired speed-up of the gate's own process
C evolve.verify compile-faster: proof.compileSpeedup >= 1.05 -- block measured paired speed-up of the gate's CL-compile step
C evolve.verify big-model-cap: proof.bigModelCalls <= 10 -- block at most ten big-model idea calls per run
C evolve.verify library-share: proof.libraryShareSecond >= proof.libraryShareFirst -- block the share of wins from LAYA's own library does not fall on the second task
C evolve.verify second-faster: proof.secondTaskFaster == true -- block the second similar task (the same gate on the newer p22 commit) reaches 90% of the common speed-up in fewer evaluations with the earlier tasks episodes and moves than an engine with an empty store
C evolve.verify adversary: proof.exploitRateFalls == true -- block the adversary's exploit rate falls after the judge hardens
C evolve.verify stored: proof.winEpisodes >= 1 -- block winning changes are written as episodes with their context
C evolve.verify training: proof.training == false -- block no weights are fitted; learning is episode writes
C evolve.final applies: final.appliesToTarget == true -- block the gate, compile and combined patches apply to the current release candidate (track/int-final)
C evolve.final identical: final.outputsIdentical == true -- block on the release candidate every gate and compile check gives byte-identical outputs with the patches
C evolve.final gate-faster: final.gateSpeedup >= 1.05 -- block paired speed-up of the gate's own process on the release candidate
C evolve.final compile-faster: final.compileSpeedup >= 1.05 -- block paired speed-up of the gate's CL-compile step on the release candidate (bounded memo)
C evolve.final memo-bounded: final.memoEntries <= final.memoBound -- block one real compile keeps fewer memo entries than the bound, so the bound never evicts within a run
C evolve.final contracts: final.contractsSame == true -- block the gate's own contract areas witness the same contracts with and without the patches
J confirm-spec confirmed|revise: "Does this spec (objective, must-hold constraints, budget) say what you meant by make gate.py faster?"
F Timings are wall clock on a shared machine with other agents running; every comparison is interleaved A/B and the median of pairs.
F The gate-plan task stubs subprocess steps (workers, compile, build, render, LAYA); their own time is measured as separate tasks (cl-compile) or not evolved here.
