CL 1
L evolve-moves v1 -- LAYA's library of known optimisation moves for the plan-25 evolving engine; data, never executed as text
A evolve.move.apply(move:str, file:str, function:str) -> candidate -- Deterministic rewrite or a Luna instantiation of the move's CL text on one hot function
A evolve.move.learn(winner:object) -> move -- A winning model idea generalised into a reusable move plus a win episode
A evolve.move.retire(move:str, context:object) -> episode -- Three or more tries without a win in one context (task, file) retire the move there only; it stays available in every other context
P apply(move, file, function): evolve.move.apply(move, file, function)
P learn(winner): evolve.move.learn(winner)
-- Retirement is context-scoped: scope = the context keys a retirement is bound to; an episode with no file (a whole-task finding) counts for every file of its task; an unknown task counts nowhere.
-- @retire {"scope":["task","file"],"tries":3,"maxWins":0}
-- skip-repeated-validation assumes a PURE validator: outcome depends only on the JSON value of its arguments, no side effects, success returns None and failure raises; only successes are remembered, in a bounded LRU (4096 SHA-256 digests per process).
-- Seed moves. transform = a rewrite in grant_agent.evolve_moves, or "luna" (the CL text is instantiated by Luna on a matching hot function).
-- @move {"id":"skip-repeated-validation","family":"caching","transform":"skip-repeated-validation","applies_when":"A pure validator is called for its exception on identical JSON inputs many times in one process","match":"\\.(check|validate|verify)\\w*\\(","cl":"P skip-repeated-validation(call): key = canonical(args); if key in proven: skip; call(args); proven.add(key)"}
-- @move {"id":"skip-unchanged-write","family":"io","transform":"skip-unchanged-write","applies_when":"A durable JSON write (fsync + replace) rewrites a file whose content is already identical","match":"atomic_write_json\\(","cl":"P skip-unchanged-write(path, payload): if read_json(path) == payload: return path; atomic_write_json(path, payload)"}
-- @move {"id":"statement-walk","family":"algorithmic","transform":"statement-walk","applies_when":"A full ast.walk only looks for statement node types such as imports; statements never occur inside expressions","match":"ast\\.walk\\(","cl":"P statement-walk(tree): visit body, orelse, finalbody, handlers and cases lists only"}
-- @move {"id":"hoist-regex","family":"constant","transform":"hoist-regex","applies_when":"A literal regular expression is compiled through the re module cache inside a hot function","match":"re\\.(findall|search|match|sub|finditer)\\(","cl":"P hoist-regex(pattern): PATTERN = re.compile(pattern) at module level; PATTERN.findall(text)"}
-- @move {"id":"call-once","family":"redundancy","transform":"call-once","applies_when":"A zero-argument function that scans the file system is called more than once in one process","match":"def \\w+\\(\\):","cl":"P call-once(function): first result is kept for the process; callers receive a deep copy"}
-- @move {"id":"parallel-map","family":"parallel","transform":"luna","applies_when":"A loop applies independent CPU- or IO-bound work (parse, read, hash) to many files; results are combined in input order","match":"for \\w+ in [^\\n]+:[\\s\\S]{0,800}(read_text|read_bytes|ast\\.parse|sha256|json\\.loads)","cl":"P parallel-map(items, work): results = pool.map(work, items) in input order; combine exactly as the loop did"}
-- @move {"id":"dedupe-before-expensive","family":"redundancy","transform":"luna","applies_when":"An expensive pure check runs before a lookup that would make it unnecessary for an already-seen input","match":"if \\w+ in self\\.\\w+:","cl":"P dedupe-before-expensive(input): if canonical(input) already accepted: return cached; else check then record"}
-- @move {"id":"index-once","family":"algorithmic","transform":"luna","applies_when":"Repeated linear scans or per-item set unions over the same collection inside a loop","match":"set\\(\\)\\.union\\(\\*|for \\w+ in [^\\n]+:\\n\\s+for \\w+ in","cl":"P index-once(collection): build a dict index once; look items up in the loop"}
-- @move {"id":"fewer-allocations","family":"allocation","transform":"luna","applies_when":"Temporary lists, sets or Path objects are built per item in a hot loop only to be consumed once","match":"Path\\(|\\.relative_to\\(|sorted\\(","cl":"P fewer-allocations(loop): reuse strings and generators; avoid Path round trips inside the loop"}
C evolve.moves seeded: moves.seeded >= 9 -- block the library starts with the known moves
C evolve.moves data: moves.executedAsText == false -- block a move's CL text is data; only named rewrites run
C evolve.moves scoped-retirement: moves.retiredButAvailableElsewhere >= 1 -- block replaying the real episode store, a move retired in one context stays available in another
C evolve.moves memo-bounded: moves.memoBounded == true -- block the skip-repeated-validation helper keeps at most its bound in a long-lived process and still raises on invalid input after eviction
C evolve.moves memo-pure-only: moves.memoKeepsOnlySuccess == true -- block a validator that raises or returns a value is never remembered (purity assumption made explicit)
