CL 1
L game-dev v1 -- Authored executable manual
-- @manual {"chapters":{"bridges":{"title":"Operate native game editors and Babylon through exact sessions and checked receipts"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"}},"clVersion":"1.1","id":"game-dev","kind":"environment","proofs":{"area":"proofs-e-models, surface-games-extra","manifests":["config/proofs/proofs-e-models.json","config/proofs/games-journey.json","config/proofs/surface-games-extra.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.gamedev.action":"t1","neyvia.gamedev.asset_validate":"t2","neyvia.gamedev.project_status":"t3","neyvia.gamedev.receipt":"t4","neyvia.gamedev.receipts":"t5","neyvia.gamedev.sessions":"t6","neyvia.gamedev.setup":"t3","neyvia.gamedev.state":"t7","neyvia.gamedev.status":"t7","proofs-e-models.status":"t7"},"tool_metadata":{"neyvia.gamedev.action":{"mutability_class":"artifact_write"},"neyvia.gamedev.asset_validate":{"mutability_class":"none"},"neyvia.gamedev.project_status":{"mutability_class":"read"},"neyvia.gamedev.receipt":{"mutability_class":"none"},"neyvia.gamedev.receipts":{"mutability_class":"none"},"neyvia.gamedev.sessions":{"mutability_class":"none"},"neyvia.gamedev.setup":{"mutability_class":"artifact_write"},"neyvia.gamedev.state":{"mutability_class":"read"},"neyvia.gamedev.status":{"mutability_class":"none"},"neyvia.verify.status":{}}}
-- @proof {"checkedAt":["grant_agent.neyvia_gamedev.handle_command","grant_agent.neyvia_gamedev.validate_asset","grant_agent.proofs_games_journey.export_validation_journey","scripts/gamedev/scene-runtime.js:NeyviaScene.dispatch","scripts/gamedev/scene-runtime.js:NeyviaScene.persist"],"claim":"A local Babylon NullEngine journey creates and edits real mesh geometry, preserves the edit across scene save/reopen, refuses an unsupported primitive without changing the saved scene, exports a GLB that passes Khronos validation, diagnoses a broken glTF reference, and refuses paths outside the selected workspace.","id":"gamedev.export-validation-journey","impact":["Game Dev project export validation and engine import boundary"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:keepSelection -> checkedProofsEModel"],"claim":"Native selection never changes implicitly; browser reload affinity follows only one same-project/context replacement","id":"gamedev.keepSelection","impact":["gamedev frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:tabForStage -> checkedProofsEModel"],"claim":"Explicit known tabs win, then launcher app aliases, then embedded Browser 3D","id":"gamedev.tabForStage","impact":["gamedev frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:visibleFields -> checkedProofsEModel"],"claim":"Conditional controls show exactly fields whose predicates hold","id":"gamedev.visibleFields","impact":["gamedev frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:initialValues -> checkedProofsEModel"],"claim":"Form defaults resolve duplicate keys according to their condition","id":"gamedev.initialValues","impact":["gamedev frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:buildArgs -> checkedProofsEModel"],"claim":"Visible fields become exact bridge args; vectors/numbers are finite, JSON text must parse as an object and wildcard fields are flattened","id":"gamedev.buildArgs","impact":["gamedev frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:actionFields -> checkedProofsEModel"],"claim":"Godot edit/interact and Unity test forms retain their typed bridge fields/defaults; other actions return valid field arrays","id":"gamedev.actionFields","impact":["Game Dev typed action forms and engine bridge args"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxGameDevModel.js:sessionLabel","web/src/neyvia/next/nxGameDevModel.js:keepSelection -> checkedProofsEModel","scripts/uifix2_contracts.py:c4_gamedev_names_and_selection","scripts/p22_release_models.mjs"],"claim":"Sessions are named in words (Browser 3D editor, Editor), never with raw environment ids or a literal null; a reloaded browser-webgl or browser-null scene stays selected","id":"gamedev.sessionLabel","impact":["Game Dev sessions list and session card"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"action\":{\"type\":\"string\"},\"args\":{\"type\":\"object\"},\"requestId\":{\"type\":\"string\"}},\"required\":[\"sessionId\",\"action\"],\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}},\"action\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"engine\":{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]},\"projectPath\":{\"type\":\"string\"}},\"required\":[\"engine\",\"projectPath\"],\"allOf\":[{\"properties\":{\"projectPath\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"requestId\":{\"type\":\"string\"}},\"required\":[\"requestId\"],\"allOf\":[{\"properties\":{\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{sessionId?:str limit?:1..200 ..}
T t6{engine?:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath?:str context?:json:"{\"type\":\"string\",\"enum\":[\"Edit\",\"Play\",\"Client\",\"Server\"]}" ..}
T t7{..}
T t8{}
T t9{engines:json:"{\"type\":\"array\"}" sessions:json:"{\"type\":\"array\"}" ..}
T t10 json:"{\"type\":\"object\"}"
T t11{requestId:str}
T t12{path:str}
T t13{engine:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath:str}
T t14{sessionId:str action:str args:json:"{\"type\":\"object\"}" requestId:str}
T t15{ok:bool ..}
T t16 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L game-dev.bridges v1 -- Operate native game editors and Babylon through exact sessions and checked receipts
-- @record {"chapter":"bridges","data":{"args":{},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.gamedev.status"},"key":"live","section":"state"}
S game-dev.live:{engines:json:"{\"type\":\"array\"}" sessions:json:"{\"type\":\"array\"}" ..}=neyvia.gamedev.status()
-- @record {"chapter":"bridges","data":{"effect":"Observe installation separately from heartbeat connection","pre":"Selected backend root and scoped workspace; no editor starts","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.status","tool":"neyvia.gamedev.status"},"key":"status","section":"actions"}
A neyvia.gamedev.status() -> json:"{\"type\":\"object\"}" -- Observe installation separately from heartbeat connection
F verify-status "No authored observer check is bound to neyvia.gamedev.status" -> ask operator blocks:neyvia.gamedev.status
-- @record {"chapter":"bridges","data":{"effect":"Observe exact engine/project/context/session/capabilities; never select by engine alone","pre":"Selected backend root","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.sessions","tool":"neyvia.gamedev.sessions"},"key":"sessions","section":"actions"}
A neyvia.gamedev.sessions(engine?:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath?:str context?:json:"{\"type\":\"string\",\"enum\":[\"Edit\",\"Play\",\"Client\",\"Server\"]}") -> json:"{\"type\":\"object\"}" -- Observe exact engine/project/context/session/capabilities; never select by engine alone
C neyvia.gamedev.sessions one-editor-session:matches(neyvia.gamedev.sessions(context:"Edit" engine:engine projectPath:projectPath) .sessions {items:{properties:{clientId:{minLength:1 type:"string"} status:{const:"connected"}} required:["sessionId" "clientId"] type:"object"} maxItems:1 minItems:1 type:"array"})
-- @record {"chapter":"bridges","data":{"effect":"Copy local bridge package and create a project-scoped token; no editor/system install","pre":"Existing project inside selected workspace; installed native editor; no conflicting bridge files","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.setup","tool":"neyvia.gamedev.setup"},"key":"setup","section":"actions"}
A neyvia.gamedev.setup(engine:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath:str) -> json:"{\"type\":\"object\"}" ! -- Copy local bridge package and create a project-scoped token; no editor/system install
C neyvia.gamedev.setup configured:neyvia.gamedev.project_status(engine:engine projectPath:projectPath) .configured == true
-- @record {"chapter":"bridges","data":{"effect":"Queue an affinity-bound native operation once; success is determined by native completion, not queue admission","pre":"Exact connected session advertises action; matching context/Studio; scoped file paths; load_asset passes validator","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.gamedev.action","tool":"neyvia.gamedev.action"},"key":"action","section":"actions"}
A neyvia.gamedev.action(sessionId:str action:str args?:json:"{\"type\":\"object\"}" requestId?:str) -> json:"{\"type\":\"object\"}" ! -- Queue an affinity-bound native operation once; success is determined by native completion, not queue admission
C neyvia.gamedev.action complete:neyvia.gamedev.receipt(requestId:requestId) .status == "succeeded"
-- @record {"chapter":"bridges","data":{"effect":"Observe queue/running/terminal result, error and elapsed time; pending is not completed","pre":"Existing requestId on the same persistent backend","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.receipt","tool":"neyvia.gamedev.receipt"},"key":"receipt","section":"actions"}
A neyvia.gamedev.receipt(requestId:str) -> json:"{\"type\":\"object\"}" -- Observe queue/running/terminal result, error and elapsed time; pending is not completed
C neyvia.gamedev.receipt complete:neyvia.gamedev.receipt(requestId:requestId) .status == "succeeded"
-- @record {"chapter":"bridges","data":{"effect":"Run official Khronos Validator; invalid exports cannot be loaded by action","pre":"Existing scoped .glb/.gltf with bounded local resources and Node available","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.asset_validate","tool":"neyvia.gamedev.asset_validate"},"key":"asset_validate","section":"actions"}
A neyvia.gamedev.asset_validate(path:str) -> json:"{\"type\":\"object\"}" ! -- Run official Khronos Validator; invalid exports cannot be loaded by action
C neyvia.gamedev.asset_validate valid-asset:neyvia.gamedev.asset_validate(path:path) .valid == true
-- @record {"chapter":"bridges","data":{"effect":"Observe durable action receipts and reported UI selection separately from native bridge observations","pre":"Read only inside the selected owner workspace","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.receipts","tool":"neyvia.gamedev.receipts"},"key":"gamedev.receipts","section":"actions"}
A neyvia.gamedev.receipts(sessionId?:str limit?:1..200) -> json:"{\"type\":\"object\"}" -- Observe durable action receipts and reported UI selection separately from native bridge observations
F verify-gamedev-receipts "No authored observer check is bound to neyvia.gamedev.receipts" -> ask operator blocks:neyvia.gamedev.receipts
-- @record {"chapter":"bridges","data":{"effect":"Observe durable action receipts and reported UI selection separately from native bridge observations","pre":"Read only inside the selected owner workspace","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.state","tool":"neyvia.gamedev.state"},"key":"gamedev.state","section":"actions"}
A neyvia.gamedev.state() -> json:"{\"type\":\"object\"}" -- Observe durable action receipts and reported UI selection separately from native bridge observations
F verify-gamedev-state "No authored observer check is bound to neyvia.gamedev.state" -> ask operator blocks:neyvia.gamedev.state
-- @record {"chapter":"bridges","data":{"effect":"Read exact bridge package hashes and configuration affinity separately from connection","pre":"Selected workspace project; capability content is never returned","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.gamedev.project_status","tool":"neyvia.gamedev.project_status"},"key":"project-status","section":"actions"}
A neyvia.gamedev.project_status(engine:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath:str) -> json:"{\"type\":\"object\"}" -- Read exact bridge package hashes and configuration affinity separately from connection
F verify-project-status "No authored observer check is bound to neyvia.gamedev.project_status" -> ask operator blocks:neyvia.gamedev.project_status
-- @record {"chapter":"bridges","data":{"args":{"requestId":{"$input":"requestId"}},"expect":{"op":"eq","path":"status","value":"succeeded"},"tool":"neyvia.gamedev.receipt"},"key":"complete","section":"checks"}
C neyvia.gamedev.receipt complete:neyvia.gamedev.receipt(requestId:requestId) .status == "succeeded"
-- @record {"chapter":"bridges","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"valid","value":true},"tool":"neyvia.gamedev.asset_validate"},"key":"valid-asset","section":"checks"}
C neyvia.gamedev.asset_validate valid-asset:neyvia.gamedev.asset_validate(path:path) .valid == true
-- @record {"chapter":"bridges","data":{"args":{"engine":{"$input":"engine"},"projectPath":{"$input":"projectPath"}},"expect":{"op":"eq","path":"configured","value":true},"tool":"neyvia.gamedev.project_status"},"key":"configured","section":"checks"}
C neyvia.gamedev.project_status configured:neyvia.gamedev.project_status(engine:engine projectPath:projectPath) .configured == true
-- @record {"chapter":"bridges","data":{"args":{"context":"Edit","engine":{"$input":"engine"},"projectPath":{"$input":"projectPath"}},"expect":{"op":"schema","path":"sessions","schema":{"items":{"properties":{"clientId":{"minLength":1,"type":"string"},"status":{"const":"connected"}},"required":["sessionId","clientId"],"type":"object"},"maxItems":1,"minItems":1,"type":"array"}},"tool":"neyvia.gamedev.sessions"},"key":"one-editor-session","section":"checks"}
C neyvia.gamedev.sessions one-editor-session:matches(neyvia.gamedev.sessions(context:"Edit" engine:engine projectPath:projectPath) .sessions {items:{properties:{clientId:{minLength:1 type:"string"} status:{const:"connected"}} required:["sessionId" "clientId"] type:"object"} maxItems:1 minItems:1 type:"array"})
-- @record {"chapter":"bridges","data":{"goal":"Find installed editors and exact connected native contexts before operating","inputs":{"$cl_type":"t8"},"steps":[{"action":"status","args":{},"save":"availability"},{"action":"sessions","args":{},"save":"native"}]},"key":"discover-live-editors","section":"procedures"}
P discover-live-editors():availability=neyvia.gamedev.status(); native=neyvia.gamedev.sessions() -- Find installed editors and exact connected native contexts before operating
V P discover-live-editors -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"goal":"Check a terminal native receipt after polling until it stops being queued/running","inputs":{"$cl_type":"t11"},"steps":[{"action":"receipt","args":{"requestId":{"$input":"requestId"}},"check":"complete","save":"receipt"}]},"key":"review-completed-action","section":"procedures"}
P review-completed-action(requestId:str):receipt=neyvia.gamedev.receipt(requestId:requestId) C complete -- Check a terminal native receipt after polling until it stops being queued/running
V P review-completed-action -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"goal":"Reject broken glTF resources before any engine import","inputs":{"$cl_type":"t12"},"steps":[{"action":"asset_validate","args":{"path":{"$input":"path"}},"check":"valid-asset","save":"validation"}]},"key":"validate-export-before-engine-load","section":"procedures"}
P validate-export-before-engine-load(path:str):validation=neyvia.gamedev.asset_validate(path:path) C valid-asset -- Reject broken glTF resources before any engine import
V P validate-export-before-engine-load -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"goal":"Install a project-local bridge and prove its current package hashes/configuration; native connection requires a separate session heartbeat","inputs":{"$cl_type":"t13"},"steps":[{"action":"setup","args":{"engine":{"$input":"engine"},"projectPath":{"$input":"projectPath"}},"check":"configured","save":"setup"}]},"key":"setup-project","section":"procedures"}
P setup-project(engine:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath:str):setup=neyvia.gamedev.setup(engine:engine projectPath:projectPath) C configured -- Install a project-local bridge and prove its current package hashes/configuration; native connection requires a separate session heartbeat
V P setup-project -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"goal":"Queue exactly one affinity-bound native operation; poll this same request and review native completion before claiming scene behavior","inputs":{"$cl_type":"t14"},"steps":[{"action":"action","args":{"action":{"$input":"action"},"args":{"$input":"args"},"requestId":{"$input":"requestId"},"sessionId":{"$input":"sessionId"}},"check":"complete","save":"request"}]},"key":"operate-exact-session","section":"procedures"}
P operate-exact-session(sessionId:str action:str args:json:"{\"type\":\"object\"}" requestId:str):request=neyvia.gamedev.action(action:action args:args requestId:requestId sessionId:sessionId) C complete -- Queue exactly one affinity-bound native operation; poll this same request and review native completion before claiming scene behavior
V P operate-exact-session -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"goal":"In a disposable project with exactly one native editor instance, observe one connected client-affine session after registration retry; multiple real instances remain ambiguous","inputs":{"$cl_type":"t13"},"steps":[{"action":"sessions","args":{"context":"Edit","engine":{"$input":"engine"},"projectPath":{"$input":"projectPath"}},"check":"one-editor-session","save":"native"}]},"key":"inspect-one-editor-session","section":"procedures"}
P inspect-one-editor-session(engine:json:"{\"type\":\"string\",\"enum\":[\"unity\",\"roblox\",\"blender\",\"godot\",\"babylon\"]}" projectPath:str):native=neyvia.gamedev.sessions(context:"Edit" engine:engine projectPath:projectPath) C one-editor-session -- In a disposable project with exactly one native editor instance, observe one connected client-affine session after registration retry; multiple real instances remain ambiguous
V P inspect-one-editor-session -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"bridges","data":{"failure":"Editor is detected but no native session is connected","recovery":"Use setup then enable the project-local plugin in its actual editor; inspect heartbeat before actions"},"key":"0","section":"pitfalls"}
X Editor is detected but no native session is connected -> Use setup then enable the project-local plugin in its actual editor; inspect heartbeat before actions
-- @record {"chapter":"bridges","data":{"failure":"Action is queued/running","recovery":"Poll the same requestId until terminal; do not call it complete or queue a fresh retry"},"key":"1","section":"pitfalls"}
X Action is queued/running -> Poll the same requestId until terminal; do not call it complete or queue a fresh retry
-- @record {"chapter":"bridges","data":{"failure":"Backend restart, timeout or ambiguous completion","recovery":"Inspect native state first; interrupted actions are failed and never automatically replayed"},"key":"2","section":"pitfalls"}
X Backend restart, timeout or ambiguous completion -> Inspect native state first; interrupted actions are failed and never automatically replayed
-- @record {"chapter":"bridges","data":{"failure":"Changed request payload reuses an ID","recovery":"Inspect previous receipt, then choose a new ID only for a new explicit intent"},"key":"3","section":"pitfalls"}
X Changed request payload reuses an ID -> Inspect previous receipt, then choose a new ID only for a new explicit intent
-- @record {"chapter":"bridges","data":{"failure":"Roblox simulation stop preserves edits","recovery":"Require preserveChanges:true for simulation; player EndTest uses exact Server session, then observe Edit playResult"},"key":"4","section":"pitfalls"}
X Roblox simulation stop preserves edits -> Require preserveChanges:true for simulation; player EndTest uses exact Server session, then observe Edit playResult
-- @record {"chapter":"bridges","data":"Native Unity, Blender and Roblox defining editor journeys remain unproven. Godot and rendered Babylon journeys are recorded by the UI integration owner in plans/15-handoff.md followups; FOLLOW replay proves shared backend receipts, not a new editor installation.","key":"0","section":"frontier"}
F Native Unity, Blender and Roblox defining editor journeys remain unproven. Godot and rendered Babylon journeys are recorded by the UI integration owner in plans/15-handoff.md followups; FOLLOW replay proves shared backend receipts, not a new editor installation.
-- @record {"chapter":"bridges","data":"Unity glTF loading requires an existing project importer","key":"1","section":"frontier"}
F Unity glTF loading requires an existing project importer
-- @record {"chapter":"bridges","data":"Roblox StudioTestService play/end APIs and actual Client/Server plugin contexts remain unverified without Studio","key":"2","section":"frontier"}
F Roblox StudioTestService play/end APIs and actual Client/Server plugin contexts remain unverified without Studio
-- @record {"chapter":"bridges","data":"Observer/action/check tools share HTTP /api/backend, bot state and desktop forwarding; existing generic Tauri IPC carries gamedev_*_command.","key":"0","section":"guidance"}
M game-dev "Observer/action/check tools share HTTP /api/backend, bot state and desktop forwarding; existing generic Tauri IPC carries gamedev_*_command." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Unity: select/inspect path is scene hierarchy or Assets/...; guarded script edit uses source+expectedSha256; component edit path/component/property/value or vector; run/stop/reload; test mode EditMode/PlayMode only with existing Test Framework.","key":"1","section":"guidance"}
M game-dev "Unity: select/inspect path is scene hierarchy or Assets/...; guarded script edit uses source+expectedSha256; component edit path/component/property/value or vector; run/stop/reload; test mode EditMode/PlayMode only with existing Test Framework." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Godot Edit: inspect; select/edit node relative to scene, property and value; script edit path res://...gd, source, expectedSha256; validate path res://...gd; run -> observe separate Play session; Play interact node,input invokes game's explicit neyvia_interact method.","key":"2","section":"guidance"}
M game-dev "Godot Edit: inspect; select/edit node relative to scene, property and value; script edit path res://...gd, source, expectedSha256; validate path res://...gd; run -> observe separate Play session; Play interact node,input invokes game's explicit neyvia_interact method." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Roblox: exact studio_id and Edit/Client/Server affinity; Instance path, script source+expectedSource; run mode play uses StudioTestService (if available); stop mode play requires Server and final Edit playResult observation; simulation stop requires preserveChanges:true; read actual console.","key":"3","section":"guidance"}
M game-dev "Roblox: exact studio_id and Edit/Client/Server affinity; Instance path, script source+expectedSource; run mode play uses StudioTestService (if available); stop mode play requires Server and final Edit playResult observation; simulation stop requires preserveChanges:true; read actual console." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Blender: inspect/select/edit object and location/rotation/scale; render path PNG and camera; export path GLB/glTF and selectedOnly; validate then load_asset path.","key":"4","section":"guidance"}
M game-dev "Blender: inspect/select/edit object and location/rotation/scale; render path PNG and camera; export path GLB/glTF and selectedOnly; validate then load_asset path." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Babylon: edit op create/transform/material, name, position/rotation/scaling/color finite triples, expectedRevision; run/stop; interact name,rotateY radians; test name,position/minVertices; export path GLB with expectedSha256 for overwrite; validate then load_asset path GLB.","key":"5","section":"guidance"}
M game-dev "Babylon: edit op create/transform/material, name, position/rotation/scaling/color finite triples, expectedRevision; run/stop; interact name,rotateY radians; test name,position/minVertices; export path GLB with expectedSha256 for overwrite; validate then load_asset path GLB." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Export/import proof is boundary-specific. NullEngine runs real scene geometry and loader but cannot prove rendered pixels, clicks or Blender rendering.","key":"6","section":"guidance"}
M game-dev "Export/import proof is boundary-specific. NullEngine runs real scene geometry and loader but cannot prove rendered pixels, clicks or Blender rendering." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Engine APIs remain native; do not unify Unity Components, Roblox Instances and Godot Nodes.","key":"7","section":"guidance"}
M game-dev "Engine APIs remain native; do not unify Unity Components, Roblox Instances and Godot Nodes." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Private .neyvia/gamedev-bridge.json must remain out of source control. Never expose its token in UI or receipts.","key":"8","section":"guidance"}
M game-dev "Private .neyvia/gamedev-bridge.json must remain out of source control. Never expose its token in UI or receipts." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Game Dev action log reads gamedev_receipts_command so bot and UI actions share durable results. Screen reports use POST /api/ui/app-state app=game-dev and appear through neyvia.gamedev.state; reported selection never establishes native engine success.","key":"9","section":"guidance"}
M game-dev "Game Dev action log reads gamedev_receipts_command so bot and UI actions share durable results. Screen reports use POST /api/ui/app-state app=game-dev and appear through neyvia.gamedev.state; reported selection never establishes native engine success." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Native bridges use the literal loopback port in the selected project capability configuration, excluding public port 47881. Unity batchmode/nographics, Godot --headless --editor, and Blender --background preserve the actual native scene operations. A pending request is not a completed edit; use the same requestId and reread inspect after success.","key":"10","section":"guidance"}
M game-dev "Native bridges use the literal loopback port in the selected project capability configuration, excluding public port 47881. Unity batchmode/nographics, Godot --headless --editor, and Blender --background preserve the actual native scene operations. A pending request is not a completed edit; use the same requestId and reread inspect after success." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Observe sessions with explicit engine, projectPath and context before action. CL fills sessionId only when this current observation contains one exact native session; it never guesses a native session from the chat identity.","key":"11","section":"guidance"}
M game-dev "Observe sessions with explicit engine, projectPath and context before action. CL fills sessionId only when this current observation contains one exact native session; it never guesses a native session from the chat identity." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Unity, Godot and Blender register with a stable per-instance clientId. Identical retry replies preserve the native session; changed affinity or capabilities refuse reuse. Separate editor instances keep separate identities, so CL still refuses ambiguous session selection. Unity idle polls never execute empty nested request objects.","key":"12","section":"guidance"}
M game-dev "Unity, Godot and Blender register with a stable per-instance clientId. Identical retry replies preserve the native session; changed affinity or capabilities refuse reuse. Separate editor instances keep separate identities, so CL still refuses ambiguous session selection. Unity idle polls never execute empty nested request objects." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"LAYA3D uses the shared scene.transcribe, laya.judge and scene.improve core. Read manuals/cl/laya-3d.cl for defect predicates and manuals/cl/laya-3d-image.cl for image-model acceptance. Blender transcribe observes mesh facts; canonical renders fixed front/side/back/top views; snapshot/restore guard named mesh_fix operations. shape_program executes literal bounded shape operations in its own collection, not Python code.","key":"13","section":"guidance"}
M game-dev "LAYA3D uses the shared scene.transcribe, laya.judge and scene.improve core. Read manuals/cl/laya-3d.cl for defect predicates and manuals/cl/laya-3d-image.cl for image-model acceptance. Blender transcribe observes mesh facts; canonical renders fixed front/side/back/top views; snapshot/restore guard named mesh_fix operations. shape_program executes literal bounded shape operations in its own collection, not Python code." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"For image input call scene.improve with domain=laya3d, source={sessionId, sheet, spec:{object, cells:[{cell, caption, role, camera:{yaw, elevation, roll}, illustrationOnly?}]}} and budget={max_steps:1,max_seconds:240,allowed_fixes:[shape.refit],guards:{outline_iou_mean:min}}; call it once per program edit until the ladder is exhausted. Cells are physical row-major positions from detected gutters, never printed numbers. Camera readings may list alternatives and are fitted within 25 degrees; the first cell is the anchor. Illustration-only cells (topology guides, exploded, detail) are recorded, never geometry. The returned modelPath resumes the CL model; scene.transcribe with sessionId/modelPath observes the live model without rebuilding. Predicates read the shape-model node (worst and mean view outline IoU, colour and extent bands); per-view numbers are evidence. Silhouettes cannot recover concavities; held-out views measure 3D shape.","key":"14","section":"guidance"}
M game-dev "For image input call scene.improve with domain=laya3d, source={sessionId, sheet, spec:{object, cells:[{cell, caption, role, camera:{yaw, elevation, roll}, illustrationOnly?}]}} and budget={max_steps:1,max_seconds:240,allowed_fixes:[shape.refit],guards:{outline_iou_mean:min}}; call it once per program edit until the ladder is exhausted. Cells are physical row-major positions from detected gutters, never printed numbers. Camera readings may list alternatives and are fitted within 25 degrees; the first cell is the anchor. Illustration-only cells (topology guides, exploded, detail) are recorded, never geometry. The returned modelPath resumes the CL model; scene.transcribe with sessionId/modelPath observes the live model without rebuilding. Predicates read the shape-model node (worst and mean view outline IoU, colour and extent bands); per-view numbers are evidence. Silhouettes cannot recover concavities; held-out views measure 3D shape." src:"authored manual" state:verified
-- @record {"chapter":"bridges","data":"Godot and Unity transcribe expose live native hierarchy, scale, mesh/material/reference facts and collider intent to the same predicates; engine.scale is the only automatic engine fix, collider and reference findings stay review-only. Godot's client reconnects with the same clientId when the editor's first scan outlasts the socket handshake. A Unity project needs ProjectSettings/ProjectVersion.txt, or UPM adds and downloads the default template packages; the bridge package declares its JSON, UnityWebRequest and Physics modules. Blender scene.improve callers pass guards {silhouette_quality:min}; transcribe keeps render paths out of the Scene so rollback is checked by sha256. Roblox observer is code-only until an installed Studio session is available. Native texture upscale is bounded resampling, not invented detail; topology flow and rendered lighting remain review-only when not measured.","key":"15","section":"guidance"}
M game-dev "Godot and Unity transcribe expose live native hierarchy, scale, mesh/material/reference facts and collider intent to the same predicates; engine.scale is the only automatic engine fix, collider and reference findings stay review-only. Godot's client reconnects with the same clientId when the editor's first scan outlasts the socket handshake. A Unity project needs ProjectSettings/ProjectVersion.txt, or UPM adds and downloads the default template packages; the bridge package declares its JSON, UnityWebRequest and Physics modules. Blender scene.improve callers pass guards {silhouette_quality:min}; transcribe keeps render paths out of the Scene so rollback is checked by sha256. Roblox observer is code-only until an installed Studio session is available. Native texture upscale is bounded resampling, not invented detail; topology flow and rendered lighting remain review-only when not measured." src:"authored manual" state:verified
L game-dev.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t7"},"shape":{"$cl_type":"t15"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S game-dev.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t16"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" ! -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t7"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"gamedev.keepSelection: Native selection never changes implicitly; browser reload affinity follows only one same-project/context replacement","key":"0","section":"guidance"}
M game-dev "gamedev.keepSelection: Native selection never changes implicitly; browser reload affinity follows only one same-project/context replacement" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"gamedev.tabForStage: Explicit known tabs win, then launcher app aliases, then embedded Browser 3D","key":"1","section":"guidance"}
M game-dev "gamedev.tabForStage: Explicit known tabs win, then launcher app aliases, then embedded Browser 3D" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"gamedev.visibleFields: Conditional controls show exactly fields whose predicates hold","key":"2","section":"guidance"}
M game-dev "gamedev.visibleFields: Conditional controls show exactly fields whose predicates hold" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"gamedev.initialValues: Form defaults resolve duplicate keys according to their condition","key":"3","section":"guidance"}
M game-dev "gamedev.initialValues: Form defaults resolve duplicate keys according to their condition" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"gamedev.buildArgs: Visible fields become exact bridge args; vectors/numbers are finite, JSON text must parse as an object and wildcard fields are flattened","key":"4","section":"guidance"}
M game-dev "gamedev.buildArgs: Visible fields become exact bridge args; vectors/numbers are finite, JSON text must parse as an object and wildcard fields are flattened" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"gamedev.actionFields: Godot edit/interact and Unity test forms retain their typed bridge fields/defaults; other actions return valid field arrays","key":"5","section":"guidance"}
M game-dev "gamedev.actionFields: Godot edit/interact and Unity test forms retain their typed bridge fields/defaults; other actions return valid field arrays" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"6","section":"guidance"}
M game-dev "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
-- @proof {"checkedAt":["grant_agent.neyvia_gamedev.report_state","grant_agent.ui_command_bus.UICommandBus.put","grant_agent.ui_command_bus.UICommandBus.get","grant_agent.proofs_surface_games_extra.screen_state_persists_and_refuses_invalid_tab"],"claim":"Game Dev screen selection persists the exact tab, project and UI client through the backend state bus; an unknown tab is refused and leaves the last valid selection unchanged.","id":"p22.gamedev.screen-state-persistence","impact":["Game Dev selected editor/project screen state and invalid-tab refusal"],"phase":"post"}
