CL 1
L handoff-recovery v1 -- Authored executable manual
-- @manual {"chapters":{"intake":{"title":"Reviewed handoff intake: Notes + Files, not a generic model benchmark"},"proofs_a_capabilities":{"title":"Capability action contracts (PROOFS-a)"}},"clVersion":"1.1","id":"handoff-recovery","kind":"workflow","proofs":{"area":"a-capabilities","manifests":["config/proofs/a-capabilities.json"],"startup":{"procedures":["grant_agent.proofs_a_capabilities.self_check"],"runner":"grant_agent.proof_verifier.run_verification","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.files.move":"t1","neyvia.files.stat":"t2","neyvia.notes.pin":"t3","neyvia.notes.read":"t4","neyvia.notes.write":"t5"},"tool_metadata":{"neyvia.files.move":{"mutability_class":"none"},"neyvia.files.stat":{"mutability_class":"read"},"neyvia.notes.pin":{"mutability_class":"none"},"neyvia.notes.read":{"mutability_class":"read"},"neyvia.notes.write":{"mutability_class":"none"}}}
-- @proof {"checkedAt":["grant_agent.checkpoints.CheckpointStore.save -> check_checkpoint","grant_agent.proofs_a_capabilities.self_check"],"claim":"Saved checkpoints reread as the complete record with no atomic-write temporary tails.","id":"a.checkpoint-durable","impact":["bounded local capability actions","agent/operator evidence","recoverable scratch state"],"phase":"goal"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"from\":{\"type\":\"string\"},\"to\":{\"type\":\"string\"}},\"required\":[\"from\",\"to\"],\"allOf\":[{\"properties\":{\"from\":{\"not\":{\"enum\":[\"\"]}},\"to\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"preview\":{\"type\":\"boolean\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"pinned\":{\"type\":\"boolean\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"body\":{\"type\":\"string\"},\"mode\":{\"type\":\"string\",\"enum\":[\"replace\",\"append\"]},\"expectedModified\":{\"type\":\"string\"}},\"required\":[\"body\"],\"allOf\":[{\"properties\":{\"body\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{}
T t7{folder:str exists:bool notes:json:"{\"type\":\"array\"}" tags:json:"{\"type\":\"array\"}" ..}
T t8{body:str modified:str pinned:bool ..}
T t9 json:"{\"type\":\"object\"}"
T t10{path:str message:str source:str target:str}
L handoff-recovery.intake v1 -- Reviewed handoff intake: Notes + Files, not a generic model benchmark
-- @record {"chapter":"intake","data":{"args":{},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t7"},"tool":"neyvia.notes.list"},"key":"note","section":"state"}
S handoff-recovery.note:{folder:str exists:bool notes:json:"{\"type\":\"array\"}" tags:json:"{\"type\":\"array\"}" ..}=neyvia.notes.list()
-- @record {"chapter":"intake","data":{"effect":"Return body, relative path, tags, pinned and nanosecond modified stamp","pre":"Existing .md/.markdown/.txt resolved beneath notes folder, at most 2 MiB","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.notes.read","tool":"neyvia.notes.read"},"key":"notes.read","section":"actions"}
A neyvia.notes.read(path:str) -> {body:str modified:str pinned:bool ..} -- Return body, relative path, tags, pinned and nanosecond modified stamp
F verify-notes-read "No authored observer check is bound to neyvia.notes.read" -> ask operator blocks:neyvia.notes.read
-- @record {"chapter":"intake","data":{"effect":"Atomically create or replace Markdown; append adds newline-separated text; no path chooses a unique title filename","pre":"UTF-8 body <=2 MiB; explicit path stays beneath notes folder with note extension; supplied expectedModified must match an existing note","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.notes.write","tool":"neyvia.notes.write"},"key":"notes.write","section":"actions"}
A neyvia.notes.write(path?:str title?:str body:str mode?:json:"{\"type\":\"string\",\"enum\":[\"replace\",\"append\"]}" expectedModified?:str) -> json:"{\"type\":\"object\"}" ! -- Atomically create or replace Markdown; append adds newline-separated text; no path chooses a unique title filename
C neyvia.notes.write captured:neyvia.notes.read(path:path) .body has message
-- @record {"chapter":"intake","data":{"effect":"Atomically update .neyvia-notes.json pin list; note bytes unchanged","pre":"Existing note beneath notes folder; pinned defaults true","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.notes.pin","tool":"neyvia.notes.pin"},"key":"notes.pin","section":"actions"}
A neyvia.notes.pin(path:str pinned?:bool) -> json:"{\"type\":\"object\"}" ! -- Atomically update .neyvia-notes.json pin list; note bytes unchanged
C neyvia.notes.pin pinned:neyvia.notes.read(path:path) .pinned == true
-- @record {"chapter":"intake","data":{"effect":"Return kind/size/openWith; preview=true reads first 64 KiB only for text/notes","pre":"Existing guarded path inside a Files place outside protected tree","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.files.stat","tool":"neyvia.files.stat"},"key":"files.stat","section":"actions"}
A neyvia.files.stat(path:str preview?:bool) -> json:"{\"type\":\"object\"}" -- Return kind/size/openWith; preview=true reads first 64 KiB only for text/notes
F verify-files-stat "No authored observer check is bound to neyvia.files.stat" -> ask operator blocks:neyvia.files.stat
-- @record {"chapter":"intake","data":{"effect":"Move/rename without overwrite; an existing destination folder receives source.name; replace undo receipt","pre":"Existing guarded source; destination parent exists, destination absent except case rename; no folder into itself; model approval for both non-workspace/non-notes places","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.files.move","tool":"neyvia.files.move"},"key":"files.move","section":"actions"}
A neyvia.files.move(from:str to:str) -> json:"{\"type\":\"object\"}" ! -- Move/rename without overwrite; an existing destination folder receives source.name; replace undo receipt
F verify-files-move "No authored observer check is bound to neyvia.files.move" -> ask operator blocks:neyvia.files.move
-- @record {"chapter":"intake","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"contains","path":"body","value":{"$input":"message"}},"tool":"neyvia.notes.read"},"key":"captured","section":"checks"}
C neyvia.notes.read captured:neyvia.notes.read(path:path) .body has message
-- @record {"chapter":"intake","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"pinned","value":true},"tool":"neyvia.notes.read"},"key":"pinned","section":"checks"}
C neyvia.notes.read pinned:neyvia.notes.read(path:path) .pinned == true
-- @record {"chapter":"intake","data":{"goal":"Move the explicitly reviewed draft, append its #ready receipt once and pin it","inputs":{"$cl_type":"t10"},"steps":[{"action":"notes.read","args":{"path":{"$input":"path"}},"save":"before"},{"action":"files.stat","args":{"path":{"$input":"source"},"preview":true},"save":"selected"},{"judge":"approval"},{"action":"files.move","args":{"from":{"$input":"source"},"to":{"$input":"target"}},"save":"moved","when":{"judge":"approval","option":"approved"}},{"action":"notes.write","args":{"body":{"$input":"message"},"expectedModified":{"$result":"before.modified"},"mode":"append","path":{"$input":"path"}},"check":"captured","save":"written","when":{"judge":"approval","option":"approved"}},{"action":"notes.pin","args":{"path":{"$input":"path"},"pinned":true},"check":"pinned","save":"pin","when":{"judge":"approval","option":"approved"}}]},"key":"stage-reviewed","section":"procedures"}
P stage-reviewed(path:str message:str source:str target:str):before=neyvia.notes.read(path:path); selected=neyvia.files.stat(path:source preview:true); J approval=approved; moved=neyvia.files.move(from:source to:target); written=neyvia.notes.write(body:message expectedModified:before.modified mode:"append" path:path) C captured; pin=neyvia.notes.pin(path:path pinned:true) C pinned -- Move the explicitly reviewed draft, append its #ready receipt once and pin it
V P stage-reviewed -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"intake","data":{"goal":"Hold unreviewed draft and append/pin a #needs-review receipt","inputs":{"$cl_type":"t10"},"steps":[{"action":"notes.read","args":{"path":{"$input":"path"}},"save":"before"},{"judge":"receipt"},{"action":"notes.write","args":{"body":{"$input":"message"},"expectedModified":{"$result":"before.modified"},"mode":"append","path":{"$input":"path"}},"check":"captured","save":"written","when":{"judge":"receipt","option":"record"}},{"action":"notes.pin","args":{"path":{"$input":"path"},"pinned":true},"check":"pinned","save":"pin","when":{"judge":"receipt","option":"record"}}]},"key":"record-review","section":"procedures"}
P record-review(path:str message:str source:str target:str):before=neyvia.notes.read(path:path); J receipt=record; written=neyvia.notes.write(body:message expectedModified:before.modified mode:"append" path:path) C captured; pin=neyvia.notes.pin(path:path pinned:true) C pinned -- Hold unreviewed draft and append/pin a #needs-review receipt
V P record-review -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"intake","data":{"goal":"Preserve both colliding drafts and append/pin a #blocked receipt","inputs":{"$cl_type":"t10"},"steps":[{"action":"notes.read","args":{"path":{"$input":"path"}},"save":"before"},{"judge":"receipt"},{"action":"notes.write","args":{"body":{"$input":"message"},"expectedModified":{"$result":"before.modified"},"mode":"append","path":{"$input":"path"}},"check":"captured","save":"written","when":{"judge":"receipt","option":"record"}},{"action":"notes.pin","args":{"path":{"$input":"path"},"pinned":true},"check":"pinned","save":"pin","when":{"judge":"receipt","option":"record"}}]},"key":"record-blocked","section":"procedures"}
P record-blocked(path:str message:str source:str target:str):before=neyvia.notes.read(path:path); J receipt=record; written=neyvia.notes.write(body:message expectedModified:before.modified mode:"append" path:path) C captured; pin=neyvia.notes.pin(path:path pinned:true) C pinned -- Preserve both colliding drafts and append/pin a #blocked receipt
V P record-blocked -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"intake","data":{"goal":"Guarded idempotent capture with a fresh read and an explicit record/skip decision","inputs":{"$cl_type":"t10"},"steps":[{"action":"notes.read","args":{"path":{"$input":"path"}},"save":"before"},{"judge":"capture"},{"action":"notes.write","args":{"body":{"$input":"message"},"expectedModified":{"$result":"before.modified"},"mode":"append","path":{"$input":"path"}},"check":"captured","save":"written","when":{"judge":"capture","option":"record"}},{"action":"notes.pin","args":{"path":{"$input":"path"},"pinned":true},"check":"pinned","save":"pin","when":{"judge":"capture","option":"record"}}]},"key":"capture-once","section":"procedures"}
P capture-once(path:str message:str source:str target:str):before=neyvia.notes.read(path:path); J capture=record; written=neyvia.notes.write(body:message expectedModified:before.modified mode:"append" path:path) C captured; pin=neyvia.notes.pin(path:path pinned:true) C pinned -- Guarded idempotent capture with a fresh read and an explicit record/skip decision
V P capture-once -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"intake","data":{"goal":"Restore the selected staged draft without undoing unrelated Files operations; append/pin #restored receipt","inputs":{"$cl_type":"t10"},"steps":[{"action":"notes.read","args":{"path":{"$input":"path"}},"save":"before"},{"action":"files.stat","args":{"path":{"$input":"source"},"preview":true},"save":"selected"},{"judge":"restore"},{"action":"files.move","args":{"from":{"$input":"source"},"to":{"$input":"target"}},"save":"moved","when":{"judge":"restore","option":"restore"}},{"action":"notes.write","args":{"body":{"$input":"message"},"expectedModified":{"$result":"before.modified"},"mode":"append","path":{"$input":"path"}},"check":"captured","save":"written","when":{"judge":"restore","option":"restore"}},{"action":"notes.pin","args":{"path":{"$input":"path"},"pinned":true},"check":"pinned","save":"pin","when":{"judge":"restore","option":"restore"}}]},"key":"restore-selected","section":"procedures"}
P restore-selected(path:str message:str source:str target:str):before=neyvia.notes.read(path:path); selected=neyvia.files.stat(path:source preview:true); J restore=restore; moved=neyvia.files.move(from:source to:target); written=neyvia.notes.write(body:message expectedModified:before.modified mode:"append" path:path) C captured; pin=neyvia.notes.pin(path:path pinned:true) C pinned -- Restore the selected staged draft without undoing unrelated Files operations; append/pin #restored receipt
V P restore-selected -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"intake","data":{"constraints":"Choose skip when already captured. Otherwise record only by guarded append. A failed conflict run is not resumable: reconcile actual note, restart fresh and choose skip if message already exists.","options":["record","skip"],"question":"Does the exact message already occur in before.body?"},"key":"capture","section":"judge"}
J capture record|skip:"Does the exact message already occur in before.body?" -- Choose skip when already captured. Otherwise record only by guarded append. A failed conflict run is not resumable: reconcile actual note, restart fresh and choose skip if message already exists.
V J capture -> human:operator why:"explicit choice required"
-- @record {"chapter":"intake","data":{"constraints":"Only explicit reviewed approval with absent destination allows the move. Pending review uses record-review; collisions use record-blocked. Do not overwrite or invent another destination.","options":["approved","stop"],"question":"Is the draft reviewed and its exact destination absent?"},"key":"approval","section":"judge"}
J approval approved|stop:"Is the draft reviewed and its exact destination absent?" -- Only explicit reviewed approval with absent destination allows the move. Pending review uses record-review; collisions use record-blocked. Do not overwrite or invent another destination.
V J approval -> human:operator why:"explicit choice required"
-- @record {"chapter":"intake","data":{"constraints":"Record the exact tagged message in the selected note; preserve draft bytes. Pin the receipt so Paul can find it.","options":["record","stop"],"question":"Is this the authorized handoff receipt for the selected task?"},"key":"receipt","section":"judge"}
J receipt record|stop:"Is this the authorized handoff receipt for the selected task?" -- Record the exact tagged message in the selected note; preserve draft bytes. Pin the receipt so Paul can find it.
V J receipt -> human:operator why:"explicit choice required"
-- @record {"chapter":"intake","data":{"constraints":"Restore by explicit files.move. Global files.undo targets the most recent operation and must not undo another operation.","options":["restore","stop"],"question":"Is source the selected staged draft and target its original absent path?"},"key":"restore","section":"judge"}
J restore restore|stop:"Is source the selected staged draft and target its original absent path?" -- Restore by explicit files.move. Global files.undo targets the most recent operation and must not undo another operation.
V J restore -> human:operator why:"explicit choice required"
-- @record {"chapter":"intake","data":{"failure":"notes.write returns ok=false status=conflict after another editor changed the note","recovery":"Do not drop expectedModified or resume the failed run. Start a fresh capture-once run, inspect before.body, then record or skip. Retain concurrent editor text."},"key":"0","section":"pitfalls"}
X notes.write returns ok=false status=conflict after another editor changed the note -> Do not drop expectedModified or resume the failed run. Start a fresh capture-once run, inspect before.body, then record or skip. Retain concurrent editor text.
-- @record {"chapter":"intake","data":{"failure":"A destination exists","recovery":"Do not rename the destination, overwrite, undo it or choose a suffix. Keep both originals and record-blocked with #blocked."},"key":"1","section":"pitfalls"}
X A destination exists -> Do not rename the destination, overwrite, undo it or choose a suffix. Keep both originals and record-blocked with #blocked.
-- @record {"chapter":"intake","data":{"failure":"Another Files operation followed staging","recovery":"Use restore-selected with the staged path as source and original path as target. Never call global files.undo."},"key":"2","section":"pitfalls"}
X Another Files operation followed staging -> Use restore-selected with the staged path as source and original path as target. Never call global files.undo.
-- @record {"chapter":"intake","data":"This manual supplies environment-specific receipt conventions; passing it does not prove general model improvement.","key":"0","section":"frontier"}
F This manual supplies environment-specific receipt conventions; passing it does not prove general model improvement.
-- @record {"chapter":"intake","data":"Judgement decisions are external inputs. Deterministic procedure token accounting excludes human/model judgement.","key":"1","section":"frontier"}
F Judgement decisions are external inputs. Deterministic procedure token accounting excludes human/model judgement.
-- @record {"chapter":"intake","data":"A move or note receipt proves backend state, not rendered UI.","key":"2","section":"frontier"}
F A move or note receipt proves backend state, not rendered UI.
-- @record {"chapter":"intake","data":"Task mapping: approved => stage-reviewed (approval=approved); pending => record-review (receipt=record); collision => record-blocked (receipt=record); stale and duplicate => capture-once (capture=record if message absent, otherwise skip); undo => restore-selected (restore=restore).","key":"0","section":"guidance"}
M handoff-recovery "Task mapping: approved => stage-reviewed (approval=approved); pending => record-review (receipt=record); collision => record-blocked (receipt=record); stale and duplicate => capture-once (capture=record if message absent, otherwise skip); undo => restore-selected (restore=restore)." src:"authored manual" state:verified
-- @record {"chapter":"intake","data":"Always use the exact supplied path/message/source/target inputs. Raw equivalent actions are allowed; procedure use is not required for scoring.","key":"1","section":"guidance"}
M handoff-recovery "Always use the exact supplied path/message/source/target inputs. Raw equivalent actions are allowed; procedure use is not required for scoring." src:"authored manual" state:verified
-- @record {"chapter":"intake","data":"Every new receipt uses guarded append and is pinned. Exact already-present receipt stays unchanged. Pending and collision tasks do not move files.","key":"2","section":"guidance"}
M handoff-recovery "Every new receipt uses guarded append and is pinned. Exact already-present receipt stays unchanged. Pending and collision tasks do not move files." src:"authored manual" state:verified
-- @record {"chapter":"intake","data":"Stale case: the fixture makes one real concurrent edit after first read/judge. A failed verifier is a stop, not success. Re-read via a fresh capture-once run and preserve both paragraphs.","key":"3","section":"guidance"}
M handoff-recovery "Stale case: the fixture makes one real concurrent edit after first read/judge. A failed verifier is a stop, not success. Re-read via a fresh capture-once run and preserve both paragraphs." src:"authored manual" state:verified
L handoff-recovery.proofs_a_capabilities v1 -- Capability action contracts (PROOFS-a)
-- @record {"chapter":"proofs_a_capabilities","data":{"failure":"Scratch receipt is mistaken for external runtime or rendered UI evidence","recovery":"Use a real rendered or authorized external journey before claiming those boundaries"},"key":"0","section":"pitfalls"}
X Scratch receipt is mistaken for external runtime or rendered UI evidence -> Use a real rendered or authorized external journey before claiming those boundaries
-- @record {"chapter":"proofs_a_capabilities","data":"Unmapped original cases remain protected until complete equivalent contracts and startup receipts exist","key":"0","section":"frontier"}
F Unmapped original cases remain protected until complete equivalent contracts and startup receipts exist
-- @record {"chapter":"proofs_a_capabilities","data":"Behavior plans preserve selected capsule gates and bounded learned vectors; compiler cache remains observable.","key":"0","section":"guidance"}
M handoff-recovery "Behavior plans preserve selected capsule gates and bounded learned vectors; compiler cache remains observable." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_capabilities","data":"Challenge selection follows configured token relevance; checkpoint saving verifies the durable full record.","key":"1","section":"guidance"}
M handoff-recovery "Challenge selection follows configured token relevance; checkpoint saving verifies the durable full record." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_capabilities","data":"Capability descriptions bind actual adapter state; artifact lineage binds local file hashes and persistent relation endpoints.","key":"2","section":"guidance"}
M handoff-recovery "Capability descriptions bind actual adapter state; artifact lineage binds local file hashes and persistent relation endpoints." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_capabilities","data":"Typed recovery remains review-only and does not retain narrative file bodies.","key":"3","section":"guidance"}
M handoff-recovery "Typed recovery remains review-only and does not retain narrative file bodies." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_capabilities","data":"Run neyvia verify --areas a-capabilities in isolated scratch state.","key":"4","section":"guidance"}
M handoff-recovery "Run neyvia verify --areas a-capabilities in isolated scratch state." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_capabilities","data":"Capability initialization uses an explicit empty vault configuration under disposable proof state. Saved broker/account configurations are never read; these procedures make no vault/account execution claim.","key":"5","section":"guidance"}
M handoff-recovery "Capability initialization uses an explicit empty vault configuration under disposable proof state. Saved broker/account configurations are never read; these procedures make no vault/account execution claim." src:"authored manual" state:verified
