CL 1
L hill-climb v1 -- Authored executable manual
-- @manual {"chapters":{"evolver":{"title":"Paired evolution with locked judges and fresh confirmation"},"method":{"title":"Executable hill-climb method: chronological mechanism and measured quality"},"overview":{"title":"Frozen improvement receipts, history and measured Pareto tradeoffs"},"proofs-e-sv":{"title":"PROOFS-e s-v host contracts and confined startup receipts"},"proofs-e-wz":{"title":"PROOFS-e W-Z: live contracts and scratch self-checks"}},"clVersion":"1.1","id":"hill-climb","kind":"workflow","proofs":{"area":"hill-climb","manifests":["config/proofs/proofs-e-sv.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.evolver.genome":"t1","neyvia.evolver.job":"t2","neyvia.evolver.lineage":"t3","neyvia.evolver.receipt":"t4","neyvia.evolver.run":"t5","neyvia.evolver.state":"t6","neyvia.lab.state":"t7","neyvia.workflow.check":"t8","neyvia.workflow.record":"t8"},"tool_metadata":{"neyvia.evolver.genome":{},"neyvia.evolver.job":{},"neyvia.evolver.lineage":{},"neyvia.evolver.receipt":{},"neyvia.evolver.run":{},"neyvia.evolver.state":{},"neyvia.lab.state":{},"neyvia.workflow.check":{"mutability_class":"read"},"neyvia.workflow.record":{"mutability_class":"artifact_write"}}}
-- @proof {"checkedAt":["grant_agent.self_repair.execute_self_repair_job","grant_agent.proofs_e_wz.check_repair","grant_agent.proofs_e_wz.self_check"],"claim":"Repair attempts never exceed the existing hard cap; repair/verify phase counts equal attempts actually used and verification occurs only after passed repair actions.","id":"proofs-e-wz.repair-bounds","impact":["bounded detect-repair-verify loop"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.self_repair.execute_self_repair_job","grant_agent.proofs_e_wz.check_repair","grant_agent.proofs_e_wz.self_check"],"claim":"Completion requires a real passed detection or verification phase; proof booleans match executed phase results, tracked changes match before/after hashes and the saved receipt exactly equals the returned receipt.","id":"proofs-e-wz.repair-receipt","impact":["repair evidence","tracked bytes","job completion"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.self_repair.execute_self_repair_job","grant_agent.proofs_e_wz.check_repair","grant_agent.proofs_e_wz.self_check"],"claim":"An invalid repair contract returns a blocked durable receipt with its contract error and runs no command phases or claimed final verification.","id":"proofs-e-wz.repair-blocked","impact":["invalid execution contracts","failure reporting"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.worker.run_local_worker_once","grant_agent.proofs_e_wz.check_worker_repair","grant_agent.proofs_e_wz.self_check"],"claim":"After actual local worker execution, the persisted job status matches its result, all reported phase events are recorded and the repair receipt is registered as a durable artifact.","id":"proofs-e-wz.worker-repair","impact":["cluster worker","repair artifacts","event history"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.suite_report.build_suite_summary -> grant_agent.proofs_e_sv.check","grant_agent.proofs_e_sv.self_check"],"claim":"Suite averages, pass rate and preset count exactly reflect supplied observed rows, including the empty suite.","id":"sv.suite.summary","impact":["hill-climb","PROOFS-e s-v behavior"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.suite_report.write_suite_artifacts -> grant_agent.proofs_e_sv.check","grant_agent.proofs_e_sv.self_check"],"claim":"Successful suite artifact writing returns paths whose JSON preserves all input evidence and whose human report lists every preset.","id":"sv.suite.artifacts","impact":["hill-climb","PROOFS-e s-v behavior"],"phase":"invariant"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\"},\"genome\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"domain\",\"genome\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2{requestId:str#1.. ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\"}},\"required\":[\"domain\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\"},\"trial\":{\"type\":\"integer\",\"minimum\":1}},\"required\":[\"domain\",\"trial\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{domain:json:"{\"type\":\"string\",\"enum\":[\"manual_compression\",\"cl_skill\",\"manual_compression_v2\",\"cl_skill_v2\",\"cl_skill_v3\",\"paul_intent\",\"manual_json_local_v1\"]}" requestId:str#1.. maxTrials?:1..2 ..}
T t6{domain?:str ..}
T t7{..}
T t8{manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t9{ok:true domains:json:"{\"type\":\"array\"}" publicPromotion:false ..}
T t10 json:"{\"type\":\"object\"}"
T t11{report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t12 json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"
T t13{}
T t14{records:json:"{\"type\":\"array\"}" competitions:json:"{\"type\":\"array\"}" automaticTraining:false automaticPromotion:false ..}
L hill-climb.evolver v1 -- Paired evolution with locked judges and fresh confirmation
-- @record {"chapter":"evolver","data":{"args":{},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t9"},"tool":"neyvia.evolver.state"},"key":"current","section":"state"}
S hill-climb.current:{ok:true domains:json:"{\"type\":\"array\"}" publicPromotion:false ..}=neyvia.evolver.state()
-- @record {"chapter":"evolver","data":{"effect":"Read actual receipts; no public release changes","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.evolver.state","tool":"neyvia.evolver.state"},"key":"evolver.state","section":"actions"}
A neyvia.evolver.state(domain?:str) -> json:"{\"type\":\"object\"}" ! -- Read actual receipts; no public release changes
C neyvia.evolver.state observed:neyvia.evolver.state() .publicPromotion == false
-- @record {"chapter":"evolver","data":{"effect":"Read actual receipts; no public release changes","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.evolver.lineage","tool":"neyvia.evolver.lineage"},"key":"evolver.lineage","section":"actions"}
A neyvia.evolver.lineage(domain:str) -> json:"{\"type\":\"object\"}" ! -- Read actual receipts; no public release changes
F verify-evolver-lineage "No authored observer check is bound to neyvia.evolver.lineage" -> ask operator blocks:neyvia.evolver.lineage
-- @record {"chapter":"evolver","data":{"effect":"Read actual receipts; no public release changes","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.evolver.receipt","tool":"neyvia.evolver.receipt"},"key":"evolver.receipt","section":"actions"}
A neyvia.evolver.receipt(domain:str trial:1..) -> json:"{\"type\":\"object\"}" ! -- Read actual receipts; no public release changes
F verify-evolver-receipt "No authored observer check is bound to neyvia.evolver.receipt" -> ask operator blocks:neyvia.evolver.receipt
-- @record {"chapter":"evolver","data":{"effect":"Start a bounded named frozen domain; local compression uses no model; the other domains use GPT-6 Luna","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.evolver.run","tool":"neyvia.evolver.run"},"key":"evolver.run","section":"actions"}
A neyvia.evolver.run(domain:json:"{\"type\":\"string\",\"enum\":[\"manual_compression\",\"cl_skill\",\"manual_compression_v2\",\"cl_skill_v2\",\"cl_skill_v3\",\"paul_intent\",\"manual_json_local_v1\"]}" requestId:str#1.. maxTrials?:1..2) -> json:"{\"type\":\"object\"}" ! -- Start a bounded named frozen domain; local compression uses no model; the other domains use GPT-6 Luna
F verify-evolver-run "No authored observer check is bound to neyvia.evolver.run" -> ask operator blocks:neyvia.evolver.run
-- @record {"chapter":"evolver","data":{"effect":"Read actual receipts; no public release changes","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.evolver.job","tool":"neyvia.evolver.job"},"key":"evolver.job","section":"actions"}
A neyvia.evolver.job(requestId:str#1..) -> json:"{\"type\":\"object\"}" ! -- Read actual receipts; no public release changes
F verify-evolver-job "No authored observer check is bound to neyvia.evolver.job" -> ask operator blocks:neyvia.evolver.job
-- @record {"chapter":"evolver","data":{"effect":"Read actual receipts; no public release changes","pre":"Read selected workspace state; do not pass judge, panel or promotion edits","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.evolver.genome","tool":"neyvia.evolver.genome"},"key":"evolver.genome","section":"actions"}
A neyvia.evolver.genome(domain:str genome:str ~"^[a-f0-9]{64}$") -> json:"{\"type\":\"object\"}" ! -- Read actual receipts; no public release changes
F verify-evolver-genome "No authored observer check is bound to neyvia.evolver.genome" -> ask operator blocks:neyvia.evolver.genome
-- @record {"chapter":"evolver","data":{"args":{},"expect":{"op":"eq","path":"publicPromotion","value":false},"tool":"neyvia.evolver.state"},"key":"observed","section":"checks"}
C neyvia.evolver.state observed:neyvia.evolver.state() .publicPromotion == false
-- @record {"chapter":"evolver","data":{"goal":"Inspect frozen evolution without publication","inputs":{"$cl_type":"t7"},"steps":[{"action":"evolver.state","args":{},"check":"observed","save":"state"}]},"key":"inspect","section":"procedures"}
P inspect():state=neyvia.evolver.state() C observed -- Inspect frozen evolution without publication
V P inspect -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evolver","data":{"constraints":"A Pareto member alone is insufficient. Read paired intervals, corrected alpha, hard gates and distinct panel IDs. Promotion changes only this workspace incumbent.","options":["inspect-receipt","retain-incumbent"],"question":"Did discovery and fresh reconfirmation both satisfy the same frozen promotion contract?"},"key":"promotion","section":"judge"}
J promotion inspect-receipt|retain-incumbent:"Did discovery and fresh reconfirmation both satisfy the same frozen promotion contract?" -- A Pareto member alone is insufficient. Read paired intervals, corrected alpha, hard gates and distinct panel IDs. Promotion changes only this workspace incumbent.
V J promotion -> human:operator why:"explicit choice required"
-- @record {"chapter":"evolver","data":{"failure":"Model sampling is called reproducibly seeded","recovery":"CLI has no sampling-seed control. Seeds control task inputs and pair order; provider sampling remains uncontrolled."},"key":"0","section":"pitfalls"}
X Model sampling is called reproducibly seeded -> CLI has no sampling-seed control. Seeds control task inputs and pair order; provider sampling remains uncontrolled.
-- @record {"chapter":"evolver","data":{"failure":"Token count called native Luna token count","recovery":"Denominator uses o200k_base reference tokenization; actual CLI input/output usage is recorded separately."},"key":"1","section":"pitfalls"}
X Token count called native Luna token count -> Denominator uses o200k_base reference tokenization; actual CLI input/output usage is recorded separately.
-- @record {"chapter":"evolver","data":{"failure":"CL source checks called visual quality","recovery":"This first domain measures frozen adherence plus compilation/markup correctness. Browser appearance is outside that measurement."},"key":"2","section":"pitfalls"}
X CL source checks called visual quality -> This first domain measures frozen adherence plus compilation/markup correctness. Browser appearance is outside that measurement.
-- @record {"chapter":"evolver","data":"Claude owns the Hill climbing screen and rendered lineage journey","key":"0","section":"frontier"}
F Claude owns the Hill climbing screen and rendered lineage journey
-- @record {"chapter":"evolver","data":"Field L5, other domains and unrestricted rewrite languages require separate adapters and evidence","key":"1","section":"frontier"}
F Field L5, other domains and unrestricted rewrite languages require separate adapters and evidence
-- @record {"chapter":"evolver","data":"Domain source: src/grant_agent/evolver_domains.py; engine: src/grant_agent/evolver_core.py; real runner: scripts/run_t13_evolution.py","key":"0","section":"guidance"}
M hill-climb "Domain source: src/grant_agent/evolver_domains.py; engine: src/grant_agent/evolver_core.py; real runner: scripts/run_t13_evolution.py" src:"authored manual" state:verified
L hill-climb.method v1 -- Executable hill-climb method: chronological mechanism and measured quality
-- @record {"chapter":"method","data":{"args":{"evidence":{"$input":"evidence"},"manual":"hill-climb","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"inputs":{"$cl_type":"t11"},"shape":{"$cl_type":"t12"},"tool":"neyvia.workflow.check"},"key":"adherence","section":"state"}
S hill-climb.adherence:json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"=neyvia.workflow.check(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens)
-- @record {"chapter":"method","data":{"effect":"Validate ordered workflow evidence","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.workflow.check","tool":"neyvia.workflow.check"},"key":"check","section":"actions"}
A neyvia.workflow.check(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" -- Validate ordered workflow evidence
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"method","data":{"effect":"Persist a validated workflow receipt under the selected task root","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t12"},"reversible":false,"schema":"neyvia.workflow.record","tool":"neyvia.workflow.record"},"key":"record","section":"actions"}
A neyvia.workflow.record(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" ! -- Persist a validated workflow receipt under the selected task root
C neyvia.workflow.record adhered:neyvia.workflow.check(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"method","data":{"args":{"evidence":{"$input":"evidence"},"manual":"hill-climb","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"expect":{"op":"eq","path":"accepted","value":true},"tool":"neyvia.workflow.check"},"key":"adhered","section":"checks"}
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"method","data":{"goal":"Verify defining workflow mechanism against host evidence and persist the acceptance receipt","inputs":{"$cl_type":"t11"},"steps":[{"action":"check","args":{"evidence":{"$input":"evidence"},"manual":"hill-climb","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"verified"},{"action":"record","args":{"evidence":{"$input":"evidence"},"manual":"hill-climb","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"recorded"}]},"key":"verify-and-record","section":"procedures"}
P verify-and-record(report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..):verified=neyvia.workflow.check(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered; recorded=neyvia.workflow.record(evidence:evidence manual:"hill-climb" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered -- Verify defining workflow mechanism against host evidence and persist the acceptance receipt
V P verify-and-record -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"method","data":{"constraints":"Use an independent frozen host quality judge; self-reported quality is not evidence.","options":["accept","revise"],"question":"Does the outcome satisfy the actual task, beyond recorded adherence?"},"key":"quality","section":"judge"}
J quality accept|revise:"Does the outcome satisfy the actual task, beyond recorded adherence?" -- Use an independent frozen host quality judge; self-reported quality is not evidence.
V J quality -> human:operator why:"explicit choice required"
-- @record {"chapter":"method","data":{"failure":"A model writes its own successful receipt, outcome score or token count","recovery":"The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail"},"key":"0","section":"pitfalls"}
X A model writes its own successful receipt, outcome score or token count -> The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail
-- @record {"chapter":"method","data":"Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.","key":"0","section":"frontier"}
F Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.
-- @record {"chapter":"method","data":"Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.","key":"1","section":"frontier"}
F Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.
-- @record {"chapter":"method","data":"Baseline first, before changing anything. Freeze the executable check, candidate task data and noise threshold.","key":"0","section":"guidance"}
M hill-climb "Baseline first, before changing anything. Freeze the executable check, candidate task data and noise threshold." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Change exactly one mechanism; measure the candidate with the same checkHash as baseline. Higher value means better; transform minimization metrics before judging.","key":"1","section":"guidance"}
M hill-climb "Change exactly one mechanism; measure the candidate with the same checkHash as baseline. Higher value means better; transform minimization metrics before judging." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Accept only measured value > baseline value + frozen noise. A tie or inconclusive run keeps the baseline. Link measurement to a real research-ledger receipt and state a stop rule.","key":"2","section":"guidance"}
M hill-climb "Accept only measured value > baseline value + frozen noise. A tie or inconclusive run keeps the baseline. Link measurement to a real research-ledger receipt and state a stop rule." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Report shape: {events:[{stage,data}],result:object}. Required chronological stages: baseline, change, measure, decision, log, stop","key":"3","section":"guidance"}
M hill-climb "Report shape: {events:[{stage,data}],result:object}. Required chronological stages: baseline, change, measure, decision, log, stop" src:"authored manual" state:verified
-- @record {"chapter":"method","data":"baseline{receipt}; change{candidate,changes:[one mechanism]}; measure{receipt}; decision{keep:boolean,reason}; log{receipt}; stop{rule}. Evidence measurement receipts have checkHash,value,noise; ledger receipt has kind=research-ledger,measurement=measure receipt ID.","key":"4","section":"guidance"}
M hill-climb "baseline{receipt}; change{candidate,changes:[one mechanism]}; measure{receipt}; decision{keep:boolean,reason}; log{receipt}; stop{rule}. Evidence measurement receipts have checkHash,value,noise; ledger receipt has kind=research-ledger,measurement=measure receipt ID." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified.","key":"5","section":"guidance"}
M hill-climb "Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below.","key":"6","section":"guidance"}
M hill-climb "Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below." src:"authored manual" state:verified
-- @record {"chapter":"method","data":"Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"baseline\",\"data\":{\"receipt\":\"baseline\"}},{\"stage\":\"change\",\"data\":{\"candidate\":\"one candidate name\",\"changes\":[\"one mechanism change\"]}},{\"stage\":\"measure\",\"data\":{\"receipt\":\"measurement\"}},{\"stage\":\"decision\",\"data\":{\"keep\":false,\"reason\":\"measurement does not beat baseline beyond noise\"}},{\"stage\":\"log\",\"data\":{\"receipt\":\"log\"}},{\"stage\":\"stop\",\"data\":{\"rule\":\"stop after this measured decision\"}}],\"result\":{\"decision\":\"task-specific actual answer\"}}","key":"7","section":"guidance"}
M hill-climb "Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"baseline\",\"data\":{\"receipt\":\"baseline\"}},{\"stage\":\"change\",\"data\":{\"candidate\":\"one candidate name\",\"changes\":[\"one mechanism change\"]}},{\"stage\":\"measure\",\"data\":{\"receipt\":\"measurement\"}},{\"stage\":\"decision\",\"data\":{\"keep\":false,\"reason\":\"measurement does not beat baseline beyond noise\"}},{\"stage\":\"log\",\"data\":{\"receipt\":\"log\"}},{\"stage\":\"stop\",\"data\":{\"rule\":\"stop after this measured decision\"}}],\"result\":{\"decision\":\"task-specific actual answer\"}}" src:"authored manual" state:verified
L hill-climb.overview v1 -- Frozen improvement receipts, history and measured Pareto tradeoffs
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t13"},"shape":{"$cl_type":"t14"},"tool":"neyvia.lab.state"},"key":"current","section":"state"}
S hill-climb.current:{records:json:"{\"type\":\"array\"}" competitions:json:"{\"type\":\"array\"}" automaticTraining:false automaticPromotion:false ..}=neyvia.lab.state()
-- @record {"chapter":"overview","data":{"effect":"Read latest 50 records and eligible measured Pareto sets; automaticTraining/Promotion and semanticQualityVerified remain false","pre":"Selected root improvement receipt store readable","returns":{"$cl_type":"t14"},"reversible":true,"schema":"neyvia.lab.state","tool":"neyvia.lab.state"},"key":"lab.state","section":"actions"}
A neyvia.lab.state() -> {records:json:"{\"type\":\"array\"}" competitions:json:"{\"type\":\"array\"}" automaticTraining:false automaticPromotion:false ..} ! -- Read latest 50 records and eligible measured Pareto sets; automaticTraining/Promotion and semanticQualityVerified remain false
C neyvia.lab.state no-promotion:neyvia.lab.state() .automaticPromotion == false
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"automaticPromotion","value":false},"tool":"neyvia.lab.state"},"key":"no-promotion","section":"checks"}
C neyvia.lab.state no-promotion:neyvia.lab.state() .automaticPromotion == false
-- @record {"chapter":"overview","data":{"goal":"Read frozen improvement receipts and decide whether comparisons support the requested objective","inputs":{"$cl_type":"t13"},"steps":[{"action":"lab.state","args":{},"check":"no-promotion","save":"lab"},{"judge":"candidate"}]},"key":"inspect-measurements","section":"procedures"}
P inspect-measurements():lab=neyvia.lab.state() C no-promotion; J candidate -- Read frozen improvement receipts and decide whether comparisons support the requested objective
V P inspect-measurements -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Compare same definitionHash, boundary and instrument key set. Pareto minimizes numeric values/meanMs/bytes; a frontier candidate is not a semantic winner. Reject invalid/nonfinite measurements; missing instruments prevent domination claims.","options":["compare","more-evidence"],"question":"Do these eligible candidates answer the improvement objective?"},"key":"candidate","section":"judge"}
J candidate compare|more-evidence:"Do these eligible candidates answer the improvement objective?" -- Compare same definitionHash, boundary and instrument key set. Pareto minimizes numeric values/meanMs/bytes; a frontier candidate is not a semantic winner. Reject invalid/nonfinite measurements; missing instruments prevent domination claims.
V J candidate -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Pareto winner is called model promotion","recovery":"Read automaticPromotion=false and semanticQualityVerified=false; perform separate matched behavioral evaluation"},"key":"0","section":"pitfalls"}
X Pareto winner is called model promotion -> Read automaticPromotion=false and semanticQualityVerified=false; perform separate matched behavioral evaluation
-- @record {"chapter":"overview","data":{"failure":"Candidates have different instrument key sets","recovery":"Do not claim domination across incomparable vectors"},"key":"1","section":"pitfalls"}
X Candidates have different instrument key sets -> Do not claim domination across incomparable vectors
-- @record {"chapter":"overview","data":{"failure":"Records lack finite numeric measurements or eligibility","recovery":"Exclude invalid vectors; collect missing evidence before comparison"},"key":"2","section":"pitfalls"}
X Records lack finite numeric measurements or eligibility -> Exclude invalid vectors; collect missing evidence before comparison
-- @record {"chapter":"overview","data":"Legacy Lab measurements remain separate from frozen domain-specific Evolver evaluations","key":"0","section":"frontier"}
F Legacy Lab measurements remain separate from frozen domain-specific Evolver evaluations
-- @record {"chapter":"overview","data":"Legacy competitions do not train or promote models","key":"1","section":"frontier"}
F Legacy competitions do not train or promote models
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_lab_board.py (vector, pareto, state); tests/test_neyvia_native_studios.py.","key":"0","section":"guidance"}
M hill-climb "Source: src/grant_agent/neyvia_lab_board.py (vector, pareto, state); tests/test_neyvia_native_studios.py." src:"authored manual" state:verified
L hill-climb.proofs-e-sv v1 -- PROOFS-e s-v host contracts and confined startup receipts
-- @record {"chapter":"proofs-e-sv","data":{"failure":"A passed scratch validator or receipt reducer is mistaken for provider, native release, NAS or rendered UI proof","recovery":"Read the adapter boundary and retain every unmapped case in the migration frontier"},"key":"0","section":"pitfalls"}
X A passed scratch validator or receipt reducer is mistaken for provider, native release, NAS or rendered UI proof -> Read the adapter boundary and retain every unmapped case in the migration frontier
-- @record {"chapter":"proofs-e-sv","data":"config/proofs/proofs-e-sv.json lists exact retained cases and the missing host/journey receipt; pending cases are never deletion authority.","key":"0","section":"frontier"}
F config/proofs/proofs-e-sv.json lists exact retained cases and the missing host/journey receipt; pending cases are never deletion authority.
-- @record {"chapter":"proofs-e-sv","data":"Production calls enforce these semantic contracts before returning. Startup entry: grant_agent.proofs_e_sv.self_check with a fresh confined root.","key":"0","section":"guidance"}
M hill-climb "Production calls enforce these semantic contracts before returning. Startup entry: grant_agent.proofs_e_sv.self_check with a fresh confined root." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-sv","data":"Run the registered proofs-e-sv area through neyvia.verify to obtain real scratch process, file, archive, language-compiler and local HTTP receipts.","key":"1","section":"guidance"}
M hill-climb "Run the registered proofs-e-sv area through neyvia.verify to obtain real scratch process, file, archive, language-compiler and local HTTP receipts." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-sv","data":"This chapter is separate from other area additions; sv.* contract IDs identify its host-owned guarantees.","key":"2","section":"guidance"}
M hill-climb "This chapter is separate from other area additions; sv.* contract IDs identify its host-owned guarantees." src:"authored manual" state:verified
L hill-climb.proofs-e-wz v1 -- PROOFS-e W-Z: live contracts and scratch self-checks
-- @record {"chapter":"proofs-e-wz","data":{"failure":"A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement","recovery":"Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion"},"key":"0","section":"pitfalls"}
X A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement -> Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion
-- @record {"chapter":"proofs-e-wz","data":"Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.","key":"0","section":"frontier"}
F Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.
-- @record {"chapter":"proofs-e-wz","data":"Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.","key":"1","section":"frontier"}
F Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.
-- @record {"chapter":"proofs-e-wz","data":"Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.","key":"2","section":"frontier"}
F Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.
-- @record {"chapter":"proofs-e-wz","data":"The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.","key":"3","section":"frontier"}
F The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.
-- @record {"chapter":"proofs-e-wz","data":"Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz","key":"0","section":"guidance"}
M hill-climb "Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action.","key":"1","section":"guidance"}
M hill-climb "Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection.","key":"2","section":"guidance"}
M hill-climb "Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection." src:"authored manual" state:verified
