CL 1
L hyperframes v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Agent-usable HyperFrames (HeyGen, Apache-2.0): lint, observe the timeline, render headless to MP4 with outcome contracts, snapshot frames and run the Studio privately."}},"clVersion":"1.1","id":"hyperframes","kind":"environment","schema":"neyvia.manual.v1","schemas":{"neyvia.mod.hyperframes.edit":"live_schema_9","neyvia.mod.hyperframes.lint":"live_schema_10","neyvia.mod.hyperframes.render":"live_schema_11","neyvia.mod.hyperframes.snapshot":"live_schema_12","neyvia.mod.hyperframes.studio":"live_schema_13","neyvia.mod.hyperframes.timeline":"live_schema_14","neyvia.mod.hyperframes.verify":"live_schema_15"},"tool_metadata":{"neyvia.mod.hyperframes.edit":{"mutability_class":"artifact_write"},"neyvia.mod.hyperframes.lint":{"mutability_class":"read"},"neyvia.mod.hyperframes.render":{"mutability_class":"artifact_write"},"neyvia.mod.hyperframes.snapshot":{"mutability_class":"artifact_write"},"neyvia.mod.hyperframes.studio":{"mutability_class":"external_action"},"neyvia.mod.hyperframes.timeline":{"mutability_class":"read"},"neyvia.mod.hyperframes.verify":{"mutability_class":"artifact_write"}}}
T live_schema_9 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"op\":{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"move\",\"trim\",\"split\",\"delete\",\"set\",\"duplicate\"]},\"ref\":{\"type\":\"string\",\"maxLength\":200},\"time\":{\"type\":\"number\"},\"options\":{\"type\":\"object\"}},\"required\":[\"project\",\"op\",\"ref\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"ref\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_10 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_11 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"out\":{\"type\":\"string\",\"maxLength\":4000},\"fps\":{\"type\":\"number\",\"minimum\":1,\"maximum\":120},\"quality\":{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"draft\",\"standard\",\"high\"]},\"expectedS\":{\"type\":\"number\"},\"workers\":{\"type\":\"number\",\"minimum\":1,\"maximum\":8}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_12 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"out\":{\"type\":\"string\",\"maxLength\":4000},\"at\":{\"type\":\"array\",\"items\":{\"type\":\"number\"}},\"frames\":{\"type\":\"number\",\"minimum\":1,\"maximum\":30}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_13 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000},\"action\":{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"start\",\"stop\",\"status\"]}},\"required\":[\"project\",\"action\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_14 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":4000}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_15 {..}
T t1{project:str#..4000}
T t2{project:str#..4000 out?:str#..4000 fps?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":120}" quality?:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"draft\",\"standard\",\"high\"]}" expectedS?:num workers?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":8}"}
T t3{project:str#..4000 op:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"move\",\"trim\",\"split\",\"delete\",\"set\",\"duplicate\"]}" ref:str#..200 time?:num options?:json:"{\"type\":\"object\"}"}
T t4{project:str#..4000 out?:str#..4000 at?:[num] frames?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":30}"}
T t5{project:str#..4000 action:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"start\",\"stop\",\"status\"]}"}
T t6{}
T t7 json:"{\"type\":\"object\"}"
T t8 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
L hyperframes.overview v1 -- Agent-usable HyperFrames (HeyGen, Apache-2.0): lint, observe the timeline, render headless to MP4 with outcome contracts, snapshot frames and run the Studio privately.
-- @record {"chapter":"overview","data":{"effect":"Lint a HyperFrames composition folder; returns the upstream findings.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":true,"schema":"neyvia.mod.hyperframes.lint","tool":"neyvia.mod.hyperframes.lint"},"key":"mod.hyperframes.lint","section":"actions"}
A neyvia.mod.hyperframes.lint(project:str#..4000) -> json:"{\"type\":\"object\"}" -- Lint a HyperFrames composition folder; returns the upstream findings.
F verify-mod-hyperframes-lint "No authored observer check is bound to neyvia.mod.hyperframes.lint" -> ask operator blocks:neyvia.mod.hyperframes.lint
-- @record {"chapter":"overview","data":{"effect":"Observe a composition's tracks and clips as a CL Scene.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":true,"schema":"neyvia.mod.hyperframes.timeline","tool":"neyvia.mod.hyperframes.timeline"},"key":"mod.hyperframes.timeline","section":"actions"}
A neyvia.mod.hyperframes.timeline(project:str#..4000) -> json:"{\"type\":\"object\"}" -- Observe a composition's tracks and clips as a CL Scene.
F verify-mod-hyperframes-timeline "No authored observer check is bound to neyvia.mod.hyperframes.timeline" -> ask operator blocks:neyvia.mod.hyperframes.timeline
-- @record {"chapter":"overview","data":{"effect":"Render a composition headless to MP4 and check duration, frame count, black/frozen frames and audio clipping on the file.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.hyperframes.render","tool":"neyvia.mod.hyperframes.render"},"key":"mod.hyperframes.render","section":"actions"}
A neyvia.mod.hyperframes.render(project:str#..4000 out?:str#..4000 fps?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":120}" quality?:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"draft\",\"standard\",\"high\"]}" expectedS?:num workers?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":8}") -> json:"{\"type\":\"object\"}" ! -- Render a composition headless to MP4 and check duration, frame count, black/frozen frames and audio clipping on the file.
F verify-mod-hyperframes-render "No authored observer check is bound to neyvia.mod.hyperframes.render" -> ask operator blocks:neyvia.mod.hyperframes.render
-- @record {"chapter":"overview","data":{"effect":"One upstream timeline edit (move, trim, split, delete, set, duplicate) on a clip ref, then re-observe the timeline.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.hyperframes.edit","tool":"neyvia.mod.hyperframes.edit"},"key":"mod.hyperframes.edit","section":"actions"}
A neyvia.mod.hyperframes.edit(project:str#..4000 op:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"move\",\"trim\",\"split\",\"delete\",\"set\",\"duplicate\"]}" ref:str#..200 time?:num options?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- One upstream timeline edit (move, trim, split, delete, set, duplicate) on a clip ref, then re-observe the timeline.
F verify-mod-hyperframes-edit "No authored observer check is bound to neyvia.mod.hyperframes.edit" -> ask operator blocks:neyvia.mod.hyperframes.edit
-- @record {"chapter":"overview","data":{"effect":"Capture exact frames as PNG at given times.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.hyperframes.snapshot","tool":"neyvia.mod.hyperframes.snapshot"},"key":"mod.hyperframes.snapshot","section":"actions"}
A neyvia.mod.hyperframes.snapshot(project:str#..4000 out?:str#..4000 at?:[num] frames?:json:"{\"type\":\"number\",\"minimum\":1,\"maximum\":30}") -> json:"{\"type\":\"object\"}" ! -- Capture exact frames as PNG at given times.
F verify-mod-hyperframes-snapshot "No authored observer check is bound to neyvia.mod.hyperframes.snapshot" -> ask operator blocks:neyvia.mod.hyperframes.snapshot
-- @record {"chapter":"overview","data":{"effect":"Start, stop or read the HyperFrames Studio preview server for a project (127.0.0.1:49165, no browser window).","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object"},"reversible":false,"schema":"neyvia.mod.hyperframes.studio","tool":"neyvia.mod.hyperframes.studio"},"key":"mod.hyperframes.studio","section":"actions"}
A neyvia.mod.hyperframes.studio(project:str#..4000 action:json:"{\"type\":\"string\",\"maxLength\":4000,\"enum\":[\"start\",\"stop\",\"status\"]}") -> json:"{\"type\":\"object\"}" ! -- Start, stop or read the HyperFrames Studio preview server for a project (127.0.0.1:49165, no browser window).
F verify-mod-hyperframes-studio "No authored observer check is bound to neyvia.mod.hyperframes.studio" -> ask operator blocks:neyvia.mod.hyperframes.studio
-- @record {"chapter":"overview","data":{"effect":"Real round trip on a two-clip composition: render headless, then the outcome contracts.","pre":"Selected workspace; the mod is installed, enabled and its local tool is present","returns":{"type":"object","properties":{"passed":{"const":true}},"required":["passed"]},"reversible":false,"schema":"neyvia.mod.hyperframes.verify","tool":"neyvia.mod.hyperframes.verify"},"key":"mod.hyperframes.verify","section":"actions"}
A neyvia.mod.hyperframes.verify() -> {passed:true ..} ! -- Real round trip on a two-clip composition: render headless, then the outcome contracts.
F verify-mod-hyperframes-verify "No authored observer check is bound to neyvia.mod.hyperframes.verify" -> ask operator blocks:neyvia.mod.hyperframes.verify
-- @record {"chapter":"overview","data":{"goal":"Run the real round trip and check its outcome contracts","inputs":{"type":"object","properties":{},"additionalProperties":false},"steps":[{"action":"mod.hyperframes.verify","args":{},"save":"verified"}]},"key":"verify-hyperframes","section":"procedures"}
P verify-hyperframes(): verified=neyvia.mod.hyperframes.verify() -- Run the real round trip and check its outcome contracts
V P verify-hyperframes -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"The local tool is missing","recovery":"Build or point the NEYVIA_* path at it; the action refuses rather than downloading anything."},"key":"0","section":"pitfalls"}
X The local tool is missing -> Build or point the NEYVIA_* path at it; the action refuses rather than downloading anything.
-- @record {"chapter":"overview","data":{"failure":"A render exists but is wrong","recovery":"Read the outcome block (duration, frames, black/frozen runs, clipping); never call a render good from its exit code."},"key":"1","section":"pitfalls"}
X A render exists but is wrong -> Read the outcome block (duration, frames, black/frozen runs, clipping); never call a render good from its exit code.
-- @record {"chapter":"overview","data":"HyperFrames 0.8.138 cannot attach to an existing browser over CDP; it launches the local chrome-headless-shell with a throwaway profile. On Windows capture is screenshot mode, about 2-6 frames per second per render on a loaded machine.","key":"0","section":"frontier"}
F HyperFrames 0.8.138 cannot attach to an existing browser over CDP; it launches the local chrome-headless-shell with a throwaway profile. On Windows capture is screenshot mode, about 2-6 frames per second per render on a loaded machine.
-- @record {"chapter":"overview","data":"Adapted, not forked: every action runs the unmodified upstream program. HyperFrames by HeyGen, Apache-2.0, https://github.com/heygen-com/hyperframes.","key":"1","section":"frontier"}
F Adapted, not forked: every action runs the unmodified upstream program. HyperFrames by HeyGen, Apache-2.0, https://github.com/heygen-com/hyperframes.
-- @record {"chapter":"overview","data":"Compositions are HTML: clips are elements with data-start, data-duration and data-track-index; one paused GSAP timeline is registered at window.__timelines[composition-id].","key":"0","section":"guidance"}
M hyperframes "Compositions are HTML: clips are elements with data-start, data-duration and data-track-index; one paused GSAP timeline is registered at window.__timelines[composition-id]." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Observe with mod.hyperframes.timeline, change the HTML, lint, then render; read the outcome block before calling a render good.","key":"1","section":"guidance"}
M hyperframes "Observe with mod.hyperframes.timeline, change the HTML, lint, then render; read the outcome block before calling a render good." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Open the visual editor through the HyperFrames Studio app; it embeds the Studio served on loopback.","key":"2","section":"guidance"}
M hyperframes "Open the visual editor through the HyperFrames Studio app; it embeds the Studio served on loopback." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Installs switched off from Marketplace > Apps & mods; read this manual and the declared permissions, then enable it.","key":"3","section":"guidance"}
M hyperframes "Installs switched off from Marketplace > Apps & mods; read this manual and the declared permissions, then enable it." src:"authored manual" state:verified
