CL 1
L image-studio v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Real pixel edits, protected regions, export and explicit provider generation"},"proofs-c-image-frontend":{"title":"PROOFS-c: image composition and provider model contracts"}},"clVersion":"1.1","id":"image-studio","kind":"environment","proofs":{"area":"proofs-c-frontend"},"schema":"neyvia.manual.v1","schemas":{"neyvia.image.composite":"t1","neyvia.image.crop":"t2","neyvia.image.export":"t3","neyvia.image.generate":"t4","neyvia.image.open":"t5","neyvia.image.resize":"t6","neyvia.image.state":"t7","rel_view_state":"t7"},"tool_metadata":{"neyvia.image.composite":{"mutability_class":"artifact_write"},"neyvia.image.crop":{"mutability_class":"artifact_write"},"neyvia.image.export":{"mutability_class":"artifact_write"},"neyvia.image.generate":{"mutability_class":"external_action"},"neyvia.image.open":{"mutability_class":"none"},"neyvia.image.resize":{"mutability_class":"artifact_write"},"neyvia.image.state":{"mutability_class":"read"},"neyvia.view.state":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:projectToProviderPayload -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Provider payload preserves canvas, selection, prompt intent, layer roles and rounded geometry; only visible layers are counted","id":"image.payload.geometry","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:createLayerFromSelection -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Selection becomes one editable selected shape with rounded geometry, positive extent and nonnegative feather","id":"image.layers.selection","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:updateLayerInProject -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"A patch affects only its addressed layer and preserves the other layers","id":"image.layers.update","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:removeLayerFromProject -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Deletion preserves at least one layer and selects the last survivor when removing the selected layer","id":"image.layers.delete","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:setFocusedHistoryItem -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Only an existing retained session can become focused; its annotations replace the overlay","id":"image.history.focus","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:updateFocusedHistoryAnnotations -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Overlay changes persist on the focused history session and preserve other sessions","id":"image.history.annotations","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:createOpsThreadForFocusedHistory -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"History, overlay and one idempotent issue thread share the receipt/request proof handle","id":"image.history.thread","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:buildKeyboardTraversalAnnouncement -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Scope/edge jumps announce both scoped positions; focus announces the destination","id":"image.keyboard.announcement","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:appendKeyboardJumpTrail -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Recent traversal trail is bounded, retains newest records, and carries scope/reason/time","id":"image.keyboard.trail","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:formatKeyboardJumpTrailEntry -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Trail entry shows its traversal text with a local clock, or an explicit recent fallback for invalid time","id":"image.keyboard.entry","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:formatKeyboardJumpTrailTooltip -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Traversal tooltip preserves scope/reason, full local time when valid, and announcement","id":"image.keyboard.tooltip","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imageProviderAdapters.js:registerImageProviderAdapter -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Registered adapter has its trimmed unique identity and callable transport","id":"image.provider.adapter","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imageProviderAdapters.js:requestProviderOperation -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Every available, blocked or draft operation has a traceable request, timing, handoff and prompt receipt; nonavailable operations preserve failure evidence","id":"image.provider.receipt","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imageProviderAdapters.js:applyProviderResult -> checkedImageAction","web/src/neyvia/imagePlaygroundContracts.js:checkedImageAction"],"claim":"Provider application preserves receipt/artifact/timing/handoff and annotation proof links, while draft results never masquerade as persisted sessions","id":"image.provider.history","impact":["Image composition, provider dispatch, receipts, annotations and keyboard review"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imagePlaygroundState.js:module initialization -> checkImagePromptPresets","web/src/neyvia/imagePlaygroundContracts.js:checkImagePromptPresets"],"claim":"Stable disciplined UI presets retain their composition guidance and bounded strengths","id":"image.prompt.presets","impact":["Image prompt presets"],"phase":"invariant"}
-- @proof {"checkedAt":["src/grant_agent/neyvia_image_generate.py:generate_image","web/src/neyvia/imageProviderAdapters.js:IMAGE_REQUEST_DEADLINE_MS"],"claim":"Generation never outlives its request: the backend stops Codex after 300 seconds and the UI gives up at 330, both ending in a plain failed result","id":"image.generate.deadline","impact":["Image generation, provider dispatch, receipts, queue and library"],"phase":"post"}
-- @proof {"checkedAt":["src/grant_agent/neyvia_image_generate.py:codex_cli_status"],"claim":"With no Codex CLI or no Codex sign-in the user gets a plain error naming the fix within seconds, and the job is recorded failed","id":"image.generate.preflight","impact":["Image generation, provider dispatch, receipts, queue and library"],"phase":"post"}
-- @proof {"checkedAt":["src/grant_agent/neyvia_image_generate.py:sweep_stale_jobs","web/src/neyvia/imagePlaygroundState.js:settleStaleHistoryItem"],"claim":"A generation job is always done or failed: stale running jobs from an earlier backend session are swept to failed","id":"image.generate.job-settled","impact":["Image generation, provider dispatch, receipts, queue and library"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/imageProviderAdapters.js:buildQueueTimeline","scripts/p22_release_models.mjs"],"claim":"A failed request does not time-stamp the generating, artifact or handoff stages it never reached","id":"image.queue.failed-timeline","impact":["Image generation, provider dispatch, receipts, queue and library"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/ImagePlayground.jsx:ArtifactThumb","scripts/p22_release_dom.mjs"],"claim":"A library image whose file is missing shows a labelled placeholder instead of a broken image","id":"image.library.missing-file","impact":["Image generation, provider dispatch, receipts, queue and library"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"edit\":{\"type\":\"string\"},\"region\":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"integer\",\"minimum\":0},\"y\":{\"type\":\"integer\",\"minimum\":0},\"width\":{\"type\":\"integer\",\"minimum\":1},\"height\":{\"type\":\"integer\",\"minimum\":1}},\"required\":[\"x\",\"y\",\"width\",\"height\"]}},\"required\":[\"edit\",\"region\"],\"allOf\":[{\"properties\":{\"edit\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2{region:{x:0.. y:0.. width:1.. height:1.. ..} ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"requestId\":{\"type\":\"string\"},\"request\":{\"type\":\"object\"}},\"required\":[\"requestId\",\"request\"],\"allOf\":[{\"properties\":{\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"source\":{\"type\":\"string\"}},\"required\":[\"source\"],\"allOf\":[{\"properties\":{\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{width:1.. height:1.. ..}
T t7{..}
T t8{}
T t9{state:json:"{\"type\":[\"object\",\"null\"]}" requested:json:"{\"type\":[\"object\",\"null\"]}" generation:json:"{\"type\":\"object\"}" ..}
T t10 json:"{\"type\":\"object\"}"
T t11{source:str width:int}
T t12{source:str x:0.. y:0.. width:1.. height:1..}
T t13{path:str}
T t14{edit:str region:{x:0.. y:0.. width:1.. height:1.. ..} ..}
T t15{path:str ..}
T t16{source:str ..}
T t17{assetId:str ..}
L image-studio.overview v1 -- Real pixel edits, protected regions, export and explicit provider generation
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.image.state"},"key":"current","section":"state"}
S image-studio.current:{state:json:"{\"type\":[\"object\",\"null\"]}" requested:json:"{\"type\":[\"object\",\"null\"]}" generation:json:"{\"type\":\"object\"}" ..}=neyvia.image.state()
-- @record {"chapter":"overview","data":{"effect":"Read observed state, requested asset and generation receipts; abandoned running generation is reported uncertain","pre":"Selected root bus readable; no image required","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.image.state","tool":"neyvia.image.state"},"key":"image.state","section":"actions"}
A neyvia.image.state() -> {state:json:"{\"type\":[\"object\",\"null\"]}" requested:json:"{\"type\":[\"object\",\"null\"]}" generation:json:"{\"type\":\"object\"}" ..} -- Read observed state, requested asset and generation receipts; abandoned running generation is reported uncertain
C neyvia.image.state crop-height:neyvia.image.state() .requested.dimensions.height == height
C neyvia.image.state preview-ready:neyvia.image.state() .state.status == "ready"
C neyvia.image.state preview-fresh:neyvia.image.state() .state.fresh == true
C neyvia.image.state preview-asset:neyvia.image.state() .state.assetId == assetId
-- @record {"chapter":"overview","data":{"effect":"Composite edit into region, verify outside pixels unchanged, publish new PNG and parent hash","pre":"Requested source hash matches; contained integer region; edit is an allowed decodable image","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.image.composite","tool":"neyvia.image.composite"},"key":"image.composite","section":"actions"}
A neyvia.image.composite(edit:str region:{x:0.. y:0.. width:1.. height:1.. ..}) -> json:"{\"type\":\"object\"}" ! -- Composite edit into region, verify outside pixels unchanged, publish new PNG and parent hash
F verify-image-composite "No authored observer check is bound to neyvia.image.composite" -> ask operator blocks:neyvia.image.composite
-- @record {"chapter":"overview","data":{"effect":"Write cropped PNG artifact, publish it as requested asset, retain parentSha256","pre":"Requested asset exists and source SHA-256 still matches; integer positive rectangle contained in image","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.image.crop","tool":"neyvia.image.crop"},"key":"image.crop","section":"actions"}
A neyvia.image.crop(region:{x:0.. y:0.. width:1.. height:1.. ..}) -> json:"{\"type\":\"object\"}" ! -- Write cropped PNG artifact, publish it as requested asset, retain parentSha256
C neyvia.image.crop crop-width:neyvia.image.state() .requested.dimensions.width == width
-- @record {"chapter":"overview","data":{"effect":"Exclusively copy exact asset bytes to new file and verify SHA-256; parent-directory approval covers new exports","pre":"Requested source hash matches; absent allowed destination; owner grants image-export for destination parent","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.image.export","tool":"neyvia.image.export"},"key":"image.export","section":"actions"}
A neyvia.image.export(path:str) -> json:"{\"type\":\"object\"}" ! -- Exclusively copy exact asset bytes to new file and verify SHA-256; parent-directory approval covers new exports
C neyvia.image.export export-readable:neyvia.files.stat(path:path) .kind == "file"
-- @record {"chapter":"overview","data":{"effect":"Start one provider request asynchronously; exact ID retries return receipt, different payload refused; success publishes asset","pre":"Stable nonblank requestId and object request; exact fingerprint approval, idle generation worker, running backend and ready Codex subscription; paid fallback disabled","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.image.generate","tool":"neyvia.image.generate"},"key":"image.generate","section":"actions"}
A neyvia.image.generate(requestId:str request:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Start one provider request asynchronously; exact ID retries return receipt, different payload refused; success publishes asset
F verify-image-generate "No authored observer check is bound to neyvia.image.generate" -> ask operator blocks:neyvia.image.generate
-- @record {"chapter":"overview","data":{"effect":"Inspect pixels/hash, register asset and emit image.open; source unchanged and uiVerified=false","pre":"Existing decodable image inside workspace/repo/registered project, <=32 MiB and <=50 megapixels","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.image.open","tool":"neyvia.image.open"},"key":"image.open","section":"actions"}
A neyvia.image.open(source:str) -> json:"{\"type\":\"object\"}" -- Inspect pixels/hash, register asset and emit image.open; source unchanged and uiVerified=false
C neyvia.image.open source-width:neyvia.image.state() .requested.dimensions.width == width
-- @record {"chapter":"overview","data":{"effect":"Write LANCZOS-resized PNG and publish new requested asset; source unchanged","pre":"Requested asset exists and source hash matches; positive integer width/height with product <=50 million","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.image.resize","tool":"neyvia.image.resize"},"key":"image.resize","section":"actions"}
A neyvia.image.resize(width:1.. height:1..) -> json:"{\"type\":\"object\"}" ! -- Write LANCZOS-resized PNG and publish new requested asset; source unchanged
F verify-image-resize "No authored observer check is bound to neyvia.image.resize" -> ask operator blocks:neyvia.image.resize
-- @record {"chapter":"overview","data":{"effect":"Read current windows, ids, placements, mounted DOM geometry and delivered events.","pre":"The shell reports state after React commits; fresh=false means unavailable.","returns":{"$cl_type":"t10"},"reversible":true,"schema":"rel_view_state","tool":"neyvia.view.state"},"key":"view.state","section":"actions"}
A neyvia.view.state() -> json:"{\"type\":\"object\"}" -- Read current windows, ids, placements, mounted DOM geometry and delivered events.
C neyvia.view.state preview-shell-fresh:neyvia.view.state() .state.fresh == true
C neyvia.view.state preview-window-visible:matches(neyvia.view.state() .state.dom.windows {contains:{properties:{id:{const:"app:image-studio"} placement:{enum:["main" "side" "full"]} visible:{const:true}} required:["id" "visible" "placement"] type:"object"} type:"array"})
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"requested.dimensions.width","value":{"$input":"width"}},"tool":"neyvia.image.state"},"key":"source-width","section":"checks"}
C neyvia.image.state source-width:neyvia.image.state() .requested.dimensions.width == width
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"requested.dimensions.width","value":{"$input":"width"}},"tool":"neyvia.image.state"},"key":"crop-width","section":"checks"}
C neyvia.image.state crop-width:neyvia.image.state() .requested.dimensions.width == width
-- @record {"chapter":"overview","data":{"args":{"path":{"$path":"path"}},"expect":{"op":"eq","path":"kind","value":"file"},"tool":"neyvia.files.stat"},"key":"export-readable","section":"checks"}
C neyvia.files.stat export-readable:neyvia.files.stat(path:path) .kind == "file"
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"requested.dimensions.height","value":{"$input":"height"}},"tool":"neyvia.image.state"},"key":"crop-height","section":"checks"}
C neyvia.image.state crop-height:neyvia.image.state() .requested.dimensions.height == height
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.status","value":"ready"},"tool":"neyvia.image.state"},"key":"preview-ready","section":"checks"}
C neyvia.image.state preview-ready:neyvia.image.state() .state.status == "ready"
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.assetId","value":{"$input":"assetId"}},"tool":"neyvia.image.state"},"key":"preview-asset","section":"checks"}
C neyvia.image.state preview-asset:neyvia.image.state() .state.assetId == assetId
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.fresh","value":true},"tool":"neyvia.view.state"},"key":"preview-shell-fresh","section":"checks"}
C neyvia.view.state preview-shell-fresh:neyvia.view.state() .state.fresh == true
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"schema","path":"state.dom.windows","schema":{"contains":{"properties":{"id":{"const":"app:image-studio"},"placement":{"enum":["main","side","full"]},"visible":{"const":true}},"required":["id","visible","placement"],"type":"object"},"type":"array"}},"tool":"neyvia.view.state"},"key":"preview-window-visible","section":"checks"}
C neyvia.view.state preview-window-visible:matches(neyvia.view.state() .state.dom.windows {contains:{properties:{id:{const:"app:image-studio"} placement:{enum:["main" "side" "full"]} visible:{const:true}} required:["id" "visible" "placement"] type:"object"} type:"array"})
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.fresh","value":true},"tool":"neyvia.image.state"},"key":"preview-fresh","section":"checks"}
C neyvia.image.state preview-fresh:neyvia.image.state() .state.fresh == true
-- @record {"chapter":"overview","data":{"goal":"Open source image and verify original width before editing","inputs":{"$cl_type":"t11"},"steps":[{"action":"image.open","args":{"source":{"$path":"source"}},"check":"source-width","save":"original"}]},"key":"open-inspect","section":"procedures"}
P open-inspect(source:str width:int):original=neyvia.image.open(source:source) C source-width -- Open source image and verify original width before editing
V P open-inspect -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Inspect source and proposed pixel rectangle, create new PNG and verify its requested width/height","inputs":{"$cl_type":"t12"},"steps":[{"action":"image.open","args":{"source":{"$path":"source"}},"save":"original"},{"judge":"composition"},{"action":"image.crop","args":{"region":{"height":{"$input":"height"},"width":{"$input":"width"},"x":{"$input":"x"},"y":{"$input":"y"}}},"check":"crop-width","save":"cropped","when":{"judge":"composition","option":"crop"}},{"action":"image.state","args":{},"check":"crop-height","save":"dimensions","when":{"judge":"composition","option":"crop"}}]},"key":"crop-for-composition","section":"procedures"}
P crop-for-composition(source:str x:0.. y:0.. width:1.. height:1..):original=neyvia.image.open(source:source); J composition=crop; cropped=neyvia.image.crop(region:{height:height width:width x:x y:y}) C crop-width; dimensions=neyvia.image.state() C crop-height -- Inspect source and proposed pixel rectangle, create new PNG and verify its requested width/height
V P crop-for-composition -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Read current asset, review destination and export without overwrite","inputs":{"$cl_type":"t13"},"steps":[{"action":"image.state","args":{},"save":"current"},{"judge":"export"},{"action":"image.export","args":{"path":{"$path":"path"}},"check":"export-readable","save":"exported","when":{"judge":"export","option":"export"}}]},"key":"export-reviewed-image","section":"procedures"}
P export-reviewed-image(path:str):current=neyvia.image.state(); J export=export; exported=neyvia.image.export(path:path) C export-readable -- Read current asset, review destination and export without overwrite
V P export-reviewed-image -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t14"},"steps":[{"action":"image.composite","args":{"edit":{"$input":"edit"},"region":{"$input":"region"}},"save":"effect"}]},"key":"verify-effect-image-composite","section":"procedures"}
P verify-effect-image-composite(edit:str region:{x:0.. y:0.. width:1.. height:1.. ..}):effect=neyvia.image.composite(edit:edit region:region) -- Verify the actual effect through fresh owning observers
V P verify-effect-image-composite -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t2"},"steps":[{"action":"image.crop","args":{"region":{"$input":"region"}},"save":"effect"}]},"key":"verify-effect-image-crop","section":"procedures"}
P verify-effect-image-crop(region:{x:0.. y:0.. width:1.. height:1.. ..}):effect=neyvia.image.crop(region:region) -- Verify the actual effect through fresh owning observers
V P verify-effect-image-crop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t15"},"steps":[{"action":"image.export","args":{"path":{"$input":"path"}},"save":"effect"}]},"key":"verify-effect-image-export","section":"procedures"}
P verify-effect-image-export(path:str):effect=neyvia.image.export(path:path) -- Verify the actual effect through fresh owning observers
V P verify-effect-image-export -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t16"},"steps":[{"action":"image.open","args":{"source":{"$input":"source"}},"save":"effect"}]},"key":"verify-effect-image-open","section":"procedures"}
P verify-effect-image-open(source:str):effect=neyvia.image.open(source:source) -- Verify the actual effect through fresh owning observers
V P verify-effect-image-open -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t6"},"steps":[{"action":"image.resize","args":{"height":{"$input":"height"},"width":{"$input":"width"}},"save":"effect"}]},"key":"verify-effect-image-resize","section":"procedures"}
P verify-effect-image-resize(width:1.. height:1..):effect=neyvia.image.resize(height:height width:width) -- Verify the actual effect through fresh owning observers
V P verify-effect-image-resize -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the exact decoded asset reported by Image Studio and its current visible shell window. Opening a file alone is not preview proof.","inputs":{"$cl_type":"t17"},"steps":[{"action":"image.state","args":{},"check":"preview-ready","save":"preview-ready"},{"action":"image.state","args":{},"check":"preview-fresh","save":"preview-fresh"},{"action":"image.state","args":{},"check":"preview-asset","save":"preview-asset"},{"action":"view.state","args":{},"check":"preview-shell-fresh","save":"preview-shell-fresh"},{"action":"view.state","args":{},"check":"preview-window-visible","save":"preview-window-visible"}]},"key":"verify-live-preview","section":"procedures"}
P verify-live-preview(assetId:str):preview-ready=neyvia.image.state() C preview-ready; preview-fresh=neyvia.image.state() C preview-fresh; preview-asset=neyvia.image.state() C preview-asset; preview-shell-fresh=neyvia.view.state() C preview-shell-fresh; preview-window-visible=neyvia.view.state() C preview-window-visible -- Verify the exact decoded asset reported by Image Studio and its current visible shell window. Opening a file alone is not preview proof.
V P verify-live-preview -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Use requested.dimensions; rectangle uses source pixels, not browser coordinates. Preserve source; review rendered crop before export. Cropping can discard context even when coordinates are valid.","options":["crop","leave"],"question":"Does the crop preserve the subject and intended context?"},"key":"composition","section":"judge"}
J composition crop|leave:"Does the crop preserve the subject and intended context?" -- Use requested.dimensions; rectangle uses source pixels, not browser coordinates. Preserve source; review rendered crop before export. Cropping can discard context even when coordinates are valid.
V J composition -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Destination must be absent inside allowed workspace/project and owner-approved; retain the original source. Backend export copies exact asset bytes.","options":["export","leave"],"question":"Is this reviewed image ready to save at the new destination?"},"key":"export","section":"judge"}
J export export|leave:"Is this reviewed image ready to save at the new destination?" -- Destination must be absent inside allowed workspace/project and owner-approved; retain the original source. Backend export copies exact asset bytes.
V J export -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Source changed after open","recovery":"Reopen original and recompute region; hash mismatch blocks edits"},"key":"0","section":"pitfalls"}
X Source changed after open -> Reopen original and recompute region; hash mismatch blocks edits
-- @record {"chapter":"overview","data":{"failure":"Crop exceeds dimensions","recovery":"Use integer pixel rectangle within requested width/height"},"key":"1","section":"pitfalls"}
X Crop exceeds dimensions -> Use integer pixel rectangle within requested width/height
-- @record {"chapter":"overview","data":{"failure":"Generation is running/busy/uncertain","recovery":"Observe image.state and saved provider artifact; same requestId replays, never use new ID just to retry uncertain work"},"key":"2","section":"pitfalls"}
X Generation is running/busy/uncertain -> Observe image.state and saved provider artifact; same requestId replays, never use new ID just to retry uncertain work
-- @record {"chapter":"overview","data":{"failure":"Export path already exists","recovery":"Select a new path; export never replaces files"},"key":"3","section":"pitfalls"}
X Export path already exists -> Select a new path; export never replaces files
-- @record {"chapter":"overview","data":{"failure":"A valid crop looks wrong","recovery":"Inspect new pixels at full size; dimension/hash checks cannot decide composition"},"key":"4","section":"pitfalls"}
X A valid crop looks wrong -> Inspect new pixels at full size; dimension/hash checks cannot decide composition
-- @record {"chapter":"overview","data":{"failure":"Gateway edit receipt wraps asset under toolResult","recovery":"Read image.state.requested for dimensions/hash instead of assuming the mutation envelope is flat."},"key":"5","section":"pitfalls"}
X Gateway edit receipt wraps asset under toolResult -> Read image.state.requested for dimensions/hash instead of assuming the mutation envelope is flat.
-- @record {"chapter":"overview","data":"Style, subject fidelity and browser-rendered appearance need human/model visual review","key":"0","section":"frontier"}
F Style, subject fidelity and browser-rendered appearance need human/model visual review
-- @record {"chapter":"overview","data":"Provider generation readiness and exact-request approval are separate from deterministic pixel edits","key":"1","section":"frontier"}
F Provider generation readiness and exact-request approval are separate from deterministic pixel edits
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_image_tools.py and neyvia_image_approval.py; tests/test_neyvia_native_studios.py.","key":"0","section":"guidance"}
M image-studio "Source: src/grant_agent/neyvia_image_tools.py and neyvia_image_approval.py; tests/test_neyvia_native_studios.py." src:"authored manual" state:verified
L image-studio.proofs-c-image-frontend v1 -- PROOFS-c: image composition and provider model contracts
-- @record {"chapter":"proofs-c-image-frontend","data":{"failure":"A passing model self-check is mistaken for remote generation or rendered UI proof","recovery":"Inspect the receipt boundary and run the actual application journey for its remaining frontier"},"key":"0","section":"pitfalls"}
X A passing model self-check is mistaken for remote generation or rendered UI proof -> Inspect the receipt boundary and run the actual application journey for its remaining frontier
-- @record {"chapter":"proofs-c-image-frontend","data":"Image UI route/default runtime wiring and rendered browser controls still need their actual user journeys","key":"0","section":"frontier"}
F Image UI route/default runtime wiring and rendered browser controls still need their actual user journeys
-- @record {"chapter":"proofs-c-image-frontend","data":"Historical Codex May-11 reference manifest was replaced by current May-13 imagegen reference; missing history alone does not establish dead code","key":"1","section":"frontier"}
F Historical Codex May-11 reference manifest was replaced by current May-13 imagegen reference; missing history alone does not establish dead code
-- @record {"chapter":"proofs-c-image-frontend","data":"Live review connected bridge, planner panels, proof-copy links, replay controls and project switcher remain rendered UI boundaries","key":"2","section":"frontier"}
F Live review connected bridge, planner panels, proof-copy links, replay controls and project switcher remain rendered UI boundaries
-- @record {"chapter":"proofs-c-image-frontend","data":"Mobile authenticated lazy loading, bootstrap refresh, empty phone indexes and one-session transcript hydration remain integration/UI boundaries","key":"3","section":"frontier"}
F Mobile authenticated lazy loading, bootstrap refresh, empty phone indexes and one-session transcript hydration remain integration/UI boundaries
-- @record {"chapter":"proofs-c-image-frontend","data":"SVG compositor is a real local registered provider; external remote image generation is not exercised","key":"4","section":"frontier"}
F SVG compositor is a real local registered provider; external remote image generation is not exercised
-- @record {"chapter":"proofs-c-image-frontend","data":"Startup entry: scripts/proofs-c-frontend.mjs --root <scratch>; config/proofs/proofs-c-frontend.json owns reviewed procedures and per-case coverage","key":"0","section":"guidance"}
M image-studio "Startup entry: scripts/proofs-c-frontend.mjs --root <scratch>; config/proofs/proofs-c-frontend.json owns reviewed procedures and per-case coverage" src:"authored manual" state:verified
-- @proof {"checkedAt":["grant_agent.proofs_image_studio_journey.self_check","grant_agent.neyvia_image_tools.call","grant_agent.neyvia_image_tools.inside","grant_agent.neyvia_image_tools.inspect","grant_agent.neyvia_image_tools.publish","grant_agent.visual_specifications.composite_region","grant_agent.neyvia_outputs.publish","grant_agent.ui_command_bus.UICommandBus.get","grant_agent.ui_command_bus.UICommandBus.put"],"claim":"Native Image Studio edits synthetic local pixels through crop, resize, composite and export; observers verify output dimensions, selected and preserved pixels, filenames and publication, while invalid rectangles and outside-root images are refused without replacing the requested asset","id":"p22.image-studio.pixel-edit-journey","impact":["Image Studio local crop, resize, composite and export","Image Studio protected input and requested-asset state"],"phase":"post"}
