CL 1
L inception v1 -- Authored executable manual
-- @manual {"chapters":{"release":{"title":"Pinned scratch Neyvia tests a candidate through T16 and T18"}},"clVersion":"1.1","id":"inception","kind":"environment","schema":"neyvia.manual.v1","schemas":{"neyvia.inception.inventory":"t1","neyvia.inception.report":"t1","terminal.exec":"t2"},"tool_metadata":{"neyvia.inception.inventory":{"mutability_class":"read"},"neyvia.inception.report":{"mutability_class":"read"},"terminal.exec":{"mutability_class":"external_action"}}}
T t1{..}
T t2{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t3 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t4 json:"{\"type\":\"object\"}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"stateRoot\":{\"type\":\"string\",\"enum\":[\".\"],\"default\":\".\"}},\"additionalProperties\":false}"
L inception.release v1 -- Pinned scratch Neyvia tests a candidate through T16 and T18
-- @record {"chapter":"release","data":{"args":{},"inputs":{"$cl_type":"t3"},"shape":{"$cl_type":"t4"},"tool":"neyvia.inception.inventory"},"key":"coverage","section":"state"}
S inception.coverage:json:"{\"type\":\"object\"}"=neyvia.inception.inventory()
-- @record {"chapter":"release","data":{"args":{},"inputs":{"$cl_type":"t3"},"shape":{"$cl_type":"t4"},"tool":"neyvia.inception.report"},"key":"last-run","section":"state"}
S inception.last-run:json:"{\"type\":\"object\"}"=neyvia.inception.report()
-- @record {"chapter":"release","data":{"effect":"Read every authoritative manual hash, procedure, input, judge and goal check","pre":"Selected candidate source is available","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.inception.inventory","tool":"neyvia.inception.inventory"},"key":"inventory","section":"actions"}
A neyvia.inception.inventory() -> json:"{\"type\":\"object\"}" -- Read every authoritative manual hash, procedure, input, judge and goal check
F verify-inventory "No authored observer check is bound to neyvia.inception.inventory" -> ask operator blocks:neyvia.inception.inventory
-- @record {"chapter":"release","data":{"effect":"Recheck source hashes and T16/T18 proof bytes before returning releaseGate","pre":"Run receipt may be absent; absence keeps releaseGate false","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.inception.report","tool":"neyvia.inception.report"},"key":"report","section":"actions"}
A neyvia.inception.report() -> json:"{\"type\":\"object\"}" -- Recheck source hashes and T16/T18 proof bytes before returning releaseGate
C neyvia.inception.report report-present:neyvia.inception.report() .available == true
-- @record {"chapter":"release","data":{"effect":"Run fresh source-bound C8 adapter admission and refusal checks, with the executable driver closure copied and hashed under the D run root.","pre":"Selected checkout is the isolated nx-int-final worktree; writes confined to D:/NeyviaRuns/INTN; no product, network, or browser action is made.","returns":{"$cl_type":"t4"},"reversible":true,"schema":"terminal.exec","tool":"terminal.exec"},"key":"adapter-preflight","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> json:"{\"type\":\"object\"}" ! -- Run fresh source-bound C8 adapter admission and refusal checks, with the executable driver closure copied and hashed under the D run root.
C terminal.exec adapter-preflight-passed:matches(workspace.read(path:"c8-preflight-result.json") {properties:{content:{pattern:"\"preflightStatus\": \"C8-ADAPTER-PREFLIGHT-PASSED\"" type:"string"}} required:["content"] type:"object"})
-- @record {"chapter":"release","data":{"args":{},"expect":{"op":"eq","path":"available","value":true},"tool":"neyvia.inception.report"},"key":"report-present","section":"checks"}
C neyvia.inception.report report-present:neyvia.inception.report() .available == true
-- @record {"chapter":"release","data":{"args":{"path":"c8-preflight-result.json"},"expect":{"op":"schema","path":"","schema":{"properties":{"content":{"pattern":"\"preflightStatus\": \"C8-ADAPTER-PREFLIGHT-PASSED\"","type":"string"}},"required":["content"],"type":"object"}},"tool":"workspace.read"},"key":"adapter-preflight-passed","section":"checks"}
C workspace.read adapter-preflight-passed:matches(workspace.read(path:"c8-preflight-result.json") {properties:{content:{pattern:"\"preflightStatus\": \"C8-ADAPTER-PREFLIGHT-PASSED\"" type:"string"}} required:["content"] type:"object"})
-- @record {"chapter":"release","data":{"goal":"Read the last report with freshly revalidated evidence; a blocked release is a valid reported outcome","inputs":{"$cl_type":"t3"},"steps":[{"action":"report","args":{},"check":"report-present","save":"release"}]},"key":"inspect-release","section":"procedures"}
P inspect-release():release=neyvia.inception.report() C report-present -- Read the last report with freshly revalidated evidence; a blocked release is a valid reported outcome
V P inspect-release -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"release","data":{"goal":"Execute fresh C8 source-hash, deferred-slot, scoped-input, escape and bounds admission/refusal checks.","inputs":{"$cl_type":"t5"},"steps":[{"action":"adapter-preflight","args":{"command":"import sys,json; from pathlib import Path; sys.path.insert(0,\"C:/Users/user/Projects/nx-int-final/scripts\"); import c8_journey; result=c8_journey.preflight_contract(\"D:/NeyviaRuns/INTN/c8-cl-preflight\"); Path(\"c8-preflight-result.json\").write_text(json.dumps(result),encoding=\"utf-8\"); print(result[\"preflightStatus\"])","cwd":{"$path":"stateRoot"},"maxOutputChars":50000,"shell":"python","timeoutMs":120000},"check":"adapter-preflight-passed","save":"receipt"}]},"key":"run-adapter-preflight","section":"procedures"}
P run-adapter-preflight(stateRoot?:json:"{\"type\":\"string\",\"enum\":[\".\"],\"default\":\".\"}"):receipt=terminal.exec(command:"import sys,json; from pathlib import Path; sys.path.insert(0,\"C:/Users/user/Projects/nx-int-final/scripts\"); import c8_journey; result=c8_journey.preflight_contract(\"D:/NeyviaRuns/INTN/c8-cl-preflight\"); Path(\"c8-preflight-result.json\").write_text(json.dumps(result),encoding=\"utf-8\"); print(result[\"preflightStatus\"])" cwd:stateRoot maxOutputChars:50000 shell:"python" timeoutMs:120000) C adapter-preflight-passed -- Execute fresh C8 source-hash, deferred-slot, scoped-input, escape and bounds admission/refusal checks.
V P run-adapter-preflight -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"release","data":{"failure":"Unbound procedure or missing device/provider","recovery":"Author a source-hash-bound disposable journey or supply its required host; never call the row passed"},"key":"0","section":"pitfalls"}
X Unbound procedure or missing device/provider -> Author a source-hash-bound disposable journey or supply its required host; never call the row passed
-- @record {"chapter":"release","data":{"failure":"T16 background action unavailable or user input observed","recovery":"Keep the journey blocked; do not silently front the window or replay uncertain effects"},"key":"1","section":"pitfalls"}
X T16 background action unavailable or user input observed -> Keep the journey blocked; do not silently front the window or replay uncertain effects
-- @record {"chapter":"release","data":{"failure":"Evidence bytes or manual source changed","recovery":"Run again against the new explicit candidate and pin"},"key":"2","section":"pitfalls"}
X Evidence bytes or manual source changed -> Run again against the new explicit candidate and pin
-- @record {"chapter":"release","data":"Only Notes write-and-pin and Settings read-preferences have authored UI bindings initially; all other rows remain release blockers","key":"0","section":"frontier"}
F Only Notes write-and-pin and Settings read-preferences have authored UI bindings initially; all other rows remain release blockers
-- @record {"chapter":"release","data":"The runner is exclusively headless until plan 20 C11 provides a verified isolated desktop; T18 browser proof never counts as T16 native proof","key":"1","section":"frontier"}
F The runner is exclusively headless until plan 20 C11 provides a verified isolated desktop; T18 browser proof never counts as T16 native proof
-- @record {"chapter":"release","data":"Devices, microphone, editor, external model and public release journeys need their actual hosts and separate authority","key":"2","section":"frontier"}
F Devices, microphone, editor, external model and public release journeys need their actual hosts and separate authority
-- @record {"chapter":"release","data":"Build into .agent_control/C8/build-headless with the local Vite runner and no dependency installation","key":"0","section":"guidance"}
M inception "Build into .agent_control/C8/build-headless with the local Vite runner and no dependency installation" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Run scripts/run_c8_inception.py --stable-ref <local commit> --stable-port 48754 --candidate-port 48755 --journey-port settings=48756 --workers 2 --build-dir .agent_control/C8/build-headless --state-root .agent_control/proofs/C8/report-c8c","key":"1","section":"guidance"}
M inception "Run scripts/run_c8_inception.py --stable-ref <local commit> --stable-port 48754 --candidate-port 48755 --journey-port settings=48756 --workers 2 --build-dir .agent_control/C8/build-headless --state-root .agent_control/proofs/C8/report-c8c" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Exit 0 means every row passed. Exit 2 means the report was saved and release remains blocked","key":"2","section":"guidance"}
M inception "Exit 0 means every row passed. Exit 2 means the report was saved and release remains blocked" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Stable source is archived from Git in a separate scratch directory. Services use separate explicit ports and disposable state. No credentials or NAS are read; no push, merge or public promotion occurs","key":"3","section":"guidance"}
M inception "Stable source is archived from Git in a separate scratch directory. Services use separate explicit ports and disposable state. No credentials or NAS are read; no push, merge or public promotion occurs" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Headless webPassed counts real rendered browser journeys; releaseGate stays false until every row has both T16 and T18 proof","key":"4","section":"guidance"}
M inception "Headless webPassed counts real rendered browser journeys; releaseGate stays false until every row has both T16 and T18 proof" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Parallel journeys use distinct explicitly supplied candidate ports and disposable state; no shared pane state between workers","key":"5","section":"guidance"}
M inception "Parallel journeys use distinct explicitly supplied candidate ports and disposable state; no shared pane state between workers" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"The Notes/Settings backend scope refuses all child-process and desktop launches; runtime/native checks outside that scope remain blocked","key":"6","section":"guidance"}
M inception "The Notes/Settings backend scope refuses all child-process and desktop launches; runtime/native checks outside that scope remain blocked" src:"authored manual" state:verified
-- @record {"chapter":"release","data":"Run scripts/prove_c8_report.py --port 48757 --report scripts/evidence/C8c.json to verify the real HTTP report tool and its failure paths","key":"7","section":"guidance"}
M inception "Run scripts/prove_c8_report.py --port 48757 --report scripts/evidence/C8c.json to verify the real HTTP report tool and its failure paths" src:"authored manual" state:verified
