CL 1
L laya-glance v1 -- Authored executable manual
-- @manual {"chapters":{"scene":{"title":"One Scene core: transcribe, predicates, instant examples and guarded improvement"}},"clVersion":"1.1","id":"laya-glance","kind":"environment","proofs":{"area":"scene-core"},"schema":"neyvia.manual.v1","schemas":{"neyvia.laya.glance":"t7","neyvia.laya.glance_contracts":"t6","neyvia.laya.glance_learn":"t9","neyvia.laya.glance_lesson":"t8","neyvia.laya.glance_proof":"t6","neyvia.laya.judge":"t3","neyvia.scene.episode":"t5","neyvia.scene.improve":"t4","neyvia.scene.transcribe":"t1","neyvia.scene.vocabulary":"t2"},"tool_metadata":{"neyvia.laya.glance":{"mutability_class":"read"},"neyvia.laya.glance_contracts":{"mutability_class":"read"},"neyvia.laya.glance_learn":{"mutability_class":"artifact_write"},"neyvia.laya.glance_lesson":{"mutability_class":"artifact_write"},"neyvia.laya.glance_proof":{"mutability_class":"read"},"neyvia.laya.judge":{"mutability_class":"read"},"neyvia.scene.episode":{"mutability_class":"artifact_write"},"neyvia.scene.improve":{"mutability_class":"external_action"},"neyvia.scene.transcribe":{"mutability_class":"read"},"neyvia.scene.vocabulary":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["grant_agent.scene_core.judge","grant_agent.laya_glance_contracts.observe"],"claim":"Actual before/after DOM and canvas observations bind typed defects to nodes and fixes.","id":"layag.scene-predicates","impact":["src/grant_agent/scene_core","src/grant_agent/laya_glance.py","src/grant_agent/perception_scene.js"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.laya_glance_proof.run","grant_agent.laya_glance.glance"],"claim":"From pixels alone, the black PDF page, see-through panels and clipped chips are caught on recorded before captures and absent on the after captures.","id":"layag.pixel-before-after","impact":["src/grant_agent/laya_glance_image.py","src/grant_agent/laya_glance.py","src/grant_agent/laya_glance_proof.py","manuals/cl/laya-glance.cl"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.scene_core.normalize","grant_agent.scene_core.check_predicates","grant_agent.scene_core.judge"],"claim":"An out-of-repo caller judges its own raw scene with its own predicates through the shared judge; predicates are validated data and never executed.","id":"core.sdk-seam","impact":["src/grant_agent/scene_core/__init__.py","src/grant_agent/neyvia_laya_capabilities.py","src/neyvia_sdk/client.py","packages/neyvia-sdk/index.js"],"phase":"invariant"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"object\"}},\"required\":[\"domain\",\"source\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"domain\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{scene:json:"{\"type\":\"object\"}" user?:str#..16000 domain?:str#..16000 predicates?:[json:"{\"type\":\"object\"}"]#..500 record?:bool ..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"domain\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"object\"},\"budget\":{\"type\":\"object\"}},\"required\":[\"domain\",\"source\",\"budget\"],\"allOf\":[{\"properties\":{\"domain\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"scene\":{\"type\":\"object\"},\"label\":{},\"reason\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"string\",\"maxLength\":16000},\"user\":{\"type\":\"string\",\"maxLength\":16000},\"layer\":{\"enum\":[\"corrective\",\"personal\"]}},\"required\":[\"scene\",\"label\",\"reason\",\"source\"],\"allOf\":[{\"properties\":{\"label\":{\"not\":{\"enum\":[null,\"\"]}},\"reason\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{..}
T t7{scene?:json:"{\"type\":\"object\"}" handle?:str#..16000 screenshot?:str#..16000 fuzzy?:bool ..}
T t8 json:"{\"type\":\"object\",\"properties\":{\"scene\":{\"type\":\"object\"},\"node\":{\"type\":\"string\",\"maxLength\":16000},\"predicate\":{\"enum\":[\"clipped-text\",\"raw-error\",\"encoded-path\",\"internal-id\",\"overlap\",\"unreadable-contrast\"]},\"label\":{\"enum\":[\"broken\",\"fine\"]},\"reason\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"scene\",\"node\",\"predicate\",\"label\",\"reason\",\"source\"],\"allOf\":[{\"properties\":{\"node\":{\"not\":{\"enum\":[\"\"]}},\"reason\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9 json:"{\"type\":\"object\",\"properties\":{\"screenshot\":{\"type\":\"string\",\"maxLength\":16000},\"label\":{\"enum\":[\"broken\",\"fine\"]},\"reason\":{\"type\":\"string\",\"maxLength\":16000},\"source\":{\"type\":\"string\",\"maxLength\":16000},\"surface\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"screenshot\",\"label\",\"reason\",\"source\"],\"allOf\":[{\"properties\":{\"screenshot\":{\"not\":{\"enum\":[\"\"]}},\"reason\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10 json:"{\"type\":\"object\"}"
T t11 json:"{\"type\":\"object\",\"properties\":{}}"
L laya-glance.scene v1 -- One Scene core: transcribe, predicates, instant examples and guarded improvement
-- @record {"chapter":"scene","data":{"effect":"Transcribe one domain source through its registered adapter into a shared CL Scene.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scene.transcribe","tool":"neyvia.scene.transcribe"},"key":"scene-transcribe","section":"actions"}
A neyvia.scene.transcribe(domain:str#..16000 source:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Transcribe one domain source through its registered adapter into a shared CL Scene.
F verify-scene-transcribe "No authored observer check is bound to neyvia.scene.transcribe" -> ask operator blocks:neyvia.scene.transcribe
-- @record {"chapter":"scene","data":{"effect":"Read the registered domain predicates and named fix patterns.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scene.vocabulary","tool":"neyvia.scene.vocabulary"},"key":"scene-vocabulary","section":"actions"}
A neyvia.scene.vocabulary(domain:str#..16000) -> json:"{\"type\":\"object\"}" -- Read the registered domain predicates and named fix patterns.
F verify-scene-vocabulary "No authored observer check is bound to neyvia.scene.vocabulary" -> ask operator blocks:neyvia.scene.vocabulary
-- @record {"chapter":"scene","data":{"effect":"Apply one shared predicate evaluator and instant episodic admission to a Scene. Out-of-repo callers may pass a raw scene with its domain and their own predicates (same shape, data only, never executed).","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.laya.judge","tool":"neyvia.laya.judge"},"key":"laya-judge","section":"actions"}
A neyvia.laya.judge(scene:json:"{\"type\":\"object\"}" user?:str#..16000 domain?:str#..16000 predicates?:[json:"{\"type\":\"object\"}"]#..500 record?:bool) -> json:"{\"type\":\"object\"}" ! -- Apply one shared predicate evaluator and instant episodic admission to a Scene. Out-of-repo callers may pass a raw scene with its domain and their own predicates (same shape, data only, never executed).
C neyvia.laya.judge external-predicates:matches(neyvia.laya.judge(domain:"sdk-probe" predicates:[{condition:{all:[{field:"kind" op:"eq" value:"position"} {field:"measurements.exposure" op:"gt" value:0.25}]} evidence:["measurements.exposure" "measurements.limit"] fix:{action:"config.reduce-size" arguments:{review:"human"}} id:"risk-limit-breach" severity:"error"} {condition:{field:"attributes.note" op:"eq" value:"0"} evidence:["attributes.note"] fix:{action:"review" arguments:{}} id:"code-as-data" severity:"error"} {condition:{all:[{field:"kind" op:"eq" value:"quote"} {field:"measurements.ageSeconds" op:"gt" value:60}]} evidence:["measurements.ageSeconds"] fix:{action:"data.refresh" arguments:{}} id:"stale-data" severity:"warning"}] record:false scene:{nodes:[{attributes:{symbol:"BTC-USD"} id:"book" kind:"position" measurements:{exposure:0.31 limit:0.25}} {attributes:{note:"__import__('os').system('calc')"} id:"feed" kind:"quote" measurements:{ageSeconds:2}}]}) .findings {items:{properties:{node:{const:"book"} predicate:{const:"risk-limit-breach"}} required:["predicate" "node"] type:"object"} maxItems:1 minItems:1 type:"array"})
-- @record {"chapter":"scene","data":{"effect":"Apply only explicitly budgeted reversible adapter fixes; trading is human review only.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scene.improve","tool":"neyvia.scene.improve"},"key":"scene-improve","section":"actions"}
A neyvia.scene.improve(domain:str#..16000 source:json:"{\"type\":\"object\"}" budget:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Apply only explicitly budgeted reversible adapter fixes; trading is human review only.
F verify-scene-improve "No authored observer check is bound to neyvia.scene.improve" -> ask operator blocks:neyvia.scene.improve
-- @record {"chapter":"scene","data":{"effect":"Write a labelled Scene episode immediately without training.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.scene.episode","tool":"neyvia.scene.episode"},"key":"scene-episode","section":"actions"}
A neyvia.scene.episode(scene:json:"{\"type\":\"object\"}" label:any reason:str#..16000 source:str#..16000 user?:str#..16000 layer?:"corrective"|"personal") -> json:"{\"type\":\"object\"}" ! -- Write a labelled Scene episode immediately without training.
F verify-scene-episode "No authored observer check is bound to neyvia.scene.episode" -> ask operator blocks:neyvia.scene.episode
-- @record {"chapter":"scene","data":{"effect":"Observe real headless DOM/canvas cases for the CL scene predicates.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.laya.glance_contracts","tool":"neyvia.laya.glance_contracts"},"key":"laya-glance_contracts","section":"actions"}
A neyvia.laya.glance_contracts() -> json:"{\"type\":\"object\"}" -- Observe real headless DOM/canvas cases for the CL scene predicates.
C neyvia.laya.glance_contracts live-predicates:neyvia.laya.glance_contracts() .passed == true
-- @record {"chapter":"scene","data":{"effect":"Apply the CL broken-UI vocabulary to a perception scene or immutable handle. Unknown facts request one model look.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.laya.glance","tool":"neyvia.laya.glance"},"key":"laya-glance","section":"actions"}
A neyvia.laya.glance(scene?:json:"{\"type\":\"object\"}" handle?:str#..16000 screenshot?:str#..16000 fuzzy?:bool) -> json:"{\"type\":\"object\"}" ! -- Apply the CL broken-UI vocabulary to a perception scene or immutable handle. Unknown facts request one model look.
F verify-laya-glance "No authored observer check is bound to neyvia.laya.glance" -> ask operator blocks:neyvia.laya.glance
-- @record {"chapter":"scene","data":{"effect":"Glance the recorded before/after fix captures from pixels alone: black PDF page, see-through panels, clipped composer chips.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.laya.glance_proof","tool":"neyvia.laya.glance_proof"},"key":"laya-glance_proof","section":"actions"}
A neyvia.laya.glance_proof() -> json:"{\"type\":\"object\"}" -- Glance the recorded before/after fix captures from pixels alone: black PDF page, see-through panels, clipped composer chips.
C neyvia.laya.glance_proof pixel-before-after:neyvia.laya.glance_proof() .passed == true
-- @record {"chapter":"scene","data":{"effect":"Teach one node instantly: broken adds the defect to similar text, fine suppresses a false alarm. No training.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.laya.glance_lesson","tool":"neyvia.laya.glance_lesson"},"key":"laya-glance_lesson","section":"actions"}
A neyvia.laya.glance_lesson(scene:json:"{\"type\":\"object\"}" node:str#..16000 predicate:"clipped-text"|"raw-error"|"encoded-path"|"internal-id"|"overlap"|"unreadable-contrast" label:"broken"|"fine" reason:str#..16000 source:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Teach one node instantly: broken adds the defect to similar text, fine suppresses a false alarm. No training.
F verify-laya-glance_lesson "No authored observer check is bound to neyvia.laya.glance_lesson" -> ask operator blocks:neyvia.laya.glance_lesson
-- @record {"chapter":"scene","data":{"effect":"Write one labelled screenshot episode; no training or head consolidation.","pre":"Registered adapter; source is observed data; mutations need caller authority","returns":{"$cl_type":"t10"},"reversible":false,"schema":"neyvia.laya.glance_learn","tool":"neyvia.laya.glance_learn"},"key":"laya-glance_learn","section":"actions"}
A neyvia.laya.glance_learn(screenshot:str#..16000 label:"broken"|"fine" reason:str#..16000 source:str#..16000 surface?:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Write one labelled screenshot episode; no training or head consolidation.
F verify-laya-glance_learn "No authored observer check is bound to neyvia.laya.glance_learn" -> ask operator blocks:neyvia.laya.glance_learn
-- @record {"chapter":"scene","data":{"args":{},"expect":{"op":"eq","path":"passed","value":true},"tool":"neyvia.laya.glance_contracts"},"key":"live-predicates","section":"checks"}
C neyvia.laya.glance_contracts live-predicates:neyvia.laya.glance_contracts() .passed == true
-- @record {"chapter":"scene","data":{"args":{},"expect":{"op":"eq","path":"passed","value":true},"tool":"neyvia.laya.glance_proof"},"key":"pixel-before-after","section":"checks"}
C neyvia.laya.glance_proof pixel-before-after:neyvia.laya.glance_proof() .passed == true
-- @record {"chapter":"scene","data":{"args":{"domain":"sdk-probe","predicates":[{"condition":{"all":[{"field":"kind","op":"eq","value":"position"},{"field":"measurements.exposure","op":"gt","value":0.25}]},"evidence":["measurements.exposure","measurements.limit"],"fix":{"action":"config.reduce-size","arguments":{"review":"human"}},"id":"risk-limit-breach","severity":"error"},{"condition":{"field":"attributes.note","op":"eq","value":"0"},"evidence":["attributes.note"],"fix":{"action":"review","arguments":{}},"id":"code-as-data","severity":"error"},{"condition":{"all":[{"field":"kind","op":"eq","value":"quote"},{"field":"measurements.ageSeconds","op":"gt","value":60}]},"evidence":["measurements.ageSeconds"],"fix":{"action":"data.refresh","arguments":{}},"id":"stale-data","severity":"warning"}],"record":false,"scene":{"nodes":[{"attributes":{"symbol":"BTC-USD"},"id":"book","kind":"position","measurements":{"exposure":0.31,"limit":0.25}},{"attributes":{"note":"__import__('os').system('calc')"},"id":"feed","kind":"quote","measurements":{"ageSeconds":2}}]}},"expect":{"op":"schema","path":"findings","schema":{"items":{"properties":{"node":{"const":"book"},"predicate":{"const":"risk-limit-breach"}},"required":["predicate","node"],"type":"object"},"maxItems":1,"minItems":1,"type":"array"}},"tool":"neyvia.laya.judge"},"key":"external-predicates","section":"checks"}
C neyvia.laya.judge external-predicates:matches(neyvia.laya.judge(domain:"sdk-probe" predicates:[{condition:{all:[{field:"kind" op:"eq" value:"position"} {field:"measurements.exposure" op:"gt" value:0.25}]} evidence:["measurements.exposure" "measurements.limit"] fix:{action:"config.reduce-size" arguments:{review:"human"}} id:"risk-limit-breach" severity:"error"} {condition:{field:"attributes.note" op:"eq" value:"0"} evidence:["attributes.note"] fix:{action:"review" arguments:{}} id:"code-as-data" severity:"error"} {condition:{all:[{field:"kind" op:"eq" value:"quote"} {field:"measurements.ageSeconds" op:"gt" value:60}]} evidence:["measurements.ageSeconds"] fix:{action:"data.refresh" arguments:{}} id:"stale-data" severity:"warning"}] record:false scene:{nodes:[{attributes:{symbol:"BTC-USD"} id:"book" kind:"position" measurements:{exposure:0.31 limit:0.25}} {attributes:{note:"__import__('os').system('calc')"} id:"feed" kind:"quote" measurements:{ageSeconds:2}}]}) .findings {items:{properties:{node:{const:"book"} predicate:{const:"risk-limit-breach"}} required:["predicate" "node"] type:"object"} maxItems:1 minItems:1 type:"array"})
-- @record {"chapter":"scene","data":{"goal":"Exercise actual headless DOM/canvas observations and compare before/after defect outcomes","inputs":{"$cl_type":"t11"},"steps":[{"action":"laya-glance_contracts","args":{},"check":"live-predicates","save":"observed"}]},"key":"prove-scenes","section":"procedures"}
P prove-scenes():observed=neyvia.laya.glance_contracts() C live-predicates -- Exercise actual headless DOM/canvas observations and compare before/after defect outcomes
V P prove-scenes -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scene","data":{"goal":"Glance the recorded before/after fix captures from pixels: the black PDF page, see-through panels and clipped chips are caught before and absent after","inputs":{"$cl_type":"t11"},"steps":[{"action":"laya-glance_proof","args":{},"check":"pixel-before-after","save":"proof"}]},"key":"prove-pixels","section":"procedures"}
P prove-pixels():proof=neyvia.laya.glance_proof() C pixel-before-after -- Glance the recorded before/after fix captures from pixels: the black PDF page, see-through panels and clipped chips are caught before and absent after
V P prove-pixels -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scene","data":{"goal":"Judge a caller-transcribed scene with caller-supplied predicates (the out-of-repo SDK seam): one exact finding, code-shaped text stays data","inputs":{"$cl_type":"t11"},"steps":[{"action":"laya-judge","args":{"domain":"sdk-probe","predicates":[{"condition":{"all":[{"field":"kind","op":"eq","value":"position"},{"field":"measurements.exposure","op":"gt","value":0.25}]},"evidence":["measurements.exposure","measurements.limit"],"fix":{"action":"config.reduce-size","arguments":{"review":"human"}},"id":"risk-limit-breach","severity":"error"},{"condition":{"field":"attributes.note","op":"eq","value":"0"},"evidence":["attributes.note"],"fix":{"action":"review","arguments":{}},"id":"code-as-data","severity":"error"},{"condition":{"all":[{"field":"kind","op":"eq","value":"quote"},{"field":"measurements.ageSeconds","op":"gt","value":60}]},"evidence":["measurements.ageSeconds"],"fix":{"action":"data.refresh","arguments":{}},"id":"stale-data","severity":"warning"}],"record":false,"scene":{"nodes":[{"attributes":{"symbol":"BTC-USD"},"id":"book","kind":"position","measurements":{"exposure":0.31,"limit":0.25}},{"attributes":{"note":"__import__('os').system('calc')"},"id":"feed","kind":"quote","measurements":{"ageSeconds":2}}]}},"check":"external-predicates","save":"verdict"}]},"key":"prove-sdk-seam","section":"procedures"}
P prove-sdk-seam():verdict=neyvia.laya.judge(domain:"sdk-probe" predicates:[{condition:{all:[{field:"kind" op:"eq" value:"position"} {field:"measurements.exposure" op:"gt" value:0.25}]} evidence:["measurements.exposure" "measurements.limit"] fix:{action:"config.reduce-size" arguments:{review:"human"}} id:"risk-limit-breach" severity:"error"} {condition:{field:"attributes.note" op:"eq" value:"0"} evidence:["attributes.note"] fix:{action:"review" arguments:{}} id:"code-as-data" severity:"error"} {condition:{all:[{field:"kind" op:"eq" value:"quote"} {field:"measurements.ageSeconds" op:"gt" value:60}]} evidence:["measurements.ageSeconds"] fix:{action:"data.refresh" arguments:{}} id:"stale-data" severity:"warning"}] record:false scene:{nodes:[{attributes:{symbol:"BTC-USD"} id:"book" kind:"position" measurements:{exposure:0.31 limit:0.25}} {attributes:{note:"__import__('os').system('calc')"} id:"feed" kind:"quote" measurements:{ageSeconds:2}}]}) C external-predicates -- Judge a caller-transcribed scene with caller-supplied predicates (the out-of-repo SDK seam): one exact finding, code-shaped text stays data
V P prove-sdk-seam -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scene","data":{"failure":"Missing style or geometry fact","recovery":"Preserve unknown and request one model look; never infer a clean screen."},"key":"0","section":"pitfalls"}
X Missing style or geometry fact -> Preserve unknown and request one model look; never infer a clean screen.
-- @record {"chapter":"scene","data":"UI fixes edit a web source tree, never a live window: CSS/token overrides computed from the finding and recorded library patches (laya-ui-fix.cl); improve keeps one only when a fresh private render shows strictly fewer findings with no guard regression. A perception scene or screenshot alone stays proposal-only. Engine adapters register separately.","key":"0","section":"frontier"}
F UI fixes edit a web source tree, never a live window: CSS/token overrides computed from the finding and recorded library patches (laya-ui-fix.cl); improve keeps one only when a fresh private render shows strictly fewer findings with no guard regression. A perception scene or screenshot alone stays proposal-only. Engine adapters register separately.
-- @record {"chapter":"scene","data":"Pixel-only recall is low for overlap (icon collisions), off-screen controls and phone peek sheets whose foreign text lies wholly inside the sheet; a clean pixel verdict is therefore never admitted and escalates to one model look.","key":"1","section":"frontier"}
F Pixel-only recall is low for overlap (icon collisions), off-screen controls and phone peek sheets whose foreign text lies wholly inside the sheet; a clean pixel verdict is therefore never admitted and escalates to one model look.
-- @record {"chapter":"scene","data":"A screenshot glance takes about 0.5 s (OCR ~0.2 s, pixel facts ~0.25 s, judge ~6 ms); the DOM+screenshot gate glance adds the render.","key":"2","section":"frontier"}
F A screenshot glance takes about 0.5 s (OCR ~0.2 s, pixel facts ~0.25 s, judge ~6 ms); the DOM+screenshot gate glance adds the render.
-- @record {"chapter":"scene","data":"Broken means a see-through surface, clipped text, raw error, encoded path or internal id, blank expected render, unintended overlap, unreadable contrast, or an off-screen control. Crisp predicates cite observed facts; fuzzy judgement uses instant episodes at nominal 0.95. No training runs or new heads.","key":"0","section":"guidance"}
M laya-glance "Broken means a see-through surface, clipped text, raw error, encoded path or internal id, blank expected render, unintended overlap, unreadable contrast, or an off-screen control. Crisp predicates cite observed facts; fuzzy judgement uses instant episodes at nominal 0.95. No training runs or new heads." src:"authored manual" state:verified
-- @record {"chapter":"scene","data":"Transcribe from the perception DOM graph when the app is live; a screenshot alone is read by local OCR plus measured pixel facts. With both, the screenshot cross-checks DOM coverage and fills contrast, and pixel findings count only where their calibrated precision reaches 0.95.","key":"1","section":"guidance"}
M laya-glance "Transcribe from the perception DOM graph when the app is live; a screenshot alone is read by local OCR plus measured pixel facts. With both, the screenshot cross-checks DOM coverage and fills contrast, and pixel findings count only where their calibrated precision reaches 0.95." src:"authored manual" state:verified
-- @record {"chapter":"scene","data":"Teach with laya.glance_lesson (one node, effective on the next glance) or laya.glance_learn (one labelled screenshot, updates calibration). Lessons apply only to text-intrinsic predicates; see-through, off-screen and blank renders depend on layout.","key":"2","section":"guidance"}
M laya-glance "Teach with laya.glance_lesson (one node, effective on the next glance) or laya.glance_learn (one labelled screenshot, updates calibration). Lessons apply only to text-intrinsic predicates; see-through, off-screen and blank renders depend on layout." src:"authored manual" state:verified

-- @bug {"type":"see-through","predicate":{"any":[{"all":[{"field":"facts.source","op":"eq","value":"dom"},{"field":"facts.surface","op":"eq","value":true},{"field":"facts.backgroundAlpha","op":"lt","value":1},{"field":"facts.behindText","op":"nonempty"}]},{"all":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"facts.crossesSurfaceEdge","op":"nonempty"}]}]},"fix":"Use an opaque surface background and a stacking context; keep underlying text outside the panel paint.","means":"A floating or peek surface lets text from underneath show through. DOM: translucent surface with text behind it. Pixels: a text line continues straight across a long surface boundary.","actions":["ui.css.stacking-layer","ui.css.opaque-surface"]}
-- @bug {"type":"clipped-text","predicate":{"any":[{"all":[{"field":"facts.source","op":"eq","value":"dom"},{"any":[{"field":"facts.clippedText","op":"eq","value":true},{"field":"facts.firstGlyphOutside","op":"eq","value":true}]}]},{"all":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"facts.spacedEllipsis","op":"eq","value":true}]}]},"fix":"Allow intrinsic label width, align the first glyph inside the clip, and truncate only at the end or wrap.","means":"Glyphs are cut by their box. DOM: text rects outside the clip or natural width beyond a nowrap overflow box. Pixels: a fragment followed by a detached ellipsis (the label was cut at the start and again at the end).","actions":["ui.css.align-start","ui.css.intrinsic-width","ui.css.shrink-text"]}
-- @bug {"type":"raw-error","predicate":{"all":[{"any":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"facts.userContent","op":"eq","value":false}]},{"field":"text","op":"matches","value":"Traceback \\(most recent call last\\)|(?-i:\\b[A-Z][A-Za-z]+(?:Error|Exception)\\b)|\\b(?:could|can)\\s?not be (?:read|checked|started|loaded|reached|opened)\\s*:|\\bapp-server\\b|\\b[\\w-]+\\s?\\.\\s?(?:exe|dll|py|ps1)\\b|(?:^|\\s)--[a-z][a-z-]{2,}\\b|\\bE(?:NOENT|CONNREFUSED|ACCES|PIPE)\\b|\\bexit code -?\\d+|\\bstatus(?: code)? [45]\\d\\d\\b|Unhandled (?:exception|rejection)|undefined is not|Cannot read propert|error sending request|\bhttps?://(?:127\\.0\\.0\\.1|localhost)\b"}]},"fix":"Show a plain-language failure and Retry; move the stack trace and process wording into details.","means":"Developer error wording is visible: exception class names, stack traces, executables or CLI flags, backend process names, \"could not be read: <technical reason>\"."}
-- @bug {"type":"encoded-path","predicate":{"all":[{"any":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"facts.userContent","op":"eq","value":false}]},{"field":"text","op":"matches","value":"^(?!\\s*PS\\b)(?!\\s*[a-z]\\s?:[^<>]*>\\s*$).*(?:raw\\?path=|\\?path=|%[0-9a-f]{2}[^%\\s]{0,40}%[0-9a-f]{2}|\\b[a-z]:[\\\\/][\\w .-]+[\\\\/]|(?:^|[\\s…(.])\\\\[\\w.-]{3,}|\\b(?:src|web|scripts|node_modules|users|appdata)[\\\\/][\\w-]{3,}|\\b[\\w-]+[\\\\/][\\w-]+\\s?\\.\\s?(?:py|js|jsx|ts|tsx|mjs|json|ps1|sh|exe|toml|ya?ml)\\b|[\\w-]*[_-][\\w-]*\\\\[\\w-]{2,}|\\b(?:127\\.0\\.0\\.1|localhost):\\d{2,})"}]},"fix":"Decode the display filename, keep transport URLs and absolute paths out of visible labels, show the base name with the path in a tooltip.","means":"A percent-encoded transport route or an absolute filesystem/repository path is user copy (terminal prompts excluded)."}
-- @bug {"type":"internal-id","predicate":{"all":[{"any":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"facts.userContent","op":"eq","value":false}]},{"field":"text","op":"matches","value":"\\b[a-z]+-null\\b|\\bnull\\b|\\bundefined\\b|(?-i:\\bNaN\\b)|\\[object Object\\]|(?<![\\\\/.])(?-i:\\b[a-z][a-z0-9]*_[a-z0-9]+(?:_[a-z0-9]+)*\\b)(?![\\\\/]|\\s?\\.\\s?[a-z]{2,4}\\b)|\\b[a-z]{3,}\\.[a-z]{3,}\\.(?!(?:com|org|net|io|dev|app|ai|fr|de|uk)\\b)[a-z_]{2,}\\b|\\b[a-z]+-[a-z]\\d+\\b|(?-i:\\b[A-Z]\\d+-[a-z]+-[a-z]+\\b)|(?-i:<[A-Z]\\d+-\\s?[a-z]+)|\\b[0-9a-f]{12,}\\b"}]},"fix":"Resolve a human-readable display name; keep internal identifiers in details.","means":"An internal identifier is user copy: null/undefined literals, snake_case or dotted tool ids, source-s1 style ids, hex ids."}
-- @bug {"type":"blank-render","predicate":{"all":[{"field":"facts.expectedContent","op":"eq","value":true},{"field":"facts.uniform","op":"eq","value":true}]},"fix":"Verify the render finished and drew nonuniform content; inspect document loading and canvas errors.","means":"A page or media frame that must show content is uniform. DOM: marked canvas/img is flat. Pixels: a fully visible portrait page rectangle with no text and no vertical detail."}
-- @bug {"type":"overlap","predicate":{"field":"facts.overlap","op":"nonempty"},"fix":"Separate sibling text bounds with gap, wrapping or correct stacking; preserve intended overlays.","means":"Two distinct text boxes are painted on top of each other."}
-- @bug {"type":"unreadable-contrast","predicate":{"any":[{"all":[{"field":"facts.source","op":"eq","value":"dom"},{"field":"text","op":"nonempty"},{"field":"facts.scrolledOut","op":"eq","value":false},{"field":"facts.placeholder","op":"eq","value":false},{"field":"facts.transparentText","op":"eq","value":false},{"field":"facts.contrastRatio","op":"lt","value":4.5}]},{"all":[{"field":"facts.source","op":"eq","value":"pixels"},{"field":"text","op":"matches","value":"(?:[a-z][^a-z]*){4}"},{"field":"bounds.h","op":"ge","value":8},{"field":"facts.contrastRatio","op":"lt","value":2.15}]}]},"fix":"Choose foreground and composited background tokens with at least 4.5:1 contrast.","means":"Text colour is too close to its painted background. DOM: computed or pixel-proven colours below 4.5:1 for visible, non-placeholder text. Pixels: a word-sized line whose measured ink against its surround is below 2.15:1 (anti-aliasing lowers pixel contrast)."}
-- @bug {"type":"off-screen-control","predicate":{"field":"facts.offScreenControl","op":"eq","value":true},"fix":"Keep controls within the viewport or expose them through scrolling or an overflow menu.","means":"A control or its label is cut by the viewport edge."}
