CL 1
L laya-3d v1 -- Native 3D adapters for the shared Scene core; no training
-- @proof {"id":"laya.frozen-cpu-floor","claim":"Default System-1 transformer retains at least 138/231 on JevBench dataset dc3995d8ae1e2fc8e81ce38431add509eb8bb39b85aadfd0c7c32079382dde51, all 93 retained value/probability outputs unchanged and layout 48/48. The floor runner exits nonzero on regression. Live browser calls alone use the admitted g3-c2 runtime and retain verified-episode confidence semantics.","checkedAt":["scripts/laya3d_regression.py:admission","grant_agent.laya_app_service.main","grant_agent.laya_service.browser_decide"],"impact":["frozen System-1 default","browser.decide/page_done","release floor exit status"],"phase":"post"}
A scene.transcribe(domain:str, source:object) -> scene -- Exact private game-dev Edit session; native facts
A laya.judge(scene:object) -> verdict -- Shared crisp predicates and scoped instant episodes
A scene.improve(domain:str, source:object, budget:object) -> receipt -- Shared strict finding reduction and guarded metrics; restore rejected revisions
P inspect(domain, source): scene.transcribe(domain, source)
P upgrade(domain, source, budget): scene.improve(domain, source, budget)
P image-to-model(source, budget): scene.improve("laya3d", source, budget)
A shape.primitive(args:object) -> mesh -- box sphere cylinder cone
A shape.extrude(args:object) -> mesh -- observed outline loops with holes; declared depth
A shape.lathe(args:object) -> mesh -- radial profile around Z
A shape.sweep(args:object) -> mesh -- elliptical cross sections with capped ends
A shape.boolean(args:object) -> mesh -- exact union difference intersection
A shape.mirror(args:object) -> mesh -- native axis mirror
A shape.bevel(args:object) -> mesh -- bounded bevel
A shape.subdivide(args:object) -> mesh -- bounded native subdivision
A shape.displace(args:object) -> mesh -- provided depth image as UV displacement; eyes only
A shape.visual_hull(args:object) -> mesh -- carve bounds with observed masks through fitted weak-perspective cameras (hull_math)
A shape.smooth(args:object) -> mesh -- voxel remesh at hull pitch plus bounded relaxation
A shape.project_texture(args:object) -> mesh -- per-face source-view colour through the fitted cameras; occlusion not modelled; alpha never hides geometry errors
-- @predicate {"id":"worst-view-outline-below-50","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.5}]},"severity":"error","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-60","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.6}]},"severity":"error","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-70","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.7}]},"severity":"error","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-80","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.8}]},"severity":"error","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-85","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.85}]},"severity":"warning","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-90","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.9}]},"severity":"warning","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"worst-view-outline-below-95","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMin","op":"lt","value":0.95}]},"severity":"warning","evidence":["measurements.outlineIoUMin"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-50","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.5}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-52","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.52}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-54","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.54}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-56","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.56}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-58","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.58}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-60","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.6}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-62","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.62}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-64","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.64}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-66","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.66}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-68","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.68}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-70","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.7}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-72","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.72}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-74","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.74}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-76","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.76}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-78","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.78}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-80","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.8}]},"severity":"error","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-82","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.82}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-84","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.84}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-86","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.86}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-88","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.88}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-90","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.9}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-92","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.92}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-94","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.94}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-outline-below-96","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.outlineIoUMean","op":"lt","value":0.96}]},"severity":"warning","evidence":["measurements.outlineIoUMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-30","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.3}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-20","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.2}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-15","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.15}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-12","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.12}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-10","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.1}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-08","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.08}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-06","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.06}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-colour-above-05","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.colourErrorMean","op":"gt","value":0.05}]},"severity":"warning","evidence":["measurements.colourErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-extent-above-30","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.extentErrorMean","op":"gt","value":0.3}]},"severity":"warning","evidence":["measurements.extentErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-extent-above-20","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.extentErrorMean","op":"gt","value":0.2}]},"severity":"warning","evidence":["measurements.extentErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-extent-above-15","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.extentErrorMean","op":"gt","value":0.15}]},"severity":"warning","evidence":["measurements.extentErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-extent-above-10","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.extentErrorMean","op":"gt","value":0.1}]},"severity":"warning","evidence":["measurements.extentErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"mean-extent-above-05","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.extentErrorMean","op":"gt","value":0.05}]},"severity":"warning","evidence":["measurements.extentErrorMean"],"fix":{"action":"shape.refit","arguments":{}}}
-- @predicate {"id":"part-mismatch","domains":["laya3d"],"condition":{"all":[{"field":"kind","op":"eq","value":"shape-model"},{"field":"measurements.partMatchMin","op":"lt","value":1}]},"severity":"warning","evidence":["measurements.partMatchMin"],"fix":{"action":"shape.refit","arguments":{}}}
C laya3d.verify precision: proof.precision == 1 -- block labelled native defect predictions contain no false positives
C laya3d.verify recall: proof.recall == 1 -- block labelled supported defects are found
C laya3d.verify rollback: proof.rollback == true -- block silhouette regression restores exact geometry
C laya3d.verify improvement: proof.improved > 0 -- block actual shared-core fixes remove findings
C laya3d.verify silhouette: proof.silhouettePreserved == true -- block canonical mask IoU cannot decrease
C laya3d.verify episode: proof.episodes > 0 -- block shared laya_instant receives outcome episodes
C laya3d.verify training: proof.training == false -- block no fitting or consolidation for scene domains
J intent closed|open: "Is this intended to be a closed surface? Open surfaces are not holes by default."
J reference source|parent: "Are masks aligned to the source image in the same orthographic cameras? Parent masks prove preservation only."
F Topology flow, semantic floaters, artistic lighting and unaligned source-image fidelity need independently labelled intent; unknown is never clean.
F UV coverage is mapped surface fraction, stretch is triangle edge anisotropy, and UV area sum is not overlap-free occupancy.
F Texture upscale is native resampling, not recovered high-frequency detail. Roblox execution requires an installed Studio; until then its observer is unexecuted code and no Roblox fact is claimed.
F Godot and Unity apply only engine.scale automatically; missing-collider and broken-reference stay review findings because a collider shape or a reference target is authored intent.
F A floater predicate counts small disconnected surface components, not isolated duplicate points; looseVertices is reported separately.
F Image generation requires scene.improve authorization. scene.transcribe(modelPath) observes the live native program; it never replaces geometry. Refitting uses each supplied view for its facing texture projection and cannot waive any view guard.
M API "scene_core.Adapter transcribe/vocabulary/fixes/checkpoint/restore; shared scene_core.judge and improve own all decisions. Source includes sessionId, domain, targets, renders=true. Budget must guard silhouette_quality:min for Blender." src:"plan 23" state:verified
-- @predicate {"id":"duplicate-vertices","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"measurements.duplicateVertices","op":"gt","value":0}]},"severity":"error","evidence":["measurements.duplicateVertices"],"fix":{"action":"mesh.merge","arguments":{"distance":0.000001}}}
-- @predicate {"id":"holes","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.closedSurface","op":"eq","value":true},{"field":"measurements.boundaryEdges","op":"gt","value":0}]},"severity":"error","evidence":["measurements.boundaryEdges"],"fix":{"action":"mesh.fill_holes","arguments":{"closedSurface":true,"maxSides":32}}}
-- @predicate {"id":"non-manifold","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.closedSurface","op":"eq","value":true},{"field":"measurements.nonManifoldEdges","op":"gt","value":0}]},"severity":"error","evidence":["measurements.nonManifoldEdges"],"fix":{"action":"mesh.voxel_remesh","arguments":{"voxelSize":0.05}}}
-- @predicate {"id":"flipped-normals","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"measurements.closedManifold","op":"eq","value":true},{"field":"measurements.flippedNormals","op":"gt","value":0}]},"severity":"error","evidence":["measurements.flippedNormals"],"fix":{"action":"mesh.normals","arguments":{}}}
-- @predicate {"id":"floaters","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.singleComponent","op":"eq","value":true},{"field":"measurements.smallComponentVertices","op":"gt","value":0}]},"severity":"error","evidence":["measurements.components","measurements.smallComponentVertices"],"fix":{"action":"mesh.remove_floaters","arguments":{"maxVertices":8}}}
-- @predicate {"id":"missing-uv","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.uv","op":"eq","value":true},{"field":"measurements.uvCoverage","op":"lt","value":0.999}]},"severity":"error","evidence":["measurements.uvCoverage"],"fix":{"action":"mesh.unwrap","arguments":{}}}
-- @predicate {"id":"uv-outside","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.uv","op":"eq","value":true},{"field":"measurements.uvOutsideLoops","op":"gt","value":0}]},"severity":"warning","evidence":["measurements.uvOutsideLoops"],"fix":{"action":"mesh.pack_uv","arguments":{}}}
-- @predicate {"id":"flat-shading","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.smooth","op":"eq","value":true},{"field":"measurements.flatFaces","op":"gt","value":0}]},"severity":"warning","evidence":["measurements.flatFaces"],"fix":{"action":"mesh.smooth","arguments":{}}}
-- @predicate {"id":"unapplied-scale","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.unitScale","op":"eq","value":true},{"field":"measurements.scaleError","op":"gt","value":0.000001}]},"severity":"warning","evidence":["measurements.scaleError"],"fix":{"action":"mesh.scale","arguments":{}}}
-- @predicate {"id":"offset-origin","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.originCentered","op":"eq","value":true},{"field":"measurements.originOffsetRelative","op":"gt","value":0.000001}]},"severity":"warning","evidence":["measurements.originOffsetRelative"],"fix":{"action":"mesh.origin","arguments":{}}}
-- @predicate {"id":"wrong-scale","domains":["godot","unity","roblox"],"condition":{"all":[{"field":"attributes.targets.unitScale","op":"eq","value":true},{"field":"measurements.scaleError","op":"gt","value":0.000001}]},"severity":"warning","evidence":["attributes.scale","measurements.scaleError"],"fix":{"action":"engine.scale","arguments":{}}}
-- @predicate {"id":"low-texture-resolution","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.texture","op":"eq","value":true},{"field":"measurements.textureResolutionDeficit","op":"gt","value":0}]},"severity":"warning","evidence":["measurements.textureMinResolution","measurements.textureResolutionDeficit"],"fix":{"action":"mesh.upscale_texture","arguments":{}}}
-- @predicate {"id":"uv-stretch","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.stretch","op":"eq","value":true},{"field":"measurements.uvStretchExcess","op":"gt","value":0}]},"severity":"warning","evidence":["measurements.uvStretchMax"],"fix":{"action":"mesh.unwrap","arguments":{}}}
-- @predicate {"id":"vertex-budget","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"measurements.vertexBudgetExcess","op":"gt","value":0}]},"severity":"warning","evidence":["measurements.vertices","measurements.vertexBudgetExcess"],"fix":{"action":"mesh.decimate","arguments":{"ratio":0.5}}}
-- @predicate {"id":"undersampled-silhouette","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.refineSilhouette","op":"eq","value":true},{"field":"measurements.silhouetteMatch","op":"lt","value":0.98},{"field":"measurements.longestEdgeRelative","op":"gt","value":0.1}]},"severity":"warning","evidence":["measurements.silhouetteMatch","measurements.longestEdgeRelative"],"fix":{"action":"mesh.subdivide","arguments":{"levels":1}}}
-- @predicate {"id":"intersections","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.noIntersections","op":"eq","value":true},{"field":"measurements.intersectingObjects","op":"nonempty"}]},"severity":"warning","evidence":["measurements.intersectingObjects"],"fix":{"action":"review","arguments":{}}}
-- @predicate {"id":"asymmetry","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.symmetric","op":"eq","value":true},{"field":"measurements.symmetryErrorRelative","op":"gt","value":0.001}]},"severity":"warning","evidence":["measurements.symmetryErrorRelative"],"fix":{"action":"review","arguments":{}}}
-- @predicate {"id":"topology-flow","domains":["blender"],"condition":{"all":[{"field":"kind","op":"eq","value":"mesh"},{"field":"attributes.targets.quadFlow","op":"eq","value":true},{"field":"measurements.topologyFlow","op":"eq","value":"poor"}]},"severity":"warning","evidence":["measurements.topologyFlow","measurements.nonQuadFaces","measurements.extraordinaryVertices"],"fix":{"action":"review","arguments":{}}}
-- @predicate {"id":"missing-collider","domains":["godot","unity","roblox"],"condition":{"all":[{"field":"attributes.requiresCollider","op":"eq","value":true},{"field":"measurements.colliderCount","op":"eq","value":0}]},"severity":"error","evidence":["measurements.colliderCount"],"fix":{"action":"review","arguments":{}}}
-- @predicate {"id":"broken-reference","domains":["godot","unity","roblox"],"condition":{"field":"measurements.brokenReferences","op":"gt","value":0},"severity":"error","evidence":["measurements.brokenReferences"],"fix":{"action":"review","arguments":{}}}
