CL 1
L laya-video v1 -- LAYA edits video: brief -> EDL -> HyperFrames render -> transcribe -> shared judge -> named EDL fixes; no training
A scene.transcribe(domain:"video", source:{project:path quality?:"preview"|"master"}) -> scene -- render the project's edl.json headless (HyperFrames, throwaway profile) and measure the file: shots, cuts, black/frozen frames, BS.1770 loudness, true peak, clipping, silence, measured beats, Whisper speech, keyframe OCR, Obscura caption DOM, LAYA glance of each source capture
A laya.judge(scene:object) -> verdict -- shared crisp predicates below; one finding per (predicate, node)
A scene.improve(domain:"video", source:object, budget:object) -> receipt -- one named EDL fix per step; kept only on a strict finding reduction with no guarded metric regression, else edl.json is restored byte-exact
A video.assemble(brief:path, out:path) -> edl -- first draft straight from the CL brief: one shot per story beat from real captures
A video.vote(a:scene, b:scene, winner:"a"|"b", user:str, reason:str) -> episodes -- Paul's A/B taste as two personal episodes
P cut(brief, out): video.assemble(brief, out) ; scene.improve("video", {project:out}, budget) ; scene.transcribe("video", {project:out, quality:"master"})
P inspect(project): scene.transcribe("video", {project}) ; laya.judge(scene)
P taste(a, b, winner): video.vote(a, b, winner, user:"paul", reason)
-- @predicate {"id":"wrong-aspect","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.aspectError","op":"gt","value":0.01}]},"severity":"error","evidence":["measurements.width","measurements.height","measurements.aspectError"],"fix":{"action":"render.set_aspect","arguments":{}},"means":"The rendered frame is not the brief's aspect ratio."}
-- @predicate {"id":"pacing-off-brief","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"any":[{"field":"measurements.durationOutsideBrief","op":"eq","value":true},{"field":"measurements.pacingOutsideBrief","op":"eq","value":true}]}]},"severity":"error","evidence":["measurements.durationS","measurements.medianShotS"],"fix":{"action":"edl.retime","arguments":{}},"means":"Measured length or median shot length is outside the brief."}
-- @predicate {"id":"audio-clipping","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"any":[{"field":"measurements.clippedSamples","op":"gt","value":0},{"field":"measurements.truePeakDbtp","op":"gt","value":-1.0}]}]},"severity":"error","evidence":["measurements.clippedSamples","measurements.truePeakDbtp","measurements.integratedLufs"],"fix":{"action":"audio.normalize","arguments":{}},"means":"Decoded audio reaches full scale or its 4x oversampled true peak is above -1 dBTP."}
-- @predicate {"id":"dead-air","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.deadAirMaxS","op":"gt","value":1.0}]},"severity":"error","evidence":["measurements.deadAirMaxS"],"fix":{"action":"audio.extend_bed","arguments":{}},"means":"More than 1 s under -50 dBFS before the designed tail."}
-- @predicate {"id":"missing-shot","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.missingMustInclude","op":"nonempty"}]},"severity":"error","evidence":["measurements.missingMustInclude"],"fix":{"action":"edl.insert_shot","arguments":{}},"means":"A must-include surface is not on screen for at least 1 s."}
-- @predicate {"id":"brand-type-off-guide","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.fontFamiliesOffBrand","op":"nonempty"}]},"severity":"warning","evidence":["measurements.fontFamiliesOffBrand"],"fix":{"action":"brand.apply_tokens","arguments":{}},"means":"On-screen type uses a family outside the brand guide (computed style in the composition DOM)."}
-- @predicate {"id":"black-frames","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.blackFrames","op":"gt","value":0}]},"severity":"error","evidence":["measurements.blackFrames","measurements.blackStartS"],"fix":{"action":"edl.close_gap","arguments":{}},"means":"Decoded frames inside the shot window are black (mean luma < 12 of 255, flat)."}
-- @predicate {"id":"frozen-frames","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"attributes.designedHold","op":"eq","value":false},{"field":"measurements.frozenOverLimit","op":"eq","value":true}]},"severity":"warning","evidence":["measurements.frozenRunMaxS","measurements.frozenStartS"],"fix":{"action":"edl.add_motion","arguments":{}},"means":"Non-black frames that stay within 0.15/255 of the run's first frame for longer than the brief's freeze limit (1.5 s unless the brief says otherwise) outside a designed hold."}
-- @predicate {"id":"screen-defect","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.screenDefects","op":"nonempty"}]},"severity":"error","evidence":["measurements.screenDefects"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"LAYA glance finds a calibrated (precision >= 0.95) UI defect in the source capture."}
-- @predicate {"id":"screen-advisory","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.screenAdvisory","op":"nonempty"}]},"severity":"warning","evidence":["measurements.screenAdvisory"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"LAYA glance raised an uncalibrated finding on the source capture; a launch film avoids doubtful screens."}
-- @predicate {"id":"billing-imagery","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.sourceText","op":"matches","value":"\\b(invoice|billing|subscription|payment|pricing)\\b"}]},"severity":"error","evidence":["measurements.sourceText"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"OCR of the source capture shows billing or invoice text."}
-- @predicate {"id":"jump-cut","condition":{"all":[{"field":"kind","op":"eq","value":"cut"},{"field":"attributes.transition","op":"eq","value":"none"},{"field":"measurements.similarity","op":"ge","value":0.75}]},"severity":"error","evidence":["measurements.similarity","measurements.timeS","measurements.sameSurface"],"fix":{"action":"edl.separate","arguments":{}},"means":"Frames either side of a cut are near-identical in layout (normalised correlation >= 0.75): an unintended jump cut. A designed dissolve (the incoming clip's transition) is not a cut."}
-- @predicate {"id":"cut-off-beat","condition":{"all":[{"field":"kind","op":"eq","value":"cut"},{"field":"attributes.syncRequested","op":"eq","value":true},{"field":"measurements.offBeatMs","op":"gt","value":45}]},"severity":"warning","evidence":["measurements.timeS","measurements.offBeatMs"],"fix":{"action":"edl.snap_cuts","arguments":{}},"means":"The measured cut is more than 45 ms from the nearest measured beat when the brief asks for sync."}
-- @predicate {"id":"caption-unsafe","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.outsideSafe","op":"eq","value":true}]},"severity":"error","evidence":["measurements.box"],"fix":{"action":"caption.move_into_safe","arguments":{}},"means":"The caption's DOM box leaves the brief's title-safe area."}
-- @predicate {"id":"caption-unreadable","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"any":[{"field":"measurements.tooSmall","op":"eq","value":true},{"field":"measurements.lowContrast","op":"eq","value":true}]}]},"severity":"error","evidence":["measurements.heightFrac","measurements.contrastRatio"],"fix":{"action":"caption.restyle","arguments":{}},"means":"Caption box is under the brief's minimum height or its measured pixel contrast is under 4.5:1."}
-- @predicate {"id":"caption-too-brief","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.tooBrief","op":"eq","value":true}]},"severity":"warning","evidence":["measurements.holdS","measurements.minHoldS"],"fix":{"action":"caption.extend","arguments":{}},"means":"On screen for less than 0.6 s + 0.1 s per word."}
-- @predicate {"id":"caption-overlap","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.overlaps","op":"nonempty"}]},"severity":"error","evidence":["measurements.overlaps","measurements.box"],"fix":{"action":"caption.restack","arguments":{}},"means":"Two captions share screen time and their DOM boxes intersect."}
-- @predicate {"id":"brand-colour-off-guide","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.brandDeltaE","op":"gt","value":12}]},"severity":"warning","evidence":["measurements.textColour","measurements.brandDeltaE"],"fix":{"action":"brand.apply_tokens","arguments":{}},"means":"Measured caption text colour is more than 12 deltaE from every brand colour."}
-- @predicate {"id":"error-copy","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"any":[{"field":"measurements.errorCopy","op":"nonempty"},{"field":"measurements.framePathText","op":"nonempty"}]}]},"severity":"error","evidence":["measurements.errorCopy","measurements.framePathText"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"2x OCR of the source capture (or OCR of the rendered frame) shows error-state copy, a raw error, an encoded or absolute path, or an internal id (the UI vocabulary regexes plus error phrasing)."}
-- @predicate {"id":"unreadable-text","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.unreadTextRuns","op":"gt","value":0}]},"severity":"error","evidence":["measurements.unreadTextRuns"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"Text-like ink OCR could not read (paths, ids, code): a read line that continues for 6 line heights and 120 px, or a free-standing line-shaped block no OCR word touches with under 1.2 word spaces per 100 px."}
-- @predicate {"id":"empty-state","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"any":[{"all":[{"field":"measurements.emptyStateCopy","op":"nonempty"},{"field":"measurements.blankFraction","op":"gt","value":0.6}]},{"field":"measurements.blankFraction","op":"gt","value":0.85},{"field":"measurements.largestFlatRect","op":"gt","value":0.7}]}]},"severity":"error","evidence":["measurements.emptyStateCopy","measurements.blankFraction","measurements.largestFlatRect"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"The capture is a placeholder: empty-state copy over a mostly blank screen, more than 85% of 32px blocks flat, or one flat rectangle over 70% of the frame (an undrawn page, an empty viewport)."}
-- @predicate {"id":"debug-sheet","condition":{"all":[{"field":"kind","op":"eq","value":"shot"},{"field":"measurements.debugLabels","op":"nonempty"}]},"severity":"error","evidence":["measurements.debugLabels"],"fix":{"action":"edl.swap_capture","arguments":{}},"means":"The capture carries tool labels (two or more whole OCR lines that are kebab-case identifiers such as before-shape): a debug contact sheet, not product imagery."}
-- @predicate {"id":"caption-path","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.pathText","op":"eq","value":true}]},"severity":"error","evidence":["measurements.pathText"],"fix":{"action":"review","arguments":{}},"means":"Caption copy contains a path or internal id (the UI vocabulary regexes); copy is authored, so a person rewrites it."}
-- @predicate {"id":"frame-count-off","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.frameCountOff","op":"eq","value":true}]},"severity":"error","evidence":["measurements.frames","measurements.expectedFrames","measurements.fps"],"fix":{"action":"review","arguments":{}},"means":"Decoded frame count differs from duration x fps by more than one frame (a renderer or mux fault; from track/laya-video's contracts)."}
-- @predicate {"id":"loudness-off","condition":{"all":[{"field":"kind","op":"eq","value":"video"},{"field":"measurements.loudnessOff","op":"eq","value":true}]},"severity":"warning","evidence":["measurements.integratedLufs","measurements.targetLufs"],"fix":{"action":"audio.normalize","arguments":{}},"means":"Integrated BS.1770 loudness more than 2 LU from the brief's target (from track/laya-video's vocabulary)."}
-- @predicate {"id":"caption-not-rendered","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.notRendered","op":"eq","value":true}]},"severity":"error","evidence":["measurements.startS"],"fix":{"action":"review","arguments":{}},"means":"An authored caption has no laid-out box in the composition DOM at its own time (from track/laya-video's contracts)."}
-- @predicate {"id":"caption-too-long","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.tooLong","op":"eq","value":true}]},"severity":"warning","evidence":["measurements.words","measurements.maxWords"],"fix":{"action":"review","arguments":{}},"means":"More words in one caption than the brief allows; copy is authored, so a person shortens it (from track/laya-video's vocabulary)."}
-- @predicate {"id":"stock-phrase","condition":{"all":[{"field":"kind","op":"eq","value":"caption"},{"field":"measurements.stockPhrase","op":"nonempty"}]},"severity":"warning","evidence":["measurements.stockPhrase"],"fix":{"action":"review","arguments":{}},"means":"Template launch copy (seamless, unlock, AI-powered, introducing...); a person rewrites it (track/laya-video's list)."}
C laya-video.verify draft-judged: proof.before.findings > 0 -- block the first draft was actually judged on measured facts
C laya-video.verify improved: proof.after.findings < proof.before.findings -- block improve removed findings
C laya-video.verify brief: proof.after.briefChecks == true -- block the after cut passes the brief's own C lines
C laya-video.verify rollback: proof.rollbackExact == true -- block a fix the core rejected in THIS run restores edl.json and the re-observed Scene byte-exact (practice repairs do not count)
C laya-video.verify fresh: proof.fresh == true -- block the summarised before/after/master were measured with the current observers (no stale receipts)
C laya-video.verify practice-recall: proof.practice.recall >= 0.9 -- block injected defects (self-made practice) are found
C laya-video.verify practice-precision: proof.practice.precision >= 0.9 -- block clean practice cuts stay quiet
C laya-video.verify episodes: proof.episodes > 0 -- block outcomes reach laya_instant immediately
C laya-video.verify headless: proof.visibleWindows == 0 -- block renders and DOM reads are headless
C laya-video.verify training: proof.training == false -- block no training or consolidation
J taste a|b: "Which cut feels more like Neyvia?"
V J taste -> human:paul evidence:a,b
X Whisper invents words on instrumental music -> keep only segments with no-speech probability < 0.5 and mean log-probability > -1
X A flagged capture with no clean alternative is ripple-deleted only when its surface is not a brief must-include; a must-include stays and is reported for recapture
X A fix applies the house rule to every instance of its predicate -> one render per rule, not per node; the strict-subset rule still rejects a fix that creates any new finding
F HyperFrames 0.8.138 launches its own browser and has no connect-over-CDP option, so renders use the local chrome-headless-shell with a throwaway profile; Obscura reads the composition DOM.
F Beat sync is measured against beats detected in the rendered audio (low-band spectral flux, autocorrelation tempo); music without a pulse yields no beats and cut-off-beat stays unknown-free but silent.
F Caption contrast and colour are measured from decoded pixels inside the exact DOM box; text under ~10 px in previews makes colour a blend, so brand colour uses a 12 deltaE tolerance.
F Paul's taste votes are personal episodes; none were cast by agents.
F HyperFrames 0.8.138 normalises each <audio> clip (a +12.9 dBFS bed renders at -11.3 LUFS, -2 dBTP), so EDL gain cannot make its render clip; audio-clipping is proven on a file-level injection (40006 clipped samples found, clean cut quiet).
F Jump cuts compare the coarse layout (5x5 block means of 160x90 thumbnails, flat frames excluded): a 7% re-framed copy scores 0.87, the launch cut's real cuts at most 0.60; the 0.75 threshold rests on that small sample.
F Caption contrast is measured inside the DOM box against the box's own median; over a busy screenshot without a scrim the median can be the screenshot, so low-contrast text is only reliably caught on plain or scrimmed backgrounds.
F A round is one HyperFrames render plus measurement: 11-460 s on this machine at 640x360@12 (median about 150 s); the core's 300 s budget rejects slower rounds, which are retried once from the render cache.
F Lead review of the v1 master found shots the judge passed: Windows OCR silently drops path-like words, so a raw error with a path read as clean. Source captures are now read at 2x, their copy is matched against the UI vocabulary's own raw-error/encoded-path/internal-id regexes plus error phrasing, and text-like ink a recognised line continues into but OCR did not read (6 line heights, 120 px) counts as unreadable text; empty states are copy over a blank screen or >85% flat blocks. On 467 tour captures these flag 370 error-copy, 173 empty-state, 66 unreadable-text and 37 debug-sheet captures (mostly the sidebar's "Codex could not be read" and "No chats yet"); precision of unreadable-text on dense side panels is not measured.
M API "laya_video.make_adapter registers domain video lazily in scene_core.adapter; source={project, quality} renders and judges the cut EDL (neyvia.video.cut.v1), source={video, project?, brief?, fast?} judges a rendered file with the same observers (the project's cut or clip EDL only supplies ids, shot windows and caption DOM); fixes edit only edl.json; checkpoint/restore = edl.json bytes; renders cached by project content." src:"plan 28" state:verified
M API "One video stack (7 Oct): neyvia.video.* tools (video_hyperframes free-form EDL neyvia.video.edl.v1, laya_video_edit pre-render domain video-edit, video_contracts fast contracts, Whisper word start/end timings) came from track/laya-video; this adapter, its observers and this vocabulary from track/video. Both are credited in the module docstrings." src:"VIDEO2 reconciliation" state:verified
F A layout shot composes real media (a Kronos sheet beside its headless Blender turntable clip, phone captures in a drawn device frame). Each image layer is source-audited like a capture and UI layers are glanced; a video layer is audited on one of its own frames; blank and flat-rectangle measures apply to UI layers only, because a render or sheet on a plain backdrop is not an empty screen.
F Masters render at 60 fps. A freeze is measured against the first frame of the still run (mean difference under 0.15 of 255 on 160x90 grey thumbnails), so a slow push at 60 fps, which moves sub-pixel per frame, leaves the run within about 0.1 s while encoder settling on a held frame (under 0.1) stays inside it; previously consecutive frames were compared with a 0.02 threshold, which encoder noise broke.
