CL 1
L local-mechanisms v1 -- Authored executable manual
-- @manual {"chapters":{"mechanisms":{"title":"Frozen artifact competition and lossless context compaction"}},"clVersion":"1.1","id":"local-mechanisms","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"context.compact":"t1","lab.compare":"t2","lab.competition":"t3","lab.instrument":"t4"},"tool_metadata":{"context.compact":{"mutability_class":"artifact_write"},"lab.compare":{"mutability_class":"artifact_write"},"lab.competition":{"mutability_class":"artifact_write"},"lab.instrument":{"mutability_class":"artifact_write"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"focus\":{\"type\":\"string\"},\"targetRatio\":{\"type\":\"number\",\"minimum\":0.05,\"maximum\":0.8},\"maxContextTokens\":{\"type\":\"integer\",\"minimum\":1000,\"maximum\":2000000}},\"required\":[\"sessionId\"],\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"identity\":{\"type\":\"string\"},\"targets\":{\"type\":\"object\",\"minProperties\":2,\"maxProperties\":8,\"additionalProperties\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}},\"workId\":{\"type\":\"string\"}},\"required\":[\"identity\",\"targets\",\"workId\"],\"allOf\":[{\"properties\":{\"identity\":{\"not\":{\"enum\":[\"\"]}},\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"identity\":{\"type\":\"string\"},\"source\":{\"type\":\"string\"},\"candidates\":{\"type\":\"array\",\"minItems\":2,\"maxItems\":8,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}},\"instruments\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":12,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}},\"workId\":{\"type\":\"string\"}},\"required\":[\"identity\",\"source\",\"candidates\",\"instruments\",\"workId\"],\"allOf\":[{\"properties\":{\"identity\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}},\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"identity\":{\"type\":\"string\"},\"spec\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]},\"key\":{\"type\":\"string\",\"minLength\":1},\"max\":{\"type\":\"number\"},\"maxMeanMs\":{\"type\":\"number\",\"minimum\":0},\"minWidth\":{\"type\":\"integer\",\"minimum\":0},\"minHeight\":{\"type\":\"integer\",\"minimum\":0},\"maxBytes\":{\"type\":\"integer\",\"minimum\":0}},\"required\":[\"kind\"]}},\"required\":[\"identity\",\"spec\"],\"allOf\":[{\"properties\":{\"identity\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\"}"
T t6{sessionId:str focus:str targetRatio:0.05..0.8 maxContextTokens:1000..2000000 ..}
T t7{identity:str targets:json:"{\"type\":\"object\",\"minProperties\":2,\"maxProperties\":8,\"additionalProperties\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}}" workId:str ..}
T t8{identity:str source:str candidates:json:"{\"type\":\"array\",\"minItems\":2,\"maxItems\":8,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":12,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" workId:str ..}
T t9{identity:str spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1.. max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..} ..}
L local-mechanisms.mechanisms v1 -- Frozen artifact competition and lossless context compaction
-- @record {"chapter":"mechanisms","data":{"effect":"Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence","pre":"Intact local source, frozen instruments and active durable context; selected work preferences enabled","returns":{"$cl_type":"t5"},"reversible":false,"schema":"context.compact","tool":"context.compact"},"key":"context-compact","section":"actions"}
A context.compact(sessionId:str focus?:str targetRatio?:0.05..0.8 maxContextTokens?:1000..2000000) -> json:"{\"type\":\"object\"}" ! -- Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence
F verify-context-compact "No authored observer check is bound to context.compact" -> ask operator blocks:context.compact
-- @record {"chapter":"mechanisms","data":{"effect":"Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence","pre":"Intact local source, frozen instruments and active durable context; selected work preferences enabled","returns":{"$cl_type":"t5"},"reversible":false,"schema":"lab.compare","tool":"lab.compare"},"key":"lab-compare","section":"actions"}
A lab.compare(identity:str targets:json:"{\"type\":\"object\",\"minProperties\":2,\"maxProperties\":8,\"additionalProperties\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}}" workId:str) -> json:"{\"type\":\"object\"}" ! -- Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence
F verify-lab-compare "No authored observer check is bound to lab.compare" -> ask operator blocks:lab.compare
-- @record {"chapter":"mechanisms","data":{"effect":"Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence","pre":"Intact local source, frozen instruments and active durable context; selected work preferences enabled","returns":{"$cl_type":"t5"},"reversible":false,"schema":"lab.competition","tool":"lab.competition"},"key":"lab-competition","section":"actions"}
A lab.competition(identity:str source:str candidates:json:"{\"type\":\"array\",\"minItems\":2,\"maxItems\":8,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":12,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" workId:str) -> json:"{\"type\":\"object\"}" ! -- Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence
F verify-lab-competition "No authored observer check is bound to lab.competition" -> ask operator blocks:lab.competition
-- @record {"chapter":"mechanisms","data":{"effect":"Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence","pre":"Intact local source, frozen instruments and active durable context; selected work preferences enabled","returns":{"$cl_type":"t5"},"reversible":false,"schema":"lab.instrument","tool":"lab.instrument"},"key":"lab-instrument","section":"actions"}
A lab.instrument(identity:str spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1.. max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..}) -> json:"{\"type\":\"object\"}" ! -- Freeze isolated candidates, measure all candidates against identical criteria, or archive older context without losing original evidence
F verify-lab-instrument "No authored observer check is bound to lab.instrument" -> ask operator blocks:lab.instrument
-- @record {"chapter":"mechanisms","data":{"goal":"Archive older active context without deleting it, protect recent and pinned evidence, and write a compaction receipt.","inputs":{"$cl_type":"t6"},"steps":[{"action":"context-compact","args":{"focus":{"$input":"focus"},"maxContextTokens":{"$input":"maxContextTokens"},"sessionId":{"$input":"sessionId"},"targetRatio":{"$input":"targetRatio"}},"save":"saved"}]},"key":"verify-context-compact","section":"procedures"}
P verify-context-compact(sessionId:str focus:str targetRatio:0.05..0.8 maxContextTokens:1000..2000000):saved=context.compact(focus:focus maxContextTokens:maxContextTokens sessionId:sessionId targetRatio:targetRatio) -- Archive older active context without deleting it, protect recent and pinned evidence, and write a compaction receipt.
V P verify-context-compact -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"mechanisms","data":{"goal":"Measure every competition candidate with the same frozen instruments; never automatically promote","inputs":{"$cl_type":"t7"},"steps":[{"action":"lab-compare","args":{"identity":{"$input":"identity"},"targets":{"$input":"targets"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"verify-lab-compare","section":"procedures"}
P verify-lab-compare(identity:str targets:json:"{\"type\":\"object\",\"minProperties\":2,\"maxProperties\":8,\"additionalProperties\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}}" workId:str):saved=lab.compare(identity:identity targets:targets workId:workId) -- Measure every competition candidate with the same frozen instruments; never automatically promote
V P verify-lab-compare -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"mechanisms","data":{"goal":"Create isolated candidate source snapshots under one frozen measurement contract","inputs":{"$cl_type":"t8"},"steps":[{"action":"lab-competition","args":{"candidates":{"$input":"candidates"},"identity":{"$input":"identity"},"instruments":{"$input":"instruments"},"source":{"$input":"source"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"verify-lab-competition","section":"procedures"}
P verify-lab-competition(identity:str source:str candidates:json:"{\"type\":\"array\",\"minItems\":2,\"maxItems\":8,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":12,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120}}" workId:str):saved=lab.competition(candidates:candidates identity:identity instruments:instruments source:source workId:workId) -- Create isolated candidate source snapshots under one frozen measurement contract
V P verify-lab-competition -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"mechanisms","data":{"goal":"Freeze an existing quality instrument for matched artifact evaluation","inputs":{"$cl_type":"t9"},"steps":[{"action":"lab-instrument","args":{"identity":{"$input":"identity"},"spec":{"$input":"spec"}},"save":"saved"}]},"key":"verify-lab-instrument","section":"procedures"}
P verify-lab-instrument(identity:str spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1.. max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..}):saved=lab.instrument(identity:identity spec:spec) -- Freeze an existing quality instrument for matched artifact evaluation
V P verify-lab-instrument -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"mechanisms","data":{"failure":"One failed candidate is omitted from a comparison","recovery":"Measure every candidate named by the frozen contract and retain failed criteria."},"key":"0","section":"pitfalls"}
X One failed candidate is omitted from a comparison -> Measure every candidate named by the frozen contract and retain failed criteria.
-- @record {"chapter":"mechanisms","data":{"failure":"A compacted receipt hides lost instructions or original messages","recovery":"Freshly compare every old ledger row; protected content stays active and archived content stays retrievable."},"key":"1","section":"pitfalls"}
X A compacted receipt hides lost instructions or original messages -> Freshly compare every old ledger row; protected content stays active and archived content stays retrievable.
-- @record {"chapter":"mechanisms","data":"A frozen local artifact measurement proves its declared criterion, not general model improvement.","key":"0","section":"frontier"}
F A frozen local artifact measurement proves its declared criterion, not general model improvement.
-- @record {"chapter":"mechanisms","data":"Candidate promotion and provider/model execution require their own authority and real journey.","key":"1","section":"frontier"}
F Candidate promotion and provider/model execution require their own authority and real journey.
-- @record {"chapter":"mechanisms","data":"Use new competition identities; isolated byte snapshots preserve the original source.","key":"0","section":"guidance"}
M local-mechanisms "Use new competition identities; isolated byte snapshots preserve the original source." src:"authored manual" state:verified
-- @record {"chapter":"mechanisms","data":"Compaction needs an active bounded ledger. An empty ledger is refused rather than credited as an effect.","key":"1","section":"guidance"}
M local-mechanisms "Compaction needs an active bounded ledger. An empty ledger is refused rather than credited as an effect." src:"authored manual" state:verified
