CL 1
L local-environment v1 -- Authored executable manual
-- @manual {"chapters":{"environment":{"title":"Pinned local interpreters and declared task effects"}},"clVersion":"1.1","id":"local-environment","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"environment.create":"t1","environment.run":"t2"},"tool_metadata":{"environment.create":{"mutability_class":"process_execute"},"environment.run":{"mutability_class":"process_execute"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"environmentId\":{\"type\":\"string\"},\"lockPath\":{\"type\":\"string\"},\"timeout\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":300}},\"required\":[\"environmentId\",\"lockPath\"],\"allOf\":[{\"properties\":{\"environmentId\":{\"not\":{\"enum\":[\"\"]}},\"lockPath\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"manifestPath\":{\"type\":\"string\"},\"args\":{\"type\":\"array\",\"maxItems\":32,\"items\":{\"type\":\"string\",\"maxLength\":4096}},\"timeout\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":300},\"outputs\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":8,\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"]}}},\"required\":[\"manifestPath\",\"args\"],\"allOf\":[{\"properties\":{\"manifestPath\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\"}"
T t4{environmentId:str lockPath:str timeout:1..300 ..}
T t5{manifestPath:str args:[str#..4096]#..32 timeout:1..300 outputs:[{path:str#1..4096 sha256:str ~"^[a-fA-F0-9]{64}$"}]#1..8 ..}
L local-environment.environment v1 -- Pinned local interpreters and declared task effects
-- @record {"chapter":"environment","data":{"effect":"Create and independently probe a pinned interpreter or run exact saved source and verify newly written declared file bytes","pre":"Explicit workspace execution grant, bounded pinned lock or scoped saved Python script and newly created output paths","returns":{"$cl_type":"t3"},"reversible":false,"schema":"environment.create","tool":"environment.create"},"key":"environment-create","section":"actions"}
A environment.create(environmentId:str lockPath:str timeout?:1..300) -> json:"{\"type\":\"object\"}" ! -- Create and independently probe a pinned interpreter or run exact saved source and verify newly written declared file bytes
F verify-environment-create "No authored observer check is bound to environment.create" -> ask operator blocks:environment.create
-- @record {"chapter":"environment","data":{"effect":"Create and independently probe a pinned interpreter or run exact saved source and verify newly written declared file bytes","pre":"Explicit workspace execution grant, bounded pinned lock or scoped saved Python script and newly created output paths","returns":{"$cl_type":"t3"},"reversible":false,"schema":"environment.run","tool":"environment.run"},"key":"environment-run","section":"actions"}
A environment.run(manifestPath:str args:[str#..4096]#..32 timeout?:1..300 outputs?:[{path:str#1..4096 sha256:str ~"^[a-fA-F0-9]{64}$"}]#1..8) -> json:"{\"type\":\"object\"}" ! -- Create and independently probe a pinned interpreter or run exact saved source and verify newly written declared file bytes
F verify-environment-run "No authored observer check is bound to environment.run" -> ask operator blocks:environment.run
-- @record {"chapter":"environment","data":{"goal":"Create or reuse hash-pinned Python dependencies with a shared uv cache. Dependency installation requires a mutation grant.","inputs":{"$cl_type":"t4"},"steps":[{"action":"environment-create","args":{"environmentId":{"$input":"environmentId"},"lockPath":{"$input":"lockPath"},"timeout":{"$input":"timeout"}},"save":"saved"}]},"key":"verify-environment-create","section":"procedures"}
P verify-environment-create(environmentId:str lockPath:str timeout:1..300):saved=environment.create(environmentId:environmentId lockPath:lockPath timeout:timeout) -- Create or reuse hash-pinned Python dependencies with a shared uv cache. Dependency installation requires a mutation grant.
V P verify-environment-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"environment","data":{"goal":"Run Python in a saved dependency environment and preserve the argv-bound process receipt. CL additionally requires a scoped script and declared fresh output hashes; dependency isolation is not an OS sandbox.","inputs":{"$cl_type":"t5"},"steps":[{"action":"environment-run","args":{"args":{"$input":"args"},"manifestPath":{"$input":"manifestPath"},"outputs":{"$input":"outputs"},"timeout":{"$input":"timeout"}},"save":"saved"}]},"key":"verify-environment-run","section":"procedures"}
P verify-environment-run(manifestPath:str args:[str#..4096]#..32 timeout:1..300 outputs:[{path:str#1..4096 sha256:str ~"^[a-fA-F0-9]{64}$"}]#1..8):saved=environment.run(args:args manifestPath:manifestPath outputs:outputs timeout:timeout) -- Run Python in a saved dependency environment and preserve the argv-bound process receipt. CL additionally requires a scoped script and declared fresh output hashes; dependency isolation is not an OS sandbox.
V P verify-environment-run -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"environment","data":{"failure":"An old matching output or forged process receipt is mistaken for a new effect","recovery":"Use a new declared output path and exact SHA256; completion rechecks bytes, script, argv and interpreter."},"key":"0","section":"pitfalls"}
X An old matching output or forged process receipt is mistaken for a new effect -> Use a new declared output path and exact SHA256; completion rechecks bytes, script, argv and interpreter.
-- @record {"chapter":"environment","data":{"failure":"The pinned lock or script changes after execution","recovery":"Completion is refused; preserve the original run and use a new explicit environment or script."},"key":"1","section":"pitfalls"}
X The pinned lock or script changes after execution -> Completion is refused; preserve the original run and use a new explicit environment or script.
-- @record {"chapter":"environment","data":"Only declared new workspace output files establish the run effect. Other side effects require their own observer.","key":"0","section":"frontier"}
F Only declared new workspace output files establish the run effect. Other side effects require their own observer.
-- @record {"chapter":"environment","data":"Inline -c/-m execution, reused output files and absent declared output hashes remain CL frontier.","key":"1","section":"frontier"}
F Inline -c/-m execution, reused output files and absent declared output hashes remain CL frontier.
-- @record {"chapter":"environment","data":"A Python dependency environment is not an OS sandbox. Offline empty-lock proof does not establish external dependency installation.","key":"2","section":"frontier"}
F A Python dependency environment is not an OS sandbox. Offline empty-lock proof does not establish external dependency installation.
-- @record {"chapter":"environment","data":"Use only already installed uv and Python. Respect network, installation and workspace authority.","key":"0","section":"guidance"}
M local-environment "Use only already installed uv and Python. Respect network, installation and workspace authority." src:"authored manual" state:verified
-- @record {"chapter":"environment","data":"The creation proof uses a real interpreter probe. Run receipts bind actual argv, source/interpreter hashes and declared outputs.","key":"1","section":"guidance"}
M local-environment "The creation proof uses a real interpreter probe. Run receipts bind actual argv, source/interpreter hashes and declared outputs." src:"authored manual" state:verified
