CL 1
L local-records v1 -- Authored executable manual
-- @manual {"chapters":{"records":{"title":"Exact local records and declared artifact criteria"}},"clVersion":"1.1","id":"local-records","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"behavior.create":"t1","behavior.observe":"t2","experience.compare":"live_schema_34","experience.investigate":"live_schema_35","experience.note":"live_schema_36","experience.trace":"live_schema_37","experiment.create":"t7","experiment.restore":"t8","orchestration.compile":"t9","quality.challenge":"t10","quality.compare":"t11","quality.examine":"t12","quality.holdout":"t13","quality.instrument":"t14","quality.measure":"t15","taste.correction":"t16"},"tool_metadata":{"behavior.create":{"mutability_class":"artifact_write"},"behavior.observe":{"mutability_class":"artifact_write"},"experience.compare":{"mutability_class":"artifact_write"},"experience.investigate":{"mutability_class":"artifact_write"},"experience.note":{"mutability_class":"artifact_write"},"experience.trace":{"mutability_class":"artifact_write"},"experiment.create":{"mutability_class":"artifact_write"},"experiment.restore":{"mutability_class":"artifact_write"},"orchestration.compile":{"mutability_class":"artifact_write"},"quality.challenge":{"mutability_class":"artifact_write"},"quality.compare":{"mutability_class":"artifact_write"},"quality.examine":{"mutability_class":"artifact_write"},"quality.holdout":{"mutability_class":"artifact_write"},"quality.instrument":{"mutability_class":"artifact_write"},"quality.measure":{"mutability_class":"artifact_write"},"taste.correction":{"mutability_class":"artifact_write"}}}
T live_schema_34 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"baseline\":{\"type\":\"string\"},\"candidate\":{\"type\":\"string\"},\"preference\":{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]},\"observations\":{\"type\":\"object\"},\"arguments\":{\"type\":\"object\",\"properties\":{\"baseline\":{\"type\":\"string\"},\"candidate\":{\"type\":\"string\"},\"preference\":{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]},\"observations\":{\"type\":\"object\"}}}},\"required\":[\"workId\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_35 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"hypothesis\":{\"type\":\"string\"},\"experiment\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"},\"arguments\":{\"type\":\"object\",\"properties\":{\"hypothesis\":{\"type\":\"string\"},\"experiment\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}}}},\"required\":[\"workId\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_36 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"lesson\":{\"type\":\"string\"},\"conditions\":{\"type\":\"string\"},\"invalidation\":{\"type\":\"string\"},\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"arguments\":{\"type\":\"object\",\"properties\":{\"lesson\":{\"type\":\"string\"},\"conditions\":{\"type\":\"string\"},\"invalidation\":{\"type\":\"string\"},\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}}}},\"required\":[\"workId\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_37 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"traceId\":{\"type\":\"string\"},\"eventKind\":{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]},\"payload\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"},\"arguments\":{\"type\":\"object\",\"properties\":{\"traceId\":{\"type\":\"string\"},\"eventKind\":{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]},\"payload\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}}}},\"required\":[\"workId\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t1 json:"{\"type\":\"object\",\"properties\":{\"experimentId\":{\"type\":\"string\"},\"baselineInput\":{\"type\":\"string\"},\"variantInput\":{\"type\":\"string\"},\"acceptance\":{\"type\":\"object\"},\"requestedRoute\":{\"type\":\"object\"},\"budget\":{\"type\":\"object\"},\"workId\":{\"type\":\"string\"}},\"required\":[\"experimentId\",\"baselineInput\",\"variantInput\",\"acceptance\",\"requestedRoute\",\"budget\",\"workId\"],\"allOf\":[{\"properties\":{\"experimentId\":{\"not\":{\"enum\":[\"\"]}},\"baselineInput\":{\"not\":{\"enum\":[\"\"]}},\"variantInput\":{\"not\":{\"enum\":[\"\"]}},\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"experimentId\":{\"type\":\"string\"},\"variant\":{\"type\":\"string\",\"enum\":[\"baseline\",\"variant\"]},\"response\":{\"type\":\"string\"},\"actualRoute\":{\"type\":\"object\"},\"latencyMs\":{\"type\":\"number\"},\"cost\":{\"type\":\"number\"},\"workId\":{\"type\":\"string\"}},\"required\":[\"experimentId\",\"variant\",\"response\",\"actualRoute\",\"workId\"],\"allOf\":[{\"properties\":{\"experimentId\":{\"not\":{\"enum\":[\"\"]}},\"response\":{\"not\":{\"enum\":[\"\"]}},\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"baseline\":{\"type\":\"string\"},\"candidate\":{\"type\":\"string\"},\"preference\":{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]},\"observations\":{\"type\":\"object\"}},\"required\":[\"workId\",\"baseline\",\"candidate\",\"preference\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}},\"baseline\":{\"not\":{\"enum\":[\"\"]}},\"candidate\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"hypothesis\":{\"type\":\"string\"},\"experiment\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}},\"required\":[\"workId\",\"hypothesis\",\"experiment\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}},\"hypothesis\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"lesson\":{\"type\":\"string\"},\"conditions\":{\"type\":\"string\"},\"invalidation\":{\"type\":\"string\"},\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"workId\",\"lesson\",\"conditions\",\"invalidation\",\"evidence\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}},\"lesson\":{\"not\":{\"enum\":[\"\"]}},\"conditions\":{\"not\":{\"enum\":[\"\"]}},\"invalidation\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"traceId\":{\"type\":\"string\"},\"eventKind\":{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]},\"payload\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}},\"required\":[\"workId\",\"traceId\",\"eventKind\",\"payload\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}},\"traceId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7 json:"{\"type\":\"object\",\"properties\":{\"experimentId\":{\"type\":\"string\"},\"source\":{\"type\":\"string\"},\"launchRecipe\":{\"type\":\"object\"},\"resetRecipe\":{\"type\":\"object\"}},\"required\":[\"experimentId\",\"source\"],\"allOf\":[{\"properties\":{\"experimentId\":{\"not\":{\"enum\":[\"\"]}},\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8 json:"{\"type\":\"object\",\"properties\":{\"experimentId\":{\"type\":\"string\"},\"restoreId\":{\"type\":\"string\"}},\"required\":[\"experimentId\",\"restoreId\"],\"allOf\":[{\"properties\":{\"experimentId\":{\"not\":{\"enum\":[\"\"]}},\"restoreId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9 json:"{\"type\":\"object\",\"properties\":{\"source\":{\"type\":\"string\"},\"outputPath\":{\"type\":\"string\",\"description\":\"Optional screenshot path inside the active workspace. Omit to use the managed artifact path.\"}},\"required\":[\"source\"],\"allOf\":[{\"properties\":{\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"holdout\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"proposal\":{\"type\":\"object\"}},\"required\":[\"holdout\",\"proposal\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t11 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"instrument\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"baseline\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096},\"candidate\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}},\"required\":[\"instrument\",\"baseline\",\"candidate\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t12 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"holdout\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"targets\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":20,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}}},\"required\":[\"holdout\",\"targets\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t13 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"i\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"spec\":{\"type\":\"object\",\"properties\":{\"instruments\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":20,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}}},\"required\":[\"instruments\"]}},\"required\":[\"i\",\"spec\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t14 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"i\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"spec\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]},\"key\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":256},\"max\":{\"type\":\"number\"},\"maxMeanMs\":{\"type\":\"number\",\"minimum\":0},\"minWidth\":{\"type\":\"integer\",\"minimum\":0},\"minHeight\":{\"type\":\"integer\",\"minimum\":0},\"maxBytes\":{\"type\":\"integer\",\"minimum\":0}},\"required\":[\"kind\"]}},\"required\":[\"i\",\"spec\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t15 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"instrument\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"},\"target\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}},\"required\":[\"instrument\",\"target\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t16 json:"{\"type\":\"object\",\"properties\":{\"workId\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"context\":{\"type\":\"string\",\"enum\":[\"landing-page\",\"product-ui\",\"research\",\"game\"]},\"before_path\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096},\"after_path\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096},\"correction\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":12000},\"agent_id\":{\"type\":\"string\",\"maxLength\":120}},\"required\":[\"context\",\"before_path\",\"after_path\",\"correction\"]}},\"required\":[\"workId\",\"arguments\"],\"allOf\":[{\"properties\":{\"workId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t17 json:"{\"type\":\"object\"}"
T t18{experimentId:str baselineInput:str variantInput:str acceptance:json:"{\"type\":\"object\"}" requestedRoute:json:"{\"type\":\"object\"}" budget:json:"{\"type\":\"object\"}" workId:str ..}
T t19{experimentId:str variant:json:"{\"type\":\"string\",\"enum\":[\"baseline\",\"variant\"]}" response:str actualRoute:json:"{\"type\":\"object\"}" latencyMs:num cost:num workId:str ..}
T t20{workId:str baseline:str candidate:str preference:json:"{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]}" observations:json:"{\"type\":\"object\"}" ..}
T t21{workId:str hypothesis:str experiment:json:"{\"type\":\"object\"}" references:json:"{\"type\":\"array\"}" ..}
T t22{workId:str lesson:str conditions:str invalidation:str evidence:[str] ..}
T t23{workId:str traceId:str eventKind:json:"{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]}" payload:json:"{\"type\":\"object\"}" references:json:"{\"type\":\"array\"}" ..}
T t24{experimentId:str source:str launchRecipe:json:"{\"type\":\"object\"}" resetRecipe:json:"{\"type\":\"object\"}" ..}
T t25{experimentId:str restoreId:str ..}
T t26{source:str outputPath:json:"{\"type\":\"string\",\"description\":\"Optional screenshot path inside the active workspace. Omit to use the managed artifact path.\"}" ..}
T t27{workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" proposal:json:"{\"type\":\"object\"}"} ..}
T t28{workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" baseline:str#1..4096 candidate:str#1..4096} ..}
T t29{workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" targets:[str#1..4096]#1..20} ..}
T t30{workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":20,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}}" ..}} ..}
T t31{workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1..256 max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..}} ..}
T t32{workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" target:str#1..4096} ..}
T t33{workId:str arguments:{context:json:"{\"type\":\"string\",\"enum\":[\"landing-page\",\"product-ui\",\"research\",\"game\"]}" before_path:str#1..4096 after_path:str#1..4096 correction:str#1..12000 agent_id?:str#..120} ..}
L local-records.records v1 -- Exact local records and declared artifact criteria
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"behavior.create","tool":"behavior.create"},"key":"behavior-create","section":"actions"}
A behavior.create(experimentId:str baselineInput:str variantInput:str acceptance:json:"{\"type\":\"object\"}" requestedRoute:json:"{\"type\":\"object\"}" budget:json:"{\"type\":\"object\"}" workId:str) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-behavior-create "No authored observer check is bound to behavior.create" -> ask operator blocks:behavior.create
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"behavior.observe","tool":"behavior.observe"},"key":"behavior-observe","section":"actions"}
A behavior.observe(experimentId:str variant:json:"{\"type\":\"string\",\"enum\":[\"baseline\",\"variant\"]}" response:str actualRoute:json:"{\"type\":\"object\"}" latencyMs?:num cost?:num workId:str) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-behavior-observe "No authored observer check is bound to behavior.observe" -> ask operator blocks:behavior.observe
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"type":"object"},"reversible":false,"schema":"experience.compare","tool":"experience.compare"},"key":"experience-compare","section":"actions"}
A experience.compare(workId:str baseline?:str candidate?:str preference?:json:"{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]}" observations?:json:"{\"type\":\"object\"}" arguments?:json:"{\"type\":\"object\",\"properties\":{\"baseline\":{\"type\":\"string\"},\"candidate\":{\"type\":\"string\"},\"preference\":{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]},\"observations\":{\"type\":\"object\"}}}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experience-compare "No authored observer check is bound to experience.compare" -> ask operator blocks:experience.compare
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"type":"object"},"reversible":false,"schema":"experience.investigate","tool":"experience.investigate"},"key":"experience-investigate","section":"actions"}
A experience.investigate(workId:str hypothesis?:str experiment?:json:"{\"type\":\"object\"}" references?:json:"{\"type\":\"array\"}" arguments?:json:"{\"type\":\"object\",\"properties\":{\"hypothesis\":{\"type\":\"string\"},\"experiment\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}}}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experience-investigate "No authored observer check is bound to experience.investigate" -> ask operator blocks:experience.investigate
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"type":"object"},"reversible":false,"schema":"experience.note","tool":"experience.note"},"key":"experience-note","section":"actions"}
A experience.note(workId:str lesson?:str conditions?:str invalidation?:str evidence?:[str] arguments?:json:"{\"type\":\"object\",\"properties\":{\"lesson\":{\"type\":\"string\"},\"conditions\":{\"type\":\"string\"},\"invalidation\":{\"type\":\"string\"},\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}}}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experience-note "No authored observer check is bound to experience.note" -> ask operator blocks:experience.note
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"type":"object"},"reversible":false,"schema":"experience.trace","tool":"experience.trace"},"key":"experience-trace","section":"actions"}
A experience.trace(workId:str traceId?:str eventKind?:json:"{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]}" payload?:json:"{\"type\":\"object\"}" references?:json:"{\"type\":\"array\"}" arguments?:json:"{\"type\":\"object\",\"properties\":{\"traceId\":{\"type\":\"string\"},\"eventKind\":{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]},\"payload\":{\"type\":\"object\"},\"references\":{\"type\":\"array\"}}}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experience-trace "No authored observer check is bound to experience.trace" -> ask operator blocks:experience.trace
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"experiment.create","tool":"experiment.create"},"key":"experiment-create","section":"actions"}
A experiment.create(experimentId:str source:str launchRecipe?:json:"{\"type\":\"object\"}" resetRecipe?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experiment-create "No authored observer check is bound to experiment.create" -> ask operator blocks:experiment.create
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"experiment.restore","tool":"experiment.restore"},"key":"experiment-restore","section":"actions"}
A experiment.restore(experimentId:str restoreId:str) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-experiment-restore "No authored observer check is bound to experiment.restore" -> ask operator blocks:experiment.restore
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"orchestration.compile","tool":"orchestration.compile"},"key":"orchestration-compile","section":"actions"}
A orchestration.compile(source:str outputPath?:json:"{\"type\":\"string\",\"description\":\"Optional screenshot path inside the active workspace. Omit to use the managed artifact path.\"}") -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-orchestration-compile "No authored observer check is bound to orchestration.compile" -> ask operator blocks:orchestration.compile
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.challenge","tool":"quality.challenge"},"key":"quality-challenge","section":"actions"}
A quality.challenge(workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" proposal:json:"{\"type\":\"object\"}"}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-challenge "No authored observer check is bound to quality.challenge" -> ask operator blocks:quality.challenge
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.compare","tool":"quality.compare"},"key":"quality-compare","section":"actions"}
A quality.compare(workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" baseline:str#1..4096 candidate:str#1..4096}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-compare "No authored observer check is bound to quality.compare" -> ask operator blocks:quality.compare
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.examine","tool":"quality.examine"},"key":"quality-examine","section":"actions"}
A quality.examine(workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" targets:[str#1..4096]#1..20}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-examine "No authored observer check is bound to quality.examine" -> ask operator blocks:quality.examine
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.holdout","tool":"quality.holdout"},"key":"quality-holdout","section":"actions"}
A quality.holdout(workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":20,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}}" ..}}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-holdout "No authored observer check is bound to quality.holdout" -> ask operator blocks:quality.holdout
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.instrument","tool":"quality.instrument"},"key":"quality-instrument","section":"actions"}
A quality.instrument(workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1..256 max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..}}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-instrument "No authored observer check is bound to quality.instrument" -> ask operator blocks:quality.instrument
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"quality.measure","tool":"quality.measure"},"key":"quality-measure","section":"actions"}
A quality.measure(workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" target:str#1..4096}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-quality-measure "No authored observer check is bound to quality.measure" -> ask operator blocks:quality.measure
-- @record {"chapter":"records","data":{"effect":"Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy","pre":"Exact scoped identity and intact local owner/source artifacts","returns":{"$cl_type":"t17"},"reversible":false,"schema":"taste.correction","tool":"taste.correction"},"key":"taste-correction","section":"actions"}
A taste.correction(workId:str arguments:{context:json:"{\"type\":\"string\",\"enum\":[\"landing-page\",\"product-ui\",\"research\",\"game\"]}" before_path:str#1..4096 after_path:str#1..4096 correction:str#1..12000 agent_id?:str#..120}) -> json:"{\"type\":\"object\"}" ! -- Persist an exact proposed record, frozen criterion measurement, compiled plan or isolated byte copy
F verify-taste-correction "No authored observer check is bound to taste.correction" -> ask operator blocks:taste.correction
-- @record {"chapter":"records","data":{"goal":"Freeze a matched API behavioral experiment, observable criterion, route and call budget; does not run a model.","inputs":{"$cl_type":"t18"},"steps":[{"action":"behavior-create","args":{"acceptance":{"$input":"acceptance"},"baselineInput":{"$input":"baselineInput"},"budget":{"$input":"budget"},"experimentId":{"$input":"experimentId"},"requestedRoute":{"$input":"requestedRoute"},"variantInput":{"$input":"variantInput"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-behavior-create","section":"procedures"}
P record-behavior-create(experimentId:str baselineInput:str variantInput:str acceptance:json:"{\"type\":\"object\"}" requestedRoute:json:"{\"type\":\"object\"}" budget:json:"{\"type\":\"object\"}" workId:str):saved=behavior.create(acceptance:acceptance baselineInput:baselineInput budget:budget experimentId:experimentId requestedRoute:requestedRoute variantInput:variantInput workId:workId) -- Freeze a matched API behavioral experiment, observable criterion, route and call budget; does not run a model.
V P record-behavior-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Record explicitly unverified, caller-reported API observations. Does not establish internal model state or improvement.","inputs":{"$cl_type":"t19"},"steps":[{"action":"behavior-observe","args":{"actualRoute":{"$input":"actualRoute"},"cost":{"$input":"cost"},"experimentId":{"$input":"experimentId"},"latencyMs":{"$input":"latencyMs"},"response":{"$input":"response"},"variant":{"$input":"variant"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-behavior-observe","section":"procedures"}
P record-behavior-observe(experimentId:str variant:json:"{\"type\":\"string\",\"enum\":[\"baseline\",\"variant\"]}" response:str actualRoute:json:"{\"type\":\"object\"}" latencyMs:num cost:num workId:str):saved=behavior.observe(actualRoute:actualRoute cost:cost experimentId:experimentId latencyMs:latencyMs response:response variant:variant workId:workId) -- Record explicitly unverified, caller-reported API observations. Does not establish internal model state or improvement.
V P record-behavior-observe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Record a provisional critic comparison tied to two actual image artifacts; does not claim user preference.","inputs":{"$cl_type":"t20"},"steps":[{"action":"experience-compare","args":{"baseline":{"$input":"baseline"},"candidate":{"$input":"candidate"},"observations":{"$input":"observations"},"preference":{"$input":"preference"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-experience-compare","section":"procedures"}
P record-experience-compare(workId:str baseline:str candidate:str preference:json:"{\"type\":\"string\",\"enum\":[\"user\",\"provisional\",\"undecided\"]}" observations:json:"{\"type\":\"object\"}"):saved=experience.compare(baseline:baseline candidate:candidate observations:observations preference:preference workId:workId) -- Record a provisional critic comparison tied to two actual image artifacts; does not claim user preference.
V P record-experience-compare -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Preserve an explicit hypothesis and proposed experiment without claiming the experiment ran.","inputs":{"$cl_type":"t21"},"steps":[{"action":"experience-investigate","args":{"experiment":{"$input":"experiment"},"hypothesis":{"$input":"hypothesis"},"references":{"$input":"references"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-experience-investigate","section":"procedures"}
P record-experience-investigate(workId:str hypothesis:str experiment:json:"{\"type\":\"object\"}" references:json:"{\"type\":\"array\"}"):saved=experience.investigate(experiment:experiment hypothesis:hypothesis references:references workId:workId) -- Preserve an explicit hypothesis and proposed experiment without claiming the experiment ran.
V P record-experience-investigate -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"After work, preserve a small proposed lesson, applicability conditions, invalidation rules and existing evidence paths. Requires learning enabled; does not establish truth or authority.","inputs":{"$cl_type":"t22"},"steps":[{"action":"experience-note","args":{"conditions":{"$input":"conditions"},"evidence":{"$input":"evidence"},"invalidation":{"$input":"invalidation"},"lesson":{"$input":"lesson"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-experience-note","section":"procedures"}
P record-experience-note(workId:str lesson:str conditions:str invalidation:str evidence:[str]):saved=experience.note(conditions:conditions evidence:evidence invalidation:invalidation lesson:lesson workId:workId) -- After work, preserve a small proposed lesson, applicability conditions, invalidation rules and existing evidence paths. Requires learning enabled; does not establish truth or authority.
V P record-experience-note -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Append a timestamped reported interaction observation with references; not an independently verified journey.","inputs":{"$cl_type":"t23"},"steps":[{"action":"experience-trace","args":{"eventKind":{"$input":"eventKind"},"payload":{"$input":"payload"},"references":{"$input":"references"},"traceId":{"$input":"traceId"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-experience-trace","section":"procedures"}
P record-experience-trace(workId:str traceId:str eventKind:json:"{\"type\":\"string\",\"enum\":[\"input\",\"frame\",\"state\",\"error\",\"timing\"]}" payload:json:"{\"type\":\"object\"}" references:json:"{\"type\":\"array\"}"):saved=experience.trace(eventKind:eventKind payload:payload references:references traceId:traceId workId:workId) -- Append a timestamped reported interaction observation with references; not an independently verified journey.
V P record-experience-trace -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Preserve an isolated experiment snapshot and declared recipes; does not execute recipes.","inputs":{"$cl_type":"t24"},"steps":[{"action":"experiment-create","args":{"experimentId":{"$input":"experimentId"},"launchRecipe":{"$input":"launchRecipe"},"resetRecipe":{"$input":"resetRecipe"},"source":{"$input":"source"}},"save":"saved"}]},"key":"record-experiment-create","section":"procedures"}
P record-experiment-create(experimentId:str source:str launchRecipe:json:"{\"type\":\"object\"}" resetRecipe:json:"{\"type\":\"object\"}"):saved=experiment.create(experimentId:experimentId launchRecipe:launchRecipe resetRecipe:resetRecipe source:source) -- Preserve an isolated experiment snapshot and declared recipes; does not execute recipes.
V P record-experiment-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Restore an intact experiment into a new isolated directory, refusing overwrite.","inputs":{"$cl_type":"t25"},"steps":[{"action":"experiment-restore","args":{"experimentId":{"$input":"experimentId"},"restoreId":{"$input":"restoreId"}},"save":"saved"}]},"key":"record-experiment-restore","section":"procedures"}
P record-experiment-restore(experimentId:str restoreId:str):saved=experiment.restore(experimentId:experimentId restoreId:restoreId) -- Restore an intact experiment into a new isolated directory, refusing overwrite.
V P record-experiment-restore -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Compile a compact NEYVIA/1 program into a validated dependency graph with runtime, permission, budget, and proof contracts.","inputs":{"$cl_type":"t26"},"steps":[{"action":"orchestration-compile","args":{"outputPath":{"$input":"outputPath"},"source":{"$input":"source"}},"save":"saved"}]},"key":"record-orchestration-compile","section":"procedures"}
P record-orchestration-compile(source:str outputPath:json:"{\"type\":\"string\",\"description\":\"Optional screenshot path inside the active workspace. Omit to use the managed artifact path.\"}"):saved=orchestration.compile(outputPath:outputPath source:source) -- Compile a compact NEYVIA/1 program into a validated dependency graph with runtime, permission, budget, and proof contracts.
V P record-orchestration-compile -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Persist a proposed examination challenge pending operator review. Arguments: holdout, proposal.","inputs":{"$cl_type":"t27"},"steps":[{"action":"quality-challenge","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-challenge","section":"procedures"}
P record-quality-challenge(workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" proposal:json:"{\"type\":\"object\"}"}):saved=quality.challenge(arguments:arguments workId:workId) -- Persist a proposed examination challenge pending operator review. Arguments: holdout, proposal.
V P record-quality-challenge -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Apply the same frozen instrument to real baseline and candidate artifacts. Arguments: instrument, baseline, candidate.","inputs":{"$cl_type":"t28"},"steps":[{"action":"quality-compare","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-compare","section":"procedures"}
P record-quality-compare(workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" baseline:str#1..4096 candidate:str#1..4096}):saved=quality.compare(arguments:arguments workId:workId) -- Apply the same frozen instrument to real baseline and candidate artifacts. Arguments: instrument, baseline, candidate.
V P record-quality-compare -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Run all frozen examination instruments on supplied artifact targets. Arguments: holdout, targets.","inputs":{"$cl_type":"t29"},"steps":[{"action":"quality-examine","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-examine","section":"procedures"}
P record-quality-examine(workId:str arguments:{holdout:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" targets:[str#1..4096]#1..20}):saved=quality.examine(arguments:arguments workId:workId) -- Run all frozen examination instruments on supplied artifact targets. Arguments: holdout, targets.
V P record-quality-examine -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Seal an immutable examination with an instruments list. Arguments: i, spec.","inputs":{"$cl_type":"t30"},"steps":[{"action":"quality-holdout","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-holdout","section":"procedures"}
P record-quality-holdout(workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{instruments:json:"{\"type\":\"array\",\"minItems\":1,\"maxItems\":20,\"uniqueItems\":true,\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}}" ..}}):saved=quality.holdout(arguments:arguments workId:workId) -- Seal an immutable examination with an instruments list. Arguments: i, spec.
V P record-quality-holdout -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Seal a json_numeric, image or trace_timing instrument specification. Arguments: i, spec.","inputs":{"$cl_type":"t31"},"steps":[{"action":"quality-instrument","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-instrument","section":"procedures"}
P record-quality-instrument(workId:str arguments:{i:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" spec:{kind:json:"{\"type\":\"string\",\"enum\":[\"json_numeric\",\"image\",\"trace_timing\"]}" key?:str#1..256 max?:num maxMeanMs?:json:"{\"type\":\"number\",\"minimum\":0}" minWidth?:0.. minHeight?:0.. maxBytes?:0..}}):saved=quality.instrument(arguments:arguments workId:workId) -- Seal a json_numeric, image or trace_timing instrument specification. Arguments: i, spec.
V P record-quality-instrument -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Measure an actual scoped artifact and preserve a receipt. Arguments: instrument, target.","inputs":{"$cl_type":"t32"},"steps":[{"action":"quality-measure","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-quality-measure","section":"procedures"}
P record-quality-measure(workId:str arguments:{instrument:json:"{\"type\":\"string\",\"minLength\":1,\"maxLength\":120,\"pattern\":\"^[A-Za-z0-9][A-Za-z0-9_.-]*$\"}" target:str#1..4096}):saved=quality.measure(arguments:arguments workId:workId) -- Measure an actual scoped artifact and preserve a receipt. Arguments: instrument, target.
V P record-quality-measure -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"goal":"Record a provisional contextual correction from real before/after artifacts. Arguments: context, before_path, after_path, correction.","inputs":{"$cl_type":"t33"},"steps":[{"action":"taste-correction","args":{"arguments":{"$input":"arguments"},"workId":{"$input":"workId"}},"save":"saved"}]},"key":"record-taste-correction","section":"procedures"}
P record-taste-correction(workId:str arguments:{context:json:"{\"type\":\"string\",\"enum\":[\"landing-page\",\"product-ui\",\"research\",\"game\"]}" before_path:str#1..4096 after_path:str#1..4096 correction:str#1..12000 agent_id?:str#..120}):saved=taste.correction(arguments:arguments workId:workId) -- Record a provisional contextual correction from real before/after artifacts. Arguments: context, before_path, after_path, correction.
V P record-taste-correction -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"records","data":{"failure":"A reported observation is mistaken for actual provider/model quality","recovery":"Keep evidenceVerified false and use a separately authorized real provider journey."},"key":"0","section":"pitfalls"}
X A reported observation is mistaken for actual provider/model quality -> Keep evidenceVerified false and use a separately authorized real provider journey.
-- @record {"chapter":"records","data":{"failure":"A frozen source, instrument or saved record changes","recovery":"Completion is refused; inspect the owning source and create a new explicit trial."},"key":"1","section":"pitfalls"}
X A frozen source, instrument or saved record changes -> Completion is refused; inspect the owning source and create a new explicit trial.
-- @record {"chapter":"records","data":"No provider model is invoked. No general quality, operator taste or skill improvement is established.","key":"0","section":"frontier"}
F No provider model is invoked. No general quality, operator taste or skill improvement is established.
-- @record {"chapter":"records","data":"Dependency provisioning, host rehearsal and skill mutation require their own fresh execution witness.","key":"1","section":"frontier"}
F Dependency provisioning, host rehearsal and skill mutation require their own fresh execution witness.
-- @record {"chapter":"records","data":"Enable applicable collaboration preferences through the operator seam before a trial.","key":"0","section":"guidance"}
M local-records "Enable applicable collaboration preferences through the operator seam before a trial." src:"authored manual" state:verified
-- @record {"chapter":"records","data":"Instrument criteria establish exactly the measured local artifact property. Preserve failed measurements.","key":"1","section":"guidance"}
M local-records "Instrument criteria establish exactly the measured local artifact property. Preserve failed measurements." src:"authored manual" state:verified
