CL 1
L local-browser-sdk v1 -- Authored executable manual
-- @manual {"chapters":{"evidence":{"title":"Actual owned browser and SDK evidence"}},"clVersion":"1.1","id":"local-browser-sdk","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"neyvia.app_sdk.preview":"t1","neyvia.app_sdk.verify":"t2","neyvia.browser.decide":"t3","neyvia.perception.browser.action":"t4","neyvia.perception.browser.close":"t5","neyvia.perception.browser.observe":"t6","neyvia.perception.browser.open":"t7","workspace.read":"t8"},"tool_metadata":{"neyvia.app_sdk.preview":{"mutability_class":"none"},"neyvia.app_sdk.verify":{"mutability_class":"external_action"},"neyvia.browser.decide":{"mutability_class":"read"},"neyvia.perception.browser.action":{"mutability_class":"external_action"},"neyvia.perception.browser.close":{"mutability_class":"external_action"},"neyvia.perception.browser.open":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"device\":{\"type\":\"string\"},\"port\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":65535}},\"required\":[\"project\",\"port\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"},\"clSource\":{\"type\":\"string\"},\"native\":{\"type\":\"object\"},\"steps\":{\"type\":\"array\",\"items\":{\"type\":\"object\"}}},\"required\":[\"project\",\"url\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"tabId\":{\"type\":\"string\"},\"question\":{\"type\":\"string\"},\"context\":{\"type\":\"object\",\"properties\":{\"goal\":{},\"options\":{},\"progress\":{},\"action_receipts\":{},\"query\":{},\"result\":{},\"previous\":{},\"decision_profile\":{},\"advisory_field\":{},\"evidence\":{}},\"additionalProperties\":false}},\"required\":[\"tabId\",\"question\"],\"allOf\":[{\"properties\":{\"tabId\":{\"not\":{\"enum\":[\"\"]}},\"question\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"browserId\":{\"type\":\"string\"},\"revision\":{\"type\":\"string\"},\"element\":{\"type\":\"string\"},\"action\":{\"enum\":[\"fill\",\"click\"]},\"value\":{\"type\":\"string\"}},\"required\":[\"browserId\",\"revision\",\"element\",\"action\"],\"allOf\":[{\"properties\":{\"browserId\":{\"not\":{\"enum\":[\"\"]}},\"revision\":{\"not\":{\"enum\":[\"\"]}},\"element\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"browserId\":{\"type\":\"string\"}},\"required\":[\"browserId\"],\"allOf\":[{\"properties\":{\"browserId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6{browserId?:str ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\"}},\"required\":[\"url\"],\"allOf\":[{\"properties\":{\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9 json:"{\"type\":\"object\"}"
T t10{url:str ..}
T t11{browserId:str revision:str element:str action:"fill"|"click" value:str ..}
T t12{browserId:str ..}
T t13{project:str device:str port:1..65535 ..}
T t14{project:str url:str clSource:str native:json:"{\"type\":\"object\"}" steps:[json:"{\"type\":\"object\"}"] ..}
T t15{tabId:str question:str context:json:"{\"type\":\"object\",\"properties\":{\"goal\":{},\"options\":{},\"progress\":{},\"action_receipts\":{},\"query\":{},\"result\":{},\"previous\":{},\"decision_profile\":{},\"advisory_field\":{},\"evidence\":{}},\"additionalProperties\":false}" ..}
T t16{observation:str ..}
L local-browser-sdk.evidence v1 -- Actual owned browser and SDK evidence
-- @record {"chapter":"evidence","data":{"args":{},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t9"},"tool":"neyvia.perception.browser.observe"},"key":"private-browser","section":"state"}
S local-browser-sdk.private-browser:json:"{\"type\":\"object\"}"=neyvia.perception.browser.observe()
-- @record {"chapter":"evidence","data":{"effect":"Open a private browser session for exactly this origin; no user profile or downloads.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.perception.browser.open","tool":"neyvia.perception.browser.open"},"key":"perception-browser-open","section":"actions"}
A neyvia.perception.browser.open(url:str) -> json:"{\"type\":\"object\"}" ! -- Open a private browser session for exactly this origin; no user profile or downloads.
F verify-perception-browser-open "No authored observer check is bound to neyvia.perception.browser.open" -> ask operator blocks:neyvia.perception.browser.open
-- @record {"chapter":"evidence","data":{"effect":"Act on a fresh DOM projection; stale revisions fail before any effect. Caller must authorize the action.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.perception.browser.action","tool":"neyvia.perception.browser.action"},"key":"perception-browser-action","section":"actions"}
A neyvia.perception.browser.action(browserId:str revision:str element:str action:"fill"|"click" value?:str) -> json:"{\"type\":\"object\"}" ! -- Act on a fresh DOM projection; stale revisions fail before any effect. Caller must authorize the action.
F verify-perception-browser-action "No authored observer check is bound to neyvia.perception.browser.action" -> ask operator blocks:neyvia.perception.browser.action
-- @record {"chapter":"evidence","data":{"effect":"Close this owned browser session.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.perception.browser.close","tool":"neyvia.perception.browser.close"},"key":"perception-browser-close","section":"actions"}
A neyvia.perception.browser.close(browserId:str) -> json:"{\"type\":\"object\"}" ! -- Close this owned browser session.
F verify-perception-browser-close "No authored observer check is bound to neyvia.perception.browser.close" -> ask operator blocks:neyvia.perception.browser.close
-- @record {"chapter":"evidence","data":{"effect":"Open an SDK app in Mobile Studio's existing phone frame. port is the explicit running Neyvia backend port.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.app_sdk.preview","tool":"neyvia.app_sdk.preview"},"key":"app_sdk-preview","section":"actions"}
A neyvia.app_sdk.preview(project:str device?:str port:1..65535) -> json:"{\"type\":\"object\"}" ! -- Open an SDK app in Mobile Studio's existing phone frame. port is the explicit running Neyvia backend port.
F verify-app_sdk-preview "No authored observer check is bound to neyvia.app_sdk.preview" -> ask operator blocks:neyvia.app_sdk.preview
-- @record {"chapter":"evidence","data":{"effect":"Run the app's goals through T18 web perception and optional T16 native inspection; failed goals refuse completion. Uses an explicit running-app URL.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.app_sdk.verify","tool":"neyvia.app_sdk.verify"},"key":"app_sdk-verify","section":"actions"}
A neyvia.app_sdk.verify(project:str url:str clSource?:str native?:json:"{\"type\":\"object\"}" steps?:[json:"{\"type\":\"object\"}"]) -> json:"{\"type\":\"object\"}" ! -- Run the app's goals through T18 web perception and optional T16 native inspection; failed goals refuse completion. Uses an explicit running-app URL.
F verify-app_sdk-verify "No authored observer check is bound to neyvia.app_sdk.verify" -> ask operator blocks:neyvia.app_sdk.verify
-- @record {"chapter":"evidence","data":{"effect":"Acquire fresh native DOM and ask the attached LAYA service; explicit unavailable fallback, advisory only.","pre":"Actual configured owned Neyvia browser, current source and authorized local runtime; exact fresh revision for browser actions","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.browser.decide","tool":"neyvia.browser.decide"},"key":"browser-decide","section":"actions"}
A neyvia.browser.decide(tabId:str question:str context?:json:"{\"type\":\"object\",\"properties\":{\"goal\":{},\"options\":{},\"progress\":{},\"action_receipts\":{},\"query\":{},\"result\":{},\"previous\":{},\"decision_profile\":{},\"advisory_field\":{},\"evidence\":{}},\"additionalProperties\":false}") -> json:"{\"type\":\"object\"}" -- Acquire fresh native DOM and ask the attached LAYA service; explicit unavailable fallback, advisory only.
F verify-browser-decide "No authored observer check is bound to neyvia.browser.decide" -> ask operator blocks:neyvia.browser.decide
-- @record {"chapter":"evidence","data":{"effect":"Read the exact mounted-runtime witness bytes","pre":"Use the bounded observation captured from the actual mounted child realm","returns":{"$cl_type":"t9"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"read-sdk-observation","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> json:"{\"type\":\"object\"}" -- Read the exact mounted-runtime witness bytes
C workspace.read sdk-native-observation:matches(workspace.read(path:observation) .content {allOf:[{pattern:"\"actualMountedControlChangesState\"\\s*:\\s*true"} {pattern:"\"nativeAppPixelsPresent\"\\s*:\\s*true"} {pattern:"\"nativePhoneActuallyVisible\"\\s*:\\s*true"} {pattern:"\"previewActualPositiveCL\"\\s*:\\s*true"} {pattern:"\"currentManualEffectReceipt\"\\s*:\\s*true"}] type:"string"})
-- @record {"chapter":"evidence","data":{"args":{"path":{"$input":"observation"}},"expect":{"op":"schema","path":"content","schema":{"allOf":[{"pattern":"\"actualMountedControlChangesState\"\\s*:\\s*true"},{"pattern":"\"nativeAppPixelsPresent\"\\s*:\\s*true"},{"pattern":"\"nativePhoneActuallyVisible\"\\s*:\\s*true"},{"pattern":"\"previewActualPositiveCL\"\\s*:\\s*true"},{"pattern":"\"currentManualEffectReceipt\"\\s*:\\s*true"}],"type":"string"}},"tool":"workspace.read"},"key":"sdk-native-observation","section":"checks"}
C workspace.read sdk-native-observation:matches(workspace.read(path:observation) .content {allOf:[{pattern:"\"actualMountedControlChangesState\"\\s*:\\s*true"} {pattern:"\"nativeAppPixelsPresent\"\\s*:\\s*true"} {pattern:"\"nativePhoneActuallyVisible\"\\s*:\\s*true"} {pattern:"\"previewActualPositiveCL\"\\s*:\\s*true"} {pattern:"\"currentManualEffectReceipt\"\\s*:\\s*true"}] type:"string"})
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t10"},"steps":[{"action":"perception-browser-open","args":{"url":{"$input":"url"}},"save":"effect"}]},"key":"perception-browser-open","section":"procedures"}
P perception-browser-open(url:str):effect=neyvia.perception.browser.open(url:url) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P perception-browser-open -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t11"},"steps":[{"action":"perception-browser-action","args":{"action":{"$input":"action"},"browserId":{"$input":"browserId"},"element":{"$input":"element"},"revision":{"$input":"revision"},"value":{"$input":"value"}},"save":"effect"}]},"key":"perception-browser-action","section":"procedures"}
P perception-browser-action(browserId:str revision:str element:str action:"fill"|"click" value:str):effect=neyvia.perception.browser.action(action:action browserId:browserId element:element revision:revision value:value) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P perception-browser-action -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t12"},"steps":[{"action":"perception-browser-close","args":{"browserId":{"$input":"browserId"}},"save":"effect"}]},"key":"perception-browser-close","section":"procedures"}
P perception-browser-close(browserId:str):effect=neyvia.perception.browser.close(browserId:browserId) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P perception-browser-close -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t13"},"steps":[{"action":"app_sdk-preview","args":{"device":{"$input":"device"},"port":{"$input":"port"},"project":{"$input":"project"}},"save":"effect"}]},"key":"app_sdk-preview","section":"procedures"}
P app_sdk-preview(project:str device:str port:1..65535):effect=neyvia.app_sdk.preview(device:device port:port project:project) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P app_sdk-preview -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t14"},"steps":[{"action":"app_sdk-verify","args":{"clSource":{"$input":"clSource"},"native":{"$input":"native"},"project":{"$input":"project"},"steps":{"$input":"steps"},"url":{"$input":"url"}},"save":"effect"}]},"key":"app_sdk-verify","section":"procedures"}
P app_sdk-verify(project:str url:str clSource:str native:json:"{\"type\":\"object\"}" steps:[json:"{\"type\":\"object\"}"]):effect=neyvia.app_sdk.verify(clSource:clSource native:native project:project steps:steps url:url) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P app_sdk-verify -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Execute the actual browser or SDK journey and independently verify fresh owner state","inputs":{"$cl_type":"t15"},"steps":[{"action":"browser-decide","args":{"context":{"$input":"context"},"question":{"$input":"question"},"tabId":{"$input":"tabId"}},"save":"effect"}]},"key":"browser-decide","section":"procedures"}
P browser-decide(tabId:str question:str context:json:"{\"type\":\"object\",\"properties\":{\"goal\":{},\"options\":{},\"progress\":{},\"action_receipts\":{},\"query\":{},\"result\":{},\"previous\":{},\"decision_profile\":{},\"advisory_field\":{},\"evidence\":{}},\"additionalProperties\":false}"):effect=neyvia.browser.decide(context:context question:question tabId:tabId) -- Execute the actual browser or SDK journey and independently verify fresh owner state
V P browser-decide -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"The actual mounted SDK child realm changes shared state and paints native iframe content","inputs":{"$cl_type":"t16"},"steps":[{"action":"read-sdk-observation","args":{"path":{"$input":"observation"}},"check":"sdk-native-observation","save":"mounted"}]},"key":"prove-sdk-mounted-observation","section":"procedures"}
P prove-sdk-mounted-observation(observation:str):mounted=workspace.read(path:observation) C sdk-native-observation -- The actual mounted SDK child realm changes shared state and paints native iframe content
V P prove-sdk-mounted-observation -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"failure":"Observed revision or retained proof changes","recovery":"Observe again and run the requested operation against current state; never accept stale evidence."},"key":"0","section":"pitfalls"}
X Observed revision or retained proof changes -> Observe again and run the requested operation against current state; never accept stale evidence.
-- @record {"chapter":"evidence","data":{"failure":"Phone layout passes but the iframe is blank","recovery":"Require the mounted child identity, a real increment and native pixels. A separate same-URL context cannot replace the child realm."},"key":"1","section":"pitfalls"}
X Phone layout passes but the iframe is blank -> Require the mounted child identity, a real increment and native pixels. A separate same-URL context cannot replace the child realm.
-- @record {"chapter":"evidence","data":"Visible WebView2 promotion needs an allowed desktop and actual native import plus fresh observed DOM. This task prohibits visible windows.","key":"0","section":"frontier"}
F Visible WebView2 promotion needs an allowed desktop and actual native import plus fresh observed DOM. This task prohibits visible windows.
-- @record {"chapter":"evidence","data":"Use actual configured Neyvia headless contexts; require fresh observed revisions before DOM actions.","key":"0","section":"guidance"}
M local-browser-sdk "Use actual configured Neyvia headless contexts; require fresh observed revisions before DOM actions." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"SDK verification executes the authored contract journey and retains source hashes, actual state and screenshot bytes.","key":"1","section":"guidance"}
M local-browser-sdk "SDK verification executes the authored contract journey and retains source hashes, actual state and screenshot bytes." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"SDK previews need a mounted Phone iframe and delivered owner event.","key":"2","section":"guidance"}
M local-browser-sdk "SDK previews need a mounted Phone iframe and delivered owner event." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"LAYA decisions require the actual frozen local service and durable advisory receipts; advice grants no action authority.","key":"3","section":"guidance"}
M local-browser-sdk "LAYA decisions require the actual frozen local service and durable advisory receipts; advice grants no action authority." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"Observe the sole owned private browser session before acting; multiple sessions require an existing host-selected identity. Transport stamps stay internal. The observer starts no browser.","key":"4","section":"guidance"}
M local-browser-sdk "Observe the sole owned private browser session before acting; multiple sessions require an existing host-selected identity. Transport stamps stay internal. The observer starts no browser." src:"authored manual" state:verified
