CL 1
L local-media v1 -- Authored executable manual
-- @manual {"chapters":{"evidence":{"title":"Fresh retained browser, video and skill evidence"}},"clVersion":"1.1","id":"local-media","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"preview.annotate":"t1","preview.screenshot":"t2","preview.taste":"t3","skill.live.iterate":"t4","video.digest":"t5"},"tool_metadata":{"preview.annotate":{"mutability_class":"artifact_write"},"preview.screenshot":{"mutability_class":"artifact_write"},"preview.taste":{"mutability_class":"artifact_write"},"skill.live.iterate":{"mutability_class":"file_write"},"video.digest":{"mutability_class":"artifact_write"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\"},\"rectangle\":{\"type\":\"object\"},\"comment\":{\"type\":\"string\"},\"viewport\":{\"type\":\"object\"},\"outputDir\":{\"type\":\"string\"},\"delayMs\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":10000}},\"required\":[\"url\",\"rectangle\"],\"allOf\":[{\"properties\":{\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\"},\"outputPath\":{\"type\":\"string\"},\"fullPage\":{\"type\":\"boolean\"},\"width\":{\"type\":\"integer\",\"minimum\":320,\"maximum\":3840},\"height\":{\"type\":\"integer\",\"minimum\":240,\"maximum\":2160},\"waitFor\":{\"type\":\"string\"},\"delayMs\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":10000},\"waitUntil\":{\"type\":\"string\",\"enum\":[\"domcontentloaded\",\"load\",\"networkidle\"]}},\"required\":[\"url\"],\"allOf\":[{\"properties\":{\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\"},\"goal\":{\"type\":\"string\",\"maxLength\":600},\"viewports\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"desktop\",\"phone\"]}},\"colorScheme\":{\"type\":\"string\",\"enum\":[\"dark\",\"light\"]},\"waitFor\":{\"type\":\"string\"},\"delayMs\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":10000},\"includeImageData\":{\"type\":\"boolean\",\"description\":\"Inline capped screenshots for the installed desktop Preview, which has no HTTP artifact route.\"},\"journey\":{\"type\":\"object\",\"description\":\"Controls to exercise through Laya: actions [{kind: click|fill|select|press, label, value?, expect?}], expect [{kind: selector_text|text_present|selector_exists|url_contains, ...}].\"},\"outputDir\":{\"type\":\"string\",\"description\":\"Optional report directory inside the active workspace. Omit to use the managed artifact directory.\"}},\"required\":[\"url\"],\"allOf\":[{\"properties\":{\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"skillId\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"content\":{\"type\":\"string\"},\"expectedSha256\":{\"type\":\"string\"},\"sessionId\":{\"type\":\"string\"},\"request\":{\"type\":\"string\"}},\"required\":[\"path\",\"content\",\"sessionId\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}},\"content\":{\"not\":{\"enum\":[\"\"]}},\"sessionId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"outputDir\":{\"type\":\"string\"},\"maxFrames\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":36},\"maxSceneFrames\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":24},\"sceneThreshold\":{\"type\":\"number\",\"minimum\":0.05,\"maximum\":0.95},\"sceneScanSeconds\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":3600},\"extractAudio\":{\"type\":\"boolean\"},\"transcribe\":{\"type\":\"string\",\"enum\":[\"auto\",\"none\",\"local\"]},\"whisperModel\":{\"type\":\"string\"},\"timeoutSeconds\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":7200}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\"}"
T t7{url:str outputPath:str fullPage:bool width:320..3840 height:240..2160 waitFor:str delayMs:0..10000 waitUntil:json:"{\"type\":\"string\",\"enum\":[\"domcontentloaded\",\"load\",\"networkidle\"]}" ..}
T t8{url:str rectangle:json:"{\"type\":\"object\"}" comment:str viewport:json:"{\"type\":\"object\"}" outputDir:str delayMs:0..10000 ..}
T t9{url:str goal:str#..600 viewports:[json:"{\"type\":\"string\",\"enum\":[\"desktop\",\"phone\"]}"] colorScheme:json:"{\"type\":\"string\",\"enum\":[\"dark\",\"light\"]}" waitFor:str delayMs:0..10000 includeImageData:json:"{\"type\":\"boolean\",\"description\":\"Inline capped screenshots for the installed desktop Preview, which has no HTTP artifact route.\"}" journey:json:"{\"type\":\"object\",\"description\":\"Controls to exercise through Laya: actions [{kind: click|fill|select|press, label, value?, expect?}], expect [{kind: selector_text|text_present|selector_exists|url_contains, ...}].\"}" outputDir:json:"{\"type\":\"string\",\"description\":\"Optional report directory inside the active workspace. Omit to use the managed artifact directory.\"}" ..}
T t10{path:str outputDir:str maxFrames:1..36 maxSceneFrames:0..24 sceneThreshold:0.05..0.95 sceneScanSeconds:1..3600 extractAudio:bool transcribe:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"none\",\"local\"]}" whisperModel:str timeoutSeconds:1..7200 ..}
T t11{skillId:str path:str content:str expectedSha256:str sessionId:str request:str ..}
L local-media.evidence v1 -- Fresh retained browser, video and skill evidence
-- @record {"chapter":"evidence","data":{"effect":"Capture a real PNG from a URL with Playwright or Chromium and return dimensions, SHA-256, and engine proof.","pre":"Authorized current browser URL, workspace-owned artifacts and successful real rendering","returns":{"$cl_type":"t6"},"reversible":false,"schema":"preview.screenshot","tool":"preview.screenshot"},"key":"preview-screenshot","section":"actions"}
A preview.screenshot(url:str outputPath?:str fullPage?:bool width?:320..3840 height?:240..2160 waitFor?:str delayMs?:0..10000 waitUntil?:json:"{\"type\":\"string\",\"enum\":[\"domcontentloaded\",\"load\",\"networkidle\"]}") -> json:"{\"type\":\"object\"}" ! -- Capture a real PNG from a URL with Playwright or Chromium and return dimensions, SHA-256, and engine proof.
F verify-preview-screenshot "No authored observer check is bound to preview.screenshot" -> ask operator blocks:preview.screenshot
-- @record {"chapter":"evidence","data":{"effect":"Capture a preview, draw an operator-selected rectangle and comment, create a cropped region, and write a W3C-shaped annotation receipt with hashes.","pre":"Authorized current browser URL, workspace-owned artifacts and successful real rendering","returns":{"$cl_type":"t6"},"reversible":false,"schema":"preview.annotate","tool":"preview.annotate"},"key":"preview-annotate","section":"actions"}
A preview.annotate(url:str rectangle:json:"{\"type\":\"object\"}" comment?:str viewport?:json:"{\"type\":\"object\"}" outputDir?:str delayMs?:0..10000) -> json:"{\"type\":\"object\"}" ! -- Capture a preview, draw an operator-selected rectangle and comment, create a cropped region, and write a W3C-shaped annotation receipt with hashes.
F verify-preview-annotate "No authored observer check is bound to preview.annotate" -> ask operator blocks:preview.annotate
-- @record {"chapter":"evidence","data":{"effect":"See and measure your own rendered UI before calling visual work done. Renders the page at desktop and phone widths, returns screenshots to inspect, and reports colliding text, overflow, contrast, typeface and colour discipline, tap targets, competing primary actions and box clutter with evidence and fixes. Optional journey: Laya exercises the controls the goal depends on and reports what it actually tested. Use this tool for a Laya browser journey: provide the page URL, goal, and journey actions with expected outcomes. Measurements inform judgment; they never certify beauty.","pre":"Authorized current browser URL, workspace-owned artifacts and successful real rendering","returns":{"$cl_type":"t6"},"reversible":false,"schema":"preview.taste","tool":"preview.taste"},"key":"preview-taste","section":"actions"}
A preview.taste(url:str goal?:str#..600 viewports?:[json:"{\"type\":\"string\",\"enum\":[\"desktop\",\"phone\"]}"] colorScheme?:json:"{\"type\":\"string\",\"enum\":[\"dark\",\"light\"]}" waitFor?:str delayMs?:0..10000 includeImageData?:json:"{\"type\":\"boolean\",\"description\":\"Inline capped screenshots for the installed desktop Preview, which has no HTTP artifact route.\"}" journey?:json:"{\"type\":\"object\",\"description\":\"Controls to exercise through Laya: actions [{kind: click|fill|select|press, label, value?, expect?}], expect [{kind: selector_text|text_present|selector_exists|url_contains, ...}].\"}" outputDir?:json:"{\"type\":\"string\",\"description\":\"Optional report directory inside the active workspace. Omit to use the managed artifact directory.\"}") -> json:"{\"type\":\"object\"}" ! -- See and measure your own rendered UI before calling visual work done. Renders the page at desktop and phone widths, returns screenshots to inspect, and reports colliding text, overflow, contrast, typeface and colour discipline, tap targets, competing primary actions and box clutter with evidence and fixes. Optional journey: Laya exercises the controls the goal depends on and reports what it actually tested. Use this tool for a Laya browser journey: provide the page URL, goal, and journey actions with expected outcomes. Measurements inform judgment; they never certify beauty.
F verify-preview-taste "No authored observer check is bound to preview.taste" -> ask operator blocks:preview.taste
-- @record {"chapter":"evidence","data":{"effect":"Convert a video into model-readable timestamped frames, scene-change frames, a storyboard, audio, optional local Whisper transcript, and a JSON manifest.","pre":"Intact scoped video input, installed FFmpeg and FFprobe, workspace-owned outputs","returns":{"$cl_type":"t6"},"reversible":false,"schema":"video.digest","tool":"video.digest"},"key":"video-digest","section":"actions"}
A video.digest(path:str outputDir?:str maxFrames?:1..36 maxSceneFrames?:0..24 sceneThreshold?:0.05..0.95 sceneScanSeconds?:1..3600 extractAudio?:bool transcribe?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"none\",\"local\"]}" whisperModel?:str timeoutSeconds?:1..7200) -> json:"{\"type\":\"object\"}" ! -- Convert a video into model-readable timestamped frames, scene-change frames, a storyboard, audio, optional local Whisper transcript, and a JSON manifest.
F verify-video-digest "No authored observer check is bound to video.digest" -> ask operator blocks:video.digest
-- @record {"chapter":"evidence","data":{"effect":"Validate and atomically revise a live session SKILL.md with optimistic conflict detection, an external backup, and durable version receipts.","pre":"Local Codex SKILL.md, valid replacement, exact loaded version hash and host-managed session","returns":{"$cl_type":"t6"},"reversible":false,"schema":"skill.live.iterate","tool":"skill.live.iterate"},"key":"skill-live-iterate","section":"actions"}
A skill.live.iterate(skillId?:str path:str content:str expectedSha256?:str sessionId:str request?:str) -> json:"{\"type\":\"object\"}" ! -- Validate and atomically revise a live session SKILL.md with optimistic conflict detection, an external backup, and durable version receipts.
F verify-skill-live-iterate "No authored observer check is bound to skill.live.iterate" -> ask operator blocks:skill.live.iterate
-- @record {"chapter":"evidence","data":{"goal":"Capture and independently verify retained media bytes, requested inputs and persisted receipts","inputs":{"$cl_type":"t7"},"steps":[{"action":"preview-screenshot","args":{"delayMs":{"$input":"delayMs"},"fullPage":{"$input":"fullPage"},"height":{"$input":"height"},"outputPath":{"$input":"outputPath"},"url":{"$input":"url"},"waitFor":{"$input":"waitFor"},"waitUntil":{"$input":"waitUntil"},"width":{"$input":"width"}},"save":"effect"}]},"key":"preview-screenshot","section":"procedures"}
P preview-screenshot(url:str outputPath:str fullPage:bool width:320..3840 height:240..2160 waitFor:str delayMs:0..10000 waitUntil:json:"{\"type\":\"string\",\"enum\":[\"domcontentloaded\",\"load\",\"networkidle\"]}"):effect=preview.screenshot(delayMs:delayMs fullPage:fullPage height:height outputPath:outputPath url:url waitFor:waitFor waitUntil:waitUntil width:width) -- Capture and independently verify retained media bytes, requested inputs and persisted receipts
V P preview-screenshot -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Capture and independently verify retained media bytes, requested inputs and persisted receipts","inputs":{"$cl_type":"t8"},"steps":[{"action":"preview-annotate","args":{"comment":{"$input":"comment"},"delayMs":{"$input":"delayMs"},"outputDir":{"$input":"outputDir"},"rectangle":{"$input":"rectangle"},"url":{"$input":"url"},"viewport":{"$input":"viewport"}},"save":"effect"}]},"key":"preview-annotate","section":"procedures"}
P preview-annotate(url:str rectangle:json:"{\"type\":\"object\"}" comment:str viewport:json:"{\"type\":\"object\"}" outputDir:str delayMs:0..10000):effect=preview.annotate(comment:comment delayMs:delayMs outputDir:outputDir rectangle:rectangle url:url viewport:viewport) -- Capture and independently verify retained media bytes, requested inputs and persisted receipts
V P preview-annotate -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Capture and independently verify retained media bytes, requested inputs and persisted receipts","inputs":{"$cl_type":"t9"},"steps":[{"action":"preview-taste","args":{"colorScheme":{"$input":"colorScheme"},"delayMs":{"$input":"delayMs"},"goal":{"$input":"goal"},"includeImageData":{"$input":"includeImageData"},"journey":{"$input":"journey"},"outputDir":{"$input":"outputDir"},"url":{"$input":"url"},"viewports":{"$input":"viewports"},"waitFor":{"$input":"waitFor"}},"save":"effect"}]},"key":"preview-taste","section":"procedures"}
P preview-taste(url:str goal:str#..600 viewports:[json:"{\"type\":\"string\",\"enum\":[\"desktop\",\"phone\"]}"] colorScheme:json:"{\"type\":\"string\",\"enum\":[\"dark\",\"light\"]}" waitFor:str delayMs:0..10000 includeImageData:json:"{\"type\":\"boolean\",\"description\":\"Inline capped screenshots for the installed desktop Preview, which has no HTTP artifact route.\"}" journey:json:"{\"type\":\"object\",\"description\":\"Controls to exercise through Laya: actions [{kind: click|fill|select|press, label, value?, expect?}], expect [{kind: selector_text|text_present|selector_exists|url_contains, ...}].\"}" outputDir:json:"{\"type\":\"string\",\"description\":\"Optional report directory inside the active workspace. Omit to use the managed artifact directory.\"}"):effect=preview.taste(colorScheme:colorScheme delayMs:delayMs goal:goal includeImageData:includeImageData journey:journey outputDir:outputDir url:url viewports:viewports waitFor:waitFor) -- Capture and independently verify retained media bytes, requested inputs and persisted receipts
V P preview-taste -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Capture and independently verify retained media bytes, requested inputs and persisted receipts","inputs":{"$cl_type":"t10"},"steps":[{"action":"video-digest","args":{"extractAudio":{"$input":"extractAudio"},"maxFrames":{"$input":"maxFrames"},"maxSceneFrames":{"$input":"maxSceneFrames"},"outputDir":{"$input":"outputDir"},"path":{"$input":"path"},"sceneScanSeconds":{"$input":"sceneScanSeconds"},"sceneThreshold":{"$input":"sceneThreshold"},"timeoutSeconds":{"$input":"timeoutSeconds"},"transcribe":{"$input":"transcribe"},"whisperModel":{"$input":"whisperModel"}},"save":"effect"}]},"key":"video-digest","section":"procedures"}
P video-digest(path:str outputDir:str maxFrames:1..36 maxSceneFrames:0..24 sceneThreshold:0.05..0.95 sceneScanSeconds:1..3600 extractAudio:bool transcribe:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"none\",\"local\"]}" whisperModel:str timeoutSeconds:1..7200):effect=video.digest(extractAudio:extractAudio maxFrames:maxFrames maxSceneFrames:maxSceneFrames outputDir:outputDir path:path sceneScanSeconds:sceneScanSeconds sceneThreshold:sceneThreshold timeoutSeconds:timeoutSeconds transcribe:transcribe whisperModel:whisperModel) -- Capture and independently verify retained media bytes, requested inputs and persisted receipts
V P video-digest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"goal":"Capture and independently verify retained media bytes, requested inputs and persisted receipts","inputs":{"$cl_type":"t11"},"steps":[{"action":"skill-live-iterate","args":{"content":{"$input":"content"},"expectedSha256":{"$input":"expectedSha256"},"path":{"$input":"path"},"request":{"$input":"request"},"sessionId":{"$input":"sessionId"},"skillId":{"$input":"skillId"}},"save":"effect"}]},"key":"skill-live-iterate","section":"procedures"}
P skill-live-iterate(skillId:str path:str content:str expectedSha256:str sessionId:str request:str):effect=skill.live.iterate(content:content expectedSha256:expectedSha256 path:path request:request sessionId:sessionId skillId:skillId) -- Capture and independently verify retained media bytes, requested inputs and persisted receipts
V P skill-live-iterate -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"evidence","data":{"failure":"Retained proof changes after capture","recovery":"Restore the exact retained bytes or make a new capture and verify it."},"key":"0","section":"pitfalls"}
X Retained proof changes after capture -> Restore the exact retained bytes or make a new capture and verify it.
-- @record {"chapter":"evidence","data":"Remote authenticated pages and model-backed Laya journeys need account and provider authority.","key":"0","section":"frontier"}
F Remote authenticated pages and model-backed Laya journeys need account and provider authority.
-- @record {"chapter":"evidence","data":"Capture pages in the current browser; verify PNG byte hashes and requested geometry.","key":"0","section":"guidance"}
M local-media "Capture pages in the current browser; verify PNG byte hashes and requested geometry." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"Video needs installed FFmpeg and FFprobe; bind actual selected frames, timestamps, storyboard, audio and transcript artifacts.","key":"1","section":"guidance"}
M local-media "Video needs installed FFmpeg and FFprobe; bind actual selected frames, timestamps, storyboard, audio and transcript artifacts." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"Skill revisions retain loaded-version CAS, validated contents, preserved original, durable receipt and ledger. Session identity belongs to the host.","key":"2","section":"guidance"}
M local-media "Skill revisions retain loaded-version CAS, validated contents, preserved original, durable receipt and ledger. Session identity belongs to the host." src:"authored manual" state:verified
-- @record {"chapter":"evidence","data":"Taste measures retained captures; it never certifies beauty.","key":"3","section":"guidance"}
M local-media "Taste measures retained captures; it never certifies beauty." src:"authored manual" state:verified
