CL 1
L local-host v1 -- Authored executable manual
-- @manual {"chapters":{"host":{"title":"Owned process and plugin effects"}},"clVersion":"1.1","id":"local-host","kind":"workflow","proofs":{"area":"local-host-journey, installed-preflight-journey","manifests":["config/proofs/local-host-journey.json","config/proofs/installed-preflight-journey.json"]},"schema":"neyvia.manual.v1","schemas":{"codex.plugins.call":"t1","host.inspect_preview":"t2","host.launch":"t3","host.launch_file":"t4","host.stop":"t5"},"tool_metadata":{"codex.plugins.call":{"mutability_class":"external_write"},"host.inspect_preview":{"mutability_class":"artifact_write"},"host.launch":{"mutability_class":"process_execute"},"host.launch_file":{"mutability_class":"process_execute"},"host.stop":{"mutability_class":"process_execute"}}}
-- @proof {"checkedAt":["grant_agent.proofs_local_host_journey.self_check","grant_agent.creative_tools.CreativeToolRuntime.call","grant_agent.installed_programs.InstalledPrograms.prepare_file","grant_agent.installed_programs.InstalledPrograms.launch_file","grant_agent.installed_programs.InstalledPrograms.launch","grant_agent.installed_programs.InstalledPrograms._work","grant_agent.installed_programs.InstalledPrograms.status","grant_agent.cl.fixcl4_host_effects.snapshot_for","grant_agent.cl.fixcl4_host_effects.checks_for","grant_agent.cl.fixcl4_host_effects._verify","grant_agent.cl.fixcl4_host_effects.process_identity"],"claim":"A scoped host.launch_file journey runs an existing script through Neyvia's local host owner, freshly observes the completed session and exact nonce-bearing output, and refuses a source path outside the selected workspace without adding a session.","id":"p22.local-host.managed-process-journey","impact":["local-host managed process launch","host.launch_file","workspace path boundary"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"server\":{\"type\":\"string\"},\"tool\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\"},\"effect\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}},\"required\":[\"server\",\"tool\"],\"additionalProperties\":false,\"allOf\":[{\"properties\":{\"server\":{\"not\":{\"enum\":[\"\"]}},\"tool\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"}},\"required\":[\"sessionId\",\"url\"],\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}},\"url\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"executable\":{\"type\":\"string\"},\"arguments\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"timeoutSeconds\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":86400}},\"required\":[\"executable\"],\"allOf\":[{\"properties\":{\"executable\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"arguments\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"timeoutSeconds\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":86400}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"expectedRevision\":{\"type\":\"integer\",\"minimum\":0}},\"required\":[\"sessionId\"],\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\"}"
T t7 json:"{\"type\":\"object\",\"properties\":{\"server\":{\"type\":\"string\"},\"tool\":{\"type\":\"string\"},\"arguments\":{\"type\":\"object\"},\"effect\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}},\"required\":[\"server\",\"tool\",\"effect\",\"arguments\"],\"additionalProperties\":false}"
T t8{sessionId:str url:str ..}
T t9{executable:str arguments:[str] timeoutSeconds:1..86400 ..}
T t10{path:str arguments:[str] timeoutSeconds:1..86400 ..}
T t11{sessionId:str expectedRevision:0.. ..}
L local-host.host v1 -- Owned process and plugin effects
-- @record {"chapter":"host","data":{"effect":"Fresh exact kernel process and owner state or independently observed requested file bytes","pre":"Owned managed session or explicitly configured reviewed workspace plugin","returns":{"$cl_type":"t6"},"reversible":true,"schema":"codex.plugins.call","tool":"codex.plugins.call"},"key":"codex-plugins-call","section":"actions"}
A codex.plugins.call(server:str tool:str arguments?:json:"{\"type\":\"object\"}" effect?:{path:str sha256:str ~"^[a-f0-9]{64}$"}) -> json:"{\"type\":\"object\"}" ! -- Fresh exact kernel process and owner state or independently observed requested file bytes
F verify-codex-plugins-call "No authored observer check is bound to codex.plugins.call" -> ask operator blocks:codex.plugins.call
-- @record {"chapter":"host","data":{"effect":"Fresh exact kernel process and owner state or independently observed requested file bytes","pre":"Owned managed session or explicitly configured reviewed workspace plugin","returns":{"$cl_type":"t6"},"reversible":true,"schema":"host.inspect_preview","tool":"host.inspect_preview"},"key":"host-inspect_preview","section":"actions"}
A host.inspect_preview(sessionId:str url:str) -> json:"{\"type\":\"object\"}" ! -- Fresh exact kernel process and owner state or independently observed requested file bytes
F verify-host-inspect_preview "No authored observer check is bound to host.inspect_preview" -> ask operator blocks:host.inspect_preview
-- @record {"chapter":"host","data":{"effect":"Fresh exact kernel process and owner state or independently observed requested file bytes","pre":"Owned managed session or explicitly configured reviewed workspace plugin","returns":{"$cl_type":"t6"},"reversible":true,"schema":"host.launch","tool":"host.launch"},"key":"host-launch","section":"actions"}
A host.launch(executable:str arguments?:[str] timeoutSeconds?:1..86400) -> json:"{\"type\":\"object\"}" ! -- Fresh exact kernel process and owner state or independently observed requested file bytes
F verify-host-launch "No authored observer check is bound to host.launch" -> ask operator blocks:host.launch
-- @record {"chapter":"host","data":{"effect":"Fresh exact kernel process and owner state or independently observed requested file bytes","pre":"Owned managed session or explicitly configured reviewed workspace plugin","returns":{"$cl_type":"t6"},"reversible":true,"schema":"host.launch_file","tool":"host.launch_file"},"key":"host-launch_file","section":"actions"}
A host.launch_file(path:str arguments?:[str] timeoutSeconds?:1..86400) -> json:"{\"type\":\"object\"}" ! -- Fresh exact kernel process and owner state or independently observed requested file bytes
F verify-host-launch_file "No authored observer check is bound to host.launch_file" -> ask operator blocks:host.launch_file
-- @record {"chapter":"host","data":{"effect":"Fresh exact kernel process and owner state or independently observed requested file bytes","pre":"Owned managed session or explicitly configured reviewed workspace plugin","returns":{"$cl_type":"t6"},"reversible":false,"schema":"host.stop","tool":"host.stop"},"key":"host-stop","section":"actions"}
A host.stop(sessionId:str expectedRevision?:0..) -> json:"{\"type\":\"object\"}" ! -- Fresh exact kernel process and owner state or independently observed requested file bytes
F verify-host-stop "No authored observer check is bound to host.stop" -> ask operator blocks:host.stop
-- @record {"chapter":"host","data":{"goal":"Fresh exact kernel process and owner state or independently observed requested file bytes","inputs":{"$cl_type":"t7"},"steps":[{"action":"codex-plugins-call","args":{"arguments":{"$input":"arguments"},"effect":{"$input":"effect"},"server":{"$input":"server"},"tool":{"$input":"tool"}},"save":"effect"}]},"key":"codex-plugins-call","section":"procedures"}
P codex-plugins-call(server:str tool:str arguments:json:"{\"type\":\"object\"}" effect:{path:str sha256:str ~"^[a-f0-9]{64}$"}):effect=codex.plugins.call(arguments:arguments effect:effect server:server tool:tool) -- Fresh exact kernel process and owner state or independently observed requested file bytes
V P codex-plugins-call -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"host","data":{"goal":"Fresh exact kernel process and owner state or independently observed requested file bytes","inputs":{"$cl_type":"t8"},"steps":[{"action":"host-inspect_preview","args":{"sessionId":{"$input":"sessionId"},"url":{"$input":"url"}},"save":"effect"}]},"key":"host-inspect_preview","section":"procedures"}
P host-inspect_preview(sessionId:str url:str):effect=host.inspect_preview(sessionId:sessionId url:url) -- Fresh exact kernel process and owner state or independently observed requested file bytes
V P host-inspect_preview -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"host","data":{"goal":"Fresh exact kernel process and owner state or independently observed requested file bytes","inputs":{"$cl_type":"t9"},"steps":[{"action":"host-launch","args":{"arguments":{"$input":"arguments"},"executable":{"$input":"executable"},"timeoutSeconds":{"$input":"timeoutSeconds"}},"save":"effect"}]},"key":"host-launch","section":"procedures"}
P host-launch(executable:str arguments:[str] timeoutSeconds:1..86400):effect=host.launch(arguments:arguments executable:executable timeoutSeconds:timeoutSeconds) -- Fresh exact kernel process and owner state or independently observed requested file bytes
V P host-launch -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"host","data":{"goal":"Fresh exact kernel process and owner state or independently observed requested file bytes","inputs":{"$cl_type":"t10"},"steps":[{"action":"host-launch_file","args":{"arguments":{"$input":"arguments"},"path":{"$input":"path"},"timeoutSeconds":{"$input":"timeoutSeconds"}},"save":"effect"}]},"key":"host-launch_file","section":"procedures"}
P host-launch_file(path:str arguments:[str] timeoutSeconds:1..86400):effect=host.launch_file(arguments:arguments path:path timeoutSeconds:timeoutSeconds) -- Fresh exact kernel process and owner state or independently observed requested file bytes
V P host-launch_file -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"host","data":{"goal":"Fresh exact kernel process and owner state or independently observed requested file bytes","inputs":{"$cl_type":"t11"},"steps":[{"action":"host-stop","args":{"expectedRevision":{"$input":"expectedRevision"},"sessionId":{"$input":"sessionId"}},"save":"effect"}]},"key":"host-stop","section":"procedures"}
P host-stop(sessionId:str expectedRevision:0..):effect=host.stop(expectedRevision:expectedRevision sessionId:sessionId) -- Fresh exact kernel process and owner state or independently observed requested file bytes
V P host-stop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"host","data":"A responding preview URL does not establish which process owns its socket.","key":"0","section":"frontier"}
F A responding preview URL does not establish which process owns its socket.
-- @record {"chapter":"host","data":"Plugin effects are limited to the explicitly declared guarded file byte postcondition; other plugin effects stay unproven.","key":"1","section":"frontier"}
F Plugin effects are limited to the explicitly declared guarded file byte postcondition; other plugin effects stay unproven.
-- @record {"chapter":"host","data":"Launch only approved headless programs for background journeys.","key":"0","section":"guidance"}
M local-host "Launch only approved headless programs for background journeys." src:"authored manual" state:verified
-- @proof {"checkedAt":["grant_agent.proofs_installed_preflight_journey.self_check","grant_agent.proofs_installed_preflight_journey._journey","grant_agent.installed_programs.InstalledPrograms.discover","grant_agent.installed_programs.InstalledPrograms.prepare_file","grant_agent.runtimes.runtime_adapter_map"],"claim":"Installed program discovery identifies the current Python executable and resolves an owned scratch script to it without starting the script; an outside-root path is refused, dependency readiness remains unverified, and no delegated provider route or worker process is invented.","id":"runtime.program.local-python-preflight","impact":["local program availability and command resolution","managed workspace root refusal","truthful readiness without provider execution"],"phase":"invariant"}
