CL 1
L manuals-next v1 -- Authored executable manual
-- @manual {"chapters":{"scripts":{"title":"scripts: repeated verified procedures"},"state":{"title":"state: durable handles and deltas"},"versions":{"title":"versions: reviewed patches and failure recovery"}},"clVersion":"1.1","id":"manuals-next","kind":"workflow","proofs":{"area":"manual-registry-journey","manifests":["config/proofs/manual-registry-journey.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.manual.compile":"t1","neyvia.manual.compiled":"t2","neyvia.manual.demote":"t3","neyvia.manual.frontier":"t4","neyvia.manual.observe":"t5","neyvia.manual.patch.apply":"t6","neyvia.manual.project":"t7","neyvia.manual.recover":"t8","neyvia.manual.recovery.bind":"t9","neyvia.manual.run":"t10","neyvia.manual.script.run":"t11","neyvia.manual.versions":"t12"},"tool_metadata":{"neyvia.manual.compile":{"mutability_class":"none"},"neyvia.manual.compiled":{"mutability_class":"none"},"neyvia.manual.demote":{"mutability_class":"none"},"neyvia.manual.frontier":{"mutability_class":"none"},"neyvia.manual.observe":{"mutability_class":"none"},"neyvia.manual.patch.apply":{"mutability_class":"none"},"neyvia.manual.project":{"mutability_class":"none"},"neyvia.manual.recover":{"mutability_class":"none"},"neyvia.manual.recovery.bind":{"mutability_class":"none"},"neyvia.manual.run":{"mutability_class":"none"},"neyvia.manual.script.run":{"mutability_class":"none"},"neyvia.manual.versions":{"mutability_class":"none"}}}
T t1 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"chapter\":{\"type\":\"string\"},\"procedure\":{\"type\":\"string\"},\"inputs\":{\"type\":\"object\"},\"minRuns\":{\"type\":\"integer\",\"minimum\":2,\"maximum\":100}},\"required\":[\"id\",\"procedure\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"procedure\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2{id?:str ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"chapter\":{\"type\":\"string\"},\"procedure\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"}},\"required\":[\"id\",\"chapter\",\"procedure\",\"reason\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"chapter\":{\"not\":{\"enum\":[\"\"]}},\"procedure\":{\"not\":{\"enum\":[\"\"]}},\"reason\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"note\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4000},\"observed\":{\"type\":\"object\"},\"operations\":{\"type\":\"array\",\"items\":{\"type\":\"object\"},\"maxItems\":100}},\"required\":[\"id\",\"note\",\"observed\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"state\":{\"type\":\"string\"},\"inputs\":{\"type\":\"object\"},\"chapter\":{\"type\":\"string\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"},\"stream\":{\"type\":\"string\"},\"previousHandle\":{\"type\":\"string\"},\"reset\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"state\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"state\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"patchId\":{\"type\":\"string\"},\"expectedSha256\":{\"type\":\"string\"},\"approved\":{\"const\":true},\"reviewer\":{\"type\":\"string\"},\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1}},\"required\":[\"id\",\"patchId\",\"expectedSha256\",\"approved\",\"reviewer\",\"evidence\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"patchId\":{\"not\":{\"enum\":[\"\"]}},\"expectedSha256\":{\"not\":{\"enum\":[\"\"]}},\"reviewer\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7 json:"{\"type\":\"object\",\"properties\":{\"handle\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100}},\"required\":[\"handle\"],\"allOf\":[{\"properties\":{\"handle\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8 json:"{\"type\":\"object\",\"properties\":{\"runId\":{\"type\":\"string\"},\"recipeId\":{\"type\":\"string\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}},\"required\":[\"runId\",\"recipeId\"],\"allOf\":[{\"properties\":{\"runId\":{\"not\":{\"enum\":[\"\"]}},\"recipeId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9 json:"{\"type\":\"object\",\"properties\":{\"runId\":{\"type\":\"string\"},\"chapter\":{\"type\":\"string\"},\"procedure\":{\"type\":\"string\"},\"inputs\":{\"type\":\"object\"}},\"required\":[\"runId\",\"chapter\",\"procedure\",\"inputs\"],\"allOf\":[{\"properties\":{\"runId\":{\"not\":{\"enum\":[\"\"]}},\"chapter\":{\"not\":{\"enum\":[\"\"]}},\"procedure\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"procedure\":{\"type\":\"string\"},\"inputs\":{\"type\":\"object\"},\"chapter\":{\"type\":\"string\"},\"runId\":{\"type\":\"string\"},\"decisions\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}},\"evidence\":{\"type\":\"string\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}},\"required\":[\"id\",\"procedure\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"procedure\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t11 json:"{\"type\":\"object\",\"properties\":{\"scriptId\":{\"type\":\"string\"},\"inputs\":{\"type\":\"object\"},\"runId\":{\"type\":\"string\"},\"decisions\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}},\"evidence\":{\"type\":\"string\"},\"scopeTools\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}},\"required\":[\"scriptId\"],\"allOf\":[{\"properties\":{\"scriptId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t12 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t13{}
T t14 json:"{\"type\":\"object\",\"required\":[\"scripts\"]}"
T t15 json:"{\"type\":\"object\"}"
T t16{id:str chapter:str procedure:str inputs:json:"{\"type\":\"object\"}" minRuns:2..100 ..}
T t17 json:"{\"$input\":\"inputs\"}"
T t18{id:str procedure:str inputs:json:"{\"type\":\"object\"}" chapter:str runId:str decisions:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" ..}
T t19{scriptId:str inputs:json:"{\"type\":\"object\"}" runId:str decisions:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" ..}
T t20 json:"{\"type\":\"object\",\"required\":[\"manuals\"]}"
T t21{id:str state:str inputs:json:"{\"type\":\"object\"}" chapter:str scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" stream:str previousHandle:str reset:bool ..}
T t22{handle:str path:str offset:0.. limit:1..100 ..}
T t23{id:str}
T t24 json:"{\"type\":\"object\",\"required\":[\"sha256\",\"lineage\"]}"
T t25{id:str note:str#1..4000 observed:json:"{\"type\":\"object\"}"}
T t26 json:"{\"type\":\"object\",\"properties\":{\"chapter\":{\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"procedure\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"}},\"required\":[\"id\",\"chapter\",\"procedure\",\"reason\"],\"additionalProperties\":false}"
T t27 json:"{\"type\":\"object\",\"properties\":{\"evidence\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1},\"expectedSha256\":{\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"patchId\":{\"type\":\"string\"},\"reviewer\":{\"type\":\"string\"}},\"required\":[\"id\",\"patchId\",\"expectedSha256\",\"reviewer\",\"evidence\"],\"additionalProperties\":false}"
T t28{runId:str recipeId:str scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" ..}
T t29{runId:str chapter:str procedure:str inputs:json:"{\"type\":\"object\"}" ..}
L manuals-next.scripts v1 -- scripts: repeated verified procedures
-- @record {"chapter":"scripts","data":{"args":{},"inputs":{"$cl_type":"t13"},"shape":{"$cl_type":"t14"},"tool":"neyvia.manual.compiled"},"key":"current","section":"state"}
S manuals-next.current:json:"{\"type\":\"object\",\"required\":[\"scripts\"]}"=neyvia.manual.compiled()
-- @record {"chapter":"scripts","data":{"effect":"Execute actions and checks; stop at JUDGE; resume same runId with one offered decision","pre":"Current manual/procedure, typed inputs and caller authority","returns":{"$cl_type":"t15"},"reversible":false,"schema":"neyvia.manual.run","tool":"neyvia.manual.run"},"key":"run","section":"actions"}
A neyvia.manual.run(id:str procedure:str inputs?:json:"{\"type\":\"object\"}" chapter?:str runId?:str decisions?:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" evidence?:str scopeTools?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}") -> json:"{\"type\":\"object\"}" ! -- Execute actions and checks; stop at JUDGE; resume same runId with one offered decision
F verify-run "No authored observer check is bound to neyvia.manual.run" -> ask operator blocks:neyvia.manual.run
-- @record {"chapter":"scripts","data":{"effect":"Persist checked executable plan; constant context and decisions specialize; varying branches stay JUDGE","pre":"At least minRuns=3 verified repeated traces, current hash and exact input cohort","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.compile","tool":"neyvia.manual.compile"},"key":"compile","section":"actions"}
A neyvia.manual.compile(id:str chapter?:str procedure:str inputs?:json:"{\"type\":\"object\"}" minRuns?:2..100) -> json:"{\"type\":\"object\"}" ! -- Persist checked executable plan; constant context and decisions specialize; varying branches stay JUDGE
F verify-compile "No authored observer check is bound to neyvia.manual.compile" -> ask operator blocks:neyvia.manual.compile
-- @record {"chapter":"scripts","data":{"effect":"List executable plans and stale version flags","pre":"Selected workspace","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.compiled","tool":"neyvia.manual.compiled"},"key":"compiled","section":"actions"}
A neyvia.manual.compiled(id?:str) -> json:"{\"type\":\"object\"}" -- List executable plans and stale version flags
F verify-compiled "No authored observer check is bound to neyvia.manual.compiled" -> ask operator blocks:neyvia.manual.compiled
-- @record {"chapter":"scripts","data":{"effect":"No model call; changed state stops at JUDGE; every effect runs original checks","pre":"scriptId, learned inputs, original gateway grants and unchanged evidence","returns":{"$cl_type":"t15"},"reversible":false,"schema":"neyvia.manual.script.run","tool":"neyvia.manual.script.run"},"key":"script.run","section":"actions"}
A neyvia.manual.script.run(scriptId:str inputs?:json:"{\"type\":\"object\"}" runId?:str decisions?:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" evidence?:str scopeTools?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}") -> json:"{\"type\":\"object\"}" -- No model call; changed state stops at JUDGE; every effect runs original checks
F verify-script-run "No authored observer check is bound to neyvia.manual.script.run" -> ask operator blocks:neyvia.manual.script.run
-- @record {"chapter":"scripts","data":{"goal":"Retain exact grounded compile artifact with fresh owner effect checks","inputs":{"$cl_type":"t16"},"steps":[{"action":"compile","args":{"chapter":{"$input":"chapter"},"id":{"$input":"id"},"inputs":{"$cl_type":"t17"},"minRuns":{"$input":"minRuns"},"procedure":{"$input":"procedure"}},"save":"artifact"}]},"key":"verified-compile","section":"procedures"}
P verified-compile(id:str chapter:str procedure:str inputs:json:"{\"type\":\"object\"}" minRuns:2..100):artifact=neyvia.manual.compile(chapter:chapter id:id inputs:inputs minRuns:minRuns procedure:procedure) -- Retain exact grounded compile artifact with fresh owner effect checks
V P verified-compile -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scripts","data":{"goal":"Retain exact grounded run artifact with fresh owner effect checks","inputs":{"$cl_type":"t18"},"steps":[{"action":"run","args":{"chapter":{"$input":"chapter"},"decisions":{"$input":"decisions"},"id":{"$input":"id"},"inputs":{"$cl_type":"t17"},"procedure":{"$input":"procedure"},"runId":{"$input":"runId"},"scopeTools":{"$input":"scopeTools"}},"save":"artifact"}]},"key":"verified-run","section":"procedures"}
P verified-run(id:str procedure:str inputs:json:"{\"type\":\"object\"}" chapter:str runId:str decisions:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}"):artifact=neyvia.manual.run(chapter:chapter decisions:decisions id:id inputs:inputs procedure:procedure runId:runId scopeTools:scopeTools) -- Retain exact grounded run artifact with fresh owner effect checks
V P verified-run -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scripts","data":{"goal":"Retain exact grounded script.run artifact with fresh owner effect checks","inputs":{"$cl_type":"t19"},"steps":[{"action":"script.run","args":{"decisions":{"$input":"decisions"},"inputs":{"$cl_type":"t17"},"runId":{"$input":"runId"},"scopeTools":{"$input":"scopeTools"},"scriptId":{"$input":"scriptId"}},"save":"artifact"}]},"key":"verified-script-run","section":"procedures"}
P verified-script-run(scriptId:str inputs:json:"{\"type\":\"object\"}" runId:str decisions:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}"):artifact=neyvia.manual.script.run(decisions:decisions inputs:inputs runId:runId scopeTools:scopeTools scriptId:scriptId) -- Retain exact grounded script.run artifact with fresh owner effect checks
V P verified-script-run -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"scripts","data":{"constraints":"Only exact learned input scope and current hashes may run; changed state must retain JUDGE; no implied authority from compilation.","options":["run","recompile"],"question":"Is the retained script mapped to the current task and version?"},"key":"script-choice","section":"judge"}
J script-choice run|recompile:"Is the retained script mapped to the current task and version?" -- Only exact learned input scope and current hashes may run; changed state must retain JUDGE; no implied authority from compilation.
V J script-choice -> human:operator why:"explicit choice required"
-- @record {"chapter":"scripts","data":{"failure":"stale script, changed inputs or newer varying decision evidence","recovery":"Use manual.run for new inputs; collect checked ordinary runs and compile again."},"key":"0","section":"pitfalls"}
X stale script, changed inputs or newer varying decision evidence -> Use manual.run for new inputs; collect checked ordinary runs and compile again.
-- @record {"chapter":"scripts","data":{"failure":"changed state before a learned decision","recovery":"Inspect the returned JUDGE and explicitly choose an option before resuming."},"key":"1","section":"pitfalls"}
X changed state before a learned decision -> Inspect the returned JUDGE and explicitly choose an option before resuming.
-- @record {"chapter":"scripts","data":"Only observed exact input cohorts can specialize; judgement requiring taste stays with the model or Paul.","key":"0","section":"frontier"}
F Only observed exact input cohorts can specialize; judgement requiring taste stays with the model or Paul.
-- @record {"chapter":"scripts","data":"neyvia.manual.compile(id,chapter,procedure,inputs,minRuns) consumes .neyvia/manual-runs.jsonl and durable completed runs.","key":"0","section":"guidance"}
M manuals-next "neyvia.manual.compile(id,chapter,procedure,inputs,minRuns) consumes .neyvia/manual-runs.jsonl and durable completed runs." src:"authored manual" state:verified
-- @record {"chapter":"scripts","data":"neyvia.manual.script.run(scriptId,inputs,scopeTools?) uses the same runner; resume with scriptId,runId,decisions.","key":"1","section":"guidance"}
M manuals-next "neyvia.manual.script.run(scriptId,inputs,scopeTools?) uses the same runner; resume with scriptId,runId,decisions." src:"authored manual" state:verified
-- @record {"chapter":"scripts","data":"Artifacts are data plans, not arbitrary source; modelCalls=0 means this runner made no hidden model request.","key":"2","section":"guidance"}
M manuals-next "Artifacts are data plans, not arbitrary source; modelCalls=0 means this runner made no hidden model request." src:"authored manual" state:verified
-- @record {"chapter":"scripts","data":"zeroToken is conditional on learned state/input guards; changed state or variable branches return JUDGE.","key":"3","section":"guidance"}
M manuals-next "zeroToken is conditional on learned state/input guards; changed state or variable branches return JUDGE." src:"authored manual" state:verified
-- @record {"chapter":"scripts","data":"CL execution completion requires authored verifiers on every nested mutation; compiled cohorts and model-free reruns retain exact original evidence.","key":"4","section":"guidance"}
M manuals-next "CL execution completion requires authored verifiers on every nested mutation; compiled cohorts and model-free reruns retain exact original evidence." src:"authored manual" state:verified
L manuals-next.state v1 -- state: durable handles and deltas
-- @record {"chapter":"state","data":{"args":{},"inputs":{"$cl_type":"t13"},"shape":{"$cl_type":"t20"},"tool":"neyvia.manual.index"},"key":"current","section":"state"}
S manuals-next.current:json:"{\"type\":\"object\",\"required\":[\"manuals\"]}"=neyvia.manual.index()
-- @record {"chapter":"state","data":{"effect":"First small result is observed; large result is a handle; later results are diffs","pre":"Grounded observer and typed inputs; use a separate stream per context","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.observe","tool":"neyvia.manual.observe"},"key":"observe","section":"actions"}
A neyvia.manual.observe(id:str state:str inputs?:json:"{\"type\":\"object\"}" chapter?:str scopeTools?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" stream?:str previousHandle?:str reset?:bool) -> json:"{\"type\":\"object\"}" -- First small result is observed; large result is a handle; later results are diffs
F verify-observe "No authored observer check is bound to neyvia.manual.observe" -> ask operator blocks:neyvia.manual.observe
-- @record {"chapter":"state","data":{"effect":"Return bounded selected state; tooLarge requires a deeper path","pre":"Returned immutable handle, JSON Pointer, offset>=0, limit 1..100","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.project","tool":"neyvia.manual.project"},"key":"project","section":"actions"}
A neyvia.manual.project(handle:str path?:str offset?:0.. limit?:1..100) -> json:"{\"type\":\"object\"}" -- Return bounded selected state; tooLarge requires a deeper path
C neyvia.manual.project selected-projection-handle:neyvia.manual.project(handle:handle limit:limit offset:offset path:path) .handle == handle
-- @record {"chapter":"state","data":{"args":{"handle":{"$input":"handle"},"limit":{"$input":"limit"},"offset":{"$input":"offset"},"path":{"$input":"path"}},"expect":{"op":"eq","path":"handle","value":{"$input":"handle"}},"tool":"neyvia.manual.project"},"key":"selected-projection-handle","section":"checks"}
C neyvia.manual.project selected-projection-handle:neyvia.manual.project(handle:handle limit:limit offset:offset path:path) .handle == handle
-- @record {"chapter":"state","data":{"goal":"Read exact observe state with independent source/artifact verification","inputs":{"$cl_type":"t21"},"steps":[{"action":"observe","args":{"chapter":{"$input":"chapter"},"id":{"$input":"id"},"inputs":{"$cl_type":"t17"},"previousHandle":{"$input":"previousHandle"},"reset":{"$input":"reset"},"scopeTools":{"$input":"scopeTools"},"state":{"$input":"state"},"stream":{"$input":"stream"}},"save":"state"}]},"key":"verified-observe","section":"procedures"}
P verified-observe(id:str state:str inputs:json:"{\"type\":\"object\"}" chapter:str scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}" stream:str previousHandle:str reset:bool):state=neyvia.manual.observe(chapter:chapter id:id inputs:inputs previousHandle:previousHandle reset:reset scopeTools:scopeTools state:state stream:stream) -- Read exact observe state with independent source/artifact verification
V P verified-observe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"state","data":{"goal":"Read exact project state with independent source/artifact verification","inputs":{"$cl_type":"t22"},"steps":[{"action":"project","args":{"handle":{"$input":"handle"},"limit":{"$input":"limit"},"offset":{"$input":"offset"},"path":{"$input":"path"}},"check":"selected-projection-handle","save":"state"}]},"key":"verified-project","section":"procedures"}
P verified-project(handle:str path:str offset:0.. limit:1..100):state=neyvia.manual.project(handle:handle limit:limit offset:offset path:path) C selected-projection-handle -- Read exact project state with independent source/artifact verification
V P verified-project -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"state","data":{"failure":"tooLarge projection","recovery":"Choose a deeper JSON Pointer or smaller limit; never infer omitted state."},"key":"0","section":"pitfalls"}
X tooLarge projection -> Choose a deeper JSON Pointer or smaller limit; never infer omitted state.
-- @record {"chapter":"state","data":"Observer source may itself be bounded; handle covers the observed value, not unread source bytes.","key":"0","section":"frontier"}
F Observer source may itself be bounded; handle covers the observed value, not unread source bytes.
-- @record {"chapter":"state","data":"neyvia.manual.observe(id,chapter,state,inputs,stream?,previousHandle?,reset?) reads actual tool state.","key":"0","section":"guidance"}
M manuals-next "neyvia.manual.observe(id,chapter,state,inputs,stream?,previousHandle?,reset?) reads actual tool state." src:"authored manual" state:verified
-- @record {"chapter":"state","data":"Large observations never paste the whole value; retain handle and use neyvia.manual.project(handle,path,offset,limit).","key":"1","section":"guidance"}
M manuals-next "Large observations never paste the whole value; retain handle and use neyvia.manual.project(handle,path,offset,limit)." src:"authored manual" state:verified
-- @record {"chapter":"state","data":"Diffs use JSON Patch add/remove/replace; diffHandle points to an oversized patch. Handles and stream baselines survive restart.","key":"2","section":"guidance"}
M manuals-next "Diffs use JSON Patch add/remove/replace; diffHandle points to an oversized patch. Handles and stream baselines survive restart." src:"authored manual" state:verified
-- @record {"chapter":"state","data":"Observe persists a fresh source-bound handle and stream/diff; project reads an existing immutable handle. Source drift invalidates observation completion while old handles remain immutable.","key":"3","section":"guidance"}
M manuals-next "Observe persists a fresh source-bound handle and stream/diff; project reads an existing immutable handle. Source drift invalidates observation completion while old handles remain immutable." src:"authored manual" state:verified
L manuals-next.versions v1 -- versions: reviewed patches and failure recovery
-- @record {"chapter":"versions","data":{"args":{"id":{"$input":"id"}},"inputs":{"$cl_type":"t23"},"shape":{"$cl_type":"t24"},"tool":"neyvia.manual.versions"},"key":"current","section":"state"}
S manuals-next.current:json:"{\"type\":\"object\",\"required\":[\"sha256\",\"lineage\"]}"=neyvia.manual.versions(id:id)
-- @record {"chapter":"versions","data":{"effect":"Quarantine notes or bounded JSON Patch operations; never change live source","pre":"Actual unmatched state/failure evidence","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.frontier","tool":"neyvia.manual.frontier"},"key":"frontier","section":"actions"}
A neyvia.manual.frontier(id:str note:str#1..4000 observed:json:"{\"type\":\"object\"}" operations?:[json:"{\"type\":\"object\"}"]#..100) -> json:"{\"type\":\"object\"}" -- Quarantine notes or bounded JSON Patch operations; never change live source
F verify-frontier "No authored observer check is bound to neyvia.manual.frontier" -> ask operator blocks:neyvia.manual.frontier
-- @record {"chapter":"versions","data":{"effect":"Validate and promote scoped revision with parent hash; no repository source edits","pre":"approved=true, reviewer, evidence and expectedSha256=current base","returns":{"$cl_type":"t15"},"reversible":false,"schema":"neyvia.manual.patch.apply","tool":"neyvia.manual.patch.apply"},"key":"patch.apply","section":"actions"}
A neyvia.manual.patch.apply(id:str patchId:str expectedSha256:str approved:true reviewer:str evidence:[str]#1..) -> json:"{\"type\":\"object\"}" -- Validate and promote scoped revision with parent hash; no repository source edits
F verify-patch-apply "No authored observer check is bound to neyvia.manual.patch.apply" -> ask operator blocks:neyvia.manual.patch.apply
-- @record {"chapter":"versions","data":{"effect":"Read current hash, full lineage and demoted procedures","pre":"Registered manual id","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.versions","tool":"neyvia.manual.versions"},"key":"versions","section":"actions"}
A neyvia.manual.versions(id:str) -> json:"{\"type\":\"object\"}" -- Read current hash, full lineage and demoted procedures
F verify-versions "No authored observer check is bound to neyvia.manual.versions" -> ask operator blocks:neyvia.manual.versions
-- @record {"chapter":"versions","data":{"effect":"Quarantine procedure removal; explicit patch.apply required","pre":"Existing procedure plus reason","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.demote","tool":"neyvia.manual.demote"},"key":"demote","section":"actions"}
A neyvia.manual.demote(id:str chapter:str procedure:str reason:str) -> json:"{\"type\":\"object\"}" -- Quarantine procedure removal; explicit patch.apply required
F verify-demote "No authored observer check is bound to neyvia.manual.demote" -> ask operator blocks:neyvia.manual.demote
-- @record {"chapter":"versions","data":{"effect":"Bind recipe to hash, exact failure, inputs and original tool restriction","pre":"Observed failed runId and typed recovery procedure/inputs","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.manual.recovery.bind","tool":"neyvia.manual.recovery.bind"},"key":"recovery.bind","section":"actions"}
A neyvia.manual.recovery.bind(runId:str chapter:str procedure:str inputs:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" ! -- Bind recipe to hash, exact failure, inputs and original tool restriction
F verify-recovery-bind "No authored observer check is bound to neyvia.manual.recovery.bind" -> ask operator blocks:neyvia.manual.recovery.bind
-- @record {"chapter":"versions","data":{"effect":"Run a fresh checked recovery; never replay failed effects; unchanged original failure retained","pre":"Failed runId and matching recipeId; caller authority","returns":{"$cl_type":"t15"},"reversible":false,"schema":"neyvia.manual.recover","tool":"neyvia.manual.recover"},"key":"recover","section":"actions"}
A neyvia.manual.recover(runId:str recipeId:str scopeTools?:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}") -> json:"{\"type\":\"object\"}" ! -- Run a fresh checked recovery; never replay failed effects; unchanged original failure retained
F verify-recover "No authored observer check is bound to neyvia.manual.recover" -> ask operator blocks:neyvia.manual.recover
-- @record {"chapter":"versions","data":{"goal":"Save one observed manual frontier as a quarantined patch without changing the active version","inputs":{"$cl_type":"t25"},"steps":[{"action":"versions","args":{"id":{"$input":"id"}},"save":"before"},{"action":"frontier","args":{"id":{"$input":"id"},"note":{"$input":"note"},"observed":{"$input":"observed"}},"save":"patch"}]},"key":"quarantine-observation","section":"procedures"}
P quarantine-observation(id:str note:str#1..4000 observed:json:"{\"type\":\"object\"}"):before=neyvia.manual.versions(id:id); patch=neyvia.manual.frontier(id:id note:note observed:observed) -- Save one observed manual frontier as a quarantined patch without changing the active version
V P quarantine-observation -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"versions","data":{"goal":"Quarantine removal of one named obsolete procedure while keeping the current manual active","inputs":{"$cl_type":"t26"},"steps":[{"action":"versions","args":{"id":{"$input":"id"}},"save":"before"},{"action":"demote","args":{"chapter":{"$input":"chapter"},"id":{"$input":"id"},"procedure":{"$input":"procedure"},"reason":{"$input":"reason"}},"save":"patch"}]},"key":"quarantine-demotion","section":"procedures"}
P quarantine-demotion(chapter:str id:str procedure:str reason:str):before=neyvia.manual.versions(id:id); patch=neyvia.manual.demote(chapter:chapter id:id procedure:procedure reason:reason) -- Quarantine removal of one named obsolete procedure while keeping the current manual active
V P quarantine-demotion -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"versions","data":{"goal":"Apply one explicitly reviewed quarantined patch to this workspace with current base hash and evidence","inputs":{"$cl_type":"t27"},"steps":[{"action":"versions","args":{"id":{"$input":"id"}},"save":"before"},{"judge":"patch-review"},{"action":"patch.apply","args":{"approved":true,"evidence":{"$input":"evidence"},"expectedSha256":{"$input":"expectedSha256"},"id":{"$input":"id"},"patchId":{"$input":"patchId"},"reviewer":{"$input":"reviewer"}},"save":"promoted","when":{"judge":"patch-review","option":"approve"}}]},"key":"promote-reviewed-patch","section":"procedures"}
P promote-reviewed-patch(evidence:[str]#1.. expectedSha256:str id:str patchId:str reviewer:str):before=neyvia.manual.versions(id:id); J patch-review=approve; promoted=neyvia.manual.patch.apply(approved:true evidence:evidence expectedSha256:expectedSha256 id:id patchId:patchId reviewer:reviewer) -- Apply one explicitly reviewed quarantined patch to this workspace with current base hash and evidence
V P promote-reviewed-patch -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"versions","data":{"goal":"Retain exact grounded recover artifact with fresh owner effect checks","inputs":{"$cl_type":"t28"},"steps":[{"action":"recover","args":{"recipeId":{"$input":"recipeId"},"runId":{"$input":"runId"},"scopeTools":{"$input":"scopeTools"}},"save":"artifact"}]},"key":"verified-recover","section":"procedures"}
P verified-recover(runId:str recipeId:str scopeTools:json:"{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Optional restriction on nested tools; never grants authority\"}"):artifact=neyvia.manual.recover(recipeId:recipeId runId:runId scopeTools:scopeTools) -- Retain exact grounded recover artifact with fresh owner effect checks
V P verified-recover -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"versions","data":{"goal":"Retain exact grounded recovery.bind artifact with fresh owner effect checks","inputs":{"$cl_type":"t29"},"steps":[{"action":"recovery.bind","args":{"chapter":{"$input":"chapter"},"inputs":{"$cl_type":"t17"},"procedure":{"$input":"procedure"},"runId":{"$input":"runId"}},"save":"artifact"}]},"key":"verified-recovery-bind","section":"procedures"}
P verified-recovery-bind(runId:str chapter:str procedure:str inputs:json:"{\"type\":\"object\"}"):artifact=neyvia.manual.recovery.bind(chapter:chapter inputs:inputs procedure:procedure runId:runId) -- Retain exact grounded recovery.bind artifact with fresh owner effect checks
V P verified-recovery-bind -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"versions","data":{"constraints":"Promotion requires explicit reviewer, evidence and current base hash; unknown or failing effects stay quarantined.","options":["approve","quarantine"],"question":"Is the quarantined change supported by current evidence?"},"key":"patch-review","section":"judge"}
J patch-review approve|quarantine:"Is the quarantined change supported by current evidence?" -- Promotion requires explicit reviewer, evidence and current base hash; unknown or failing effects stay quarantined.
V J patch-review -> human:operator why:"explicit choice required"
-- @record {"chapter":"versions","data":{"failure":"stale baseSha256 or invalid action schema","recovery":"Read current version, revise quarantined patch, rerun grounding; do not bypass CAS."},"key":"0","section":"pitfalls"}
X stale baseSha256 or invalid action schema -> Read current version, revise quarantined patch, rerun grounding; do not bypass CAS.
-- @record {"chapter":"versions","data":{"failure":"unknown situation or verifier failure without a recipe","recovery":"Inspect frontier evidence; an explorer/reviewer creates a quarantined patch or bound recovery."},"key":"1","section":"pitfalls"}
X unknown situation or verifier failure without a recipe -> Inspect frontier evidence; an explorer/reviewer creates a quarantined patch or bound recovery.
-- @record {"chapter":"versions","data":"No automatic explorer/model call or LAYA service integration; frontier responses identify where explicit exploration starts.","key":"0","section":"frontier"}
F No automatic explorer/model call or LAYA service integration; frontier responses identify where explicit exploration starts.
-- @record {"chapter":"versions","data":"Machine detection returns status=frontier for unknown procedures/states or schema drift and quarantines execution failures with no bound recipe.","key":"0","section":"guidance"}
M manuals-next "Machine detection returns status=frontier for unknown procedures/states or schema drift and quarantines execution failures with no bound recipe." src:"authored manual" state:verified
-- @record {"chapter":"versions","data":"Bind a recipe with neyvia.manual.recovery.bind(runId,chapter,procedure,inputs), then select neyvia.manual.recover(runId,recipeId).","key":"1","section":"guidance"}
M manuals-next "Bind a recipe with neyvia.manual.recovery.bind(runId,chapter,procedure,inputs), then select neyvia.manual.recover(runId,recipeId)." src:"authored manual" state:verified
-- @record {"chapter":"versions","data":"Patch operations support chapter-scoped JSON Patch test/add/remove/replace; promotion is explicit and workspace-local.","key":"2","section":"guidance"}
M manuals-next "Patch operations support chapter-scoped JSON Patch test/add/remove/replace; promotion is explicit and workspace-local." src:"authored manual" state:verified
-- @record {"chapter":"versions","data":"Removed procedures stay in parent snapshots and lineage demoted[]; obsolete scripts/recipes cannot run against newer hashes.","key":"3","section":"guidance"}
M manuals-next "Removed procedures stay in parent snapshots and lineage demoted[]; obsolete scripts/recipes cannot run against newer hashes." src:"authored manual" state:verified

-- @proof {"id":"p22.manuals.registry-action-admission","phase":"post","claim":"The production manual registry grounds manuals against callable action schemas, refuses a malformed observer schema, blocks an observer outside the caller's nested-tool scope before dispatch, and admits the same observation only when its exact read tool is granted.","checkedAt":["grant_agent.manual_contracts.validate_structure","grant_agent.manual_contracts.validate_grounding","grant_agent.neyvia_manuals.validate","grant_agent.neyvia_manuals.context","grant_agent.neyvia_manuals.call","grant_agent.proofs_manual_registry_journey.manual_registry_journey"],"impact":["Authored manual validation against the live callable tool registry","Nested observer action admission and caller scope enforcement"]}
