CL 1
L memory v1 -- Authored executable manual
-- @manual {"chapters":{"cue-memory":{"title":"Private cue memory and fresh lifecycle proof"}},"clVersion":"1.1","id":"memory","kind":"environment","schema":"neyvia.manual.v1","schemas":{"neyvia.efficiency.extract":"t1","neyvia.memory.correct":"t2","neyvia.memory.forget":"t3","neyvia.memory.inspect":"t4","neyvia.memory.list":"t5","neyvia.memory.recall":"t6","neyvia.memory.remember":"t7","terminal.exec":"t8","workspace.read":"t9"},"tool_metadata":{"neyvia.memory.correct":{"mutability_class":"artifact_write"},"neyvia.memory.forget":{"mutability_class":"artifact_write"},"neyvia.memory.inspect":{"mutability_class":"read"},"neyvia.memory.list":{"mutability_class":"read"},"neyvia.memory.recall":{"mutability_class":"read"},"neyvia.memory.remember":{"mutability_class":"artifact_write"},"terminal.exec":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"}},"proofs":{"area":"proofs-e-host"}}
-- @proof {"id":"memory.launcher-host-binding","phase":"invariant","claim":"Native memory uses the trusted host root and selected project; malformed, stale or mismatched launcher scope disables memory with a content-free log and never fails ordinary chat startup.","checkedAt":["src/grant_agent/neyvia_memory_tools.py:launcher_context","src/grant_agent/web_backend_chat.py:_run_neyvia_chat","src/grant_agent/neyvia_agent.py:_codex_neyvia_mcp_args","src/grant_agent/neyvia_mcp_stdio.py:CompactNeyviaMCPServer._gateway"],"impact":["Normal workspace-root launch and separate selected chat projects"]}
T t1{path:str field:str strategy?:json:"{\"type\":\"string\",\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"]}" useScript?:bool ..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"key\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},\"content\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":2000},\"kind\":{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"]},\"cues\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}},\"expiresAt\":{\"type\":[\"string\",\"null\"]},\"exportPolicy\":{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]},\"requestId\":{\"type\":\"string\",\"minLength\":1},\"id\":{\"type\":\"string\",\"minLength\":1},\"expectedRevision\":{\"type\":\"integer\",\"minimum\":1}},\"required\":[\"id\",\"expectedRevision\",\"key\",\"content\",\"requestId\"]}"
T t3{id:str#1.. expectedRevision:1.. requestId:str#1.. ..}
T t4{id:str#1.. ..}
T t5{limit?:1..200 ..}
T t6{situation:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"string\"},\"app\":{\"type\":\"string\"},\"layer\":{\"type\":\"string\"},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"string\"},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}" budget?:0..1024 destination?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}" ..}
T t7{key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"]}" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}" expiresAt?:str|null exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}" requestId:str#1.. ..}
T t8{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t9 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t11 json:"{\"type\":\"object\"}"
T t12{memory:{id:str revision:int status:str content?:str ..} generation:int ..}
T t13{key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"]}"="fact" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}"={"intent":["memory"]} expiresAt?:str|null=null exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}"="local" requestId:str#1..}
T t14 json:"{\"type\":\"object\",\"properties\":{\"key\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},\"content\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":2000},\"kind\":{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"],\"default\":\"fact\"},\"cues\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}},\"default\":{\"intent\":[\"memory\"]}},\"expiresAt\":{\"type\":[\"string\",\"null\"],\"default\":null},\"exportPolicy\":{\"type\":\"string\",\"enum\":[\"local\",\"provider\"],\"default\":\"local\"},\"requestId\":{\"type\":\"string\",\"minLength\":1},\"id\":{\"type\":\"string\",\"minLength\":1},\"expectedRevision\":{\"type\":\"integer\",\"minimum\":1}},\"required\":[\"id\",\"expectedRevision\",\"key\",\"content\",\"requestId\"],\"additionalProperties\":false}"
T t15{id:str#1.. expectedRevision:1.. requestId:str#1..}
T t16{id:str#1.. expectedContent:str}
T t17{query:str expectedContent:str}
T t18{query:str}
L memory.cue-memory v1 -- Private cue memory and fresh lifecycle proof
-- @record {"chapter":"cue-memory","data":{"args":{},"inputs":{"$cl_type":"t10"},"shape":{"$cl_type":"t11"},"tool":"neyvia.memory.list"},"key":"scope","section":"state"}
S memory.scope:json:"{\"type\":\"object\"}"=neyvia.memory.list()
-- @record {"chapter":"cue-memory","data":{"effect":"Save one explicit claim or pending candidate with provenance and an atomic revision.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.memory.remember","tool":"neyvia.memory.remember"},"key":"remember","section":"actions"}
A neyvia.memory.remember(key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"]}" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}" expiresAt?:str|null exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}" requestId:str#1..) -> {memory:{id:str revision:int status:str content?:str ..} generation:int ..} ! -- Save one explicit claim or pending candidate with provenance and an atomic revision.
F verify-remember "No authored observer check is bound to neyvia.memory.remember" -> ask operator blocks:neyvia.memory.remember
-- @record {"chapter":"cue-memory","data":{"effect":"Replace the exact revision and revoke superseded context atomically.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.memory.correct","tool":"neyvia.memory.correct"},"key":"correct","section":"actions"}
A neyvia.memory.correct(key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"]}" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}" expiresAt?:str|null exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}" requestId:str#1.. id:str#1.. expectedRevision:1..) -> {memory:{id:str revision:int status:str content?:str ..} generation:int ..} ! -- Replace the exact revision and revoke superseded context atomically.
F verify-correct "No authored observer check is bound to neyvia.memory.correct" -> ask operator blocks:neyvia.memory.correct
-- @record {"chapter":"cue-memory","data":{"effect":"Delete content and cue indexes while retaining only a tombstone.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t12"},"reversible":false,"schema":"neyvia.memory.forget","tool":"neyvia.memory.forget"},"key":"forget","section":"actions"}
A neyvia.memory.forget(id:str#1.. expectedRevision:1.. requestId:str#1..) -> {memory:{id:str revision:int status:str content?:str ..} generation:int ..} ! -- Delete content and cue indexes while retaining only a tombstone.
F verify-forget "No authored observer check is bound to neyvia.memory.forget" -> ask operator blocks:neyvia.memory.forget
-- @record {"chapter":"cue-memory","data":{"effect":"Read scoped claims, expiry, policy and provenance.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.memory.list","tool":"neyvia.memory.list"},"key":"list","section":"actions"}
A neyvia.memory.list(limit?:1..200) -> json:"{\"type\":\"object\"}" -- Read scoped claims, expiry, policy and provenance.
F verify-list "No authored observer check is bound to neyvia.memory.list" -> ask operator blocks:neyvia.memory.list
-- @record {"chapter":"cue-memory","data":{"effect":"Read one current scoped record; reject another user or project.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t12"},"reversible":true,"schema":"neyvia.memory.inspect","tool":"neyvia.memory.inspect"},"key":"inspect","section":"actions"}
A neyvia.memory.inspect(id:str#1..) -> {memory:{id:str revision:int status:str content?:str ..} generation:int ..} -- Read one current scoped record; reject another user or project.
C neyvia.memory.inspect current-content:neyvia.memory.inspect(id:id) .memory.content == expectedContent
-- @record {"chapter":"cue-memory","data":{"effect":"Read a fresh bounded cue projection with actual token and route receipts.","pre":"Authenticated user and server-selected project. Explicit user approval for corrections, deletion or provider export.","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.memory.recall","tool":"neyvia.memory.recall"},"key":"recall","section":"actions"}
A neyvia.memory.recall(situation:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"string\"},\"app\":{\"type\":\"string\"},\"layer\":{\"type\":\"string\"},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"string\"},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}}}" budget?:0..1024 destination?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"]}") -> json:"{\"type\":\"object\"}" -- Read a fresh bounded cue projection with actual token and route receipts.
C neyvia.memory.recall known-cue:neyvia.memory.recall(budget:256 situation:{intent:query}) .section has expectedContent
C neyvia.memory.recall forgotten-cue:neyvia.memory.recall(budget:256 situation:{intent:query}) .tokens == 0
-- @record {"chapter":"cue-memory","data":{"effect":"Read current receipt fields without loading the entire report.","pre":"Owned synthetic MEM receipt produced by the real driver.","returns":{"$cl_type":"t11"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"read-proof","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> json:"{\"type\":\"object\"}" -- Read current receipt fields without loading the entire report.
F verify-read-proof "No authored observer check is bound to workspace.read" -> ask operator blocks:workspace.read
-- @record {"chapter":"cue-memory","data":{"effect":"Run the pinned production contract driver; a command exit alone does not prove its memory invariant.","pre":"Explicitly owned nx-mem checkout, assigned ports and disposable fixtures. No visible windows, credentials, external promotion or live tree.","returns":{"$cl_type":"t11"},"reversible":true,"schema":"terminal.exec","tool":"terminal.exec"},"key":"exercise","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> json:"{\"type\":\"object\"}" ! -- Run the pinned production contract driver; a command exit alone does not prove its memory invariant.
F verify-exercise "No authored observer check is bound to terminal.exec" -> ask operator blocks:terminal.exec
-- @record {"chapter":"cue-memory","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"memory.content","value":{"$input":"expectedContent"}},"tool":"neyvia.memory.inspect"},"key":"current-content","section":"checks"}
C neyvia.memory.inspect current-content:neyvia.memory.inspect(id:id) .memory.content == expectedContent
-- @record {"chapter":"cue-memory","data":{"args":{"budget":256,"situation":{"intent":{"$input":"query"}}},"expect":{"op":"contains","path":"section","value":{"$input":"expectedContent"}},"tool":"neyvia.memory.recall"},"key":"known-cue","section":"checks"}
C neyvia.memory.recall known-cue:neyvia.memory.recall(budget:256 situation:{intent:query}) .section has expectedContent
-- @record {"chapter":"cue-memory","data":{"args":{"budget":256,"situation":{"intent":{"$input":"query"}}},"expect":{"op":"eq","path":"tokens","value":0},"tool":"neyvia.memory.recall"},"key":"forgotten-cue","section":"checks"}
C neyvia.memory.recall forgotten-cue:neyvia.memory.recall(budget:256 situation:{intent:query}) .tokens == 0
-- @record {"chapter":"cue-memory","data":{"goal":"Save one explicit claim or pending candidate with provenance and an atomic revision.","inputs":{"$cl_type":"t13"},"steps":[{"action":"remember","args":{"content":{"$input":"content"},"cues":{"$input":"cues"},"expiresAt":{"$input":"expiresAt"},"exportPolicy":{"$input":"exportPolicy"},"key":{"$input":"key"},"kind":{"$input":"kind"},"requestId":{"$input":"requestId"}},"save":"saved"}]},"key":"remember","section":"procedures"}
P remember(key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"],\"default\":\"fact\"}" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}},\"default\":{\"intent\":[\"memory\"]}}" expiresAt?:json:"{\"type\":[\"string\",\"null\"],\"default\":null}" exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"],\"default\":\"local\"}" requestId:str#1..):saved=neyvia.memory.remember(content:content cues:cues expiresAt:expiresAt exportPolicy:exportPolicy key:key kind:kind requestId:requestId) -- Save one explicit claim or pending candidate with provenance and an atomic revision.
V P remember -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"goal":"Replace the exact revision and revoke superseded context atomically.","inputs":{"$cl_type":"t14"},"steps":[{"action":"correct","args":{"content":{"$input":"content"},"cues":{"$input":"cues"},"expectedRevision":{"$input":"expectedRevision"},"expiresAt":{"$input":"expiresAt"},"exportPolicy":{"$input":"exportPolicy"},"id":{"$input":"id"},"key":{"$input":"key"},"kind":{"$input":"kind"},"requestId":{"$input":"requestId"}},"save":"saved"}]},"key":"correct","section":"procedures"}
P correct(key:str#1..160 content:str#1..2000 kind?:json:"{\"type\":\"string\",\"enum\":[\"fact\",\"preference\",\"procedure\",\"pitfall\"],\"default\":\"fact\"}" cues?:json:"{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"intent\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"app\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"layer\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"files\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"task\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12},\"entities\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":160},\"maxItems\":12}},\"default\":{\"intent\":[\"memory\"]}}" expiresAt?:json:"{\"type\":[\"string\",\"null\"],\"default\":null}" exportPolicy?:json:"{\"type\":\"string\",\"enum\":[\"local\",\"provider\"],\"default\":\"local\"}" requestId:str#1.. id:str#1.. expectedRevision:1..):saved=neyvia.memory.correct(content:content cues:cues expectedRevision:expectedRevision expiresAt:expiresAt exportPolicy:exportPolicy id:id key:key kind:kind requestId:requestId) -- Replace the exact revision and revoke superseded context atomically.
V P correct -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"goal":"Delete content and cue indexes while retaining only a tombstone.","inputs":{"$cl_type":"t15"},"steps":[{"action":"forget","args":{"expectedRevision":{"$input":"expectedRevision"},"id":{"$input":"id"},"requestId":{"$input":"requestId"}},"save":"saved"}]},"key":"forget","section":"procedures"}
P forget(id:str#1.. expectedRevision:1.. requestId:str#1..):saved=neyvia.memory.forget(expectedRevision:expectedRevision id:id requestId:requestId) -- Delete content and cue indexes while retaining only a tombstone.
V P forget -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"goal":"Observe the current stored claim independently.","inputs":{"$cl_type":"t16"},"steps":[{"action":"inspect","args":{"id":{"$input":"id"}},"check":"current-content","save":"fresh"}]},"key":"inspect-current","section":"procedures"}
P inspect-current(id:str#1.. expectedContent:str):fresh=neyvia.memory.inspect(id:id) C current-content -- Observe the current stored claim independently.
V P inspect-current -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"goal":"Read a fresh cue result under the hard memory budget.","inputs":{"$cl_type":"t17"},"steps":[{"action":"recall","args":{"budget":256,"situation":{"intent":{"$input":"query"}}},"check":"known-cue","save":"fresh"}]},"key":"recall-known","section":"procedures"}
P recall-known(query:str expectedContent:str):fresh=neyvia.memory.recall(budget:256 situation:{intent:query}) C known-cue -- Read a fresh cue result under the hard memory budget.
V P recall-known -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"goal":"Read a fresh cue result under the hard memory budget.","inputs":{"$cl_type":"t18"},"steps":[{"action":"recall","args":{"budget":256,"situation":{"intent":{"$input":"query"}}},"check":"forgotten-cue","save":"fresh"}]},"key":"recall-empty","section":"procedures"}
P recall-empty(query:str):fresh=neyvia.memory.recall(budget:256 situation:{intent:query}) C forgotten-cue -- Read a fresh cue result under the hard memory budget.
V P recall-empty -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"cue-memory","data":{"failure":"memory_scope_unbound","recovery":"Use an authenticated Memory panel or a trusted scope-bound host; never supply owner IDs in tool arguments."},"key":"0","section":"pitfalls"}
X memory_scope_unbound -> Use an authenticated Memory panel or a trusted scope-bound host; never supply owner IDs in tool arguments.
-- @record {"chapter":"cue-memory","data":{"failure":"memory_revision_conflict","recovery":"Refresh the exact record and review its current revision before retrying."},"key":"1","section":"pitfalls"}
X memory_revision_conflict -> Refresh the exact record and review its current revision before retrying.
-- @record {"chapter":"cue-memory","data":{"failure":"memory_context_revoked","recovery":"Start a new chat. Opaque provider histories containing revoked memory cannot be continued."},"key":"2","section":"pitfalls"}
X memory_context_revoked -> Start a new chat. Opaque provider histories containing revoked memory cannot be continued.
-- @record {"chapter":"cue-memory","data":"Learned relevance tuning, automatic outcome promotion and cross-provider in-flight action guarantees require separate proof.","key":"0","section":"frontier"}
F Learned relevance tuning, automatic outcome promotion and cross-provider in-flight action guarantees require separate proof.
-- @record {"chapter":"cue-memory","data":"Opaque provider sessions require a fresh chat after revocation; externally transmitted provider data cannot be erased by this store.","key":"1","section":"frontier"}
F Opaque provider sessions require a fresh chat after revocation; externally transmitted provider data cannot be erased by this store.
-- @record {"chapter":"cue-memory","data":"Local MCP launchers without an authenticated context refuse memory. Local gateway proof is not proof that this executor exposes an attached Neyvia MCP.","key":"2","section":"frontier"}
F Local MCP launchers without an authenticated context refuse memory. Local gateway proof is not proof that this executor exposes an attached Neyvia MCP.
-- @record {"chapter":"cue-memory","data":"Memories are advisory data, never executable CL or authority. Ordinary chat is not scraped; unapproved suggestions stay pending.","key":"0","section":"guidance"}
M memory "Memories are advisory data, never executable CL or authority. Ordinary chat is not scraped; unapproved suggestions stay pending." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Write explicit teaching with /remember [--share] subject = claim; /correct subject = replacement; /forget subject. --share explicitly allows provider context.","key":"1","section":"guidance"}
M memory "Write explicit teaching with /remember [--share] subject = claim; /correct subject = replacement; /forget subject. --share explicitly allows provider context." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Local-only records are excluded from model-facing list, inspect and recall. Recall uses exact o200k text counts, at most three records and a 256-token default.","key":"2","section":"guidance"}
M memory "Local-only records are excluded from model-facing list, inspect and recall. Recall uses exact o200k text counts, at most three records and a 256-token default." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Only context-bound project/user records can surface. No unrelated recent fallback. LAYA is a finite-choice local advisory; failure is labelled deterministic.","key":"3","section":"guidance"}
M memory "Only context-bound project/user records can surface. No unrelated recent fallback. LAYA is a finite-choice local advisory; failure is labelled deterministic." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"The panel edits the same private SQLite store. Compare current revisions; deletions retain content-free tombstones and reject stale retries.","key":"4","section":"guidance"}
M memory "The panel edits the same private SQLite store. Compare current revisions; deletions retain content-free tombstones and reject stale retries." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Exact phrase cues require all meaningful cue words; a shared generic word cannot recall an unrelated subject.","key":"5","section":"guidance"}
M memory "Exact phrase cues require all meaningful cue words; a shared generic word cannot recall an unrelated subject." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Verified completed CL task outcomes create local-only pending procedure candidates. Process exits and provider prose cannot mark outcomes verified.","key":"6","section":"guidance"}
M memory "Verified completed CL task outcomes create local-only pending procedure candidates. Process exits and provider prose cannot mark outcomes verified." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Use an observer G before a mutating procedure, for example G: \"expected\" in memory.recall(situation={\"intent\":\"launch signal\"})[\"section\"].","key":"7","section":"guidance"}
M memory "Use an observer G before a mutating procedure, for example G: \"expected\" in memory.recall(situation={\"intent\":\"launch signal\"})[\"section\"]." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Repeat contract work with exercise-cases and exercise-lifecycle. The hidden browser driver uses production authentication and real provider chats; verify-browser reads its small result fields.","key":"8","section":"guidance"}
M memory "Repeat contract work with exercise-cases and exercise-lifecycle. The hidden browser driver uses production authentication and real provider chats; verify-browser reads its small result fields." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","data":"Server-launched Native SDK and MCP receive private scope through the parent environment. Unbound launchers refuse memory; model arguments cannot select owners.","key":"9","section":"guidance"}
M memory "Server-launched Native SDK and MCP receive private scope through the parent environment. Unbound launchers refuse memory; model arguments cannot select owners." src:"authored manual" state:verified
-- @record {"chapter":"cue-memory","section":"guidance","key":"10","data":"Backend host root owns memory even when a chat uses another project folder. The launcher supplies NEYVIA_MEMORY_HOST_ROOT and the exact project. Invalid bindings return no memory and log a reason; explicit unbound memory tools still refuse access."}
M memory "Backend host root owns memory even when a chat uses another project folder. The launcher supplies NEYVIA_MEMORY_HOST_ROOT and the exact project. Invalid bindings return no memory and log a reason; explicit unbound memory tools still refuse access." src:"authored manual" state:verified
