CL 1
L mission-plan v1 -- Authored executable manual
-- @manual {"chapters":{"fixcl3-local":{"title":"Exact retained local admission and supervision"},"orchestration":{"title":"Plan sections with Claude builders and Codex verification"},"proofs-c-missions":{"title":"PROOFS-c mission lifecycle contracts"},"proofs-c-missions-local-02":{"title":"PROOFS-c local mission evidence and admission contracts"},"proofs-e-frontend":{"title":"PROOFS-e frontend action contracts"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"}},"clVersion":"1.1","id":"mission-plan","kind":"workflow","proofs":{"area":"proofs-c-missions, proofs-e-frontend","manifests":["config/proofs/proofs-c-missions.json","config/proofs/proofs-e-frontend.json","config/proofs/proofs-e-models.json"],"startup":{"procedures":["receipt persistence/concurrency","artifact confinement","executor/verifier context boundaries","phase lifecycle/bounded repair","simulated acceptance harness repeated with isolated durable operation identities","continuity concurrency/corruption recovery","GPU cost/duration/idle policy","security scope/coverage/route separation","CLI durable orchestration","real local producer output and dialogue provenance","missing/read-only/concrete transcript priority","local durable read-model and flight recorder","hard/planned artifact repair with unrelated-failure rejection","fresh saved public-launch repair packet","saved measured-capacity admission","explicit native/POSIX path parsing","mission.shared-live-reset-and-artifact"],"runner":"grant_agent.proof_verifier.run_verification","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.mission.control":"t1","neyvia.mission.from_plan":"t2","neyvia.mission.list":"t3","proofs-e-models.status":"t3"},"tool_metadata":{"neyvia.mission.control":{"mutability_class":"none"},"neyvia.mission.from_plan":{"mutability_class":"none"},"neyvia.mission.list":{"mutability_class":"read"},"neyvia.verify.status":{"mutability_class":"none"}}}
-- @proof {"checkedAt":["mission_receipts.validate_mission_receipt -> proofs_c_missions.check_receipt","proofs_c_missions.self_check"],"claim":"Receipts use known schemas, producer phases, parseable timestamps, required fields and verification decisions; invalid input is rejected before append.","id":"proofs-c.missions.receipt-schema","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_receipts.append_mission_receipt -> proofs_c_missions.check_receipt_write (inside file lock)","proofs_c_missions.self_check"],"claim":"Locked appends persist the exact serialized stream tail, preserve concurrent receipts and bound retention; invalid input creates no stream.","id":"proofs-c.missions.receipt-durable","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_receipts.load_mission_receipts -> proofs_c_missions.check_receipt_read","proofs_c_missions.self_check"],"claim":"Receipt reads skip malformed rows, filter by mission before limiting and preserve durable stream order.","id":"proofs-c.missions.receipt-filter","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_receipts.validate_mission_receipt / mission_phase_runner -> proofs_c_missions.check_default_factories","proofs_c_missions.self_check"],"claim":"Mutable dataclass factories produce distinct containers; receipt validation and phase control reject shared default factories.","id":"proofs-c.missions.default-isolation","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_artifacts.build_mission_run_artifact_layout -> proofs_c_missions.check_layout","proofs_c_missions.self_check"],"claim":"File-safe mission IDs confine all layout paths to their canonical mission root; create builds the directories and create=false does not write.","id":"proofs-c.missions.artifact-layout","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_phase_inputs.build_executor_phase_input -> proofs_c_missions.check_capsule","proofs_c_missions.self_check"],"claim":"Executor handoff contains bounded goal/compact plan/selected skill IDs/file scope; wrong schemas and planner-only raw context are excluded.","id":"proofs-c.missions.executor-boundary","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_phase_inputs.build_verifier_phase_input -> proofs_c_missions.check_capsule","proofs_c_missions.self_check"],"claim":"Verifier handoff contains compact goal/plan/execution and ordered deduplicated changed files/artifacts; runtime metadata is excluded.","id":"proofs-c.missions.verifier-boundary","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_phase_inputs.check_selected_skill_relevance -> proofs_c_missions.check_relevance","proofs_c_missions.self_check"],"claim":"Empty skill selection blocks and irrelevant selected skills need review; counts exactly reflect inspected selection.","id":"proofs-c.missions.skill-relevance","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_phase_runner.start_current_phase/complete_current_phase -> proofs_c_missions.check_run","proofs_c_missions.self_check"],"claim":"Mission envelopes preserve lifecycle vocabulary, known schema, parseable timestamps and independently owned mutable state.","id":"proofs-c.missions.run-envelope","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_phase_runner.complete_current_phase -> proofs_c_missions.check_transition","proofs_c_missions.self_check"],"claim":"Phase control follows accepted successors/status, preserves receipt references, bounds repair loops, blocks exhausted repair and refuses terminal/completed restarts.","id":"proofs-c.missions.phase-transition","impact":["mission handoff","durable receipts","operator status"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_acceptance_harness.MissionAcceptanceHarness.run -> proofs_c_missions.check_acceptance","proofs_c_missions.self_check"],"claim":"The five simulated local harness journeys produce exact durable summaries and distinct attempt receipts; receipt flags clearly exclude real external/model execution.","id":"proofs-c.missions.acceptance-receipt","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["continuity_policy.MissionContinuityStore._create_or_update_unlocked/load -> proofs_c_missions.check_continuity_write/check_continuity_recovery","proofs_c_missions.self_check"],"claim":"Continuity writes under the mission lock increment the current revision once, persist exact facts and preserve the preceding valid snapshot; corrupt state recovers previous facts without inventing progress.","id":"proofs-c.missions.continuity-durable","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["continuity_policy.MissionContinuityStore.evaluate_gpu_action -> proofs_c_missions.check_gpu","proofs_c_missions.self_check"],"claim":"GPU decisions preserve estimated session cost, policy blockers, and duration/idle release requirements.","id":"proofs-c.missions.gpu-policy","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["security_runtime_policy.evaluate_security_action/build_purple_team_plan -> proofs_c_missions.check_security/check_security_plan","proofs_c_missions.self_check"],"claim":"Active security decisions require authorized owner/target/action scope and action-time approval where required; invalid budgets normalize safely and purple-team phases keep auditor/red/blue/defender separation.","id":"proofs-c.missions.security-scope","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["security_runtime_policy.audit_security_tool_coverage -> proofs_c_missions.check_security_coverage","proofs_c_missions.self_check"],"claim":"Security phase readiness exactly matches executable candidates; planned/unavailable tools never satisfy missing defensive coverage.","id":"proofs-c.missions.security-coverage","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.apply_agent_turn_mode_to_launch -> proofs_c_missions.check_turn_mode","proofs_c_missions.self_check"],"claim":"Turn modes preserve the goal and checks: plan adds the written-plan gate, fast lowers effort and caps a selected budget, max-context raises effort and Deep Run budget, standard preserves semantics.","id":"proofs-c.missions.turn-mode","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.ControlRoomStore._write_json_if_changed -> proofs_c_missions.check_control_write","proofs_c_missions.self_check"],"claim":"Successful control-room JSON writes equal the durable normalized payload before returning.","id":"proofs-c.missions.control-durable","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["cli.cmd_mission_orchestration -> proofs_c_missions.check_orchestration","proofs_c_missions.self_check"],"claim":"CLI orchestration returns only when the saved mission, runtime autonomy and receipt agree on concurrency/observation/merge/awareness policy.","id":"proofs-c.missions.orchestration-durable","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["fluxio_harness.infer_task_route_profile -> proofs_c_missions.check_security_route","proofs_c_missions.self_check"],"claim":"Matched red-team tasks use adversarial verification intent; matched blue-team tasks use defensive detection intent, with distinct mission types.","id":"proofs-c.missions.security-route","impact":["mission runtime","durable receipts","authority admission"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.mission_runtime_dialogue_turns -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Dialogue contains only eligible captured output or durable runtime-output text, preserving runtime/model/source/capture provenance and excluding control events.","id":"proofs-c.missions.local-dialogue","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.ControlRoomStore._mission_runtime_transcript_payload -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Transcript attachment requires concrete output or artifact evidence, retains rejected-session evidence, prefers the latest concrete session, and exposes missing evidence without synthetic messages.","id":"proofs-c.missions.local-transcript","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.ControlRoomStore._mission_agent_messages_payload -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Agent-message projection preserves dialogue receipts and marks control-room planning, actions, heartbeats and integrity notes as trace-only bookkeeping.","id":"proofs-c.missions.local-messages","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.ControlRoomStore._mission_run_read_model_payload -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Mission read models preserve identity, lifecycle and filtered ordered receipts without changing missions.json; foreign snapshots never replace the current mission.","id":"proofs-c.missions.local-read-model","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.ControlRoomStore._compact_flight_recorder_payload -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Flight-recorder projection preserves written phase, process IDs and bounded event history; absent or invalid snapshots never invent events.","id":"proofs-c.missions.local-flight","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control.mission_hard_artifact_gate -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Hard artifact completion requires both meaningful runtime output and concrete artifact evidence; either missing boundary stays failed.","id":"proofs-c.missions.local-artifact-gate","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control._complete_repaired_hard_artifact_gate_from_detail -> proofs_c_missions.check_local_projection","mission_control._complete_repaired_planned_scope_artifact_gate_from_detail -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Artifact repair completes only after the failed gate is actually ready and no unrelated failures remain; rejected repairs preserve mission state and successful repair is durable.","id":"proofs-c.missions.local-artifact-repair","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control._public_launch_readiness_digest -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Public-launch digest selects the freshest saved evidence and preserves operator repair/publication fields; missing receipts cannot claim readiness.","id":"proofs-c.missions.local-public-launch","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["cli._mission_storage_pressure_blocker -> proofs_c_missions.check_local_projection","proofs_c_missions.self_check"],"claim":"Storage launch admission blocks only from saved measured-capacity evidence; unknown or failed probe states never invent disk pressure.","id":"proofs-c.missions.local-storage","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["mission_control._platform_path_for_windows_drive -> proofs_c_missions.check_platform_path","proofs_c_missions.self_check"],"claim":"Explicit platform parsing preserves Windows drive and tail when converting to POSIX mount form and preserves native paths; parsing does not probe or launch WSL.","id":"proofs-c.missions.local-platform","impact":["mission evidence projection","truthful completion","operator repair"],"phase":"invariant"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxMissionsModel.js:shapeMission -> checkedProofsEModel"],"claim":"Mission observers retain tasks, normalize unknown states, compute prerequisite levels and progress, and preserve draft/paused/stopped phases","id":"missions.shapeMission","impact":["missions frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxMissionsModel.js:draftProblems -> checkedProofsEModel"],"claim":"Mission drafts need a goal, folder, task prompts, acceptance and a positive optional budget","id":"missions.draftProblems","impact":["missions frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxMissionsModel.js:createRequest -> checkedProofsEModel"],"claim":"Creation trims fields, preserves harness/model routing and removes self/missing prerequisites; optional positive budget is rounded","id":"missions.createRequest","impact":["missions frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxMissionsModel.js:planPrompt -> checkedProofsEModel"],"claim":"Planning asks for the real mission.create tool and explicitly leaves starting to the person","id":"missions.planPrompt","impact":["missions frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/neyviaMissionProjection.js:projectAgentLiveView -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.live","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.live","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.live"],"claim":"Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","id":"mission.live","impact":["neyviaMissionProjection"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/neyviaMissionProjection.js:applyMissionEventDelta -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.delta","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.delta","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.delta"],"claim":"Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","id":"mission.delta","impact":["neyviaMissionProjection"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/neyviaMissionProjection.js:mergeMissionArtifacts -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.artifacts","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.artifacts","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.mission.artifacts"],"claim":"Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","id":"mission.artifacts","impact":["neyviaMissionProjection"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"action\":{\"type\":\"string\",\"enum\":[\"start\",\"pause\",\"stop\",\"redirect\"]},\"taskId\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"}},\"required\":[\"id\",\"action\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"planPath\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"goal\":{\"type\":\"string\"},\"folders\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}},\"builder\":{\"type\":\"object\"},\"verifier\":{\"type\":\"object\"},\"holdAtPlanPercent\":{\"type\":[\"integer\",\"null\"],\"minimum\":1,\"maximum\":100},\"budget\":{\"type\":\"object\"},\"acceptanceChecks\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"planPath\",\"folder\",\"acceptanceChecks\"],\"allOf\":[{\"properties\":{\"planPath\":{\"not\":{\"enum\":[\"\"]}},\"folder\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{..}
T t4 json:"{\"type\":\"object\"}"
T t5{}
T t6{ok:bool ..}
T t7 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L mission-plan.fixcl3-local v1 -- Exact retained local admission and supervision
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained mission.from_plan","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.mission.from_plan","tool":"neyvia.mission.from_plan"},"key":"neyvia.mission.from_plan","section":"actions"}
A neyvia.mission.from_plan(planPath:str folder:str id?:str goal?:str folders?:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" builder?:json:"{\"type\":\"object\"}" verifier?:json:"{\"type\":\"object\"}" holdAtPlanPercent?:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1,\"maximum\":100}" budget?:json:"{\"type\":\"object\"}" acceptanceChecks:[str]) -> json:"{\"type\":\"object\"}" -- Exact retained mission.from_plan
F verify-neyvia-mission-from_plan "No authored observer check is bound to neyvia.mission.from_plan" -> ask operator blocks:neyvia.mission.from_plan
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained mission.control","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.mission.control","tool":"neyvia.mission.control"},"key":"neyvia.mission.control","section":"actions"}
A neyvia.mission.control(id:str action:json:"{\"type\":\"string\",\"enum\":[\"start\",\"pause\",\"stop\",\"redirect\"]}" taskId?:str prompt?:str model?:str effort?:str permissionMode?:str) -> json:"{\"type\":\"object\"}" -- Exact retained mission.control
F verify-neyvia-mission-control "No authored observer check is bound to neyvia.mission.control" -> ask operator blocks:neyvia.mission.control
-- @record {"chapter":"fixcl3-local","data":{"failure":"Fresh owner state differs from this action subject","recovery":"Reconcile the specific retained effect; never replay an uncertain launch."},"key":"0","section":"pitfalls"}
X Fresh owner state differs from this action subject -> Reconcile the specific retained effect; never replay an uncertain launch.
-- @record {"chapter":"fixcl3-local","data":"Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.","key":"0","section":"frontier"}
F Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.
-- @record {"chapter":"fixcl3-local","data":"CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes.","key":"0","section":"guidance"}
M mission-plan "CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes." src:"authored manual" state:verified
L mission-plan.orchestration v1 -- Plan sections with Claude builders and Codex verification
-- @record {"chapter":"orchestration","data":{"args":{},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t4"},"tool":"neyvia.mission.list"},"key":"missions","section":"state"}
S mission-plan.missions:json:"{\"type\":\"object\"}"=neyvia.mission.list()
-- @record {"chapter":"orchestration","data":{"effect":"Store dormant section tasks","pre":"Existing distinct worktrees and assigned unique ports; exact launch intent requires owner approval","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.mission.from_plan","tool":"neyvia.mission.from_plan"},"key":"neyvia.mission.from_plan","section":"actions"}
A neyvia.mission.from_plan(planPath:str folder:str id?:str goal?:str folders?:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}" builder?:json:"{\"type\":\"object\"}" verifier?:json:"{\"type\":\"object\"}" holdAtPlanPercent?:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1,\"maximum\":100}" budget?:json:"{\"type\":\"object\"}" acceptanceChecks:[str]) -> json:"{\"type\":\"object\"}" -- Store dormant section tasks
F verify-neyvia-mission-from_plan "No authored observer check is bound to neyvia.mission.from_plan" -> ask operator blocks:neyvia.mission.from_plan
-- @record {"chapter":"orchestration","data":{"effect":"Read or supervise mission tasks","pre":"Existing distinct worktrees and assigned unique ports; exact launch intent requires owner approval","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.mission.control","tool":"neyvia.mission.control"},"key":"neyvia.mission.control","section":"actions"}
A neyvia.mission.control(id:str action:json:"{\"type\":\"string\",\"enum\":[\"start\",\"pause\",\"stop\",\"redirect\"]}" taskId?:str prompt?:str model?:str effort?:str permissionMode?:str) -> json:"{\"type\":\"object\"}" -- Read or supervise mission tasks
F verify-neyvia-mission-control "No authored observer check is bound to neyvia.mission.control" -> ask operator blocks:neyvia.mission.control
-- @record {"chapter":"orchestration","data":{"effect":"Read or supervise mission tasks","pre":"Existing distinct worktrees and assigned unique ports; exact launch intent requires owner approval","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.mission.list","tool":"neyvia.mission.list"},"key":"neyvia.mission.list","section":"actions"}
A neyvia.mission.list() -> json:"{\"type\":\"object\"}" -- Read or supervise mission tasks
F verify-neyvia-mission-list "No authored observer check is bound to neyvia.mission.list" -> ask operator blocks:neyvia.mission.list
-- @record {"chapter":"orchestration","data":{"constraints":"Use mission.control only after review; completed runs do not imply verifier PASS.","options":["approve","stop"],"question":"Do the stored prompts, routes, worktrees, ports and acceptance checks match the approved scope?"},"key":"review","section":"judge"}
J review approve|stop:"Do the stored prompts, routes, worktrees, ports and acceptance checks match the approved scope?" -- Use mission.control only after review; completed runs do not imply verifier PASS.
V J review -> human:operator why:"explicit choice required"
-- @record {"chapter":"orchestration","data":{"failure":"Unsupported model or verification reports a failure","recovery":"Preserve failed run evidence; repair in scope and rerun verification; never silently change providers."},"key":"0","section":"pitfalls"}
X Unsupported model or verification reports a failure -> Preserve failed run evidence; repair in scope and rerun verification; never silently change providers.
-- @record {"chapter":"orchestration","data":"Table allocations guide harness prompts; they do not enforce operating-system port bindings.","key":"0","section":"frontier"}
F Table allocations guide harness prompts; they do not enforce operating-system port bindings.
-- @record {"chapter":"orchestration","data":"Use ## Â§0 shared rules and ## Â§1 track: title sections plus a Track/Worktree/Backend/Vite table.","key":"0","section":"guidance"}
M mission-plan "Use ## Â§0 shared rules and ## Â§1 track: title sections plus a Track/Worktree/Backend/Vite table." src:"authored manual" state:verified
-- @record {"chapter":"orchestration","data":"One Codex integration verifier needs every Claude build; import remains dormant; verifier stays waiting until all builds are done.","key":"1","section":"guidance"}
M mission-plan "One Codex integration verifier needs every Claude build; import remains dormant; verifier stays waiting until all builds are done." src:"authored manual" state:verified
-- @record {"chapter":"orchestration","data":"holdAtPlanPercent defaults to 70 and independently paces each app; unknown usage remains unknown.","key":"2","section":"guidance"}
M mission-plan "holdAtPlanPercent defaults to 70 and independently paces each app; unknown usage remains unknown." src:"authored manual" state:verified
L mission-plan.proofs-c-missions v1 -- PROOFS-c mission lifecycle contracts
-- @record {"chapter":"proofs-c-missions","data":{"failure":"A receipt or phase contract fails","recovery":"Preserve evidence and repair its owner; phase-only receipts do not prove model execution."},"key":"0","section":"pitfalls"}
X A receipt or phase contract fails -> Preserve evidence and repair its owner; phase-only receipts do not prove model execution.
-- @record {"chapter":"proofs-c-missions","data":"Supervisor peer coordination remains outside authorized scope; its orchestration test remains.","key":"0","section":"frontier"}
F Supervisor peer coordination remains outside authorized scope; its orchestration test remains.
-- @record {"chapter":"proofs-c-missions","data":"Installed security audit requires honest execution/delegation observations; no fake connected-provider fixture is claimed.","key":"1","section":"frontier"}
F Installed security audit requires honest execution/delegation observations; no fake connected-provider fixture is claimed.
-- @record {"chapter":"proofs-c-missions","data":"Mission-control cases outside turn-mode mapping are owned by separate control workers.","key":"2","section":"frontier"}
F Mission-control cases outside turn-mode mapping are owned by separate control workers.
-- @record {"chapter":"proofs-c-missions","data":"These contracts execute inside production Python mission actions; neyvia verify runs their disposable startup journey.","key":"0","section":"guidance"}
M mission-plan "These contracts execute inside production Python mission actions; neyvia verify runs their disposable startup journey." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"Acceptance harness intentionally runs stub MCP adapters: its receipts say simulated=true and do not prove external model/provider execution.","key":"1","section":"guidance"}
M mission-plan "Acceptance harness intentionally runs stub MCP adapters: its receipts say simulated=true and do not prove external model/provider execution." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.receipt-schema: Receipts use known schemas, producer phases, parseable timestamps, required fields and verification decisions; invalid input is rejected before append.","key":"2","section":"guidance"}
M mission-plan "proofs-c.missions.receipt-schema: Receipts use known schemas, producer phases, parseable timestamps, required fields and verification decisions; invalid input is rejected before append." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.receipt-durable: Locked appends persist the exact serialized stream tail, preserve concurrent receipts and bound retention; invalid input creates no stream.","key":"3","section":"guidance"}
M mission-plan "proofs-c.missions.receipt-durable: Locked appends persist the exact serialized stream tail, preserve concurrent receipts and bound retention; invalid input creates no stream." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.receipt-filter: Receipt reads skip malformed rows, filter by mission before limiting and preserve durable stream order.","key":"4","section":"guidance"}
M mission-plan "proofs-c.missions.receipt-filter: Receipt reads skip malformed rows, filter by mission before limiting and preserve durable stream order." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.default-isolation: Mutable dataclass factories produce distinct containers; receipt validation and phase control reject shared default factories.","key":"5","section":"guidance"}
M mission-plan "proofs-c.missions.default-isolation: Mutable dataclass factories produce distinct containers; receipt validation and phase control reject shared default factories." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.artifact-layout: File-safe mission IDs confine all layout paths to their canonical mission root; create builds the directories and create=false does not write.","key":"6","section":"guidance"}
M mission-plan "proofs-c.missions.artifact-layout: File-safe mission IDs confine all layout paths to their canonical mission root; create builds the directories and create=false does not write." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.executor-boundary: Executor handoff contains bounded goal/compact plan/selected skill IDs/file scope; wrong schemas and planner-only raw context are excluded.","key":"7","section":"guidance"}
M mission-plan "proofs-c.missions.executor-boundary: Executor handoff contains bounded goal/compact plan/selected skill IDs/file scope; wrong schemas and planner-only raw context are excluded." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.verifier-boundary: Verifier handoff contains compact goal/plan/execution and ordered deduplicated changed files/artifacts; runtime metadata is excluded.","key":"8","section":"guidance"}
M mission-plan "proofs-c.missions.verifier-boundary: Verifier handoff contains compact goal/plan/execution and ordered deduplicated changed files/artifacts; runtime metadata is excluded." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.skill-relevance: Empty skill selection blocks and irrelevant selected skills need review; counts exactly reflect inspected selection.","key":"9","section":"guidance"}
M mission-plan "proofs-c.missions.skill-relevance: Empty skill selection blocks and irrelevant selected skills need review; counts exactly reflect inspected selection." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.run-envelope: Mission envelopes preserve lifecycle vocabulary, known schema, parseable timestamps and independently owned mutable state.","key":"10","section":"guidance"}
M mission-plan "proofs-c.missions.run-envelope: Mission envelopes preserve lifecycle vocabulary, known schema, parseable timestamps and independently owned mutable state." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.phase-transition: Phase control follows accepted successors/status, preserves receipt references, bounds repair loops, blocks exhausted repair and refuses terminal/completed restarts.","key":"11","section":"guidance"}
M mission-plan "proofs-c.missions.phase-transition: Phase control follows accepted successors/status, preserves receipt references, bounds repair loops, blocks exhausted repair and refuses terminal/completed restarts." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.acceptance-receipt: The five simulated local harness journeys produce exact durable summaries and distinct attempt receipts; receipt flags clearly exclude real external/model execution.","key":"12","section":"guidance"}
M mission-plan "proofs-c.missions.acceptance-receipt: The five simulated local harness journeys produce exact durable summaries and distinct attempt receipts; receipt flags clearly exclude real external/model execution." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.continuity-durable: Continuity writes under the mission lock increment the current revision once, persist exact facts and preserve the preceding valid snapshot; corrupt state recovers previous facts without inventing progress.","key":"13","section":"guidance"}
M mission-plan "proofs-c.missions.continuity-durable: Continuity writes under the mission lock increment the current revision once, persist exact facts and preserve the preceding valid snapshot; corrupt state recovers previous facts without inventing progress." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.gpu-policy: GPU decisions preserve estimated session cost, policy blockers, and duration/idle release requirements.","key":"14","section":"guidance"}
M mission-plan "proofs-c.missions.gpu-policy: GPU decisions preserve estimated session cost, policy blockers, and duration/idle release requirements." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.security-scope: Active security decisions require authorized owner/target/action scope and action-time approval where required; invalid budgets normalize safely and purple-team phases keep auditor/red/blue/defender separation.","key":"15","section":"guidance"}
M mission-plan "proofs-c.missions.security-scope: Active security decisions require authorized owner/target/action scope and action-time approval where required; invalid budgets normalize safely and purple-team phases keep auditor/red/blue/defender separation." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.security-coverage: Security phase readiness exactly matches executable candidates; planned/unavailable tools never satisfy missing defensive coverage.","key":"16","section":"guidance"}
M mission-plan "proofs-c.missions.security-coverage: Security phase readiness exactly matches executable candidates; planned/unavailable tools never satisfy missing defensive coverage." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.turn-mode: Turn modes preserve the goal and checks: plan adds the written-plan gate, fast lowers effort and caps a selected budget, max-context raises effort and Deep Run budget, standard preserves semantics.","key":"17","section":"guidance"}
M mission-plan "proofs-c.missions.turn-mode: Turn modes preserve the goal and checks: plan adds the written-plan gate, fast lowers effort and caps a selected budget, max-context raises effort and Deep Run budget, standard preserves semantics." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.control-durable: Successful control-room JSON writes equal the durable normalized payload before returning.","key":"18","section":"guidance"}
M mission-plan "proofs-c.missions.control-durable: Successful control-room JSON writes equal the durable normalized payload before returning." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.orchestration-durable: CLI orchestration returns only when the saved mission, runtime autonomy and receipt agree on concurrency/observation/merge/awareness policy.","key":"19","section":"guidance"}
M mission-plan "proofs-c.missions.orchestration-durable: CLI orchestration returns only when the saved mission, runtime autonomy and receipt agree on concurrency/observation/merge/awareness policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions","data":"proofs-c.missions.security-route: Matched red-team tasks use adversarial verification intent; matched blue-team tasks use defensive detection intent, with distinct mission types.","key":"20","section":"guidance"}
M mission-plan "proofs-c.missions.security-route: Matched red-team tasks use adversarial verification intent; matched blue-team tasks use defensive detection intent, with distinct mission types." src:"authored manual" state:verified
L mission-plan.proofs-c-missions-local-02 v1 -- PROOFS-c local mission evidence and admission contracts
-- @record {"chapter":"proofs-c-missions-local-02","data":{"failure":"Saved projection data is mistaken for external runtime execution","recovery":"Inspect producer/source/capture evidence; this self-check runs a local Python producer and never claims a model/provider or WSL session."},"key":"0","section":"pitfalls"}
X Saved projection data is mistaken for external runtime execution -> Inspect producer/source/capture evidence; this self-check runs a local Python producer and never claims a model/provider or WSL session.
-- @record {"chapter":"proofs-c-missions-local-02","data":"Local transcript/read-model/flight/artifact-repair self-checks prove helper boundaries only; aggregate snapshot/detail tests remain until their collector-dependent assertions can be executed within authorization.","key":"0","section":"frontier"}
F Local transcript/read-model/flight/artifact-repair self-checks prove helper boundaries only; aggregate snapshot/detail tests remain until their collector-dependent assertions can be executed within authorization.
-- @record {"chapter":"proofs-c-missions-local-02","data":"Saved storage fixtures exercise admission logic without probing a NAS or claiming actual disk capacity.","key":"1","section":"frontier"}
F Saved storage fixtures exercise admission logic without probing a NAS or claiming actual disk capacity.
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-dialogue: Dialogue contains only eligible captured output or durable runtime-output text, preserving runtime/model/source/capture provenance and excluding control events.","key":"0","section":"guidance"}
M mission-plan "proofs-c.missions.local-dialogue: Dialogue contains only eligible captured output or durable runtime-output text, preserving runtime/model/source/capture provenance and excluding control events." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-transcript: Transcript attachment requires concrete output or artifact evidence, retains rejected-session evidence, prefers the latest concrete session, and exposes missing evidence without synthetic messages.","key":"1","section":"guidance"}
M mission-plan "proofs-c.missions.local-transcript: Transcript attachment requires concrete output or artifact evidence, retains rejected-session evidence, prefers the latest concrete session, and exposes missing evidence without synthetic messages." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-messages: Agent-message projection preserves dialogue receipts and marks control-room planning, actions, heartbeats and integrity notes as trace-only bookkeeping.","key":"2","section":"guidance"}
M mission-plan "proofs-c.missions.local-messages: Agent-message projection preserves dialogue receipts and marks control-room planning, actions, heartbeats and integrity notes as trace-only bookkeeping." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-read-model: Mission read models preserve identity, lifecycle and filtered ordered receipts without changing missions.json; foreign snapshots never replace the current mission.","key":"3","section":"guidance"}
M mission-plan "proofs-c.missions.local-read-model: Mission read models preserve identity, lifecycle and filtered ordered receipts without changing missions.json; foreign snapshots never replace the current mission." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-flight: Flight-recorder projection preserves written phase, process IDs and bounded event history; absent or invalid snapshots never invent events.","key":"4","section":"guidance"}
M mission-plan "proofs-c.missions.local-flight: Flight-recorder projection preserves written phase, process IDs and bounded event history; absent or invalid snapshots never invent events." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-artifact-gate: Hard artifact completion requires both meaningful runtime output and concrete artifact evidence; either missing boundary stays failed.","key":"5","section":"guidance"}
M mission-plan "proofs-c.missions.local-artifact-gate: Hard artifact completion requires both meaningful runtime output and concrete artifact evidence; either missing boundary stays failed." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-artifact-repair: Artifact repair completes only after the failed gate is actually ready and no unrelated failures remain; rejected repairs preserve mission state and successful repair is durable.","key":"6","section":"guidance"}
M mission-plan "proofs-c.missions.local-artifact-repair: Artifact repair completes only after the failed gate is actually ready and no unrelated failures remain; rejected repairs preserve mission state and successful repair is durable." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-public-launch: Public-launch digest selects the freshest saved evidence and preserves operator repair/publication fields; missing receipts cannot claim readiness.","key":"7","section":"guidance"}
M mission-plan "proofs-c.missions.local-public-launch: Public-launch digest selects the freshest saved evidence and preserves operator repair/publication fields; missing receipts cannot claim readiness." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-storage: Storage launch admission blocks only from saved measured-capacity evidence; unknown or failed probe states never invent disk pressure.","key":"8","section":"guidance"}
M mission-plan "proofs-c.missions.local-storage: Storage launch admission blocks only from saved measured-capacity evidence; unknown or failed probe states never invent disk pressure." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-missions-local-02","data":"proofs-c.missions.local-platform: Explicit platform parsing preserves Windows drive and tail when converting to POSIX mount form and preserves native paths; parsing does not probe or launch WSL.","key":"9","section":"guidance"}
M mission-plan "proofs-c.missions.local-platform: Explicit platform parsing preserves Windows drive and tail when converting to POSIX mount form and preserves native paths; parsing does not probe or launch WSL." src:"authored manual" state:verified
L mission-plan.proofs-e-frontend v1 -- PROOFS-e frontend action contracts
-- @record {"chapter":"proofs-e-frontend","data":{"failure":"Host/backend or rendered behavior has not been inspected.","recovery":"Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers."},"key":"0","section":"pitfalls"}
X Host/backend or rendered behavior has not been inspected. -> Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers.
-- @record {"chapter":"proofs-e-frontend","data":"Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.","key":"0","section":"frontier"}
F Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.
-- @record {"chapter":"proofs-e-frontend","data":"mission.live: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","key":"0","section":"guidance"}
M mission-plan "mission.live: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"mission.delta: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","key":"1","section":"guidance"}
M mission-plan "mission.delta: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"mission.artifacts: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound.","key":"2","section":"guidance"}
M mission-plan "mission.artifacts: Builder and Agent Live share mission evidence; only executing statuses are live, rotated logs discard old events and artifact endpoints remain bound." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json","key":"3","section":"guidance"}
M mission-plan "Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Startup procedures: mission.shared-live-reset-and-artifact","key":"4","section":"guidance"}
M mission-plan "Startup procedures: mission.shared-live-reset-and-artifact" src:"authored manual" state:verified
L mission-plan.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t3"},"shape":{"$cl_type":"t6"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S mission-plan.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t7"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t3"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"missions.shapeMission: Mission observers retain tasks, normalize unknown states, compute prerequisite levels and progress, and preserve draft/paused/stopped phases","key":"0","section":"guidance"}
M mission-plan "missions.shapeMission: Mission observers retain tasks, normalize unknown states, compute prerequisite levels and progress, and preserve draft/paused/stopped phases" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"missions.draftProblems: Mission drafts need a goal, folder, task prompts, acceptance and a positive optional budget","key":"1","section":"guidance"}
M mission-plan "missions.draftProblems: Mission drafts need a goal, folder, task prompts, acceptance and a positive optional budget" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"missions.createRequest: Creation trims fields, preserves harness/model routing and removes self/missing prerequisites; optional positive budget is rounded","key":"2","section":"guidance"}
M mission-plan "missions.createRequest: Creation trims fields, preserves harness/model routing and removes self/missing prerequisites; optional positive budget is rounded" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"missions.planPrompt: Planning asks for the real mission.create tool and explicitly leaves starting to the person","key":"3","section":"guidance"}
M mission-plan "missions.planPrompt: Planning asks for the real mission.create tool and explicitly leaves starting to the person" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"4","section":"guidance"}
M mission-plan "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
