CL 1
L mobile-studio v1 -- Authored executable manual
-- @manual {"chapters":{"apple-targets":{"title":"Windows Apple builds and three simulation tiers"},"fixcl3-local":{"title":"Exact retained local admission and supervision"},"overview":{"title":"Web-export frames and Windows iPhone/iPad/Mac builds; Android uses existing SDK"},"proofs-c-local-authoring":{"title":"PROOFS-c local authoring and package contracts"}},"clVersion":"1.1","id":"mobile-studio","kind":"environment","proofs":{"area":"proofs-c-mobile","manifests":["config/proofs/proofs-c-mobile.json"],"startup":{"procedures":["author-configure-package-reload-reject"],"runner":"grant_agent.proofs_c_mobile.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.browser.capture":"t1","neyvia.mobile.build":"t2","neyvia.mobile.create":"t3","neyvia.mobile.install":"t4","neyvia.mobile.preview":"t5","neyvia.mobile.setup":"t6","neyvia.mobile.simulate":"t7","neyvia.mobile.status":"t8","neyvia.mobile.verify":"t9"},"tool_metadata":{"neyvia.browser.capture":{"mutability_class":"artifact_write"},"neyvia.mobile.build":{"mutability_class":"external_action"},"neyvia.mobile.create":{"mutability_class":"artifact_write"},"neyvia.mobile.install":{"mutability_class":"external_action"},"neyvia.mobile.preview":{"mutability_class":"none"},"neyvia.mobile.setup":{"mutability_class":"none"},"neyvia.mobile.simulate":{"mutability_class":"artifact_write"},"neyvia.mobile.status":{"mutability_class":"read"},"neyvia.mobile.verify":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["ios_studio.create_ios_app -> proofs_c_mobile.check_project"],"claim":"Created Expo authoring files retain requested identity, entrypoint and supported dependency versions.","id":"proofs-c.mobile.project","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["ios_studio._safe_child"],"claim":"Creation rejects paths outside selected root before any effects.","id":"proofs-c.mobile.scope","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"pre"}
-- @proof {"checkedAt":["ios_studio.create_ios_app"],"claim":"Creation requires a valid reverse-domain bundle identifier before writing.","id":"proofs-c.mobile.bundle-id","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"pre"}
-- @proof {"checkedAt":["ios_studio.create_ios_build_capsule -> proofs_c_mobile.check_capsule"],"claim":"Each capsule retains its source root and exact manifest, excluding generated paths, confidential suffixes and links.","id":"proofs-c.mobile.capsule","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["ios_studio.save_ios_builder -> proofs_c_mobile.check_config"],"claim":"Builder metadata persists only the allowed fields and signing references, without passwords.","id":"proofs-c.mobile.builder-config","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler.save_windows_ios_config -> proofs_c_mobile.check_config"],"claim":"Compiler preferences validate before writing and persist exactly, without signing passwords.","id":"proofs-c.mobile.compiler-config","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler._download_verified"],"claim":"Downloaded bytes match the expected digest before atomic promotion; mismatch never promotes a destination.","id":"proofs-c.mobile.download-digest","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler._write_info_plist -> proofs_c_mobile.check_plist"],"claim":"Persisted plist exactly matches identity and iPhoneOS platform metadata.","id":"proofs-c.mobile.metadata","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler._zip_payload -> proofs_c_mobile.check_package"],"claim":"IPA archive contains exactly the app files under Payload with unchanged bytes.","id":"proofs-c.mobile.package","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler._safe_copy_web_assets -> proofs_c_mobile.check_web_assets"],"claim":"Assets stage inside the app www directory and root-relative links become local links.","id":"proofs-c.mobile.web-assets","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["windows_ios_compiler._clean_error"],"claim":"Failure receipts strip terminal control codes and retain bounded useful text.","id":"proofs-c.mobile.error-text","impact":["local app source","Mobile Studio authoring","build capsule","package receipts"],"phase":"post"}
-- @proof {"checkedAt":["web_backend.FluxioWebBackend.dispatch -> proofs_c_mobile.check_backend"],"claim":"Mobile authoring, status and compiler configuration commands retain requested workspace, app identity, current recognition and preferences.","id":"proofs-c.mobile.backend-wiring","impact":["authenticated command API","Mobile Studio source and status","compiler preferences"],"phase":"post"}
-- @proof {"checkedAt":["apple_targets.verify -> apple_bundle.verify_bundle; edge_fixture_mobile.run_apple_artifacts"],"claim":"Real retained iPhone/iPad/Mac bundles pass independent byte, archive, Mach-O and signature integrity checks; C7 copy mutations must fail without changing originals. No Apple-host trust claim.","id":"mobile-studio.apple-artifact-integrity","impact":["Apple bundles","archive integrity"],"phase":"post"}
-- @proof {"checkedAt":["edge_fixture_mobile.run_apple_preview -> scripts/apple/preview.py + preview.mjs"],"claim":"C7 captures the real authenticated Scroll Study UI in iPhone/Mac/iPad frames, operates controls and records sandbox storage limits; no native Apple execution claim.","id":"mobile-studio.apple-preview-rendered","impact":["Mobile Studio","Scroll Study preview"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"tabId\":{\"type\":\"string\"},\"fullPage\":{\"type\":\"boolean\"}},\"required\":[\"tabId\"],\"allOf\":[{\"properties\":{\"tabId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2{platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" project?:str waitSeconds?:0..900 addShell?:bool ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"bundleId\":{\"type\":\"string\"}},\"required\":[\"path\",\"name\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}},\"name\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"target\":{\"type\":\"string\"},\"project\":{\"type\":\"string\"},\"avd\":{\"type\":\"string\"},\"waitSeconds\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":600}},\"required\":[\"target\"],\"allOf\":[{\"properties\":{\"target\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{device?:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}" project?:str orientation?:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}" dark?:bool startExpo?:bool textScale?:0.8..2 keyboard?:bool ..}
T t6{part:json:"{\"type\":\"string\",\"enum\":[\"ios-compiler\"]}" project?:str ..}
T t7{project?:str tier:json:"{\"type\":\"string\",\"enum\":[\"instant\",\"cloud\",\"device\"]}" platform?:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" results?:str ..}
T t8{project?:str ..}
T t9{project?:str platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" ..}
T t10{project:str ..}
T t11 json:"{\"type\":\"object\"}"
T t12{project:str}
T t13{project:str device?:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}"="iphone-16-pro" orientation?:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}"="portrait" dark?:bool=false textScale?:0.8..2=1 keyboard?:bool=false}
T t14{project:str results:str}
T t15{tabId:str ..}
T t16{}
T t17{device:str orientation:str dark:bool jobs:json:"{\"type\":\"array\"}" ..}
T t18{device:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}" orientation:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}"}
T t19{project:str platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" addShell?:bool=false}
T t20{path:str name:str bundleId?:str="" approvedRequest?:str=""}
L mobile-studio.apple-targets v1 -- Windows Apple builds and three simulation tiers
-- @record {"chapter":"apple-targets","data":{"args":{"project":{"$input":"project"}},"inputs":{"$cl_type":"t10"},"shape":{"$cl_type":"t11"},"tool":"neyvia.mobile.status"},"key":"apple","section":"state"}
S mobile-studio.apple:json:"{\"type\":\"object\"}"=neyvia.mobile.status(project:project)
-- @record {"chapter":"apple-targets","data":{"effect":"Read current Apple support, previews and build receipts","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.status","tool":"neyvia.mobile.status"},"key":"status","section":"actions"}
A neyvia.mobile.status(project?:str) -> json:"{\"type\":\"object\"}" -- Read current Apple support, previews and build receipts
C neyvia.mobile.status unsupported-declared:neyvia.mobile.status(project:project) .apple.targets.watchos.build == false
-- @record {"chapter":"apple-targets","data":{"effect":"Compile, sign and package the selected supported Apple target on Windows","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.build","tool":"neyvia.mobile.build"},"key":"build","section":"actions"}
A neyvia.mobile.build(platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" project?:str waitSeconds?:0..900 addShell?:bool) -> json:"{\"type\":\"object\"}" ! -- Compile, sign and package the selected supported Apple target on Windows
F verify-build "No authored observer check is bound to neyvia.mobile.build" -> ask operator blocks:neyvia.mobile.build
-- @record {"chapter":"apple-targets","data":{"effect":"Re-read bundle and archive; verify target, executable pages, resource and metadata hashes","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.verify","tool":"neyvia.mobile.verify"},"key":"verify","section":"actions"}
A neyvia.mobile.verify(project?:str platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}") -> json:"{\"type\":\"object\"}" -- Re-read bundle and archive; verify target, executable pages, resource and metadata hashes
C neyvia.mobile.verify bundle-valid-ios:neyvia.mobile.verify(platform:"ios" project:project) .ok == true
C neyvia.mobile.verify no-native-claim-ios:neyvia.mobile.verify(platform:"ios" project:project) .nativeExecutionVerified == false
C neyvia.mobile.verify bundle-valid-ipados:neyvia.mobile.verify(platform:"ipados" project:project) .ok == true
C neyvia.mobile.verify no-native-claim-ipados:neyvia.mobile.verify(platform:"ipados" project:project) .nativeExecutionVerified == false
C neyvia.mobile.verify bundle-valid-macos:neyvia.mobile.verify(platform:"macos" project:project) .ok == true
C neyvia.mobile.verify no-native-claim-macos:neyvia.mobile.verify(platform:"macos" project:project) .nativeExecutionVerified == false
-- @record {"chapter":"apple-targets","data":{"effect":"Persist emulated frame, colour, rem text scaling and optional web keyboard","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.preview","tool":"neyvia.mobile.preview"},"key":"preview","section":"actions"}
A neyvia.mobile.preview(device?:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}" project?:str orientation?:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}" dark?:bool startExpo?:bool textScale?:0.8..2 keyboard?:bool) -> json:"{\"type\":\"object\"}" ! -- Persist emulated frame, colour, rem text scaling and optional web keyboard
C neyvia.mobile.preview preview-present:neyvia.mobile.status(project:project) .preview.ready == true
-- @record {"chapter":"apple-targets","data":{"effect":"Instant browser frame, dormant cloud preparation/import or real-device handoff","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.simulate","tool":"neyvia.mobile.simulate"},"key":"simulate","section":"actions"}
A neyvia.mobile.simulate(project?:str tier:json:"{\"type\":\"string\",\"enum\":[\"instant\",\"cloud\",\"device\"]}" platform?:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" results?:str) -> json:"{\"type\":\"object\"}" ! -- Instant browser frame, dormant cloud preparation/import or real-device handoff
C neyvia.mobile.simulate preview-present:neyvia.mobile.status(project:project) .preview.ready == true
C neyvia.mobile.simulate cloud-off:neyvia.mobile.status(project:project) .apple.cloudEnabled == false
C neyvia.mobile.simulate cloud-off:neyvia.mobile.status(project:project) .apple.cloudEnabled == false
-- @record {"chapter":"apple-targets","data":{"effect":"Return Apple sideload/open steps; never claim the device was installed","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.install","tool":"neyvia.mobile.install"},"key":"install","section":"actions"}
A neyvia.mobile.install(target:str project?:str avd?:str waitSeconds?:0..600) -> json:"{\"type\":\"object\"}" ! -- Return Apple sideload/open steps; never claim the device was installed
F verify-install "No authored observer check is bound to neyvia.mobile.install" -> ask operator blocks:neyvia.mobile.install
-- @record {"chapter":"apple-targets","data":{"effect":"Signing is an atomic build phase; Mac ad-hoc, IPA zsign or configured identity/profile","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.build","tool":"neyvia.mobile.build"},"key":"sign","section":"actions"}
A neyvia.mobile.build(platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" project?:str waitSeconds?:0..900 addShell?:bool) -> json:"{\"type\":\"object\"}" ! -- Signing is an atomic build phase; Mac ad-hoc, IPA zsign or configured identity/profile
F verify-sign "No authored observer check is bound to neyvia.mobile.build" -> ask operator blocks:neyvia.mobile.build
-- @record {"chapter":"apple-targets","data":{"effect":"Packaging is an atomic build phase; Mac ZIP retains Unix execute mode; IPA uses Payload","pre":"Existing app; installed direct LLVM; supported web export and bundle identity","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.build","tool":"neyvia.mobile.build"},"key":"package","section":"actions"}
A neyvia.mobile.build(platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" project?:str waitSeconds?:0..900 addShell?:bool) -> json:"{\"type\":\"object\"}" ! -- Packaging is an atomic build phase; Mac ZIP retains Unix execute mode; IPA uses Payload
F verify-package "No authored observer check is bound to neyvia.mobile.build" -> ask operator blocks:neyvia.mobile.build
-- @record {"chapter":"apple-targets","data":{"effect":"Capture actual native browser PNG pixels and source-bound runtime receipt","pre":"Existing owned Obscura Apple preview tab; runtime available. No desktop-wide screen capture.","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.browser.capture","tool":"neyvia.browser.capture"},"key":"screenshot","section":"actions"}
A neyvia.browser.capture(tabId:str fullPage?:bool) -> json:"{\"type\":\"object\"}" ! -- Capture actual native browser PNG pixels and source-bound runtime receipt
F verify-screenshot "No authored observer check is bound to neyvia.browser.capture" -> ask operator blocks:neyvia.browser.capture
-- @record {"chapter":"apple-targets","data":{"args":{"project":{"$input":"project"}},"expect":{"op":"eq","path":"apple.cloudEnabled","value":false},"tool":"neyvia.mobile.status"},"key":"cloud-off","section":"checks"}
C neyvia.mobile.status cloud-off:neyvia.mobile.status(project:project) .apple.cloudEnabled == false
-- @record {"chapter":"apple-targets","data":{"args":{"project":{"$input":"project"}},"expect":{"op":"eq","path":"preview.ready","value":true},"tool":"neyvia.mobile.status"},"key":"preview-present","section":"checks"}
C neyvia.mobile.status preview-present:neyvia.mobile.status(project:project) .preview.ready == true
-- @record {"chapter":"apple-targets","data":{"args":{"project":{"$input":"project"}},"expect":{"op":"eq","path":"apple.targets.watchos.build","value":false},"tool":"neyvia.mobile.status"},"key":"unsupported-declared","section":"checks"}
C neyvia.mobile.status unsupported-declared:neyvia.mobile.status(project:project) .apple.targets.watchos.build == false
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"ios","project":{"$input":"project"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.mobile.verify"},"key":"bundle-valid-ios","section":"checks"}
C neyvia.mobile.verify bundle-valid-ios:neyvia.mobile.verify(platform:"ios" project:project) .ok == true
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"ios","project":{"$input":"project"}},"expect":{"op":"eq","path":"nativeExecutionVerified","value":false},"tool":"neyvia.mobile.verify"},"key":"no-native-claim-ios","section":"checks"}
C neyvia.mobile.verify no-native-claim-ios:neyvia.mobile.verify(platform:"ios" project:project) .nativeExecutionVerified == false
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"ipados","project":{"$input":"project"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.mobile.verify"},"key":"bundle-valid-ipados","section":"checks"}
C neyvia.mobile.verify bundle-valid-ipados:neyvia.mobile.verify(platform:"ipados" project:project) .ok == true
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"ipados","project":{"$input":"project"}},"expect":{"op":"eq","path":"nativeExecutionVerified","value":false},"tool":"neyvia.mobile.verify"},"key":"no-native-claim-ipados","section":"checks"}
C neyvia.mobile.verify no-native-claim-ipados:neyvia.mobile.verify(platform:"ipados" project:project) .nativeExecutionVerified == false
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"macos","project":{"$input":"project"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.mobile.verify"},"key":"bundle-valid-macos","section":"checks"}
C neyvia.mobile.verify bundle-valid-macos:neyvia.mobile.verify(platform:"macos" project:project) .ok == true
-- @record {"chapter":"apple-targets","data":{"args":{"platform":"macos","project":{"$input":"project"}},"expect":{"op":"eq","path":"nativeExecutionVerified","value":false},"tool":"neyvia.mobile.verify"},"key":"no-native-claim-macos","section":"checks"}
C neyvia.mobile.verify no-native-claim-macos:neyvia.mobile.verify(platform:"macos" project:project) .nativeExecutionVerified == false
-- @record {"chapter":"apple-targets","data":{"goal":"Build a Windows artifact, verify its seals, select its emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"build","args":{"platform":"ios","project":{"$input":"project"},"waitSeconds":60},"save":"build"},{"action":"verify","args":{"platform":"ios","project":{"$input":"project"}},"check":"bundle-valid-ios","save":"outcome"},{"action":"simulate","args":{"platform":"ios","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"build-verify-preview-ios","section":"procedures"}
P build-verify-preview-ios(project:str):build=neyvia.mobile.build(platform:"ios" project:project waitSeconds:60); outcome=neyvia.mobile.verify(platform:"ios" project:project) C bundle-valid-ios; preview=neyvia.mobile.simulate(platform:"ios" project:project tier:"instant") C preview-present -- Build a Windows artifact, verify its seals, select its emulated frame
V P build-verify-preview-ios -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Fast repeated byte outcomes without rebuilding or model calls","inputs":{"$cl_type":"t12"},"steps":[{"action":"verify","args":{"platform":"ios","project":{"$input":"project"}},"check":"bundle-valid-ios","save":"outcome"},{"action":"verify","args":{"platform":"ios","project":{"$input":"project"}},"check":"no-native-claim-ios","save":"boundary"}]},"key":"verify-retained-artifact-ios","section":"procedures"}
P verify-retained-artifact-ios(project:str):outcome=neyvia.mobile.verify(platform:"ios" project:project) C bundle-valid-ios; boundary=neyvia.mobile.verify(platform:"ios" project:project) C no-native-claim-ios -- Fast repeated byte outcomes without rebuilding or model calls
V P verify-retained-artifact-ios -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Build a Windows artifact, verify its seals, select its emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"build","args":{"platform":"ipados","project":{"$input":"project"},"waitSeconds":60},"save":"build"},{"action":"verify","args":{"platform":"ipados","project":{"$input":"project"}},"check":"bundle-valid-ipados","save":"outcome"},{"action":"simulate","args":{"platform":"ipados","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"build-verify-preview-ipados","section":"procedures"}
P build-verify-preview-ipados(project:str):build=neyvia.mobile.build(platform:"ipados" project:project waitSeconds:60); outcome=neyvia.mobile.verify(platform:"ipados" project:project) C bundle-valid-ipados; preview=neyvia.mobile.simulate(platform:"ipados" project:project tier:"instant") C preview-present -- Build a Windows artifact, verify its seals, select its emulated frame
V P build-verify-preview-ipados -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Fast repeated byte outcomes without rebuilding or model calls","inputs":{"$cl_type":"t12"},"steps":[{"action":"verify","args":{"platform":"ipados","project":{"$input":"project"}},"check":"bundle-valid-ipados","save":"outcome"},{"action":"verify","args":{"platform":"ipados","project":{"$input":"project"}},"check":"no-native-claim-ipados","save":"boundary"}]},"key":"verify-retained-artifact-ipados","section":"procedures"}
P verify-retained-artifact-ipados(project:str):outcome=neyvia.mobile.verify(platform:"ipados" project:project) C bundle-valid-ipados; boundary=neyvia.mobile.verify(platform:"ipados" project:project) C no-native-claim-ipados -- Fast repeated byte outcomes without rebuilding or model calls
V P verify-retained-artifact-ipados -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Build a Windows artifact, verify its seals, select its emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"build","args":{"platform":"macos","project":{"$input":"project"},"waitSeconds":60},"save":"build"},{"action":"verify","args":{"platform":"macos","project":{"$input":"project"}},"check":"bundle-valid-macos","save":"outcome"},{"action":"simulate","args":{"platform":"macos","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"build-verify-preview-macos","section":"procedures"}
P build-verify-preview-macos(project:str):build=neyvia.mobile.build(platform:"macos" project:project waitSeconds:60); outcome=neyvia.mobile.verify(platform:"macos" project:project) C bundle-valid-macos; preview=neyvia.mobile.simulate(platform:"macos" project:project tier:"instant") C preview-present -- Build a Windows artifact, verify its seals, select its emulated frame
V P build-verify-preview-macos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Fast repeated byte outcomes without rebuilding or model calls","inputs":{"$cl_type":"t12"},"steps":[{"action":"verify","args":{"platform":"macos","project":{"$input":"project"}},"check":"bundle-valid-macos","save":"outcome"},{"action":"verify","args":{"platform":"macos","project":{"$input":"project"}},"check":"no-native-claim-macos","save":"boundary"}]},"key":"verify-retained-artifact-macos","section":"procedures"}
P verify-retained-artifact-macos(project:str):outcome=neyvia.mobile.verify(platform:"macos" project:project) C bundle-valid-macos; boundary=neyvia.mobile.verify(platform:"macos" project:project) C no-native-claim-macos -- Fast repeated byte outcomes without rebuilding or model calls
V P verify-retained-artifact-macos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Prepare own-account Simulator capsule without dispatching a run","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"ios","project":{"$input":"project"},"tier":"cloud"},"check":"cloud-off","save":"capsule"}]},"key":"prepare-cloud-off","section":"procedures"}
P prepare-cloud-off(project:str):capsule=neyvia.mobile.simulate(platform:"ios" project:project tier:"cloud") C cloud-off -- Prepare own-account Simulator capsule without dispatching a run
V P prepare-cloud-off -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"No unsupported Apple bundle is fabricated","inputs":{"$cl_type":"t12"},"steps":[{"action":"status","args":{"project":{"$input":"project"}},"check":"unsupported-declared","save":"support"}]},"key":"refuse-unsupported-watch","section":"procedures"}
P refuse-unsupported-watch(project:str):support=neyvia.mobile.status(project:project) C unsupported-declared -- No unsupported Apple bundle is fabricated
V P refuse-unsupported-watch -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain a project-bound emulated preview","inputs":{"$cl_type":"t13"},"steps":[{"action":"preview","args":{"dark":{"$input":"dark"},"device":{"$input":"device"},"keyboard":{"$input":"keyboard"},"orientation":{"$input":"orientation"},"project":{"$input":"project"},"textScale":{"$input":"textScale"}},"check":"preview-present","save":"preview"}]},"key":"preview-apple","section":"procedures"}
P preview-apple(project:str device?:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"],\"default\":\"iphone-16-pro\"}" orientation?:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"],\"default\":\"portrait\"}" dark?:json:"{\"type\":\"boolean\",\"default\":false}" textScale?:json:"{\"type\":\"number\",\"minimum\":0.8,\"maximum\":2,\"default\":1}" keyboard?:json:"{\"type\":\"boolean\",\"default\":false}"):preview=neyvia.mobile.preview(dark:dark device:device keyboard:keyboard orientation:orientation project:project textScale:textScale) C preview-present -- Retain a project-bound emulated preview
V P preview-apple -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"ios","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-ios","section":"procedures"}
P preview-frame-ios(project:str):preview=neyvia.mobile.simulate(platform:"ios" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-ios -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"ipados","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-ipados","section":"procedures"}
P preview-frame-ipados(project:str):preview=neyvia.mobile.simulate(platform:"ipados" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-ipados -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"macos","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-macos","section":"procedures"}
P preview-frame-macos(project:str):preview=neyvia.mobile.simulate(platform:"macos" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-macos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"watchos","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-watchos","section":"procedures"}
P preview-frame-watchos(project:str):preview=neyvia.mobile.simulate(platform:"watchos" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-watchos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"tvos","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-tvos","section":"procedures"}
P preview-frame-tvos(project:str):preview=neyvia.mobile.simulate(platform:"tvos" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-tvos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Retain exact Apple emulated frame","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"visionos","project":{"$input":"project"},"tier":"instant"},"check":"preview-present","save":"preview"}]},"key":"preview-frame-visionos","section":"procedures"}
P preview-frame-visionos(project:str):preview=neyvia.mobile.simulate(platform:"visionos" project:project tier:"instant") C preview-present -- Retain exact Apple emulated frame
V P preview-frame-visionos -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Prepare own-account Simulator capsule without dispatching a run","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"ios","project":{"$input":"project"},"tier":"cloud"},"check":"cloud-off","save":"capsule"}]},"key":"prepare-cloud-off-ios","section":"procedures"}
P prepare-cloud-off-ios(project:str):capsule=neyvia.mobile.simulate(platform:"ios" project:project tier:"cloud") C cloud-off -- Prepare own-account Simulator capsule without dispatching a run
V P prepare-cloud-off-ios -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Import hash-bound downloaded outcome without running cloud","inputs":{"$cl_type":"t14"},"steps":[{"action":"simulate","args":{"platform":"ios","project":{"$input":"project"},"results":{"$input":"results"},"tier":"cloud"},"check":"cloud-off","save":"result"}]},"key":"import-cloud-ios","section":"procedures"}
P import-cloud-ios(project:str results:str):result=neyvia.mobile.simulate(platform:"ios" project:project results:results tier:"cloud") C cloud-off -- Import hash-bound downloaded outcome without running cloud
V P import-cloud-ios -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Prepare own-account Simulator capsule without dispatching a run","inputs":{"$cl_type":"t12"},"steps":[{"action":"simulate","args":{"platform":"ipados","project":{"$input":"project"},"tier":"cloud"},"check":"cloud-off","save":"capsule"}]},"key":"prepare-cloud-off-ipados","section":"procedures"}
P prepare-cloud-off-ipados(project:str):capsule=neyvia.mobile.simulate(platform:"ipados" project:project tier:"cloud") C cloud-off -- Prepare own-account Simulator capsule without dispatching a run
V P prepare-cloud-off-ipados -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Import hash-bound downloaded outcome without running cloud","inputs":{"$cl_type":"t14"},"steps":[{"action":"simulate","args":{"platform":"ipados","project":{"$input":"project"},"results":{"$input":"results"},"tier":"cloud"},"check":"cloud-off","save":"result"}]},"key":"import-cloud-ipados","section":"procedures"}
P import-cloud-ipados(project:str results:str):result=neyvia.mobile.simulate(platform:"ipados" project:project results:results tier:"cloud") C cloud-off -- Import hash-bound downloaded outcome without running cloud
V P import-cloud-ipados -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"goal":"Capture owned browser preview pixels; never claim Apple OS simulation","inputs":{"$cl_type":"t15"},"steps":[{"action":"screenshot","args":{"tabId":{"$input":"tabId"}},"save":"capture"}]},"key":"capture-apple-preview","section":"procedures"}
P capture-apple-preview(tabId:str):capture=neyvia.browser.capture(tabId:tabId) -- Capture owned browser preview pixels; never claim Apple OS simulation
V P capture-apple-preview -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"apple-targets","data":{"failure":"watchOS/tvOS build","recovery":"No WKWebView. Separate native renderer required; concept frame only."},"key":"0","section":"pitfalls"}
X watchOS/tvOS build -> No WKWebView. Separate native renderer required; concept frame only.
-- @record {"chapter":"apple-targets","data":{"failure":"visionOS spatial build","recovery":"WKWebView exists but native runtime/linker/signing lane is absent. Flat web preview only."},"key":"1","section":"pitfalls"}
X visionOS spatial build -> WKWebView exists but native runtime/linker/signing lane is absent. Flat web preview only.
-- @record {"chapter":"apple-targets","data":{"failure":"Mac cannot open or Apple codesign refuses","recovery":"Preserve artifact and report Apple-host result; Windows hash integrity cannot prove Gatekeeper acceptance."},"key":"2","section":"pitfalls"}
X Mac cannot open or Apple codesign refuses -> Preserve artifact and report Apple-host result; Windows hash integrity cannot prove Gatekeeper acceptance.
-- @record {"chapter":"apple-targets","data":{"failure":"Cloud requested","recovery":"Prepare only; no dispatch tool. Paul installs the workflow in his account, checks minutes/billing and opts in."},"key":"3","section":"pitfalls"}
X Cloud requested -> Prepare only; no dispatch tool. Paul installs the workflow in his account, checks minutes/billing and opts in.
-- @record {"chapter":"apple-targets","data":"No macOS VM on non-Apple hardware; no Apple Simulator on Windows.","key":"0","section":"frontier"}
F No macOS VM on non-Apple hardware; no Apple Simulator on Windows.
-- @record {"chapter":"apple-targets","data":"Apple-hardware launch, Apple codesign trust, signing identities/notarization and cloud results need separately exercised host proof.","key":"1","section":"frontier"}
F Apple-hardware launch, Apple codesign trust, signing identities/notarization and cloud results need separately exercised host proof.
-- @record {"chapter":"apple-targets","data":"Frames emulate web behaviour, not OS APIs. Dynamic Type scales rem/root sizing; fixed-pixel fonts/native IME need device checks.","key":"2","section":"frontier"}
F Frames emulate web behaviour, not OS APIs. Dynamic Type scales rem/root sizing; fixed-pixel fonts/native IME need device checks.
-- @record {"chapter":"apple-targets","data":"Cloud screenshot import is a hash-checked downloaded snapshot, not live streaming or independently authenticated GitHub proof.","key":"3","section":"frontier"}
F Cloud screenshot import is a hash-checked downloaded snapshot, not live streaming or independently authenticated GitHub proof.
-- @record {"chapter":"apple-targets","data":"Mac: universal AppKit/WKWebView app + executable-mode ZIP. Supply native/AppIcon.icns for project artwork; fallback uses Neyvia icon.","key":"0","section":"guidance"}
M mobile-studio "Mac: universal AppKit/WKWebView app + executable-mode ZIP. Supply native/AppIcon.icns for project artwork; fallback uses Neyvia icon." src:"authored manual" state:verified
-- @record {"chapter":"apple-targets","data":"iPad: device family 2, full-screen false, all tablet orientations.","key":"1","section":"guidance"}
M mobile-studio "iPad: device family 2, full-screen false, all tablet orientations." src:"authored manual" state:verified
-- @record {"chapter":"apple-targets","data":"package/sign are atomic build phases; do not modify a sealed bundle.","key":"2","section":"guidance"}
M mobile-studio "package/sign are atomic build phases; do not modify a sealed bundle." src:"authored manual" state:verified
-- @record {"chapter":"apple-targets","data":"Screenshot proof uses an owned headless browser with final rendered Mobile Studio/Scroll Study state. Never fabricate captures.","key":"3","section":"guidance"}
M mobile-studio "Screenshot proof uses an owned headless browser with final rendered Mobile Studio/Scroll Study state. Never fabricate captures." src:"authored manual" state:verified
-- @record {"chapter":"apple-targets","data":"Apple reference: https://developer.apple.com/design/human-interface-guidelines/web-views ; cloud billing: https://docs.github.com/en/billing/concepts/product-billing/github-actions","key":"4","section":"guidance"}
M mobile-studio "Apple reference: https://developer.apple.com/design/human-interface-guidelines/web-views ; cloud billing: https://docs.github.com/en/billing/concepts/product-billing/github-actions" src:"authored manual" state:verified
-- @record {"chapter":"apple-targets","data":"Screenshot action uses browser.capture and its native pixel/hash observer on an existing owned Obscura tab. This task used C7 headless rendered journey because the attached MCP transport was not callable. Native screenshot connector was not exercised.","key":"5","section":"guidance"}
M mobile-studio "Screenshot action uses browser.capture and its native pixel/hash observer on an existing owned Obscura tab. This task used C7 headless rendered journey because the attached MCP transport was not callable. Native screenshot connector was not exercised." src:"authored manual" state:verified
L mobile-studio.fixcl3-local v1 -- Exact retained local admission and supervision
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained mobile.create","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.create","tool":"neyvia.mobile.create"},"key":"neyvia.mobile.create","section":"actions"}
A neyvia.mobile.create(path:str name:str bundleId?:str) -> json:"{\"type\":\"object\"}" ! -- Exact retained mobile.create
F verify-neyvia-mobile-create "No authored observer check is bound to neyvia.mobile.create" -> ask operator blocks:neyvia.mobile.create
-- @record {"chapter":"fixcl3-local","data":{"failure":"Fresh owner state differs from this action subject","recovery":"Reconcile the specific retained effect; never replay an uncertain launch."},"key":"0","section":"pitfalls"}
X Fresh owner state differs from this action subject -> Reconcile the specific retained effect; never replay an uncertain launch.
-- @record {"chapter":"fixcl3-local","data":"Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.","key":"0","section":"frontier"}
F Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.
-- @record {"chapter":"fixcl3-local","data":"After mobile.create requests approval, its durable artifact identity can remain uncertain. Reconcile the exact unchanged empty target and use a distinct recovery action ID; automatic replay is refused.","key":"1","section":"frontier"}
F After mobile.create requests approval, its durable artifact identity can remain uncertain. Reconcile the exact unchanged empty target and use a distinct recovery action ID; automatic replay is refused.
-- @record {"chapter":"fixcl3-local","data":"CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes.","key":"0","section":"guidance"}
M mobile-studio "CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes." src:"authored manual" state:verified
L mobile-studio.overview v1 -- Web-export frames and Windows iPhone/iPad/Mac builds; Android uses existing SDK
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t16"},"shape":{"$cl_type":"t17"},"tool":"neyvia.mobile.status"},"key":"current","section":"state"}
S mobile-studio.current:{device:str orientation:str dark:bool jobs:json:"{\"type\":\"array\"}" ..}=neyvia.mobile.status()
-- @record {"chapter":"overview","data":{"effect":"Read app shape/existence, frame, detected SDKs/devices, jobs and latest build receipts","pre":"Selected root readable; optional project resolves to safe path (missing project reported via exists)","returns":{"$cl_type":"t17"},"reversible":true,"schema":"neyvia.mobile.status","tool":"neyvia.mobile.status"},"key":"mobile.status","section":"actions"}
A neyvia.mobile.status(project?:str) -> {device:str orientation:str dark:bool jobs:json:"{\"type\":\"array\"}" ..} -- Read app shape/existence, frame, detected SDKs/devices, jobs and latest build receipts
C neyvia.mobile.status starter-preview:neyvia.mobile.status() .preview.ready == true
C neyvia.mobile.status orientation-saved:neyvia.mobile.status() .orientation == orientation
C neyvia.mobile.status device-probe-disabled:neyvia.mobile.status() .android.deviceProbeEnabled == false
-- @record {"chapter":"overview","data":{"effect":"Start build job; Android may prebuild/install Capacitor and Gradle dependencies; success writes APK/IPA receipt, not install","pre":"Existing safe app; installed toolchain; Android shell consent; Apple platform support explicit","returns":{"type":"object","properties":{"job":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}},"reversible":false,"schema":"neyvia.mobile.build","tool":"neyvia.mobile.build"},"key":"mobile.build","section":"actions"}
A neyvia.mobile.build(platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" project?:str waitSeconds?:0..900 addShell?:bool) -> json:"{\"type\":\"object\",\"properties\":{\"job\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"]}}}" ! -- Start build job; Android may prebuild/install Capacitor and Gradle dependencies; success writes APK/IPA receipt, not install
C neyvia.mobile.build build-job-recorded: matches(neyvia.mobile.status(project:project).jobs,{contains:{properties:{id:{const:result.job.id} kind:{const:"build"} platform:{const:platform} project:{const:project}} required:["id" "platform" "project" "kind"] type:"object"} type:"array"})
-- @record {"chapter":"overview","data":{"effect":"Create local app scaffold and select it; does not prove build or installed app","pre":"Name >=2 chars, valid dotted bundleId, absent/empty safe target, owner grants mobile-create for exact target","returns":{"$cl_type":"t11"},"reversible":false,"schema":"neyvia.mobile.create","tool":"neyvia.mobile.create"},"key":"mobile.create","section":"actions"}
A neyvia.mobile.create(path:str name:str bundleId?:str) -> json:"{\"type\":\"object\"}" ! -- Create local app scaffold and select it; does not prove build or installed app
C neyvia.mobile.create starter-selected:neyvia.mobile.status() .project.name == name
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"project.name","value":{"$input":"name"}},"tool":"neyvia.mobile.status"},"key":"starter-selected","section":"checks"}
C neyvia.mobile.status starter-selected:neyvia.mobile.status() .project.name == name
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"preview.ready","value":true},"tool":"neyvia.mobile.status"},"key":"starter-preview","section":"checks"}
C neyvia.mobile.status starter-preview:neyvia.mobile.status() .preview.ready == true
-- @record {"chapter":"overview","data":{"goal":"Create and select a real local starter app with a ready web preview","inputs":{"$cl_type":"t20"},"steps":[{"action":"mobile.create","args":{"path":{"$path":"path"},"name":{"$input":"name"},"bundleId":{"$input":"bundleId"}},"check":"starter-selected","save":"created"},{"action":"mobile.status","args":{},"check":"starter-preview","save":"selected"}]},"key":"create-starter-app","section":"procedures"}
P create-starter-app(path:str name:str bundleId?:json:"{\"type\":\"string\",\"default\":\"\"}" approvedRequest?:json:"{\"type\":\"string\",\"default\":\"\"}"):created=neyvia.mobile.create(bundleId:bundleId name:name path:path) C starter-selected; selected=neyvia.mobile.status() C starter-preview -- Create and select a real local starter app with a ready web preview
V P create-starter-app -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"effect":"Return iPhone sideload steps or start adb install/launch job; waitSeconds may return pending job","pre":"Safe project; iPhone returns guide; Android requires prior APK, adb and unambiguous online device or available emulator; external action authority","returns":{"$cl_type":"t11"},"reversible":false,"schema":"neyvia.mobile.install","tool":"neyvia.mobile.install"},"key":"mobile.install","section":"actions"}
A neyvia.mobile.install(target:str project?:str avd?:str waitSeconds?:0..600) -> json:"{\"type\":\"object\"}" ! -- Return iPhone sideload steps or start adb install/launch job; waitSeconds may return pending job
F verify-mobile-install "No authored observer check is bound to neyvia.mobile.install" -> ask operator blocks:neyvia.mobile.install
-- @record {"chapter":"overview","data":{"effect":"Persist phone frame and expose preview; startExpo starts existing Expo dev server without installing dependencies","pre":"Known device and portrait/landscape; supplied project is existing safe directory; startExpo requires Expo app","returns":{"$cl_type":"t11"},"reversible":false,"schema":"neyvia.mobile.preview","tool":"neyvia.mobile.preview"},"key":"mobile.preview","section":"actions"}
A neyvia.mobile.preview(device?:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}" project?:str orientation?:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}" dark?:bool startExpo?:bool textScale?:0.8..2 keyboard?:bool) -> json:"{\"type\":\"object\"}" ! -- Persist phone frame and expose preview; startExpo starts existing Expo dev server without installing dependencies
C neyvia.mobile.preview device-saved:neyvia.mobile.status() .device == device
-- @record {"chapter":"overview","data":{"effect":"Start compiler download job; status/receipt report outcome, no implicit system setup","pre":"part=ios-compiler and explicit owner grant mobile-setup:ios-compiler; 864 MB download needs separate authorization","returns":{"$cl_type":"t11"},"reversible":true,"schema":"neyvia.mobile.setup","tool":"neyvia.mobile.setup"},"key":"mobile.setup","section":"actions"}
A neyvia.mobile.setup(part:json:"{\"type\":\"string\",\"enum\":[\"ios-compiler\"]}" project?:str) -> json:"{\"type\":\"object\"}" ! -- Start compiler download job; status/receipt report outcome, no implicit system setup
F verify-mobile-setup "No authored observer check is bound to neyvia.mobile.setup" -> ask operator blocks:neyvia.mobile.setup
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"device","value":{"$input":"device"}},"tool":"neyvia.mobile.status"},"key":"device-saved","section":"checks"}
C neyvia.mobile.status device-saved:neyvia.mobile.status() .device == device
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"orientation","value":{"$input":"orientation"}},"tool":"neyvia.mobile.status"},"key":"orientation-saved","section":"checks"}
C neyvia.mobile.status orientation-saved:neyvia.mobile.status() .orientation == orientation
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"android.deviceProbeEnabled","value":false},"tool":"neyvia.mobile.status"},"key":"device-probe-disabled","section":"checks"}
C neyvia.mobile.status device-probe-disabled:neyvia.mobile.status() .android.deviceProbeEnabled == false
-- @record {"chapter":"overview","data":{"goal":"Read current phone settings, choose a device and rotation, then verify retained frame","inputs":{"$cl_type":"t18"},"steps":[{"action":"mobile.status","args":{},"save":"before"},{"judge":"phone-frame"},{"action":"mobile.preview","args":{"device":{"$input":"device"},"orientation":{"$input":"orientation"}},"check":"device-saved","save":"preview","when":{"judge":"phone-frame","option":"preview"}},{"action":"mobile.status","args":{},"check":"orientation-saved","save":"after","when":{"judge":"phone-frame","option":"preview"}}]},"key":"set-phone-frame","section":"procedures"}
P set-phone-frame(device:json:"{\"type\":\"string\",\"enum\":[\"iphone-16-pro\",\"iphone-16-pro-max\",\"iphone-16\",\"iphone-se\",\"pixel-9\",\"pixel-9-pro-xl\",\"ipad-pro-13\",\"mac-window\",\"watch-46\",\"apple-tv\",\"vision-window\"]}" orientation:json:"{\"type\":\"string\",\"enum\":[\"portrait\",\"landscape\"]}"):before=neyvia.mobile.status(); J phone-frame=preview; preview=neyvia.mobile.preview(device:device orientation:orientation) C device-saved; after=neyvia.mobile.status() C orientation-saved -- Read current phone settings, choose a device and rotation, then verify retained frame
V P set-phone-frame -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"args":{"project":{"$path":"project"}},"expect":{"op":"schema","path":"jobs","schema":{"contains":{"properties":{"id":{"const":{"$result":"job.job.id"}},"kind":{"const":"build"},"platform":{"const":{"$input":"platform"}},"project":{"const":{"$path":"project"}}},"required":["id","platform","project","kind"],"type":"object"},"type":"array"}},"tool":"neyvia.mobile.status"},"key":"build-job-recorded","section":"checks"}
C neyvia.mobile.status build-job-recorded:matches(neyvia.mobile.status(project:project) .jobs {contains:{properties:{id:{const:job.job.id} kind:{const:"build"} platform:{const:platform} project:{const:project}} required:["id" "platform" "project" "kind"] type:"object"} type:"array"})
-- @record {"chapter":"overview","data":{"goal":"Inspect selected app toolchains, review platform and start a real build job","inputs":{"$cl_type":"t19"},"steps":[{"action":"mobile.status","args":{"project":{"$path":"project"}},"save":"readiness"},{"judge":"build-target"},{"action":"mobile.build","args":{"platform":{"$input":"platform"},"project":{"$path":"project"},"addShell":{"$input":"addShell"}},"check":"build-job-recorded","save":"job","when":{"judge":"build-target","option":"build"}},{"action":"mobile.status","args":{"project":{"$path":"project"}},"save":"progress","when":{"judge":"build-target","option":"build"}}]},"key":"build-chosen-platform","section":"procedures"}
P build-chosen-platform(project:str platform:json:"{\"type\":\"string\",\"enum\":[\"ios\",\"android\",\"ipados\",\"macos\",\"watchos\",\"tvos\",\"visionos\"]}" addShell?:json:"{\"type\":\"boolean\",\"default\":false}"):readiness=neyvia.mobile.status(project:project); J build-target=build; job=neyvia.mobile.build(addShell:addShell platform:platform project:project) C build-job-recorded; progress=neyvia.mobile.status(project:project) -- Inspect selected app toolchains, review platform and start a real build job
V P build-chosen-platform -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Inspect installed tools in an explicitly isolated session with NEYVIA_MOBILE_PROBE_DEVICES=0; no adb daemon, emulator or device discovery","inputs":{"$cl_type":"t16"},"steps":[{"action":"mobile.status","args":{},"check":"device-probe-disabled","save":"installed"}]},"key":"inspect-without-devices","section":"procedures"}
P inspect-without-devices():installed=neyvia.mobile.status() C device-probe-disabled -- Inspect installed tools in an explicitly isolated session with NEYVIA_MOBILE_PROBE_DEVICES=0; no adb daemon, emulator or device discovery
V P inspect-without-devices -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Input device is one of mobile.preview enum; choose based on target screen/safe areas. Frame state does not prove touch, keyboard, build or install behavior.","options":["preview","leave"],"question":"Which tested phone frame and rotation matches the target audience?"},"key":"phone-frame","section":"judge"}
J phone-frame preview|leave:"Which tested phone frame and rotation matches the target audience?" -- Input device is one of mobile.preview enum; choose based on target screen/safe areas. Frame state does not prove touch, keyboard, build or install behavior.
V J phone-frame -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Check status missing[] and project kind first. Do not install SDKs automatically. Android shell generation/Gradle dependency downloads change project and may exceed current download authorization; stop until separately authorized.","options":["build","leave"],"question":"Build with the installed platform toolchain now?"},"key":"build-target","section":"judge"}
J build-target build|leave:"Build with the installed platform toolchain now?" -- Check status missing[] and project kind first. Do not install SDKs automatically. Android shell generation/Gradle dependency downloads change project and may exceed current download authorization; stop until separately authorized.
V J build-target -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Android tools missing / needsShell true","recovery":"Report exact missing SDK sizes; addShell creates project files and downloads dependencies only after authority"},"key":"0","section":"pitfalls"}
X Android tools missing / needsShell true -> Report exact missing SDK sizes; addShell creates project files and downloads dependencies only after authority
-- @record {"chapter":"overview","data":{"failure":"Gradle exits but APK absent","recovery":"Inspect job error and output path; do not invent artifact"},"key":"1","section":"pitfalls"}
X Gradle exits but APK absent -> Inspect job error and output path; do not invent artifact
-- @record {"chapter":"overview","data":{"failure":"USB unauthorized or multiple phones","recovery":"Unlock/approve debugging or supply exact serial from status; do not guess"},"key":"2","section":"pitfalls"}
X USB unauthorized or multiple phones -> Unlock/approve debugging or supply exact serial from status; do not guess
-- @record {"chapter":"overview","data":{"failure":"iPhone install returns status=manual","recovery":"Give IPA path and AltStore/SideStore steps; no adb-style automatic iPhone installation"},"key":"3","section":"pitfalls"}
X iPhone install returns status=manual -> Give IPA path and AltStore/SideStore steps; no adb-style automatic iPhone installation
-- @record {"chapter":"overview","data":{"failure":"Preview state saved but app blank","recovery":"Verify webRoot/index.html or Expo server separately and inspect actual preview"},"key":"4","section":"pitfalls"}
X Preview state saved but app blank -> Verify webRoot/index.html or Expo server separately and inspect actual preview
-- @record {"chapter":"overview","data":{"failure":"Person expects a native iPhone or Android editor or simulator","recovery":"Say plainly: Mobile Studio previews the web export in a phone frame and builds it; for native screens use Android's emulator (Android Studio) or a real iPhone via the build/sideload path"},"key":"5","section":"pitfalls"}
X Person expects a native iPhone or Android editor or simulator -> Say plainly: Mobile Studio previews the web export in a phone frame and builds it; for native screens use Android's emulator (Android Studio) or a real iPhone via the build/sideload path
-- @record {"chapter":"overview","data":"Native Swift/SwiftUI or Kotlin/Compose editing, Xcode or Android Studio layouts and an iOS Simulator are not part of Mobile Studio; the preview is a web view in a phone frame","key":"0","section":"frontier"}
F Native Swift/SwiftUI or Kotlin/Compose editing, Xcode or Android Studio layouts and an iOS Simulator are not part of Mobile Studio; the preview is a web view in a phone frame
-- @record {"chapter":"overview","data":"Store signing/submission, real-device gestures and accessibility need separate proof","key":"1","section":"frontier"}
F Store signing/submission, real-device gestures and accessibility need separate proof
-- @record {"chapter":"overview","data":"Compiler setup downloads 864 MB; current 200 MB scope does not authorize it","key":"2","section":"frontier"}
F Compiler setup downloads 864 MB; current 200 MB scope does not authorize it
-- @record {"chapter":"overview","data":"Completed job is build evidence; UI/device launch needs a separate journey","key":"3","section":"frontier"}
F Completed job is build evidence; UI/device launch needs a separate journey
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_mobile_studio.py (preview, build, install, call); tests/test_neyvia_mobile_studio.py.","key":"0","section":"guidance"}
M mobile-studio "Source: src/grant_agent/neyvia_mobile_studio.py (preview, build, install, call); tests/test_neyvia_mobile_studio.py." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Private headless verification may set NEYVIA_MOBILE_PROBE_DEVICES=0. Device discovery is explicitly disabled and reported as deviceProbeEnabled:false; installed SDK and Java discovery still run. Ordinary sessions retain existing device discovery.","key":"1","section":"guidance"}
M mobile-studio "Private headless verification may set NEYVIA_MOBILE_PROBE_DEVICES=0. Device discovery is explicitly disabled and reported as deviceProbeEnabled:false; installed SDK and Java discovery still run. Ordinary sessions retain existing device discovery." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"For owner-click creation, approvedRequest binds a distinct recovery to the native approval ID. Before supplying it, read the exact approval receipt, approve that request, and confirm the parent folder listing is unchanged. Never replay an uncertain write.","key":"2","section":"guidance"}
M mobile-studio "For owner-click creation, approvedRequest binds a distinct recovery to the native approval ID. Before supplying it, read the exact approval receipt, approve that request, and confirm the parent folder listing is unchanged. Never replay an uncertain write." src:"authored manual" state:verified
L mobile-studio.proofs-c-local-authoring v1 -- PROOFS-c local authoring and package contracts
-- @record {"chapter":"proofs-c-local-authoring","data":{"failure":"A package receipt is mistaken for native compilation or installation.","recovery":"Require separate compiler/signing and device receipts."},"key":"0","section":"pitfalls"}
X A package receipt is mistaken for native compilation or installation. -> Require separate compiler/signing and device receipts.
-- @record {"chapter":"proofs-c-local-authoring","data":"Native signing/device and remote builder require their hosts.","key":"0","section":"frontier"}
F Native signing/device and remote builder require their hosts.
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.project: Created Expo authoring files retain requested identity, entrypoint and supported dependency versions. Checked: ios_studio.create_ios_app -> proofs_c_mobile.check_project","key":"0","section":"guidance"}
M mobile-studio "proofs-c.mobile.project: Created Expo authoring files retain requested identity, entrypoint and supported dependency versions. Checked: ios_studio.create_ios_app -> proofs_c_mobile.check_project" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.scope: Creation rejects paths outside selected root before any effects. Checked: ios_studio._safe_child","key":"1","section":"guidance"}
M mobile-studio "proofs-c.mobile.scope: Creation rejects paths outside selected root before any effects. Checked: ios_studio._safe_child" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.bundle-id: Creation requires a valid reverse-domain bundle identifier before writing. Checked: ios_studio.create_ios_app","key":"2","section":"guidance"}
M mobile-studio "proofs-c.mobile.bundle-id: Creation requires a valid reverse-domain bundle identifier before writing. Checked: ios_studio.create_ios_app" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.capsule: Each capsule retains its source root and exact manifest, excluding generated paths, confidential suffixes and links. Checked: ios_studio.create_ios_build_capsule -> proofs_c_mobile.check_capsule","key":"3","section":"guidance"}
M mobile-studio "proofs-c.mobile.capsule: Each capsule retains its source root and exact manifest, excluding generated paths, confidential suffixes and links. Checked: ios_studio.create_ios_build_capsule -> proofs_c_mobile.check_capsule" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.builder-config: Builder metadata persists only the allowed fields and signing references, without passwords. Checked: ios_studio.save_ios_builder -> proofs_c_mobile.check_config","key":"4","section":"guidance"}
M mobile-studio "proofs-c.mobile.builder-config: Builder metadata persists only the allowed fields and signing references, without passwords. Checked: ios_studio.save_ios_builder -> proofs_c_mobile.check_config" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.compiler-config: Compiler preferences validate before writing and persist exactly, without signing passwords. Checked: windows_ios_compiler.save_windows_ios_config -> proofs_c_mobile.check_config","key":"5","section":"guidance"}
M mobile-studio "proofs-c.mobile.compiler-config: Compiler preferences validate before writing and persist exactly, without signing passwords. Checked: windows_ios_compiler.save_windows_ios_config -> proofs_c_mobile.check_config" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.download-digest: Downloaded bytes match the expected digest before atomic promotion; mismatch never promotes a destination. Checked: windows_ios_compiler._download_verified","key":"6","section":"guidance"}
M mobile-studio "proofs-c.mobile.download-digest: Downloaded bytes match the expected digest before atomic promotion; mismatch never promotes a destination. Checked: windows_ios_compiler._download_verified" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.metadata: Persisted plist exactly matches identity and iPhoneOS platform metadata. Checked: windows_ios_compiler._write_info_plist -> proofs_c_mobile.check_plist","key":"7","section":"guidance"}
M mobile-studio "proofs-c.mobile.metadata: Persisted plist exactly matches identity and iPhoneOS platform metadata. Checked: windows_ios_compiler._write_info_plist -> proofs_c_mobile.check_plist" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.package: IPA archive contains exactly the app files under Payload with unchanged bytes. Checked: windows_ios_compiler._zip_payload -> proofs_c_mobile.check_package","key":"8","section":"guidance"}
M mobile-studio "proofs-c.mobile.package: IPA archive contains exactly the app files under Payload with unchanged bytes. Checked: windows_ios_compiler._zip_payload -> proofs_c_mobile.check_package" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.web-assets: Assets stage inside the app www directory and root-relative links become local links. Checked: windows_ios_compiler._safe_copy_web_assets -> proofs_c_mobile.check_web_assets","key":"9","section":"guidance"}
M mobile-studio "proofs-c.mobile.web-assets: Assets stage inside the app www directory and root-relative links become local links. Checked: windows_ios_compiler._safe_copy_web_assets -> proofs_c_mobile.check_web_assets" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.error-text: Failure receipts strip terminal control codes and retain bounded useful text. Checked: windows_ios_compiler._clean_error","key":"10","section":"guidance"}
M mobile-studio "proofs-c.mobile.error-text: Failure receipts strip terminal control codes and retain bounded useful text. Checked: windows_ios_compiler._clean_error" src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-local-authoring","data":"proofs-c.mobile.backend-wiring: Mobile authoring, status and compiler configuration commands retain requested workspace, app identity, current recognition and preferences. Checked: web_backend.FluxioWebBackend.dispatch -> proofs_c_mobile.check_backend","key":"11","section":"guidance"}
M mobile-studio "proofs-c.mobile.backend-wiring: Mobile authoring, status and compiler configuration commands retain requested workspace, app identity, current recognition and preferences. Checked: web_backend.FluxioWebBackend.dispatch -> proofs_c_mobile.check_backend" src:"authored manual" state:verified
