CL 1
L modules v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Reusable repository modules, public APIs and optional mods"}},"clVersion":"1.1","id":"modules","kind":"environment","proofs":{"area":"path-policy-outcomes, python-sdk-journey","manifests":["config/proofs/path-policy-outcomes.json","config/proofs/python-sdk-journey.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.marketplace.get":"t1","neyvia.marketplace.install":"live_schema_12","neyvia.marketplace.list":"t3","neyvia.marketplace.read":"t1","neyvia.marketplace.remove":"t1","neyvia.marketplace.set":"t4","neyvia.marketplace.update":"live_schema_13","neyvia.modules.get":"t1","neyvia.modules.list":"t5","neyvia.modules.source":"t6","neyvia.modules.validate":"t3"},"tool_metadata":{"neyvia.marketplace.get":{"mutability_class":"read"},"neyvia.marketplace.install":{"mutability_class":"external_action"},"neyvia.marketplace.list":{"mutability_class":"read"},"neyvia.marketplace.read":{"mutability_class":"read"},"neyvia.marketplace.remove":{"mutability_class":"artifact_write"},"neyvia.marketplace.set":{"mutability_class":"artifact_write"},"neyvia.marketplace.update":{"mutability_class":"external_action"},"neyvia.modules.get":{"mutability_class":"read"},"neyvia.modules.list":{"mutability_class":"read"},"neyvia.modules.source":{"mutability_class":"read"},"neyvia.modules.validate":{"mutability_class":"read"}}}
T live_schema_12 json:"{\"type\":\"object\",\"properties\":{\"source\":{\"type\":\"string\"},\"ref\":{\"type\":\"string\"},\"sha256\":{\"type\":\"string\"}},\"required\":[\"source\"],\"allOf\":[{\"properties\":{\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_13 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"preview\":{\"type\":\"boolean\"},\"commit\":{\"type\":\"string\"},\"sha256\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t1 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"source\":{\"type\":\"string\"},\"ref\":{\"type\":\"string\"}},\"required\":[\"source\"],\"allOf\":[{\"properties\":{\"source\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"enabled\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"enabled\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{query?:str offset?:0.. limit?:1..100 ..}
T t6 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"}},\"required\":[\"id\",\"path\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t8 json:"{\"type\":\"object\"}"
T t9{id:str ..}
T t10{id:str enabled:bool}
T t11{source:str id:str}
L modules.overview v1 -- Reusable repository modules, public APIs and optional mods
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t7"},"shape":{"$cl_type":"t8"},"tool":"neyvia.modules.list"},"key":"catalog","section":"state"}
S modules.catalog:json:"{\"type\":\"object\"}"=neyvia.modules.list()
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"inputs":{"$cl_type":"t9"},"shape":{"$cl_type":"t8"},"tool":"neyvia.modules.get"},"key":"module","section":"state"}
S modules.module:json:"{\"type\":\"object\"}"=neyvia.modules.get(id:id)
-- @record {"chapter":"overview","data":{"effect":"Read and search Neyvia's generated module map, with saved enabled state.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.modules.list","tool":"neyvia.modules.list"},"key":"modules.list","section":"actions"}
A neyvia.modules.list(query?:str offset?:0.. limit?:1..100) -> json:"{\"type\":\"object\"}" -- Read and search Neyvia's generated module map, with saved enabled state.
F verify-modules-list "No authored observer check is bound to neyvia.modules.list" -> ask operator blocks:neyvia.modules.list
-- @record {"chapter":"overview","data":{"effect":"Read a module's source ownership, manuals, actions, dependencies and contracts.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.modules.get","tool":"neyvia.modules.get"},"key":"modules.get","section":"actions"}
A neyvia.modules.get(id:str) -> json:"{\"type\":\"object\"}" -- Read a module's source ownership, manuals, actions, dependencies and contracts.
F verify-modules-get "No authored observer check is bound to neyvia.modules.get" -> ask operator blocks:neyvia.modules.get
-- @record {"chapter":"overview","data":{"effect":"Read an exact owned module source file; never opens an unrelated workspace path.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.modules.source","tool":"neyvia.modules.source"},"key":"modules.source","section":"actions"}
A neyvia.modules.source(id:str path:str) -> json:"{\"type\":\"object\"}" -- Read an exact owned module source file; never opens an unrelated workspace path.
F verify-modules-source "No authored observer check is bound to neyvia.modules.source" -> ask operator blocks:neyvia.modules.source
-- @record {"chapter":"overview","data":{"effect":"Check every scoped file is owned, the map is current and manual actions exist.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.modules.validate","tool":"neyvia.modules.validate"},"key":"modules.validate","section":"actions"}
A neyvia.modules.validate() -> json:"{\"type\":\"object\"}" -- Check every scoped file is owned, the map is current and manual actions exist.
C neyvia.modules.validate map-current:neyvia.modules.validate() .ok == true
C neyvia.modules.validate private-sources-closed:neyvia.modules.validate() .publicSources == {privateExcluded:true privateReadRefused:true}
-- @record {"chapter":"overview","data":{"effect":"Read installed developer-source apps and mods with manuals, contracts and saved lifecycle state.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.marketplace.list","tool":"neyvia.marketplace.list"},"key":"marketplace.list","section":"actions"}
A neyvia.marketplace.list() -> json:"{\"type\":\"object\"}" -- Read installed developer-source apps and mods with manuals, contracts and saved lifecycle state.
F verify-marketplace-list "No authored observer check is bound to neyvia.marketplace.list" -> ask operator blocks:neyvia.marketplace.list
-- @record {"chapter":"overview","data":{"effect":"Read one installed source app or mod's current immutable version and lifecycle state.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.marketplace.get","tool":"neyvia.marketplace.get"},"key":"marketplace.get","section":"actions"}
A neyvia.marketplace.get(id:str) -> json:"{\"type\":\"object\"}" -- Read one installed source app or mod's current immutable version and lifecycle state.
F verify-marketplace-get "No authored observer check is bound to neyvia.marketplace.get" -> ask operator blocks:neyvia.marketplace.get
-- @record {"chapter":"overview","data":{"effect":"Install a trusted local folder or GitHub git URL into an immutable private snapshot; no dependency installs.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"type":"object"},"reversible":true,"schema":"neyvia.marketplace.install","tool":"neyvia.marketplace.install"},"key":"marketplace.install","section":"actions"}
A neyvia.marketplace.install(source:str ref?:str sha256?:str) -> json:"{\"type\":\"object\"}" ! -- Install a trusted local folder or GitHub git URL into an immutable private snapshot; no dependency installs.
C neyvia.marketplace.install installed-off: neyvia.marketplace.get(id:id).item.state=="disabled"
-- @record {"chapter":"overview","data":{"effect":"Enable or disable an installed source app or mod, protecting active dependencies.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.marketplace.set","tool":"neyvia.marketplace.set"},"key":"marketplace.set","section":"actions"}
A neyvia.marketplace.set(id:str enabled:bool) -> json:"{\"type\":\"object\"}" ! -- Enable or disable an installed source app or mod, protecting active dependencies.
C neyvia.marketplace.set enabled-state:neyvia.modules.get(id:id) .module.enabled == enabled
C neyvia.marketplace.set enable-source:neyvia.marketplace.get(id:id) .item.state == "active"
C neyvia.marketplace.set disable-source:neyvia.marketplace.get(id:id) .item.state == "disabled"
-- @record {"chapter":"overview","data":{"effect":"Snapshot the installed item's original folder or git source; preserve prior versions and enabled state.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"type":"object"},"reversible":true,"schema":"neyvia.marketplace.update","tool":"neyvia.marketplace.update"},"key":"marketplace.update","section":"actions"}
A neyvia.marketplace.update(id:str preview?:bool commit?:str sha256?:str) -> json:"{\"type\":\"object\"}" ! -- Snapshot the installed item's original folder or git source; preserve prior versions and enabled state.
F verify-marketplace-update "No authored observer check is bound to neyvia.marketplace.update" -> ask operator blocks:neyvia.marketplace.update
-- @record {"chapter":"overview","data":{"effect":"Read an installed item's executable manual and declared contracts without running its code.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.marketplace.read","tool":"neyvia.marketplace.read"},"key":"marketplace.read","section":"actions"}
A neyvia.marketplace.read(id:str) -> json:"{\"type\":\"object\"}" -- Read an installed item's executable manual and declared contracts without running its code.
F verify-marketplace-read "No authored observer check is bound to neyvia.marketplace.read" -> ask operator blocks:neyvia.marketplace.read
-- @record {"chapter":"overview","data":{"effect":"Remove a disabled source app or mod that nothing depends on; its snapshots move aside, recoverable.","pre":"Selected workspace; module is mapped and any optional dependencies are enabled","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.marketplace.remove","tool":"neyvia.marketplace.remove"},"key":"marketplace.remove","section":"actions"}
A neyvia.marketplace.remove(id:str) -> json:"{\"type\":\"object\"}" ! -- Remove a disabled source app or mod that nothing depends on; its snapshots move aside, recoverable.
F verify-marketplace-remove "No authored observer check is bound to neyvia.marketplace.remove" -> ask operator blocks:neyvia.marketplace.remove
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.modules.validate"},"key":"map-current","section":"checks"}
C neyvia.modules.validate map-current:neyvia.modules.validate() .ok == true
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"module.enabled","value":{"$input":"enabled"}},"tool":"neyvia.modules.get"},"key":"enabled-state","section":"checks"}
C neyvia.modules.get enabled-state:neyvia.modules.get(id:id) .module.enabled == enabled
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"item.state","value":"active"},"tool":"neyvia.marketplace.get"},"key":"enable-source","section":"checks"}
C neyvia.marketplace.get enable-source:neyvia.marketplace.get(id:id) .item.state == "active"
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"item.state","value":"disabled"},"tool":"neyvia.marketplace.get"},"key":"disable-source","section":"checks"}
C neyvia.marketplace.get disable-source:neyvia.marketplace.get(id:id) .item.state == "disabled"
-- @record {"chapter":"overview","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"item.state","value":"disabled"},"tool":"neyvia.marketplace.get"},"key":"installed-off","section":"checks"}
C neyvia.marketplace.get installed-off:neyvia.marketplace.get(id:id) .item.state == "disabled"
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"publicSources","value":{"privateExcluded":true,"privateReadRefused":true}},"tool":"neyvia.modules.validate"},"key":"private-sources-closed","section":"checks"}
C neyvia.modules.validate private-sources-closed:neyvia.modules.validate() .publicSources == {privateExcluded:true privateReadRefused:true}
-- @record {"chapter":"overview","data":{"goal":"Every scoped source file has an owner, every action exists and generated data is current","inputs":{"$cl_type":"t7"},"steps":[{"action":"modules.validate","args":{},"check":"map-current","save":"map"},{"action":"modules.validate","args":{},"check":"private-sources-closed","save":"public"}]},"key":"verify-map","section":"procedures"}
P verify-map():map=neyvia.modules.validate() C map-current; public=neyvia.modules.validate() C private-sources-closed -- Every scoped source file has an owner, every action exists and generated data is current
V P verify-map -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Change optional module availability and observe the persisted result","inputs":{"$cl_type":"t10"},"steps":[{"action":"marketplace.set","args":{"enabled":{"$input":"enabled"},"id":{"$input":"id"}},"check":"enabled-state","save":"changed"}]},"key":"set-optional","section":"procedures"}
P set-optional(id:str enabled:bool):changed=neyvia.marketplace.set(enabled:enabled id:id) C enabled-state -- Change optional module availability and observe the persisted result
V P set-optional -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Persist and observe source item state active","inputs":{"$cl_type":"t9"},"steps":[{"action":"marketplace.set","args":{"enabled":true,"id":{"$input":"id"}},"check":"enable-source","save":"changed"}]},"key":"enable-source","section":"procedures"}
P enable-source(id:str):changed=neyvia.marketplace.set(enabled:true id:id) C enable-source -- Persist and observe source item state active
V P enable-source -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Persist and observe source item state disabled","inputs":{"$cl_type":"t9"},"steps":[{"action":"marketplace.set","args":{"enabled":false,"id":{"$input":"id"}},"check":"disable-source","save":"changed"}]},"key":"disable-source","section":"procedures"}
P disable-source(id:str):changed=neyvia.marketplace.set(enabled:false id:id) C disable-source -- Persist and observe source item state disabled
V P disable-source -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"A new source app or mod installs turned off; the owner turns it on after reviewing it","inputs":{"$cl_type":"t11"},"steps":[{"action":"marketplace.install","args":{"source":{"$input":"source"}},"check":"installed-off","save":"installed"}]},"key":"install-off","section":"procedures"}
P install-off(source:str id:str):installed=neyvia.marketplace.install(source:source) C installed-off -- A new source app or mod installs turned off; the owner turns it on after reviewing it
V P install-off -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"Module map drifted or manual names a missing action","recovery":"Fix ownership/action registration; compile CL, regenerate the module map and rerun modules.verify-map()."},"key":"0","section":"pitfalls"}
X Module map drifted or manual names a missing action -> Fix ownership/action registration; compile CL, regenerate the module map and rerun modules.verify-map().
-- @record {"chapter":"overview","data":{"failure":"Optional module is disabled or required by an enabled dependant","recovery":"Enable required dependencies first; disable dependants before their dependency. Core switches are refused."},"key":"1","section":"pitfalls"}
X Optional module is disabled or required by an enabled dependant -> Enable required dependencies first; disable dependants before their dependency. Core switches are refused.
-- @record {"chapter":"overview","data":"Trusted repository-local mods only; no downloading or executing untrusted packages. Changing a mod action schema requires restarting the owned backend to rebuild its tool catalog.","key":"0","section":"frontier"}
F Trusted repository-local mods only; no downloading or executing untrusted packages. Changing a mod action schema requires restarting the owned backend to rebuild its tool catalog.
-- @record {"chapter":"overview","data":"Source inspection is read-only; edit the named file in your editor. External connector runtime readiness is described by game-dev.cl, not inferred from registry presence.","key":"1","section":"frontier"}
F Source inspection is read-only; edit the named file in your editor. External connector runtime readiness is described by game-dev.cl, not inferred from registry presence.
-- @record {"chapter":"overview","data":"MODULES.md indexes source-derived modules. modules/<id>/README.md lists each purpose, public API, files, CL manual, contracts and dependencies.","key":"0","section":"guidance"}
M modules "MODULES.md indexes source-derived modules. modules/<id>/README.md lists each purpose, public API, files, CL manual, contracts and dependencies." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Core modules stay enabled. Source apps and mods use one workspace-local marketplace lifecycle; every mod action and hosted app SDK call uses its saved gate.","key":"1","section":"guidance"}
M modules "Core modules stay enabled. Source apps and mods use one workspace-local marketplace lifecycle; every mod action and hosted app SDK call uses its saved gate." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Run modules.verify-map() after source changes. Rebuild config/neyvia.modules.json with system Python scripts/generate_module_map.py; review before commit.","key":"2","section":"guidance"}
M modules "Run modules.verify-map() after source changes. Rebuild config/neyvia.modules.json with system Python scripts/generate_module_map.py; review before commit." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"The registry maps existing implementation units; a generated purpose or import dependency is a static description, not a claim of independently replaceable ABI.","key":"3","section":"guidance"}
M modules "The registry maps existing implementation units; a generated purpose or import dependency is a static description, not a claim of independently replaceable ABI." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Read neyvia chapter modding-neyvia and docs/BUILDING_APPS_AND_MODS.md. Reuse neyvia-sdk for sign-in/providers, memory, LAYA verification, CL and app hosting rather than copying architecture.","key":"4","section":"guidance"}
M modules "Read neyvia chapter modding-neyvia and docs/BUILDING_APPS_AND_MODS.md. Reuse neyvia-sdk for sign-in/providers, memory, LAYA verification, CL and app hosting rather than copying architecture." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Marketplace > Apps & mods is the store over these actions: cards with state, a details view (plain actions, what it asks for, promises, versions, source, manual), an enable switch, Update, Remove with an in-place confirm, and Add from source. Its rendered proof is the install, enable, open, disable and remove journey that scripts/mod_render.py drives through Obscura on the owned backend.","key":"5","section":"guidance"}
M modules "Marketplace > Apps & mods is the store over these actions: cards with state, a details view (plain actions, what it asks for, promises, versions, source, manual), an enable switch, Update, Remove with an in-place confirm, and Add from source. Its rendered proof is the install, enable, open, disable and remove journey that scripts/mod_render.py drives through Obscura on the owned backend." src:"authored manual" state:verified
-- @proof {"id":"p22.path-policy-outcomes","phase":"post","claim":"A real Git diff leaves deleted paths exempt, requires file-level evidence for surviving files with removed lines and binary changes, preserves changed-line locations for Unicode and spaced paths across bounded large pathspec batches, and classifies generated output, third-party trees and CI workflow configuration by policy.","checkedAt":["grant_agent.contract_diff.changed_lines","grant_agent.contract_diff._line_inventories","grant_agent.contract_coverage.classify","grant_agent.contract_coverage.model","grant_agent.contract_measurements.admission","grant_agent.proofs_path_policy_outcomes.path_policy_classification"],"impact":["Path policy and measured changed-line admission"]}
-- @proof {"id":"p22.python-sdk-http-boundary","phase":"post","claim":"The Python SDK maps an HTTP 400 service refusal to NeyviaError with the original status, code, message, and request command.","checkedAt":["src/neyvia_sdk/client.py","grant_agent.proofs_python_sdk_journey.self_check"],"impact":["Python SDK HTTP 400 refusal mapping"]}
