CL 1
L native-applications v1 -- Authored executable manual
-- @manual {"chapters":{"office":{"title":"Owned native document, version and render workflow"}},"clVersion":"1.1","id":"native-applications","kind":"environment","proofs":{"area":"applications-journey"},"schema":"neyvia.manual.v1","schemas":{"close":"t1","edit":"t2","observe":"t3","open":"t4","persist":"t5"},"tool_metadata":{"neyvia.nativeapp.edit":{"mutability_class":"workspace_write"},"neyvia.nativeapp.persist":{"mutability_class":"workspace_write"}}}
T t1{sessionId:str}
T t2 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"required\":[\"sessionId\",\"value\"],\"additionalProperties\":false,\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}},\"value\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{sessionId:str expected:str persisted:bool}
T t4{app:"Microsoft Word"|"Microsoft Excel"|"Microsoft PowerPoint"|"Command Prompt"|"Windows PowerShell"|"Xournal++"|"Git"|"Mozilla Firefox"|"Zen Browser"}
T t5 json:"{\"type\":\"object\",\"properties\":{\"sessionId\":{\"type\":\"string\"}},\"required\":[\"sessionId\"],\"additionalProperties\":false,\"allOf\":[{\"properties\":{\"sessionId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\"}"
T t7{sessionId:str value1:str value2:str value3:str value4:str value5:str}
L native-applications.office v1 -- Owned native document, version and render workflow
-- @record {"chapter":"office","data":{"effect":"Revise the owned native draft, Git note or browser card input","pre":"Owned hidden document and successful guard","returns":{"$cl_type":"t6"},"reversible":true,"schema":"edit","tool":"neyvia.nativeapp.edit"},"key":"revision1","section":"actions"}
A neyvia.nativeapp.edit(sessionId:str value:str) -> json:"{\"type\":\"object\"}" ! -- Revise the owned native draft, Git note or browser card input
C neyvia.nativeapp.edit revision1:neyvia.nativeapp.observe(expected:value1 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"effect":"Revise the owned native draft, Git note or browser card input","pre":"Owned hidden document and successful guard","returns":{"$cl_type":"t6"},"reversible":true,"schema":"edit","tool":"neyvia.nativeapp.edit"},"key":"revision2","section":"actions"}
A neyvia.nativeapp.edit(sessionId:str value:str) -> json:"{\"type\":\"object\"}" ! -- Revise the owned native draft, Git note or browser card input
C neyvia.nativeapp.edit revision2:neyvia.nativeapp.observe(expected:value2 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"effect":"Revise the owned native draft, Git note or browser card input","pre":"Owned hidden document and successful guard","returns":{"$cl_type":"t6"},"reversible":true,"schema":"edit","tool":"neyvia.nativeapp.edit"},"key":"revision3","section":"actions"}
A neyvia.nativeapp.edit(sessionId:str value:str) -> json:"{\"type\":\"object\"}" ! -- Revise the owned native draft, Git note or browser card input
C neyvia.nativeapp.edit revision3:neyvia.nativeapp.observe(expected:value3 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"effect":"Revise the owned native draft, Git note or browser card input","pre":"Owned hidden document and successful guard","returns":{"$cl_type":"t6"},"reversible":true,"schema":"edit","tool":"neyvia.nativeapp.edit"},"key":"revision4","section":"actions"}
A neyvia.nativeapp.edit(sessionId:str value:str) -> json:"{\"type\":\"object\"}" ! -- Revise the owned native draft, Git note or browser card input
C neyvia.nativeapp.edit revision4:neyvia.nativeapp.observe(expected:value4 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"effect":"Revise the owned native draft, Git note or browser card input","pre":"Owned hidden document and successful guard","returns":{"$cl_type":"t6"},"reversible":true,"schema":"edit","tool":"neyvia.nativeapp.edit"},"key":"revision5","section":"actions"}
A neyvia.nativeapp.edit(sessionId:str value:str) -> json:"{\"type\":\"object\"}" ! -- Revise the owned native draft, Git note or browser card input
C neyvia.nativeapp.edit revision5:neyvia.nativeapp.observe(expected:value5 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"effect":"Save and reopen a document, commit a local note, or render a card","pre":"Token-owned draft","returns":{"$cl_type":"t6"},"reversible":true,"schema":"persist","tool":"neyvia.nativeapp.persist"},"key":"persist","section":"actions"}
A neyvia.nativeapp.persist(sessionId:str) -> json:"{\"type\":\"object\"}" ! -- Save and reopen a document, commit a local note, or render a card
C neyvia.nativeapp.persist persist:neyvia.nativeapp.observe(expected:value5 persisted:true sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value1"},"persisted":false,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"revision1","section":"checks"}
C neyvia.nativeapp.observe revision1:neyvia.nativeapp.observe(expected:value1 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value2"},"persisted":false,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"revision2","section":"checks"}
C neyvia.nativeapp.observe revision2:neyvia.nativeapp.observe(expected:value2 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value3"},"persisted":false,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"revision3","section":"checks"}
C neyvia.nativeapp.observe revision3:neyvia.nativeapp.observe(expected:value3 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value4"},"persisted":false,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"revision4","section":"checks"}
C neyvia.nativeapp.observe revision4:neyvia.nativeapp.observe(expected:value4 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value5"},"persisted":false,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"revision5","section":"checks"}
C neyvia.nativeapp.observe revision5:neyvia.nativeapp.observe(expected:value5 persisted:false sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"args":{"expected":{"$input":"value5"},"persisted":true,"sessionId":{"$input":"sessionId"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.nativeapp.observe"},"key":"persist","section":"checks"}
C neyvia.nativeapp.observe persist:neyvia.nativeapp.observe(expected:value5 persisted:true sessionId:sessionId) .ok == true
-- @record {"chapter":"office","data":{"goal":"Revise an owned memo, budget, slide deck, versioned note or browser card; persist and independently verify the artifact","inputs":{"$cl_type":"t7"},"steps":[{"action":"revision1","args":{"sessionId":{"$input":"sessionId"},"value":{"$input":"value1"}},"check":"revision1","save":"revision1"},{"action":"revision2","args":{"sessionId":{"$input":"sessionId"},"value":{"$input":"value2"}},"check":"revision2","save":"revision2"},{"action":"revision3","args":{"sessionId":{"$input":"sessionId"},"value":{"$input":"value3"}},"check":"revision3","save":"revision3"},{"action":"revision4","args":{"sessionId":{"$input":"sessionId"},"value":{"$input":"value4"}},"check":"revision4","save":"revision4"},{"action":"revision5","args":{"sessionId":{"$input":"sessionId"},"value":{"$input":"value5"}},"check":"revision5","save":"revision5"},{"action":"persist","args":{"sessionId":{"$input":"sessionId"}},"check":"persist","save":"persist"}]},"key":"revise-save-reopen","section":"procedures"}
P revise-save-reopen(sessionId:str value1:str value2:str value3:str value4:str value5:str):revision1=neyvia.nativeapp.edit(sessionId:sessionId value:value1) C revision1; revision2=neyvia.nativeapp.edit(sessionId:sessionId value:value2) C revision2; revision3=neyvia.nativeapp.edit(sessionId:sessionId value:value3) C revision3; revision4=neyvia.nativeapp.edit(sessionId:sessionId value:value4) C revision4; revision5=neyvia.nativeapp.edit(sessionId:sessionId value:value5) C revision5; persist=neyvia.nativeapp.persist(sessionId:sessionId) C persist -- Revise an owned memo, budget, slide deck, versioned note or browser card; persist and independently verify the artifact
V P revise-save-reopen -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"office","data":{"failure":"New-process ownership or guard fails","recovery":"Refuse the session; never use an existing instance"},"key":"0","section":"pitfalls"}
X New-process ownership or guard fails -> Refuse the session; never use an existing instance
-- @record {"chapter":"office","data":"Firefox-family screenshot checks validate the rendered color and visible heading ink, not OCR text","key":"0","section":"frontier"}
F Firefox-family screenshot checks validate the rendered color and visible heading ink, not OCR text
-- @record {"chapter":"office","data":"Pixel preview and UIA interaction are separate from these application-native tools","key":"1","section":"frontier"}
F Pixel preview and UIA interaction are separate from these application-native tools
-- @record {"chapter":"office","data":"Only host-owned token files and hidden COM instances; compilation never removes native verifiers or guard checks","key":"0","section":"guidance"}
M native-applications "Only host-owned token files and hidden COM instances; compilation never removes native verifiers or guard checks" src:"authored manual" state:verified
-- @proof {"checkedAt":["cua_native_procedures.HostedNativeApplications.request","cua_native_procedures.HostedNativeApplications.__getattr__","cua_native_procedures.NativeApplications.open","cua_native_procedures.NativeApplications.edit","cua_native_procedures.NativeApplications.persist","cua_native_procedures.NativeApplications.observe","cua_native_procedures.NativeApplications.close","cua_native_procedures.NativeApplications.native_process","proofs_applications_journey.self_check"],"claim":"A disposable Unicode Git note is edited, read before save, committed through the owned Git CLI, and independently observed from HEAD; multiline input preserves the saved bytes and a later edit makes the prior saved view stale.","id":"p22.applications.git-note-journey","impact":["Native applications","Owned Git note editing and save/reopen"],"phase":"post"}
