CL 1
L nearby-send-runtime v1 -- Authored executable manual
-- @manual {"chapters":{"proofs-d-nearby":{"title":"Nearby Send: checked plan, streaming cancellation, durable chunk resume and verified wire acknowledgements"}},"clVersion":"1.1","id":"nearby-send-runtime","kind":"environment","proofs":{"area":"d-nearby","manifests":["config/proofs/d-nearby.json"],"startup":{"procedures":["bounded-preview-before-network","legacy-preview-migration","mid-chunk-child-sdk-cancel","reject-invalid-resume-and-ack","killed-sender-ack-recovery-and-retry","legacy-sdk-cancel","upload-failure-cancel","rejected-remote-cancel"],"runner":"grant_agent.proofs_d_nearby.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.efficiency.extract":"t1","terminal.exec":"t2","workspace.read":"t3"},"tool_metadata":{"terminal.exec":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["nearby_send.NearbySendService.build_plan -> proofs_d_nearby.check_plan","nearby_send.NearbySendService.send","nearby_send.NearbySendService._verify_planned_file","proofs_d_nearby.self_check"],"claim":"Hash-bound previews cover every source byte with ordered content-addressed chunks, exact file/byte/part counts, and enforced part bounds before any network action. Sending verifies the preview hash and source bytes again.","id":"d.nearby.hash-bound-plan","impact":["source preview","network admission","transfer budget"],"phase":"pre"}
-- @proof {"checkedAt":["nearby_send.NearbySendService._verify_planned_file -> proofs_d_nearby.check_verified_file","proofs_d_nearby.self_check"],"claim":"A pre-upgrade preview without chunk metadata is accepted only after its preview hash and actual unchanged source hash/size/mtime verify; it is enriched with the actual chunk manifest and marked migrated on wire and receipt.","id":"d.nearby.legacy-migration","impact":["old persisted preview","prepare-upload manifest","receipt migration count"],"phase":"post"}
-- @proof {"checkedAt":["nearby_send.NearbySendService._parse_upload_authorization -> proofs_d_nearby.check_resume_authorization","proofs_d_nearby.self_check"],"claim":"Resume begins only at a real chunk boundary with an exact contiguous prefix of part/offset/size/SHA256 receipts marked integrityVerified=true; invalid offsets or receipts fail without a whole-file remote integrity claim.","id":"d.nearby.resume-integrity","impact":["receiver resume authorization","acknowledged prefix","resumed upload budget"],"phase":"pre"}
-- @proof {"checkedAt":["nearby_send.NearbySendService._validate_chunk_acknowledgement -> proofs_d_nearby.check_chunk_receipt","nearby_send.NearbySendService.send -> proofs_d_nearby.check_transfer_result","proofs_d_nearby.self_check"],"claim":"An upload ACK binds exact part, offset, size and content hash plus positive integrity evidence; only a complete verified prefix can justify remoteHashVerified=true. Invalid hash/nextOffset replies never become acknowledged parts.","id":"d.nearby.chunk-ack-integrity","impact":["wire ACK","chunk upload state","remote hash evidence"],"phase":"post"}
-- @proof {"checkedAt":["nearby_send.NearbySendService._upload_chunked_file -> proofs_d_nearby.check_ack_progress","proofs_d_nearby.self_check"],"claim":"Each accepted chunk prefix and exact byte offset are atomically persisted before the next chunk. A killed sender recovers as interrupted with its acknowledged prefix and a retry sends only receiver-unacknowledged chunks.","id":"d.nearby.durable-ack-prefix","impact":["durable active transfer","crash recovery","receiver ACK store"],"phase":"post"}
-- @proof {"checkedAt":["nearby_send.NearbySendService.request_cancel_active_transfer -> proofs_d_nearby.check_cancel_request","nearby_send.NearbySendService._cancel -> proofs_d_nearby.check_cancel_transport","nearby_send.NearbySendService._upload_file/_upload_chunked_file -> nearby_send.NearbySendService._raise_if_cancelled","nearby_send.NearbySendService.send -> proofs_d_nearby.check_transfer_result","proofs_d_nearby.self_check"],"claim":"A cancellation request reports accepted but cancelled=false/finalState=pending until the sender terminates. Shared durable requests stop streaming at the next sender poll. Remote acknowledgment is true only for real HTTP200/204; rejected cancellation stays false with its status/error.","id":"d.nearby.cancel-truth","impact":["cross-process cancellation","wire stream lifetime","remote cancellation evidence"],"phase":"invariant"}
-- @proof {"checkedAt":["nearby_send.NearbySendService.send -> proofs_d_nearby.check_transfer_result","proofs_d_nearby.self_check"],"claim":"Every completed/failed/cancelled sender result refers to its durable owned receipt; truth flags, byte/part summaries and source identities match real acknowledgment evidence. Failures carry stable causes; local transfer never claims physical-device or multi-recipient proof or retains tokens.","id":"d.nearby.terminal-receipt","impact":["public transfer result","durable receipt","local proof boundary"],"phase":"post"}
T t1{path:str field:str strategy?:json:"{\"type\":\"string\",\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"]}" useScript?:bool ..}
T t2{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4{ok:true exitCode:0 ..}
T t5 json:"{\"type\":\"object\"}"
T t6{command:str#1.. expectedMarker:str}
L nearby-send-runtime.proofs-d-nearby v1 -- Nearby Send: checked plan, streaming cancellation, durable chunk resume and verified wire acknowledgements
-- @record {"chapter":"proofs-d-nearby","data":{"effect":"Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action.","pre":"Owned disposable cwd, explicit owner approval and the pinned C8e journey adapter. Never use the input desktop or an external provider.","returns":{"$cl_type":"t4"},"reversible":true,"schema":"terminal.exec","tool":"terminal.exec"},"key":"exercise","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> {ok:true exitCode:0 ..} ! -- Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action.
F verify-exercise "No authored observer check is bound to terminal.exec" -> ask operator blocks:terminal.exec
-- @record {"chapter":"proofs-d-nearby","data":{"effect":"Read durable effect bytes afresh through the workspace boundary.","pre":"Read the actual artifact produced by this procedure.","returns":{"$cl_type":"t5"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"read-effect","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> json:"{\"type\":\"object\"}" -- Read durable effect bytes afresh through the workspace boundary.
C workspace.read actual-preview-file:neyvia.efficiency.extract(field:"/summary/fileCount" path:"c8e-effects/nearby-send-runtime/preview.json" useScript:true) .answer.valueJson == "1"
C workspace.read send-needs-approval:neyvia.efficiency.extract(field:"/approvalRefusal/status" path:"c8e-effects/nearby-send-runtime/effect.json" useScript:true) .answer.valueJson == "\"approval_required\""
C workspace.read changed-source-refused:neyvia.efficiency.extract(field:"/sourceChangeRefusal" path:"c8e-effects/nearby-send-runtime/effect.json" useScript:true) .answer.valueJson has "Source changed after transfer preview"
-- @record {"chapter":"proofs-d-nearby","data":{"args":{"field":"/summary/fileCount","path":"c8e-effects/nearby-send-runtime/preview.json","useScript":true},"expect":{"op":"eq","path":"answer.valueJson","value":"1"},"tool":"neyvia.efficiency.extract"},"key":"actual-preview-file","section":"checks"}
C neyvia.efficiency.extract actual-preview-file:neyvia.efficiency.extract(field:"/summary/fileCount" path:"c8e-effects/nearby-send-runtime/preview.json" useScript:true) .answer.valueJson == "1"
-- @record {"chapter":"proofs-d-nearby","data":{"args":{"field":"/approvalRefusal/status","path":"c8e-effects/nearby-send-runtime/effect.json","useScript":true},"expect":{"op":"eq","path":"answer.valueJson","value":"\"approval_required\""},"tool":"neyvia.efficiency.extract"},"key":"send-needs-approval","section":"checks"}
C neyvia.efficiency.extract send-needs-approval:neyvia.efficiency.extract(field:"/approvalRefusal/status" path:"c8e-effects/nearby-send-runtime/effect.json" useScript:true) .answer.valueJson == "\"approval_required\""
-- @record {"chapter":"proofs-d-nearby","data":{"args":{"field":"/sourceChangeRefusal","path":"c8e-effects/nearby-send-runtime/effect.json","useScript":true},"expect":{"op":"contains","path":"answer.valueJson","value":"Source changed after transfer preview"},"tool":"neyvia.efficiency.extract"},"key":"changed-source-refused","section":"checks"}
C neyvia.efficiency.extract changed-source-refused:neyvia.efficiency.extract(field:"/sourceChangeRefusal" path:"c8e-effects/nearby-send-runtime/effect.json" useScript:true) .answer.valueJson has "Source changed after transfer preview"
-- @record {"chapter":"proofs-d-nearby","data":{"goal":"Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action.","inputs":{"$cl_type":"t6"},"steps":[{"action":"exercise","args":{"command":{"$input":"command"},"maxOutputChars":12000,"shell":"python","timeoutMs":30000},"save":"executed"},{"action":"read-effect","args":{"path":"c8e-effects/nearby-send-runtime/effect.json"},"check":"actual-preview-file","save":"fresh0"},{"action":"read-effect","args":{"path":"c8e-effects/nearby-send-runtime/effect.json"},"check":"send-needs-approval","save":"fresh1"},{"action":"read-effect","args":{"path":"c8e-effects/nearby-send-runtime/effect.json"},"check":"changed-source-refused","save":"fresh2"}]},"key":"preview-and-refuse-changed-source","section":"procedures"}
P preview-and-refuse-changed-source(command:str#1.. expectedMarker:str):executed=terminal.exec(command:command maxOutputChars:12000 shell:"python" timeoutMs:30000); fresh0=workspace.read(path:"c8e-effects/nearby-send-runtime/effect.json") C actual-preview-file; fresh1=workspace.read(path:"c8e-effects/nearby-send-runtime/effect.json") C send-needs-approval; fresh2=workspace.read(path:"c8e-effects/nearby-send-runtime/effect.json") C changed-source-refused -- Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action.
V P preview-and-refuse-changed-source -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-d-nearby","data":{"failure":"Resume offset or ACK hash disagrees with the preview","recovery":"Refuse the wire claim, persist failed receipt and cancel the peer session; never invent a verified prefix"},"key":"0","section":"pitfalls"}
X Resume offset or ACK hash disagrees with the preview -> Refuse the wire claim, persist failed receipt and cancel the peer session; never invent a verified prefix
-- @record {"chapter":"proofs-d-nearby","data":{"failure":"A sender process dies during a chunk","recovery":"Read get_active_transfer to recover interrupted state; retry the same verified plan and negotiate the receiver-held ACK prefix"},"key":"1","section":"pitfalls"}
X A sender process dies during a chunk -> Read get_active_transfer to recover interrupted state; retry the same verified plan and negotiate the receiver-held ACK prefix
-- @record {"chapter":"proofs-d-nearby","data":{"failure":"Cancel returns accepted while upload is running","recovery":"Read the final sender receipt; request acceptance is pending and does not prove remote rollback"},"key":"2","section":"pitfalls"}
X Cancel returns accepted while upload is running -> Read the final sender receipt; request acceptance is pending and does not prove remote rollback
-- @record {"chapter":"proofs-d-nearby","data":"This grounded runtime manual describes existing grant_agent.sdk/NearbySendService entry points; the host verifier executes its scratch startup procedures directly","key":"0","section":"frontier"}
F This grounded runtime manual describes existing grant_agent.sdk/NearbySendService entry points; the host verifier executes its scratch startup procedures directly
-- @record {"chapter":"proofs-d-nearby","data":"The real byte-stream laboratory is loopback only on explicit48495; no physical device, TLS certificate pinning, multicast discovery or multi-recipient proof is claimed","key":"1","section":"frontier"}
F The real byte-stream laboratory is loopback only on explicit48495; no physical device, TLS certificate pinning, multicast discovery or multi-recipient proof is claimed
-- @record {"chapter":"proofs-d-nearby","data":"This executable journey proves only Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action. Other declared contracts, rendered surfaces, physical devices and live provider behavior require their separate journeys.","key":"2","section":"frontier"}
F This executable journey proves only Create a hash-bound actual file preview, refuse unapproved send, and refuse changed source before any socket action. Other declared contracts, rendered surfaces, physical devices and live provider behavior require their separate journeys.
-- @record {"chapter":"proofs-d-nearby","data":"User/SDK entry points: plan_nearby_send, send_nearby_files, cancel_nearby_active_transfer, get_nearby_active_transfer; all use NearbySendService and shared root state","key":"0","section":"guidance"}
M nearby-send-runtime "User/SDK entry points: plan_nearby_send, send_nearby_files, cancel_nearby_active_transfer, get_nearby_active_transfer; all use NearbySendService and shared root state" src:"authored manual" state:verified
-- @record {"chapter":"proofs-d-nearby","data":"Production inline contract module: src/grant_agent/proofs_d_nearby.py; declaration and original-case mapping: config/proofs/d-nearby.json","key":"1","section":"guidance"}
M nearby-send-runtime "Production inline contract module: src/grant_agent/proofs_d_nearby.py; declaration and original-case mapping: config/proofs/d-nearby.json" src:"authored manual" state:verified
-- @record {"chapter":"proofs-d-nearby","data":"Startup procedures use a real socket receiver that writes received payloads and computes their SHA256, real child SDK cancellation, a terminated owned child sender, and receiver-held acknowledged bytes","key":"2","section":"guidance"}
M nearby-send-runtime "Startup procedures use a real socket receiver that writes received payloads and computes their SHA256, real child SDK cancellation, a terminated owned child sender, and receiver-held acknowledged bytes" src:"authored manual" state:verified
