CL 1
L neyvia-reference v1 -- Authored executable manual
-- @manual {"chapters":{"missions":{"title":"missions"},"proactivity":{"title":"proactivity"},"proofs-c-live-review-frontend":{"title":"PROOFS-c: live review projection integrity"},"renderer":{"title":"Renderer pane acknowledgement"},"schedule":{"title":"schedule"},"time":{"title":"time"}},"clVersion":"1.1","id":"neyvia-reference","kind":"environment","proofs":{"area":"proofs-c-frontend"},"schema":"neyvia.manual.v1","schemas":{"neyvia.attention.list":"t1","neyvia.mission.control":"t2","neyvia.mission.create":"t3","neyvia.mission.list":"t4","neyvia.pane.observe":"t5","neyvia.pane.show":"live_schema_32","neyvia.schedule.after":"t7","neyvia.schedule.cancel":"t8","neyvia.schedule.create":"t9","neyvia.schedule.list":"t4","neyvia.time.budget":"t10","neyvia.time.now":"t4","neyvia.timer.lap":"t11","neyvia.timer.list":"t12","neyvia.timer.read":"t13","neyvia.timer.start":"t14","neyvia.timer.stop":"t8","neyvia.watch.cancel":"t8","neyvia.watch.create":"t15","neyvia.watch.list":"t16"},"tool_metadata":{"neyvia.attention.list":{"mutability_class":"read"},"neyvia.mission.control":{"mutability_class":"none"},"neyvia.mission.create":{"mutability_class":"none"},"neyvia.mission.list":{"mutability_class":"read"},"neyvia.pane.observe":{"mutability_class":"none"},"neyvia.pane.show":{"mutability_class":"none"},"neyvia.schedule.after":{"mutability_class":"none"},"neyvia.schedule.cancel":{"mutability_class":"none"},"neyvia.schedule.create":{"mutability_class":"none"},"neyvia.schedule.list":{"mutability_class":"read"},"neyvia.time.budget":{"mutability_class":"read"},"neyvia.time.now":{"mutability_class":"read"},"neyvia.timer.lap":{"mutability_class":"none"},"neyvia.timer.list":{"mutability_class":"read"},"neyvia.timer.read":{"mutability_class":"read"},"neyvia.timer.start":{"mutability_class":"none"},"neyvia.timer.stop":{"mutability_class":"none"},"neyvia.watch.cancel":{"mutability_class":"none"},"neyvia.watch.create":{"mutability_class":"none"},"neyvia.watch.list":{"mutability_class":"read"}}}
T live_schema_32 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str ..}
T live_schema_31 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
-- @proof {"checkedAt":["web/src/neyvia/missionControlModel.js:buildMissionControlModel -> checkedLiveReviewProjection","web/src/neyvia/missionReviewContracts.js:checkedLiveReviewProjection"],"claim":"Live review preserves every event domain, annotation recovery handles, screenshot/replay links, planner and supervisor route/feedback fields","id":"mission.review.projection","impact":["Live review projection, replay and planner proof handles"],"phase":"post"}
T t1{limit?:1..100 offset?:0.. recentHours?:0.01..720 ..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"action\":{\"type\":\"string\",\"enum\":[\"start\",\"pause\",\"stop\",\"redirect\"]},\"taskId\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"}},\"required\":[\"id\",\"action\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"goal\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"tasks\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"harness\":{\"type\":\"string\"},\"owner\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"transport\":{\"type\":\"string\"},\"routingProfile\":{\"type\":\"string\",\"enum\":[\"planner\",\"executor\",\"verifier\",\"classifier\"]},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"requiresGpu\":{\"type\":\"boolean\"},\"completionEvidence\":{\"type\":\"object\"}},\"required\":[\"id\",\"prompt\"]}},\"budget\":{\"type\":\"object\"},\"acceptanceChecks\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"goal\",\"folder\",\"tasks\",\"acceptanceChecks\"],\"allOf\":[{\"properties\":{\"goal\":{\"not\":{\"enum\":[\"\"]}},\"folder\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4{..}
T t5{eventId?:str ..}
T t6{kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"seconds\":{\"type\":\"number\",\"exclusiveMinimum\":0},\"prompt\":{\"type\":\"string\"},\"scope\":{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty object means notification only. An empty text transport wrapper uses this same safe scope.\"},\"requestId\":{\"type\":\"string\"}},\"required\":[\"seconds\",\"prompt\",\"scope\",\"requestId\"],\"allOf\":[{\"properties\":{\"prompt\":{\"not\":{\"enum\":[\"\"]}},\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t9 json:"{\"type\":\"object\",\"properties\":{\"when\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"scope\":{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty scope means notification only, including an empty text transport wrapper.\"},\"requestId\":{\"type\":\"string\"}},\"required\":[\"when\",\"prompt\",\"scope\",\"requestId\"],\"allOf\":[{\"properties\":{\"when\":{\"not\":{\"enum\":[\"\"]}},\"prompt\":{\"not\":{\"enum\":[\"\"]}},\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10{deadlineAt?:str estimatedNextSeconds?:json:"{\"type\":\"number\",\"minimum\":0}" verificationReserveSeconds?:json:"{\"type\":\"number\",\"minimum\":0}" optional?:bool ..}
T t11 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"lapId\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"phase\":{\"type\":\"string\",\"enum\":[\"planning\",\"execution\",\"verification\",\"review\",\"other\"]}},\"required\":[\"id\",\"lapId\",\"label\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"lapId\":{\"not\":{\"enum\":[\"\"]}},\"label\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t12{status?:json:"{\"type\":\"string\",\"enum\":[\"running\",\"stopped\",\"all\"]}" offset?:0.. limit?:1..100 ..}
T t13 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t14 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"phase\":{\"type\":\"string\",\"enum\":[\"planning\",\"execution\",\"verification\",\"review\",\"other\"]},\"targetSeconds\":{\"type\":\"number\",\"exclusiveMinimum\":0}},\"required\":[\"id\",\"label\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"label\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t15 json:"{\"type\":\"object\",\"properties\":{\"requestId\":{\"type\":\"string\"},\"runId\":{\"type\":\"string\"},\"message\":{\"type\":\"string\"},\"states\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"completed\",\"failed\",\"interrupted\",\"cancelled\",\"waiting_approval\",\"waiting_input\"]}},\"followup\":{\"type\":\"object\",\"properties\":{\"app\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"}},\"required\":[\"app\",\"folder\",\"prompt\"],\"additionalProperties\":false}},\"required\":[\"requestId\",\"runId\",\"message\"],\"allOf\":[{\"properties\":{\"requestId\":{\"not\":{\"enum\":[\"\"]}},\"runId\":{\"not\":{\"enum\":[\"\"]}},\"message\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t16{offset?:0.. limit?:1..100 ..}
T t17{}
T t18 json:"{\"type\":\"object\"}"
T t19{goal:str folder:str tasks:[{id:str prompt:str title?:str folder?:str harness?:str owner?:str model?:str effort?:str permissionMode?:str transport?:str routingProfile?:json:"{\"type\":\"string\",\"enum\":[\"planner\",\"executor\",\"verifier\",\"classifier\"]}" needs?:[str] requiresGpu?:bool completionEvidence?:json:"{\"type\":\"object\"}" ..}] acceptanceChecks:[str]}
T t20{id:str}
T t21{index:0.. id:str status:str}
T t22{runId:str requestId:str message:str states:[json:"{\"type\":\"string\",\"enum\":[\"completed\",\"failed\",\"interrupted\",\"cancelled\",\"waiting_approval\",\"waiting_input\"]}"]}
T t23{id:str ..}
T t24{requestId:str runId:str message:str ..}
T t25{schedule:{id:str ..} ..}
T t26{seconds:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}" prompt:str requestId:str}
T t27{seconds:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}" prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty object means notification only. An empty text transport wrapper uses this same safe scope.\"}" requestId:str ..}
T t28{when:str prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty scope means notification only, including an empty text transport wrapper.\"}" requestId:str ..}
T t29{id:str label:str}
T t30{id:str lapId:str label:str}
L neyvia-reference.missions v1 -- missions
-- @record {"chapter":"missions","data":{"args":{},"inputs":{"$cl_type":"t17"},"shape":{"$cl_type":"t18"},"tool":"neyvia.mission.list"},"key":"current","section":"state"}
S neyvia-reference.current:json:"{\"type\":\"object\"}"=neyvia.mission.list()
-- @record {"chapter":"missions","data":{"effect":"Read missions/task trees, acceptance evidence and reported usage coverage","pre":"Night Shift service stores readable","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.mission.list","tool":"neyvia.mission.list"},"key":"mission.list","section":"actions"}
A neyvia.mission.list() -> json:"{\"type\":\"object\"}" -- Read missions/task trees, acceptance evidence and reported usage coverage
C neyvia.mission.list selected-id:neyvia.mission.list() ["missions"] [index] ["id"] == id
C neyvia.mission.list selected-status:neyvia.mission.list() ["missions"] [index] ["status"] == status
-- @record {"chapter":"missions","data":{"effect":"Start approved branches, pause future launches, stop owned runs or redirect dormant task; completed evidence immutable","pre":"Known mission/task branch; start needs fingerprint-bound owner approval; redirect only dormant/blocked task and nonempty route/prompt patch","returns":{"$cl_type":"t18"},"reversible":false,"schema":"neyvia.mission.control","tool":"neyvia.mission.control"},"key":"mission.control","section":"actions"}
A neyvia.mission.control(id:str action:json:"{\"type\":\"string\",\"enum\":[\"start\",\"pause\",\"stop\",\"redirect\"]}" taskId?:str prompt?:str model?:str effort?:str permissionMode?:str) -> json:"{\"type\":\"object\"}" ! -- Start approved branches, pause future launches, stop owned runs or redirect dormant task; completed evidence immutable
F verify-mission-control "No authored observer check is bound to neyvia.mission.control" -> ask operator blocks:neyvia.mission.control
-- @record {"chapter":"missions","data":{"effect":"Persist draft mission and dormant waiting tasks; nothing launches","pre":"Nonblank goal/checks; 1–100 unique explicit task IDs; safe folders/routes; acyclic internal needs; positive recognized budgets; exact ID retries","returns":{"$cl_type":"t18"},"reversible":false,"schema":"neyvia.mission.create","tool":"neyvia.mission.create"},"key":"mission.create","section":"actions"}
A neyvia.mission.create(id?:str goal:str folder:str tasks:[{id:str prompt:str title?:str folder?:str harness?:str owner?:str model?:str effort?:str permissionMode?:str transport?:str routingProfile?:json:"{\"type\":\"string\",\"enum\":[\"planner\",\"executor\",\"verifier\",\"classifier\"]}" needs?:[str] requiresGpu?:bool completionEvidence?:json:"{\"type\":\"object\"}" ..}] budget?:json:"{\"type\":\"object\"}" acceptanceChecks:[str]) -> json:"{\"type\":\"object\"}" ! -- Persist draft mission and dormant waiting tasks; nothing launches
F verify-mission-create "No authored observer check is bound to neyvia.mission.create" -> ask operator blocks:neyvia.mission.create
-- @record {"chapter":"missions","data":{"args":{},"expect":{"op":"eq","path":["missions",{"$input":"index"},"id"],"value":{"$input":"id"}},"tool":"neyvia.mission.list"},"key":"selected-id","section":"checks"}
C neyvia.mission.list selected-id:neyvia.mission.list() ["missions"] [index] ["id"] == id
-- @record {"chapter":"missions","data":{"args":{},"expect":{"op":"eq","path":["missions",{"$input":"index"},"status"],"value":{"$input":"status"}},"tool":"neyvia.mission.list"},"key":"selected-status","section":"checks"}
C neyvia.mission.list selected-status:neyvia.mission.list() ["missions"] [index] ["status"] == status
-- @record {"chapter":"missions","data":{"goal":"Read mission inventory, review explicit task graph and save dormant draft","inputs":{"$cl_type":"t19"},"steps":[{"action":"mission.list","args":{},"save":"before"},{"judge":"mission-draft"},{"action":"mission.create","args":{"acceptanceChecks":{"$input":"acceptanceChecks"},"folder":{"$path":"folder"},"goal":{"$input":"goal"},"tasks":{"$input":"tasks"}},"save":"draft","when":{"judge":"mission-draft","option":"store-draft"}},{"action":"mission.list","args":{},"save":"retained","when":{"judge":"mission-draft","option":"store-draft"}}]},"key":"draft-mission","section":"procedures"}
P draft-mission(goal:str folder:str tasks:[{id:str prompt:str title?:str folder?:str harness?:str owner?:str model?:str effort?:str permissionMode?:str transport?:str routingProfile?:json:"{\"type\":\"string\",\"enum\":[\"planner\",\"executor\",\"verifier\",\"classifier\"]}" needs?:[str] requiresGpu?:bool completionEvidence?:json:"{\"type\":\"object\"}" ..}] acceptanceChecks:[str]):before=neyvia.mission.list(); J mission-draft=store-draft; draft=neyvia.mission.create(acceptanceChecks:acceptanceChecks folder:folder goal:goal tasks:tasks); retained=neyvia.mission.list() -- Read mission inventory, review explicit task graph and save dormant draft
V P draft-mission -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"missions","data":{"goal":"Read actual branch state and choose pause or stop","inputs":{"$cl_type":"t20"},"steps":[{"action":"mission.list","args":{},"save":"before"},{"judge":"branch-control"},{"action":"mission.control","args":{"action":"pause","id":{"$input":"id"}},"save":"paused","when":{"judge":"branch-control","option":"pause"}},{"action":"mission.control","args":{"action":"stop","id":{"$input":"id"}},"save":"stopped","when":{"judge":"branch-control","option":"stop"}},{"action":"mission.list","args":{},"save":"after"}]},"key":"supervise-mission","section":"procedures"}
P supervise-mission(id:str):before=neyvia.mission.list(); J branch-control=pause; paused=neyvia.mission.control(action:"pause" id:id); stopped=neyvia.mission.control(action:"stop" id:id); after=neyvia.mission.list() -- Read actual branch state and choose pause or stop
V P supervise-mission -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"missions","data":{"goal":"Verify that the selected mission has the expected ID and draft/running/paused/stopped state","inputs":{"$cl_type":"t21"},"steps":[{"action":"mission.list","args":{},"check":"selected-id","save":"identity"},{"action":"mission.list","args":{},"check":"selected-status","save":"outcome"}]},"key":"verify-retained-status","section":"procedures"}
P verify-retained-status(index:0.. id:str status:str):identity=neyvia.mission.list() C selected-id; outcome=neyvia.mission.list() C selected-status -- Verify that the selected mission has the expected ID and draft/running/paused/stopped state
V P verify-retained-status -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"missions","data":{"constraints":"Draft storage launches nothing. IDs unique, needs internal and acyclic; choose concrete completion evidence and positive token/time limits. Start requires owner approval fingerprint for exact mission/branches.","options":["store-draft","revise"],"question":"Do tasks, prerequisites, route and acceptance checks express the requested goal?"},"key":"mission-draft","section":"judge"}
J mission-draft store-draft|revise:"Do tasks, prerequisites, route and acceptance checks express the requested goal?" -- Draft storage launches nothing. IDs unique, needs internal and acyclic; choose concrete completion evidence and positive token/time limits. Start requires owner approval fingerprint for exact mission/branches.
V J mission-draft -> human:operator why:"explicit choice required"
-- @record {"chapter":"missions","data":{"constraints":"Pause leaves running tasks active; stop cancels selected owned runs and dependent branches. Neither changes completed evidence. Confirm exact mission/task scope before decision.","options":["pause","stop"],"question":"Pause future launches or stop owned runs?"},"key":"branch-control","section":"judge"}
J branch-control pause|stop:"Pause future launches or stop owned runs?" -- Pause leaves running tasks active; stop cancels selected owned runs and dependent branches. Neither changes completed evidence. Confirm exact mission/task scope before decision.
V J branch-control -> human:operator why:"explicit choice required"
-- @record {"chapter":"missions","data":{"failure":"Cyclic or outside-mission prerequisites","recovery":"Repair explicit needs graph; draft refused before storage"},"key":"0","section":"pitfalls"}
X Cyclic or outside-mission prerequisites -> Repair explicit needs graph; draft refused before storage
-- @record {"chapter":"missions","data":{"failure":"Token budget waits for unknown usage","recovery":"Wait for transport-reported usage; do not estimate model text"},"key":"1","section":"pitfalls"}
X Token budget waits for unknown usage -> Wait for transport-reported usage; do not estimate model text
-- @record {"chapter":"missions","data":{"failure":"Task done interpreted as accepted quality","recovery":"Read evidence and explicit checks; evidence_ready_for_review still requires review"},"key":"2","section":"pitfalls"}
X Task done interpreted as accepted quality -> Read evidence and explicit checks; evidence_ready_for_review still requires review
-- @record {"chapter":"missions","data":{"failure":"Redirect running/done task","recovery":"Pause/reconcile running work; completed evidence immutable, create fresh task intent"},"key":"3","section":"pitfalls"}
X Redirect running/done task -> Pause/reconcile running work; completed evidence immutable, create fresh task intent
-- @record {"chapter":"missions","data":{"failure":"A Claude Code or Codex task waits with 'Holding: ... limit at N%'","recovery":"Its plan window passed Night Shift resources holdAtPlanPercent (default 70); it starts by itself after the shown reset. Raise or null holdAtPlanPercent only when Paul says so."},"key":"4","section":"pitfalls"}
X A Claude Code or Codex task waits with 'Holding: ... limit at N%' -> Its plan window passed Night Shift resources holdAtPlanPercent (default 70); it starts by itself after the shown reset. Raise or null holdAtPlanPercent only when Paul says so.
-- @record {"chapter":"missions","data":"Mission semantic quality and cash cost are not generated by summary","key":"0","section":"frontier"}
F Mission semantic quality and cash cost are not generated by summary
-- @record {"chapter":"missions","data":"Unreported transport token usage prevents exact budget admission","key":"1","section":"frontier"}
F Unreported transport token usage prevents exact budget admission
-- @record {"chapter":"missions","data":"Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs.","key":"0","section":"guidance"}
M neyvia-reference "Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs." src:"authored manual" state:verified
-- @record {"chapter":"missions","data":"For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread.","key":"1","section":"guidance"}
M neyvia-reference "For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread." src:"authored manual" state:verified
L neyvia-reference.proactivity v1 -- proactivity
-- @record {"chapter":"proactivity","data":{"args":{},"inputs":{"$cl_type":"t17"},"shape":{"$cl_type":"t18"},"tool":"neyvia.attention.list"},"key":"current","section":"state"}
S neyvia-reference.current:json:"{\"type\":\"object\"}"=neyvia.attention.list()
-- @record {"chapter":"proactivity","data":{"effect":"Read outstanding approvals, waiting/failed runs and blocked tasks with source IDs; no automatic repair","pre":"Backend broker plus Night Shift store; bounded offset/limit","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.attention.list","tool":"neyvia.attention.list"},"key":"attention.list","section":"actions"}
A neyvia.attention.list(limit?:1..100 offset?:0.. recentHours?:0.01..720) -> json:"{\"type\":\"object\"}" -- Read outstanding approvals, waiting/failed runs and blocked tasks with source IDs; no automatic repair
F verify-attention-list "No authored observer check is bound to neyvia.attention.list" -> ask operator blocks:neyvia.attention.list
-- @record {"chapter":"proactivity","data":{"effect":"Persist cancelled watch and wake scheduler; existing follow-up/run unaffected","pre":"Known armed watch; cancelled exact retry allowed; fired watches cannot be cancelled here","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.watch.cancel","tool":"neyvia.watch.cancel"},"key":"watch.cancel","section":"actions"}
A neyvia.watch.cancel(id:str) -> json:"{\"type\":\"object\"}" ! -- Persist cancelled watch and wake scheduler; existing follow-up/run unaffected
F verify-watch-cancel "No authored observer check is bound to neyvia.watch.cancel" -> ask operator blocks:neyvia.watch.cancel
-- @record {"chapter":"proactivity","data":{"effect":"Arm event-driven one-shot notification; optional approved follow-up uses durable scheduler","pre":"Known broker run, stable requestId exact fingerprint; supported nonempty states; message 1–2000 chars; <=64 armed; optional explicit read-only followup needs exact approval","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.watch.create","tool":"neyvia.watch.create"},"key":"watch.create","section":"actions"}
A neyvia.watch.create(requestId:str runId:str message:str states?:[json:"{\"type\":\"string\",\"enum\":[\"completed\",\"failed\",\"interrupted\",\"cancelled\",\"waiting_approval\",\"waiting_input\"]}"] followup?:{app:str folder:str prompt:str model?:str}) -> json:"{\"type\":\"object\"}" -- Arm event-driven one-shot notification; optional approved follow-up uses durable scheduler
F verify-watch-create "No authored observer check is bound to neyvia.watch.create" -> ask operator blocks:neyvia.watch.create
-- @record {"chapter":"proactivity","data":{"effect":"Read watch conditions/outcomes and follow-up schedule/run identities","pre":"Workspace watch store readable; offset >=0, limit 1–100","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.watch.list","tool":"neyvia.watch.list"},"key":"watch.list","section":"actions"}
A neyvia.watch.list(offset?:0.. limit?:1..100) -> json:"{\"type\":\"object\"}" -- Read watch conditions/outcomes and follow-up schedule/run identities
C neyvia.watch.list selected-id:neyvia.watch.list() ["watches"] [index] ["id"] == id
C neyvia.watch.list selected-status:neyvia.watch.list() ["watches"] [index] ["status"] == status
-- @record {"chapter":"proactivity","data":{"args":{},"expect":{"op":"eq","path":["watches",{"$input":"index"},"id"],"value":{"$input":"id"}},"tool":"neyvia.watch.list"},"key":"selected-id","section":"checks"}
C neyvia.watch.list selected-id:neyvia.watch.list() ["watches"] [index] ["id"] == id
-- @record {"chapter":"proactivity","data":{"args":{},"expect":{"op":"eq","path":["watches",{"$input":"index"},"status"],"value":{"$input":"status"}},"tool":"neyvia.watch.list"},"key":"selected-status","section":"checks"}
C neyvia.watch.list selected-status:neyvia.watch.list() ["watches"] [index] ["status"] == status
-- @record {"chapter":"proactivity","data":{"goal":"Read pending approvals, blocked tasks and recent failed runs before intervention","inputs":{"$cl_type":"t17"},"steps":[{"action":"attention.list","args":{},"save":"inbox"},{"action":"watch.list","args":{},"save":"watches"},{"judge":"attention"}]},"key":"triage-attention","section":"procedures"}
P triage-attention():inbox=neyvia.attention.list(); watches=neyvia.watch.list(); J attention -- Read pending approvals, blocked tasks and recent failed runs before intervention
V P triage-attention -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proactivity","data":{"goal":"Inspect retained watches, review terminal/waiting conditions and arm a notification","inputs":{"$cl_type":"t22"},"steps":[{"action":"watch.list","args":{},"save":"before"},{"judge":"watch-intent"},{"action":"watch.create","args":{"message":{"$input":"message"},"requestId":{"$input":"requestId"},"runId":{"$input":"runId"},"states":{"$input":"states"}},"save":"armed","when":{"judge":"watch-intent","option":"arm"}},{"action":"watch.list","args":{},"save":"after","when":{"judge":"watch-intent","option":"arm"}}]},"key":"watch-run","section":"procedures"}
P watch-run(runId:str requestId:str message:str states:[json:"{\"type\":\"string\",\"enum\":[\"completed\",\"failed\",\"interrupted\",\"cancelled\",\"waiting_approval\",\"waiting_input\"]}"]):before=neyvia.watch.list(); J watch-intent=arm; armed=neyvia.watch.create(message:message requestId:requestId runId:runId states:states); after=neyvia.watch.list() -- Inspect retained watches, review terminal/waiting conditions and arm a notification
V P watch-run -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proactivity","data":{"goal":"Verify the chosen one-shot watch identity and armed/fired/cancelled/blocked/uncertain status","inputs":{"$cl_type":"t21"},"steps":[{"action":"watch.list","args":{},"check":"selected-id","save":"identity"},{"action":"watch.list","args":{},"check":"selected-status","save":"outcome"}]},"key":"verify-retained-status","section":"procedures"}
P verify-retained-status(index:0.. id:str status:str):identity=neyvia.watch.list() C selected-id; outcome=neyvia.watch.list() C selected-status -- Verify the chosen one-shot watch identity and armed/fired/cancelled/blocked/uncertain status
V P verify-retained-status -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proactivity","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t23"},"steps":[{"action":"watch.cancel","args":{"id":{"$input":"id"}},"save":"effect"}]},"key":"verify-effect-watch-cancel","section":"procedures"}
P verify-effect-watch-cancel(id:str):effect=neyvia.watch.cancel(id:id) -- Verify the actual effect through fresh owning observers
V P verify-effect-watch-cancel -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proactivity","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t24"},"steps":[{"action":"watch.create","args":{"message":{"$input":"message"},"requestId":{"$input":"requestId"},"runId":{"$input":"runId"}},"save":"effect"}]},"key":"verify-effect-watch-create","section":"procedures"}
P verify-effect-watch-create(requestId:str runId:str message:str):effect=neyvia.watch.create(message:message requestId:requestId runId:runId) -- Verify the actual effect through fresh owning observers
V P verify-effect-watch-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proactivity","data":{"constraints":"Prioritize explicit approval/waiting input IDs. Do not retry failed/interrupted work without inspecting retained effects. Inbox is bounded local evidence, not an outcome verdict.","options":["owner-input","inspect-run"],"question":"Does this item need owner input or reconciliation of an existing run?"},"key":"attention","section":"judge"}
J attention owner-input|inspect-run:"Does this item need owner input or reconciliation of an existing run?" -- Prioritize explicit approval/waiting input IDs. Do not retry failed/interrupted work without inspecting retained effects. Inbox is bounded local evidence, not an outcome verdict.
V J attention -> human:operator why:"explicit choice required"
-- @record {"chapter":"proactivity","data":{"constraints":"Notification only, no followup object here. Choose supported states and exact message; runId must exist, stable requestId exact intent, max 64 armed. Followup chat requires separate explicit approval.","options":["arm","leave"],"question":"Arm a one-shot notification for this known run condition?"},"key":"watch-intent","section":"judge"}
J watch-intent arm|leave:"Arm a one-shot notification for this known run condition?" -- Notification only, no followup object here. Choose supported states and exact message; runId must exist, stable requestId exact intent, max 64 armed. Followup chat requires separate explicit approval.
V J watch-intent -> human:operator why:"explicit choice required"
-- @record {"chapter":"proactivity","data":{"failure":"Watch fired/uncertain after backend restart","recovery":"Inspect saved event/schedule; never automatic rearm or duplicate follow-up"},"key":"0","section":"pitfalls"}
X Watch fired/uncertain after backend restart -> Inspect saved event/schedule; never automatic rearm or duplicate follow-up
-- @record {"chapter":"proactivity","data":{"failure":"Cancel already-fired watch refused","recovery":"Use returned schedule/run controls; watch.cancel affects only armed watch"},"key":"1","section":"pitfalls"}
X Cancel already-fired watch refused -> Use returned schedule/run controls; watch.cancel affects only armed watch
-- @record {"chapter":"proactivity","data":{"failure":"Attention list truncated","recovery":"Page with nextOffset and narrower recentHours; absence is not absence from all history"},"key":"2","section":"pitfalls"}
X Attention list truncated -> Page with nextOffset and narrower recentHours; absence is not absence from all history
-- @record {"chapter":"proactivity","data":"No provider polling or automatic repair in attention.list","key":"0","section":"frontier"}
F No provider polling or automatic repair in attention.list
-- @record {"chapter":"proactivity","data":"Watch supports explicit states only; arbitrary semantic conditions unmapped","key":"1","section":"frontier"}
F Watch supports explicit states only; arbitrary semantic conditions unmapped
-- @record {"chapter":"proactivity","data":"Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs.","key":"0","section":"guidance"}
M neyvia-reference "Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs." src:"authored manual" state:verified
-- @record {"chapter":"proactivity","data":"For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread.","key":"1","section":"guidance"}
M neyvia-reference "For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread." src:"authored manual" state:verified
L neyvia-reference.proofs-c-live-review-frontend v1 -- PROOFS-c: live review projection integrity
-- @record {"chapter":"proofs-c-live-review-frontend","data":{"failure":"A passing model self-check is mistaken for remote generation or rendered UI proof","recovery":"Inspect the receipt boundary and run the actual application journey for its remaining frontier"},"key":"0","section":"pitfalls"}
X A passing model self-check is mistaken for remote generation or rendered UI proof -> Inspect the receipt boundary and run the actual application journey for its remaining frontier
-- @record {"chapter":"proofs-c-live-review-frontend","data":"Image UI route/default runtime wiring and rendered browser controls still need their actual user journeys","key":"0","section":"frontier"}
F Image UI route/default runtime wiring and rendered browser controls still need their actual user journeys
-- @record {"chapter":"proofs-c-live-review-frontend","data":"Historical Codex May-11 reference manifest was replaced by current May-13 imagegen reference; missing history alone does not establish dead code","key":"1","section":"frontier"}
F Historical Codex May-11 reference manifest was replaced by current May-13 imagegen reference; missing history alone does not establish dead code
-- @record {"chapter":"proofs-c-live-review-frontend","data":"Live review connected bridge, planner panels, proof-copy links, replay controls and project switcher remain rendered UI boundaries","key":"2","section":"frontier"}
F Live review connected bridge, planner panels, proof-copy links, replay controls and project switcher remain rendered UI boundaries
-- @record {"chapter":"proofs-c-live-review-frontend","data":"Mobile authenticated lazy loading, bootstrap refresh, empty phone indexes and one-session transcript hydration remain integration/UI boundaries","key":"3","section":"frontier"}
F Mobile authenticated lazy loading, bootstrap refresh, empty phone indexes and one-session transcript hydration remain integration/UI boundaries
-- @record {"chapter":"proofs-c-live-review-frontend","data":"SVG compositor is a real local registered provider; external remote image generation is not exercised","key":"4","section":"frontier"}
F SVG compositor is a real local registered provider; external remote image generation is not exercised
-- @record {"chapter":"proofs-c-live-review-frontend","data":"Startup entry: scripts/proofs-c-frontend.mjs --root <scratch>; config/proofs/proofs-c-frontend.json owns reviewed procedures and per-case coverage","key":"0","section":"guidance"}
M neyvia-reference "Startup entry: scripts/proofs-c-frontend.mjs --root <scratch>; config/proofs/proofs-c-frontend.json owns reviewed procedures and per-case coverage" src:"authored manual" state:verified
L neyvia-reference.renderer v1 -- Renderer pane acknowledgement
-- @record {"chapter":"renderer","data":{"args":{},"inputs":{"$cl_type":"t4"},"shape":{"$cl_type":"t18"},"tool":"neyvia.pane.observe"},"key":"visible-pane","section":"state"}
S neyvia-reference.visible-pane:json:"{\"type\":\"object\"}"=neyvia.pane.observe()
-- @record {"chapter":"renderer","data":{"effect":"Fresh content observation","pre":"Authenticated owner renderer uses this workspace event channel","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.pane.observe","tool":"neyvia.pane.observe"},"key":"pane.observe","section":"actions"}
A neyvia.pane.observe(eventId?:str) -> json:"{\"type\":\"object\"}" -- Fresh content observation
F verify-pane-observe "No authored observer check is bound to neyvia.pane.observe" -> ask operator blocks:neyvia.pane.observe
-- @record {"chapter":"renderer","data":{"effect":"Request a pane; completion waits for mounted visible content acknowledgement","pre":"Authenticated owner renderer uses this workspace event channel","returns":{"type":"object"},"reversible":true,"schema":"neyvia.pane.show","tool":"neyvia.pane.show"},"key":"pane.show","section":"actions"}
A neyvia.pane.show(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str) -> json:"{\"type\":\"object\"}" -- Request a pane; completion waits for mounted visible content acknowledgement
C neyvia.pane.show visible: neyvia.pane.observe().visible==true
-- @record {"chapter":"renderer","data":{"args":{},"expect":{"op":"eq","path":"visible","value":true},"tool":"neyvia.pane.observe"},"key":"visible","section":"checks"}
C neyvia.pane.observe visible:neyvia.pane.observe() .visible == true
-- @record {"chapter":"renderer","data":{"goal":"Mount the requested pane and verify its fresh rendered content","inputs":{"type":"object","properties":{"kind":{"type":"string","enum":["diff","file","artifact","terminal","browser","mission","replay","builder","accounts","runtime","settings","preview","outputs","perception","agentview","sessions","usage","parallel","agents"]},"target":{"type":"string"}},"required":["kind","target"]},"steps":[{"action":"pane.show","args":{"kind":{"$input":"kind"},"target":{"$input":"target"}},"check":"visible","save":"request"}]},"key":"show-observed-pane","section":"procedures"}
P show-observed-pane(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str): request=neyvia.pane.show(kind:kind target:target) C visible -- Mount the requested pane and verify its fresh rendered content
V P show-observed-pane -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"renderer","data":{"failure":"No renderer content report or stale observation","recovery":"Mount in the owner shell and report content over /api/ui/ack; never invent a renderer receipt"},"key":"0","section":"pitfalls"}
X No renderer content report or stale observation -> Mount in the owner shell and report content over /api/ui/ack; never invent a renderer receipt
-- @record {"chapter":"renderer","data":"Claude UI wiring and real Neyvia renderer mount/content proof remain required; queued pane events are incomplete","key":"0","section":"frontier"}
F Claude UI wiring and real Neyvia renderer mount/content proof remain required; queued pane events are incomplete
-- @record {"chapter":"renderer","data":"ACK observation: paneId, runtimeId, kind, target, contentHash (SHA-256 of UTF-8 displayed content), mounted, visible. Heartbeat at most 5 seconds; reports expire after 30 seconds. File content uses normalized editor text.","key":"0","section":"guidance"}
M neyvia-reference "ACK observation: paneId, runtimeId, kind, target, contentHash (SHA-256 of UTF-8 displayed content), mounted, visible. Heartbeat at most 5 seconds; reports expire after 30 seconds. File content uses normalized editor text." src:"authored manual" state:verified
L neyvia-reference.schedule v1 -- schedule
-- @record {"chapter":"schedule","data":{"args":{},"inputs":{"$cl_type":"t17"},"shape":{"$cl_type":"t18"},"tool":"neyvia.schedule.list"},"key":"current","section":"state"}
S neyvia-reference.current:json:"{\"type\":\"object\"}"=neyvia.schedule.list()
-- @record {"chapter":"schedule","data":{"effect":"Read durable follow-up records and outcomes; no new launches","pre":"Workspace scheduler store readable","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.schedule.list","tool":"neyvia.schedule.list"},"key":"schedule.list","section":"actions"}
A neyvia.schedule.list() -> json:"{\"type\":\"object\"}" -- Read durable follow-up records and outcomes; no new launches
C neyvia.schedule.list selected-id:neyvia.schedule.list() ["schedules"] [index] ["id"] == id
C neyvia.schedule.list selected-status:neyvia.schedule.list() ["schedules"] [index] ["status"] == status
-- @record {"chapter":"schedule","data":{"effect":"Translate relative delay once into durable follow-up; retries keep original timestamp","pre":"Positive finite seconds; stable ID <=160 chars; exact seconds/prompt/scope on retry; chat scope read-only with safe folder and supported harness","returns":{"$cl_type":"t25"},"reversible":true,"schema":"neyvia.schedule.after","tool":"neyvia.schedule.after"},"key":"schedule.after","section":"actions"}
A neyvia.schedule.after(seconds:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}" prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty object means notification only. An empty text transport wrapper uses this same safe scope.\"}" requestId:str) -> {schedule:{id:str ..} ..} -- Translate relative delay once into durable follow-up; retries keep original timestamp
F verify-schedule-after "No authored observer check is bound to neyvia.schedule.after" -> ask operator blocks:neyvia.schedule.after
-- @record {"chapter":"schedule","data":{"effect":"Persist cancelled status; fired follow-ups require separate run reconciliation","pre":"Existing pending follow-up ID","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.schedule.cancel","tool":"neyvia.schedule.cancel"},"key":"schedule.cancel","section":"actions"}
A neyvia.schedule.cancel(id:str) -> json:"{\"type\":\"object\"}" ! -- Persist cancelled status; fired follow-ups require separate run reconciliation
F verify-schedule-cancel "No authored observer check is bound to neyvia.schedule.cancel" -> ask operator blocks:neyvia.schedule.cancel
-- @record {"chapter":"schedule","data":{"effect":"Persist one pending follow-up and wake workspace scheduler; empty scope means notification only","pre":"Nonblank stable requestId; future timezone-qualified when; retry prompt/scope/time identical; chat scope read-only with safe folder and supported harness","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.schedule.create","tool":"neyvia.schedule.create"},"key":"schedule.create","section":"actions"}
A neyvia.schedule.create(when:str prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty scope means notification only, including an empty text transport wrapper.\"}" requestId:str) -> json:"{\"type\":\"object\"}" ! -- Persist one pending follow-up and wake workspace scheduler; empty scope means notification only
F verify-schedule-create "No authored observer check is bound to neyvia.schedule.create" -> ask operator blocks:neyvia.schedule.create
-- @record {"chapter":"schedule","data":{"args":{},"expect":{"op":"eq","path":["schedules",{"$input":"index"},"id"],"value":{"$input":"id"}},"tool":"neyvia.schedule.list"},"key":"selected-id","section":"checks"}
C neyvia.schedule.list selected-id:neyvia.schedule.list() ["schedules"] [index] ["id"] == id
-- @record {"chapter":"schedule","data":{"args":{},"expect":{"op":"eq","path":["schedules",{"$input":"index"},"status"],"value":{"$input":"status"}},"tool":"neyvia.schedule.list"},"key":"selected-status","section":"checks"}
C neyvia.schedule.list selected-status:neyvia.schedule.list() ["schedules"] [index] ["status"] == status
-- @record {"chapter":"schedule","data":{"goal":"Read follow-ups, review reminder and schedule one notification after specified seconds","inputs":{"$cl_type":"t26"},"steps":[{"action":"schedule.list","args":{},"save":"before"},{"judge":"followup"},{"action":"schedule.after","args":{"prompt":{"$input":"prompt"},"requestId":{"$input":"requestId"},"scope":{},"seconds":{"$input":"seconds"}},"save":"scheduled","when":{"judge":"followup","option":"notify"}},{"action":"schedule.list","args":{},"save":"retained","when":{"judge":"followup","option":"notify"}}]},"key":"remind-after","section":"procedures"}
P remind-after(seconds:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}" prompt:str requestId:str):before=neyvia.schedule.list(); J followup=notify; scheduled=neyvia.schedule.after(prompt:prompt requestId:requestId scope:{} seconds:seconds); retained=neyvia.schedule.list() -- Read follow-ups, review reminder and schedule one notification after specified seconds
V P remind-after -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"goal":"Read schedule intent and cancel only selected pending follow-up","inputs":{"$cl_type":"t20"},"steps":[{"action":"schedule.list","args":{},"save":"schedules"},{"judge":"cancel-reminder"},{"action":"schedule.cancel","args":{"id":{"$input":"id"}},"save":"cancelled","when":{"judge":"cancel-reminder","option":"cancel"}}]},"key":"cancel-pending","section":"procedures"}
P cancel-pending(id:str):schedules=neyvia.schedule.list(); J cancel-reminder=cancel; cancelled=neyvia.schedule.cancel(id:id) -- Read schedule intent and cancel only selected pending follow-up
V P cancel-pending -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"goal":"Verify that the chosen follow-up has the expected ID and waiting/cancelled/done/blocked outcome","inputs":{"$cl_type":"t21"},"steps":[{"action":"schedule.list","args":{},"check":"selected-id","save":"identity"},{"action":"schedule.list","args":{},"check":"selected-status","save":"outcome"}]},"key":"verify-retained-status","section":"procedures"}
P verify-retained-status(index:0.. id:str status:str):identity=neyvia.schedule.list() C selected-id; outcome=neyvia.schedule.list() C selected-status -- Verify that the chosen follow-up has the expected ID and waiting/cancelled/done/blocked outcome
V P verify-retained-status -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t27"},"steps":[{"action":"schedule.after","args":{"prompt":{"$input":"prompt"},"requestId":{"$input":"requestId"},"scope":{"$input":"scope"},"seconds":{"$input":"seconds"}},"save":"effect"}]},"key":"verify-effect-schedule-after","section":"procedures"}
P verify-effect-schedule-after(seconds:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}" prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty object means notification only. An empty text transport wrapper uses this same safe scope.\"}" requestId:str):effect=neyvia.schedule.after(prompt:prompt requestId:requestId scope:scope seconds:seconds) -- Verify the actual effect through fresh owning observers
V P verify-effect-schedule-after -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t23"},"steps":[{"action":"schedule.cancel","args":{"id":{"$input":"id"}},"save":"effect"}]},"key":"verify-effect-schedule-cancel","section":"procedures"}
P verify-effect-schedule-cancel(id:str):effect=neyvia.schedule.cancel(id:id) -- Verify the actual effect through fresh owning observers
V P verify-effect-schedule-cancel -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t28"},"steps":[{"action":"schedule.create","args":{"prompt":{"$input":"prompt"},"requestId":{"$input":"requestId"},"scope":{"$input":"scope"},"when":{"$input":"when"}},"save":"effect"}]},"key":"verify-effect-schedule-create","section":"procedures"}
P verify-effect-schedule-create(when:str prompt:str scope:json:"{\"type\":\"object\",\"x-empty-text-is-empty-object\":true,\"description\":\"Empty scope means notification only, including an empty text transport wrapper.\"}" requestId:str):effect=neyvia.schedule.create(prompt:prompt requestId:requestId scope:scope when:when) -- Verify the actual effect through fresh owning observers
V P verify-effect-schedule-create -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"schedule","data":{"constraints":"This procedure uses scope={}; no future model is launched. For chat use explicit app/folder/model/prompt and read-only mode; never smuggle write work into scope.","options":["notify","leave"],"question":"Is this a notification-only reminder or does it require a future chat?"},"key":"followup","section":"judge"}
J followup notify|leave:"Is this a notification-only reminder or does it require a future chat?" -- This procedure uses scope={}; no future model is launched. For chat use explicit app/folder/model/prompt and read-only mode; never smuggle write work into scope.
V J followup -> human:operator why:"explicit choice required"
-- @record {"chapter":"schedule","data":{"constraints":"Match id and intent from schedule.list; fired/running follow-up cannot be undone by schedule.cancel. Cancelling future notification does not cancel an existing provider run.","options":["cancel","keep"],"question":"Is this pending reminder obsolete?"},"key":"cancel-reminder","section":"judge"}
J cancel-reminder cancel|keep:"Is this pending reminder obsolete?" -- Match id and intent from schedule.list; fired/running follow-up cannot be undone by schedule.cancel. Cancelling future notification does not cancel an existing provider run.
V J cancel-reminder -> human:operator why:"explicit choice required"
-- @record {"chapter":"schedule","data":{"failure":"Naive/past ISO timestamp refused","recovery":"Read time.now, choose future timezone-qualified timestamp"},"key":"0","section":"pitfalls"}
X Naive/past ISO timestamp refused -> Read time.now, choose future timezone-qualified timestamp
-- @record {"chapter":"schedule","data":{"failure":"requestId already represents different follow-up","recovery":"Keep original intent on retry; new intent gets new ID"},"key":"1","section":"pitfalls"}
X requestId already represents different follow-up -> Keep original intent on retry; new intent gets new ID
-- @record {"chapter":"schedule","data":{"failure":"Scheduled chat requests write permissions","recovery":"Use approved Night Shift mission instead; schedule chat scope read-only"},"key":"2","section":"pitfalls"}
X Scheduled chat requests write permissions -> Use approved Night Shift mission instead; schedule chat scope read-only
-- @record {"chapter":"schedule","data":{"failure":"Cancel pending schedule not found","recovery":"Read outcome/run identity; reconcile executed follow-up separately"},"key":"3","section":"pitfalls"}
X Cancel pending schedule not found -> Read outcome/run identity; reconcile executed follow-up separately
-- @record {"chapter":"schedule","data":"Recurring schedules and automatic write-mode follow-ups unmapped","key":"0","section":"frontier"}
F Recurring schedules and automatic write-mode follow-ups unmapped
-- @record {"chapter":"schedule","data":"Notification delivery depends on local scheduler being alive","key":"1","section":"frontier"}
F Notification delivery depends on local scheduler being alive
-- @record {"chapter":"schedule","data":"Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs.","key":"0","section":"guidance"}
M neyvia-reference "Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs." src:"authored manual" state:verified
-- @record {"chapter":"schedule","data":"For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread.","key":"1","section":"guidance"}
M neyvia-reference "For verify-retained-status, take index from the latest list and match exact id first. For watches index is within the first default page; use watch.list offset/limit to inspect older pages directly. Status changes between reads correctly fail the expectation and require reread." src:"authored manual" state:verified
L neyvia-reference.time v1 -- time
-- @record {"chapter":"time","data":{"args":{},"inputs":{"$cl_type":"t17"},"shape":{"$cl_type":"t18"},"tool":"neyvia.time.now"},"key":"current","section":"state"}
S neyvia-reference.current:json:"{\"type\":\"object\"}"=neyvia.time.now()
-- @record {"chapter":"time","data":{"effect":"Return precise UTC/local ISO timestamps and Unix seconds","pre":"System clock available","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.time.now","tool":"neyvia.time.now"},"key":"time.now","section":"actions"}
A neyvia.time.now() -> json:"{\"type\":\"object\"}" -- Return precise UTC/local ISO timestamps and Unix seconds
F verify-time-now "No authored observer check is bound to neyvia.time.now" -> ask operator blocks:neyvia.time.now
-- @record {"chapter":"time","data":{"effect":"Return advisory deadline risk and verification reserve; never stop agent work","pre":"Optional deadline has explicit timezone; estimates/reserve nonnegative","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.time.budget","tool":"neyvia.time.budget"},"key":"time.budget","section":"actions"}
A neyvia.time.budget(deadlineAt?:str estimatedNextSeconds?:json:"{\"type\":\"number\",\"minimum\":0}" verificationReserveSeconds?:json:"{\"type\":\"number\",\"minimum\":0}" optional?:bool) -> json:"{\"type\":\"object\"}" -- Return advisory deadline risk and verification reserve; never stop agent work
F verify-time-budget "No authored observer check is bound to neyvia.time.budget" -> ask operator blocks:neyvia.time.budget
-- @record {"chapter":"time","data":{"effect":"Persist one checkpoint and interval measurement; exact retry replays saved lap","pre":"Existing running timer with <1000 laps; stable lapId <=160 chars and label 1–200; repeated lapId must match intent","returns":{"$cl_type":"t18"},"reversible":false,"schema":"neyvia.timer.lap","tool":"neyvia.timer.lap"},"key":"timer.lap","section":"actions"}
A neyvia.timer.lap(id:str lapId:str label:str phase?:json:"{\"type\":\"string\",\"enum\":[\"planning\",\"execution\",\"verification\",\"review\",\"other\"]}") -> json:"{\"type\":\"object\"}" ! -- Persist one checkpoint and interval measurement; exact retry replays saved lap
F verify-timer-lap "No authored observer check is bound to neyvia.timer.lap" -> ask operator blocks:neyvia.timer.lap
-- @record {"chapter":"time","data":{"effect":"Read paged timer inventory with explicit nextOffset","pre":"status running/stopped/all; offset >=0, limit 1–100","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.timer.list","tool":"neyvia.timer.list"},"key":"timer.list","section":"actions"}
A neyvia.timer.list(status?:json:"{\"type\":\"string\",\"enum\":[\"running\",\"stopped\",\"all\"]}" offset?:0.. limit?:1..100) -> json:"{\"type\":\"object\"}" -- Read paged timer inventory with explicit nextOffset
F verify-timer-list "No authored observer check is bound to neyvia.timer.list" -> ask operator blocks:neyvia.timer.list
-- @record {"chapter":"time","data":{"effect":"Read elapsed measurement and paged laps; restarted-process values marked wall_clock_recovered_estimate","pre":"Existing timer ID; offset >=0, limit 1–100","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.timer.read","tool":"neyvia.timer.read"},"key":"timer.read","section":"actions"}
A neyvia.timer.read(id:str offset?:0.. limit?:1..100) -> json:"{\"type\":\"object\"}" -- Read elapsed measurement and paged laps; restarted-process values marked wall_clock_recovered_estimate
F verify-timer-read "No authored observer check is bound to neyvia.timer.read" -> ask operator blocks:neyvia.timer.read
-- @record {"chapter":"time","data":{"effect":"Persist running elapsed timer; same intent replays, stopped ID cannot restart a new measurement","pre":"ID nonblank <=160 chars; label 1–200 chars; positive finite targetSeconds; existing ID must match label/phase/target","returns":{"$cl_type":"t18"},"reversible":false,"schema":"neyvia.timer.start","tool":"neyvia.timer.start"},"key":"timer.start","section":"actions"}
A neyvia.timer.start(id:str label:str phase?:json:"{\"type\":\"string\",\"enum\":[\"planning\",\"execution\",\"verification\",\"review\",\"other\"]}" targetSeconds?:json:"{\"type\":\"number\",\"exclusiveMinimum\":0}") -> json:"{\"type\":\"object\"}" ! -- Persist running elapsed timer; same intent replays, stopped ID cannot restart a new measurement
C neyvia.timer.start timer-running:neyvia.timer.read(id:id) .timer.status == "running"
-- @record {"chapter":"time","data":{"effect":"Persist stopped measurement; repeat stop replays it; never cancel associated work","pre":"Existing timer ID","returns":{"$cl_type":"t18"},"reversible":false,"schema":"neyvia.timer.stop","tool":"neyvia.timer.stop"},"key":"timer.stop","section":"actions"}
A neyvia.timer.stop(id:str) -> json:"{\"type\":\"object\"}" ! -- Persist stopped measurement; repeat stop replays it; never cancel associated work
C neyvia.timer.stop timer-stopped:neyvia.timer.read(id:id) .timer.status == "stopped"
-- @record {"chapter":"time","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"timer.status","value":"running"},"tool":"neyvia.timer.read"},"key":"timer-running","section":"checks"}
C neyvia.timer.read timer-running:neyvia.timer.read(id:id) .timer.status == "running"
-- @record {"chapter":"time","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"timer.status","value":"stopped"},"tool":"neyvia.timer.read"},"key":"timer-stopped","section":"checks"}
C neyvia.timer.read timer-stopped:neyvia.timer.read(id:id) .timer.status == "stopped"
-- @record {"chapter":"time","data":{"goal":"Start a distinct elapsed-work measurement and verify running state","inputs":{"$cl_type":"t29"},"steps":[{"action":"timer.start","args":{"id":{"$input":"id"},"label":{"$input":"label"}},"check":"timer-running","save":"started"}]},"key":"start-timer","section":"procedures"}
P start-timer(id:str label:str):started=neyvia.timer.start(id:id label:label) C timer-running -- Start a distinct elapsed-work measurement and verify running state
V P start-timer -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"time","data":{"goal":"Read elapsed timer, decide checkpoint, then record one lap and stop","inputs":{"$cl_type":"t30"},"steps":[{"action":"timer.read","args":{"id":{"$input":"id"}},"save":"before"},{"judge":"checkpoint"},{"action":"timer.lap","args":{"id":{"$input":"id"},"label":{"$input":"label"},"lapId":{"$input":"lapId"}},"save":"lap","when":{"judge":"checkpoint","option":"lap-stop"}},{"action":"timer.stop","args":{"id":{"$input":"id"}},"check":"timer-stopped","save":"stopped","when":{"judge":"checkpoint","option":"lap-stop"}}]},"key":"lap-and-stop","section":"procedures"}
P lap-and-stop(id:str lapId:str label:str):before=neyvia.timer.read(id:id); J checkpoint=lap-stop; lap=neyvia.timer.lap(id:id label:label lapId:lapId); stopped=neyvia.timer.stop(id:id) C timer-stopped -- Read elapsed timer, decide checkpoint, then record one lap and stop
V P lap-and-stop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"time","data":{"constraints":"Timer is elapsed time, not CPU/provider cost. Stop only measurement; it does not cancel work. A stopped ID cannot be reused for a new timing intent.","options":["lap-stop","keep-running"],"question":"Record this completed checkpoint and stop measurement?"},"key":"checkpoint","section":"judge"}
J checkpoint lap-stop|keep-running:"Record this completed checkpoint and stop measurement?" -- Timer is elapsed time, not CPU/provider cost. Stop only measurement; it does not cancel work. A stopped ID cannot be reused for a new timing intent.
V J checkpoint -> human:operator why:"explicit choice required"
-- @record {"chapter":"time","data":{"failure":"Timer ID/lapId reused with different intent","recovery":"Use new ID for new measurement; exact retries replay retained values"},"key":"0","section":"pitfalls"}
X Timer ID/lapId reused with different intent -> Use new ID for new measurement; exact retries replay retained values
-- @record {"chapter":"time","data":{"failure":"Timer spans backend restart","recovery":"Report clockBasis=wall_clock_recovered_estimate and clockAnomaly; do not call it monotonic precision"},"key":"1","section":"pitfalls"}
X Timer spans backend restart -> Report clockBasis=wall_clock_recovered_estimate and clockAnomaly; do not call it monotonic precision
-- @record {"chapter":"time","data":{"failure":"Advisory target exceeded","recovery":"Continue required work or report real blocker; timer does not stop it"},"key":"2","section":"pitfalls"}
X Advisory target exceeded -> Continue required work or report real blocker; timer does not stop it
-- @record {"chapter":"time","data":{"failure":"A lap is attempted on stopped timer or beyond 1000 laps","recovery":"Start a distinct timer for next measurement; retain old evidence"},"key":"3","section":"pitfalls"}
X A lap is attempted on stopped timer or beyond 1000 laps -> Start a distinct timer for next measurement; retain old evidence
-- @record {"chapter":"time","data":"No provider cost or CPU-time accounting in elapsed timers","key":"0","section":"frontier"}
F No provider cost or CPU-time accounting in elapsed timers
-- @record {"chapter":"time","data":"Wall clock across restarts may change; do not use as calibrated performance benchmark","key":"1","section":"frontier"}
F Wall clock across restarts may change; do not use as calibrated performance benchmark
-- @record {"chapter":"time","data":"Source: src/grant_agent/neyvia_time_tools.py; seconds targets and deadline risk are advisory.","key":"0","section":"guidance"}
M neyvia-reference "Source: src/grant_agent/neyvia_time_tools.py; seconds targets and deadline risk are advisory." src:"authored manual" state:verified
-- @record {"chapter":"time","data":"Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs.","key":"1","section":"guidance"}
M neyvia-reference "Source: src/grant_agent/neyvia_time_tools.py, neyvia_workspace_tools.py schedule, neyvia_missions.py, neyvia_run_watches.py, neyvia_attention.py; scripts/verify-manual-first.mjs." src:"authored manual" state:verified
