CL 1
L nightshift v1 -- Authored executable manual
T realbugs0 json:"{\"type\":\"object\"}"
T realbugs1 {id:str ..}
-- @manual {"chapters":{"board":{"title":"The Night Shift board in the Canopy: chain tasks, tick with evidence, set the night budget"},"fixcl3-local":{"title":"Exact retained local admission and supervision"},"overview":{"title":"Night Shift task tree, budgets and morning evidence"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"realbugs-lifecycle":{"title":"Task-matching completion evidence before Done"},"filmbugs":{"title":"Launch film behavior contracts"}},"clVersion":"1.1","id":"nightshift","kind":"workflow","proofs":{"area":"proofs-e-models","manifests":["config/proofs/proofs-e-models.json","config/proofs/nightshift-journey.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.nightshift.begin":"t1","neyvia.nightshift.block":"t2","neyvia.nightshift.create":"t3","neyvia.nightshift.edit":"t4","neyvia.nightshift.import":"t5","neyvia.nightshift.reparent":"t6","neyvia.nightshift.resources":"t7","neyvia.nightshift.start":"t8","neyvia.nightshift.stop":"t9","neyvia.nightshift.summary":"t1","neyvia.nightshift.task":"t9","neyvia.nightshift.tasks":"t1","neyvia.nightshift.tick":"t10","neyvia.pane.show":"live_schema_25","neyvia.state":"t1","proofs-e-models.status":"t1","realbugs_summary":"realbugs0","realbugs_task":"realbugs1"},"tool_metadata":{"neyvia.nightshift.begin":{"mutability_class":"none"},"neyvia.nightshift.block":{"mutability_class":"none"},"neyvia.nightshift.create":{"mutability_class":"none"},"neyvia.nightshift.edit":{"mutability_class":"none"},"neyvia.nightshift.import":{"mutability_class":"none"},"neyvia.nightshift.reparent":{"mutability_class":"none"},"neyvia.nightshift.resources":{"mutability_class":"none"},"neyvia.nightshift.start":{"mutability_class":"none"},"neyvia.nightshift.stop":{"mutability_class":"none"},"neyvia.nightshift.summary":{"mutability_class":"none"},"neyvia.nightshift.task":{"mutability_class":"none"},"neyvia.nightshift.tasks":{"mutability_class":"none"},"neyvia.nightshift.tick":{"mutability_class":"none"},"neyvia.pane.show":{"mutability_class":"none"},"neyvia.verify.status":{"mutability_class":"none"}}}
-- @proof {"id":"nightshift.claude-session-usage","phase":"invariant","claim":"Claude terminal attempts publish live cumulative token usage from Usage transcript records, counting streamed message IDs once and including helper sessions, cache reads and writes. Saved unknown finished attempts recover only from their persisted session and started/finished run window; unavailable measurements stay unknown.","checkedAt":["grant_agent.connected_sessions.claude_usage.ClaudeTranscriptUsage.poll","grant_agent.nightshift_ledger.recover_claude_usage","grant_agent.usage_report.claude_usage_entry"],"impact":["Launch film behavior"]}
T live_schema_25 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str ..}
T live_schema_24 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:shapeBoard -> checkedProofsEModel"],"claim":"Board excludes missions by default, retains dependency/missing/open/dependent edges and exact state counts","id":"nightshift.shapeBoard","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:startable -> checkedProofsEModel"],"claim":"Only waiting, unarmed agent tasks can be armed; Paul's tasks are always excluded","id":"nightshift.startable","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:evidenceView -> checkedProofsEModel"],"claim":"Evidence retains its actual path, commit, run ids or owner-only command; labels disclose opening meaning","id":"nightshift.evidenceView","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:morning -> checkedProofsEModel"],"claim":"Morning summary counts only completed unreported runs and non-mission tasks; actual evidence links take precedence","id":"nightshift.morning","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:quietNow -> checkedProofsEModel"],"claim":"Quiet windows are start-inclusive/end-exclusive in selected local/UTC clock; midnight wraps and equal endpoints mean all day","id":"nightshift.quietNow","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["scripts/p22_nightshift_journey.mjs","web/src/neyvia/next/NxNightShift.jsx","web/src/neyvia/next/NxNightShiftParts.jsx","web/src/neyvia/next/nxNightShiftApi.js","web/src/neyvia/next/nxNightShiftModel.js","src/grant_agent/neyvia_nightshift.py"],"claim":"On an owned local backend, the mounted production Night Shift saves finite night, concurrency, per-task, plan-hold and GPU quiet-hour limits; a newly added GPU task remains waiting and unarmed, with no run or completion evidence until the owner explicitly starts it.","id":"p22.nightshift.local-policy-ui-journey","impact": ["Night Shift resource limits and GPU quiet hours","New tasks wait for explicit start without fake completion evidence"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:treeLayout -> checkedProofsEModel"],"claim":"Every board task gets one measured leaf on its prerequisite branch with exact geometry and alternate sides without invented tasks","id":"nightshift.treeLayout","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:policyForm -> checkedProofsEModel"],"claim":"Saved policy fields convert measured seconds to one-decimal hours/minutes; toggles retain quiet/GPU/plan hold state and harness budgets","id":"nightshift.policyForm","impact":["nightshift frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxNightShiftModel.js:policyPatch -> checkedProofsEModel"],"claim":"Budget patches convert valid fields to positive integer units and report every invalid count/time/OpenCode token budget","id":"nightshift.policyPatch","impact":["nightshift frontend model consumers"],"phase":"post"}
T t1{..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"}},\"required\":[\"id\",\"reason\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"reason\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"owner\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"harness\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"transport\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"requiresGpu\":{\"type\":\"boolean\"},\"limits\":{\"type\":\"object\"},\"completionEvidence\":{\"type\":\"object\"}},\"required\":[\"prompt\"],\"allOf\":[{\"properties\":{\"prompt\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t4 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"patch\":{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"owner\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"harness\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"transport\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"requiresGpu\":{\"type\":\"boolean\"},\"limits\":{\"type\":\"object\"},\"completionEvidence\":{\"type\":\"object\"}},\"additionalProperties\":false},\"expectedUpdatedAt\":{\"type\":\"string\"}},\"required\":[\"id\",\"patch\",\"expectedUpdatedAt\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"expectedUpdatedAt\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{text?:str path?:str folder?:str folders?:json:"{\"type\":\"object\"}" defaults?:json:"{\"type\":\"object\"}" ..}
T t6 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"expectedUpdatedAt\":{\"type\":\"string\"}},\"required\":[\"id\",\"needs\",\"expectedUpdatedAt\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}},\"expectedUpdatedAt\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7{maxConcurrent?:int|null maxTaskSeconds?:int|null maxTaskTokens?:int|null maxNightSeconds?:int|null holdAtPlanPercent?:int|null paused?:bool perHarness?:json:"{\"type\":\"object\"}" perHarnessBudgets?:json:"{\"type\":\"object\"}" gpuReservedFor?:str|null quietGpuHours?:json:"{\"type\":[\"object\",\"null\"]}" ..}
T t8{ids:[str] ..}
T t9 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t10 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"evidence\":{\"type\":\"object\"}},\"required\":[\"id\",\"evidence\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t11{kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
T t12{}
T t13 json:"{\"type\":\"object\"}"
T t14{id:str ..}
T t15 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"updatedAt\":{\"type\":\"string\"},\"armed\":{\"type\":\"boolean\"},\"status\":{\"type\":\"string\"}},\"required\":[\"id\",\"updatedAt\",\"armed\",\"status\",\"title\",\"needs\"]}"
T t16{nightSeconds:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1}" holdPercent:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1,\"maximum\":100}"}
T t17{id:str title:str ..}
T t18{id:str needs:[str] ..}
T t19{id:str#1.. prompt:str#1.. folder:str#1.. harness:str#1.. model:str#1..}
T t20{text:str#1.. folder:str#1..}
T t21{id:str#1.. reason:str#1..}
T t22{ok:bool ..}
T t23 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L nightshift.board v1 -- The Night Shift board in the Canopy: chain tasks, tick with evidence, set the night budget
-- @record {"chapter":"board","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t13"},"tool":"neyvia.nightshift.tasks"},"key":"board","section":"state"}
S nightshift.board:json:"{\"type\":\"object\"}"=neyvia.nightshift.tasks()
-- @record {"chapter":"board","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t13"},"tool":"neyvia.nightshift.summary"},"key":"morning","section":"state"}
S nightshift.morning:json:"{\"type\":\"object\"}"=neyvia.nightshift.summary()
-- @record {"chapter":"board","data":{"args":{"id":{"$input":"id"}},"inputs":{"$cl_type":"t14"},"shape":{"$cl_type":"t15"},"tool":"neyvia.nightshift.task"},"key":"task","section":"state"}
S nightshift.task:json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"updatedAt\":{\"type\":\"string\"},\"armed\":{\"type\":\"boolean\"},\"status\":{\"type\":\"string\"}},\"required\":[\"id\",\"updatedAt\",\"armed\",\"status\",\"title\",\"needs\"]}"=neyvia.nightshift.task(id:id)
-- @record {"chapter":"board","data":{"effect":"Open the Night Shift board (mission pane, target nightshift) on Paul's stage","pre":"A Neyvia window is connected to this backend","returns":{"type":"object"},"reversible":true,"schema":"neyvia.pane.show","tool":"neyvia.pane.show"},"key":"pane.show","section":"actions"}
A neyvia.pane.show(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str) -> json:"{\"type\":\"object\"}" ! -- Open the Night Shift board (mission pane, target nightshift) on Paul's stage
C neyvia.pane.show board-open: neyvia.state().pane.kind=="mission"
-- @record {"chapter":"board","data":{"effect":"Store a dormant task; needs are task IDs. Nothing runs until explicitly started.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.create","tool":"neyvia.nightshift.create"},"key":"nightshift.create","section":"actions"}
A neyvia.nightshift.create(id?:str title?:str prompt:str owner?:str folder?:str harness?:str model?:str effort?:str permissionMode?:str transport?:str needs?:[str] requiresGpu?:bool limits?:json:"{\"type\":\"object\"}" completionEvidence?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Store a dormant task; needs are task IDs. Nothing runs until explicitly started.
F verify-nightshift-create "No authored observer check is bound to neyvia.nightshift.create" -> ask operator blocks:neyvia.nightshift.create
-- @record {"chapter":"board","data":{"effect":"Arm explicit task IDs under approved prompts/routes, prerequisites and saved resource policy.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":false,"schema":"neyvia.nightshift.start","tool":"neyvia.nightshift.start"},"key":"nightshift.start","section":"actions"}
A neyvia.nightshift.start(ids:[str]) -> json:"{\"type\":\"object\"}" -- Arm explicit task IDs under approved prompts/routes, prerequisites and saved resource policy.
F verify-nightshift-start "No authored observer check is bound to neyvia.nightshift.start" -> ask operator blocks:neyvia.nightshift.start
-- @record {"chapter":"board","data":{"effect":"Complete a task with checked file, commit or its own completed run evidence; releases armed dependents.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":false,"schema":"neyvia.nightshift.tick","tool":"neyvia.nightshift.tick"},"key":"nightshift.tick","section":"actions"}
A neyvia.nightshift.tick(id:str evidence:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Complete a task with checked file, commit or its own completed run evidence; releases armed dependents.
F verify-nightshift-tick "No authored observer check is bound to neyvia.nightshift.tick" -> ask operator blocks:neyvia.nightshift.tick
-- @record {"chapter":"board","data":{"effect":"Read resource policy or request an owner-approved patch. Token limits use reported transport usage.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.resources","tool":"neyvia.nightshift.resources"},"key":"nightshift.resources","section":"actions"}
A neyvia.nightshift.resources(maxConcurrent?:int|null maxTaskSeconds?:int|null maxTaskTokens?:int|null maxNightSeconds?:int|null holdAtPlanPercent?:int|null paused?:bool perHarness?:json:"{\"type\":\"object\"}" perHarnessBudgets?:json:"{\"type\":\"object\"}" gpuReservedFor?:str|null quietGpuHours?:json:"{\"type\":[\"object\",\"null\"]}") -> json:"{\"type\":\"object\"}" -- Read resource policy or request an owner-approved patch. Token limits use reported transport usage.
C neyvia.nightshift.resources plan-hold:neyvia.nightshift.resources() .holdAtPlanPercent == holdPercent
-- @record {"chapter":"board","data":{"effect":"Read morning evidence, blockers, waiting on Paul, measured time and token coverage.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.summary","tool":"neyvia.nightshift.summary"},"key":"nightshift.summary","section":"actions"}
A neyvia.nightshift.summary() -> json:"{\"type\":\"object\"}" -- Read morning evidence, blockers, waiting on Paul, measured time and token coverage.
F verify-nightshift-summary "No authored observer check is bound to neyvia.nightshift.summary" -> ask operator blocks:neyvia.nightshift.summary
-- @record {"chapter":"board","data":{"effect":"Observe one saved task before editing or checking its result.","pre":"Use the current updatedAt of a dormant task with no harness attempt or completion evidence","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.nightshift.task","tool":"neyvia.nightshift.task"},"key":"task","section":"actions"}
A neyvia.nightshift.task(id:str) -> json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"updatedAt\":{\"type\":\"string\"},\"armed\":{\"type\":\"boolean\"},\"status\":{\"type\":\"string\"}},\"required\":[\"id\",\"updatedAt\",\"armed\",\"status\",\"title\",\"needs\"]}" -- Observe one saved task before editing or checking its result.
C neyvia.nightshift.task edit-disarmed:neyvia.nightshift.task(id:id) .armed == false
-- @record {"chapter":"board","data":{"effect":"Edit a dormant unattempted task with its observed updatedAt; disarms it until explicitly started again.","pre":"Use the current updatedAt of a dormant task with no harness attempt or completion evidence","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.nightshift.edit","tool":"neyvia.nightshift.edit"},"key":"edit","section":"actions"}
A neyvia.nightshift.edit(id:str patch:json:"{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"owner\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"harness\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"effort\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"transport\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"requiresGpu\":{\"type\":\"boolean\"},\"limits\":{\"type\":\"object\"},\"completionEvidence\":{\"type\":\"object\"}},\"additionalProperties\":false}" expectedUpdatedAt:str) -> json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"updatedAt\":{\"type\":\"string\"},\"armed\":{\"type\":\"boolean\"},\"status\":{\"type\":\"string\"}},\"required\":[\"id\",\"updatedAt\",\"armed\",\"status\",\"title\",\"needs\"]}" -- Edit a dormant unattempted task with its observed updatedAt; disarms it until explicitly started again.
C neyvia.nightshift.edit title-saved:neyvia.nightshift.task(id:id) .title == title
-- @record {"chapter":"board","data":{"effect":"Replace dormant task prerequisites; missing tasks and dependency cycles are refused; disarms the task.","pre":"Use the current updatedAt of a dormant task with no harness attempt or completion evidence","returns":{"$cl_type":"t15"},"reversible":true,"schema":"neyvia.nightshift.reparent","tool":"neyvia.nightshift.reparent"},"key":"reparent","section":"actions"}
A neyvia.nightshift.reparent(id:str needs:[str] expectedUpdatedAt:str) -> json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"needs\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"updatedAt\":{\"type\":\"string\"},\"armed\":{\"type\":\"boolean\"},\"status\":{\"type\":\"string\"}},\"required\":[\"id\",\"updatedAt\",\"armed\",\"status\",\"title\",\"needs\"]}" ! -- Replace dormant task prerequisites; missing tasks and dependency cycles are refused; disarms the task.
C neyvia.nightshift.reparent needs-saved:neyvia.nightshift.task(id:id) .needs == needs
-- @record {"chapter":"board","data":{"args":{},"expect":{"op":"eq","path":"pane.kind","value":"mission"},"tool":"neyvia.state"},"key":"board-open","section":"checks"}
C neyvia.state board-open:neyvia.state() .pane.kind == "mission"
-- @record {"chapter":"board","data":{"args":{},"expect":{"op":"eq","path":"holdAtPlanPercent","value":{"$input":"holdPercent"}},"tool":"neyvia.nightshift.resources"},"key":"plan-hold","section":"checks"}
C neyvia.nightshift.resources plan-hold:neyvia.nightshift.resources() .holdAtPlanPercent == holdPercent
-- @record {"chapter":"board","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"title","value":{"$input":"title"}},"tool":"neyvia.nightshift.task"},"key":"title-saved","section":"checks"}
C neyvia.nightshift.task title-saved:neyvia.nightshift.task(id:id) .title == title
-- @record {"chapter":"board","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"needs","value":{"$input":"needs"}},"tool":"neyvia.nightshift.task"},"key":"needs-saved","section":"checks"}
C neyvia.nightshift.task needs-saved:neyvia.nightshift.task(id:id) .needs == needs
-- @record {"chapter":"board","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"armed","value":false},"tool":"neyvia.nightshift.task"},"key":"edit-disarmed","section":"checks"}
C neyvia.nightshift.task edit-disarmed:neyvia.nightshift.task(id:id) .armed == false
-- @record {"chapter":"board","data":{"goal":"Show Paul the Night Shift board","inputs":{"$cl_type":"t12"},"steps":[{"action":"pane.show","args":{"kind":"mission","target":"nightshift"},"check":"board-open","save":"shown"}]},"key":"open-board","section":"procedures"}
P open-board():shown=neyvia.pane.show(kind:"mission" target:"nightshift") C board-open -- Show Paul the Night Shift board
V P open-board -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"board","data":{"goal":"Cap the night's wall time and hold Codex and Claude launches at a plan-limit share","inputs":{"$cl_type":"t16"},"steps":[{"action":"nightshift.resources","args":{"holdAtPlanPercent":{"$input":"holdPercent"},"maxNightSeconds":{"$input":"nightSeconds"}},"check":"plan-hold","save":"policy"}]},"key":"night-budget","section":"procedures"}
P night-budget(nightSeconds:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1}" holdPercent:json:"{\"type\":[\"integer\",\"null\"],\"minimum\":1,\"maximum\":100}"):policy=neyvia.nightshift.resources(holdAtPlanPercent:holdPercent maxNightSeconds:nightSeconds) C plan-hold -- Cap the night's wall time and hold Codex and Claude launches at a plan-limit share
V P night-budget -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"board","data":{"goal":"Save the requested dormant task change and independently observe it disarmed","inputs":{"$cl_type":"t17"},"steps":[{"action":"task","args":{"id":{"$input":"id"}},"save":"before"},{"action":"edit","args":{"expectedUpdatedAt":{"$result":"before.updatedAt"},"id":{"$input":"id"},"patch":{"title":{"$input":"title"}}},"check":"title-saved","save":"changed"},{"action":"task","args":{"id":{"$input":"id"}},"check":"edit-disarmed","save":"after"}]},"key":"edit-task-title","section":"procedures"}
P edit-task-title(id:str title:str):before=neyvia.nightshift.task(id:id); changed=neyvia.nightshift.edit(expectedUpdatedAt:before.updatedAt id:id patch:{title:title}) C title-saved; after=neyvia.nightshift.task(id:id) C edit-disarmed -- Save the requested dormant task change and independently observe it disarmed
V P edit-task-title -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"board","data":{"goal":"Save the requested dormant task change and independently observe it disarmed","inputs":{"$cl_type":"t18"},"steps":[{"action":"task","args":{"id":{"$input":"id"}},"save":"before"},{"action":"reparent","args":{"expectedUpdatedAt":{"$result":"before.updatedAt"},"id":{"$input":"id"},"needs":{"$input":"needs"}},"check":"needs-saved","save":"changed"},{"action":"task","args":{"id":{"$input":"id"}},"check":"edit-disarmed","save":"after"}]},"key":"reparent-task","section":"procedures"}
P reparent-task(id:str needs:[str]):before=neyvia.nightshift.task(id:id); changed=neyvia.nightshift.reparent(expectedUpdatedAt:before.updatedAt id:id needs:needs) C needs-saved; after=neyvia.nightshift.task(id:id) C edit-disarmed -- Save the requested dormant task change and independently observe it disarmed
V P reparent-task -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"board","data":{"constraints":"Start only when Paul asked for the work to run; a bot start also needs his approval. hold leaves both stored, dormant, visible on the board.","options":["start","hold"],"question":"Should these tasks be armed now, with these prompts, routes and the saved budget?"},"key":"arm-now","section":"judge"}
J arm-now start|hold:"Should these tasks be armed now, with these prompts, routes and the saved budget?" -- Start only when Paul asked for the work to run; a bot start also needs his approval. hold leaves both stored, dormant, visible on the board.
V J arm-now -> human:operator why:"explicit choice required"
-- @record {"chapter":"board","data":{"failure":"A dependent was created without its prerequisite (needs empty)","recovery":"Use nightshift.reparent with current expectedUpdatedAt. Edits disarm dormant tasks and refuse missing dependencies, cycles, running tasks and recorded attempts."},"key":"0","section":"pitfalls"}
X A dependent was created without its prerequisite (needs empty) -> Use nightshift.reparent with current expectedUpdatedAt. Edits disarm dormant tasks and refuse missing dependencies, cycles, running tasks and recorded attempts.
-- @record {"chapter":"board","data":{"failure":"Codex task that writes files stalls at launch on Windows","recovery":"Seen 2 Oct: codex-windows-sandbox-setup.exe stayed running and the run never started (likely a one-time elevated sandbox setup Paul must accept). Stop it from the board; until set up, use read-only prompts that answer in the reply and tick with run evidence"},"key":"1","section":"pitfalls"}
X Codex task that writes files stalls at launch on Windows -> Seen 2 Oct: codex-windows-sandbox-setup.exe stayed running and the run never started (likely a one-time elevated sandbox setup Paul must accept). Stop it from the board; until set up, use read-only prompts that answer in the reply and tick with run evidence
-- @record {"chapter":"board","data":{"failure":"Start all left a blocked task alone","recovery":"Blocked tasks restart one at a time from the board (Start again) after reading why"},"key":"2","section":"pitfalls"}
X Start all left a blocked task alone -> Blocked tasks restart one at a time from the board (Start again) after reading why
-- @record {"chapter":"board","data":{"failure":"Morning card shows a run that did not report tokens","recovery":"Its tokens are unknown, not zero; a harness token budget holds further launches until a new night"},"key":"3","section":"pitfalls"}
X Morning card shows a run that did not report tokens -> Its tokens are unknown, not zero; a harness token budget holds further launches until a new night
-- @record {"chapter":"board","data":"The board draws prerequisites as lines on desktop; on phone the columns stack and the lines are hidden","key":"0","section":"frontier"}
F The board draws prerequisites as lines on desktop; on phone the columns stack and the lines are hidden
-- @record {"chapter":"board","data":"Plan-limit percentages come from the agents dashboard; Claude reports them only during a turn Neyvia runs","key":"1","section":"frontier"}
F Plan-limit percentages come from the agents dashboard; Claude reports them only during a turn Neyvia runs
-- @record {"chapter":"board","data":"UI: Canopy > Missions pane > Night Shift tab (pane.show kind mission, target nightshift; launcher 'Night Shift'; strip Night Shift > Open the board; Home widget; Grove rail).","key":"0","section":"guidance"}
M nightshift "UI: Canopy > Missions pane > Night Shift tab (pane.show kind mission, target nightshift; launcher 'Night Shift'; strip Night Shift > Open the board; Home widget; Grove rail)." src:"authored manual" state:verified
-- @record {"chapter":"board","data":"Board: morning card with the growing tree (one leaf per task; full green leaf = done with evidence; amber = running; red = blocked; gold = waiting on Paul), then columns First / Then (n) with lines from each prerequisite.","key":"1","section":"guidance"}
M nightshift "Board: morning card with the growing tree (one leaf per task; full green leaf = done with evidence; amber = running; red = blocked; gold = waiting on Paul), then columns First / Then (n) with lines from each prerequisite." src:"authored manual" state:verified
-- @record {"chapter":"board","data":"Task panel: Start / Start again, Stop, Mark done (evidence: agent run, file, commit, or a command Paul vouches for), Block with a reason. Add task and Import TASKS.md never start anything.","key":"2","section":"guidance"}
M nightshift "Task panel: Start / Start again, Stop, Mark done (evidence: agent run, file, commit, or a command Paul vouches for), Block with a reason. Add task and Import TASKS.md never start anything." src:"authored manual" state:verified
-- @record {"chapter":"board","data":"Budget panel: pause, hours per night, tasks at once, minutes and tokens per task, per-agent tokens and hours, plan hold (default 70%), keep GPU for dictation, quiet GPU hours.","key":"3","section":"guidance"}
M nightshift "Budget panel: pause, hours per night, tasks at once, minutes and tokens per task, per-agent tokens and hours, plan hold (default 70%), keep GPU for dictation, quiet GPU hours." src:"authored manual" state:verified
-- @record {"chapter":"board","data":"New night starts a fresh budget period only when nothing runs; history and evidence stay.","key":"4","section":"guidance"}
M nightshift "New night starts a fresh budget period only when nothing runs; history and evidence stay." src:"authored manual" state:verified
-- @record {"chapter":"board","data":"Dormant unattempted tasks can be edited or reparented by tools/commands with expectedUpdatedAt. Active, completed and attempted task records stay immutable. Editing disarms the task; explicitly start it again after reviewing the new graph. Select a dormant task and choose Edit task to update its title, prompt and prerequisites. Save changes writes the graph atomically and disarms the task. If someone else changes it, cancel and reopen Edit task to review the current version.","key":"5","section":"guidance"}
M nightshift "Dormant unattempted tasks can be edited or reparented by tools/commands with expectedUpdatedAt. Active, completed and attempted task records stay immutable. Editing disarms the task; explicitly start it again after reviewing the new graph. Select a dormant task and choose Edit task to update its title, prompt and prerequisites. Save changes writes the graph atomically and disarms the task. If someone else changes it, cancel and reopen Edit task to review the current version." src:"authored manual" state:verified
L nightshift.fixcl3-local v1 -- Exact retained local admission and supervision
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained nightshift.start","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.start","tool":"neyvia.nightshift.start"},"key":"neyvia.nightshift.start","section":"actions"}
A neyvia.nightshift.start(ids:[str]) -> json:"{\"type\":\"object\"}" -- Exact retained nightshift.start
F verify-neyvia-nightshift-start "No authored observer check is bound to neyvia.nightshift.start" -> ask operator blocks:neyvia.nightshift.start
-- @record {"chapter":"fixcl3-local","data":{"effect":"Exact retained nightshift.stop","pre":"Saved disposable/local subject; explicit owner approval for arming or creation; never active provider control","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.stop","tool":"neyvia.nightshift.stop"},"key":"neyvia.nightshift.stop","section":"actions"}
A neyvia.nightshift.stop(id:str) -> json:"{\"type\":\"object\"}" -- Exact retained nightshift.stop
F verify-neyvia-nightshift-stop "No authored observer check is bound to neyvia.nightshift.stop" -> ask operator blocks:neyvia.nightshift.stop
-- @record {"chapter":"fixcl3-local","data":{"failure":"Fresh owner state differs from this action subject","recovery":"Reconcile the specific retained effect; never replay an uncertain launch."},"key":"0","section":"pitfalls"}
X Fresh owner state differs from this action subject -> Reconcile the specific retained effect; never replay an uncertain launch.
-- @record {"chapter":"fixcl3-local","data":"Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.","key":"0","section":"frontier"}
F Admission, arming and local starter bytes do not prove provider execution, rendered preview, device build or installation. Active provider controls require a terminal provider witness.
-- @record {"chapter":"fixcl3-local","data":"CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes.","key":"0","section":"guidance"}
M nightshift "CL completion re-reads the owner and compares the exact task graph, source hash, retained control or starter bytes." src:"authored manual" state:verified
L nightshift.overview v1 -- Night Shift task tree, budgets and morning evidence
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t13"},"tool":"neyvia.nightshift.tasks"},"key":"board","section":"state"}
S nightshift.board:json:"{\"type\":\"object\"}"=neyvia.nightshift.tasks()
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t12"},"shape":{"$cl_type":"t13"},"tool":"neyvia.nightshift.summary"},"key":"morning","section":"state"}
S nightshift.morning:json:"{\"type\":\"object\"}"=neyvia.nightshift.summary()
-- @record {"chapter":"overview","data":{"effect":"Read the saved task graph, evidence and launch reasons.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.tasks","tool":"neyvia.nightshift.tasks"},"key":"nightshift.tasks","section":"actions"}
A neyvia.nightshift.tasks() -> json:"{\"type\":\"object\"}" -- Read the saved task graph, evidence and launch reasons.
F verify-nightshift-tasks "No authored observer check is bound to neyvia.nightshift.tasks" -> ask operator blocks:neyvia.nightshift.tasks
-- @record {"chapter":"overview","data":{"effect":"Store a dormant task; needs are task IDs. Nothing runs until explicitly started.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.create","tool":"neyvia.nightshift.create"},"key":"nightshift.create","section":"actions"}
A neyvia.nightshift.create(id?:str title?:str prompt:str owner?:str folder?:str harness?:str model?:str effort?:str permissionMode?:str transport?:str needs?:[str] requiresGpu?:bool limits?:json:"{\"type\":\"object\"}" completionEvidence?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Store a dormant task; needs are task IDs. Nothing runs until explicitly started.
F verify-nightshift-create "No authored observer check is bound to neyvia.nightshift.create" -> ask operator blocks:neyvia.nightshift.create
-- @record {"chapter":"overview","data":{"effect":"Import TASKS.md dormant; source checkboxes do not count as execution evidence.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.import","tool":"neyvia.nightshift.import"},"key":"nightshift.import","section":"actions"}
A neyvia.nightshift.import(text?:str path?:str folder?:str folders?:json:"{\"type\":\"object\"}" defaults?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Import TASKS.md dormant; source checkboxes do not count as execution evidence.
F verify-nightshift-import "No authored observer check is bound to neyvia.nightshift.import" -> ask operator blocks:neyvia.nightshift.import
-- @record {"chapter":"overview","data":{"effect":"Complete a task with checked file, commit or its own completed run evidence; releases armed dependents.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":false,"schema":"neyvia.nightshift.tick","tool":"neyvia.nightshift.tick"},"key":"nightshift.tick","section":"actions"}
A neyvia.nightshift.tick(id:str evidence:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\"}" -- Complete a task with checked file, commit or its own completed run evidence; releases armed dependents.
F verify-nightshift-tick "No authored observer check is bound to neyvia.nightshift.tick" -> ask operator blocks:neyvia.nightshift.tick
-- @record {"chapter":"overview","data":{"effect":"Arm explicit task IDs under approved prompts/routes, prerequisites and saved resource policy.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":false,"schema":"neyvia.nightshift.start","tool":"neyvia.nightshift.start"},"key":"nightshift.start","section":"actions"}
A neyvia.nightshift.start(ids:[str]) -> json:"{\"type\":\"object\"}" -- Arm explicit task IDs under approved prompts/routes, prerequisites and saved resource policy.
F verify-nightshift-start "No authored observer check is bound to neyvia.nightshift.start" -> ask operator blocks:neyvia.nightshift.start
-- @record {"chapter":"overview","data":{"effect":"Stop an owned task; active repository lock stays until terminal harness state.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.stop","tool":"neyvia.nightshift.stop"},"key":"nightshift.stop","section":"actions"}
A neyvia.nightshift.stop(id:str) -> json:"{\"type\":\"object\"}" ! -- Stop an owned task; active repository lock stays until terminal harness state.
F verify-nightshift-stop "No authored observer check is bound to neyvia.nightshift.stop" -> ask operator blocks:neyvia.nightshift.stop
-- @record {"chapter":"overview","data":{"effect":"Block a non-active task with a reason; completed evidence is immutable.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.block","tool":"neyvia.nightshift.block"},"key":"nightshift.block","section":"actions"}
A neyvia.nightshift.block(id:str reason:str) -> json:"{\"type\":\"object\"}" -- Block a non-active task with a reason; completed evidence is immutable.
F verify-nightshift-block "No authored observer check is bound to neyvia.nightshift.block" -> ask operator blocks:neyvia.nightshift.block
-- @record {"chapter":"overview","data":{"effect":"Read resource policy or request an owner-approved patch. Token limits use reported transport usage.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.resources","tool":"neyvia.nightshift.resources"},"key":"nightshift.resources","section":"actions"}
A neyvia.nightshift.resources(maxConcurrent?:int|null maxTaskSeconds?:int|null maxTaskTokens?:int|null maxNightSeconds?:int|null holdAtPlanPercent?:int|null paused?:bool perHarness?:json:"{\"type\":\"object\"}" perHarnessBudgets?:json:"{\"type\":\"object\"}" gpuReservedFor?:str|null quietGpuHours?:json:"{\"type\":[\"object\",\"null\"]}") -> json:"{\"type\":\"object\"}" -- Read resource policy or request an owner-approved patch. Token limits use reported transport usage.
F verify-nightshift-resources "No authored observer check is bound to neyvia.nightshift.resources" -> ask operator blocks:neyvia.nightshift.resources
-- @record {"chapter":"overview","data":{"effect":"Read morning evidence, blockers, waiting on Paul, measured time and token coverage.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":true,"schema":"neyvia.nightshift.summary","tool":"neyvia.nightshift.summary"},"key":"nightshift.summary","section":"actions"}
A neyvia.nightshift.summary() -> json:"{\"type\":\"object\"}" -- Read morning evidence, blockers, waiting on Paul, measured time and token coverage.
C neyvia.nightshift.summary usage-known:neyvia.nightshift.summary() .usage.complete == true
-- @record {"chapter":"overview","data":{"effect":"Begin a fresh explicit night budget period only with no running tasks; preserves history.","pre":"Owner-approved scope; explicit prompts, prerequisites and saved resource policy","returns":{"$cl_type":"t13"},"reversible":false,"schema":"neyvia.nightshift.begin","tool":"neyvia.nightshift.begin"},"key":"nightshift.begin","section":"actions"}
A neyvia.nightshift.begin() -> json:"{\"type\":\"object\"}" -- Begin a fresh explicit night budget period only with no running tasks; preserves history.
F verify-nightshift-begin "No authored observer check is bound to neyvia.nightshift.begin" -> ask operator blocks:neyvia.nightshift.begin
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"usage.complete","value":true},"tool":"neyvia.nightshift.summary"},"key":"usage-known","section":"checks"}
C neyvia.nightshift.summary usage-known:neyvia.nightshift.summary() .usage.complete == true
-- @record {"chapter":"overview","data":{"goal":"Observe real evidence and measured usage before reviewing completion","inputs":{"$cl_type":"t12"},"steps":[{"action":"nightshift.summary","args":{},"check":"usage-known","save":"morning"},{"judge":"acceptance"}]},"key":"read-morning","section":"procedures"}
P read-morning():morning=neyvia.nightshift.summary() C usage-known; J acceptance -- Observe real evidence and measured usage before reviewing completion
V P read-morning -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Store one exact dormant task and read its saved prerequisites","inputs":{"$cl_type":"t19"},"steps":[{"action":"nightshift.create","args":{"folder":{"$input":"folder"},"harness":{"$input":"harness"},"id":{"$input":"id"},"model":{"$input":"model"},"prompt":{"$input":"prompt"}},"save":"stored"}]},"key":"store-task","section":"procedures"}
P store-task(id:str#1.. prompt:str#1.. folder:str#1.. harness:str#1.. model:str#1..):stored=neyvia.nightshift.create(folder:folder harness:harness id:id model:model prompt:prompt) -- Store one exact dormant task and read its saved prerequisites
V P store-task -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Import the selected TASKS.md text as dormant tasks, retaining every prerequisite","inputs":{"$cl_type":"t20"},"steps":[{"action":"nightshift.import","args":{"folder":{"$input":"folder"},"text":{"$input":"text"}},"save":"imported"}]},"key":"import-text","section":"procedures"}
P import-text(text:str#1.. folder:str#1..):imported=neyvia.nightshift.import(folder:folder text:text) -- Import the selected TASKS.md text as dormant tasks, retaining every prerequisite
V P import-text -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Block one saved non-active task with an exact reason","inputs":{"$cl_type":"t21"},"steps":[{"action":"nightshift.block","args":{"id":{"$input":"id"},"reason":{"$input":"reason"}},"save":"blocked"}]},"key":"block-task","section":"procedures"}
P block-task(id:str#1.. reason:str#1..):blocked=neyvia.nightshift.block(id:id reason:reason) -- Block one saved non-active task with an exact reason
V P block-task -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Start a new night budget period after owner approval and observe its saved ID","inputs":{"$cl_type":"t12"},"steps":[{"action":"nightshift.begin","args":{},"save":"night"}]},"key":"begin-night","section":"procedures"}
P begin-night():night=neyvia.nightshift.begin() -- Start a new night budget period after owner approval and observe its saved ID
V P begin-night -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"A completed CLI run proves execution, not output quality. Inspect file hashes, commits and transcript; unknown usage blocks exact token-budget admission.","options":["accept","inspect"],"question":"Do the evidence links satisfy the requested acceptance criteria?"},"key":"acceptance","section":"judge"}
J acceptance accept|inspect:"Do the evidence links satisfy the requested acceptance criteria?" -- A completed CLI run proves execution, not output quality. Inspect file hashes, commits and transcript; unknown usage blocks exact token-budget admission.
V J acceptance -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Checked imported row treated as done","recovery":"Import is dormant; tick with fresh typed file, commit or this task's completed run evidence"},"key":"0","section":"pitfalls"}
X Checked imported row treated as done -> Import is dormant; tick with fresh typed file, commit or this task's completed run evidence
-- @record {"chapter":"overview","data":{"failure":"Interrupted task resent after restart","recovery":"Inspect its saved run; explicit start creates a new accounted attempt"},"key":"1","section":"pitfalls"}
X Interrupted task resent after restart -> Inspect its saved run; explicit start creates a new accounted attempt
-- @record {"chapter":"overview","data":{"failure":"Resource hold mistaken for failure","recovery":"Read summary task reason; approved policy changes or explicit new night release armed work"},"key":"2","section":"pitfalls"}
X Resource hold mistaken for failure -> Read summary task reason; approved policy changes or explicit new night release armed work
-- @record {"chapter":"overview","data":"CLI token caps are enforced at reported usage events and may overshoot between events","key":"0","section":"frontier"}
F CLI token caps are enforced at reported usage events and may overshoot between events
-- @record {"chapter":"overview","data":"GPU policy covers declared requiresGpu tasks; external workloads are not observed","key":"1","section":"frontier"}
F GPU policy covers declared requiresGpu tasks; external workloads are not observed
-- @record {"chapter":"overview","data":"HTTP /api/nightshift and nightshift_<action>_command share SQLite state; desktop commands forward to the persistent authenticated backend","key":"0","section":"guidance"}
M nightshift "HTTP /api/nightshift and nightshift_<action>_command share SQLite state; desktop commands forward to the persistent authenticated backend" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Bot start, budget changes and beginning a new night require fingerprint-bound owner approval; owner UI uses authenticated commands","key":"1","section":"guidance"}
M nightshift "Bot start, budget changes and beginning a new night require fingerprint-bound owner approval; owner UI uses authenticated commands" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Quiet times are HH:MM local or UTC; equal endpoints mean all day; ASR GPU reservation is the default","key":"2","section":"guidance"}
M nightshift "Quiet times are HH:MM local or UTC; equal endpoints mean all day; ASR GPU reservation is the default" src:"authored manual" state:verified
L nightshift.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t1"},"shape":{"$cl_type":"t22"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S nightshift.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t23"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t1"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"nightshift.shapeBoard: Board excludes missions by default, retains dependency/missing/open/dependent edges and exact state counts","key":"0","section":"guidance"}
M nightshift "nightshift.shapeBoard: Board excludes missions by default, retains dependency/missing/open/dependent edges and exact state counts" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.startable: Only waiting, unarmed agent tasks can be armed; Paul's tasks are always excluded","key":"1","section":"guidance"}
M nightshift "nightshift.startable: Only waiting, unarmed agent tasks can be armed; Paul's tasks are always excluded" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.evidenceView: Evidence retains its actual path, commit, run ids or owner-only command; labels disclose opening meaning","key":"2","section":"guidance"}
M nightshift "nightshift.evidenceView: Evidence retains its actual path, commit, run ids or owner-only command; labels disclose opening meaning" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.morning: Morning summary counts only completed unreported runs and non-mission tasks; actual evidence links take precedence","key":"3","section":"guidance"}
M nightshift "nightshift.morning: Morning summary counts only completed unreported runs and non-mission tasks; actual evidence links take precedence" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.quietNow: Quiet windows are start-inclusive/end-exclusive in selected local/UTC clock; midnight wraps and equal endpoints mean all day","key":"4","section":"guidance"}
M nightshift "nightshift.quietNow: Quiet windows are start-inclusive/end-exclusive in selected local/UTC clock; midnight wraps and equal endpoints mean all day" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.treeLayout: Every board task gets one measured leaf on its prerequisite branch with exact geometry and alternate sides without invented tasks","key":"5","section":"guidance"}
M nightshift "nightshift.treeLayout: Every board task gets one measured leaf on its prerequisite branch with exact geometry and alternate sides without invented tasks" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.policyForm: Saved policy fields convert measured seconds to one-decimal hours/minutes; toggles retain quiet/GPU/plan hold state and harness budgets","key":"6","section":"guidance"}
M nightshift "nightshift.policyForm: Saved policy fields convert measured seconds to one-decimal hours/minutes; toggles retain quiet/GPU/plan hold state and harness budgets" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"nightshift.policyPatch: Budget patches convert valid fields to positive integer units and report every invalid count/time/OpenCode token budget","key":"7","section":"guidance"}
M nightshift "nightshift.policyPatch: Budget patches convert valid fields to positive integer units and report every invalid count/time/OpenCode token budget" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"8","section":"guidance"}
M nightshift "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L nightshift.realbugs-lifecycle v1 -- Task-matching completion evidence before Done
-- @record {"chapter":"realbugs-lifecycle","section":"actions","key":"task","data":{"effect":"Read the owning lifecycle state from the selected workspace.","pre":"Owned proof session; observer does not launch or cancel any provider.","returns":{"type":"object"},"reversible":true,"schema":"realbugs_task","tool":"neyvia.nightshift.task"}}
A neyvia.nightshift.task(id:str) -> json:"{\"type\":\"object\"}" -- Read the owning lifecycle state from the selected workspace.
C neyvia.nightshift.task empty-completion-needs-review: neyvia.nightshift.task(id:id).status=="needs_review"
C neyvia.nightshift.task task-evidence-verified: neyvia.nightshift.task(id:id).evidence.verified==true
-- @record {"chapter":"realbugs-lifecycle","section":"actions","key":"summary","data":{"effect":"Read the owning lifecycle state from the selected workspace.","pre":"Owned proof session; observer does not launch or cancel any provider.","returns":{"type":"object"},"reversible":true,"schema":"realbugs_summary","tool":"neyvia.nightshift.summary"}}
A neyvia.nightshift.summary() -> json:"{\"type\":\"object\"}" -- Read the owning lifecycle state from the selected workspace.
C neyvia.nightshift.summary summary-completion-verified: neyvia.nightshift.summary().completionVerified==true
-- @record {"chapter":"realbugs-lifecycle","section":"checks","key":"empty-completion-needs-review","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"status","value":"needs_review"},"tool":"neyvia.nightshift.task"}}
C neyvia.nightshift.task empty-completion-needs-review: neyvia.nightshift.task(id:id).status=="needs_review"
-- @record {"chapter":"realbugs-lifecycle","section":"checks","key":"task-evidence-verified","data":{"args":{"id":{"$input":"id"}},"expect":{"op":"eq","path":"evidence.verified","value":true},"tool":"neyvia.nightshift.task"}}
C neyvia.nightshift.task task-evidence-verified: neyvia.nightshift.task(id:id).evidence.verified==true
-- @record {"chapter":"realbugs-lifecycle","section":"checks","key":"summary-completion-verified","data":{"args":{},"expect":{"op":"eq","path":"completionVerified","value":true},"tool":"neyvia.nightshift.summary"}}
C neyvia.nightshift.summary summary-completion-verified: neyvia.nightshift.summary().completionVerified==true
-- @record {"chapter":"realbugs-lifecycle","section":"procedures","key":"empty-completion-needs-review","data":{"goal":"Task-matching completion evidence before Done: empty-completion-needs-review","inputs":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},"steps":[{"action":"task","args":{"id":{"$input":"id"}},"check":"empty-completion-needs-review","save":"observed"}]}}
P empty-completion-needs-review(id:str): observed=neyvia.nightshift.task(id:id) C empty-completion-needs-review -- Task-matching completion evidence before Done: empty-completion-needs-review
V P empty-completion-needs-review -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"realbugs-lifecycle","section":"procedures","key":"task-evidence-verified","data":{"goal":"Task-matching completion evidence before Done: task-evidence-verified","inputs":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},"steps":[{"action":"task","args":{"id":{"$input":"id"}},"check":"task-evidence-verified","save":"observed"}]}}
P task-evidence-verified(id:str): observed=neyvia.nightshift.task(id:id) C task-evidence-verified -- Task-matching completion evidence before Done: task-evidence-verified
V P task-evidence-verified -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"realbugs-lifecycle","section":"procedures","key":"summary-completion-verified","data":{"goal":"Task-matching completion evidence before Done: summary-completion-verified","inputs":{"type":"object"},"steps":[{"action":"summary","args":{},"check":"summary-completion-verified","save":"observed"}]}}
P summary-completion-verified(): observed=neyvia.nightshift.summary() C summary-completion-verified -- Task-matching completion evidence before Done: summary-completion-verified
V P summary-completion-verified -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"0","data":"A completed run without task-matching evidence is needs_review with the rejection reason; its folder lock is released, its dependents stay waiting."}
M nightshift "A completed run without task-matching evidence is needs_review with the rejection reason; its folder lock is released, its dependents stay waiting." src:"authored manual" state:verified
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"1","data":"completionEvidence is the author-declared acceptance contract. file: path, optional contains/sha256/condition; commit: paths and optional hash/condition; receipt: path and expected top-level tool/result fields under expect (tool is required); result: read-only observer condition."}
M nightshift "completionEvidence is the author-declared acceptance contract. file: path, optional contains/sha256/condition; commit: paths and optional hash/condition; receipt: path and expected top-level tool/result fields under expect (tool is required); result: read-only observer condition." src:"authored manual" state:verified
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"2","data":"For launched file/receipt work, capture the declared output hash before dispatch and require new bytes. Commits must descend from the pre-attempt HEAD and change the declared paths. A receipt must be changed, successful, match expect, and equal the workspace saved native receipt with a valid receiptHash. Its timestamp and successful transcript tool call must belong to this attempt."}
M nightshift "For launched file/receipt work, capture the declared output hash before dispatch and require new bytes. Commits must descend from the pre-attempt HEAD and change the declared paths. A receipt must be changed, successful, match expect, and equal the workspace saved native receipt with a valid receiptHash. Its timestamp and successful transcript tool call must belong to this attempt." src:"authored manual" state:verified
-- @record {"chapter":"realbugs-lifecycle","section":"guidance","key":"3","data":"Stated results require nonempty assistant output from this attempt and a grounded read-only CL condition the verifier accepts. run evidence is accepted only with a nested verified output witness. Completion alone, old files, unrelated paths and failed observers cannot tick Done."}
M nightshift "Stated results require nonempty assistant output from this attempt and a grounded read-only CL condition the verifier accepts. run evidence is accepted only with a nested verified output witness. Completion alone, old files, unrelated paths and failed observers cannot tick Done." src:"authored manual" state:verified
L nightshift.filmbugs v1 -- Launch film behavior contracts
-- @record {"chapter":"filmbugs","section":"guidance","key":"0","data":"Claude terminal attempts publish live cumulative token usage from Usage transcript records, counting streamed message IDs once and including helper sessions, cache reads and writes. Saved unknown finished attempts recover only from their persisted session and started/finished run window; unavailable measurements stay unknown."}
M nightshift "Claude terminal attempts publish live cumulative token usage from Usage transcript records, counting streamed message IDs once and including helper sessions, cache reads and writes. Saved unknown finished attempts recover only from their persisted session and started/finished run window; unavailable measurements stay unknown." src:"authored manual" state:verified
