CL 1
L onboarding v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"First run: base pack download, agents found on this PC, interests, add-on packs and the tour"},"proofs-d-downloader":{"title":"PROOFS-d: verified download staging and durable setup choices"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"proofs_a_cli":{"title":"PROOFS-a CLI and durable coordination contracts"},"release-tour":{"title":"Release tour: every universal feature and the mounted player"}},"clVersion":"1.1","id":"onboarding","kind":"environment","proofs":{"area":"a-cli, d-onboarding, proofs-e-models","manifests":["config/proofs/a-cli.json","config/proofs/d-onboarding.json","config/proofs/proofs-e-models.json"],"startup":{"procedures":["grant_agent.proofs_a_cli.self_check","resume-and-verify","pause-and-resume","stage-detached-addon","reject-and-repair-addon","signed-manifest-admission","save-setup-choices","manual-save-and-observe"],"runner":"grant_agent.proof_verifier.run_verification","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.onboarding.base_pack":"t1","neyvia.onboarding.open":"t2","neyvia.onboarding.pack":"t3","neyvia.onboarding.recommend":"t4","neyvia.onboarding.runtimes":"t5","neyvia.onboarding.save":"t6","neyvia.onboarding.state":"t5","proofs-e-models.status":"t5","rel_view_state":"t5"},"tool_metadata":{"neyvia.onboarding.base_pack":{"mutability_class":"none"},"neyvia.onboarding.open":{"mutability_class":"none"},"neyvia.onboarding.pack":{"mutability_class":"artifact_write"},"neyvia.onboarding.recommend":{"mutability_class":"read"},"neyvia.onboarding.runtimes":{"mutability_class":"read"},"neyvia.onboarding.save":{"mutability_class":"none"},"neyvia.onboarding.state":{"mutability_class":"read"},"neyvia.verify.status":{"mutability_class":"none"},"neyvia.view.state":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["grant_agent.cli_catalog.classify","grant_agent.proofs_a_cli"],"claim":"CLI state follows platform, detection, verified install route, authentication issues and update metadata; unknown readiness is never invented.","id":"a-cli.catalog.classify","impact":["optional runtime readiness"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_catalog._fact","grant_agent.proofs_a_cli"],"claim":"Unknown declared facts stay null with unverified confidence; present facts retain their supplied confidence.","id":"a-cli.catalog.fact","impact":["publisher/source confidence"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_catalog.resolve_package_size","grant_agent.proofs_a_cli"],"claim":"A runtime without a declared npm package has no fabricated package size and explains the missing measurement.","id":"a-cli.catalog.size","impact":["download size approval"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_catalog._actions_for","grant_agent.proofs_a_cli"],"claim":"Actions match readiness state and managed install ownership; unsupported or unavailable runtimes offer skip.","id":"a-cli.catalog.actions","impact":["managed runtime controls"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_catalog.recommend","grant_agent.proofs_a_cli"],"claim":"Recommendations follow goal affinity order, exclude unsupported/unavailable entries, deduplicate and explain each result within the requested bound.","id":"a-cli.catalog.recommend","impact":["setup recommendations"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_installer._installer_locked","grant_agent.proofs_a_cli_scheduler"],"claim":"Managed runtime actions require current approval, persist receipts, preserve existing launcher and manifest on failure/collision, retain previous install on repair and remove only owned paths on uninstall.","id":"a-cli.installer.action","impact":["local managed runtime and durable coordination"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_installer._verified_package_archive","grant_agent.proofs_a_cli_scheduler"],"claim":"Package archive must remain inside staging and equal the declared SHA-512 before install or promotion.","id":"a-cli.installer.integrity","impact":["local managed runtime and durable coordination"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.progressive_setup.update_first_run_state","grant_agent.proofs_a_cli_lifecycle"],"claim":"First-run goals, reviewed permissions and skipped runtimes persist exactly across reload.","id":"a-cli.setup.state","impact":["First-run goals, reviewed permissions and skipped runtimes persist exactly across reload."],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.progressive_setup.build_progressive_setup","grant_agent.proofs_a_cli_lifecycle"],"claim":"The shell opens before optional CLI setup; essential readiness and skipped runtime selections determine resumable mission setup.","id":"a-cli.setup.view","impact":["The shell opens before optional CLI setup; essential readiness and skipped runtime selections determine resumable mission setup."],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli_catalog.build_catalog","grant_agent.proofs_a_cli"],"claim":"Catalog size lookup is restricted to explicitly selected runtimes; the optional catalog permits continuing without a CLI.","id":"a-cli.catalog.selection","impact":["Catalog size lookup is restricted to explicitly selected runtimes; the optional catalog permits continuing without a CLI."],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.cli.cmd_workspace_save before output","grant_agent.proofs_a_cli_preferences"],"claim":"Workspace preferences persist before output and selected full snapshots reflect saved values; skip snapshot avoids its expensive producer.","id":"a-cli.preferences.workspace","impact":["Workspace preferences persist before output and selected full snapshots reflect saved values; skip snapshot avoids its expensive producer."],"phase":"post"}
-- @proof {"checkedAt":["neyvia_onboarding.parse_manifest -> proofs_d_onboarding.check_manifest","neyvia_onboarding.run_download -> proofs_d_onboarding.check_manifest/safe_destination","neyvia_onboarding._safe_relative/_check_source","proofs_d_onboarding.self_check"],"claim":"Manifests use plain pack/version IDs, unique safe paths, bounded integer sizes and SHA256; only HTTPS/local file/loopback HTTP are allowed, totals match, throttling is local, and staged paths stay inside the pack folder.","id":"onboarding.manifest-safety","impact":["base/add-on manifest admission","staged filesystem"],"phase":"pre"}
-- @proof {"checkedAt":["neyvia_onboarding.parse_manifest -> neyvia_onboarding._verify_manifest_signature","proofs_d_onboarding.self_check"],"claim":"Remote non-test payload manifests require a provisioned known Ed25519 key, matching fingerprint and valid canonical Unicode signature. Unsigned admission requires test channel or both local manifest and local payloads.","id":"onboarding.signature-authority","impact":["release trust","remote manifest bytes"],"phase":"pre"}
-- @proof {"checkedAt":["neyvia_onboarding.run_download -> proofs_d_onboarding.check_staged_file/check_download_result","neyvia_onboarding._fetch","proofs_d_onboarding.self_check"],"claim":"Every committed and reused file has its declared size and actual SHA256; only all-verified bytes earn a complete receipt and exact completion counters. Corrupt hashes retry once then discard corrupt partial bytes; oversized sources and errors are durably failed.","id":"onboarding.verified-staging","impact":["payload bytes","install receipt","download progress"],"phase":"post"}
-- @proof {"checkedAt":["neyvia_onboarding.run_download -> proofs_d_onboarding.check_staged_file","neyvia_onboarding._fetch","proofs_d_onboarding.self_check"],"claim":"Partial bytes are resumed with HTTP Range or local seeking; completed files with matching receipt identity, size, timestamp and actual SHA256 are reused without another download.","id":"onboarding.resume-reuse","impact":["CDN requests","resume byte progress","staging cache"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_onboarding.run_download -> proofs_d_onboarding.check_download_result","proofs_d_onboarding.self_check"],"claim":"A consumed pause request stops at a progress boundary, persists paused status and retains resumable partial bytes; another run finishes verified staging.","id":"onboarding.pause","impact":["worker status","partial bytes"],"phase":"post"}
-- @proof {"checkedAt":["neyvia_onboarding.pack_status -> neyvia_onboarding._installed_pack_error","neyvia_onboarding.pack_status -> proofs_d_onboarding.check_pack_status","neyvia_onboarding.install_pack -> neyvia_onboarding._spawn_worker","neyvia_onboarding.install_pack/run_download -> proofs_d_onboarding.check_staging_scope","proofs_d_onboarding.self_check"],"claim":"Add-on installs run in detached workers, keep separate per-pack status and receipts, expose stagedOnly=true, and never change base-pack status. Installed means every staged file still verifies.","id":"onboarding.addon-isolation","impact":["add-on staging","base staging","system activation boundary"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_onboarding.load_pack_manifest","neyvia_onboarding.install_pack/pack_status -> proofs_d_onboarding.check_pack_status","proofs_d_onboarding.self_check"],"claim":"Unknown IDs are rejected; unavailable payloads disclose their gap. Mismatched, broken or missing manifests fail without a target; repairing the manifest clears errors and permits staging.","id":"onboarding.addon-recovery","impact":["add-on catalog","staging retries"],"phase":"pre"}
-- @proof {"checkedAt":["neyvia_onboarding.load_catalog -> proofs_d_onboarding.check_catalog","proofs_d_onboarding.self_check"],"claim":"Every catalog interest references existing registered apps and optional packs.","id":"onboarding.catalog-integrity","impact":["onboarding recommendations","app/pack registry"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_onboarding.recommend -> proofs_d_onboarding.check_recommendation","proofs_d_onboarding.self_check"],"claim":"Recommendations form unique unions in catalog order, filter tour chapters by chosen interests while retaining universal chapters, and keep nonempty tours between 60 and 90 seconds.","id":"onboarding.ordered-recommendations","impact":["tier choices","tour playback"],"phase":"post"}
-- @proof {"checkedAt":["neyvia_onboarding.save_state -> proofs_d_onboarding.check_saved","proofs_d_onboarding.self_check"],"claim":"Invalid app/interest/pack choices are rejected before writing. Accepted normalized setup choices persist exactly and firstRun becomes false.","id":"onboarding.choices-durable","impact":["setup state","completed setup"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:interestsFor -> checkedProofsEModel"],"claim":"Direct interests win over tiers; unknown/missing tiers select nothing","id":"onboarding.interestsFor","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:recommend -> checkedProofsEModel"],"claim":"Recommendations union selected interest resources in catalog order and preserve unconditional tour chapters","id":"onboarding.recommend","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:timeline -> checkedProofsEModel"],"claim":"Tour duration is 60â€“90 seconds when nonempty, proportional chapters are contiguous and last chapter consumes rounding remainder","id":"onboarding.timeline","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:locate -> checkedProofsEModel"],"claim":"Every playhead maps to its containing chapter with clamped progress; empty tours have no chapter","id":"onboarding.locate","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:downloadView -> checkedProofsEModel"],"claim":"Download percent uses measured bytes; busy/end/error words reflect state and measured ETA","id":"onboarding.downloadView","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:packView -> checkedProofsEModel"],"claim":"Pack installation controls reflect actual availability and copying state; receipt detail names verified file count/bytes","id":"onboarding.packView","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:plainMissing -> checkedProofsEModel"],"claim":"Catalog gaps use plain tool names without hiding unavailable payloads","id":"onboarding.plainMissing","impact":["onboarding frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOnboardingModel.js:runtimeHeadline -> checkedProofsEModel"],"claim":"Only observed found runtimes produce set-to-start wording and names; no result stays checking","id":"onboarding.runtimeHeadline","impact":["onboarding frontend model consumers"],"phase":"post"}
T t1{action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"start\",\"pause\"]}" ..}
T t2{step?:json:"{\"type\":\"string\",\"enum\":[\"welcome\",\"runtimes\",\"interests\",\"tour\"]}" ..}
T t3{action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"install\"]}" packId?:str ..}
T t4{interests?:[str] tier?:str ..}
T t5{..}
T t6{interests?:[str] tier?:str apps?:[str] packs?:[str] runtime?:str completed?:bool ..}
T t7{}
T t8{state:{completed:bool interests:json:"{\"type\":\"array\"}" apps:json:"{\"type\":\"array\"}" packs:json:"{\"type\":\"array\"}" tier:str ..} ..}
T t9 json:"{\"type\":\"object\"}"
T t10{interests:[str] completed:bool}
T t11{packId:str}
T t12{apps:[str] completed:bool interests:[str] packs:[str] runtime:str tier:str ..}
T t13{state:str ..}
T t14{ok:bool ..}
T t15 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
T t16 json:"{\"type\":\"object\",\"properties\":{}}"
L onboarding.overview v1 -- First run: base pack download, agents found on this PC, interests, add-on packs and the tour
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t7"},"shape":{"$cl_type":"t8"},"tool":"neyvia.onboarding.state"},"key":"current","section":"state"}
S onboarding.current:{state:{completed:bool interests:json:"{\"type\":\"array\"}" apps:json:"{\"type\":\"array\"}" packs:json:"{\"type\":\"array\"}" tier:str ..} ..}=neyvia.onboarding.state()
-- @record {"chapter":"overview","data":{"effect":"Return persisted setup choices, catalog, tour and base-pack status","pre":"Selected root readable; no saved choices required","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.onboarding.state","tool":"neyvia.onboarding.state"},"key":"onboarding.state","section":"actions"}
A neyvia.onboarding.state() -> {state:{completed:bool interests:json:"{\"type\":\"array\"}" apps:json:"{\"type\":\"array\"}" packs:json:"{\"type\":\"array\"}" tier:str ..} ..} -- Return persisted setup choices, catalog, tour and base-pack status
C neyvia.onboarding.state completed-saved:neyvia.onboarding.state() .state.completed == completed
-- @record {"chapter":"overview","data":{"effect":"Read status, resume detached downloader or request pause; checksum-verified bytes staged locally","pre":"action=status/start/pause; start requires valid size/hash/path manifest and remote signature when applicable","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.base_pack","tool":"neyvia.onboarding.base_pack"},"key":"onboarding.base_pack","section":"actions"}
A neyvia.onboarding.base_pack(action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"start\",\"pause\"]}") -> json:"{\"type\":\"object\"}" -- Read status, resume detached downloader or request pause; checksum-verified bytes staged locally
F verify-onboarding-base_pack "No authored observer check is bound to neyvia.onboarding.base_pack" -> ask operator blocks:neyvia.onboarding.base_pack
-- @record {"chapter":"overview","data":{"effect":"Emit setup-screen request with uiVerified=false; saved completion unchanged","pre":"step welcome/runtimes/interests/tour","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.open","tool":"neyvia.onboarding.open"},"key":"onboarding.open","section":"actions"}
A neyvia.onboarding.open(step?:json:"{\"type\":\"string\",\"enum\":[\"welcome\",\"runtimes\",\"interests\",\"tour\"]}") -> json:"{\"type\":\"object\"}" -- Emit setup-screen request with uiVerified=false; saved completion unchanged
F verify-onboarding-open "No authored observer check is bound to neyvia.onboarding.open" -> ask operator blocks:neyvia.onboarding.open
-- @record {"chapter":"overview","data":{"effect":"Read pack statuses or stage verified add-on in detached worker; no system install or activation","pre":"Known pack ID; install requires available packaged manifest with matching packId and safe signed/hashed sources","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.onboarding.pack","tool":"neyvia.onboarding.pack"},"key":"onboarding.pack","section":"actions"}
A neyvia.onboarding.pack(action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"install\"]}" packId?:str) -> json:"{\"type\":\"object\"}" ! -- Read pack statuses or stage verified add-on in detached worker; no system install or activation
F verify-onboarding-pack "No authored observer check is bound to neyvia.onboarding.pack" -> ask operator blocks:neyvia.onboarding.pack
-- @record {"chapter":"overview","data":{"effect":"Compute recommended apps/packs/tour chapters; save nothing","pre":"Interests are catalog IDs; optional tier beginner/intermediate/advanced","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.recommend","tool":"neyvia.onboarding.recommend"},"key":"onboarding.recommend","section":"actions"}
A neyvia.onboarding.recommend(interests?:[str] tier?:str) -> json:"{\"type\":\"object\"}" -- Compute recommended apps/packs/tour chapters; save nothing
F verify-onboarding-recommend "No authored observer check is bound to neyvia.onboarding.recommend" -> ask operator blocks:neyvia.onboarding.recommend
-- @record {"chapter":"overview","data":{"effect":"Detect local CLI availability and return setup steps; does not install runtimes","pre":"Selected root and runtime detection available","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.runtimes","tool":"neyvia.onboarding.runtimes"},"key":"onboarding.runtimes","section":"actions"}
A neyvia.onboarding.runtimes() -> json:"{\"type\":\"object\"}" -- Detect local CLI availability and return setup steps; does not install runtimes
F verify-onboarding-runtimes "No authored observer check is bound to neyvia.onboarding.runtimes" -> ask operator blocks:neyvia.onboarding.runtimes
-- @record {"chapter":"overview","data":{"effect":"Merge supplied fields into persistent setup state; omitted choices retained","pre":"Only catalog interest/app/pack IDs, valid tier/runtime and boolean completed; choices belong to person","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.save","tool":"neyvia.onboarding.save"},"key":"onboarding.save","section":"actions"}
A neyvia.onboarding.save(interests?:[str] tier?:str apps?:[str] packs?:[str] runtime?:str completed?:bool) -> json:"{\"type\":\"object\"}" -- Merge supplied fields into persistent setup state; omitted choices retained
C neyvia.onboarding.save interests-saved:neyvia.onboarding.state() .state.interests == interests
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.interests","value":{"$input":"interests"}},"tool":"neyvia.onboarding.state"},"key":"interests-saved","section":"checks"}
C neyvia.onboarding.state interests-saved:neyvia.onboarding.state() .state.interests == interests
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"state.completed","value":{"$input":"completed"}},"tool":"neyvia.onboarding.state"},"key":"completed-saved","section":"checks"}
C neyvia.onboarding.state completed-saved:neyvia.onboarding.state() .state.completed == completed
-- @record {"chapter":"overview","data":{"goal":"Recommend from selected interests, review and persist the chosen setup","inputs":{"$cl_type":"t10"},"steps":[{"action":"onboarding.recommend","args":{"interests":{"$input":"interests"}},"save":"recommended"},{"judge":"setup-choices"},{"action":"onboarding.save","args":{"completed":{"$input":"completed"},"interests":{"$input":"interests"}},"check":"interests-saved","save":"saved","when":{"judge":"setup-choices","option":"save"}},{"action":"onboarding.state","args":{},"check":"completed-saved","save":"state","when":{"judge":"setup-choices","option":"save"}}]},"key":"save-choices","section":"procedures"}
P save-choices(interests:[str] completed:bool):recommended=neyvia.onboarding.recommend(interests:interests); J setup-choices=save; saved=neyvia.onboarding.save(completed:completed interests:interests) C interests-saved; state=neyvia.onboarding.state() C completed-saved -- Recommend from selected interests, review and persist the chosen setup
V P save-choices -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Check availability and stage an explicitly selected add-on","inputs":{"$cl_type":"t11"},"steps":[{"action":"onboarding.pack","args":{"action":"status","packId":{"$input":"packId"}},"save":"before"},{"judge":"pack-download"},{"action":"onboarding.pack","args":{"action":"install","packId":{"$input":"packId"}},"save":"job","when":{"judge":"pack-download","option":"install"}},{"action":"onboarding.pack","args":{"action":"status","packId":{"$input":"packId"}},"save":"progress","when":{"judge":"pack-download","option":"install"}}]},"key":"stage-chosen-pack","section":"procedures"}
P stage-chosen-pack(packId:str):before=neyvia.onboarding.pack(action:"status" packId:packId); J pack-download=install; job=neyvia.onboarding.pack(action:"install" packId:packId); progress=neyvia.onboarding.pack(action:"status" packId:packId) -- Check availability and stage an explicitly selected add-on
V P stage-chosen-pack -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Save reviewed catalog choices and verify exact persisted state","inputs":{"$cl_type":"t12"},"steps":[{"action":"onboarding.save","args":{"apps":{"$input":"apps"},"completed":{"$input":"completed"},"interests":{"$input":"interests"},"packs":{"$input":"packs"},"runtime":{"$input":"runtime"},"tier":{"$input":"tier"}},"save":"observed"}]},"key":"save-local-choices","section":"procedures"}
P save-local-choices(apps:[str] completed:bool interests:[str] packs:[str] runtime:str tier:str):observed=neyvia.onboarding.save(apps:apps completed:completed interests:interests packs:packs runtime:runtime tier:tier) -- Save reviewed catalog choices and verify exact persisted state
V P save-local-choices -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Recommendations are suggestions; save only the person-selected catalog IDs. completed means person finished setup, not that every optional pack is installed.","options":["save","leave"],"question":"Accept the recommended setup or keep current choices?"},"key":"setup-choices","section":"judge"}
J setup-choices save|leave:"Accept the recommended setup or keep current choices?" -- Recommendations are suggestions; save only the person-selected catalog IDs. completed means person finished setup, not that every optional pack is installed.
V J setup-choices -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"constraints":"Read pack availability first; unavailable/no manifest is a stop. Staging does not activate anything. Remote downloads require chosen scope, signed manifest and size within authorized budget.","options":["install","leave"],"question":"Stage this separately packaged add-on?"},"key":"pack-download","section":"judge"}
J pack-download install|leave:"Stage this separately packaged add-on?" -- Read pack availability first; unavailable/no manifest is a stop. Staging does not activate anything. Remote downloads require chosen scope, signed manifest and size within authorized budget.
V J pack-download -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Unknown interest/app/pack/runtime ID","recovery":"Read onboarding.state catalog and use exact IDs; never save display labels"},"key":"0","section":"pitfalls"}
X Unknown interest/app/pack/runtime ID -> Read onboarding.state catalog and use exact IDs; never save display labels
-- @record {"chapter":"overview","data":{"failure":"Pack says unavailable or no packaged manifest","recovery":"Report catalog gap; selection alone does not install pack"},"key":"1","section":"pitfalls"}
X Pack says unavailable or no packaged manifest -> Report catalog gap; selection alone does not install pack
-- @record {"chapter":"overview","data":{"failure":"Checksum fails twice","recovery":"Stop downloader, verify original source/manifest; do not replace expected hash"},"key":"2","section":"pitfalls"}
X Checksum fails twice -> Stop downloader, verify original source/manifest; do not replace expected hash
-- @record {"chapter":"overview","data":{"failure":"Worker interrupted or pause requested","recovery":"Read base_pack status; start resumes verified partial bytes; running is not complete"},"key":"3","section":"pitfalls"}
X Worker interrupted or pause requested -> Read base_pack status; start resumes verified partial bytes; running is not complete
-- @record {"chapter":"overview","data":{"failure":"Remote manifest missing signature","recovery":"Provision trusted signing key through release owner; never downgrade signature verification"},"key":"4","section":"pitfalls"}
X Remote manifest missing signature -> Provision trusted signing key through release owner; never downgrade signature verification
-- @record {"chapter":"overview","data":{"failure":"Person thinks an installed pack is running or on PATH","recovery":"Installed means every file was copied into Neyvia's add-on folder and passed its checksum, with a receipt (onboarding.pack status → receipt); nothing is activated or added to the system"},"key":"5","section":"pitfalls"}
X Person thinks an installed pack is running or on PATH -> Installed means every file was copied into Neyvia's add-on folder and passed its checksum, with a receipt (onboarding.pack status → receipt); nothing is activated or added to the system
-- @record {"chapter":"overview","data":"Public base-pack release promotion and activation are outside local staging","key":"0","section":"frontier"}
F Public base-pack release promotion and activation are outside local staging
-- @record {"chapter":"overview","data":"Setup/tour command uiVerified=false needs actual user-side acknowledgement","key":"1","section":"frontier"}
F Setup/tour command uiVerified=false needs actual user-side acknowledgement
-- @record {"chapter":"overview","data":"The tour plays Neyvia's own screens (chat, checklist, launcher, missions, workspace, PDF, dictation, phone frame) on example data; it never shows or changes the person's chats","key":"2","section":"frontier"}
F The tour plays Neyvia's own screens (chat, checklist, launcher, missions, workspace, PDF, dictation, phone frame) on example data; it never shows or changes the person's chats
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_onboarding.py (save_state, parse_manifest, install_pack, run_download); tests/test_neyvia_onboarding.py.","key":"0","section":"guidance"}
M onboarding "Source: src/grant_agent/neyvia_onboarding.py (save_state, parse_manifest, install_pack, run_download); tests/test_neyvia_onboarding.py." src:"authored manual" state:verified
L onboarding.proofs-d-downloader v1 -- PROOFS-d: verified download staging and durable setup choices
-- @record {"chapter":"proofs-d-downloader","data":{"args":{"action":"status"},"inputs":{"$cl_type":"t7"},"shape":{"$cl_type":"t13"},"tool":"neyvia.onboarding.base_pack"},"key":"base-staging","section":"state"}
S onboarding.base-staging:{state:str ..}=neyvia.onboarding.base_pack(action:"status")
-- @record {"chapter":"proofs-d-downloader","data":{"args":{},"inputs":{"$cl_type":"t7"},"shape":{"$cl_type":"t8"},"tool":"neyvia.onboarding.state"},"key":"choices","section":"state"}
S onboarding.choices:{state:{completed:bool interests:json:"{\"type\":\"array\"}" apps:json:"{\"type\":\"array\"}" packs:json:"{\"type\":\"array\"}" tier:str ..} ..}=neyvia.onboarding.state()
-- @record {"chapter":"proofs-d-downloader","data":{"effect":"Read status, resume detached downloader or request pause; checksum-verified bytes staged locally","pre":"action=status/start/pause; start requires valid size/hash/path manifest and remote signature when applicable","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.base_pack","tool":"neyvia.onboarding.base_pack"},"key":"onboarding.base_pack","section":"actions"}
A neyvia.onboarding.base_pack(action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"start\",\"pause\"]}") -> json:"{\"type\":\"object\"}" -- Read status, resume detached downloader or request pause; checksum-verified bytes staged locally
F verify-onboarding-base_pack "No authored observer check is bound to neyvia.onboarding.base_pack" -> ask operator blocks:neyvia.onboarding.base_pack
-- @record {"chapter":"proofs-d-downloader","data":{"effect":"Read pack statuses or stage verified add-on in detached worker; no system install or activation","pre":"Known pack ID; install requires available packaged manifest with matching packId and safe signed/hashed sources","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.onboarding.pack","tool":"neyvia.onboarding.pack"},"key":"onboarding.pack","section":"actions"}
A neyvia.onboarding.pack(action?:json:"{\"type\":\"string\",\"enum\":[\"status\",\"install\"]}" packId?:str) -> json:"{\"type\":\"object\"}" ! -- Read pack statuses or stage verified add-on in detached worker; no system install or activation
F verify-onboarding-pack "No authored observer check is bound to neyvia.onboarding.pack" -> ask operator blocks:neyvia.onboarding.pack
-- @record {"chapter":"proofs-d-downloader","data":{"effect":"Merge supplied fields into persistent setup state; omitted choices retained","pre":"Only catalog interest/app/pack IDs, valid tier/runtime and boolean completed; choices belong to person","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.save","tool":"neyvia.onboarding.save"},"key":"onboarding.save","section":"actions"}
A neyvia.onboarding.save(interests?:[str] tier?:str apps?:[str] packs?:[str] runtime?:str completed?:bool) -> json:"{\"type\":\"object\"}" -- Merge supplied fields into persistent setup state; omitted choices retained
C neyvia.onboarding.save completed-saved:neyvia.onboarding.state() .state.completed == completed
-- @record {"chapter":"proofs-d-downloader","data":{"effect":"Return persisted setup choices, catalog, tour and base-pack status","pre":"Selected root readable; no saved choices required","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.onboarding.state","tool":"neyvia.onboarding.state"},"key":"onboarding.state","section":"actions"}
A neyvia.onboarding.state() -> {state:{completed:bool interests:json:"{\"type\":\"array\"}" apps:json:"{\"type\":\"array\"}" packs:json:"{\"type\":\"array\"}" tier:str ..} ..} -- Return persisted setup choices, catalog, tour and base-pack status
C neyvia.onboarding.state interests-saved:neyvia.onboarding.state() .state.interests == interests
-- @record {"chapter":"proofs-d-downloader","data":{"args":{},"expect":{"op":"eq","path":"state.completed","value":{"$input":"completed"}},"tool":"neyvia.onboarding.state"},"key":"completed-saved","section":"checks"}
C neyvia.onboarding.state completed-saved:neyvia.onboarding.state() .state.completed == completed
-- @record {"chapter":"proofs-d-downloader","data":{"args":{},"expect":{"op":"eq","path":"state.interests","value":{"$input":"interests"}},"tool":"neyvia.onboarding.state"},"key":"interests-saved","section":"checks"}
C neyvia.onboarding.state interests-saved:neyvia.onboarding.state() .state.interests == interests
-- @record {"chapter":"proofs-d-downloader","data":{"goal":"Persist explicitly selected scratch setup choices and observe matching completion and interests","inputs":{"$cl_type":"t10"},"steps":[{"action":"onboarding.save","args":{"completed":{"$input":"completed"},"interests":{"$input":"interests"}},"check":"completed-saved","save":"saved"},{"action":"onboarding.state","args":{},"check":"interests-saved","save":"observed"}]},"key":"save-and-observe","section":"procedures"}
P save-and-observe(interests:[str] completed:bool):saved=neyvia.onboarding.save(completed:completed interests:interests) C completed-saved; observed=neyvia.onboarding.state() C interests-saved -- Persist explicitly selected scratch setup choices and observe matching completion and interests
V P save-and-observe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-d-downloader","data":{"failure":"Timestamp unchanged after payload corruption","recovery":"Hash real bytes before reuse; re-download corrupt staging"},"key":"0","section":"pitfalls"}
X Timestamp unchanged after payload corruption -> Hash real bytes before reuse; re-download corrupt staging
-- @record {"chapter":"proofs-d-downloader","data":{"failure":"Self-check fixture port 48496 is occupied","recovery":"Stop only the owned fixture or report conflict; do not select a forbidden or implicit port"},"key":"1","section":"pitfalls"}
X Self-check fixture port 48496 is occupied -> Stop only the owned fixture or report conflict; do not select a forbidden or implicit port
-- @record {"chapter":"proofs-d-downloader","data":"Self-checks use a 230400-byte loopback CDN and generated Ed25519 fixture keys; they do not prove a remote CDN, public installer or real release activation","key":"0","section":"frontier"}
F Self-checks use a 230400-byte loopback CDN and generated Ed25519 fixture keys; they do not prove a remote CDN, public installer or real release activation
-- @record {"chapter":"proofs-d-downloader","data":"Optional packs with missing delivery manifests remain unavailable; no system installs or activation occur","key":"1","section":"frontier"}
F Optional packs with missing delivery manifests remain unavailable; no system installs or activation occur
-- @record {"chapter":"proofs-d-downloader","data":"Production contracts: src/grant_agent/proofs_d_onboarding.py; declarations: config/proofs/d-onboarding.json","key":"0","section":"guidance"}
M onboarding "Production contracts: src/grant_agent/proofs_d_onboarding.py; declarations: config/proofs/d-onboarding.json" src:"authored manual" state:verified
-- @record {"chapter":"proofs-d-downloader","data":"Startup uses a fresh scratch root, real HTTP range requests, a real detached add-on worker, adverse manifest/checksum/signature paths, and the grounded manual runner","key":"1","section":"guidance"}
M onboarding "Startup uses a fresh scratch root, real HTTP range requests, a real detached add-on worker, adverse manifest/checksum/signature paths, and the grounded manual runner" src:"authored manual" state:verified
L onboarding.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t5"},"shape":{"$cl_type":"t14"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S onboarding.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t15"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t5"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"onboarding.interestsFor: Direct interests win over tiers; unknown/missing tiers select nothing","key":"0","section":"guidance"}
M onboarding "onboarding.interestsFor: Direct interests win over tiers; unknown/missing tiers select nothing" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.recommend: Recommendations union selected interest resources in catalog order and preserve unconditional tour chapters","key":"1","section":"guidance"}
M onboarding "onboarding.recommend: Recommendations union selected interest resources in catalog order and preserve unconditional tour chapters" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.timeline: Tour duration is 60â€“90 seconds when nonempty, proportional chapters are contiguous and last chapter consumes rounding remainder","key":"2","section":"guidance"}
M onboarding "onboarding.timeline: Tour duration is 60â€“90 seconds when nonempty, proportional chapters are contiguous and last chapter consumes rounding remainder" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.locate: Every playhead maps to its containing chapter with clamped progress; empty tours have no chapter","key":"3","section":"guidance"}
M onboarding "onboarding.locate: Every playhead maps to its containing chapter with clamped progress; empty tours have no chapter" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.downloadView: Download percent uses measured bytes; busy/end/error words reflect state and measured ETA","key":"4","section":"guidance"}
M onboarding "onboarding.downloadView: Download percent uses measured bytes; busy/end/error words reflect state and measured ETA" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.packView: Pack installation controls reflect actual availability and copying state; receipt detail names verified file count/bytes","key":"5","section":"guidance"}
M onboarding "onboarding.packView: Pack installation controls reflect actual availability and copying state; receipt detail names verified file count/bytes" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.plainMissing: Catalog gaps use plain tool names without hiding unavailable payloads","key":"6","section":"guidance"}
M onboarding "onboarding.plainMissing: Catalog gaps use plain tool names without hiding unavailable payloads" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"onboarding.runtimeHeadline: Only observed found runtimes produce set-to-start wording and names; no result stays checking","key":"7","section":"guidance"}
M onboarding "onboarding.runtimeHeadline: Only observed found runtimes produce set-to-start wording and names; no result stays checking" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"8","section":"guidance"}
M onboarding "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L onboarding.proofs_a_cli v1 -- PROOFS-a CLI and durable coordination contracts
-- @record {"chapter":"proofs_a_cli","data":{"failure":"Provider runtime absent in scratch","recovery":"Require separate provider journey; local parser and database proofs remain valid within scratch."},"key":"0","section":"pitfalls"}
X Provider runtime absent in scratch -> Require separate provider journey; local parser and database proofs remain valid within scratch.
-- @record {"chapter":"proofs_a_cli","data":"tests/test_codex_completion_contracts.py::RuntimeUiContractTests.test_managed_cli_surface_uses_the_durable_runtime_turn: Original source-string checks for the classic managed CLI surface require a rendered durable runtime turn and awaited action journey before deletion; no rendered legacy UI proof is claimed in this area.","key":"0","section":"frontier"}
F tests/test_codex_completion_contracts.py::RuntimeUiContractTests.test_managed_cli_surface_uses_the_durable_runtime_turn: Original source-string checks for the classic managed CLI surface require a rendered durable runtime turn and awaited action journey before deletion; no rendered legacy UI proof is claimed in this area.
-- @record {"chapter":"proofs_a_cli","data":"Controlled provider/installer transports prove orchestration and durable state, not authenticated provider service execution.","key":"1","section":"frontier"}
F Controlled provider/installer transports prove orchestration and durable state, not authenticated provider service execution.
-- @record {"chapter":"proofs_a_cli","data":"POSIX detach option is exercised through production dispatch with an inert child transport on Windows; native POSIX session semantics are outside this receipt.","key":"2","section":"frontier"}
F POSIX detach option is exercised through production dispatch with an inert child transport on Windows; native POSIX session semantics are outside this receipt.
-- @record {"chapter":"proofs_a_cli","data":"Contracts listed in this chapter execute at the real production boundaries named in checkedAt.","key":"0","section":"guidance"}
M onboarding "Contracts listed in this chapter execute at the real production boundaries named in checkedAt." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"Startup uses isolated scratch state and finite controlled transport boundaries; examine the receipt before claiming external provider readiness.","key":"1","section":"guidance"}
M onboarding "Startup uses isolated scratch state and finite controlled transport boundaries; examine the receipt before claiming external provider readiness." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.classify: CLI state follows platform, detection, verified install route, authentication issues and update metadata; unknown readiness is never invented.","key":"2","section":"guidance"}
M onboarding "a-cli.catalog.classify: CLI state follows platform, detection, verified install route, authentication issues and update metadata; unknown readiness is never invented." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.fact: Unknown declared facts stay null with unverified confidence; present facts retain their supplied confidence.","key":"3","section":"guidance"}
M onboarding "a-cli.catalog.fact: Unknown declared facts stay null with unverified confidence; present facts retain their supplied confidence." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.size: A runtime without a declared npm package has no fabricated package size and explains the missing measurement.","key":"4","section":"guidance"}
M onboarding "a-cli.catalog.size: A runtime without a declared npm package has no fabricated package size and explains the missing measurement." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.actions: Actions match readiness state and managed install ownership; unsupported or unavailable runtimes offer skip.","key":"5","section":"guidance"}
M onboarding "a-cli.catalog.actions: Actions match readiness state and managed install ownership; unsupported or unavailable runtimes offer skip." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.recommend: Recommendations follow goal affinity order, exclude unsupported/unavailable entries, deduplicate and explain each result within the requested bound.","key":"6","section":"guidance"}
M onboarding "a-cli.catalog.recommend: Recommendations follow goal affinity order, exclude unsupported/unavailable entries, deduplicate and explain each result within the requested bound." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.installer.action: Managed runtime actions require current approval, persist receipts, preserve existing launcher and manifest on failure/collision, retain previous install on repair and remove only owned paths on uninstall.","key":"7","section":"guidance"}
M onboarding "a-cli.installer.action: Managed runtime actions require current approval, persist receipts, preserve existing launcher and manifest on failure/collision, retain previous install on repair and remove only owned paths on uninstall." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.installer.integrity: Package archive must remain inside staging and equal the declared SHA-512 before install or promotion.","key":"8","section":"guidance"}
M onboarding "a-cli.installer.integrity: Package archive must remain inside staging and equal the declared SHA-512 before install or promotion." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.setup.state: First-run goals, reviewed permissions and skipped runtimes persist exactly across reload.","key":"9","section":"guidance"}
M onboarding "a-cli.setup.state: First-run goals, reviewed permissions and skipped runtimes persist exactly across reload." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.setup.view: The shell opens before optional CLI setup; essential readiness and skipped runtime selections determine resumable mission setup.","key":"10","section":"guidance"}
M onboarding "a-cli.setup.view: The shell opens before optional CLI setup; essential readiness and skipped runtime selections determine resumable mission setup." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.catalog.selection: Catalog size lookup is restricted to explicitly selected runtimes; the optional catalog permits continuing without a CLI.","key":"11","section":"guidance"}
M onboarding "a-cli.catalog.selection: Catalog size lookup is restricted to explicitly selected runtimes; the optional catalog permits continuing without a CLI." src:"authored manual" state:verified
-- @record {"chapter":"proofs_a_cli","data":"a-cli.preferences.workspace: Workspace preferences persist before output and selected full snapshots reflect saved values; skip snapshot avoids its expensive producer.","key":"12","section":"guidance"}
M onboarding "a-cli.preferences.workspace: Workspace preferences persist before output and selected full snapshots reflect saved values; skip snapshot avoids its expensive producer." src:"authored manual" state:verified
L onboarding.release-tour v1 -- Release tour: every universal feature and the mounted player
-- @record {"chapter":"release-tour","data":{"effect":"Compute recommended apps/packs/tour chapters; save nothing","pre":"Interests are catalog IDs; optional tier beginner/intermediate/advanced","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.recommend","tool":"neyvia.onboarding.recommend"},"key":"onboarding.recommend","section":"actions"}
A neyvia.onboarding.recommend(interests?:[str] tier?:str) -> json:"{\"type\":\"object\"}" -- Compute recommended apps/packs/tour chapters; save nothing
C neyvia.onboarding.recommend includes-basics:neyvia.onboarding.recommend(interests:[]) .chapters has "basics"
C neyvia.onboarding.recommend includes-runtimes:neyvia.onboarding.recommend(interests:[]) .chapters has "runtimes"
C neyvia.onboarding.recommend includes-notes:neyvia.onboarding.recommend(interests:[]) .chapters has "notes"
C neyvia.onboarding.recommend includes-studio:neyvia.onboarding.recommend(interests:[]) .chapters has "studio"
C neyvia.onboarding.recommend includes-laya:neyvia.onboarding.recommend(interests:[]) .chapters has "laya"
C neyvia.onboarding.recommend includes-look:neyvia.onboarding.recommend(interests:[]) .chapters has "look"
C neyvia.onboarding.recommend includes-placement:neyvia.onboarding.recommend(interests:[]) .chapters has "placement"
C neyvia.onboarding.recommend includes-watching:neyvia.onboarding.recommend(interests:[]) .chapters has "watching"
C neyvia.onboarding.recommend includes-factory:neyvia.onboarding.recommend(interests:[]) .chapters has "factory"
C neyvia.onboarding.recommend includes-connectors:neyvia.onboarding.recommend(interests:[]) .chapters has "connectors"
C neyvia.onboarding.recommend includes-images:neyvia.onboarding.recommend(interests:[]) .chapters has "images"
-- @record {"chapter":"release-tour","data":{"effect":"Emit setup-screen request with uiVerified=false; saved completion unchanged","pre":"step welcome/runtimes/interests/tour","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.onboarding.open","tool":"neyvia.onboarding.open"},"key":"onboarding.open","section":"actions"}
A neyvia.onboarding.open(step?:json:"{\"type\":\"string\",\"enum\":[\"welcome\",\"runtimes\",\"interests\",\"tour\"]}") -> json:"{\"type\":\"object\"}" -- Emit setup-screen request with uiVerified=false; saved completion unchanged
C neyvia.onboarding.open tour-mounted:neyvia.view.state() .state.dom.setup.mounted == true
-- @record {"chapter":"release-tour","data":{"effect":"Read current windows, ids, placements, mounted DOM geometry and delivered events.","pre":"The shell reports state after React commits; fresh=false means unavailable.","returns":{"$cl_type":"t9"},"reversible":true,"schema":"rel_view_state","tool":"neyvia.view.state"},"key":"view.state","section":"actions"}
A neyvia.view.state() -> json:"{\"type\":\"object\"}" -- Read current windows, ids, placements, mounted DOM geometry and delivered events.
C neyvia.view.state workspace-mounted:neyvia.view.state() .state.dom.mounted == true
C neyvia.view.state storage-warning-visible:neyvia.view.state() .state.dom.storage.warningVisible == true
C neyvia.view.state storage-warning-honest:neyvia.view.state() .state.dom.storage.text == "Large local saves are unavailable. Saved data has been kept. Keep this window open until server sync completes, then reload to retry."
-- @record {"chapter":"release-tour","data":{"args":{},"expect":{"op":"eq","path":"state.dom.setup.mounted","value":true},"tool":"neyvia.view.state"},"key":"tour-mounted","section":"checks"}
C neyvia.view.state tour-mounted:neyvia.view.state() .state.dom.setup.mounted == true
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"basics"},"tool":"neyvia.onboarding.recommend"},"key":"includes-basics","section":"checks"}
C neyvia.onboarding.recommend includes-basics:neyvia.onboarding.recommend(interests:[]) .chapters has "basics"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"runtimes"},"tool":"neyvia.onboarding.recommend"},"key":"includes-runtimes","section":"checks"}
C neyvia.onboarding.recommend includes-runtimes:neyvia.onboarding.recommend(interests:[]) .chapters has "runtimes"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"notes"},"tool":"neyvia.onboarding.recommend"},"key":"includes-notes","section":"checks"}
C neyvia.onboarding.recommend includes-notes:neyvia.onboarding.recommend(interests:[]) .chapters has "notes"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"studio"},"tool":"neyvia.onboarding.recommend"},"key":"includes-studio","section":"checks"}
C neyvia.onboarding.recommend includes-studio:neyvia.onboarding.recommend(interests:[]) .chapters has "studio"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"laya"},"tool":"neyvia.onboarding.recommend"},"key":"includes-laya","section":"checks"}
C neyvia.onboarding.recommend includes-laya:neyvia.onboarding.recommend(interests:[]) .chapters has "laya"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"look"},"tool":"neyvia.onboarding.recommend"},"key":"includes-look","section":"checks"}
C neyvia.onboarding.recommend includes-look:neyvia.onboarding.recommend(interests:[]) .chapters has "look"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"placement"},"tool":"neyvia.onboarding.recommend"},"key":"includes-placement","section":"checks"}
C neyvia.onboarding.recommend includes-placement:neyvia.onboarding.recommend(interests:[]) .chapters has "placement"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"watching"},"tool":"neyvia.onboarding.recommend"},"key":"includes-watching","section":"checks"}
C neyvia.onboarding.recommend includes-watching:neyvia.onboarding.recommend(interests:[]) .chapters has "watching"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"factory"},"tool":"neyvia.onboarding.recommend"},"key":"includes-factory","section":"checks"}
C neyvia.onboarding.recommend includes-factory:neyvia.onboarding.recommend(interests:[]) .chapters has "factory"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"connectors"},"tool":"neyvia.onboarding.recommend"},"key":"includes-connectors","section":"checks"}
C neyvia.onboarding.recommend includes-connectors:neyvia.onboarding.recommend(interests:[]) .chapters has "connectors"
-- @record {"chapter":"release-tour","data":{"args":{"interests":[]},"expect":{"op":"contains","path":"chapters","value":"images"},"tool":"neyvia.onboarding.recommend"},"key":"includes-images","section":"checks"}
C neyvia.onboarding.recommend includes-images:neyvia.onboarding.recommend(interests:[]) .chapters has "images"
-- @record {"chapter":"release-tour","data":{"args":{},"expect":{"op":"eq","path":"state.dom.mounted","value":true},"tool":"neyvia.view.state"},"key":"workspace-mounted","section":"checks"}
C neyvia.view.state workspace-mounted:neyvia.view.state() .state.dom.mounted == true
-- @record {"chapter":"release-tour","data":{"args":{},"expect":{"op":"eq","path":"state.dom.storage.warningVisible","value":true},"tool":"neyvia.view.state"},"key":"storage-warning-visible","section":"checks"}
C neyvia.view.state storage-warning-visible:neyvia.view.state() .state.dom.storage.warningVisible == true
-- @record {"chapter":"release-tour","data":{"args":{},"expect":{"op":"eq","path":"state.dom.storage.text","value":"Large local saves are unavailable. Saved data has been kept. Keep this window open until server sync completes, then reload to retry."},"tool":"neyvia.view.state"},"key":"storage-warning-honest","section":"checks"}
C neyvia.view.state storage-warning-honest:neyvia.view.state() .state.dom.storage.text == "Large local saves are unavailable. Saved data has been kept. Keep this window open until server sync completes, then reload to retry."
-- @record {"chapter":"release-tour","data":{"goal":"Open the real tour player and observe the mounted setup view.","inputs":{"$cl_type":"t16"},"steps":[{"action":"onboarding.open","args":{"step":"tour"},"check":"tour-mounted","save":"opened"}]},"key":"open-release-tour","section":"procedures"}
P open-release-tour():opened=neyvia.onboarding.open(step:"tour") C tour-mounted -- Open the real tour player and observe the mounted setup view.
V P open-release-tour -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"release-tour","data":{"goal":"Ensure every new feature is shown even when no interest is selected.","inputs":{"$cl_type":"t16"},"steps":[{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-basics","save":"basics"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-runtimes","save":"runtimes"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-notes","save":"notes"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-studio","save":"studio"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-laya","save":"laya"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-look","save":"look"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-placement","save":"placement"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-watching","save":"watching"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-factory","save":"factory"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-connectors","save":"connectors"},{"action":"onboarding.recommend","args":{"interests":[]},"check":"includes-images","save":"images"}]},"key":"verify-universal-features","section":"procedures"}
P verify-universal-features():basics=neyvia.onboarding.recommend(interests:[]) C includes-basics; runtimes=neyvia.onboarding.recommend(interests:[]) C includes-runtimes; notes=neyvia.onboarding.recommend(interests:[]) C includes-notes; studio=neyvia.onboarding.recommend(interests:[]) C includes-studio; laya=neyvia.onboarding.recommend(interests:[]) C includes-laya; look=neyvia.onboarding.recommend(interests:[]) C includes-look; placement=neyvia.onboarding.recommend(interests:[]) C includes-placement; watching=neyvia.onboarding.recommend(interests:[]) C includes-watching; factory=neyvia.onboarding.recommend(interests:[]) C includes-factory; connectors=neyvia.onboarding.recommend(interests:[]) C includes-connectors; images=neyvia.onboarding.recommend(interests:[]) C includes-images -- Ensure every new feature is shown even when no interest is selected.
V P verify-universal-features -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"release-tour","data":{"goal":"Verify the mounted workspace remains usable when large local storage fails, with a visible retained-data warning. This is a disposable failure-path contract.","inputs":{"$cl_type":"t16"},"steps":[{"action":"view.state","args":{},"check":"workspace-mounted","save":"workspace-mounted"},{"action":"view.state","args":{},"check":"storage-warning-visible","save":"storage-warning-visible"},{"action":"view.state","args":{},"check":"storage-warning-honest","save":"storage-warning-honest"}]},"key":"verify-storage-warning","section":"procedures"}
P verify-storage-warning():workspace-mounted=neyvia.view.state() C workspace-mounted; storage-warning-visible=neyvia.view.state() C storage-warning-visible; storage-warning-honest=neyvia.view.state() C storage-warning-honest -- Verify the mounted workspace remains usable when large local storage fails, with a visible retained-data warning. This is a disposable failure-path contract.
V P verify-storage-warning -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"release-tour","data":"No tour scene proves a microphone, paid generation, connector or recorded agent run is available.","key":"0","section":"frontier"}
F No tour scene proves a microphone, paid generation, connector or recorded agent run is available.
-- @record {"chapter":"release-tour","data":"The player uses shipped entry components and explicitly labelled examples. Availability still depends on this PC, provider sign-in and installed toolchains. These catalog checks prove coverage; inspect the rendered player separately.","key":"0","section":"guidance"}
M onboarding "The player uses shipped entry components and explicitly labelled examples. Availability still depends on this PC, provider sign-in and installed toolchains. These catalog checks prove coverage; inspect the rendered player separately." src:"authored manual" state:verified
