CL 1
L outputs v1 -- Authored executable manual
-- @manual {"chapters":{"navigation":{"title":"Shared pane navigation"},"overview":{"title":"Outputs and shared navigation"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"proofs-e-shell":{"title":"PROOFS-e shell state and action contracts"},"rendered-journey":{"title":"Rendered Outputs and ArtifactPane journey"}},"clVersion":"1.1","id":"outputs","kind":"environment","proofs":{"area":"proofs-e-models","manifests":["config/proofs/proofs-e-models.json","config/proofs/outputs-journey.json","config/proofs/semantic-outcomes.json"]},"schema":"neyvia.manual.v1","schemas":{"neyvia.app.open":"t1","neyvia.artifact.get":"t2","neyvia.artifact.list":"t3","neyvia.artifact.open":"t2","neyvia.artifact.publish":"t4","neyvia.pane.show":"live_schema_16","neyvia.state":"t6","proofs-e-models.status":"t6","proofs-e-shell.status":"t6"},"tool_metadata":{"neyvia.app.open":{"mutability_class":"none"},"neyvia.artifact.get":{"mutability_class":"read"},"neyvia.artifact.list":{"mutability_class":"read"},"neyvia.artifact.open":{"mutability_class":"none"},"neyvia.artifact.publish":{"mutability_class":"none"},"neyvia.pane.show":{"mutability_class":"none"},"neyvia.verify.status":{"mutability_class":"none"}}}
T live_schema_16 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str ..}
T live_schema_15 {kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOutputsModel.js:perceptionTarget -> checkedProofsEModel"],"claim":"Typed pane target preserves the caller's full path/session identifier","id":"outputs.perceptionTarget","impact":["outputs frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOutputsModel.js:parsePerceptionTarget -> checkedProofsEModel"],"claim":"Only image/file paths, HTTP(S) URLs and integer window targets are accepted; delimiters in paths/session ids survive","id":"outputs.parsePerceptionTarget","impact":["outputs frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOutputsModel.js:outsideDock -> checkedProofsEModel"],"claim":"Undocking requires crossing a known dock boundary by the requested margin","id":"outputs.outsideDock","impact":["outputs frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxOutputsModel.js:dropSpot -> checkedProofsEModel"],"claim":"Floating drops choose nearest side and a clamped vertical fraction","id":"outputs.dropSpot","impact":["outputs frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/NxOutputs.jsx","web/src/neyvia/next/NxArtifactPane.jsx","web/src/neyvia/next/NxLocalOnly.jsx","web/src/neyvia/next/nxSettingsApi.js","scripts/p22_outputs_journey.mjs"],"claim":"Mounted production Outputs shows a finite scratch report with available status and its Markdown content; the mounted ArtifactPane reopens the same content, and Local-only visibly refuses an external artifact URL without requesting it. Local route fixtures prove component rendering and gating only, not backend publication or retrieval.","id":"outputs.rendered-scratch-artifact-journey","impact":["Outputs list and published-status preview","ArtifactPane reopen behavior and local-only URL refusal"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.proofs_semantic_outcomes.outputs_publication","grant_agent.proofs_semantic_outcomes._outputs_assert_opened","grant_agent.neyvia_workspace_tools.WorkspaceTools.call","grant_agent.neyvia_workspace_tools.WorkspaceTools._call_unchecked","grant_agent.proof_contracts.invoke","grant_agent.neyvia_outputs.publish","grant_agent.neyvia_outputs.get","grant_agent.neyvia_outputs.listing","grant_agent.neyvia_outputs.call","grant_agent.neyvia_files_tools.guard","grant_agent.neyvia_workspace_tools.WorkspaceTools.safe_path","grant_agent.neyvia_panes.open_artifact","grant_agent.cl.renderer_effects.show"],"claim":"The production WorkspaceTools artifact actions publish an in-scope Markdown report with independently checked exact bytes and digest, replay an exact request idempotently, and return its exact preview with a persisted pending-renderer pane request. Changed bytes make the prior get/open unavailable and conflict with reuse of its requestId; a fresh request publishes a linked recoverable version. An outside-workspace path is refused by the Files guard before publication.","id":"outputs.backend-publication-byte-recovery","impact":["Native Outputs publication, identity, and retry behavior","Changed-byte refusal and linked-version recovery","Markdown preview payload and pending renderer handoff","Files-scope refusal before publication"],"phase":"post"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"app\":{\"type\":\"string\"},\"target\":{\"type\":\"string\"}},\"required\":[\"app\"],\"allOf\":[{\"properties\":{\"app\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t2 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{kind?:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" sessionId?:str runId?:str limit?:1..200 offset?:0.. ..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]},\"title\":{\"type\":\"string\"},\"sessionId\":{\"type\":\"string\"},\"runId\":{\"type\":\"string\"},\"requestId\":{\"type\":\"string\"},\"metadata\":{\"type\":\"object\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\"]}" target:str ..}
T t6{..}
T t7 json:"{\"type\":\"object\"}"
T t8{target:str ..}
T t9{artifacts:json:"{\"type\":\"array\"}" total:int ..}
T t10{ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..}
T t11{path:str kind:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" requestId:str}
T t12{path:str ..}
T t13{ok:bool ..}
T t14 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L outputs.navigation v1 -- Shared pane navigation
-- @record {"chapter":"navigation","data":{"effect":"Persist a shared UI bus request. UI acknowledgement proves rendered opening.","pre":"Selected workspace; typed target belongs to the requested pane","returns":{"type":"object"},"reversible":true,"schema":"neyvia.pane.show","tool":"neyvia.pane.show"},"key":"pane.show","section":"actions"}
A neyvia.pane.show(kind:json:"{\"type\":\"string\",\"enum\":[\"diff\",\"file\",\"artifact\",\"terminal\",\"browser\",\"mission\",\"replay\",\"builder\",\"accounts\",\"runtime\",\"settings\",\"preview\",\"outputs\",\"perception\",\"agentview\",\"sessions\",\"usage\",\"parallel\",\"agents\"]}" target:str) -> json:"{\"type\":\"object\"}" ! -- Persist a shared UI bus request. UI acknowledgement proves rendered opening.
C neyvia.pane.show pane-request-saved: neyvia.state().pane=={kind:"outputs" target:target}
-- @record {"chapter":"navigation","data":{"args":{},"expect":{"op":"eq","path":"pane","value":{"kind":"outputs","target":{"$input":"target"}}},"tool":"neyvia.state"},"key":"pane-request-saved","section":"checks"}
C neyvia.state pane-request-saved:neyvia.state() .pane == {kind:"outputs" target:target}
-- @record {"chapter":"navigation","data":{"goal":"Persist and independently observe the outputs pane request","inputs":{"$cl_type":"t8"},"steps":[{"action":"pane.show","args":{"kind":"outputs","target":{"$input":"target"}},"check":"pane-request-saved","save":"requested"}]},"key":"request-pane","section":"procedures"}
P request-pane(target:str):requested=neyvia.pane.show(kind:"outputs" target:target) C pane-request-saved -- Persist and independently observe the outputs pane request
V P request-pane -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"navigation","data":"A persisted bus request does not prove the UI rendered the pane.","key":"0","section":"frontier"}
F A persisted bus request does not prove the UI rendered the pane.
L outputs.overview v1 -- Outputs and shared navigation
-- @record {"chapter":"overview","data":{"args":{"limit":50},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t9"},"tool":"neyvia.artifact.list"},"key":"outputs","section":"state"}
S outputs.outputs:{artifacts:json:"{\"type\":\"array\"}" total:int ..}=neyvia.artifact.list(limit:50)
-- @record {"chapter":"overview","data":{"effect":"Register an existing output with hash and provenance in the shared Outputs panel. Reuse requestId for retries; changed bytes produce a new version.","pre":"Existing file inside Files scopes; exact requestId and hash on retries","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.artifact.publish","tool":"neyvia.artifact.publish"},"key":"artifact.publish","section":"actions"}
A neyvia.artifact.publish(path:str kind?:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" title?:str sessionId?:str runId?:str requestId?:str metadata?:json:"{\"type\":\"object\"}") -> {ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..} -- Register an existing output with hash and provenance in the shared Outputs panel. Reuse requestId for retries; changed bytes produce a new version.
C neyvia.artifact.publish published-bytes:neyvia.artifact.get(id:result.artifact.id) .availability == "available"
-- @record {"chapter":"overview","data":{"effect":"Read published outputs, newest first, with optional kind/session/run filters and pagination.","pre":"Selected workspace; limit 1-200, nonnegative offset","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.artifact.list","tool":"neyvia.artifact.list"},"key":"artifact.list","section":"actions"}
A neyvia.artifact.list(kind?:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" sessionId?:str runId?:str limit?:1..200 offset?:0..) -> {ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..} -- Read published outputs, newest first, with optional kind/session/run filters and pagination.
F verify-artifact-list "No authored observer check is bound to neyvia.artifact.list" -> ask operator blocks:neyvia.artifact.list
-- @record {"chapter":"overview","data":{"effect":"Read a publication and check whether its exact bytes are still available.","pre":"Known publication id; its bytes must be unchanged to open","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.artifact.get","tool":"neyvia.artifact.get"},"key":"artifact.get","section":"actions"}
A neyvia.artifact.get(id:str) -> {ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..} -- Read a publication and check whether its exact bytes are still available.
F verify-artifact-get "No authored observer check is bound to neyvia.artifact.get" -> ask operator blocks:neyvia.artifact.get
-- @record {"chapter":"overview","data":{"effect":"Verify published bytes, then open the existing guarded artifact/diff/file pane. Refuses changed or missing bytes.","pre":"Known publication id; its bytes must be unchanged to open","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.artifact.open","tool":"neyvia.artifact.open"},"key":"artifact.open","section":"actions"}
A neyvia.artifact.open(id:str) -> {ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..} -- Verify published bytes, then open the existing guarded artifact/diff/file pane. Refuses changed or missing bytes.
F verify-artifact-open "No authored observer check is bound to neyvia.artifact.open" -> ask operator blocks:neyvia.artifact.open
-- @record {"chapter":"overview","data":{"effect":"Open a ready app through the shared UI bus; refuses unfinished apps.","pre":"Known ready registry app or workspace pane; target is text","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.app.open","tool":"neyvia.app.open"},"key":"app.open","section":"actions"}
A neyvia.app.open(app:str target?:str) -> {ok:bool artifact?:{id:str sha256:str path:str ..} artifacts?:json:"{\"type\":\"array\"}" availability?:str event?:json:"{\"type\":\"object\"}" ..} ! -- Open a ready app through the shared UI bus; refuses unfinished apps.
F verify-app-open "No authored observer check is bound to neyvia.app.open" -> ask operator blocks:neyvia.app.open
-- @record {"chapter":"overview","data":{"args":{"id":{"$result":"published.artifact.id"}},"expect":{"op":"eq","path":"availability","value":"available"},"tool":"neyvia.artifact.get"},"key":"published-bytes","section":"checks"}
C neyvia.artifact.get published-bytes:neyvia.artifact.get(id:published.artifact.id) .availability == "available"
-- @record {"chapter":"overview","data":{"goal":"Register a real output, verify its bytes, and request its preview through the shared bus","inputs":{"$cl_type":"t11"},"steps":[{"action":"artifact.publish","args":{"kind":{"$input":"kind"},"path":{"$input":"path"},"requestId":{"$input":"requestId"}},"check":"published-bytes","save":"published"},{"action":"artifact.open","args":{"id":{"$result":"published.artifact.id"}},"save":"opened"}]},"key":"publish-and-open","section":"procedures"}
P publish-and-open(path:str kind:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" requestId:str):published=neyvia.artifact.publish(kind:kind path:path requestId:requestId) C published-bytes; opened=neyvia.artifact.open(id:published.artifact.id) -- Register a real output, verify its bytes, and request its preview through the shared bus
V P publish-and-open -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t12"},"steps":[{"action":"artifact.publish","args":{"path":{"$input":"path"}},"save":"effect"}]},"key":"verify-effect-artifact-publish","section":"procedures"}
P verify-effect-artifact-publish(path:str):effect=neyvia.artifact.publish(path:path) -- Verify the actual effect through fresh owning observers
V P verify-effect-artifact-publish -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Never label new bytes as the old publication; never run an output as a command","options":["publish-new-version","inspect-writer"],"question":"A published file changed. Is the new version an intended output?"},"key":"changed-output","section":"judge"}
J changed-output publish-new-version|inspect-writer:"A published file changed. Is the new version an intended output?" -- Never label new bytes as the old publication; never run an output as a command
V J changed-output -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"File changed or disappeared","recovery":"Use artifact.get; inspect the writer and publish a new version only for intended new bytes"},"key":"0","section":"pitfalls"}
X File changed or disappeared -> Use artifact.get; inspect the writer and publish a new version only for intended new bytes
-- @record {"chapter":"overview","data":{"failure":"Request id conflict","recovery":"Reuse the original request only for exact retries; choose a new id for a new intended publication"},"key":"1","section":"pitfalls"}
X Request id conflict -> Reuse the original request only for exact retries; choose a new id for a new intended publication
-- @record {"chapter":"overview","data":{"failure":"Navigation event emitted but no rendered proof","recovery":"Inspect the UI event ack and actual target; negative acks mean the screen is not wired"},"key":"2","section":"pitfalls"}
X Navigation event emitted but no rendered proof -> Inspect the UI event ack and actual target; negative acks mean the screen is not wired
-- @record {"chapter":"overview","data":"Dock-to-float gesture and classic-screen migration need Claude's rendered acceptance; backend bus receipts do not prove them","key":"0","section":"frontier"}
F Dock-to-float gesture and classic-screen migration need Claude's rendered acceptance; backend bus receipts do not prove them
-- @record {"chapter":"overview","data":"Publications retain path and hash, not immutable byte copies; an old version cannot open after its file changed","key":"1","section":"frontier"}
F Publications retain path and hash, not immutable byte copies; an old version cannot open after its file changed
-- @record {"chapter":"overview","data":"Existing third-party producers must call artifact.publish to join the gallery; no speculative whole-disk scan","key":"2","section":"frontier"}
F Existing third-party producers must call artifact.publish to join the gallery; no speculative whole-disk scan
-- @record {"chapter":"overview","data":"HTTP: /api/ui/outputs and /api/ui/navigation; desktop: artifact_publish/list/get/open_command and app_open_command","key":"0","section":"guidance"}
M outputs "HTTP: /api/ui/outputs and /api/ui/navigation; desktop: artifact_publish/list/get/open_command and app_open_command" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Output events: artifact.published; navigation events: app.open or pane.show. UI deduplicates bus ids and acknowledges rendered actions","key":"1","section":"guidance"}
M outputs "Output events: artifact.published; navigation events: app.open or pane.show. UI deduplicates bus ids and acknowledges rendered actions" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Source: src/grant_agent/neyvia_outputs.py and neyvia_voice.py; manual procedure makes deterministic tool calls with executable hash availability check","key":"2","section":"guidance"}
M outputs "Source: src/grant_agent/neyvia_outputs.py and neyvia_voice.py; manual procedure makes deterministic tool calls with executable hash availability check" src:"authored manual" state:verified
L outputs.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t13"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S outputs.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t14"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t6"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"outputs.perceptionTarget: Typed pane target preserves the caller's full path/session identifier","key":"0","section":"guidance"}
M outputs "outputs.perceptionTarget: Typed pane target preserves the caller's full path/session identifier" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"outputs.parsePerceptionTarget: Only image/file paths, HTTP(S) URLs and integer window targets are accepted; delimiters in paths/session ids survive","key":"1","section":"guidance"}
M outputs "outputs.parsePerceptionTarget: Only image/file paths, HTTP(S) URLs and integer window targets are accepted; delimiters in paths/session ids survive" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"outputs.outsideDock: Undocking requires crossing a known dock boundary by the requested margin","key":"2","section":"guidance"}
M outputs "outputs.outsideDock: Undocking requires crossing a known dock boundary by the requested margin" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"outputs.dropSpot: Floating drops choose nearest side and a clamped vertical fraction","key":"3","section":"guidance"}
M outputs "outputs.dropSpot: Floating drops choose nearest side and a clamped vertical fraction" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"4","section":"guidance"}
M outputs "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L outputs.proofs-e-shell v1 -- PROOFS-e shell state and action contracts
-- @record {"chapter":"proofs-e-shell","data":{"args":{},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t13"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S outputs.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-shell","data":{"effect":"Read the latest verification receipt without repeating shell actions","pre":"Selected local workspace; read only","returns":{"$cl_type":"t14"},"reversible":true,"schema":"proofs-e-shell.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the latest verification receipt without repeating shell actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-shell","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-shell","data":{"goal":"Observe the latest shell proof receipt without replaying mutations","inputs":{"$cl_type":"t6"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-shell-proof-receipt","section":"procedures"}
P read-shell-proof-receipt():receipt=neyvia.verify.status() C observed -- Observe the latest shell proof receipt without replaying mutations
V P read-shell-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-shell","data":{"failure":"A queue or shell state receipt is treated as rendered app proof","recovery":"Inspect the owned running UI and actual PDF/output/provider separately"},"key":"0","section":"pitfalls"}
X A queue or shell state receipt is treated as rendered app proof -> Inspect the owned running UI and actual PDF/output/provider separately
-- @record {"chapter":"proofs-e-shell","data":"Rendered shell journeys and PDF loading require owned UI proof","key":"0","section":"frontier"}
F Rendered shell journeys and PDF loading require owned UI proof
-- @record {"chapter":"proofs-e-shell","data":"Provider execution and actual artifact publishing are separate proof boundaries","key":"1","section":"frontier"}
F Provider execution and actual artifact publishing are separate proof boundaries
-- @record {"chapter":"proofs-e-shell","data":"artifact.published increments the Outputs refresh signal; announces only offscreen and requires artifact.id","key":"0","section":"guidance"}
M outputs "artifact.published increments the Outputs refresh signal; announces only offscreen and requires artifact.id" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-shell","data":"Startup runner: scripts/proofs-e-shell.mjs --root <owned-scratch>; area proofs-e-shell checks five composed production journeys and eleven semantic corruptions","key":"1","section":"guidance"}
M outputs "Startup runner: scripts/proofs-e-shell.mjs --root <owned-scratch>; area proofs-e-shell checks five composed production journeys and eleven semantic corruptions" src:"authored manual" state:verified
L outputs.rendered-journey v1 -- Mounted Outputs and ArtifactPane outcomes
-- @record {"chapter":"rendered-journey","data":"The finite fixture drives production React components through local intercepted routes. It proves visible component content/status and local-only URL refusal; it does not prove the backend published or retrieved a real artifact.","key":"0","section":"frontier"}
F The finite fixture drives production React components through local intercepted routes. It proves visible component content/status and local-only URL refusal; it does not prove the backend published or retrieved a real artifact.
-- @record {"chapter":"rendered-journey","data":"Run scripts/p22_outputs_journey.mjs --root <owned-scratch> with the assigned Obscura ports. The receipt contains the exact scratch artifact hash and mounted DOM observations.","key":"0","section":"guidance"}
M outputs "Run scripts/p22_outputs_journey.mjs --root <owned-scratch> with the assigned Obscura ports. The receipt contains the exact scratch artifact hash and mounted DOM observations." src:"authored manual" state:verified
