CL 1
L parallel v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Parallel worktrees and connected agent coordination"},"filmbugs":{"title":"Launch film behavior contracts"}},"clVersion":"1.1","id":"parallel","kind":"environment","proofs":{"area":"parallel"},"schema":"neyvia.manual.v1","schemas":{"neyvia.parallel.answer":"t4","neyvia.parallel.ask":"t3","neyvia.parallel.done":"t5","neyvia.parallel.finish":"t7","neyvia.parallel.merge":"t6","neyvia.parallel.resolved":"t6","neyvia.parallel.settle":"t6","neyvia.parallel.start":"t1","neyvia.parallel.state":"t2","neyvia.parallel.stop":"t6"},"tool_metadata":{"neyvia.parallel.answer":{"mutability_class":"external_action"},"neyvia.parallel.ask":{"mutability_class":"external_action"},"neyvia.parallel.done":{"mutability_class":"external_action"},"neyvia.parallel.finish":{"mutability_class":"external_action"},"neyvia.parallel.merge":{"mutability_class":"external_action"},"neyvia.parallel.resolved":{"mutability_class":"external_action"},"neyvia.parallel.settle":{"mutability_class":"external_action"},"neyvia.parallel.start":{"mutability_class":"external_action"},"neyvia.parallel.state":{"mutability_class":"read"},"neyvia.parallel.stop":{"mutability_class":"external_action"}}}
-- @proof {"id":"parallel.pending-question-retry","phase":"invariant","claim":"Repeating an identical unanswered worker ask reuses the saved question without a second delivery; an answer resolves identical historical pending duplicates, preserving unrelated questions.","checkedAt":["grant_agent.neyvia_parallel.action"],"impact":["Launch film behavior"]}
-- @proof {"id":"parallel.mod-worker-done","phase":"invariant","claim":"The native Claude mod Parallel call executes the server-supplied observer-bound CL recovery within the mod catalog and existing owner grants; done still requires a clean committed branch and answered questions.","checkedAt":["grant_agent.claude_code_host.call_tool","grant_agent.cl.parallel_effects.verify"],"impact":["Launch film behavior"]}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.start","grant_agent.cl.parallel_effects.verify"],"claim":"Reject dirty checkout, invalid routes, duplicate tracks and tracks outside 1..8","id":"parallel.clean-start","impact":["parallel state","Git history","connected sessions"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.start","grant_agent.cl.parallel_effects.verify"],"claim":"Every main/worker branch and session has its own owned worktree from base; original checkout unchanged","id":"parallel.separate-worktrees","impact":["parallel state","Git history","connected sessions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"claim":"Questions and answers retain identity and delivery receipts through existing mid-turn inbox or resumed session","id":"parallel.question-answer","impact":["parallel state","Git history","connected sessions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"claim":"Done refuses dirty trees, absent commits and unanswered questions","id":"parallel.committed-done","impact":["parallel state","Git history","connected sessions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.merge","grant_agent.cl.parallel_effects.verify"],"claim":"Track order is preserved; conflict records files, both sides and summaries and pauses subsequent merges","id":"parallel.ordered-conflict","impact":["parallel state","Git history","connected sessions"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"claim":"Resolved refuses unmerged index and markers, commits merge then continues; checks determine readiness","id":"parallel.resolution","impact":["parallel state","Git history","connected sessions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"claim":"Finish requires passing checks, allowFinish and clean original base; diverged base refuses ff-only","id":"parallel.finish-authority","impact":["parallel state","Git history","connected sessions"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"claim":"Only owned sessions stop; initialized valid trees are checked clean, owned orphans and interrupted initial checkouts are recoverable, reparse points unlinked without traversal, git list verified; committed unmerged branches retained","id":"parallel.safe-settle","impact":["parallel state","Git history","connected sessions"],"phase":"post"}
-- @proof {"id":"parallel.orphan-settle","claim":"Missing linked Git metadata or an orphaned owned folder is safely removed after unlinking reparse points; prune verifies absence; every main and worker track has a durable cleanup receipt; retry is idempotent","checkedAt":["grant_agent.neyvia_parallel_git.worktree_status","grant_agent.neyvia_parallel_git.remove_worktree","grant_agent.cl.parallel_effects.verify"],"phase":"post","impact":["parallel state","Git history","connected sessions"]}
-- @proof {"id":"parallel.failed-start-settle","claim":"A partial start retains a saved failed run; settle removes initialized and never-initialized owned worktrees and branches still at base, preserving committed unmerged work","checkedAt":["grant_agent.neyvia_parallel.start","grant_agent.neyvia_parallel.action","grant_agent.cl.parallel_effects.verify"],"phase":"post","impact":["parallel state","Git history","connected sessions"]}
-- @proof {"id":"parallel.availability-retry","claim":"Explicit Claude starts allow two availability attempts of at most 45 seconds each on timeout, bypass cached failed discovery, and never retry session creation","checkedAt":["grant_agent.connected_sessions.registry.Registry.availability","grant_agent.connected_sessions.broker.ConnectedBroker.new"],"phase":"post","impact":["parallel state","Git history","connected sessions"]}
T t1{repo:str#1.. base?:str#1.. goal:str#1.. tracks:[{agent?:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]}" model?:str#1.. effort?:json:"{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}" id:str#1.. title:str#1.. brief:str#1..}]#1..8 main?:json:"{\"type\":\"object\",\"properties\":{\"agent\":{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]},\"model\":{\"type\":\"string\",\"minLength\":1},\"effort\":{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}},\"additionalProperties\":false}" allowFinish?:bool checkCommand?:str#1.. checkTimeoutSeconds?:1..3600 sparsePaths?:[str#1..]#1.. ..}
T t2{run?:str#1.. ..}
T t3{run:str#1.. track:str#1.. question:str#1.. ..}
T t4{run:str#1.. track:str#1.. answer:str#1.. questionId?:str#1.. ..}
T t5{run:str#1.. track:str#1.. summary:str#1.. ..}
T t6{run:str#1.. ..}
T t7{run:str#1.. into?:str#1.. ..}
T t8{ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..}
T t9 json:"{\"type\":\"object\"}"
T t10{repo:str#1.. goal:str#1.. tracks:[{agent?:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]}" model?:str#1.. effort?:json:"{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}" id:str#1.. title:str#1.. brief:str#1..}]#1..8 ..}
T t11{run:str#1.. track:str#1.. answer:str#1.. ..}
L parallel.overview v1 -- Parallel worktrees and connected agent coordination
-- @record {"chapter":"overview","data":{"args":{"run":{"$input":"run"}},"inputs":{"$cl_type":"t6"},"shape":{"$cl_type":"t8"},"tool":"neyvia.parallel.state"},"key":"state","section":"state"}
S parallel.state:{ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..}=neyvia.parallel.state(run:run)
-- @record {"chapter":"overview","data":{"effect":"Start a main agent and 1–8 workers in separate branches and worktrees.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.start","tool":"neyvia.parallel.start"},"key":"start","section":"actions"}
A neyvia.parallel.start(repo:str#1.. base?:str#1.. goal:str#1.. tracks:[{agent?:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]}" model?:str#1.. effort?:json:"{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}" id:str#1.. title:str#1.. brief:str#1..}]#1..8 main?:json:"{\"type\":\"object\",\"properties\":{\"agent\":{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]},\"model\":{\"type\":\"string\",\"minLength\":1},\"effort\":{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}},\"additionalProperties\":false}" allowFinish?:bool checkCommand?:str#1.. checkTimeoutSeconds?:1..3600 sparsePaths?:[str#1..]#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Start a main agent and 1–8 workers in separate branches and worktrees.
C neyvia.parallel.start start-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Observe saved runs, current session activity and Git state.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t9"},"reversible":false,"schema":"neyvia.parallel.state","tool":"neyvia.parallel.state"},"key":"state","section":"actions"}
A neyvia.parallel.state(run?:str#1..) -> json:"{\"type\":\"object\"}" -- Observe saved runs, current session activity and Git state.
F verify-state "No authored observer check is bound to neyvia.parallel.state" -> ask operator blocks:neyvia.parallel.state
-- @record {"chapter":"overview","data":{"effect":"Send a worker question to the main agent through the connected inbox.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.ask","tool":"neyvia.parallel.ask"},"key":"ask","section":"actions"}
A neyvia.parallel.ask(run:str#1.. track:str#1.. question:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Send a worker question to the main agent through the connected inbox.
C neyvia.parallel.ask ask-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Deliver the main agent answer to the worker, including mid-turn.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.answer","tool":"neyvia.parallel.answer"},"key":"answer","section":"actions"}
A neyvia.parallel.answer(run:str#1.. track:str#1.. answer:str#1.. questionId?:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Deliver the main agent answer to the worker, including mid-turn.
C neyvia.parallel.answer answer-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Verify a clean committed worker branch and merge when all tracks are done.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.done","tool":"neyvia.parallel.done"},"key":"done","section":"actions"}
A neyvia.parallel.done(run:str#1.. track:str#1.. summary:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Verify a clean committed worker branch and merge when all tracks are done.
C neyvia.parallel.done done-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Merge ready worker branches in track order; pause and notify on conflict.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.merge","tool":"neyvia.parallel.merge"},"key":"merge","section":"actions"}
A neyvia.parallel.merge(run:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Merge ready worker branches in track order; pause and notify on conflict.
C neyvia.parallel.merge merge-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Verify staged conflict resolution, commit the merge and continue.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.resolved","tool":"neyvia.parallel.resolved"},"key":"resolved","section":"actions"}
A neyvia.parallel.resolved(run:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Verify staged conflict resolution, commit the merge and continue.
C neyvia.parallel.resolved resolved-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Stop owned sessions and safely remove clean worktrees; retain unmerged branches.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.settle","tool":"neyvia.parallel.settle"},"key":"settle","section":"actions"}
A neyvia.parallel.settle(run:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Stop owned sessions and safely remove clean worktrees; retain unmerged branches.
C neyvia.parallel.settle settle-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"Stop only this run main and worker sessions, preserving branches and worktrees.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.stop","tool":"neyvia.parallel.stop"},"key":"stop","section":"actions"}
A neyvia.parallel.stop(run:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- Stop only this run main and worker sessions, preserving branches and worktrees.
C neyvia.parallel.stop stop-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"effect":"With checks passed and allowFinish enabled, integrate into the clean base checkout.","pre":"Owner-authorized repository and exact saved run scope; preserve all uncommitted work","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.parallel.finish","tool":"neyvia.parallel.finish"},"key":"finish","section":"actions"}
A neyvia.parallel.finish(run:str#1.. into?:str#1..) -> {ok:bool run:{id:str#1.. state:str repo:str tracks:[json:"{\"type\":\"object\"}"] ..} ..} ! -- With checks passed and allowFinish enabled, integrate into the clean base checkout.
C neyvia.parallel.finish finish-observed:neyvia.parallel.state(run:result.run.id) .run.id == result.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"start-observed","section":"checks"}
C neyvia.parallel.state start-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"ask-observed","section":"checks"}
C neyvia.parallel.state ask-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"answer-observed","section":"checks"}
C neyvia.parallel.state answer-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"done-observed","section":"checks"}
C neyvia.parallel.state done-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"merge-observed","section":"checks"}
C neyvia.parallel.state merge-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"resolved-observed","section":"checks"}
C neyvia.parallel.state resolved-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"settle-observed","section":"checks"}
C neyvia.parallel.state settle-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"stop-observed","section":"checks"}
C neyvia.parallel.state stop-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"args":{"run":{"$result":"receipt.run.id"}},"expect":{"op":"eq","path":"run.id","value":{"$result":"receipt.run.id"}},"tool":"neyvia.parallel.state"},"key":"finish-observed","section":"checks"}
C neyvia.parallel.state finish-observed:neyvia.parallel.state(run:receipt.run.id) .run.id == receipt.run.id
-- @record {"chapter":"overview","data":{"goal":"Start a main agent and 1–8 workers in separate branches and worktrees. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t10"},"steps":[{"action":"start","args":{"goal":{"$input":"goal"},"repo":{"$input":"repo"},"tracks":{"$input":"tracks"}},"check":"start-observed","save":"receipt"}]},"key":"start","section":"procedures"}
P start(repo:str#1.. goal:str#1.. tracks:[{agent?:json:"{\"type\":\"string\",\"enum\":[\"claude-code\",\"codex\",\"opencode\"]}" model?:str#1.. effort?:json:"{\"type\":\"string\",\"enum\":[\"low\",\"medium\",\"high\"]}" id:str#1.. title:str#1.. brief:str#1..}]#1..8):receipt=neyvia.parallel.start(goal:goal repo:repo tracks:tracks) C start-observed -- Start a main agent and 1–8 workers in separate branches and worktrees. Verify the fresh subject-bound effect and read saved state.
V P start -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Send a worker question to the main agent through the connected inbox. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t3"},"steps":[{"action":"ask","args":{"question":{"$input":"question"},"run":{"$input":"run"},"track":{"$input":"track"}},"check":"ask-observed","save":"receipt"}]},"key":"ask","section":"procedures"}
P ask(run:str#1.. track:str#1.. question:str#1..):receipt=neyvia.parallel.ask(question:question run:run track:track) C ask-observed -- Send a worker question to the main agent through the connected inbox. Verify the fresh subject-bound effect and read saved state.
V P ask -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Deliver the main agent answer to the worker, including mid-turn. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t11"},"steps":[{"action":"answer","args":{"answer":{"$input":"answer"},"run":{"$input":"run"},"track":{"$input":"track"}},"check":"answer-observed","save":"receipt"}]},"key":"answer","section":"procedures"}
P answer(run:str#1.. track:str#1.. answer:str#1..):receipt=neyvia.parallel.answer(answer:answer run:run track:track) C answer-observed -- Deliver the main agent answer to the worker, including mid-turn. Verify the fresh subject-bound effect and read saved state.
V P answer -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify a clean committed worker branch and merge when all tracks are done. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t5"},"steps":[{"action":"done","args":{"run":{"$input":"run"},"summary":{"$input":"summary"},"track":{"$input":"track"}},"check":"done-observed","save":"receipt"}]},"key":"done","section":"procedures"}
P done(run:str#1.. track:str#1.. summary:str#1..):receipt=neyvia.parallel.done(run:run summary:summary track:track) C done-observed -- Verify a clean committed worker branch and merge when all tracks are done. Verify the fresh subject-bound effect and read saved state.
V P done -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Merge ready worker branches in track order; pause and notify on conflict. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t6"},"steps":[{"action":"merge","args":{"run":{"$input":"run"}},"check":"merge-observed","save":"receipt"}]},"key":"merge","section":"procedures"}
P merge(run:str#1..):receipt=neyvia.parallel.merge(run:run) C merge-observed -- Merge ready worker branches in track order; pause and notify on conflict. Verify the fresh subject-bound effect and read saved state.
V P merge -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify staged conflict resolution, commit the merge and continue. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t6"},"steps":[{"action":"resolved","args":{"run":{"$input":"run"}},"check":"resolved-observed","save":"receipt"}]},"key":"resolved","section":"procedures"}
P resolved(run:str#1..):receipt=neyvia.parallel.resolved(run:run) C resolved-observed -- Verify staged conflict resolution, commit the merge and continue. Verify the fresh subject-bound effect and read saved state.
V P resolved -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Stop owned sessions and safely remove clean worktrees; retain unmerged branches. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t6"},"steps":[{"action":"settle","args":{"run":{"$input":"run"}},"check":"settle-observed","save":"receipt"}]},"key":"settle","section":"procedures"}
P settle(run:str#1..):receipt=neyvia.parallel.settle(run:run) C settle-observed -- Stop owned sessions and safely remove clean worktrees; retain unmerged branches. Verify the fresh subject-bound effect and read saved state.
V P settle -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Stop only this run main and worker sessions, preserving branches and worktrees. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t6"},"steps":[{"action":"stop","args":{"run":{"$input":"run"}},"check":"stop-observed","save":"receipt"}]},"key":"stop","section":"procedures"}
P stop(run:str#1..):receipt=neyvia.parallel.stop(run:run) C stop-observed -- Stop only this run main and worker sessions, preserving branches and worktrees. Verify the fresh subject-bound effect and read saved state.
V P stop -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"With checks passed and allowFinish enabled, integrate into the clean base checkout. Verify the fresh subject-bound effect and read saved state.","inputs":{"$cl_type":"t6"},"steps":[{"action":"finish","args":{"run":{"$input":"run"}},"check":"finish-observed","save":"receipt"}]},"key":"finish","section":"procedures"}
P finish(run:str#1..):receipt=neyvia.parallel.finish(run:run) C finish-observed -- With checks passed and allowFinish enabled, integrate into the clean base checkout. Verify the fresh subject-bound effect and read saved state.
V P finish -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"A worker reports done without a committed clean branch","recovery":"Inspect Git status and commits; preserve changes and commit before done"},"key":"0","section":"pitfalls"}
X A worker reports done without a committed clean branch -> Inspect Git status and commits; preserve changes and commit before done
-- @record {"chapter":"overview","data":{"failure":"A merge conflicts or checks fail","recovery":"Resolve in main integration worktree, stage and call resolved; rerun merge for checks after repair"},"key":"1","section":"pitfalls"}
X A merge conflicts or checks fail -> Resolve in main integration worktree, stage and call resolved; rerun merge for checks after repair
-- @record {"chapter":"overview","data":{"failure":"Settle sees dirty worktrees or a session is still stopping","recovery":"Preserve the work and finish session shutdown; retry settle after inspecting state"},"key":"2","section":"pitfalls"}
X Settle sees dirty worktrees or a session is still stopping -> Preserve the work and finish session shutdown; retry settle after inspecting state
-- @record {"chapter":"overview","data":"Screenshots require the UI builder pane; Git and session receipts do not prove rendered behavior","key":"0","section":"frontier"}
F Screenshots require the UI builder pane; Git and session receipts do not prove rendered behavior
-- @record {"chapter":"overview","data":"Provider sign-in and scratch-folder trust use the existing connected-session approval path","key":"1","section":"frontier"}
F Provider sign-in and scratch-folder trust use the existing connected-session approval path
-- @record {"chapter":"overview","data":"Use main integration worktree; backend owns ordered merges. Workers ask and report done using exact run/track IDs.","key":"0","section":"guidance"}
M parallel "Use main integration worktree; backend owns ordered merges. Workers ask and report done using exact run/track IDs." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Finish defaults to leaving integration history intact. Set allowFinish at start only with authorization.","key":"1","section":"guidance"}
M parallel "Finish defaults to leaving integration history intact. Set allowFinish at start only with authorization." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Start action accepts checkCommand, checkTimeoutSeconds and sparsePaths; procedure uses required fields. Otherwise configure .neyvia/parallel.json checkCommand or use the existing Stop gate.","key":"2","section":"guidance"}
M parallel "Start action accepts checkCommand, checkTimeoutSeconds and sparsePaths; procedure uses required fields. Otherwise configure .neyvia/parallel.json checkCommand or use the existing Stop gate." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Native actions are subject-bound through parallel_effects; state checks reread durable state, session ownership and Git.","key":"3","section":"guidance"}
M parallel "Native actions are subject-bound through parallel_effects; state checks reread durable state, session ownership and Git." src:"authored manual" state:verified
L parallel.filmbugs v1 -- Launch film behavior contracts
-- @record {"chapter":"filmbugs","section":"guidance","key":"0","data":"Repeating an identical unanswered worker ask reuses the saved question without a second delivery; an answer resolves identical historical pending duplicates, preserving unrelated questions."}
M parallel "Repeating an identical unanswered worker ask reuses the saved question without a second delivery; an answer resolves identical historical pending duplicates, preserving unrelated questions." src:"authored manual" state:verified
-- @record {"chapter":"filmbugs","section":"guidance","key":"1","data":"The native Claude mod Parallel call executes the server-supplied observer-bound CL recovery within the mod catalog and existing owner grants; done still requires a clean committed branch and answered questions."}
M parallel "The native Claude mod Parallel call executes the server-supplied observer-bound CL recovery within the mod catalog and existing owner grants; done still requires a clean committed branch and answered questions." src:"authored manual" state:verified
