CL 1
L proofs-b-browser v1 -- Authored executable manual
-- @manual {"chapters":{"proofs-b-harness-browser":{"title":"PROOFS-b: actual local Harness blocker and capacity presentation"}},"clVersion":"1.1","id":"proofs-b-browser","kind":"environment","proofs":{"area":"proofs-b-browser","manifests":["config/proofs/proofs-b-browser.json"],"startup":{"procedures":["proofs-b-harness-browser/read-latest"],"runner":"scripts/proofs-b-browser.mjs","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.verify.status":"t1"},"tool_metadata":{"neyvia.verify.status":{}}}
-- @proof {"checkedAt":["web/src/neyvia/HarnessesSurface.jsx:receiptView and rendered flags/controls/output","web/src/neyvia/proofsBViewContracts.js:checkHarnessView","grant_agent.harness_jobs.HarnessJobStore.cancel"],"claim":"Every Harness render consumes a checked view: blocked is actionable and nonterminal, cleanup/retry follow durable lifecycle, and blocked or cleaned-up blocker output preserves the structured result. A real Chrome fixture proves retry preserves original receipt bytes and explicit cleanup preserves the blocker result.","id":"proofs-b.browser.blocked-receipt","impact":["Harness receipt","retry and cleanup controls","original blocker evidence"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/HarnessesSurface.jsx:receiptView and queue rows","web/src/neyvia/proofsBViewContracts.js:checkHarnessView"],"claim":"Every receipt and queue label, including the accessible queue name, is checked against durable waitingReason: execution-capacity is waiting for capacity rather than active execution.","id":"proofs-b.browser.capacity-label","impact":["receipt status","visible queue label","accessible queue label"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/HarnessesSurface.jsx:receiptView.output","web/src/neyvia/proofsBViewContracts.js:checkHarnessView"],"claim":"When a capacity-wait job has no result/error, the checked receipt output explains the workspace capacity wait and explicitly says no execution slot is claimed.","id":"proofs-b.browser.capacity-explanation","impact":["execution-wait context","operator execution claims"],"phase":"post"}
T t1{..}
T t2{}
T t3{ok:true available:bool ..}
T t4 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}"
L proofs-b-browser.proofs-b-harness-browser v1 -- PROOFS-b: actual local Harness blocker and capacity presentation
-- @record {"chapter":"proofs-b-harness-browser","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-browser.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-harness-browser","data":{"effect":"Observe the existing proof boundary without replaying actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe the existing proof boundary without replaying actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-harness-browser","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-harness-browser","data":{"goal":"Read the latest browser proof boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest browser proof boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-harness-browser","data":{"failure":"A local saved-state browser journey is mistaken for successful provider inference or real capacity scheduling","recovery":"Read the fixture provenance and contract scope; infer only the rendered labels/actions and preserved local records."},"key":"0","section":"pitfalls"}
X A local saved-state browser journey is mistaken for successful provider inference or real capacity scheduling -> Read the fixture provenance and contract scope; infer only the rendered labels/actions and preserved local records.
-- @record {"chapter":"proofs-b-harness-browser","data":{"failure":"An older served bundle is mistaken for the checked implementation","recovery":"Require source stability, actual fetched bundle bytes matching the owned build, and the semantic guard in a loaded bundle."},"key":"1","section":"pitfalls"}
X An older served bundle is mistaken for the checked implementation -> Require source stability, actual fetched bundle bytes matching the owned build, and the semantic guard in a loaded bundle.
-- @record {"chapter":"proofs-b-harness-browser","data":"General conversation-fabric verifier case and 75 desktop source cases remain unproven.","key":"0","section":"frontier"}
F General conversation-fabric verifier case and 75 desktop source cases remain unproven.
-- @record {"chapter":"proofs-b-harness-browser","data":"Native desktop/device, real provider inference and actual worker capacity scheduling are separate proof boundaries.","key":"1","section":"frontier"}
F Native desktop/device, real provider inference and actual worker capacity scheduling are separate proof boundaries.
-- @record {"chapter":"proofs-b-harness-browser","data":"Every HarnessesSurface render consumes checkHarnessView labels, terminal/attention flags, cleanup/retry permissions and receipt output.","key":"0","section":"guidance"}
M proofs-b-browser "Every HarnessesSurface render consumes checkHarnessView labels, terminal/attention flags, cleanup/retry permissions and receipt output." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-harness-browser","data":"Trusted startup runner: scripts/proofs-b-browser.mjs --root <owned scratch root> --json.","key":"1","section":"guidance"}
M proofs-b-browser "Trusted startup runner: scripts/proofs-b-browser.mjs --root <owned scratch root> --json." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-harness-browser","data":"The runner starts only its own loopback backend48472 and Chrome CDP48478 with a fresh browser profile and isolated backend homes; page requests are limited to the exact fixture origin.","key":"2","section":"guidance"}
M proofs-b-browser "The runner starts only its own loopback backend48472 and Chrome CDP48478 with a fresh browser profile and isolated backend homes; page requests are limited to the exact fixture origin." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-harness-browser","data":"Only Chrome receives conventional Windows USERPROFILE/APPDATA path metadata reconstructed from HOMEDRIVE and HOMEPATH, because isolated metadata prevents its DevTools admission. CDP attests the actual user-data-dir equals the fresh owned profile. Node/backend/provider homes remain isolated; the runner never reads operator profile or credential files.","key":"3","section":"guidance"}
M proofs-b-browser "Only Chrome receives conventional Windows USERPROFILE/APPDATA path metadata reconstructed from HOMEDRIVE and HOMEPATH, because isolated metadata prevents its DevTools admission. CDP attests the actual user-data-dir equals the fresh owned profile. Node/backend/provider homes remain isolated; the runner never reads operator profile or credential files." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-harness-browser","data":"The fixture skips nested proof startup to prevent recursive verifier launch; parent startup readiness is proven separately.","key":"4","section":"guidance"}
M proofs-b-browser "The fixture skips nested proof startup to prevent recursive verifier launch; parent startup readiness is proven separately." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-harness-browser","data":"Real actions select waiting and blocked records, prepare retry, inspect exact original receipt hashes, and explicitly cancel/clean up while preserving blocker evidence.","key":"5","section":"guidance"}
M proofs-b-browser "Real actions select waiting and blocked records, prepare retry, inspect exact original receipt hashes, and explicitly cancel/clean up while preserving blocker evidence." src:"authored manual" state:verified
