CL 1
L proofs-b-adapters v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"PROOFS-b adapter contract evidence boundaries"},"proofs-b-comparison":{"title":"PROOFS-b comparison production contracts and local evidence"},"proofs-b-git":{"title":"PROOFS-b git production contracts and local evidence"},"proofs-b-handoff":{"title":"PROOFS-b handoff production contracts and local evidence"},"proofs-b-html":{"title":"PROOFS-b html production contracts and local evidence"},"proofs-b-native-sync":{"title":"PROOFS-b native sync action contracts and isolated startup"},"proofs-b-ocr":{"title":"PROOFS-b ocr production contracts and local evidence"},"proofs-b-publication":{"title":"PROOFS-b publication production contracts and local evidence"},"proofs-b-release":{"title":"PROOFS-b release production contracts and local evidence"},"proofs-b-sync":{"title":"PROOFS-b sync production contracts and local evidence"}},"clVersion":"1.1","id":"proofs-b-adapters","kind":"environment","proofs":{"area":"proofs-b-adapters","manifests":["config/proofs/proofs-b-adapters.json"],"startup":{"procedures":["adapters.release.selection","adapters.release.update","adapters.release.staging","adapters.git.objects","adapters.git.safety","adapters.ocr.boundaries","adapters.handoff.progress","adapters.comparison.grading","adapters.comparison.leader","adapters.html.scoring","adapters.workflow.publication","adapters.sync.compatibility","adapters.git.readiness","adapters.git.artifact-registration","adapters.sync.policy","adapters.sync.native-runtime","adapters.sync.plan-activation","adapters.sync.stale","adapters.sync.rollback","adapters.sync.recovery","adapters.sync.discovery"],"runner":"grant_agent.proofs_b_adapters.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.verify.status":"t1"},"tool_metadata":{"neyvia.verify.status":{}}}
-- @proof {"checkedAt":["grant_agent.github_release_source.parse_github_ref","grant_agent.github_release_source.normalize_version","grant_agent.github_release_source.select_release","grant_agent.github_release_source.select_platform_asset","grant_agent.github_release_source.find_checksum_for","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Select only published channel/version releases, accept only recognized GitHub references, normalize v-prefixed numeric versions and select matching platform/checksum metadata.","id":"adapters.release.selection","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.github_release_source.check_for_update","grant_agent.github_release_source.fetch_releases","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Update checks observe metadata without package bytes; uncertain ordering, unreachable metadata and missing platform artifacts remain unknown; installed newer versions are never downgraded.","id":"adapters.release.update","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.github_release_source.download_asset","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Successful staged files match reported byte count/digest and supplied publisher checksum; absent checksums remain explicitly unverified and declared size differences retain warnings. Checksum rejection preserves prior target. Actual HTTP Content-Length mismatch rejects premature EOF before atomic staging, preserving any prior valid target.","id":"adapters.release.staging","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.git_reference_adapter.GitReferenceAdapter.execute","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Inspect/history/show/ancestry read actual Git objects and return durable receipt bytes whose digest and HEAD/output lineage match the result.","id":"adapters.git.objects","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.git_reference_adapter.GitReferenceAdapter.execute","grant_agent.git_reference_adapter.GitReferenceAdapter._config","grant_agent.git_reference_adapter.GitReferenceAdapter._attributes","grant_agent.git_reference_adapter.GitReferenceAdapter._repository","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Every Git action validates local helper/filter/protocol/include restrictions, attributes/object-store/worktree boundaries, consistency snapshots and network denial before issuing a success receipt.","id":"adapters.git.safety","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_renderer_duplicate","grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_table_boundary","grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_formula_boundary","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"OCR text repair changes only an evidenced repeated renderer prefix, complete HTML table boundary or exact repeated display-math block; nonmatching and unfinished specimens remain byte-identical.","id":"adapters.ocr.boundaries","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.handoff.create_handoff_packet","grant_agent.handoff.save_handoff_packet","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Handoff packets preserve session lineage, objective, prompt stack, completed/remaining plan and next actions, including durable JSON serialization.","id":"adapters.handoff.progress","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.harness_comparison.grade_output","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Protocol grading compares every expected field to parsed observations and exact correctness requires every field; omitted and altered fields fail.","id":"adapters.comparison.grading","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.harness_comparison.eligibility","grant_agent.harness_comparison.capability_coverage","grant_agent.harness_comparison.summarize_attempts","grant_agent.harness_comparison.select_leader","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Unready/security harnesses are ineligible; leaders require complete exact receipt-backed read-only route-intact samples and prefer essential capability coverage while retaining observed execution median.","id":"adapters.comparison.leader","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.html_site_benchmark.grade_html","grant_agent.html_site_benchmark.combine_score","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Static HTML rubric sums only earned points out of 80; combined acceptance requires total at least75 and independently observed browser score at least12. Frozen prompt requires a single offline index.html and 390px.","id":"adapters.html.scoring","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/check_workflow_publication_integrity.py:audit_workflows","grant_agent.proofs_b_adapters.self_check:actual_repository_workflow_audit"],"claim":"Every publication audit reads actual workflow files and rejects git push including shell continuation, PR mutation, write APIs, blanket write permission and retired native branch regardless of read-only declared permissions.","id":"adapters.workflow.publication","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService.compatibility_snapshot","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Compatibility reports actual local file identity and hashes; hashVerified is true only when installed digest matches nonempty expected digest. Public transport reports credential availability without exposing the key.","id":"adapters.sync.compatibility","impact":["adapter result bytes","manual proofs-b-adapters chapter","caller observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.tool_manifest_registry.ToolManifest.from_payload","grant_agent.tool_manifest_registry.ToolManifest.readiness_as_dict","grant_agent.tool_manifest_registry.ToolManifestRegistry._runtime_readiness","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"A tool with a valid contract becomes execution-ready only with a currently hash/version-verified actual adapter and no execution prerequisites; production readiness additionally requires Boolean validated evidence and no production prerequisites. Discovery preserves agentReady while filtering live execution readiness.","id":"adapters.git.readiness","impact":["capability discovery readiness","native adapter admission","production claims"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.capability_service.CapabilityService.execute_tool_operation","grant_agent.capability_service.CapabilityService._register_adapter_artifacts","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters.self_check"],"claim":"Capability service executes the actual pinned local Git operation, validates output and registers real hash/lineage-bound receipts; bad declared digests or output lineage are rejected before artifact graph mutation.","id":"adapters.git.artifact-registration","impact":["artifact graph","native Git receipts","capability result schema"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService.build_folder_plan","grant_agent.folder_sync.FolderSyncService._allowed_folder_path","grant_agent.folder_sync.FolderSyncService._validate_ignore_patterns","grant_agent.folder_sync.FolderSyncService._validated_versioning","grant_agent.proofs_b_adapters.check_result"],"claim":"Folder paths stay under configured roots, ignores cannot include other files, and inbound versioning is required from the supported local set; unsafe choices are rejected before provider requests.","id":"adapters.sync.policy","impact":["local sync folder boundaries","provider requests","versioning authority"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.proofs_b_adapters._verified_native_executable","grant_agent.proofs_b_adapters._native_sync_check","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"Startup requires the prepared task-local Syncthing v2.1.5 executable SHA-256; missing or mismatched bytes fail closed without downloading. The owned child uses only GUI48473 and TCP48474, with discovery, relays, NAT and upgrades disabled, and is stopped in finally.","id":"adapters.sync.native-runtime","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService.build_folder_plan","grant_agent.folder_sync.FolderSyncService.apply_folder_plan","grant_agent.folder_sync.FolderSyncService.resume_folder","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"Persisted hashed plans configure actual paused folders and ignores only with approval; activation requires separate deletion-propagation approval, supported inbound versioning and actual unpaused readback. Returned receipts match their persisted bytes.","id":"adapters.sync.plan-activation","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService.apply_folder_plan","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"A changed native folder/ignore baseline causes stale_plan before mutation and reports distinct expected and actual baseline hashes.","id":"adapters.sync.stale","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService.apply_folder_plan","grant_agent.folder_sync.FolderSyncService._restore_folder","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"When native ignores fail after folder creation, restore the previous relationship and independently read back restoration; the native procedure proves absent-folder restoration using a real owned filesystem collision.","id":"adapters.sync.rollback","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.folder_sync.FolderSyncService._dangerous_recovery","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"Recovery requires approval, the exact folder ID confirmation and the matching native sendonly/receiveonly mode. Persisted requested receipts describe accepted native requests, never completed remote file recovery.","id":"adapters.sync.recovery","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.capability_service.CapabilityService.execute_tool_operation","grant_agent.folder_sync.FolderSyncService.compatibility_snapshot","grant_agent.proofs_b_adapters.check_result","grant_agent.proofs_b_adapters._native_sync_check"],"claim":"The real capability manifest exposes sync.compatibility through tool.neyvia-folder-sync as sync.health; executing its typed operation reports the actual pinned native executable hash without credential exposure.","id":"adapters.sync.discovery","impact":["folder relationship authority","native REST configuration","persisted plans and receipts","owned task-local process"],"phase":"invariant"}
T t1{..}
T t2{}
T t3{ok:true available:bool ..}
T t4 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}"
L proofs-b-adapters.overview v1 -- PROOFS-b adapter contract evidence boundaries
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"overview","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"overview","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"overview","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"overview","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"overview","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"overview","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"overview","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"overview","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"overview","data":"The feature chapters document production entry points and isolated self-check boundaries.","key":"0","section":"guidance"}
M proofs-b-adapters "The feature chapters document production entry points and isolated self-check boundaries." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Use neyvia.verify(areas:[\"proofs-b-adapters\"]) or CLI neyvia verify --area proofs-b-adapters; incomplete frontier is explicit.","key":"1","section":"guidance"}
M proofs-b-adapters "Use neyvia.verify(areas:[\"proofs-b-adapters\"]) or CLI neyvia verify --area proofs-b-adapters; incomplete frontier is explicit." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"The local observer reads only latest status and does not rerun a provider action.","key":"2","section":"guidance"}
M proofs-b-adapters "The local observer reads only latest status and does not rerun a provider action." src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-comparison v1 -- PROOFS-b comparison production contracts and local evidence
-- @record {"chapter":"proofs-b-comparison","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-comparison","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-comparison","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-comparison","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-comparison","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-comparison","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-comparison","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-comparison","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-comparison","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-comparison","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-comparison","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-comparison","data":"Protocol grading compares every expected field to parsed observations and exact correctness requires every field; omitted and altered fields fail.","key":"0","section":"guidance"}
M proofs-b-adapters "Protocol grading compares every expected field to parsed observations and exact correctness requires every field; omitted and altered fields fail." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"Unready/security harnesses are ineligible; leaders require complete exact receipt-backed read-only route-intact samples and prefer essential capability coverage while retaining observed execution median.","key":"1","section":"guidance"}
M proofs-b-adapters "Unready/security harnesses are ineligible; leaders require complete exact receipt-backed read-only route-intact samples and prefer essential capability coverage while retaining observed execution median." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"2","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"grant_agent.harness_comparison.grade_output","key":"3","section":"guidance"}
M proofs-b-adapters "grant_agent.harness_comparison.grade_output" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"grant_agent.harness_comparison.eligibility","key":"4","section":"guidance"}
M proofs-b-adapters "grant_agent.harness_comparison.eligibility" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"grant_agent.harness_comparison.capability_coverage","key":"5","section":"guidance"}
M proofs-b-adapters "grant_agent.harness_comparison.capability_coverage" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"grant_agent.harness_comparison.summarize_attempts","key":"6","section":"guidance"}
M proofs-b-adapters "grant_agent.harness_comparison.summarize_attempts" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-comparison","data":"grant_agent.harness_comparison.select_leader","key":"7","section":"guidance"}
M proofs-b-adapters "grant_agent.harness_comparison.select_leader" src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-git v1 -- PROOFS-b git production contracts and local evidence
-- @record {"chapter":"proofs-b-git","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-git","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-git","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-git","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-git","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-git","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-git","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-git","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-git","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-git","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-git","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-git","data":"Inspect/history/show/ancestry read actual Git objects and return durable receipt bytes whose digest and HEAD/output lineage match the result.","key":"0","section":"guidance"}
M proofs-b-adapters "Inspect/history/show/ancestry read actual Git objects and return durable receipt bytes whose digest and HEAD/output lineage match the result." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"Every Git action validates local helper/filter/protocol/include restrictions, attributes/object-store/worktree boundaries, consistency snapshots and network denial before issuing a success receipt.","key":"1","section":"guidance"}
M proofs-b-adapters "Every Git action validates local helper/filter/protocol/include restrictions, attributes/object-store/worktree boundaries, consistency snapshots and network denial before issuing a success receipt." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"2","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"grant_agent.git_reference_adapter.GitReferenceAdapter.execute","key":"3","section":"guidance"}
M proofs-b-adapters "grant_agent.git_reference_adapter.GitReferenceAdapter.execute" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"grant_agent.git_reference_adapter.GitReferenceAdapter.execute","key":"4","section":"guidance"}
M proofs-b-adapters "grant_agent.git_reference_adapter.GitReferenceAdapter.execute" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"grant_agent.git_reference_adapter.GitReferenceAdapter._config","key":"5","section":"guidance"}
M proofs-b-adapters "grant_agent.git_reference_adapter.GitReferenceAdapter._config" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"grant_agent.git_reference_adapter.GitReferenceAdapter._attributes","key":"6","section":"guidance"}
M proofs-b-adapters "grant_agent.git_reference_adapter.GitReferenceAdapter._attributes" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"grant_agent.git_reference_adapter.GitReferenceAdapter._repository","key":"7","section":"guidance"}
M proofs-b-adapters "grant_agent.git_reference_adapter.GitReferenceAdapter._repository" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"A tool with a valid contract becomes execution-ready only with a currently hash/version-verified actual adapter and no execution prerequisites; production readiness additionally requires Boolean validated evidence and no production prerequisites. Discovery preserves agentReady while filtering live execution readiness.","key":"8","section":"guidance"}
M proofs-b-adapters "A tool with a valid contract becomes execution-ready only with a currently hash/version-verified actual adapter and no execution prerequisites; production readiness additionally requires Boolean validated evidence and no production prerequisites. Discovery preserves agentReady while filtering live execution readiness." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-git","data":"Capability service executes the actual pinned local Git operation, validates output and registers real hash/lineage-bound receipts; bad declared digests or output lineage are rejected before artifact graph mutation.","key":"9","section":"guidance"}
M proofs-b-adapters "Capability service executes the actual pinned local Git operation, validates output and registers real hash/lineage-bound receipts; bad declared digests or output lineage are rejected before artifact graph mutation." src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-handoff v1 -- PROOFS-b handoff production contracts and local evidence
-- @record {"chapter":"proofs-b-handoff","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-handoff","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-handoff","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-handoff","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-handoff","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-handoff","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-handoff","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-handoff","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-handoff","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-handoff","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-handoff","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-handoff","data":"Handoff packets preserve session lineage, objective, prompt stack, completed/remaining plan and next actions, including durable JSON serialization.","key":"0","section":"guidance"}
M proofs-b-adapters "Handoff packets preserve session lineage, objective, prompt stack, completed/remaining plan and next actions, including durable JSON serialization." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-handoff","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"1","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-handoff","data":"grant_agent.handoff.create_handoff_packet","key":"2","section":"guidance"}
M proofs-b-adapters "grant_agent.handoff.create_handoff_packet" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-handoff","data":"grant_agent.handoff.save_handoff_packet","key":"3","section":"guidance"}
M proofs-b-adapters "grant_agent.handoff.save_handoff_packet" src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-html v1 -- PROOFS-b html production contracts and local evidence
-- @record {"chapter":"proofs-b-html","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-html","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-html","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-html","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-html","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-html","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-html","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-html","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-html","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-html","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-html","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-html","data":"Static HTML rubric sums only earned points out of 80; combined acceptance requires total at least75 and independently observed browser score at least12. Frozen prompt requires a single offline index.html and 390px.","key":"0","section":"guidance"}
M proofs-b-adapters "Static HTML rubric sums only earned points out of 80; combined acceptance requires total at least75 and independently observed browser score at least12. Frozen prompt requires a single offline index.html and 390px." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-html","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"1","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-html","data":"grant_agent.html_site_benchmark.grade_html","key":"2","section":"guidance"}
M proofs-b-adapters "grant_agent.html_site_benchmark.grade_html" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-html","data":"grant_agent.html_site_benchmark.combine_score","key":"3","section":"guidance"}
M proofs-b-adapters "grant_agent.html_site_benchmark.combine_score" src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-native-sync v1 -- PROOFS-b native sync action contracts and isolated startup
-- @record {"chapter":"proofs-b-native-sync","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-native-sync","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-native-sync","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-native-sync","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-native-sync","data":{"failure":"The prepared native executable is missing or has different bytes","recovery":"Stop before launch; prepare the authorized official package separately and verify its exact SHA-256. There is no startup download fallback."},"key":"0","section":"pitfalls"}
X The prepared native executable is missing or has different bytes -> Stop before launch; prepare the authorized official package separately and verify its exact SHA-256. There is no startup download fallback.
-- @record {"chapter":"proofs-b-native-sync","data":{"failure":"Native folders or listeners might touch external state","recovery":"Only owned roots and explicit loopback ports are used; discovery, relays, NAT, upgrades and default listeners are disabled. Finally stops only the owned PID."},"key":"1","section":"pitfalls"}
X Native folders or listeners might touch external state -> Only owned roots and explicit loopback ports are used; discovery, relays, NAT, upgrades and default listeners are disabled. Finally stops only the owned PID.
-- @record {"chapter":"proofs-b-native-sync","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-native-sync","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-native-sync","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-native-sync","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-native-sync","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-native-sync","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-native-sync","data":"Startup requires the prepared task-local Syncthing v2.1.5 executable SHA-256; missing or mismatched bytes fail closed without downloading. The owned child uses only GUI48473 and TCP48474, with discovery, relays, NAT and upgrades disabled, and is stopped in finally.","key":"0","section":"guidance"}
M proofs-b-adapters "Startup requires the prepared task-local Syncthing v2.1.5 executable SHA-256; missing or mismatched bytes fail closed without downloading. The owned child uses only GUI48473 and TCP48474, with discovery, relays, NAT and upgrades disabled, and is stopped in finally." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Persisted hashed plans configure actual paused folders and ignores only with approval; activation requires separate deletion-propagation approval, supported inbound versioning and actual unpaused readback. Returned receipts match their persisted bytes.","key":"1","section":"guidance"}
M proofs-b-adapters "Persisted hashed plans configure actual paused folders and ignores only with approval; activation requires separate deletion-propagation approval, supported inbound versioning and actual unpaused readback. Returned receipts match their persisted bytes." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"A changed native folder/ignore baseline causes stale_plan before mutation and reports distinct expected and actual baseline hashes.","key":"2","section":"guidance"}
M proofs-b-adapters "A changed native folder/ignore baseline causes stale_plan before mutation and reports distinct expected and actual baseline hashes." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"When native ignores fail after folder creation, restore the previous relationship and independently read back restoration; the native procedure proves absent-folder restoration using a real owned filesystem collision.","key":"3","section":"guidance"}
M proofs-b-adapters "When native ignores fail after folder creation, restore the previous relationship and independently read back restoration; the native procedure proves absent-folder restoration using a real owned filesystem collision." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Recovery requires approval, the exact folder ID confirmation and the matching native sendonly/receiveonly mode. Persisted requested receipts describe accepted native requests, never completed remote file recovery.","key":"4","section":"guidance"}
M proofs-b-adapters "Recovery requires approval, the exact folder ID confirmation and the matching native sendonly/receiveonly mode. Persisted requested receipts describe accepted native requests, never completed remote file recovery." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"The real capability manifest exposes sync.compatibility through tool.neyvia-folder-sync as sync.health; executing its typed operation reports the actual pinned native executable hash without credential exposure.","key":"5","section":"guidance"}
M proofs-b-adapters "The real capability manifest exposes sync.compatibility through tool.neyvia-folder-sync as sync.health; executing its typed operation reports the actual pinned native executable hash without credential exposure." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Run the registered proofs-b-adapters startup in the selected scratch workspace. All mutable native files stay under this verification's isolated scratch root; the package must already be prepared and independently pinned. Startup never downloads or installs it.","key":"6","section":"guidance"}
M proofs-b-adapters "Run the registered proofs-b-adapters startup in the selected scratch workspace. All mutable native files stay under this verification's isolated scratch root; the package must already be prepared and independently pinned. Startup never downloads or installs it." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Actual native receipts report local configuration, activation and recovery-request acceptance. No remote device, file synchronization, deletion propagation or completed recovery is claimed.","key":"7","section":"guidance"}
M proofs-b-adapters "Actual native receipts report local configuration, activation and recovery-request acceptance. No remote device, file synchronization, deletion propagation or completed recovery is claimed." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Generated native configuration, certificate and key files are never read by the proof runner. The fresh API key exists only in memory and in the owned child environment; public receipts contain no key.","key":"8","section":"guidance"}
M proofs-b-adapters "Generated native configuration, certificate and key files are never read by the proof runner. The fresh API key exists only in memory and in the owned child environment; public receipts contain no key." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"The four original health/cache/events/error-route/soft-degradation/unavailable cases remain frontiers; this migration does not add those absent behaviors.","key":"9","section":"guidance"}
M proofs-b-adapters "The four original health/cache/events/error-route/soft-degradation/unavailable cases remain frontiers; this migration does not add those absent behaviors." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-native-sync","data":"Prepared read-only executable: .agent_control/proofs-b/native-syncthing/syncthing-windows-amd64-v2.1.5/syncthing.exe; exact SHA-256 36a0f7bc372f64fa7cc4f5654fa324c0dd9f7fef2e07565e00c6e1cf73f50344.","key":"10","section":"guidance"}
M proofs-b-adapters "Prepared read-only executable: .agent_control/proofs-b/native-syncthing/syncthing-windows-amd64-v2.1.5/syncthing.exe; exact SHA-256 36a0f7bc372f64fa7cc4f5654fa324c0dd9f7fef2e07565e00c6e1cf73f50344." src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-ocr v1 -- PROOFS-b ocr production contracts and local evidence
-- @record {"chapter":"proofs-b-ocr","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-ocr","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-ocr","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-ocr","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-ocr","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-ocr","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-ocr","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-ocr","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-ocr","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-ocr","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-ocr","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-ocr","data":"OCR text repair changes only an evidenced repeated renderer prefix, complete HTML table boundary or exact repeated display-math block; nonmatching and unfinished specimens remain byte-identical.","key":"0","section":"guidance"}
M proofs-b-adapters "OCR text repair changes only an evidenced repeated renderer prefix, complete HTML table boundary or exact repeated display-math block; nonmatching and unfinished specimens remain byte-identical." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-ocr","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"1","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-ocr","data":"grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_renderer_duplicate","key":"2","section":"guidance"}
M proofs-b-adapters "grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_renderer_duplicate" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-ocr","data":"grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_table_boundary","key":"3","section":"guidance"}
M proofs-b-adapters "grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_table_boundary" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-ocr","data":"grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_formula_boundary","key":"4","section":"guidance"}
M proofs-b-adapters "grant_agent.capability_adapters.CapabilityAdapterRegistry._repair_glm_formula_boundary" src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-publication v1 -- PROOFS-b publication production contracts and local evidence
-- @record {"chapter":"proofs-b-publication","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-publication","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-publication","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-publication","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-publication","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-publication","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-publication","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-publication","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-publication","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-publication","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-publication","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-publication","data":"Every publication audit reads actual workflow files and rejects git push including shell continuation, PR mutation, write APIs, blanket write permission and retired native branch regardless of read-only declared permissions.","key":"0","section":"guidance"}
M proofs-b-adapters "Every publication audit reads actual workflow files and rejects git push including shell continuation, PR mutation, write APIs, blanket write permission and retired native branch regardless of read-only declared permissions." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-publication","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"1","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-publication","data":"scripts/check_workflow_publication_integrity.py:audit_workflows","key":"2","section":"guidance"}
M proofs-b-adapters "scripts/check_workflow_publication_integrity.py:audit_workflows" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-publication","data":"The actual audit_workflows action is itself the executable publication-policy checker; startup self_check always audits the real repository workflow files. No publication command is executed.","key":"3","section":"guidance"}
M proofs-b-adapters "The actual audit_workflows action is itself the executable publication-policy checker; startup self_check always audits the real repository workflow files. No publication command is executed." src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-release v1 -- PROOFS-b release production contracts and local evidence
-- @record {"chapter":"proofs-b-release","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-release","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-release","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-release","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-release","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-release","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-release","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-release","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-release","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-release","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-release","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-release","data":"Select only published channel/version releases, accept only recognized GitHub references, normalize v-prefixed numeric versions and select matching platform/checksum metadata.","key":"0","section":"guidance"}
M proofs-b-adapters "Select only published channel/version releases, accept only recognized GitHub references, normalize v-prefixed numeric versions and select matching platform/checksum metadata." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"Update checks observe metadata without package bytes; uncertain ordering, unreachable metadata and missing platform artifacts remain unknown; installed newer versions are never downgraded.","key":"1","section":"guidance"}
M proofs-b-adapters "Update checks observe metadata without package bytes; uncertain ordering, unreachable metadata and missing platform artifacts remain unknown; installed newer versions are never downgraded." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"Successful staged files match reported byte count/digest and supplied publisher checksum; absent checksums remain explicitly unverified and declared size differences retain warnings. Checksum rejection preserves prior target.","key":"2","section":"guidance"}
M proofs-b-adapters "Successful staged files match reported byte count/digest and supplied publisher checksum; absent checksums remain explicitly unverified and declared size differences retain warnings. Checksum rejection preserves prior target." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"3","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.parse_github_ref","key":"4","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.parse_github_ref" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.normalize_version","key":"5","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.normalize_version" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.select_release","key":"6","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.select_release" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.select_platform_asset","key":"7","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.select_platform_asset" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.find_checksum_for","key":"8","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.find_checksum_for" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.check_for_update","key":"9","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.check_for_update" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.fetch_releases","key":"10","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.fetch_releases" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"grant_agent.github_release_source.download_asset","key":"11","section":"guidance"}
M proofs-b-adapters "grant_agent.github_release_source.download_asset" src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-release","data":"A temporary owned HTTP server on48476 supplies real429 and premature-close protocol observations; it is always closed and never represents a GitHub account.","key":"12","section":"guidance"}
M proofs-b-adapters "A temporary owned HTTP server on48476 supplies real429 and premature-close protocol observations; it is always closed and never represents a GitHub account." src:"authored manual" state:verified
L proofs-b-adapters.proofs-b-sync v1 -- PROOFS-b sync production contracts and local evidence
-- @record {"chapter":"proofs-b-sync","data":{"args":{},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-adapters.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b-sync","data":{"effect":"Observe existing proof receipt without replaying feature actions","pre":"Selected workspace; read latest proof receipt","returns":{"$cl_type":"t4"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe existing proof receipt without replaying feature actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-sync","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b-sync","data":{"goal":"Read the latest verification boundary","inputs":{"$cl_type":"t2"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read the latest verification boundary
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b-sync","data":{"failure":"Local deterministic proof is interpreted as a provider or native journey","recovery":"Read the area checks and frontier; use the real required runtime before claiming that boundary"},"key":"0","section":"pitfalls"}
X Local deterministic proof is interpreted as a provider or native journey -> Read the area checks and frontier; use the real required runtime before claiming that boundary
-- @record {"chapter":"proofs-b-sync","data":"Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.","key":"0","section":"frontier"}
F Syncthing detailed health/cache/events, route/error summaries, per-folder status soft degradation and structured endpoint-unavailable behavior remain unproven and partly absent from production. Native proofs cover one isolated local service; no remote device synchronization is claimed.
-- @record {"chapter":"proofs-b-sync","data":"GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.","key":"1","section":"frontier"}
F GLM redesign jobs, changed UI artifact verification and OpenClaw reply/handoff paths require the real selected provider; no provider is substituted.
-- @record {"chapter":"proofs-b-sync","data":"The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.","key":"2","section":"frontier"}
F The repository Git manifest has no verified pin or typed operations; scratch pinning proves local registration/readiness and does not provision the repository's real manifest. Concurrent mutation/deadline and unavailable symlink creation remain uncovered.
-- @record {"chapter":"proofs-b-sync","data":"Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.","key":"3","section":"frontier"}
F Local HTTP protocol specimens prove 429 uncertainty and premature EOF rejection; actual GitHub connectivity/publication remains unobserved.
-- @record {"chapter":"proofs-b-sync","data":"HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.","key":"4","section":"frontier"}
F HTML scoring proves a static rubric and browser score gate; rendering, keyboard behavior, mobile overflow and visual quality remain separate browser evidence.
-- @record {"chapter":"proofs-b-sync","data":"Harness comparison checks score existing observations; they do not prove any provider produced those observations.","key":"5","section":"frontier"}
F Harness comparison checks score existing observations; they do not prove any provider produced those observations.
-- @record {"chapter":"proofs-b-sync","data":"Compatibility reports actual local file identity and hashes; hashVerified is true only when installed digest matches nonempty expected digest. Public transport reports credential availability without exposing the key.","key":"0","section":"guidance"}
M proofs-b-adapters "Compatibility reports actual local file identity and hashes; hashVerified is true only when installed digest matches nonempty expected digest. Public transport reports credential availability without exposing the key." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-sync","data":"Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained.","key":"1","section":"guidance"}
M proofs-b-adapters "Run neyvia verify with area proofs-b-adapters for real scratch procedures; original uncovered cases stay retained." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b-sync","data":"grant_agent.folder_sync.FolderSyncService.compatibility_snapshot","key":"2","section":"guidance"}
M proofs-b-adapters "grant_agent.folder_sync.FolderSyncService.compatibility_snapshot" src:"authored manual" state:verified
