CL 1
L proofs-b-engine v1 -- Authored executable manual
-- @manual {"chapters":{"proofs-b":{"title":"PROOFS-b engine, ecosystem and communication boundary contracts"}},"clVersion":"1.1","id":"proofs-b-engine","kind":"environment","proofs":{"area":"proofs-b-engine","manifests":["config/proofs/proofs-b-engine.json"],"startup":{"procedures":["ecosystem","local-workflow","recorder","engine-and-eval","watchdog","routes","chat-plan"],"runner":"grant_agent.proofs_b_engine.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.verify.status":"t1"},"tool_metadata":{"neyvia.verify.status":{}}}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.register_communication_account","grant_agent.proofs_b_engine.check"],"claim":"Credential-free persisted communication configuration retains per-action approval permissions.","id":"proofs-b.engine.account","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.compile_presentation_prompt","grant_agent.proofs_b_engine.check"],"claim":"Compiled prompt preserves the user original, visibly appends context, and requires explicit insertion without automated login or transcript harvesting.","id":"proofs-b.engine.presentation","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.capture_presentation_content","grant_agent.proofs_b_engine.check"],"claim":"Explicitly selected presentation content retains its source lineage and exact canonical content digest; unselected capture is rejected.","id":"proofs-b.engine.capture","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.build_share_capsule","grant_agent.proofs_b_engine.check"],"claim":"Secret findings block export; a safe durable capsule is explicitly prepared-not-sent and requires explicit sharing.","id":"proofs-b.engine.capsule","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric._experiment","grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.record_experiment_observation","grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.conclude_experiment","grant_agent.proofs_b_engine.check"],"claim":"Experiment projection exactly retains the stored journal, negative or positive verdict, state and lifetime; append/conclusion are reobserved from real SQLite state.","id":"proofs-b.engine.experiment","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric.plan_experiment_action","grant_agent.proofs_b_engine.check"],"claim":"An act-tier experiment requires recorded authorization and a named target, remains nonexecutable and requires per-action approval.","id":"proofs-b.engine.authorization","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.ecosystem_fabric.NeyviaEcosystemFabric._benchmark_claim","grant_agent.proofs_b_engine.check"],"claim":"Eligibility excludes missing subjects, budget excess and incomparable contexts without interpreting observed facts as superiority.","id":"proofs-b.engine.benchmark","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.efficient_workflow.build_efficient_workflow","grant_agent.neyvia_conversations.NeyviaConversationStore.create_concurrency_plan","grant_agent.proofs_b_engine.check"],"claim":"Reader/planner/executor/verifier stages have unique IDs and serial dependencies; only an explicitly permitted executor may mutate; role prompts have exact hashes and independent graph preparation preserves prior graphs.","id":"proofs-b.engine.workflow","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.efficient_workflow.compact_dependency_context","grant_agent.proofs_b_engine.check"],"claim":"A bounded dependency handoff preserves the full receipt reference and text digest, reports truncation, and excludes the raw runtime dump.","id":"proofs-b.engine.handoff","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.efficient_workflow.verification_result","grant_agent.proofs_b_engine.check"],"claim":"Malformed or evidence-free pass is unverified; failed verdict stays failed; workspace pass requires actual matching artifact digests.","id":"proofs-b.engine.verdict","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.neyvia_mcp_stdio.CompactNeyviaMCPServer.handle","grant_agent.neyvia_mcp_stdio.CompactNeyviaMCPServer._allowed"],"claim":"Every compact MCP request enforces read-only capabilities including nested mutations and stops tool work while a user question is pending.","id":"proofs-b.engine.mcp-authority","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.flight_recorder.MissionFlightRecorder.append_event","grant_agent.flight_recorder.MissionFlightRecorder.snapshot","grant_agent.proofs_b_engine.check"],"claim":"Recorder events retain mission identity and bounded payloads; snapshots serialize bounded tails and event counts and scratch rereads establish durable saved state.","id":"proofs-b.engine.recorder","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.flight_recorder.read_flight_recorder_events","grant_agent.proofs_b_engine.check"],"claim":"The event reader skips malformed JSON and non-object rows and retains at most the last requested 1-200 valid events.","id":"proofs-b.engine.event-tail","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.feature_suggester.suggest_features_from_text","grant_agent.proofs_b_engine.check"],"claim":"Feature suggestions use existing feature identities with descending keyword scores and retain the requested ranked relevant output.","id":"proofs-b.engine.suggestions","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.eval.summarize_runs","grant_agent.proofs_b_engine.check"],"claim":"Aggregation counts sessions, handoffs, checkpoints and successful/failed command receipts consistently; real subprocess success and failure are retained in run state.","id":"proofs-b.engine.summary","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.fluxio_harness.resolve_efficiency_autotune_policy","grant_agent.proofs_b_engine.check"],"claim":"Automatic routing requires at least three local runs; disabled/insufficient policy never applies changes, and safety bias selects uniform quality with pause on failure.","id":"proofs-b.engine.autotune","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.fluxio_harness.recommended_model_routes","grant_agent.proofs_b_engine.check"],"claim":"Core model roles remain distinct and explicit normalized role/provider/model overrides take precedence.","id":"proofs-b.engine.routes","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.fluxio_harness.FluxioHarness._delegated_route_mismatch","grant_agent.proofs_b_engine.check"],"claim":"Equivalent openai/openai-codex providers with the same phase/model/effort do not repeatedly request handoff.","id":"proofs-b.engine.route-equivalence","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.engine.AutonomousEngine.run","grant_agent.proofs_b_engine.check"],"claim":"The legacy local planning-state engine blocks unreadable docs, preserves resumable lineage and durable checkpoint/handoff receipts, bounds context rollover, records parallel merge policy and persists the same run result fields. This does not claim model execution or code implementation.","id":"proofs-b.engine.run","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.mission_watchdog.evaluate_fake_running_mission","grant_agent.proofs_b_engine.check"],"claim":"Fake-running diagnosis requires an old running/launching mission without changed files/artifacts, live local PID or recorded fresh remote lease; recent/evidenced/fresh-lease missions are exempt.","id":"proofs-b.engine.watchdog","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.mission_watchdog.enforce_fake_running_missions","grant_agent.proofs_b_engine.check"],"claim":"Each fake-running enforcement persists blocked state with a unique stuck receipt, diagnostics and repair step; repeated enforcement is idempotent.","id":"proofs-b.engine.watchdog-enforce","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.encrypted_chat.EncryptedChatService.build_message_plan","grant_agent.encrypted_chat.EncryptedChatService._resolve_room","grant_agent.encrypted_chat.EncryptedChatService._attachment_manifest","grant_agent.proofs_b_engine.check"],"claim":"Encrypted-chat preview is hash-bound, visibly attributed and attachment-scoped; secrets, denied room permissions and files outside the workspace are rejected before any send approval.","id":"proofs-b.engine.chat-plan","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.encrypted_chat.EncryptedChatService.account_catalog","grant_agent.encrypted_chat.EncryptedChatService.compatibility_snapshot","grant_agent.encrypted_chat.EncryptedChatService._binary_integrity","grant_agent.proofs_b_engine.check"],"claim":"Chat catalog/compatibility observers expose opaque identity references rather than room/user/device IDs or protected paths; configured local file identity checks verify exact hashes without claiming Matrix availability.","id":"proofs-b.engine.chat-public","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.skill_library.SkillLibrary._load_skill_rows","grant_agent.proofs_b_engine.check"],"claim":"Empty or unreadable learned-skill control JSON produces no records; successful skill loads return a list of object records.","id":"proofs-b.engine.skill-load","impact":["local feature action receipts","feature state and agent observations"],"phase":"invariant"}
T t1{..}
T t2{ok:true available:bool ..}
T t3 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}"
L proofs-b-engine.proofs-b v1 -- PROOFS-b engine, ecosystem and communication boundary contracts
-- @record {"chapter":"proofs-b","data":{"args":{},"inputs":{"$cl_type":"t1"},"shape":{"$cl_type":"t2"},"tool":"neyvia.verify.status"},"key":"latest","section":"state"}
S proofs-b-engine.latest:{ok:true available:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-b","data":{"effect":"Observe latest local proof receipt and its explicit frontier","pre":"Selected owned workspace; observer does not replay mutations","returns":{"$cl_type":"t3"},"reversible":true,"schema":"neyvia.verify.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\"]}" ! -- Observe latest local proof receipt and its explicit frontier
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-b","data":{"goal":"Read local verification status","inputs":{"$cl_type":"t1"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-latest","section":"procedures"}
P read-latest():receipt=neyvia.verify.status() C observed -- Read local verification status
V P read-latest -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-b","data":{"failure":"A file-integrity check or planning-state receipt is reported as encrypted delivery or provider execution","recovery":"Read the actual boundary and keep unexecuted Matrix/provider cases in the frontier"},"key":"0","section":"pitfalls"}
X A file-integrity check or planning-state receipt is reported as encrypted delivery or provider execution -> Read the actual boundary and keep unexecuted Matrix/provider cases in the frontier
-- @record {"chapter":"proofs-b","data":"Real Matrix transport/enrolled encrypted account required; not replaced by a transport that merely claims encryption.","key":"0","section":"frontier"}
F Real Matrix transport/enrolled encrypted account required; not replaced by a transport that merely claims encryption.
-- @record {"chapter":"proofs-b","data":"Real configured provider-backed execution required; local policy/state checks do not establish delegated completion.","key":"1","section":"frontier"}
F Real configured provider-backed execution required; local policy/state checks do not establish delegated completion.
-- @record {"chapter":"proofs-b","data":"The separate PROOFS-b chapter records feature contracts without editing shared feature manuals.","key":"0","section":"guidance"}
M proofs-b-engine "The separate PROOFS-b chapter records feature contracts without editing shared feature manuals." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b","data":"Local self-check: grant_agent.proofs_b_engine.self_check(root).","key":"1","section":"guidance"}
M proofs-b-engine "Local self-check: grant_agent.proofs_b_engine.self_check(root)." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b","data":"No credentials are read. Matrix availability handles are empty synthetic files observed only by file existence; real system Python bytes are used only for local file-integrity checks.","key":"2","section":"guidance"}
M proofs-b-engine "No credentials are read. Matrix availability handles are empty synthetic files observed only by file existence; real system Python bytes are used only for local file-integrity checks." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b","data":"Direct production function boundaries carry checks; ordinary UI/bot actions that call them inherit the same invariants. No new feature command is introduced.","key":"3","section":"guidance"}
M proofs-b-engine "Direct production function boundaries carry checks; ordinary UI/bot actions that call them inherit the same invariants. No new feature command is introduced." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b","data":"Legacy AutonomousEngine results describe its actual local planning/state algorithm, not implemented workspace edits.","key":"4","section":"guidance"}
M proofs-b-engine "Legacy AutonomousEngine results describe its actual local planning/state algorithm, not implemented workspace edits." src:"authored manual" state:verified
-- @record {"chapter":"proofs-b","data":"Coverage manifest: config/proofs/proofs-b-engine.json. Pending cases are retained until real corresponding execution is observed.","key":"5","section":"guidance"}
M proofs-b-engine "Coverage manifest: config/proofs/proofs-b-engine.json. Pending cases are retained until real corresponding execution is observed." src:"authored manual" state:verified
