CL 1
L research v1 -- Authored executable manual
-- @manual {"chapters":{"workflow":{"title":"Executable research method: chronological mechanism and measured quality"}},"clVersion":"1.1","id":"research","kind":"workflow","proofs":{"area":"research-journey"},"schema":"neyvia.manual.v1","schemas":{"neyvia.workflow.check":"t1","neyvia.workflow.record":"t1"},"tool_metadata":{"neyvia.workflow.check":{"mutability_class":"read"},"neyvia.workflow.record":{"mutability_class":"artifact_write"}}}
T t1{manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t2{report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0.. ..}
T t3 json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"
L research.workflow v1 -- Executable research method: chronological mechanism and measured quality
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"research","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"inputs":{"$cl_type":"t2"},"shape":{"$cl_type":"t3"},"tool":"neyvia.workflow.check"},"key":"adherence","section":"state"}
S research.adherence:json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}"=neyvia.workflow.check(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens)
-- @record {"chapter":"workflow","data":{"effect":"Validate ordered workflow evidence","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t3"},"reversible":true,"schema":"neyvia.workflow.check","tool":"neyvia.workflow.check"},"key":"check","section":"actions"}
A neyvia.workflow.check(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" -- Validate ordered workflow evidence
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"effect":"Persist a validated workflow receipt under the selected task root","pre":"Host owns task measurements and provider usage; report is bounded JSON","returns":{"$cl_type":"t3"},"reversible":false,"schema":"neyvia.workflow.record","tool":"neyvia.workflow.record"},"key":"record","section":"actions"}
A neyvia.workflow.record(manual:json:"{\"type\":\"string\",\"enum\":[\"hill-climb\",\"creativity\",\"critique-review\",\"efficiency\",\"research\",\"design\"]}" report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..) -> json:"{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"},\"adherence\":{\"type\":\"number\"},\"fitness\":{\"type\":[\"number\",\"null\"]},\"errors\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"accepted\",\"adherence\",\"fitness\",\"errors\"],\"additionalProperties\":true}" ! -- Persist a validated workflow receipt under the selected task root
C neyvia.workflow.record adhered:neyvia.workflow.check(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"args":{"evidence":{"$input":"evidence"},"manual":"research","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"expect":{"op":"eq","path":"accepted","value":true},"tool":"neyvia.workflow.check"},"key":"adhered","section":"checks"}
C neyvia.workflow.check adhered:neyvia.workflow.check(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens) .accepted == true
-- @record {"chapter":"workflow","data":{"goal":"Verify defining workflow mechanism against host evidence and persist the acceptance receipt","inputs":{"$cl_type":"t2"},"steps":[{"action":"check","args":{"evidence":{"$input":"evidence"},"manual":"research","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"verified"},{"action":"record","args":{"evidence":{"$input":"evidence"},"manual":"research","outcomeQuality":{"$input":"outcomeQuality"},"report":{"$input":"report"},"tokens":{"$input":"tokens"}},"check":"adhered","save":"recorded"}]},"key":"verify-and-record","section":"procedures"}
P verify-and-record(report:json:"{\"type\":\"object\"}" evidence:json:"{\"type\":\"object\",\"additionalProperties\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"sha256\":{\"type\":\"string\",\"pattern\":\"^[a-f0-9]{64}$\"}},\"required\":[\"path\",\"sha256\"],\"additionalProperties\":false}}" outcomeQuality:json:"{\"type\":\"number\",\"minimum\":0,\"maximum\":1}" tokens:0..):verified=neyvia.workflow.check(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered; recorded=neyvia.workflow.record(evidence:evidence manual:"research" outcomeQuality:outcomeQuality report:report tokens:tokens) C adhered -- Verify defining workflow mechanism against host evidence and persist the acceptance receipt
V P verify-and-record -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"workflow","data":{"constraints":"Use an independent frozen host quality judge; self-reported quality is not evidence.","options":["accept","revise"],"question":"Does the outcome satisfy the actual task, beyond recorded adherence?"},"key":"quality","section":"judge"}
J quality accept|revise:"Does the outcome satisfy the actual task, beyond recorded adherence?" -- Use an independent frozen host quality judge; self-reported quality is not evidence.
V J quality -> human:operator why:"explicit choice required"
-- @record {"chapter":"workflow","data":{"failure":"A model writes its own successful receipt, outcome score or token count","recovery":"The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail"},"key":"0","section":"pitfalls"}
X A model writes its own successful receipt, outcome score or token count -> The host supplies hash-bound local evidence files, independently judged quality and provider usage; invented IDs fail
-- @record {"chapter":"workflow","data":"Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.","key":"0","section":"frontier"}
F Executable adherence is necessary but not sufficient for semantic quality. Outcome quality belongs to a separate frozen task judge.
-- @record {"chapter":"workflow","data":"Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.","key":"1","section":"frontier"}
F Three paired tasks provide bounded evidence and cannot authorize statistical Evolver promotion.
-- @record {"chapter":"workflow","data":"Start with one question that could change the implementation decision. Compare at least two concrete prior-art sources and what each establishes.","key":"0","section":"guidance"}
M research "Start with one question that could change the implementation decision. Compare at least two concrete prior-art sources and what each establishes." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"State a prediction and a falsifier before testing. Prefer the smallest real test that discriminates the alternatives.","key":"1","section":"guidance"}
M research "State a prediction and a falsifier before testing. Prefer the smallest real test that discriminates the alternatives." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"The result must agree with measured success/failure, state limitations and separate observed facts from inference. A negative result is useful evidence.","key":"2","section":"guidance"}
M research "The result must agree with measured success/failure, state limitations and separate observed facts from inference. A negative result is useful evidence." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Report shape: {events:[{stage,data}],result:object}. Required chronological stages: question, prior-art, claim, test, result","key":"3","section":"guidance"}
M research "Report shape: {events:[{stage,data}],result:object}. Required chronological stages: question, prior-art, claim, test, result" src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"question{question}; prior-art{sources:[{source,finding}]>=2}; claim{prediction,falsifier}; test{receipt}; result{supported:boolean,limitations:[strings]}. Test evidence has success:boolean.","key":"4","section":"guidance"}
M research "question{question}; prior-art{sources:[{source,finding}]>=2}; claim{prediction,falsifier}; test{receipt}; result{supported:boolean,limitations:[strings]}. Test evidence has success:boolean." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified.","key":"5","section":"guidance"}
M research "Public tool evidence is {ID:{path:task-root-relative receipt JSON,sha256:receipt SHA256}}. Pure host evaluator evidence maps IDs to loaded measurements. Public tool outcome quality is explicitly caller-scored, never automatically verified." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below.","key":"6","section":"guidance"}
M research "Every data.receipt is a STRING naming a key in the host evidence mapping: for example {\"receipt\":\"measurement\"}. Never copy the receipt object or create a new ID. Public tool callers pass path/SHA descriptors separately; event receipt fields remain string IDs. Use the exact keys the current task supplied, not the example keys below." src:"authored manual" state:verified
-- @record {"chapter":"workflow","data":"Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"question\",\"data\":{\"question\":\"does the candidate fix the observed failure\"}},{\"stage\":\"prior-art\",\"data\":{\"sources\":[{\"source\":\"owner source file\",\"finding\":\"defining mechanism implemented here\"},{\"source\":\"actual run receipt\",\"finding\":\"records the observed failure boundary\"}]}},{\"stage\":\"claim\",\"data\":{\"prediction\":\"candidate passes the frozen check\",\"falsifier\":\"same check fails on the candidate\"}},{\"stage\":\"test\",\"data\":{\"receipt\":\"test\"}},{\"stage\":\"result\",\"data\":{\"supported\":false,\"limitations\":[\"single task does not prove generality\"]}}],\"result\":{\"decision\":\"task-specific actual answer\"}}","key":"7","section":"guidance"}
M research "Conforming shape example (replace illustrative values, IDs and decision with the actual task/evidence; do not copy its outcome): {\"events\":[{\"stage\":\"question\",\"data\":{\"question\":\"does the candidate fix the observed failure\"}},{\"stage\":\"prior-art\",\"data\":{\"sources\":[{\"source\":\"owner source file\",\"finding\":\"defining mechanism implemented here\"},{\"source\":\"actual run receipt\",\"finding\":\"records the observed failure boundary\"}]}},{\"stage\":\"claim\",\"data\":{\"prediction\":\"candidate passes the frozen check\",\"falsifier\":\"same check fails on the candidate\"}},{\"stage\":\"test\",\"data\":{\"receipt\":\"test\"}},{\"stage\":\"result\",\"data\":{\"supported\":false,\"limitations\":[\"single task does not prove generality\"]}}],\"result\":{\"decision\":\"task-specific actual answer\"}}" src:"authored manual" state:verified

-- @proof {"id":"p22.research-workspace-search","phase":"post","claim":"A local research query returns its exact Unicode source line and path as evidence; an escaping search scope is refused without changing the source.","checkedAt":["grant_agent.research.search_workspace_detailed","grant_agent.proofs_research_journey.local_workspace_search"],"impact":["Local workspace research evidence and source citations","Research search scope refusal"]}
