CL 1
L research-assistant v1 -- Authored executable manual
-- @manual {"chapters":{"journey":{"title":"Tool-only research journey with verified citations"},"public-research":{"title":"Public research with source and provider receipts"},"tool-gate":{"title":"Research tool correctness and latency gates"}},"clVersion":"1.1","id":"research-assistant","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"neyvia.research.answer":"t1","neyvia.research.journey":"t2","neyvia.research.receipt":"t3"},"tool_metadata":{"neyvia.research.answer":{"mutability_class":"external_action"},"neyvia.research.journey":{"mutability_class":"artifact_write"},"neyvia.research.receipt":{"mutability_class":"read"}}}
T t1{question:str#1.. obscuraPort:1024..65535 timeoutSeconds?:1..600 rounds?:1..5 ..}
T t2{question:str#1..2000 obscuraPort?:1024..65535 maxSources?:1..8 vertical?:json:"{\"type\":\"string\",\"enum\":[\"web\",\"scholarly\",\"code\",\"encyclopedia\"]}" answerModel?:json:"{\"type\":\"string\",\"enum\":[\"extractive\",\"gpt-6.1-sol\"]}" timeoutSeconds?:10..600 requestId?:str ~"^[a-z0-9][a-z0-9-]{0,63}$" ..}
T t3{path:str#1.. ..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"elapsedMs\":{\"type\":\"number\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}"
T t5{question:str#1..2000 requestId:str ~"^[a-z0-9][a-z0-9-]{0,63}$" ..}
T t6{question:str#1..2000 obscuraPort:1024..65535 requestId:str ~"^[a-z0-9][a-z0-9-]{0,63}$" ..}
T t7 json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}"
T t8 json:"{\"type\":\"object\"}"
T t9{path:str#1..}
L research-assistant.journey v1 -- Tool-only research journey with verified citations
-- @record {"chapter":"journey","data":{"effect":"Answer a public question through Neyvia's own tools: no-key web.search, parallel web.fetch (non-stealth Obscura only for pages refusing plain HTTP), web.dedupe, web.passages, web.cite, an extractive or explicit citation-only gpt-6.1-sol answer, then re-verify every citation; persist a timed receipt or an explicit failure.","pre":"Public web research is authorized in the selected root. obscuraPort, when passed, is inside the caller-assigned NEYVIA_BROWSER_PROOF_PORTS range. Authority=artifact_write, like web.fetch: it reads public sources and writes receipts in the selected root. No key is required; SearXNG or BRAVE_SEARCH_API_KEY are optional and reported.","returns":{"$cl_type":"t4"},"reversible":false,"schema":"neyvia.research.journey","tool":"neyvia.research.journey"},"key":"journey","section":"actions"}
A neyvia.research.journey(question:str#1..2000 obscuraPort?:1024..65535 maxSources?:1..8 vertical?:json:"{\"type\":\"string\",\"enum\":[\"web\",\"scholarly\",\"code\",\"encyclopedia\"]}" answerModel?:json:"{\"type\":\"string\",\"enum\":[\"extractive\",\"gpt-6.1-sol\"]}" timeoutSeconds?:10..600 requestId?:str ~"^[a-z0-9][a-z0-9-]{0,63}$") -> json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"elapsedMs\":{\"type\":\"number\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}" ! -- Answer a public question through Neyvia's own tools: no-key web.search, parallel web.fetch (non-stealth Obscura only for pages refusing plain HTTP), web.dedupe, web.passages, web.cite, an extractive or explicit citation-only gpt-6.1-sol answer, then re-verify every citation; persist a timed receipt or an explicit failure.
C neyvia.research.journey journey-verified:matches(neyvia.research.receipt(path:result.receiptPath) {properties:{answer:{properties:{answer:{minLength:1 type:"string"} claims:{minItems:1 type:"array"}} required:["answer" "claims"] type:"object"} citations:{items:{properties:{contentSha256:{pattern:"^[a-f0-9]{64}$" type:"string"} quote:{minLength:20 type:"string"} reverified:{const:true} url:{minLength:8 type:"string"} verified:{const:true}} required:["url" "quote" "verified" "reverified" "contentSha256"] type:"object"} minItems:1 type:"array"} claimGrounding:{properties:{accepted:{const:true}} required:["accepted"] type:"object"} elapsedMs:{maximum:60000 minimum:0 type:"number"} schema:{const:"neyvia.research.journey.v1"} search:{properties:{ok:{const:true} provider:{minLength:1 type:"string"}} required:["ok" "provider"] type:"object"} stages:{minItems:6 type:"array"} status:{const:"completed"}} required:["schema" "status" "claimGrounding" "citations" "stages" "elapsedMs" "search" "answer"] type:"object"})
-- @record {"chapter":"journey","data":{"args":{"path":{"$result":"journey.receiptPath"}},"expect":{"op":"schema","path":"","schema":{"properties":{"answer":{"properties":{"answer":{"minLength":1,"type":"string"},"claims":{"minItems":1,"type":"array"}},"required":["answer","claims"],"type":"object"},"citations":{"items":{"properties":{"contentSha256":{"pattern":"^[a-f0-9]{64}$","type":"string"},"quote":{"minLength":20,"type":"string"},"reverified":{"const":true},"url":{"minLength":8,"type":"string"},"verified":{"const":true}},"required":["url","quote","verified","reverified","contentSha256"],"type":"object"},"minItems":1,"type":"array"},"claimGrounding":{"properties":{"accepted":{"const":true}},"required":["accepted"],"type":"object"},"elapsedMs":{"maximum":60000,"minimum":0,"type":"number"},"schema":{"const":"neyvia.research.journey.v1"},"search":{"properties":{"ok":{"const":true},"provider":{"minLength":1,"type":"string"}},"required":["ok","provider"],"type":"object"},"stages":{"minItems":6,"type":"array"},"status":{"const":"completed"}},"required":["schema","status","claimGrounding","citations","stages","elapsedMs","search","answer"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"journey-verified","section":"checks"}
C neyvia.research.receipt journey-verified:matches(neyvia.research.receipt(path:journey.receiptPath) {properties:{answer:{properties:{answer:{minLength:1 type:"string"} claims:{minItems:1 type:"array"}} required:["answer" "claims"] type:"object"} citations:{items:{properties:{contentSha256:{pattern:"^[a-f0-9]{64}$" type:"string"} quote:{minLength:20 type:"string"} reverified:{const:true} url:{minLength:8 type:"string"} verified:{const:true}} required:["url" "quote" "verified" "reverified" "contentSha256"] type:"object"} minItems:1 type:"array"} claimGrounding:{properties:{accepted:{const:true}} required:["accepted"] type:"object"} elapsedMs:{maximum:60000 minimum:0 type:"number"} schema:{const:"neyvia.research.journey.v1"} search:{properties:{ok:{const:true} provider:{minLength:1 type:"string"}} required:["ok" "provider"] type:"object"} stages:{minItems:6 type:"array"} status:{const:"completed"}} required:["schema" "status" "claimGrounding" "citations" "stages" "elapsedMs" "search" "answer"] type:"object"})
-- @record {"chapter":"journey","data":{"goal":"Answer a public question with Neyvia's own tools, verify every citation from the cached source, and judge support","inputs":{"$cl_type":"t5"},"steps":[{"action":"journey","args":{"question":{"$input":"question"},"requestId":{"$input":"requestId"}},"check":"journey-verified","save":"journey"},{"judge":"support"}]},"key":"journey","section":"procedures"}
P journey(question:str#1..2000 requestId:str ~"^[a-z0-9][a-z0-9-]{0,63}$"):journey=neyvia.research.journey(question:question requestId:requestId) C journey-verified; J support -- Answer a public question with Neyvia's own tools, verify every citation from the cached source, and judge support
V P journey -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"journey","data":{"goal":"Same journey, reading pages that refuse plain HTTP through the non-stealth Obscura runtime on an assigned port","inputs":{"$cl_type":"t6"},"steps":[{"action":"journey","args":{"obscuraPort":{"$input":"obscuraPort"},"question":{"$input":"question"},"requestId":{"$input":"requestId"}},"check":"journey-verified","save":"journey"},{"judge":"support"}]},"key":"journey-rendered","section":"procedures"}
P journey-rendered(question:str#1..2000 obscuraPort:1024..65535 requestId:str ~"^[a-z0-9][a-z0-9-]{0,63}$"):journey=neyvia.research.journey(obscuraPort:obscuraPort question:question requestId:requestId) C journey-verified; J support -- Same journey, reading pages that refuse plain HTTP through the non-stealth Obscura runtime on an assigned port
V P journey-rendered -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"journey","data":{"constraints":"Completed status proves execution only. Inspect answer.citations and source receipts for entailment; quoted text existing in a source alone does not prove the claim. Preserve failed attempts and request further research if evidence is inadequate.","options":["supported","needs-more-evidence","contradicted"],"question":"Do the retrieved passages support every material answer claim, with no contradiction or missing reasoning?"},"key":"support","section":"judge"}
J support supported|needs-more-evidence|contradicted:"Do the retrieved passages support every material answer claim, with no contradiction or missing reasoning?" -- Completed status proves execution only. Inspect answer.citations and source receipts for entailment; quoted text existing in a source alone does not prove the claim. Preserve failed attempts and request further research if evidence is inadequate.
V J support -> human:operator why:"explicit choice required"
-- @record {"chapter":"journey","data":{"failure":"DuckDuckGo serves a human-verification page after a burst","recovery":"It is reported as status challenge, the transport pauses for 60 s, and search falls back to the Wikipedia index then DDGS Yandex. Never solve or bypass it; space queries (NEYVIA_DDG_MIN_INTERVAL_MS, default 2500 ms)."},"key":"0","section":"pitfalls"}
X DuckDuckGo serves a human-verification page after a burst -> It is reported as status challenge, the transport pauses for 60 s, and search falls back to the Wikipedia index then DDGS Yandex. Never solve or bypass it; space queries (NEYVIA_DDG_MIN_INTERVAL_MS, default 2500 ms).
-- @record {"chapter":"journey","data":{"failure":"Treating an exact quote as proof that the answer is right","recovery":"Citation verification proves the quoted span exists in the cached source. Use the support judgement for entailment, and run another journey or vertical when the quotes do not answer the question."},"key":"1","section":"pitfalls"}
X Treating an exact quote as proof that the answer is right -> Citation verification proves the quoted span exists in the cached source. Use the support judgement for entailment, and run another journey or vertical when the quotes do not answer the question.
-- @record {"chapter":"journey","data":"Sentence ranking is lexical and advisory; it can pick a relevant but non-answering sentence. Twenty-question development checks are not an accuracy benchmark.","key":"0","section":"frontier"}
F Sentence ranking is lexical and advisory; it can pick a relevant but non-answering sentence. Twenty-question development checks are not an accuracy benchmark.
-- @record {"chapter":"journey","data":"Unauthenticated GitHub search is rate limited by IP; a refused code search is reported, not retried with credentials.","key":"1","section":"frontier"}
F Unauthenticated GitHub search is rate limited by IP; a refused code search is reported, not retried with credentials.
-- @record {"chapter":"journey","data":"Stages, in order and each a native tool call with its own receipt: search (web.search) -> open (web.fetch, parallel) -> dedupe (web.dedupe) -> extract (web.passages plus advisory sentence ranking) -> cite (web.cite with expectedText) -> answer -> verify (web.cite again on every citation).","key":"0","section":"guidance"}
M research-assistant "Stages, in order and each a native tool call with its own receipt: search (web.search) -> open (web.fetch, parallel) -> dedupe (web.dedupe) -> extract (web.passages plus advisory sentence ranking) -> cite (web.cite with expectedText) -> answer -> verify (web.cite again on every citation)." src:"authored manual" state:verified
-- @record {"chapter":"journey","data":"Before the run, author an observer goal on the receipt the caller names: G: research.receipt(path=\"research/<requestId>/receipt.json\").claimGrounding.accepted == true. A requestId is single-use; an existing receipt is never overwritten.","key":"1","section":"guidance"}
M research-assistant "Before the run, author an observer goal on the receipt the caller names: G: research.receipt(path=\"research/<requestId>/receipt.json\").claimGrounding.accepted == true. A requestId is single-use; an existing receipt is never overwritten." src:"authored manual" state:verified
-- @record {"chapter":"journey","data":"Search needs no key: paced DuckDuckGo HTML for the web; vertical=scholarly uses OpenAlex and arXiv, code uses GitHub repositories, encyclopedia uses Wikipedia. SearXNG (NEYVIA_SEARXNG_URL) or BRAVE_SEARCH_API_KEY are optional; an unset key is recorded as not_configured, never silently skipped.","key":"2","section":"guidance"}
M research-assistant "Search needs no key: paced DuckDuckGo HTML for the web; vertical=scholarly uses OpenAlex and arXiv, code uses GitHub repositories, encyclopedia uses Wikipedia. SearXNG (NEYVIA_SEARXNG_URL) or BRAVE_SEARCH_API_KEY are optional; an unset key is recorded as not_configured, never silently skipped." src:"authored manual" state:verified
-- @record {"chapter":"journey","data":"web.fetch identifies itself honestly as NeyviaAgent. A page that refuses plain HTTP (401/403/429/503) is read through the workspace's already running non-stealth Obscura only when the journey was given obscuraPort; it is labelled obscura-rendered with plainHttpStatus. Without a runtime the refusal is reported.","key":"3","section":"guidance"}
M research-assistant "web.fetch identifies itself honestly as NeyviaAgent. A page that refuses plain HTTP (401/403/429/503) is read through the workspace's already running non-stealth Obscura only when the journey was given obscuraPort; it is labelled obscura-rendered with plainHttpStatus. Without a runtime the refusal is reported." src:"authored manual" state:verified
-- @record {"chapter":"journey","data":"answerModel=extractive (default) answers with verbatim cached spans, so every claim is byte-exact and no model or key is used. answerModel=gpt-6.1-sol may only restate the numbered verified quotes without web access; any claim citing an unknown number fails grounding.","key":"4","section":"guidance"}
M research-assistant "answerModel=extractive (default) answers with verbatim cached spans, so every claim is byte-exact and no model or key is used. answerModel=gpt-6.1-sol may only restate the numbered verified quotes without web access; any claim citing an unknown number fails grounding." src:"authored manual" state:verified
-- @record {"chapter":"journey","data":"Read receipt.stages[].elapsedMs and toolReceipts before reporting speed. Measured 2026-10-06 on 20 frozen public questions (scripts/evidence/RX-research-journeys.json): extractive journeys 20/20 completed with every citation re-verified, p50 3.2 s, mean 4.1 s, p95 6.7 s (search 1.7 s and open 1.4 s dominate); with an Obscura runtime started per journey p50 5.9 s; citation-only gpt-6.1-sol about 10 s and 9.3k tokens per journey. The lexical answer check (18/20) is a development signal, not accuracy.","key":"5","section":"guidance"}
M research-assistant "Read receipt.stages[].elapsedMs and toolReceipts before reporting speed. Measured 2026-10-06 on 20 frozen public questions (scripts/evidence/RX-research-journeys.json): extractive journeys 20/20 completed with every citation re-verified, p50 3.2 s, mean 4.1 s, p95 6.7 s (search 1.7 s and open 1.4 s dominate); with an Obscura runtime started per journey p50 5.9 s; citation-only gpt-6.1-sol about 10 s and 9.3k tokens per journey. The lexical answer check (18/20) is a development signal, not accuracy." src:"authored manual" state:verified
L research-assistant.public-research v1 -- Public research with source and provider receipts
-- @record {"chapter":"public-research","data":{"args":{"path":{"$input":"path"}},"inputs":{"$cl_type":"t3"},"shape":{"$cl_type":"t7"},"tool":"neyvia.research.receipt"},"key":"saved","section":"state"}
S research-assistant.saved:json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}"=neyvia.research.receipt(path:path)
-- @record {"chapter":"public-research","data":{"effect":"Use Sol-low keyword planning and live web search, C10b public-source Obscura/PDF capture with CPU LAYA advisory ranking, exact citation repair, and an independent Sol-low claim-grounding check; persist answers or explicit failures.","pre":"Public web research is authorized in the selected root; pass an explicit Obscura port inside the caller-assigned NEYVIA_BROWSER_PROOF_PORTS range (never a live Neyvia port); configured providers and the non-stealth runtime are available.","returns":{"$cl_type":"t7"},"reversible":false,"schema":"neyvia.research.answer","tool":"neyvia.research.answer"},"key":"answer","section":"actions"}
A neyvia.research.answer(question:str#1.. obscuraPort:1024..65535 timeoutSeconds?:1..600 rounds?:1..5) -> json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}" ! -- Use Sol-low keyword planning and live web search, C10b public-source Obscura/PDF capture with CPU LAYA advisory ranking, exact citation repair, and an independent Sol-low claim-grounding check; persist answers or explicit failures.
C neyvia.research.answer grounded:neyvia.research.receipt(path:result.receiptPath) .claimGrounding.accepted == true
-- @record {"chapter":"public-research","data":{"effect":"Read the persisted receipt without running another model or web request.","pre":"The receipt path is inside the selected workspace and comes from its research run.","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.research.receipt","tool":"neyvia.research.receipt"},"key":"receipt","section":"actions"}
A neyvia.research.receipt(path:str#1..) -> json:"{\"type\":\"object\",\"properties\":{\"receiptPath\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"type\":\"string\"},\"claimGrounding\":{\"type\":\"object\",\"properties\":{\"accepted\":{\"type\":\"boolean\"}}}}}" -- Read the persisted receipt without running another model or web request.
F verify-receipt "No authored observer check is bound to neyvia.research.receipt" -> ask operator blocks:neyvia.research.receipt
-- @record {"chapter":"public-research","data":{"args":{"path":{"$result":"research.receiptPath"}},"expect":{"op":"eq","path":"claimGrounding.accepted","value":true},"tool":"neyvia.research.receipt"},"key":"grounded","section":"checks"}
C neyvia.research.receipt grounded:neyvia.research.receipt(path:research.receiptPath) .claimGrounding.accepted == true
-- @record {"chapter":"public-research","data":{"goal":"Answer an authorized public question and inspect its persisted completion receipt","inputs":{"$cl_type":"t1"},"steps":[{"action":"answer","args":{"obscuraPort":{"$input":"obscuraPort"},"question":{"$input":"question"},"rounds":5,"timeoutSeconds":600},"check":"grounded","save":"research"},{"judge":"support"}]},"key":"research","section":"procedures"}
P research(question:str#1.. obscuraPort:1024..65535 timeoutSeconds?:1..600 rounds?:1..5):research=neyvia.research.answer(obscuraPort:obscuraPort question:question rounds:5 timeoutSeconds:600) C grounded; J support -- Answer an authorized public question and inspect its persisted completion receipt
V P research -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"public-research","data":{"goal":"Inspect source evidence and failures for an existing research run","inputs":{"$cl_type":"t3"},"steps":[{"action":"receipt","args":{"path":{"$input":"path"}},"save":"saved"}]},"key":"inspect-receipt","section":"procedures"}
P inspect-receipt(path:str#1..):saved=neyvia.research.receipt(path:path) -- Inspect source evidence and failures for an existing research run
V P inspect-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"public-research","data":{"constraints":"Completed status proves execution only. Inspect answer.citations and source receipts for entailment; quoted text existing in a source alone does not prove the claim. Preserve failed attempts and request further research if evidence is inadequate.","options":["supported","needs-more-evidence","contradicted"],"question":"Do the retrieved passages support every material answer claim, with no contradiction or missing reasoning?"},"key":"support","section":"judge"}
J support supported|needs-more-evidence|contradicted:"Do the retrieved passages support every material answer claim, with no contradiction or missing reasoning?" -- Completed status proves execution only. Inspect answer.citations and source receipts for entailment; quoted text existing in a source alone does not prove the claim. Preserve failed attempts and request further research if evidence is inadequate.
V J support -> human:operator why:"explicit choice required"
-- @record {"chapter":"public-research","data":{"failure":"Missing runtime, search CAPTCHA, unreadable source, provider timeout or unsupported output","recovery":"Read the failed receipt and stage-specific errors; repair the underlying service or query, then run a fresh question without changing reference answers."},"key":"0","section":"pitfalls"}
X Missing runtime, search CAPTCHA, unreadable source, provider timeout or unsupported output -> Read the failed receipt and stage-specific errors; repair the underlying service or query, then run a fresh question without changing reference answers.
-- @record {"chapter":"public-research","data":{"failure":"Confusing reachable URLs or matching quotes with factual support","recovery":"Read the surrounding source context and verify the actual claim and calculation; distinguish unsupported, contradicted and inaccessible evidence."},"key":"1","section":"pitfalls"}
X Confusing reachable URLs or matching quotes with factual support -> Read the surrounding source context and verify the actual claim and calculation; distinguish unsupported, contradicted and inaccessible evidence.
-- @record {"chapter":"public-research","data":"Open briefs and semantic accuracy require a frozen arm-blind judge; completed receipts alone are not accuracy judgments.","key":"0","section":"frontier"}
F Open briefs and semantic accuracy require a frozen arm-blind judge; completed receipts alone are not accuracy judgments.
-- @record {"chapter":"public-research","data":"Subscription token usage does not establish attributable monetary cost; unavailable cost remains unknown.","key":"1","section":"frontier"}
F Subscription token usage does not establish attributable monetary cost; unavailable cost remains unknown.
-- @record {"chapter":"public-research","data":"General superiority and lower cost require a completed matched comparison; targeted repairs are development evidence.","key":"2","section":"frontier"}
F General superiority and lower cost require a completed matched comparison; targeted repairs are development evidence.
-- @record {"chapter":"public-research","data":"Pass an explicit port from the caller-assigned NEYVIA_BROWSER_PROOF_PORTS range; there is no default port and no stealth browsing.","key":"0","section":"guidance"}
M research-assistant "Pass an explicit port from the caller-assigned NEYVIA_BROWSER_PROOF_PORTS range; there is no default port and no stealth browsing." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Only public questions and retrieved source content go to research models. Never provide benchmark gold answers or another arm's results.","key":"1","section":"guidance"}
M research-assistant "Only public questions and retrieved source content go to research models. Never provide benchmark gold answers or another arm's results." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Read source receipts, model receipts, searches, cascade and elapsedMs before reporting what ran.","key":"2","section":"guidance"}
M research-assistant "Read source receipts, model receipts, searches, cascade and elapsedMs before reporting what ran." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Search records the actual engine and each transport attempt; an unavailable configured engine is never reported as having searched.","key":"3","section":"guidance"}
M research-assistant "Search records the actual engine and each transport attempt; an unavailable configured engine is never reported as having searched." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Every live and data-only model step explicitly uses gpt-6.1-sol at low effort. Luna is never called by this research route. Sol preserves full relevant C10b source context; the independent checker verifies necessary relationships, temporal filters, calculations and every material answer claim. Reject a genuine quote attached to a false claim.","key":"4","section":"guidance"}
M research-assistant "Every live and data-only model step explicitly uses gpt-6.1-sol at low effort. Luna is never called by this research route. Sol preserves full relevant C10b source context; the independent checker verifies necessary relationships, temporal filters, calculations and every material answer claim. Reject a genuine quote attached to a false claim." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"A literal span repair copies one contiguous actual source span, preserving words, numbers and punctuation; it reconciles HTML whitespace or includes actual adjacent context for a short quote, and does not establish entailment.","key":"5","section":"guidance"}
M research-assistant "A literal span repair copies one contiguous actual source span, preserving words, numbers and punctuation; it reconciles HTML whitespace or includes actual adjacent context for a short quote, and does not establish entailment." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"An explicit as-of day resolves Wikipedia revisions through the public API; month and year precision use the period's last day. Include a day when that boundary matters.","key":"6","section":"guidance"}
M research-assistant "An explicit as-of day resolves Wikipedia revisions through the public API; month and year precision use the period's last day. Include a day when that boundary matters." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"PDF sources use native pypdf extraction with a 32-MiB response byte limit and 2,097,152-character extracted-text limit, separately labeled from DOM text. Metadata records actual SHA, pages and truncation. Encrypted, malformed, incomplete or oversized PDFs are refused; no OCR or invented text is used.","key":"7","section":"guidance"}
M research-assistant "PDF sources use native pypdf extraction with a 32-MiB response byte limit and 2,097,152-character extracted-text limit, separately labeled from DOM text. Metadata records actual SHA, pages and truncation. Encrypted, malformed, incomplete or oversized PDFs are refused; no OCR or invented text is used." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Research arms receive only public prompts. Independent comparator outputs and reference answers never enter Neyvia context. Every model call has actual token receipts; evaluation overhead is separate.","key":"8","section":"guidance"}
M research-assistant "Research arms receive only public prompts. Independent comparator outputs and reference answers never enter Neyvia context. Every model call has actual token receipts; evaluation overhead is separate." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Retrieved text and captured table rows retain C10b context budgets. Source ranking is advisory, never factual evidence. No whole-panel accuracy or cost claim follows from a successful native answer.","key":"9","section":"guidance"}
M research-assistant "Retrieved text and captured table rows retain C10b context budgets. Source ranking is advisory, never factual evidence. No whole-panel accuracy or cost claim follows from a successful native answer." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"The request has a 600-second bounded model deadline. Missing providers, inaccessible sources, invalid quotes and rejected claims remain visible; no invented text or answer fallback.","key":"10","section":"guidance"}
M research-assistant "The request has a 600-second bounded model deadline. Missing providers, inaccessible sources, invalid quotes and rejected claims remain visible; no invented text or answer fallback." src:"authored manual" state:verified
-- @record {"chapter":"public-research","data":"Existing owner browser runtimes are borrowed and must not be stopped by a research call.","key":"11","section":"guidance"}
M research-assistant "Existing owner browser runtimes are borrowed and must not be stopped by a research call." src:"authored manual" state:verified
L research-assistant.tool-gate v1 -- Research tool correctness and latency gates
-- @record {"chapter":"tool-gate","data":{"effect":"Read the recorded public-source benchmark; do not run another research model or modify providers.","pre":"A bounded receipt.json under the selected task root contains the actual fixed tool benchmark observations.","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.research.receipt","tool":"neyvia.research.receipt"},"key":"observe-tool-gate","section":"actions"}
A neyvia.research.receipt(path:str#1..) -> json:"{\"type\":\"object\"}" -- Read the recorded public-source benchmark; do not run another research model or modify providers.
C neyvia.research.receipt tool-gate-measured:matches(neyvia.research.receipt(path:path) {properties:{allMeasured:{const:true} casesSha256:{const:"14a0187091c99076a30e9a61ca444a0b52ccbf6c0503a5127f607ade6e40d632"} measuredTools:{const:17} selected:{additionalProperties:{properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0 type:"number"} failureRate:{maximum:1 minimum:0 type:"number"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"} required:["web.fetch" "web.read" "web.passages" "web.cite" "web.dedupe" "web.search" "web.image_search" "neyvia.research.receipt" "neyvia.browser.decide" "web.fetch.pdf" "neyvia.pdf.open" "neyvia.pdf.extract_text" "neyvia.pdf.search" "neyvia.pdf.state" "neyvia.browser.open" "neyvia.browser.observe" "neyvia.browser.capture"] type:"object"}} required:["allMeasured" "measuredTools" "casesSha256" "selected"] type:"object"})
C neyvia.research.receipt gate-web-fetch:matches(neyvia.research.receipt(path:path) .selected.web.fetch {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-read:matches(neyvia.research.receipt(path:path) .selected.web.read {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-passages:matches(neyvia.research.receipt(path:path) .selected.web.passages {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-cite:matches(neyvia.research.receipt(path:path) .selected.web.cite {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-dedupe:matches(neyvia.research.receipt(path:path) .selected.web.dedupe {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-search:matches(neyvia.research.receipt(path:path) .selected.web.search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-image_search:matches(neyvia.research.receipt(path:path) .selected.web.image_search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-research-receipt:matches(neyvia.research.receipt(path:path) .selected.neyvia.research.receipt {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-browser-decide:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.decide {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-web-fetch-pdf:matches(neyvia.research.receipt(path:path) .selected.web.fetch.pdf {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-pdf-open:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.open {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-pdf-extract_text:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.extract_text {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-pdf-search:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-pdf-state:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.state {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-browser-open:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.open {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-browser-observe:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.observe {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
C neyvia.research.receipt gate-neyvia-browser-capture:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.capture {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":"","schema":{"properties":{"allMeasured":{"const":true},"casesSha256":{"const":"14a0187091c99076a30e9a61ca444a0b52ccbf6c0503a5127f607ade6e40d632"},"measuredTools":{"const":17},"selected":{"additionalProperties":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0,"type":"number"},"failureRate":{"maximum":1,"minimum":0,"type":"number"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"},"required":["web.fetch","web.read","web.passages","web.cite","web.dedupe","web.search","web.image_search","neyvia.research.receipt","neyvia.browser.decide","web.fetch.pdf","neyvia.pdf.open","neyvia.pdf.extract_text","neyvia.pdf.search","neyvia.pdf.state","neyvia.browser.open","neyvia.browser.observe","neyvia.browser.capture"],"type":"object"}},"required":["allMeasured","measuredTools","casesSha256","selected"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"tool-gate-measured","section":"checks"}
C neyvia.research.receipt tool-gate-measured:matches(neyvia.research.receipt(path:path) {properties:{allMeasured:{const:true} casesSha256:{const:"14a0187091c99076a30e9a61ca444a0b52ccbf6c0503a5127f607ade6e40d632"} measuredTools:{const:17} selected:{additionalProperties:{properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0 type:"number"} failureRate:{maximum:1 minimum:0 type:"number"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"} required:["web.fetch" "web.read" "web.passages" "web.cite" "web.dedupe" "web.search" "web.image_search" "neyvia.research.receipt" "neyvia.browser.decide" "web.fetch.pdf" "neyvia.pdf.open" "neyvia.pdf.extract_text" "neyvia.pdf.search" "neyvia.pdf.state" "neyvia.browser.open" "neyvia.browser.observe" "neyvia.browser.capture"] type:"object"}} required:["allMeasured" "measuredTools" "casesSha256" "selected"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.fetch"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-fetch","section":"checks"}
C neyvia.research.receipt gate-web-fetch:matches(neyvia.research.receipt(path:path) .selected.web.fetch {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.read"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-read","section":"checks"}
C neyvia.research.receipt gate-web-read:matches(neyvia.research.receipt(path:path) .selected.web.read {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.passages"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-passages","section":"checks"}
C neyvia.research.receipt gate-web-passages:matches(neyvia.research.receipt(path:path) .selected.web.passages {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.cite"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-cite","section":"checks"}
C neyvia.research.receipt gate-web-cite:matches(neyvia.research.receipt(path:path) .selected.web.cite {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.dedupe"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-dedupe","section":"checks"}
C neyvia.research.receipt gate-web-dedupe:matches(neyvia.research.receipt(path:path) .selected.web.dedupe {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.search"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-search","section":"checks"}
C neyvia.research.receipt gate-web-search:matches(neyvia.research.receipt(path:path) .selected.web.search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.image_search"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-image_search","section":"checks"}
C neyvia.research.receipt gate-web-image_search:matches(neyvia.research.receipt(path:path) .selected.web.image_search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.research.receipt"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-research-receipt","section":"checks"}
C neyvia.research.receipt gate-neyvia-research-receipt:matches(neyvia.research.receipt(path:path) .selected.neyvia.research.receipt {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.browser.decide"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-browser-decide","section":"checks"}
C neyvia.research.receipt gate-neyvia-browser-decide:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.decide {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","web.fetch.pdf"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-web-fetch-pdf","section":"checks"}
C neyvia.research.receipt gate-web-fetch-pdf:matches(neyvia.research.receipt(path:path) .selected.web.fetch.pdf {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.pdf.open"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-pdf-open","section":"checks"}
C neyvia.research.receipt gate-neyvia-pdf-open:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.open {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.pdf.extract_text"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-pdf-extract_text","section":"checks"}
C neyvia.research.receipt gate-neyvia-pdf-extract_text:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.extract_text {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.pdf.search"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-pdf-search","section":"checks"}
C neyvia.research.receipt gate-neyvia-pdf-search:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.search {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.pdf.state"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-pdf-state","section":"checks"}
C neyvia.research.receipt gate-neyvia-pdf-state:matches(neyvia.research.receipt(path:path) .selected.neyvia.pdf.state {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.browser.open"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-browser-open","section":"checks"}
C neyvia.research.receipt gate-neyvia-browser-open:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.open {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.browser.observe"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-browser-observe","section":"checks"}
C neyvia.research.receipt gate-neyvia-browser-observe:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.observe {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"schema","path":["selected","neyvia.browser.capture"],"schema":{"properties":{"baseline":{"required":["correct","p50Ms","p95Ms"],"type":"object"},"cases":{"minimum":20,"type":"integer"},"correct":{"minimum":0,"type":"integer"},"correctness":{"maximum":1,"minimum":0.95,"type":"number"},"failureRate":{"maximum":0.05,"minimum":0,"type":"number"},"gates":{"properties":{"latency":{"const":true},"twentyRealCases":{"const":true}},"required":["latency","twentyRealCases"],"type":"object"},"p50Ms":{"minimum":0,"type":"number"},"p95Ms":{"minimum":0,"type":"number"}},"required":["cases","correct","correctness","failureRate","p50Ms","p95Ms","baseline","gates"],"type":"object"}},"tool":"neyvia.research.receipt"},"key":"gate-neyvia-browser-capture","section":"checks"}
C neyvia.research.receipt gate-neyvia-browser-capture:matches(neyvia.research.receipt(path:path) .selected.neyvia.browser.capture {properties:{baseline:{required:["correct" "p50Ms" "p95Ms"] type:"object"} cases:{minimum:20 type:"integer"} correct:{minimum:0 type:"integer"} correctness:{maximum:1 minimum:0.95 type:"number"} failureRate:{maximum:0.05 minimum:0 type:"number"} gates:{properties:{latency:{const:true} twentyRealCases:{const:true}} required:["latency" "twentyRealCases"] type:"object"} p50Ms:{minimum:0 type:"number"} p95Ms:{minimum:0 type:"number"}} required:["cases" "correct" "correctness" "failureRate" "p50Ms" "p95Ms" "baseline" "gates"] type:"object"})
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against tool-gate-measured","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"tool-gate-measured","save":"observed"}]},"key":"tool-gate-measured","section":"procedures"}
P tool-gate-measured(path:str#1..):observed=neyvia.research.receipt(path:path) C tool-gate-measured -- Inspect the fixed real-case evidence against tool-gate-measured
V P tool-gate-measured -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-fetch","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-fetch","save":"observed"}]},"key":"gate-web-fetch","section":"procedures"}
P gate-web-fetch(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-fetch -- Inspect the fixed real-case evidence against gate-web-fetch
V P gate-web-fetch -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-read","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-read","save":"observed"}]},"key":"gate-web-read","section":"procedures"}
P gate-web-read(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-read -- Inspect the fixed real-case evidence against gate-web-read
V P gate-web-read -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-passages","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-passages","save":"observed"}]},"key":"gate-web-passages","section":"procedures"}
P gate-web-passages(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-passages -- Inspect the fixed real-case evidence against gate-web-passages
V P gate-web-passages -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-cite","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-cite","save":"observed"}]},"key":"gate-web-cite","section":"procedures"}
P gate-web-cite(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-cite -- Inspect the fixed real-case evidence against gate-web-cite
V P gate-web-cite -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-dedupe","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-dedupe","save":"observed"}]},"key":"gate-web-dedupe","section":"procedures"}
P gate-web-dedupe(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-dedupe -- Inspect the fixed real-case evidence against gate-web-dedupe
V P gate-web-dedupe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-search","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-search","save":"observed"}]},"key":"gate-web-search","section":"procedures"}
P gate-web-search(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-search -- Inspect the fixed real-case evidence against gate-web-search
V P gate-web-search -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-image_search","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-image_search","save":"observed"}]},"key":"gate-web-image_search","section":"procedures"}
P gate-web-image_search(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-image_search -- Inspect the fixed real-case evidence against gate-web-image_search
V P gate-web-image_search -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-research-receipt","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-research-receipt","save":"observed"}]},"key":"gate-neyvia-research-receipt","section":"procedures"}
P gate-neyvia-research-receipt(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-research-receipt -- Inspect the fixed real-case evidence against gate-neyvia-research-receipt
V P gate-neyvia-research-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-browser-decide","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-browser-decide","save":"observed"}]},"key":"gate-neyvia-browser-decide","section":"procedures"}
P gate-neyvia-browser-decide(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-browser-decide -- Inspect the fixed real-case evidence against gate-neyvia-browser-decide
V P gate-neyvia-browser-decide -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-web-fetch-pdf","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-web-fetch-pdf","save":"observed"}]},"key":"gate-web-fetch-pdf","section":"procedures"}
P gate-web-fetch-pdf(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-web-fetch-pdf -- Inspect the fixed real-case evidence against gate-web-fetch-pdf
V P gate-web-fetch-pdf -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-pdf-open","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-pdf-open","save":"observed"}]},"key":"gate-neyvia-pdf-open","section":"procedures"}
P gate-neyvia-pdf-open(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-pdf-open -- Inspect the fixed real-case evidence against gate-neyvia-pdf-open
V P gate-neyvia-pdf-open -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-pdf-extract_text","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-pdf-extract_text","save":"observed"}]},"key":"gate-neyvia-pdf-extract_text","section":"procedures"}
P gate-neyvia-pdf-extract_text(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-pdf-extract_text -- Inspect the fixed real-case evidence against gate-neyvia-pdf-extract_text
V P gate-neyvia-pdf-extract_text -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-pdf-search","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-pdf-search","save":"observed"}]},"key":"gate-neyvia-pdf-search","section":"procedures"}
P gate-neyvia-pdf-search(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-pdf-search -- Inspect the fixed real-case evidence against gate-neyvia-pdf-search
V P gate-neyvia-pdf-search -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-pdf-state","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-pdf-state","save":"observed"}]},"key":"gate-neyvia-pdf-state","section":"procedures"}
P gate-neyvia-pdf-state(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-pdf-state -- Inspect the fixed real-case evidence against gate-neyvia-pdf-state
V P gate-neyvia-pdf-state -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-browser-open","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-browser-open","save":"observed"}]},"key":"gate-neyvia-browser-open","section":"procedures"}
P gate-neyvia-browser-open(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-browser-open -- Inspect the fixed real-case evidence against gate-neyvia-browser-open
V P gate-neyvia-browser-open -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-browser-observe","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-browser-observe","save":"observed"}]},"key":"gate-neyvia-browser-observe","section":"procedures"}
P gate-neyvia-browser-observe(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-browser-observe -- Inspect the fixed real-case evidence against gate-neyvia-browser-observe
V P gate-neyvia-browser-observe -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"goal":"Inspect the fixed real-case evidence against gate-neyvia-browser-capture","inputs":{"$cl_type":"t9"},"steps":[{"action":"observe-tool-gate","args":{"path":{"$input":"path"}},"check":"gate-neyvia-browser-capture","save":"observed"}]},"key":"gate-neyvia-browser-capture","section":"procedures"}
P gate-neyvia-browser-capture(path:str#1..):observed=neyvia.research.receipt(path:path) C gate-neyvia-browser-capture -- Inspect the fixed real-case evidence against gate-neyvia-browser-capture
V P gate-neyvia-browser-capture -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"tool-gate","data":{"failure":"Complete measurement is reported as passing tool quality","recovery":"Run the measured contract and every tool contract separately; preserve failed gates and compare paired baselines."},"key":"0","section":"pitfalls"}
X Complete measurement is reported as passing tool quality -> Run the measured contract and every tool contract separately; preserve failed gates and compare paired baselines.
-- @record {"chapter":"tool-gate","data":"These contracts inspect fixed real-case observations. They do not prove 49/50 answer accuracy, semantic entailment or public deployment.","key":"0","section":"frontier"}
F These contracts inspect fixed real-case observations. They do not prove 49/50 answer accuracy, semantic entailment or public deployment.
-- @record {"chapter":"tool-gate","data":"Use the byte-identical C10-tools.json copy at tool-gate/receipt.json, confined to the task runtime. Preserve raw per-case observations and the frozen corpus hash.","key":"0","section":"guidance"}
M research-assistant "Use the byte-identical C10-tools.json copy at tool-gate/receipt.json, confined to the task runtime. Preserve raw per-case observations and the frozen corpus hash." src:"authored manual" state:verified
-- @record {"chapter":"tool-gate","data":"Run scripts/c10_tools.py for actual native tool and paired baseline measurements. The contracts below are the acceptance criteria; no new test files.","key":"1","section":"guidance"}
M research-assistant "Run scripts/c10_tools.py for actual native tool and paired baseline measurements. The contracts below are the acceptance criteria; no new test files." src:"authored manual" state:verified
-- @record {"chapter":"tool-gate","data":"Run scripts/c10_tools.py with --ports (caller-assigned, e.g. 49041-49049), --obscura (explicit admitted engine) and --runtime-root on a fast local disk; there is no default port. --prefer-phase-prefix rx- selects the 2026-10-06 phases: 16/17 tools pass; neyvia.browser.decide is limited by the frozen LAYA relevance model (14/20), not by ports or providers.","key":"2","section":"guidance"}
M research-assistant "Run scripts/c10_tools.py with --ports (caller-assigned, e.g. 49041-49049), --obscura (explicit admitted engine) and --runtime-root on a fast local disk; there is no default port. --prefer-phase-prefix rx- selects the 2026-10-06 phases: 16/17 tools pass; neyvia.browser.decide is limited by the frozen LAYA relevance model (14/20), not by ports or providers." src:"authored manual" state:verified
