CL 1
L runtime-provider v1 -- Authored executable manual
-- @manual {"chapters":{"local-content-cache":{"title":"Local content-addressed cache"},"local-transfer-protocol":{"title":"Local bridge and transfer protocol fixtures"},"portable-platform":{"title":"Portable paths and local setup plans"},"provider-coordination":{"title":"PROOFS-d: durable provider scheduling and queue ownership"},"provider-effects":{"title":"Exact provider owner effects"},"requests-and-routes":{"title":"Profiles, provider requests and route plans"},"runtime-output":{"title":"Runtime outputs, wrappers and replay"}},"clVersion":"1.1","id":"runtime-provider","kind":"environment","proofs":{"area":"d-runtime","manifests":["config/proofs/d-runtime.json"],"startup":{"procedures":["runtime output and file-backed replay","current profile and tool request plans","portable path and setup plans","local BLAKE3 admission and adverse reads","local mirror message/transfer bytes and receipts","durable local auth queue and concurrent startup ownership","SQLite provider circuits, concurrent canary leases and a scratch child worker"],"runner":"grant_agent.proofs_d_runtime.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"codex.assets.import":"t1","neyvia.claude.mods":"t2","neyvia.efficiency.extract":"t3","neyvia.session.new":"t4","terminal.exec":"t5","workspace.read":"t6"},"tool_metadata":{"codex.assets.import":{},"neyvia.claude.mods":{},"neyvia.session.new":{},"terminal.exec":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["grant_agent.runtime_handback.build_handback","grant_agent.proofs_d_runtime.check"],"claim":"Runtime output retains its invocation/runtime origin, exact content and counts; content hashes make repeat handback idempotent while new resumed output remains carryable. Empty output has no invented completion.","id":"d.runtime.handback.identity","impact":["parent transcript","runtime provenance","resumed output"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_handback.handback_messages","grant_agent.proofs_d_runtime.check"],"claim":"Handed-back transcript messages retain content/text and origin; user/operator messages are authored by You, other messages by their originating runtime.","id":"d.runtime.handback.transcript","impact":["parent transcript authorship"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_wrapper.build_runtime_wrapper_spec","grant_agent.runtime_wrapper.runtime_wrapper_payload","grant_agent.proofs_d_runtime.check"],"claim":"Only supported wrappers with nonempty commands produce specs; exact command, cwd, timeout and sorted environment key names survive without serializing environment values.","id":"d.runtime.wrapper.spec","impact":["external runtime wrapper launch plans"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_wrapper.build_runtime_wrapper_state","grant_agent.proofs_d_runtime.check"],"claim":"Wrapper observations retain their runtime/cwd, observed processes, masked environment status, positive TTL and nonnegative heartbeat age; actual file tails stay bounded.","id":"d.runtime.wrapper.state","impact":["runtime observation","bounded logs"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_wrapper.build_runtime_wrapper_phase_event","grant_agent.proofs_d_runtime.check"],"claim":"Phase events retain the wrapper's runtime/cwd/log path and the supplied mission/run/phase/status/message association.","id":"d.runtime.wrapper.event","impact":["mission phase event provenance"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_wrapper.build_runtime_wrapper_execution_receipt","grant_agent.proofs_d_runtime.check"],"claim":"Execution receipts project the exact wrapper command, changed files, bounded observed logs, process tree, masked environment, heartbeat age and TTL.","id":"d.runtime.wrapper.receipt","impact":["runtime execution receipts"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_wrapper.replay_runtime_wrapper","grant_agent.proofs_d_runtime.check"],"claim":"File-backed replay admits only real dictionary rows, skips missing/malformed inputs, respects the event bound and derives latest status from observed receipt/event rows.","id":"d.runtime.wrapper.replay","impact":["runtime replay","honest completion status"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.profiles.ProfileRegistry.resolve","grant_agent.proofs_d_runtime.check"],"claim":"Profile selection resolves an explicit existing name first, first matching workspace rule second and registered default last, preserving the selected profile's agent policy.","id":"d.runtime.profile.resolve","impact":["personalization","agent risk policy"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.openai_adapter.tools_from_skills","grant_agent.proofs_d_runtime.check"],"claim":"Skill tools retain name, description, schema and strictness; enabled code execution retains auto memory/file configuration or selected container identity.","id":"d.runtime.openai.tools","impact":["OpenAI request tool schemas"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.openai_adapter.OpenAIRequestPlan.as_dict","grant_agent.proofs_d_runtime.check"],"claim":"Wire serialization preserves model, user input, tools, storage policy and requested continuation/instructions/tool-choice; unset optional fields are omitted.","id":"d.runtime.openai.request","impact":["OpenAI route and request payload"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.replay.build_lineage_timeline","grant_agent.proofs_d_runtime.check"],"claim":"A lineage timeline consists only of real source JSONL dictionaries, in lineage/source order, tagged with the originating session; missing/malformed rows do not invent events.","id":"d.runtime.lineage.source","impact":["session lineage replay"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.platform_config.PlatformConfig.from_env","grant_agent.proofs_d_runtime.check"],"claim":"Explicit workspace and configured environment roots, project name and Windows mirror survive PlatformConfig construction; this projection performs no NAS activity.","id":"d.runtime.platform.roots","impact":["platform path correspondence"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.platform_config.PlatformConfig.path_candidates","grant_agent.proofs_d_runtime.check"],"claim":"Path candidates are unique; a configured remote project path includes its corresponding local workspace and configured mirror path.","id":"d.runtime.platform.candidates","impact":["portable saved paths"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.platform_config.PlatformConfig.coerce_path","grant_agent.runtime_supervisor._coerce_platform_path","grant_agent.proofs_d_runtime.check"],"claim":"Explicit POSIX coercion maps an embedded Windows drive path to its /mnt drive mount and preserves the remaining path, including through the supervisor's pure helper.","id":"d.runtime.platform.coerce","impact":["portable session paths"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.p2p_cache.P2PCacheService.compatibility_snapshot","grant_agent.proofs_d_runtime.check"],"claim":"Cache compatibility separates implemented features, configured peers and hash-admitted available sidecar transport; declared transport versions and public discovery policy are projected honestly.","id":"d.runtime.cache.compatibility","impact":["P2P readiness claims"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.p2p_cache.P2PCacheService.bootstrap","grant_agent.proofs_d_runtime.check"],"claim":"Bootstrap observes exact local object/byte/pin counts and transport readiness without allocating an index or claiming a missing transport is ready.","id":"d.runtime.cache.bootstrap","impact":["local cache readiness"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.p2p_cache.P2PCacheService.plan_import","grant_agent.p2p_cache.P2PCacheService._workspace_file","grant_agent.proofs_d_runtime.check"],"claim":"Import plans are workspace-scoped, BLAKE3/hash bound, preserve current source metadata and kind/pin intent, and state that local import needs no network or publication.","id":"d.runtime.cache.plan","impact":["local CAS import approval"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.p2p_cache.P2PCacheService.import_object","grant_agent.proofs_d_runtime.check"],"claim":"An unapproved local import performs no admission; approved receipts retain plan/content/source identity and pin/kind, honestly distinguish copy from deduplication and claim only locally verified bytes. Source or plan drift fails closed.","id":"d.runtime.cache.import","impact":["local CAS integrity and approval"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.p2p_cache.P2PCacheService.read_text","grant_agent.p2p_cache.P2PCacheService._verified_object","grant_agent.proofs_d_runtime.check"],"claim":"Local context reads are bounded, retain digest/offset and match actual admitted bytes and truncation; invalid hash/range or changed admitted content fails closed before context is returned.","id":"d.runtime.cache.read","impact":["model context integrity"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_updates.compare_version_tokens","grant_agent.proofs_d_runtime.check"],"claim":"Runtime semantic/date versions compare numeric token tuples; v prefixes do not change version identity.","id":"d.runtime.version.order","impact":["runtime update eligibility"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/repair_nas_opencode_go_auth.py:merge_provider_env","scripts/repair_nas_opencode_go_auth.py:check_provider_env_merge","grant_agent.proofs_d_runtime.self_check"],"claim":"The pure Go environment merge retains unrelated provider entries, emits exactly one safely quoted current OPENCODE_API_KEY export and rejects an empty credential value.","id":"d.runtime.go-env.merge","impact":["provider environment text transformation"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/repair_nas_opencode_go_auth.py:_redact","grant_agent.proofs_d_runtime.self_check"],"claim":"The pure receipt redactor removes the supplied secret and returns at most 8000 characters; proof fixtures use in-memory scratch strings only.","id":"d.runtime.go-env.redact","impact":["repair receipt secrecy"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.__init__.__getattr__","grant_agent.proofs_d_runtime.check_package_export","grant_agent.proofs_d_runtime.self_check:fresh interpreter"],"claim":"Public service classes stay lazy until requested, then retain their backwards-compatible public class identity; package import alone does not load the autonomous engine.","id":"d.runtime.package.export","impact":["package startup cost","public import API"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.runtime_lane_cycle.normalize_lane_routes","grant_agent.proofs_d_runtime.check"],"claim":"The four required context/planner/executor/verifier lanes keep their role order and the selected runtime alias normalizes to the owning runtime without launch or route substitution.","id":"d.runtime.lane.aliases","impact":["runtime lane route plans"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/nas_setup.py:collect_add_users","grant_agent.proofs_d_runtime.self_check"],"claim":"Repeated flags and comma lists produce exactly the first-seen nonempty usernames once, preserving order.","id":"d.runtime.nas-setup.users","impact":["local setup argument parsing"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/setup_nas_https.py:split_hosts","grant_agent.proofs_d_runtime.self_check"],"claim":"Normalized host identities are unique and partition exactly into DNS names and valid IP addresses; a trailing DNS dot does not duplicate a host.","id":"d.runtime.nas-setup.hosts","impact":["TLS host argument planning"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/setup_nas_https.py:backend_start_command","grant_agent.proofs_d_runtime.self_check"],"claim":"The TLS backend command plan retains its explicit port, public URL and certificate/key paths; verification never launches that command or reads those files.","id":"d.runtime.nas-setup.tls-command","impact":["TLS backend command plans"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/install_nas_runtime_stack.py:node_platform_arch","scripts/install_nas_runtime_stack.py:node_dist_url","grant_agent.proofs_d_runtime.self_check"],"claim":"Supported CPU names resolve to packaged Node architecture and the planned HTTPS archive URL preserves version/architecture; unsupported CPU or empty version stops before download.","id":"d.runtime.nas-setup.node-plan","impact":["packaged runtime install plans"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_bridge.NasBridge._copy_resumable","grant_agent.proofs_d_runtime.check"],"claim":"Bridge copy completion matches actual destination SHA-256 and source size; deduplication reuses all bytes and partial resume transfers exactly the remainder.","id":"d.runtime.bridge.bytes","impact":["attachment byte integrity","local protocol resume"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_bridge.NasBridge.send_message","grant_agent.proofs_d_runtime.check"],"claim":"Each sent message's inbox/outbox envelopes exactly match its returned message and attachment metadata; transfer/reuse totals derive only from attachment receipts.","id":"d.runtime.bridge.envelope","impact":["message/attachment envelopes"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_bridge.NasBridge.receive_messages","grant_agent.proofs_d_runtime.check"],"claim":"Received materialized attachments stay under the selected output root, match actual SHA-256 and retain file names; optional acknowledgements retain message identity and inbox count stays bounded.","id":"d.runtime.bridge.receive","impact":["verified local receive","message acknowledgements"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_transfer._copy_file_resumable","grant_agent.proofs_d_runtime.check"],"claim":"Completed file copies match destination size and SHA-256, preserve exact remaining-byte resume accounting; unchanged-metadata skips do no transfer/hash work.","id":"d.runtime.transfer.file","impact":["file transfer integrity","resume and metadata skip"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_transfer._copy_directory","grant_agent.proofs_d_runtime.check"],"claim":"Directory transfer receipts account for filtered/changed/skipped files and hash-check every actually transferred destination; explicit include-all is retained and unchanged metadata does not fabricate verification work.","id":"d.runtime.transfer.directory","impact":["directory filtering and collision preservation"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.nas_transfer.NasTransfer._write_receipt","grant_agent.nas_transfer.NasTransfer.send","grant_agent.nas_transfer.NasTransfer.send_manifest","grant_agent.proofs_d_runtime.check"],"claim":"A completed transfer returns the identical JSON receipt durably persisted at its selected sender and mirror protocol roots; destination escape, unavailable explicit root and invalid batch sources stop before successful receipt/copy.","id":"d.runtime.transfer.receipt","impact":["recoverable transfer receipts","destination/preflight boundaries"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue._load_from_directory","grant_agent.proofs_d_runtime_auth.check_queue_payload"],"claim":"Durable queue schema, ordered unique provider identities, canonical lifecycle and public flow metadata remain valid on every load; malformed/future state fails closed without overwrite.","id":"d.runtime.auth-queue.state","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue._save","grant_agent.proofs_d_runtime_auth.check_queue_save"],"claim":"Successful queue writes reread the exact payload through the existing anchored provider-state directory; no credential file is part of this proof.","id":"d.runtime.auth-queue.persisted","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue._mutation","grant_agent.proofs_d_runtime_auth.check_queue_transition"],"claim":"Queue mutations preserve durable queue/provider operation identities, settle supplied presence observations, expose lost evidence as blocked, and keep cancelled/skipped operations terminal.","id":"d.runtime.auth-queue.transition","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue.record_flow","grant_agent.proofs_d_runtime_auth.check_queue_transition"],"claim":"Only public flow receipt fields persist; sessionless observers preserve the owning session and conflicting sessions cannot overwrite its durable evidence.","id":"d.runtime.auth-queue.flow","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue._present","grant_agent.proofs_d_runtime_auth.check_queue_present"],"claim":"Public queue views retain lifecycle and policy, hide opaque startup ownership, declare no stored secret material and keep Anthropic on its official provider route.","id":"d.runtime.auth-queue.projection","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.provider_auth_queue.ProviderAuthQueue._mutation","grant_agent.provider_auth_queue.ProviderAuthQueue._present","grant_agent.proofs_d_runtime_auth.check_queue_payload","grant_agent.proofs_d_runtime_auth.check_queue_transition","grant_agent.proofs_d_runtime_auth.check_queue_present"],"claim":"Existing workspace locks and canonical bounded durable leases reserve one startup owner; waiting pollers receive no executable action, stale owners cannot publish, and completion leaves the next startup unclaimed until a real poller.","id":"d.runtime.auth-queue.startup","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.cluster.ClusterRegistry._provider_circuit_admission_db","grant_agent.proofs_d_runtime_auth.circuit_admission"],"claim":"Inside the existing SQLite lease transaction, closed routes admit work, open cooldowns deny, and half-open routes reserve exactly one live canary keyed by host/runtime/provider. Direct lease creation rechecks the same admission rule.","id":"d.runtime.circuit.admission","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.cluster.ClusterRegistry.record_provider_result","grant_agent.proofs_d_runtime_auth.check_circuit_result"],"claim":"Observed result metadata opens only its route, respects transient thresholds and preserves stronger auth/credit cooldown against late results; successful owned canaries close/reset and failed/inconclusive canaries reopen durably.","id":"d.runtime.circuit.transition","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.cluster.classify_provider_result","grant_agent.proofs_d_runtime_auth.check_classification"],"claim":"Provider result classification keeps route identity and only bounded category evidence, separates auth/credit/rate/overload/transport, and explicit process success wins over authentication words in output.","id":"d.runtime.circuit.classification","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.cluster.ClusterRegistry.reset_provider_circuit","grant_agent.proofs_d_runtime_auth.check_circuit_reset"],"claim":"Manual circuit reset redacts bounded actor/reason evidence and asks for one future half-open canary rather than bypassing observed failure.","id":"d.runtime.circuit.reset","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.cluster.ClusterRegistry.record_provider_result","grant_agent.proofs_d_runtime_auth.check_circuit_reporting"],"claim":"Provider result publication requires the current active lease, matching job and reporting host; mismatched reporting does not update a provider circuit.","id":"d.runtime.circuit.reporting","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.worker.run_local_worker_once","grant_agent.worker.build_worker_doctor","grant_agent.proofs_d_runtime_auth.check_worker_circuit_before_completion","grant_agent.proofs_d_runtime_auth.check_worker_doctor","grant_agent.proofs_d_runtime_auth.observed_worker_capabilities"],"claim":"Workers record provider failure before durable job completion and doctor exposes every open/half-open route. Explicit trusted local capability observations/environment keep scratch runs within their owned root; they do not prove provider authentication or permit external workspace mappings.","id":"d.runtime.circuit.worker","impact":["durable local provider coordination","provider authority and scheduling"],"phase":"invariant"}
T t1 json:"{\"type\":\"object\",\"properties\":{\"codexHome\":{\"type\":\"string\"}}}"
T t2{enabled?:bool ..}
T t3{path:str field:str strategy?:json:"{\"type\":\"string\",\"enum\":[\"cascade\",\"direct-small\",\"direct-big\"]}" useScript?:bool ..}
T t4 json:"{\"type\":\"object\",\"properties\":{\"app\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"requestId\":{\"type\":\"string\"}},\"required\":[\"app\",\"folder\",\"prompt\",\"requestId\"],\"allOf\":[{\"properties\":{\"app\":{\"not\":{\"enum\":[\"\"]}},\"folder\":{\"not\":{\"enum\":[\"\"]}},\"prompt\":{\"not\":{\"enum\":[\"\"]}},\"requestId\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t5{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t6 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7{ok:true exitCode:0 ..}
T t8 json:"{\"type\":\"object\"}"
T t9{command:str#1.. expectedMarker:str}
T t10 json:"{\"type\":\"object\",\"properties\":{\"app\":{\"type\":\"string\"},\"folder\":{\"type\":\"string\"},\"prompt\":{\"type\":\"string\"},\"model\":{\"type\":\"string\"},\"permissionMode\":{\"type\":\"string\"},\"requestId\":{\"type\":\"string\"}},\"required\":[\"app\",\"folder\",\"prompt\",\"requestId\",\"model\",\"permissionMode\"],\"additionalProperties\":false}"
T t11{enabled:bool}
T t12{codexHome:str}
L runtime-provider.local-content-cache v1 -- Local content-addressed cache
-- @record {"chapter":"local-content-cache","data":{"effect":"Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete.","pre":"Owned disposable cwd, explicit owner approval and the pinned C8e journey adapter. Never use the input desktop or an external provider.","returns":{"$cl_type":"t7"},"reversible":true,"schema":"terminal.exec","tool":"terminal.exec"},"key":"exercise","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> {ok:true exitCode:0 ..} ! -- Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete.
F verify-exercise "No authored observer check is bound to terminal.exec" -> ask operator blocks:terminal.exec
-- @record {"chapter":"local-content-cache","data":{"effect":"Read durable effect bytes afresh through the workspace boundary.","pre":"Read the actual artifact produced by this procedure.","returns":{"$cl_type":"t8"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"read-effect","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> json:"{\"type\":\"object\"}" -- Read durable effect bytes afresh through the workspace boundary.
C workspace.read child-output:workspace.read(path:"runtime-child.txt") .content == "C8e actual hidden child output"
C workspace.read actual-replay-completed:neyvia.efficiency.extract(field:"/replay/latestStatus" path:"c8e-effects/runtime-provider/effect.json" useScript:true) .answer.valueJson == "\"completed\""
C workspace.read missing-receipt-not-invented:neyvia.efficiency.extract(field:"/missingReplay/receiptCount" path:"c8e-effects/runtime-provider/effect.json" useScript:true) .answer.valueJson == "0"
-- @record {"chapter":"local-content-cache","data":{"args":{"path":"runtime-child.txt"},"expect":{"op":"eq","path":"content","value":"C8e actual hidden child output"},"tool":"workspace.read"},"key":"child-output","section":"checks"}
C workspace.read child-output:workspace.read(path:"runtime-child.txt") .content == "C8e actual hidden child output"
-- @record {"chapter":"local-content-cache","data":{"args":{"field":"/replay/latestStatus","path":"c8e-effects/runtime-provider/effect.json","useScript":true},"expect":{"op":"eq","path":"answer.valueJson","value":"\"completed\""},"tool":"neyvia.efficiency.extract"},"key":"actual-replay-completed","section":"checks"}
C neyvia.efficiency.extract actual-replay-completed:neyvia.efficiency.extract(field:"/replay/latestStatus" path:"c8e-effects/runtime-provider/effect.json" useScript:true) .answer.valueJson == "\"completed\""
-- @record {"chapter":"local-content-cache","data":{"args":{"field":"/missingReplay/receiptCount","path":"c8e-effects/runtime-provider/effect.json","useScript":true},"expect":{"op":"eq","path":"answer.valueJson","value":"0"},"tool":"neyvia.efficiency.extract"},"key":"missing-receipt-not-invented","section":"checks"}
C neyvia.efficiency.extract missing-receipt-not-invented:neyvia.efficiency.extract(field:"/missingReplay/receiptCount" path:"c8e-effects/runtime-provider/effect.json" useScript:true) .answer.valueJson == "0"
-- @record {"chapter":"local-content-cache","data":{"goal":"Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete.","inputs":{"$cl_type":"t9"},"steps":[{"action":"exercise","args":{"command":{"$input":"command"},"maxOutputChars":12000,"shell":"python","timeoutMs":30000},"save":"executed"},{"action":"read-effect","args":{"path":"c8e-effects/runtime-provider/effect.json"},"check":"child-output","save":"fresh0"},{"action":"read-effect","args":{"path":"c8e-effects/runtime-provider/effect.json"},"check":"actual-replay-completed","save":"fresh1"},{"action":"read-effect","args":{"path":"c8e-effects/runtime-provider/effect.json"},"check":"missing-receipt-not-invented","save":"fresh2"}]},"key":"run-hidden-child-and-replay","section":"procedures"}
P run-hidden-child-and-replay(command:str#1.. expectedMarker:str):executed=terminal.exec(command:command maxOutputChars:12000 shell:"python" timeoutMs:30000); fresh0=workspace.read(path:"c8e-effects/runtime-provider/effect.json") C child-output; fresh1=workspace.read(path:"c8e-effects/runtime-provider/effect.json") C actual-replay-completed; fresh2=workspace.read(path:"c8e-effects/runtime-provider/effect.json") C missing-receipt-not-invented -- Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete.
V P run-hidden-child-and-replay -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"local-content-cache","data":{"failure":"A local fixture receipt is treated as a provider, mounted NAS or public runtime success.","recovery":"Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X A local fixture receipt is treated as a provider, mounted NAS or public runtime success. -> Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier.
-- @record {"chapter":"local-content-cache","data":"External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.","key":"0","section":"frontier"}
F External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.
-- @record {"chapter":"local-content-cache","data":"This executable journey proves only Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete. Other declared contracts, rendered surfaces, physical devices and live provider behavior require their separate journeys.","key":"1","section":"frontier"}
F This executable journey proves only Execute a hidden local Python child, capture its real output, and replay the durable execution; missing records remain incomplete. Other declared contracts, rendered surfaces, physical devices and live provider behavior require their separate journeys.
-- @record {"chapter":"local-content-cache","data":"Cache compatibility separates implemented features, configured peers and hash-admitted available sidecar transport; declared transport versions and public discovery policy are projected honestly.","key":"0","section":"guidance"}
M runtime-provider "Cache compatibility separates implemented features, configured peers and hash-admitted available sidecar transport; declared transport versions and public discovery policy are projected honestly." src:"authored manual" state:verified
-- @record {"chapter":"local-content-cache","data":"Bootstrap observes exact local object/byte/pin counts and transport readiness without allocating an index or claiming a missing transport is ready.","key":"1","section":"guidance"}
M runtime-provider "Bootstrap observes exact local object/byte/pin counts and transport readiness without allocating an index or claiming a missing transport is ready." src:"authored manual" state:verified
-- @record {"chapter":"local-content-cache","data":"Import plans are workspace-scoped, BLAKE3/hash bound, preserve current source metadata and kind/pin intent, and state that local import needs no network or publication.","key":"2","section":"guidance"}
M runtime-provider "Import plans are workspace-scoped, BLAKE3/hash bound, preserve current source metadata and kind/pin intent, and state that local import needs no network or publication." src:"authored manual" state:verified
-- @record {"chapter":"local-content-cache","data":"An unapproved local import performs no admission; approved receipts retain plan/content/source identity and pin/kind, honestly distinguish copy from deduplication and claim only locally verified bytes. Source or plan drift fails closed.","key":"3","section":"guidance"}
M runtime-provider "An unapproved local import performs no admission; approved receipts retain plan/content/source identity and pin/kind, honestly distinguish copy from deduplication and claim only locally verified bytes. Source or plan drift fails closed." src:"authored manual" state:verified
-- @record {"chapter":"local-content-cache","data":"Local context reads are bounded, retain digest/offset and match actual admitted bytes and truncation; invalid hash/range or changed admitted content fails closed before context is returned.","key":"4","section":"guidance"}
M runtime-provider "Local context reads are bounded, retain digest/offset and match actual admitted bytes and truncation; invalid hash/range or changed admitted content fails closed before context is returned." src:"authored manual" state:verified
-- @record {"chapter":"local-content-cache","data":"Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner.","key":"5","section":"guidance"}
M runtime-provider "Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner." src:"authored manual" state:verified
L runtime-provider.local-transfer-protocol v1 -- Local bridge and transfer protocol fixtures
-- @record {"chapter":"local-transfer-protocol","data":{"failure":"A local fixture receipt is treated as a provider, mounted NAS or public runtime success.","recovery":"Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X A local fixture receipt is treated as a provider, mounted NAS or public runtime success. -> Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier.
-- @record {"chapter":"local-transfer-protocol","data":"External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.","key":"0","section":"frontier"}
F External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.
-- @record {"chapter":"local-transfer-protocol","data":"Bridge copy completion matches actual destination SHA-256 and source size; deduplication reuses all bytes and partial resume transfers exactly the remainder.","key":"0","section":"guidance"}
M runtime-provider "Bridge copy completion matches actual destination SHA-256 and source size; deduplication reuses all bytes and partial resume transfers exactly the remainder." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"Each sent message's inbox/outbox envelopes exactly match its returned message and attachment metadata; transfer/reuse totals derive only from attachment receipts.","key":"1","section":"guidance"}
M runtime-provider "Each sent message's inbox/outbox envelopes exactly match its returned message and attachment metadata; transfer/reuse totals derive only from attachment receipts." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"Received materialized attachments stay under the selected output root, match actual SHA-256 and retain file names; optional acknowledgements retain message identity and inbox count stays bounded.","key":"2","section":"guidance"}
M runtime-provider "Received materialized attachments stay under the selected output root, match actual SHA-256 and retain file names; optional acknowledgements retain message identity and inbox count stays bounded." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"Completed file copies match destination size and SHA-256, preserve exact remaining-byte resume accounting; unchanged-metadata skips do no transfer/hash work.","key":"3","section":"guidance"}
M runtime-provider "Completed file copies match destination size and SHA-256, preserve exact remaining-byte resume accounting; unchanged-metadata skips do no transfer/hash work." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"Directory transfer receipts account for filtered/changed/skipped files and hash-check every actually transferred destination; explicit include-all is retained and unchanged metadata does not fabricate verification work.","key":"4","section":"guidance"}
M runtime-provider "Directory transfer receipts account for filtered/changed/skipped files and hash-check every actually transferred destination; explicit include-all is retained and unchanged metadata does not fabricate verification work." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"A completed transfer returns the identical JSON receipt durably persisted at its selected sender and mirror protocol roots; destination escape, unavailable explicit root and invalid batch sources stop before successful receipt/copy.","key":"5","section":"guidance"}
M runtime-provider "A completed transfer returns the identical JSON receipt durably persisted at its selected sender and mirror protocol roots; destination escape, unavailable explicit root and invalid batch sources stop before successful receipt/copy." src:"authored manual" state:verified
-- @record {"chapter":"local-transfer-protocol","data":"Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner.","key":"6","section":"guidance"}
M runtime-provider "Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner." src:"authored manual" state:verified
L runtime-provider.portable-platform v1 -- Portable paths and local setup plans
-- @record {"chapter":"portable-platform","data":{"failure":"A local fixture receipt is treated as a provider, mounted NAS or public runtime success.","recovery":"Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X A local fixture receipt is treated as a provider, mounted NAS or public runtime success. -> Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier.
-- @record {"chapter":"portable-platform","data":"External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.","key":"0","section":"frontier"}
F External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.
-- @record {"chapter":"portable-platform","data":"Explicit workspace and configured environment roots, project name and Windows mirror survive PlatformConfig construction; this projection performs no NAS activity.","key":"0","section":"guidance"}
M runtime-provider "Explicit workspace and configured environment roots, project name and Windows mirror survive PlatformConfig construction; this projection performs no NAS activity." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Path candidates are unique; a configured remote project path includes its corresponding local workspace and configured mirror path.","key":"1","section":"guidance"}
M runtime-provider "Path candidates are unique; a configured remote project path includes its corresponding local workspace and configured mirror path." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Explicit POSIX coercion maps an embedded Windows drive path to its /mnt drive mount and preserves the remaining path, including through the supervisor's pure helper.","key":"2","section":"guidance"}
M runtime-provider "Explicit POSIX coercion maps an embedded Windows drive path to its /mnt drive mount and preserves the remaining path, including through the supervisor's pure helper." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"The pure Go environment merge retains unrelated provider entries, emits exactly one safely quoted current OPENCODE_API_KEY export and rejects an empty credential value.","key":"3","section":"guidance"}
M runtime-provider "The pure Go environment merge retains unrelated provider entries, emits exactly one safely quoted current OPENCODE_API_KEY export and rejects an empty credential value." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"The pure receipt redactor removes the supplied secret and returns at most 8000 characters; proof fixtures use in-memory scratch strings only.","key":"4","section":"guidance"}
M runtime-provider "The pure receipt redactor removes the supplied secret and returns at most 8000 characters; proof fixtures use in-memory scratch strings only." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Repeated flags and comma lists produce exactly the first-seen nonempty usernames once, preserving order.","key":"5","section":"guidance"}
M runtime-provider "Repeated flags and comma lists produce exactly the first-seen nonempty usernames once, preserving order." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Normalized host identities are unique and partition exactly into DNS names and valid IP addresses; a trailing DNS dot does not duplicate a host.","key":"6","section":"guidance"}
M runtime-provider "Normalized host identities are unique and partition exactly into DNS names and valid IP addresses; a trailing DNS dot does not duplicate a host." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"The TLS backend command plan retains its explicit port, public URL and certificate/key paths; verification never launches that command or reads those files.","key":"7","section":"guidance"}
M runtime-provider "The TLS backend command plan retains its explicit port, public URL and certificate/key paths; verification never launches that command or reads those files." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Supported CPU names resolve to packaged Node architecture and the planned HTTPS archive URL preserves version/architecture; unsupported CPU or empty version stops before download.","key":"8","section":"guidance"}
M runtime-provider "Supported CPU names resolve to packaged Node architecture and the planned HTTPS archive URL preserves version/architecture; unsupported CPU or empty version stops before download." src:"authored manual" state:verified
-- @record {"chapter":"portable-platform","data":"Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner.","key":"9","section":"guidance"}
M runtime-provider "Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner." src:"authored manual" state:verified
L runtime-provider.provider-coordination v1 -- PROOFS-d: durable provider scheduling and queue ownership
-- @record {"chapter":"provider-coordination","data":{"failure":"Scheduling receipt is treated as real provider authentication.","recovery":"Retain the explicit lab-input boundary and the credential/backend cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X Scheduling receipt is treated as real provider authentication. -> Retain the explicit lab-input boundary and the credential/backend cases in the coverage frontier.
-- @record {"chapter":"provider-coordination","data":"Windows denied dangling file symlink creation with WinError 1314. Credential-store and actual backend/provider integration cases remain retained.","key":"0","section":"frontier"}
F Windows denied dangling file symlink creation with WinError 1314. Credential-store and actual backend/provider integration cases remain retained.
-- @record {"chapter":"provider-coordination","data":"Durable queue schema, ordered unique provider identities, canonical lifecycle and public flow metadata remain valid on every load; malformed/future state fails closed without overwrite.","key":"0","section":"guidance"}
M runtime-provider "Durable queue schema, ordered unique provider identities, canonical lifecycle and public flow metadata remain valid on every load; malformed/future state fails closed without overwrite." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Successful queue writes reread the exact payload through the existing anchored provider-state directory; no credential file is part of this proof.","key":"1","section":"guidance"}
M runtime-provider "Successful queue writes reread the exact payload through the existing anchored provider-state directory; no credential file is part of this proof." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Queue mutations preserve durable queue/provider operation identities, settle supplied presence observations, expose lost evidence as blocked, and keep cancelled/skipped operations terminal.","key":"2","section":"guidance"}
M runtime-provider "Queue mutations preserve durable queue/provider operation identities, settle supplied presence observations, expose lost evidence as blocked, and keep cancelled/skipped operations terminal." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Only public flow receipt fields persist; sessionless observers preserve the owning session and conflicting sessions cannot overwrite its durable evidence.","key":"3","section":"guidance"}
M runtime-provider "Only public flow receipt fields persist; sessionless observers preserve the owning session and conflicting sessions cannot overwrite its durable evidence." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Public queue views retain lifecycle and policy, hide opaque startup ownership, declare no stored secret material and keep Anthropic on its official provider route.","key":"4","section":"guidance"}
M runtime-provider "Public queue views retain lifecycle and policy, hide opaque startup ownership, declare no stored secret material and keep Anthropic on its official provider route." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Existing workspace locks and canonical bounded durable leases reserve one startup owner; waiting pollers receive no executable action, stale owners cannot publish, and completion leaves the next startup unclaimed until a real poller.","key":"5","section":"guidance"}
M runtime-provider "Existing workspace locks and canonical bounded durable leases reserve one startup owner; waiting pollers receive no executable action, stale owners cannot publish, and completion leaves the next startup unclaimed until a real poller." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Inside the existing SQLite lease transaction, closed routes admit work, open cooldowns deny, and half-open routes reserve exactly one live canary keyed by host/runtime/provider. Direct lease creation rechecks the same admission rule.","key":"6","section":"guidance"}
M runtime-provider "Inside the existing SQLite lease transaction, closed routes admit work, open cooldowns deny, and half-open routes reserve exactly one live canary keyed by host/runtime/provider. Direct lease creation rechecks the same admission rule." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Observed result metadata opens only its route, respects transient thresholds and preserves stronger auth/credit cooldown against late results; successful owned canaries close/reset and failed/inconclusive canaries reopen durably.","key":"7","section":"guidance"}
M runtime-provider "Observed result metadata opens only its route, respects transient thresholds and preserves stronger auth/credit cooldown against late results; successful owned canaries close/reset and failed/inconclusive canaries reopen durably." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Provider result classification keeps route identity and only bounded category evidence, separates auth/credit/rate/overload/transport, and explicit process success wins over authentication words in output.","key":"8","section":"guidance"}
M runtime-provider "Provider result classification keeps route identity and only bounded category evidence, separates auth/credit/rate/overload/transport, and explicit process success wins over authentication words in output." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Manual circuit reset redacts bounded actor/reason evidence and asks for one future half-open canary rather than bypassing observed failure.","key":"9","section":"guidance"}
M runtime-provider "Manual circuit reset redacts bounded actor/reason evidence and asks for one future half-open canary rather than bypassing observed failure." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Provider result publication requires the current active lease, matching job and reporting host; mismatched reporting does not update a provider circuit.","key":"10","section":"guidance"}
M runtime-provider "Provider result publication requires the current active lease, matching job and reporting host; mismatched reporting does not update a provider circuit." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Workers record provider failure before durable job completion and doctor exposes every open/half-open route. Explicit trusted local capability observations/environment keep scratch runs within their owned root; they do not prove provider authentication or permit external workspace mappings.","key":"11","section":"guidance"}
M runtime-provider "Workers record provider failure before durable job completion and doctor exposes every open/half-open route. Explicit trusted local capability observations/environment keep scratch runs within their owned root; they do not prove provider authentication or permit external workspace mappings." src:"authored manual" state:verified
-- @record {"chapter":"provider-coordination","data":"Self-check uses actual scratch JSON, Windows anchored directory I/O, SQLite concurrent leases and a bounded local Python child. Presence callbacks, flow metadata and provider result labels are explicit lab inputs; they do not assert real authentication, provider response, credential access or remote worker success.","key":"12","section":"guidance"}
M runtime-provider "Self-check uses actual scratch JSON, Windows anchored directory I/O, SQLite concurrent leases and a bounded local Python child. Presence callbacks, flow metadata and provider result labels are explicit lab inputs; they do not assert real authentication, provider response, credential access or remote worker success." src:"authored manual" state:verified
L runtime-provider.provider-effects v1 -- Exact provider owner effects
-- @record {"chapter":"provider-effects","data":{"effect":"Create the selected provider session, bound to the exact durable request fingerprint","pre":"Create the selected provider session, bound to the exact durable request fingerprint","returns":{"$cl_type":"t8"},"reversible":false,"schema":"neyvia.session.new","tool":"neyvia.session.new"},"key":"session.new","section":"actions"}
A neyvia.session.new(app:str folder:str prompt:str model?:str permissionMode?:str requestId:str) -> json:"{\"type\":\"object\"}" ! -- Create the selected provider session, bound to the exact durable request fingerprint
F verify-session-new "No authored observer check is bound to neyvia.session.new" -> ask operator blocks:neyvia.session.new
-- @record {"chapter":"provider-effects","data":{"effect":"Persist the selected workspace plugin launch setting and read it back","pre":"Persist the selected workspace plugin launch setting and read it back","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.claude.mods","tool":"neyvia.claude.mods"},"key":"claude.mods","section":"actions"}
A neyvia.claude.mods(enabled?:bool) -> json:"{\"type\":\"object\"}" ! -- Persist the selected workspace plugin launch setting and read it back
F verify-claude-mods "No authored observer check is bound to neyvia.claude.mods" -> ask operator blocks:neyvia.claude.mods
-- @record {"chapter":"provider-effects","data":{"effect":"Copy exact safe reviewed skills and verify bytes, pointer, catalog and disabled activation policy","pre":"Copy exact safe reviewed skills and verify bytes, pointer, catalog and disabled activation policy","returns":{"$cl_type":"t8"},"reversible":false,"schema":"codex.assets.import","tool":"codex.assets.import"},"key":"codex.assets.import","section":"actions"}
A codex.assets.import(codexHome?:str) -> json:"{\"type\":\"object\"}" ! -- Copy exact safe reviewed skills and verify bytes, pointer, catalog and disabled activation policy
F verify-codex-assets-import "No authored observer check is bound to codex.assets.import" -> ask operator blocks:codex.assets.import
-- @record {"chapter":"provider-effects","data":{"goal":"Create the selected provider session, bound to the exact durable request fingerprint","inputs":{"$cl_type":"t10"},"steps":[{"action":"session.new","args":{"app":{"$input":"app"},"folder":{"$input":"folder"},"model":{"$input":"model"},"permissionMode":{"$input":"permissionMode"},"prompt":{"$input":"prompt"},"requestId":{"$input":"requestId"}},"save":"observed"}]},"key":"create-provider-session","section":"procedures"}
P create-provider-session(app:str folder:str prompt:str model:str permissionMode:str requestId:str):observed=neyvia.session.new(app:app folder:folder model:model permissionMode:permissionMode prompt:prompt requestId:requestId) -- Create the selected provider session, bound to the exact durable request fingerprint
V P create-provider-session -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"provider-effects","data":{"goal":"Persist the selected workspace plugin launch setting and read it back","inputs":{"$cl_type":"t11"},"steps":[{"action":"claude.mods","args":{"enabled":{"$input":"enabled"}},"save":"observed"}]},"key":"set-claude-mods","section":"procedures"}
P set-claude-mods(enabled:bool):observed=neyvia.claude.mods(enabled:enabled) -- Persist the selected workspace plugin launch setting and read it back
V P set-claude-mods -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"provider-effects","data":{"goal":"Copy exact safe reviewed skills and verify bytes, pointer, catalog and disabled activation policy","inputs":{"$cl_type":"t12"},"steps":[{"action":"codex.assets.import","args":{"codexHome":{"$input":"codexHome"}},"save":"observed"}]},"key":"import-reviewed-assets","section":"procedures"}
P import-reviewed-assets(codexHome:str):observed=codex.assets.import(codexHome:codexHome) -- Copy exact safe reviewed skills and verify bytes, pointer, catalog and disabled activation policy
V P import-reviewed-assets -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"provider-effects","data":{"failure":"A saved session or import receipt is treated as generated model output","recovery":"Observe actual provider output separately; local peer proves only transport and storage"},"key":"0","section":"pitfalls"}
X A saved session or import receipt is treated as generated model output -> Observe actual provider output separately; local peer proves only transport and storage
-- @record {"chapter":"provider-effects","data":"image.generate requires approved configured Codex subscription and a real saved generated image","key":"0","section":"frontier"}
F image.generate requires approved configured Codex subscription and a real saved generated image
-- @record {"chapter":"provider-effects","data":"scroll.generate requires configured Luna CLI, actual generated cards and validation; no account read admitted here","key":"1","section":"frontier"}
F scroll.generate requires configured Luna CLI, actual generated cards and validation; no account read admitted here
-- @record {"chapter":"provider-effects","data":"codex.plugins.call requires the plugin own effect observer; generic plugin return is insufficient","key":"2","section":"frontier"}
F codex.plugins.call requires the plugin own effect observer; generic plugin return is insufficient
-- @record {"chapter":"provider-effects","data":"Reuse requestId for a retry; a changed prompt under the same requestId is refused before transport.","key":"0","section":"guidance"}
M runtime-provider "Reuse requestId for a retry; a changed prompt under the same requestId is refused before transport." src:"authored manual" state:verified
-- @record {"chapter":"provider-effects","data":"CL imports require explicit codexHome; safe skill files stay disabled until review.","key":"1","section":"guidance"}
M runtime-provider "CL imports require explicit codexHome; safe skill files stay disabled until review." src:"authored manual" state:verified
L runtime-provider.requests-and-routes v1 -- Profiles, provider requests and route plans
-- @record {"chapter":"requests-and-routes","data":{"failure":"A local fixture receipt is treated as a provider, mounted NAS or public runtime success.","recovery":"Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X A local fixture receipt is treated as a provider, mounted NAS or public runtime success. -> Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier.
-- @record {"chapter":"requests-and-routes","data":"External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.","key":"0","section":"frontier"}
F External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.
-- @record {"chapter":"requests-and-routes","data":"Profile selection resolves an explicit existing name first, first matching workspace rule second and registered default last, preserving the selected profile's agent policy.","key":"0","section":"guidance"}
M runtime-provider "Profile selection resolves an explicit existing name first, first matching workspace rule second and registered default last, preserving the selected profile's agent policy." src:"authored manual" state:verified
-- @record {"chapter":"requests-and-routes","data":"Skill tools retain name, description, schema and strictness; enabled code execution retains auto memory/file configuration or selected container identity.","key":"1","section":"guidance"}
M runtime-provider "Skill tools retain name, description, schema and strictness; enabled code execution retains auto memory/file configuration or selected container identity." src:"authored manual" state:verified
-- @record {"chapter":"requests-and-routes","data":"Wire serialization preserves model, user input, tools, storage policy and requested continuation/instructions/tool-choice; unset optional fields are omitted.","key":"2","section":"guidance"}
M runtime-provider "Wire serialization preserves model, user input, tools, storage policy and requested continuation/instructions/tool-choice; unset optional fields are omitted." src:"authored manual" state:verified
-- @record {"chapter":"requests-and-routes","data":"Runtime semantic/date versions compare numeric token tuples; v prefixes do not change version identity.","key":"3","section":"guidance"}
M runtime-provider "Runtime semantic/date versions compare numeric token tuples; v prefixes do not change version identity." src:"authored manual" state:verified
-- @record {"chapter":"requests-and-routes","data":"The four required context/planner/executor/verifier lanes keep their role order and the selected runtime alias normalizes to the owning runtime without launch or route substitution.","key":"4","section":"guidance"}
M runtime-provider "The four required context/planner/executor/verifier lanes keep their role order and the selected runtime alias normalizes to the owning runtime without launch or route substitution." src:"authored manual" state:verified
-- @record {"chapter":"requests-and-routes","data":"Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner.","key":"5","section":"guidance"}
M runtime-provider "Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner." src:"authored manual" state:verified
L runtime-provider.runtime-output v1 -- Runtime outputs, wrappers and replay
-- @record {"chapter":"runtime-output","data":{"failure":"A local fixture receipt is treated as a provider, mounted NAS or public runtime success.","recovery":"Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier."},"key":"0","section":"pitfalls"}
X A local fixture receipt is treated as a provider, mounted NAS or public runtime success. -> Keep the local protocol boundary explicit and retain unsupported lifecycle/authority cases in the coverage frontier.
-- @record {"chapter":"runtime-output","data":"External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.","key":"0","section":"frontier"}
F External/runtime service behavior and uncovered historical assertions remain in config/proofs/d-runtime.json; retained tests are not deleted.
-- @record {"chapter":"runtime-output","data":"Runtime output retains its invocation/runtime origin, exact content and counts; content hashes make repeat handback idempotent while new resumed output remains carryable. Empty output has no invented completion.","key":"0","section":"guidance"}
M runtime-provider "Runtime output retains its invocation/runtime origin, exact content and counts; content hashes make repeat handback idempotent while new resumed output remains carryable. Empty output has no invented completion." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Handed-back transcript messages retain content/text and origin; user/operator messages are authored by You, other messages by their originating runtime.","key":"1","section":"guidance"}
M runtime-provider "Handed-back transcript messages retain content/text and origin; user/operator messages are authored by You, other messages by their originating runtime." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Only supported wrappers with nonempty commands produce specs; exact command, cwd, timeout and sorted environment key names survive without serializing environment values.","key":"2","section":"guidance"}
M runtime-provider "Only supported wrappers with nonempty commands produce specs; exact command, cwd, timeout and sorted environment key names survive without serializing environment values." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Wrapper observations retain their runtime/cwd, observed processes, masked environment status, positive TTL and nonnegative heartbeat age; actual file tails stay bounded.","key":"3","section":"guidance"}
M runtime-provider "Wrapper observations retain their runtime/cwd, observed processes, masked environment status, positive TTL and nonnegative heartbeat age; actual file tails stay bounded." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Phase events retain the wrapper's runtime/cwd/log path and the supplied mission/run/phase/status/message association.","key":"4","section":"guidance"}
M runtime-provider "Phase events retain the wrapper's runtime/cwd/log path and the supplied mission/run/phase/status/message association." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Execution receipts project the exact wrapper command, changed files, bounded observed logs, process tree, masked environment, heartbeat age and TTL.","key":"5","section":"guidance"}
M runtime-provider "Execution receipts project the exact wrapper command, changed files, bounded observed logs, process tree, masked environment, heartbeat age and TTL." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"File-backed replay admits only real dictionary rows, skips missing/malformed inputs, respects the event bound and derives latest status from observed receipt/event rows.","key":"6","section":"guidance"}
M runtime-provider "File-backed replay admits only real dictionary rows, skips missing/malformed inputs, respects the event bound and derives latest status from observed receipt/event rows." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"A lineage timeline consists only of real source JSONL dictionaries, in lineage/source order, tagged with the originating session; missing/malformed rows do not invent events.","key":"7","section":"guidance"}
M runtime-provider "A lineage timeline consists only of real source JSONL dictionaries, in lineage/source order, tagged with the originating session; missing/malformed rows do not invent events." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Public service classes stay lazy until requested, then retain their backwards-compatible public class identity; package import alone does not load the autonomous engine.","key":"8","section":"guidance"}
M runtime-provider "Public service classes stay lazy until requested, then retain their backwards-compatible public class identity; package import alone does not load the autonomous engine." src:"authored manual" state:verified
-- @record {"chapter":"runtime-output","data":"Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner.","key":"9","section":"guidance"}
M runtime-provider "Host entry points listed under CHECKED enforce these contracts for every real Python action; startup uses the registered d-runtime scratch runner." src:"authored manual" state:verified
