CL 1
L scroll-generator v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Scroll generator: notes to source-bound study cards"}},"clVersion":"1.1","id":"scroll-generator","kind":"workflow","schema":"neyvia.manual.v1","schemas":{"neyvia.scroll.concepts":"t1","neyvia.scroll.generate":"t2","neyvia.scroll.import":"t3","neyvia.scroll.job":"t4","neyvia.scroll.pack":"t1","neyvia.scroll.preview":"t5","neyvia.scroll.review":"t6","neyvia.scroll.send":"t1","neyvia.scroll.state":"t7","neyvia.scroll.stats":"t1","neyvia.scroll.validate":"t1"},"tool_metadata":{"neyvia.scroll.concepts":{"mutability_class":"external_action"},"neyvia.scroll.generate":{"mutability_class":"external_action"},"neyvia.scroll.import":{"mutability_class":"artifact_write"},"neyvia.scroll.job":{"mutability_class":"read"},"neyvia.scroll.pack":{"mutability_class":"artifact_write"},"neyvia.scroll.preview":{"mutability_class":"artifact_write"},"neyvia.scroll.review":{"mutability_class":"artifact_write"},"neyvia.scroll.send":{"mutability_class":"artifact_write"},"neyvia.scroll.state":{"mutability_class":"read"},"neyvia.scroll.stats":{"mutability_class":"read"},"neyvia.scroll.validate":{"mutability_class":"read"}},"proofs":{"area":"scroll-export-journey","manifests":["config/proofs/scroll-export-journey.json"]}}
T t1{pack:str#1.. ..}
T t2{pack:str#1.. scope?:json:"{\"type\":\"object\",\"properties\":{\"chapters\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1}},\"concepts\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1}}},\"additionalProperties\":false}" requestId:str#1.. ..}
T t3{paths:[str#1..]#1..20 packId?:str#1.. title?:str#1.. subject?:str#1.. ..}
T t4{requestId:str#1.. ..}
T t5{pack:str#1.. device?:str#1.. ..}
T t6{pack:str#1.. decisions?:[{cardId:str#1.. action:"approve"|"drop"|"edit" card?:json:"{\"type\":\"object\"}"}] chapter?:str#1.. action?:"approve" ..}
T t7{pack?:str#1.. ..}
T t8{pack:str#1..}
T t9{ok:bool packs:json:"{\"type\":\"array\"}" ..}
T t10 json:"{\"type\":\"object\"}"
T t11{paths:[str#1..]#1..20 packId:str#1..}
T t12{pack:str#1.. decisions:[{cardId:str#1.. action:"approve"|"drop"|"edit" card?:json:"{\"type\":\"object\"}"}]}
L scroll-generator.overview v1 -- Scroll generator: notes to source-bound study cards
-- @record {"chapter":"overview","data":{"args":{"pack":{"$input":"pack"}},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"neyvia.scroll.state"},"key":"pack","section":"state"}
S scroll-generator.pack:{ok:bool packs:json:"{\"type\":\"array\"}" ..}=neyvia.scroll.state(pack:pack)
-- @record {"chapter":"overview","data":{"effect":"Run schema/DAG/source/maths/card-mix checks without model calls.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.validate","tool":"neyvia.scroll.validate"},"key":"validate","section":"actions"}
A neyvia.scroll.validate(pack:str#1..) -> json:"{\"type\":\"object\"}" ! -- Run schema/DAG/source/maths/card-mix checks without model calls.
C neyvia.scroll.validate valid:neyvia.scroll.validate(pack:pack) .ok == true
-- @record {"chapter":"overview","data":{"effect":"Read actual generation usage, price-qualified card/hour costs and review approval rate.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.stats","tool":"neyvia.scroll.stats"},"key":"stats","section":"actions"}
A neyvia.scroll.stats(pack:str#1..) -> json:"{\"type\":\"object\"}" -- Read actual generation usage, price-qualified card/hour costs and review approval rate.
F verify-stats "No authored observer check is bound to neyvia.scroll.stats" -> ask operator blocks:neyvia.scroll.stats
-- @record {"chapter":"overview","data":{"effect":"Hash Markdown/text study notes and create a workspace pack draft using zero-token ingest/split/candidate scripts.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.import","tool":"neyvia.scroll.import"},"key":"import","section":"actions"}
A neyvia.scroll.import(paths:[str#1..]#1..20 packId?:str#1.. title?:str#1.. subject?:str#1..) -> json:"{\"type\":\"object\"}" ! -- Hash Markdown/text study notes and create a workspace pack draft using zero-token ingest/split/candidate scripts.
F verify-import "No authored observer check is bound to neyvia.scroll.import" -> ask operator blocks:neyvia.scroll.import
-- @record {"chapter":"overview","data":{"effect":"Confirm concepts through the validated Luna cascade; graph-sanity is the only large graph judgement.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.concepts","tool":"neyvia.scroll.concepts"},"key":"concepts","section":"actions"}
A neyvia.scroll.concepts(pack:str#1..) -> json:"{\"type\":\"object\"}" ! -- Confirm concepts through the validated Luna cascade; graph-sanity is the only large graph judgement.
F verify-concepts "No authored observer check is bound to neyvia.scroll.concepts" -> ask operator blocks:neyvia.scroll.concepts
-- @record {"chapter":"overview","data":{"effect":"Start a durable cards/answer-check job. Reuse requestId for transport retries; models cannot run arbitrary tools.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.generate","tool":"neyvia.scroll.generate"},"key":"generate","section":"actions"}
A neyvia.scroll.generate(pack:str#1.. scope?:json:"{\"type\":\"object\",\"properties\":{\"chapters\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1}},\"concepts\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1}}},\"additionalProperties\":false}" requestId:str#1..) -> json:"{\"type\":\"object\"}" ! -- Start a durable cards/answer-check job. Reuse requestId for transport retries; models cannot run arbitrary tools.
F verify-generate "No authored observer check is bound to neyvia.scroll.generate" -> ask operator blocks:neyvia.scroll.generate
-- @record {"chapter":"overview","data":{"effect":"Observe a persisted job and its last stage, progress and actionable failure.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.job","tool":"neyvia.scroll.job"},"key":"job","section":"actions"}
A neyvia.scroll.job(requestId:str#1..) -> json:"{\"type\":\"object\"}" -- Observe a persisted job and its last stage, progress and actionable failure.
F verify-job "No authored observer check is bound to neyvia.scroll.job" -> ask operator blocks:neyvia.scroll.job
-- @record {"chapter":"overview","data":{"effect":"Approve, drop or edit real draft cards. Flagged answers need an explicit individual decision.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.review","tool":"neyvia.scroll.review"},"key":"review","section":"actions"}
A neyvia.scroll.review(pack:str#1.. decisions?:[{cardId:str#1.. action:"approve"|"drop"|"edit" card?:json:"{\"type\":\"object\"}"}] chapter?:str#1.. action?:"approve") -> json:"{\"type\":\"object\"}" ! -- Approve, drop or edit real draft cards. Flagged answers need an explicit individual decision.
F verify-review "No authored observer check is bound to neyvia.scroll.review" -> ask operator blocks:neyvia.scroll.review
-- @record {"chapter":"overview","data":{"effect":"Validate and zip an entirely reviewed pack and its hashed source texts; pending/flagged cards block export.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.pack","tool":"neyvia.scroll.pack"},"key":"pack","section":"actions"}
A neyvia.scroll.pack(pack:str#1..) -> json:"{\"type\":\"object\"}" ! -- Validate and zip an entirely reviewed pack and its hashed source texts; pending/flagged cards block export.
F verify-pack "No authored observer check is bound to neyvia.scroll.pack" -> ask operator blocks:neyvia.scroll.pack
-- @record {"chapter":"overview","data":{"effect":"Copy the approved generated pack into the real phone prototype and open Mobile Studio on the same state.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.preview","tool":"neyvia.scroll.preview"},"key":"preview","section":"actions"}
A neyvia.scroll.preview(pack:str#1.. device?:str#1..) -> json:"{\"type\":\"object\"}" ! -- Copy the approved generated pack into the real phone prototype and open Mobile Studio on the same state.
F verify-preview "No authored observer check is bound to neyvia.scroll.preview" -> ask operator blocks:neyvia.scroll.preview
-- @record {"chapter":"overview","data":{"effect":"Create a single-download 15-minute capability for this approved archive; requires explicit backend URL.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.send","tool":"neyvia.scroll.send"},"key":"send","section":"actions"}
A neyvia.scroll.send(pack:str#1..) -> json:"{\"type\":\"object\"}" ! -- Create a single-download 15-minute capability for this approved archive; requires explicit backend URL.
F verify-send "No authored observer check is bound to neyvia.scroll.send" -> ask operator blocks:neyvia.scroll.send
-- @record {"chapter":"overview","data":{"effect":"Read the exact pack/graph/review/job state shown to the user.","pre":"Observe the selected workspace pack; approval is required before export","returns":{"$cl_type":"t10"},"reversible":true,"schema":"neyvia.scroll.state","tool":"neyvia.scroll.state"},"key":"state","section":"actions"}
A neyvia.scroll.state(pack?:str#1..) -> json:"{\"type\":\"object\"}" -- Read the exact pack/graph/review/job state shown to the user.
F verify-state "No authored observer check is bound to neyvia.scroll.state" -> ask operator blocks:neyvia.scroll.state
-- @record {"chapter":"overview","data":{"args":{"pack":{"$input":"pack"}},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.scroll.validate"},"key":"valid","section":"checks"}
C neyvia.scroll.validate valid:neyvia.scroll.validate(pack:pack) .ok == true
-- @record {"chapter":"overview","data":{"goal":"Reject invalid cards before review/export","inputs":{"$cl_type":"t8"},"steps":[{"action":"validate","args":{"pack":{"$input":"pack"}},"check":"valid","save":"validation"}]},"key":"validate-pack","section":"procedures"}
P validate-pack(pack:str#1..):validation=neyvia.scroll.validate(pack:pack) C valid -- Reject invalid cards before review/export
V P validate-pack -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Import bounded study notes and verify their hashes in the durable pack","inputs":{"$cl_type":"t11"},"steps":[{"action":"import","args":{"packId":{"$input":"packId"},"paths":{"$input":"paths"}},"save":"result"}]},"key":"import-notes","section":"procedures"}
P import-notes(paths:[str#1..]#1..20 packId:str#1..):result=neyvia.scroll.import(packId:packId paths:paths) -- Import bounded study notes and verify their hashes in the durable pack
V P import-notes -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Apply card decisions and verify each reviewed card in the durable pack","inputs":{"$cl_type":"t12"},"steps":[{"action":"review","args":{"decisions":{"$input":"decisions"},"pack":{"$input":"pack"}},"save":"result"}]},"key":"review-cards","section":"procedures"}
P review-cards(pack:str#1.. decisions:[{cardId:str#1.. action:"approve"|"drop"|"edit" card?:json:"{\"type\":\"object\"}"}]):result=neyvia.scroll.review(decisions:decisions pack:pack) -- Apply card decisions and verify each reviewed card in the durable pack
V P review-cards -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Export a fully reviewed validated archive and verify its bytes","inputs":{"$cl_type":"t8"},"steps":[{"action":"pack","args":{"pack":{"$input":"pack"}},"save":"result"}]},"key":"export-pack","section":"procedures"}
P export-pack(pack:str#1..):result=neyvia.scroll.pack(pack:pack) -- Export a fully reviewed validated archive and verify its bytes
V P export-pack -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Materialize the approved pack in Mobile Studio and verify the generated files","inputs":{"$cl_type":"t8"},"steps":[{"action":"preview","args":{"pack":{"$input":"pack"}},"save":"result"}]},"key":"preview-pack","section":"procedures"}
P preview-pack(pack:str#1..):result=neyvia.scroll.preview(pack:pack) -- Materialize the approved pack in Mobile Studio and verify the generated files
V P preview-pack -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Create a one-download pack capability bound to the exported archive","inputs":{"$cl_type":"t8"},"steps":[{"action":"send","args":{"pack":{"$input":"pack"}},"save":"result"}]},"key":"send-pack","section":"procedures"}
P send-pack(pack:str#1..):result=neyvia.scroll.send(pack:pack) -- Create a one-download pack capability bound to the exported archive
V P send-pack -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"failure":"Model unavailable or same-tier retry exhausted","recovery":"Read job error and generation receipt; restore requested gpt-6-luna route, then resume a new scoped generation request. No substituted models."},"key":"0","section":"pitfalls"}
X Model unavailable or same-tier retry exhausted -> Read job error and generation receipt; restore requested gpt-6-luna route, then resume a new scoped generation request. No substituted models.
-- @record {"chapter":"overview","data":{"failure":"Independent answer disagrees","recovery":"One answer-dispute judgement; unresolved cards stay flagged until review."},"key":"1","section":"pitfalls"}
X Independent answer disagrees -> One answer-dispute judgement; unresolved cards stay flagged until review.
-- @record {"chapter":"overview","data":{"failure":"Card teaches what it tests","recovery":"Separate the teach card and recall card; prerequisites must already have teaching cards."},"key":"2","section":"pitfalls"}
X Card teaches what it tests -> Separate the teach card and recall card; prerequisites must already have teaching cards.
-- @record {"chapter":"overview","data":{"failure":"Unsupported answer or wrong MCQ","recovery":"Use the hashed source span, exact correct count and mistake reasons; never invent supporting notes."},"key":"3","section":"pitfalls"}
X Unsupported answer or wrong MCQ -> Use the hashed source span, exact correct count and mistake reasons; never invent supporting notes.
-- @record {"chapter":"overview","data":{"failure":"Generated variation is passed off as a course example","recovery":"Only course_example copies an exact quote and span from the imported note; adaptations identify generatedAdaptation and variantOf."},"key":"4","section":"pitfalls"}
X Generated variation is passed off as a course example -> Only course_example copies an exact quote and span from the imported note; adaptations identify generatedAdaptation and variantOf.
-- @record {"chapter":"overview","data":{"failure":"A teaching card is flicked past or a question is on an untaught part","recovery":"Exposure is persisted only after completed reading or worked steps; tests require taught parts, eight cards lag, and changed wording five to ten cards after a miss."},"key":"5","section":"pitfalls"}
X A teaching card is flicked past or a question is on an untaught part -> Exposure is persisted only after completed reading or worked steps; tests require taught parts, eight cards lag, and changed wording five to ten cards after a miss.
-- @record {"chapter":"overview","data":"Markdown/text import works. PDF/OCR extraction is not attached.","key":"0","section":"frontier"}
F Markdown/text import works. PDF/OCR extraction is not attached.
-- @record {"chapter":"overview","data":"Formula arithmetic comparison uses installed SymPy; unavailable symbolic checking is reported through a small independent solution.","key":"1","section":"frontier"}
F Formula arithmetic comparison uses installed SymPy; unavailable symbolic checking is reported through a small independent solution.
-- @record {"chapter":"overview","data":"Source numbered worked examples can be extracted; every generated procedure example is a named big judgement.","key":"2","section":"frontier"}
F Source numbered worked examples can be extracted; every generated procedure example is a named big judgement.
-- @record {"chapter":"overview","data":"Validated packs can compile after three real grounded manual runs. Compiled validation remains input/manual/provenance-bound and rechecks current cards.","key":"3","section":"frontier"}
F Validated packs can compile after three real grounded manual runs. Compiled validation remains input/manual/provenance-bound and rechecks current cards.
-- @record {"chapter":"overview","data":"Validated packs can compile after three real grounded manual runs. Compiled validation remains input/manual/provenance-bound and rechecks current cards.","key":"4","section":"frontier"}
F Validated packs can compile after three real grounded manual runs. Compiled validation remains input/manual/provenance-bound and rechecks current cards.
-- @record {"chapter":"overview","data":"Maths/physics default to paul-seven-part.v1: FORMULA, WHEN?, WHAT DO I WRITE?, PATTERN, COURSE EXAMPLE, YOUR EXERCISE, VARIATIONS/TRAPS per actionable concept. The CL source is authoritative.","key":"5","section":"frontier"}
F Maths/physics default to paul-seven-part.v1: FORMULA, WHEN?, WHAT DO I WRITE?, PATTERN, COURSE EXAMPLE, YOUR EXERCISE, VARIATIONS/TRAPS per actionable concept. The CL source is authoritative.
-- @record {"chapter":"overview","data":"scroll.validate executes the seven-part completeness, exact quoted course span, changed exercise reference and independently checked solution gates in addition to schema/DAG/source/maths/mix.","key":"6","section":"frontier"}
F scroll.validate executes the seven-part completeness, exact quoted course span, changed exercise reference and independently checked solution gates in addition to schema/DAG/source/maths/mix.
-- @record {"chapter":"overview","data":"Pattern cards teach If I see X -> try Y; pattern_drill asks recognition after the pattern is taught. Your exercises and generated variants require all supporting teaching parts and an eight-card lag.","key":"7","section":"frontier"}
F Pattern cards teach If I see X -> try Y; pattern_drill asks recognition after the pattern is taught. Your exercises and generated variants require all supporting teaching parts and an eight-card lag.
-- @record {"chapter":"overview","data":"CL pack actions require fresh source, review, validation and artifact checks; model generation still depends on the configured Luna runtime.","key":"8","section":"frontier"}
F CL pack actions require fresh source, review, validation and artifact checks; model generation still depends on the configured Luna runtime.
-- @record {"chapter":"overview","data":"R2: >=50 percent graded cards are recall (flashcard/cloze/why/order/spot/faded worked); truefalse <=20 percent. No reward cards in packs.","key":"0","section":"guidance"}
M scroll-generator "R2: >=50 percent graded cards are recall (flashcard/cloze/why/order/spot/faded worked); truefalse <=20 percent. No reward cards in packs." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Fact <=60 words; explainer <=120; reading <=40 seconds. Non-recap cards have source doc/span and stage/tier/run provenance.","key":"1","section":"guidance"}
M scroll-generator "Fact <=60 words; explainer <=120; reading <=40 seconds. Non-recap cards have source doc/span and stage/tier/run provenance." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Every prerequisite/tested concept has a teaching card. A graded card never teaches its tested concept.","key":"2","section":"guidance"}
M scroll-generator "Every prerequisite/tested concept has a teaching card. A graded card never teaches its tested concept." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Models: gpt-6-luna through T14 for wording/concepts/re-solve; gpt-6.1-sol only graph-sanity, worked-example, answer-dispute.","key":"3","section":"guidance"}
M scroll-generator "Models: gpt-6-luna through T14 for wording/concepts/re-solve; gpt-6.1-sol only graph-sanity, worked-example, answer-dispute." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"R14: worked all steps -> fade1 last step blank -> fade2 later half blank -> order/full problem. Keep the original answers.","key":"4","section":"guidance"}
M scroll-generator "R14: worked all steps -> fade1 last step blank -> fade2 later half blank -> order/full problem. Keep the original answers." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Mistake catalogue: forgetting the inner derivative; multiplying derivatives in product rule; dropping a constant; sign inversion; confusing a converse; moving a step before its prerequisite.","key":"5","section":"guidance"}
M scroll-generator "Mistake catalogue: forgetting the inner derivative; multiplying derivatives in product rule; dropping a constant; sign inversion; confusing a converse; moving a step before its prerequisite." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"fact examples: 'Slope is rise over run.'; 'A derivative is the slope of the tangent.'","key":"6","section":"guidance"}
M scroll-generator "fact examples: 'Slope is rise over run.'; 'A derivative is the slope of the tangent.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"explainer examples: 'Secant slopes tend to the tangent slope as the interval shrinks.'; 'The product rule differentiates one factor at a time and adds both changes.'","key":"7","section":"guidance"}
M scroll-generator "explainer examples: 'Secant slopes tend to the tangent slope as the interval shrinks.'; 'The product rule differentiates one factor at a time and adds both changes.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"worked examples: 'Differentiate x^3: exponent 3 comes down, lower exponent to 2, obtain 3x^2.'; 'For x^2*exp(x), find 2x and exp(x), then add 2x*exp(x)+x^2*exp(x). Why: each factor changes.'","key":"8","section":"guidance"}
M scroll-generator "worked examples: 'Differentiate x^3: exponent 3 comes down, lower exponent to 2, obtain 3x^2.'; 'For x^2*exp(x), find 2x and exp(x), then add 2x*exp(x)+x^2*exp(x). Why: each factor changes.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"flashcard examples: front 'What is rise over run called?' back 'Slope.'; front 'Differentiate x^3.' back '3x^2.'","key":"9","section":"guidance"}
M scroll-generator "flashcard examples: front 'What is rise over run called?' back 'Slope.'; front 'Differentiate x^3.' back '3x^2.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"cloze examples: before 'Slope is ', blank 'rise over run', after '.'; before 'd/dx x^3 = ', blank '3x^2', after '.'","key":"10","section":"guidance"}
M scroll-generator "cloze examples: before 'Slope is ', blank 'rise over run', after '.'; before 'd/dx x^3 = ', blank '3x^2', after '.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"why examples: front 'Why multiply by the inner derivative?' back 'It accounts for the inner function changing.'; front 'Why does the product rule have two terms?' back 'Either factor can change.'","key":"11","section":"guidance"}
M scroll-generator "why examples: front 'Why multiply by the inner derivative?' back 'It accounts for the inner function changing.'; front 'Why does the product rule have two terms?' back 'Either factor can change.'" src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"truefalse examples: 'The derivative of x^3 is 3x^2.' true with power-rule reason; 'The derivative of f*g is fprime*gprime.' false with both correct terms.","key":"12","section":"guidance"}
M scroll-generator "truefalse examples: 'The derivative of x^3 is 3x^2.' true with power-rule reason; 'The derivative of f*g is fprime*gprime.' false with both correct terms." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"mcq examples: differentiate x^3 -> 3x^2 correct, x^2 wrong missing coefficient, 3x^3 wrong unchanged exponent; differentiate (3x+1)^2 -> 6(3x+1) correct, 2(3x+1) wrong missing inner derivative, 6x wrong lost inner expression.","key":"13","section":"guidance"}
M scroll-generator "mcq examples: differentiate x^3 -> 3x^2 correct, x^2 wrong missing coefficient, 3x^3 wrong unchanged exponent; differentiate (3x+1)^2 -> 6(3x+1) correct, 2(3x+1) wrong missing inner derivative, 6x wrong lost inner expression." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"order examples: power rule -> identify exponent, multiply coefficient, lower exponent; chain rule -> identify inner function, differentiate outer, multiply inner derivative.","key":"14","section":"guidance"}
M scroll-generator "order examples: power rule -> identify exponent, multiply coefficient, lower exponent; chain rule -> identify inner function, differentiate outer, multiply inner derivative." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"spot examples: lines ['n=3','derivative=x^2'], wrong 1, fix 'derivative=3x^2'; lines ['u=3x+1','derivative=2u'], wrong 1, fix 'derivative=6u'.","key":"15","section":"guidance"}
M scroll-generator "spot examples: lines ['n=3','derivative=x^2'], wrong 1, fix 'derivative=3x^2'; lines ['u=3x+1','derivative=2u'], wrong 1, fix 'derivative=6u'." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"recap examples: 'Slope: rise/run. Derivative: tangent slope.'; 'Product: fprime*g+f*gprime. Chain: outer derivative times inner derivative.'","key":"16","section":"guidance"}
M scroll-generator "recap examples: 'Slope: rise/run. Derivative: tangent slope.'; 'Product: fprime*g+f*gprime. Chain: outer derivative times inner derivative.'" src:"authored manual" state:verified
-- @proof {"checkedAt":["grant_agent.proofs_scroll_export_journey.self_check","grant_agent.neyvia_scroll.export","grant_agent.neyvia_scroll.download","grant_agent.scroll_pack.write_scrollpack","grant_agent.scroll_pack.read_scrollpack"],"claim":"A reviewed Unicode pack exports with exact source/card semantics and sends a one-download QR SVG capability; the first route payload equals the archive and repeat/expired requests refuse with 410. The check asserts SVG path geometry only; it does not decode a QR or claim a phone/UI consumer.","id":"p22.scroll.reviewed-export-singleuse-outcome","impact":["Scroll Study reviewed export","one-use phone delivery","Unicode archive roundtrip"],"phase":"post"}
