CL 1
L settings v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Persistent settings, privacy and owner proposals"},"proofs-e-frontend":{"title":"PROOFS-e frontend action contracts"},"proofs-e-models":{"title":"PROOFS-e: production model contracts"},"proofs-e-shell":{"title":"PROOFS-e shell state and action contracts"}},"clVersion":"1.1","id":"settings","kind":"environment","proofs":{"area":"settings","manifests":["config/proofs/proofs-e-frontend.json","config/proofs/proofs-e-models.json"],"startup":{"procedures":["preferences.motion-accessibility"],"runner":"scripts/proofs-e-frontend.mjs","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.settings.get":"t1","neyvia.settings.network_check":"t1","neyvia.settings.propose":"live_schema_13","neyvia.settings.setup":"t1","neyvia.view.state":"t3","proofs-e-models.status":"t1","proofs-e-shell.status":"t1"},"tool_metadata":{"neyvia.settings.get":{"mutability_class":"read"},"neyvia.settings.network_check":{"mutability_class":"read"},"neyvia.settings.propose":{"mutability_class":"none"},"neyvia.settings.setup":{"mutability_class":"none"},"neyvia.verify.status":{"mutability_class":"none"}}}
T live_schema_13 {patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\",\"terminal\",\"paper\",\"ember\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}},\"sun\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"follow\":{\"type\":\"boolean\"},\"intoNight\":{\"type\":\"boolean\"},\"sunrise\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"},\"sunset\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"}}}}}},\"additionalProperties\":false}" expectedRevision:0.. ..}
-- @proof {"checkedAt":["neyvia_settings.update -> proofs_settings.check_revision/check_committed","proofs_settings.self_check"],"claim":"Only the current integer expectedRevision may write; a successful canonical update persists exactly one revision increment.","id":"settings.revision-cas","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"pre"}
-- @proof {"checkedAt":["neyvia_settings.update -> proofs_settings.snapshot/check_rejection","proofs_settings.self_check"],"claim":"Rejected invalid control patches change no canonical state and emit no events.","id":"settings.invalid-preserves","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_settings.update -> proofs_settings.check_committed","proofs_settings.self_check"],"claim":"Within the same transaction, canonical cleanup/night resources/density/theme storage equals the normalized Settings value.","id":"settings.canonical-mirrors","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"post"}
-- @proof {"checkedAt":["neyvia_settings.update -> proofs_settings.check_committed","proofs_settings.self_check"],"claim":"Every update emits durable identical receipt events; a nightShift patch emits exactly one normalized policy update.","id":"settings.night-policy-event","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"post"}
-- @proof {"checkedAt":["neyvia_view_tools.call -> neyvia_settings.update -> proofs_settings.check_committed","proofs_settings.self_check"],"claim":"Legacy theme selection updates the same canonical preference and mirror storage.","id":"settings.legacy-theme","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"invariant"}
-- @proof {"checkedAt":["neyvia_view_tools.call -> proofs_settings.check_view","proofs_settings.self_check"],"claim":"Ambient and transparency controls persist their exact value before returning success.","id":"settings.view-durable","impact":["canonical Settings","view preferences","Night Shift resource admission"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxRuntimeModel.js:mergeRuntimes -> checkedProofsEModel"],"claim":"Catalog aliases join live rows once; readiness/capabilities/auth/model/owner policy are observed from their authoritative source","id":"runtime.mergeRuntimes","impact":["runtime frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/next/nxRuntimeModel.js:runtimeSummary -> checkedProofsEModel"],"claim":"Ready and installed counts come from rendered runtime rows without inventing detection","id":"runtime.runtimeSummary","impact":["runtime frontend model consumers"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/neyviaShellPreferences.js:normalizeNeyviaShellPreferences -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.normalize","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.normalize","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.normalize"],"claim":"Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency.","id":"preferences.normalize","impact":["neyviaShellPreferences"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/neyviaMotion.js:neyviaMotionCssVariables -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.motion","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.motion","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.preferences.motion"],"claim":"Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency.","id":"preferences.motion","impact":["neyviaMotion"],"phase":"post"}
T t1{..}
T t2{patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}}}}},\"additionalProperties\":false}" expectedRevision:0.. ..}
T t3 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t4{}
T t5{revision:int settings:json:"{\"type\":\"object\"}" network:json:"{\"type\":\"object\"}" ..}
T t6{revision:int settings:json:"{\"type\":\"object\"}" network:json:"{\"type\":\"object\"}" setup:json:"{\"type\":\"object\"}" ..}
T t7 json:"{\"type\":\"object\"}"
T t8{revision:int ..}
T t9{ok:bool setup:json:"{\"type\":\"object\"}" ..}
T t10{patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}}}}},\"additionalProperties\":false}" expectedRevision:0..}
T t11{ok:bool ..}
T t12 json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}"
L settings.overview v1 -- Persistent settings, privacy and owner proposals
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t4"},"shape":{"$cl_type":"t5"},"tool":"neyvia.settings.get"},"key":"preferences","section":"state"}
S settings.preferences:{revision:int settings:json:"{\"type\":\"object\"}" network:json:"{\"type\":\"object\"}" ..}=neyvia.settings.get()
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t4"},"shape":{"$cl_type":"t6"},"tool":"neyvia.settings.get"},"key":"current","section":"state"}
S settings.current:{revision:int settings:json:"{\"type\":\"object\"}" network:json:"{\"type\":\"object\"}" setup:json:"{\"type\":\"object\"}" ..}=neyvia.settings.get()
-- @record {"chapter":"overview","data":{"effect":"Read persisted preferences and network enforcement","pre":"Signed-in local workspace","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.settings.get","tool":"neyvia.settings.get"},"key":"get","section":"actions"}
A neyvia.settings.get() -> json:"{\"type\":\"object\"}" -- Read persisted preferences and network enforcement
C neyvia.settings.get enforced:neyvia.settings.get() .network.enforced == true
C neyvia.settings.get local_only:neyvia.settings.get() .network.localOnly == true
-- @record {"chapter":"overview","data":{"effect":"Queue an exact owner approval; no preference changes yet","pre":"Use the observed revision; owner decides each proposal","returns":{"type":"object"},"reversible":true,"schema":"neyvia.settings.propose","tool":"neyvia.settings.propose"},"key":"propose","section":"actions"}
A neyvia.settings.propose(patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\",\"terminal\",\"paper\",\"ember\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}},\"sun\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"follow\":{\"type\":\"boolean\"},\"intoNight\":{\"type\":\"boolean\"},\"sunrise\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"},\"sunset\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"}}}}}},\"additionalProperties\":false}" expectedRevision:0..) -> json:"{\"type\":\"object\"}" -- Queue an exact owner approval; no preference changes yet
F verify-propose "No authored observer check is bound to neyvia.settings.propose" -> ask operator blocks:neyvia.settings.propose
-- @record {"chapter":"overview","data":{"effect":"Emit setup.open resume=true without deleting installed state","pre":"Owner requests setup re-entry","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.settings.setup","tool":"neyvia.settings.setup"},"key":"setup","section":"actions"}
A neyvia.settings.setup() -> json:"{\"type\":\"object\"}" -- Emit setup.open resume=true without deleting installed state
F verify-setup "No authored observer check is bound to neyvia.settings.setup" -> ask operator blocks:neyvia.settings.setup
-- @record {"chapter":"overview","data":{"effect":"Attempt nine forbidden operations and report actual policy refusals","pre":"Local-only must already be enabled","returns":{"$cl_type":"t7"},"reversible":true,"schema":"neyvia.settings.network_check","tool":"neyvia.settings.network_check"},"key":"network_check","section":"actions"}
A neyvia.settings.network_check() -> json:"{\"type\":\"object\"}" -- Attempt nine forbidden operations and report actual policy refusals
F verify-network_check "No authored observer check is bound to neyvia.settings.network_check" -> ask operator blocks:neyvia.settings.network_check
-- @record {"chapter":"overview","data":{"effect":"Observe canonical settings revision, policy and setup state","pre":"Workspace state root is available","returns":{"$cl_type":"t8"},"reversible":true,"schema":"neyvia.settings.get","tool":"neyvia.settings.get"},"key":"settings.get","section":"actions"}
A neyvia.settings.get() -> {revision:int ..} -- Observe canonical settings revision, policy and setup state
F verify-settings-get "No authored observer check is bound to neyvia.settings.get" -> ask operator blocks:neyvia.settings.get
-- @record {"chapter":"overview","data":{"effect":"Persist setup.requestedAt and emit setup.open without erasing installation","pre":"Workspace state root is available","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.settings.setup","tool":"neyvia.settings.setup"},"key":"settings.setup","section":"actions"}
A neyvia.settings.setup() -> {ok:bool setup:json:"{\"type\":\"object\"}" ..} ! -- Persist setup.requestedAt and emit setup.open without erasing installation
C neyvia.settings.setup setup-requested:matches(neyvia.view.state() .state {properties:{dom:{properties:{setup:{properties:{mounted:{const:true}} required:["mounted"] type:"object"}} required:["setup"] type:"object"} fresh:{const:true}} required:["fresh" "dom"] type:"object"})
-- @record {"chapter":"overview","data":{"effect":"Save an exact patch approval request; repeat approved proposal returns its durable receipt","pre":"Known valid patch and current expectedRevision; owner approval remains required","returns":{"type":"object"},"reversible":true,"schema":"neyvia.settings.propose","tool":"neyvia.settings.propose"},"key":"settings.propose","section":"actions"}
A neyvia.settings.propose(patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\",\"terminal\",\"paper\",\"ember\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}},\"sun\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"follow\":{\"type\":\"boolean\"},\"intoNight\":{\"type\":\"boolean\"},\"sunrise\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"},\"sunset\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"}}}}}},\"additionalProperties\":false}" expectedRevision:0..) -> json:"{\"type\":\"object\"}" ! -- Save an exact patch approval request; repeat approved proposal returns its durable receipt
F verify-settings-propose "No authored observer check is bound to neyvia.settings.propose" -> ask operator blocks:neyvia.settings.propose
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"network.enforced","value":true},"tool":"neyvia.settings.get"},"key":"enforced","section":"checks"}
C neyvia.settings.get enforced:neyvia.settings.get() .network.enforced == true
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"eq","path":"network.localOnly","value":true},"tool":"neyvia.settings.get"},"key":"local_only","section":"checks"}
C neyvia.settings.get local_only:neyvia.settings.get() .network.localOnly == true
-- @record {"chapter":"overview","data":{"args":{},"expect":{"op":"schema","path":"state","schema":{"properties":{"dom":{"properties":{"setup":{"properties":{"mounted":{"const":true}},"required":["mounted"],"type":"object"}},"required":["setup"],"type":"object"},"fresh":{"const":true}},"required":["fresh","dom"],"type":"object"}},"tool":"neyvia.view.state"},"key":"setup-requested","section":"checks"}
C neyvia.view.state setup-requested:matches(neyvia.view.state() .state {properties:{dom:{properties:{setup:{properties:{mounted:{const:true}} required:["mounted"] type:"object"}} required:["setup"] type:"object"} fresh:{const:true}} required:["fresh" "dom"] type:"object"})
-- @record {"chapter":"overview","data":{"goal":"Read canonical settings with installed enforcement","inputs":{"$cl_type":"t4"},"steps":[{"action":"get","args":{},"check":"enforced","save":"preferences"}]},"key":"read-preferences","section":"procedures"}
P read-preferences():preferences=neyvia.settings.get() C enforced -- Read canonical settings with installed enforcement
V P read-preferences -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify actual denied TCP UDP DNS HTTP HTTPS async and child operations while local-only is enabled","inputs":{"$cl_type":"t4"},"steps":[{"action":"get","args":{},"check":"local_only","save":"preferences"},{"action":"network_check","args":{},"save":"proof"}]},"key":"check-local-only","section":"procedures"}
P check-local-only():preferences=neyvia.settings.get() C local_only; proof=neyvia.settings.network_check() -- Verify actual denied TCP UDP DNS HTTP HTTPS async and child operations while local-only is enabled
V P check-local-only -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Queue an owner-reviewed settings change","inputs":{"type":"object","properties":{"patch":{"type":"object","properties":{"density":{"type":"string","enum":["calm","workshop","grove"]},"theme":{"type":"string","enum":["forest","morning","sunset","night-green","terminal","paper","ember"]},"initiative":{"type":"string","enum":["suggest","act-and-tell","silent"]},"projectInitiative":{"type":"object","additionalProperties":{"type":"string","enum":["suggest","act-and-tell","silent"]}},"localOnly":{"type":"boolean"},"cleanup":{"type":"object"},"nightShift":{"type":"object"},"toolAutoUpdate":{"type":"string","enum":["ask","off","allow"]},"look":{"type":"object","additionalProperties":false,"properties":{"font":{"type":"string","enum":["neyvia","windows","inter","geist","editorial"]},"textSize":{"type":"string","enum":["s","m","l"]},"background":{"type":"object","additionalProperties":false,"properties":{"kind":{"type":"string","enum":["theme","preset","solid","image"]},"preset":{"type":"string","maxLength":40},"color":{"type":"string","pattern":"^(#[0-9a-f]{6})?$"},"image":{"type":"string","maxLength":40},"dim":{"type":"integer","minimum":0,"maximum":90},"blur":{"type":"integer","minimum":0,"maximum":40}}},"sun":{"type":"object","additionalProperties":false,"properties":{"follow":{"type":"boolean"},"intoNight":{"type":"boolean"},"sunrise":{"type":"string","pattern":"^([01]\\d|2[0-3]):[0-5]\\d$"},"sunset":{"type":"string","pattern":"^([01]\\d|2[0-3]):[0-5]\\d$"}}}}}},"additionalProperties":false},"expectedRevision":{"type":"integer","minimum":0}},"required":["patch","expectedRevision"],"additionalProperties":false},"steps":[{"action":"propose","args":{"expectedRevision":{"$input":"expectedRevision"},"patch":{"$input":"patch"}},"save":"proposal"}]},"key":"propose-change","section":"procedures"}
P propose-change(patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\",\"terminal\",\"paper\",\"ember\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}},\"sun\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"follow\":{\"type\":\"boolean\"},\"intoNight\":{\"type\":\"boolean\"},\"sunrise\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"},\"sunset\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"}}}}}},\"additionalProperties\":false}" expectedRevision:0..): proposal=neyvia.settings.propose(expectedRevision:expectedRevision patch:patch) -- Queue an owner-reviewed settings change
V P propose-change -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Open existing setup with installed state retained","inputs":{"$cl_type":"t4"},"steps":[{"action":"setup","args":{},"save":"setup"}]},"key":"re-enter-setup","section":"procedures"}
P re-enter-setup():setup=neyvia.settings.setup() -- Open existing setup with installed state retained
V P re-enter-setup -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Request setup and observe its durable request timestamp","inputs":{"$cl_type":"t4"},"steps":[{"action":"settings.setup","args":{},"check":"setup-requested","save":"requested"}]},"key":"reenter-setup","section":"procedures"}
P reenter-setup():requested=neyvia.settings.setup() C setup-requested -- Request setup and observe its durable request timestamp
V P reenter-setup -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"type":"object","properties":{"patch":{"type":"object","properties":{"density":{"type":"string","enum":["calm","workshop","grove"]},"theme":{"type":"string","enum":["forest","morning","sunset","night-green","terminal","paper","ember"]},"initiative":{"type":"string","enum":["suggest","act-and-tell","silent"]},"projectInitiative":{"type":"object","additionalProperties":{"type":"string","enum":["suggest","act-and-tell","silent"]}},"localOnly":{"type":"boolean"},"cleanup":{"type":"object"},"nightShift":{"type":"object"},"toolAutoUpdate":{"type":"string","enum":["ask","off","allow"]},"look":{"type":"object","additionalProperties":false,"properties":{"font":{"type":"string","enum":["neyvia","windows","inter","geist","editorial"]},"textSize":{"type":"string","enum":["s","m","l"]},"background":{"type":"object","additionalProperties":false,"properties":{"kind":{"type":"string","enum":["theme","preset","solid","image"]},"preset":{"type":"string","maxLength":40},"color":{"type":"string","pattern":"^(#[0-9a-f]{6})?$"},"image":{"type":"string","maxLength":40},"dim":{"type":"integer","minimum":0,"maximum":90},"blur":{"type":"integer","minimum":0,"maximum":40}}},"sun":{"type":"object","additionalProperties":false,"properties":{"follow":{"type":"boolean"},"intoNight":{"type":"boolean"},"sunrise":{"type":"string","pattern":"^([01]\\d|2[0-3]):[0-5]\\d$"},"sunset":{"type":"string","pattern":"^([01]\\d|2[0-3]):[0-5]\\d$"}}}}}},"additionalProperties":false},"expectedRevision":{"type":"integer","minimum":0}},"required":["patch","expectedRevision"]},"steps":[{"action":"propose","args":{"expectedRevision":{"$input":"expectedRevision"},"patch":{"$input":"patch"}},"save":"effect"}]},"key":"verify-effect-propose","section":"procedures"}
P verify-effect-propose(patch:json:"{\"type\":\"object\",\"properties\":{\"density\":{\"type\":\"string\",\"enum\":[\"calm\",\"workshop\",\"grove\"]},\"theme\":{\"type\":\"string\",\"enum\":[\"forest\",\"morning\",\"sunset\",\"night-green\",\"terminal\",\"paper\",\"ember\"]},\"initiative\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]},\"projectInitiative\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\",\"enum\":[\"suggest\",\"act-and-tell\",\"silent\"]}},\"localOnly\":{\"type\":\"boolean\"},\"cleanup\":{\"type\":\"object\"},\"nightShift\":{\"type\":\"object\"},\"toolAutoUpdate\":{\"type\":\"string\",\"enum\":[\"ask\",\"off\",\"allow\"]},\"look\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"font\":{\"type\":\"string\",\"enum\":[\"neyvia\",\"windows\",\"inter\",\"geist\",\"editorial\"]},\"textSize\":{\"type\":\"string\",\"enum\":[\"s\",\"m\",\"l\"]},\"background\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"theme\",\"preset\",\"solid\",\"image\"]},\"preset\":{\"type\":\"string\",\"maxLength\":40},\"color\":{\"type\":\"string\",\"pattern\":\"^(#[0-9a-f]{6})?$\"},\"image\":{\"type\":\"string\",\"maxLength\":40},\"dim\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":90},\"blur\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":40}}},\"sun\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"follow\":{\"type\":\"boolean\"},\"intoNight\":{\"type\":\"boolean\"},\"sunrise\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"},\"sunset\":{\"type\":\"string\",\"pattern\":\"^([01]\\\\d|2[0-3]):[0-5]\\\\d$\"}}}}}},\"additionalProperties\":false}" expectedRevision:0..): effect=neyvia.settings.propose(expectedRevision:expectedRevision patch:patch) -- Verify the actual effect through fresh owning observers
V P verify-effect-propose -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Only the signed-in PC owner can apply the proposal through the approval UI; never self-approve or bypass the saved revision.","options":["approve","decline"],"question":"Should this exact proposal change the workspace settings?"},"key":"owner-change","section":"judge"}
J owner-change approve|decline:"Should this exact proposal change the workspace settings?" -- Only the signed-in PC owner can apply the proposal through the approval UI; never self-approve or bypass the saved revision.
V J owner-change -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Settings changed since observation","recovery":"Read settings.get again and review a fresh proposal; stale revisions never overwrite newer state."},"key":"0","section":"pitfalls"}
X Settings changed since observation -> Read settings.get again and review a fresh proposal; stale revisions never overwrite newer state.
-- @record {"chapter":"overview","data":{"failure":"Local-only activation reports active children","recovery":"Finish or stop only owned CLI/MCP jobs, then retry. Unknown children are refused; the OS System32 console host is not a job."},"key":"1","section":"pitfalls"}
X Local-only activation reports active children -> Finish or stop only owned CLI/MCP jobs, then retry. Unknown children are refused; the OS System32 console host is not a job.
-- @record {"chapter":"overview","data":{"failure":"External operation is blocked","recovery":"Use literal loopback services or ask the owner to disable local-only. Never silently substitute a provider."},"key":"2","section":"pitfalls"}
X External operation is blocked -> Use literal loopback services or ask the owner to disable local-only. Never silently substitute a provider.
-- @record {"chapter":"overview","data":"Rendered Settings/setup controls require Claude UI proof.","key":"0","section":"frontier"}
F Rendered Settings/setup controls require Claude UI proof.
-- @record {"chapter":"overview","data":"T10 owns aggregate night budgets and quiet GPU hours; this source uses the current live resource policy.","key":"1","section":"frontier"}
F T10 owns aggregate night budgets and quiet GPU hours; this source uses the current live resource policy.
-- @record {"chapter":"overview","data":"Application egress enforcement does not confine hostile native code or unrelated PC applications.","key":"2","section":"frontier"}
F Application egress enforcement does not confine hostile native code or unrelated PC applications.
-- @record {"chapter":"overview","data":"Density calm/workshop/grove; theme forest/morning/sunset/night-green maps to existing dark/light/sunset/night bus values.","key":"0","section":"guidance"}
M settings "Density calm/workshop/grove; theme forest/morning/sunset/night-green maps to existing dark/light/sunset/night bus values." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Suggest queues housekeeping, act-and-tell archives reversibly with notification, silent archives reversibly without toast; per-project overrides take precedence.","key":"1","section":"guidance"}
M settings "Suggest queues housekeeping, act-and-tell archives reversibly with notification, silent archives reversibly without toast; per-project overrides take precedence." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"The durable Settings revision, cleanupPolicy and nightshift.resources commit together.","key":"2","section":"guidance"}
M settings "The durable Settings revision, cleanupPolicy and nightshift.resources commit together." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Setup summaries retain recent action status without nesting prior results. Full action receipts remain available for detailed inspection.","key":"3","section":"guidance"}
M settings "Setup summaries retain recent action status without nesting prior results. Full action receipts remain available for detailed inspection." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Settings Prompts opens the existing system prompt editor through get_agent_prompt_library_command; Save role/override uses save_agent_prompt_library_command with expectedRevision. Selected .txt/.md files stay editable before saving. Native import_agent_prompt_file_command errors expose Choose a file through the browser file input; this path does not prove the physical native dialog.","key":"4","section":"guidance"}
M settings "Settings Prompts opens the existing system prompt editor through get_agent_prompt_library_command; Save role/override uses save_agent_prompt_library_command with expectedRevision. Selected .txt/.md files stay editable before saving. Native import_agent_prompt_file_command errors expose Choose a file through the browser file input; this path does not prove the physical native dialog." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Radio groups use one selected Tab stop; arrows select with wraparound, Home selects the first choice and End the last.","key":"5","section":"guidance"}
M settings "Radio groups use one selected Tab stop; arrows select with wraparound, Home selects the first choice and End the last." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"toolAutoUpdate defaults to ask. The owner may choose off or allow through settings.update; proposals require owner approval. Global CLI updates never run from development/worktree/scratch roots, even with allow. Each update records a compact tool.update activity event and retains its full receipt.","key":"6","section":"guidance"}
M settings "toolAutoUpdate defaults to ask. The owner may choose off or allow through settings.update; proposals require owner approval. Global CLI updates never run from development/worktree/scratch roots, even with allow. Each update records a compact tool.update activity event and retains its full receipt." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"In Settings > Tool updates, Global CLI updates offers Ask first, Off and Allow automatic updates. The saved PC revision governs this setting; a conflict refreshes the record and asks the owner to choose again. This control does not override development/scratch or local-only refusal.","key":"7","section":"guidance"}
M settings "In Settings > Tool updates, Global CLI updates offers Ask first, Off and Allow automatic updates. The saved PC revision governs this setting; a conflict refreshes the record and asks the owner to choose again. This control does not override development/scratch or local-only refusal." src:"authored manual" state:verified
L settings.proofs-e-frontend v1 -- PROOFS-e frontend action contracts
-- @record {"chapter":"proofs-e-frontend","data":{"failure":"Host/backend or rendered behavior has not been inspected.","recovery":"Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers."},"key":"0","section":"pitfalls"}
X Host/backend or rendered behavior has not been inspected. -> Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers.
-- @record {"chapter":"proofs-e-frontend","data":"Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.","key":"0","section":"frontier"}
F Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.
-- @record {"chapter":"proofs-e-frontend","data":"preferences.normalize: Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency.","key":"0","section":"guidance"}
M settings "preferences.normalize: Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"preferences.motion: Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency.","key":"1","section":"guidance"}
M settings "preferences.motion: Valid visual preferences preserve independent choices and reduce-motion disables motion without changing transparency." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json","key":"2","section":"guidance"}
M settings "Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Startup procedures: preferences.motion-accessibility","key":"3","section":"guidance"}
M settings "Startup procedures: preferences.motion-accessibility" src:"authored manual" state:verified
L settings.proofs-e-models v1 -- PROOFS-e: production model contracts
-- @record {"chapter":"proofs-e-models","data":{"args":{},"inputs":{"$cl_type":"t1"},"shape":{"$cl_type":"t11"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S settings.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-models","data":{"effect":"Read the most recent verification receipt without invoking production actions again","pre":"Selected local workspace; read only","returns":{"$cl_type":"t12"},"reversible":true,"schema":"proofs-e-models.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the most recent verification receipt without invoking production actions again
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-models","data":{"goal":"Read the latest receipt after the production model self-check runner","inputs":{"$cl_type":"t1"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-model-proof-receipt","section":"procedures"}
P read-model-proof-receipt():receipt=neyvia.verify.status() C observed -- Read the latest receipt after the production model self-check runner
V P read-model-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-models","data":{"failure":"Model transforms are reported as proof of a native app/provider/device effect","recovery":"Use the real owning feature procedure and its observed runtime"},"key":"0","section":"pitfalls"}
X Model transforms are reported as proof of a native app/provider/device effect -> Use the real owning feature procedure and its observed runtime
-- @record {"chapter":"proofs-e-models","data":"Rendered browser/desktop journeys are separate from pure model proof","key":"0","section":"frontier"}
F Rendered browser/desktop journeys are separate from pure model proof
-- @record {"chapter":"proofs-e-models","data":"Remote device, game editor and provider behavior require their real runtimes","key":"1","section":"frontier"}
F Remote device, game editor and provider behavior require their real runtimes
-- @record {"chapter":"proofs-e-models","data":"runtime.mergeRuntimes: Catalog aliases join live rows once; readiness/capabilities/auth/model/owner policy are observed from their authoritative source","key":"0","section":"guidance"}
M settings "runtime.mergeRuntimes: Catalog aliases join live rows once; readiness/capabilities/auth/model/owner policy are observed from their authoritative source" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"runtime.runtimeSummary: Ready and installed counts come from rendered runtime rows without inventing detection","key":"1","section":"guidance"}
M settings "runtime.runtimeSummary: Ready and installed counts come from rendered runtime rows without inventing detection" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-models","data":"Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals","key":"2","section":"guidance"}
M settings "Startup runner: scripts/proofs-e-models.mjs --root <owned-scratch>; area proofs-e-models checks real model actions and corrupted output refusals" src:"authored manual" state:verified
L settings.proofs-e-shell v1 -- PROOFS-e shell state and action contracts
-- @record {"chapter":"proofs-e-shell","data":{"args":{},"inputs":{"$cl_type":"t1"},"shape":{"$cl_type":"t11"},"tool":"neyvia.verify.status"},"key":"receipt","section":"state"}
S settings.receipt:{ok:bool ..}=neyvia.verify.status()
-- @record {"chapter":"proofs-e-shell","data":{"effect":"Read the latest verification receipt without repeating shell actions","pre":"Selected local workspace; read only","returns":{"$cl_type":"t12"},"reversible":true,"schema":"proofs-e-shell.status","tool":"neyvia.verify.status"},"key":"status","section":"actions"}
A neyvia.verify.status() -> json:"{\"type\":\"object\",\"required\":[\"ok\",\"available\",\"complete\"]}" -- Read the latest verification receipt without repeating shell actions
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-shell","data":{"args":{},"expect":{"op":"eq","path":"ok","value":true},"tool":"neyvia.verify.status"},"key":"observed","section":"checks"}
C neyvia.verify.status observed:neyvia.verify.status() .ok == true
-- @record {"chapter":"proofs-e-shell","data":{"goal":"Observe the latest shell proof receipt without replaying mutations","inputs":{"$cl_type":"t1"},"steps":[{"action":"status","args":{},"check":"observed","save":"receipt"}]},"key":"read-shell-proof-receipt","section":"procedures"}
P read-shell-proof-receipt():receipt=neyvia.verify.status() C observed -- Observe the latest shell proof receipt without replaying mutations
V P read-shell-proof-receipt -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"proofs-e-shell","data":{"failure":"A queue or shell state receipt is treated as rendered app proof","recovery":"Inspect the owned running UI and actual PDF/output/provider separately"},"key":"0","section":"pitfalls"}
X A queue or shell state receipt is treated as rendered app proof -> Inspect the owned running UI and actual PDF/output/provider separately
-- @record {"chapter":"proofs-e-shell","data":"Rendered shell journeys and PDF loading require owned UI proof","key":"0","section":"frontier"}
F Rendered shell journeys and PDF loading require owned UI proof
-- @record {"chapter":"proofs-e-shell","data":"Provider execution and actual artifact publishing are separate proof boundaries","key":"1","section":"frontier"}
F Provider execution and actual artifact publishing are separate proof boundaries
-- @record {"chapter":"proofs-e-shell","data":"Themes and scenes use bus reducer guards; malformed layouts/unknown scenes/themes retain explicit bus errors","key":"0","section":"guidance"}
M settings "Themes and scenes use bus reducer guards; malformed layouts/unknown scenes/themes retain explicit bus errors" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-shell","data":"Startup runner: scripts/proofs-e-shell.mjs --root <owned-scratch>; area proofs-e-shell checks five composed production journeys and eleven semantic corruptions","key":"1","section":"guidance"}
M settings "Startup runner: scripts/proofs-e-shell.mjs --root <owned-scratch>; area proofs-e-shell checks five composed production journeys and eleven semantic corruptions" src:"authored manual" state:verified
