CL 1
-- @proof {"checkedAt":["scripts/package_onboarding_packs.py:build","scripts/package_onboarding_packs.py:import_closure","grant_agent.proofs_pack_generator.check_local_build","grant_agent.proofs_pack_generator.self_check"],"claim":"The production local-pack generator builds all declared local-component packages in owned scratch; opened descriptors, manifests, file bytes and entrypoint source confirm package meaning, integrity, and portable paths; an out-of-scope source path is refused without writing outside scratch.","id":"p22.pack-generator.local-components","impact":["local add-on package contents","generated component and entrypoint semantics","portable manifest integrity","generator path containment"],"phase":"post"}
L slim-installer v1 -- Authored executable manual
-- @manual {"chapters":{"overview":{"title":"Signed base-pack release evidence"},"proofs-c-runtime":{"title":"PROOFS-c runtime contracts"},"proofs-e-host":{"title":"Host behavior contracts and self-checks (PROOFS-e)"},"proofs-e-release":{"title":"Release and capability observations (PROOFS-e)"}},"clVersion":"1.1","id":"slim-installer","kind":"workflow","proofs":{"area":"proofs-c-runtime, proofs-e-host, installer-extra","manifests":["config/proofs/proofs-c-runtime.json","config/proofs/proofs-e-host.json","config/proofs/proofs-e-release.json","config/proofs/installer-extra.json"],"startup":{"procedures":["catalog/recommended/private-cloud/cyclic dependency rejection","memory add/search/ingest/reopen","OpenClaw ranges and resolved PATH","hash-pinned48488 HTTP child start/reuse/stop plus foreign PID/tampering refusal","toolchain streamed bytes and tampering","real MCP stdio read/approved mutation/refusal/progressive/Neyvia host/close","loopback48487 observed declared release metadata / production candidate parser / digest refusal / durable cache hit"],"runner":"grant_agent.proofs_c_runtime.self_check","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"terminal.exec":"t1","workspace.read":"t2"},"tool_metadata":{"terminal.exec":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"}}}
-- @proof {"checkedAt":["grant_agent.install_profiles.InstallProfileRegistry.catalog_snapshot","grant_agent.proofs_c_runtime.check_catalog","grant_agent.proofs_c_runtime.self_check"],"claim":"Catalog preserves every package tier and delivery state with exact current core/optional totals.","id":"runtime.install.catalog","impact":["installation selection","core/optional inventory"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.install_profiles.InstallProfileRegistry.resolve","grant_agent.proofs_c_runtime.check_plan","grant_agent.proofs_c_runtime.self_check"],"claim":"Plan resolves profile inheritance, optional exclusions and ordered dependency closure; unfinished packages block readiness and execution remains disabled.","id":"runtime.install.plan","impact":["installation plan","dependency readiness","execution gate"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.install_profiles.InstallProfileRegistry._validate","grant_agent.install_profiles.InstallProfileRegistry._cycle_errors","grant_agent.proofs_c_runtime.self_check"],"claim":"Registry rejects package or profile dependency cycles before constructing a selectable registry.","id":"runtime.install.cycles","impact":["installation dependency graph"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.managed_local_service.ManagedServiceSpec.__post_init__","grant_agent.managed_local_service.ManagedServiceSpec.spec_hash","grant_agent.proofs_c_runtime.self_check"],"claim":"Service declaration requires explicit loopback HTTP URLs, SHA256 pins, nonempty argv; environment content and inheritance participate in specification identity.","id":"runtime.service.spec","impact":["managed child identity","local service lifecycle"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.managed_local_service.ManagedLocalService.start","grant_agent.managed_local_service.ManagedLocalService._validate_installation","grant_agent.proofs_c_runtime.self_check"],"claim":"Every start validates executable and required-file SHA256 hashes before process creation or reuse.","id":"runtime.service.installation","impact":["local process creation","model and executable bytes"],"phase":"pre"}
-- @proof {"checkedAt":["grant_agent.managed_local_service.ManagedLocalService.status","grant_agent.managed_local_service.ManagedLocalService._stop_locked","grant_agent.proofs_c_runtime.check_service_status","grant_agent.proofs_c_runtime.self_check"],"claim":"Running status requires live PID, matching executable and specification, and endpoint health/identity. Foreign or changed identity cannot be stopped.","id":"runtime.service.identity","impact":["persisted PID","foreign process safety"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.managed_local_service.ManagedLocalService.start","grant_agent.managed_local_service.ManagedLocalService._stop_locked","grant_agent.proofs_c_runtime.check_service_status","grant_agent.proofs_c_runtime.self_check"],"claim":"An installed exact healthy process is reused without spawning; an owned new process persists running identity and stops to a zero-PID state.","id":"runtime.service.lifecycle","impact":["managed lifecycle","service state receipts"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.managed_node_runtime.node_supports_current_openclaw","grant_agent.proofs_c_runtime.check_node_version","grant_agent.proofs_c_runtime.self_check"],"claim":"OpenClaw supports Node22 from22.22.3, Node24 from24.15.0 and Node25 from25.9.0 or later; Node23 and None are excluded.","id":"runtime.node.versions","impact":["optional CLI compatibility"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.managed_node_runtime.prepend_openclaw_node_to_env","grant_agent.proofs_c_runtime.check_node_env","grant_agent.proofs_c_runtime.self_check"],"claim":"Resolved Node directory leads PATH and NEYVIA_MANAGED_NODE_BIN; preserve original PATH suffix and other variables without mutating caller environment.","id":"runtime.node.environment","impact":["child CLI environment"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager.local_integrity","grant_agent.proofs_c_runtime.check_toolchain_integrity","grant_agent.proofs_c_runtime.self_check"],"claim":"Pinned executable receipts reflect actual streamed SHA256 bytes; platform-managed entries stay distinct and aggregate invalidTools/healthy exactly match rows.","id":"runtime.toolchain.integrity","impact":["marketplace pinned security toolchain"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager._check_tool","grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager._release_candidate","grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager._publish_discovery","grant_agent.proofs_c_runtime.check_toolchain_discovery","grant_agent.proofs_c_runtime.self_check"],"claim":"Stable release discovery binds exact asset template, bounded positive size, official GitHub repository URL and SHA256 digest; absence of digest raises before a candidate is returned; summary and signed-release activation policy match all rows.","id":"runtime.toolchain.discovery","impact":["official release candidate selection","no unsigned install activation"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager._publish_discovery","grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager._fresh_cache","grant_agent.marketplace_toolchain.MarketplaceToolchainUpdateManager.check_latest","grant_agent.proofs_c_runtime.check_toolchain_discovery","grant_agent.proofs_c_runtime.self_check"],"claim":"Published discovery persists exact returned metadata; a fresh schema-compatible cache returns the same rows with cache=hit before any official release fetch.","id":"runtime.toolchain.cache","impact":["release metadata cache","repeat discovery latency"],"phase":"post"}
-- @proof {"checkedAt":["scripts/package_onboarding_packs.py:import_closure"],"claim":"Local add-on import closures include transitive module dependencies with unique portable sorted paths","id":"proofs-e-host.pack-closure","impact":["host state and observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.proofs_installer_journey.self_check","grant_agent.neyvia_onboarding.start_base_pack","grant_agent.neyvia_onboarding.run_download","grant_agent.neyvia_onboarding.pause_base_pack","grant_agent.neyvia_onboarding.base_pack_status","grant_agent.neyvia_onboarding.parse_manifest"],"claim":"The first-run base-pack flow stages the generated local component bytes under the selected state root, reports and consumes pause while preserving resumable bytes, resumes to an exact durable receipt, and refuses an unsafe manifest path without changing staged bytes.","id":"p22.installer.local-pack-journey","impact":["first-run base-pack staging","download progress and pause","verified local pack bytes","manifest path refusal"],"phase":"post"}
-- @proof {"checkedAt":["scripts/prepare_slim_release.mjs:signerFromKey.sign -> checkSignedEnvelope"],"claim":"Both Ed25519 signatures bind the observed manifest bytes, signing identity and trusted comment","id":"release.signed-envelope","impact":["slim-installer production observations"],"phase":"post"}
-- @proof {"checkedAt":["scripts/prepare_slim_release.mjs:prepareRelease/signer -> validateReleaseOutput/validateSigningKeyPath"],"claim":"Release output remains a fresh directory inside the selected repository target; in-tree private key paths are rejected before reading","id":"release.staging-boundary","impact":["slim-installer production observations"],"phase":"invariant"}
-- @proof {"checkedAt":["scripts/check_installer_size.mjs:inspectInstallerBudget -> checkInstallerBudgetObservation"],"claim":"Actual artifacts and staged files determine missing-artifact, size, shell-only and forbidden-content failures","id":"release.installer-budget","impact":["slim-installer production observations"],"phase":"post"}
-- @proof {"checkedAt":["scripts/prepare_slim_release.mjs:externalPackDeclarations -> checkExternalDeclarations"],"claim":"Every current external registry pack retains pinned official source inputs, summed sizes and explicit activation blockers","id":"release.external-declarations","impact":["slim-installer production observations"],"phase":"post"}
-- @proof {"checkedAt":["vite.config.mjs:default config evaluator -> checkVitePhysicalPaths"],"claim":"Every Vite config evaluation uses the selected checkout physical web root, source alias and build output path","id":"release.vite-physical-paths","impact":["Vite build and serving configuration paths"],"phase":"post"}
T t1{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3{path:str}
T t4 json:"{\"type\":\"object\"}"
T t5{sha256:str ~"^[a-fA-F0-9]{64}$" content:str ..}
L slim-installer.overview v1 -- Signed base-pack release evidence
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"inputs":{"$cl_type":"t3"},"shape":{"$cl_type":"t4"},"tool":"workspace.read"},"key":"receipt","section":"state"}
S slim-installer.receipt:json:"{\"type\":\"object\"}"=workspace.read(path:path)
-- @record {"chapter":"overview","data":{"effect":"Return bounded decoded text and full-byte SHA-256; nextOffset paginates text","pre":"Nonblank existing text file resolves under root; no NUL in first 8192 bytes; offset >=0","returns":{"$cl_type":"t5"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"workspace.read","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> {sha256:str ~"^[a-fA-F0-9]{64}$" content:str ..} -- Return bounded decoded text and full-byte SHA-256; nextOffset paginates text
C workspace.read release-receipt:workspace.read(path:path) .content has "neyvia.slim-release/v1"
-- @record {"chapter":"overview","data":{"effect":"Run a local staging/build command and preserve its returned exit code; command can write worktree target artifacts","pre":"Explicit release scope; working directory is this worktree; private key is external; no download/system install/public service change","returns":{"$cl_type":"t4"},"reversible":false,"schema":"terminal.exec","tool":"terminal.exec"},"key":"terminal.exec","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> json:"{\"type\":\"object\"}" ! -- Run a local staging/build command and preserve its returned exit code; command can write worktree target artifacts
F verify-terminal-exec "No authored observer check is bound to terminal.exec" -> ask operator blocks:terminal.exec
-- @record {"chapter":"overview","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"contains","path":"content","value":"neyvia.slim-release/v1"},"tool":"workspace.read"},"key":"release-receipt","section":"checks"}
C workspace.read release-receipt:workspace.read(path:path) .content has "neyvia.slim-release/v1"
-- @record {"chapter":"overview","data":{"goal":"Inspect the signed pack build receipt before deciding whether it is production-ready","inputs":{"$cl_type":"t3"},"steps":[{"action":"workspace.read","args":{"path":{"$input":"path"}},"check":"release-receipt","save":"receipt"},{"judge":"release-authority"}]},"key":"inspect-release","section":"procedures"}
P inspect-release(path:str):receipt=workspace.read(path:path) C release-receipt; J release-authority -- Inspect the signed pack build receipt before deciding whether it is production-ready
V P inspect-release -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"runtimeProvenance.requirementsMatch must be true for production. build.executed must be true and installer hashes present to claim a built installer. External deliveryStatus needs-paul remains blocked even when signatures and official source hashes exist. Publishing requires separate explicit authorization.","options":["local-proof-only","release-candidate","needs-paul"],"question":"Does this receipt satisfy the authorized delivery gate?"},"key":"release-authority","section":"judge"}
J release-authority local-proof-only|release-candidate|needs-paul:"Does this receipt satisfy the authorized delivery gate?" -- runtimeProvenance.requirementsMatch must be true for production. build.executed must be true and installer hashes present to claim a built installer. External deliveryStatus needs-paul remains blocked even when signatures and official source hashes exist. Publishing requires separate explicit authorization.
V J release-authority -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Runtime package version mismatch","recovery":"Use an approved matching portable runtime. Explicit allow-existing-versions and allow-local-proof are only local proof; receipt retains mismatches."},"key":"0","section":"pitfalls"}
X Runtime package version mismatch -> Use an approved matching portable runtime. Explicit allow-existing-versions and allow-local-proof are only local proof; receipt retains mismatches.
-- @record {"chapter":"overview","data":{"failure":"Release output exists or add-on hashes changed","recovery":"Choose a fresh target directory and regenerate local manifests with package_onboarding_packs.py."},"key":"1","section":"pitfalls"}
X Release output exists or add-on hashes changed -> Choose a fresh target directory and regenerate local manifests with package_onboarding_packs.py.
-- @record {"chapter":"overview","data":{"failure":"Native first launch has no Python","recovery":"Use real desktop IPC onboarding_base_pack_status_command/start_command/pause_command; these are native commands, not registered backend tools."},"key":"2","section":"pitfalls"}
X Native first launch has no Python -> Use real desktop IPC onboarding_base_pack_status_command/start_command/pause_command; these are native commands, not registered backend tools.
-- @record {"chapter":"overview","data":"Production signing-key provisioning and HTTPS hosting need release-owner actions.","key":"0","section":"frontier"}
F Production signing-key provisioning and HTTPS hosting need release-owner actions.
-- @record {"chapter":"overview","data":"Seven external manifests pin twelve official source inputs; full dependency locks/extraction/activation remain listed as needsPaul.","key":"1","section":"frontier"}
F Seven external manifests pin twelve official source inputs; full dependency locks/extraction/activation remain listed as needsPaul.
-- @record {"chapter":"overview","data":"Installed openai-agents 0.18.3 differs from repository >=0.19.4,<0.20.","key":"2","section":"frontier"}
F Installed openai-agents 0.18.3 differs from repository >=0.19.4,<0.20.
-- @record {"chapter":"overview","data":"Stage: explicit system Python scripts/stage_portable_python.py --output src-tauri/target/<runtime>.","key":"0","section":"guidance"}
M slim-installer "Stage: explicit system Python scripts/stage_portable_python.py --output src-tauri/target/<runtime>." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Prepare: node scripts/prepare_slim_release.mjs --python-runtime <runtime> --secret-key <external PEM> --version <version> --output src-tauri/target/<release> --base-url <HTTPS URL>. Add --build for real installer build.","key":"1","section":"guidance"}
M slim-installer "Prepare: node scripts/prepare_slim_release.mjs --python-runtime <runtime> --secret-key <external PEM> --version <version> --output src-tauri/target/<release> --base-url <HTTPS URL>. Add --build for real installer build." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"Observer path should be a release-receipt.json inside selected workspace target; workspace.read can require paging for large receipts.","key":"2","section":"guidance"}
M slim-installer "Observer path should be a release-receipt.json inside selected workspace target; workspace.read can require paging for large receipts." src:"authored manual" state:verified
-- @record {"chapter":"overview","data":"See docs/manuals/slim-installer.md for native IPC and source provenance.","key":"3","section":"guidance"}
M slim-installer "See docs/manuals/slim-installer.md for native IPC and source provenance." src:"authored manual" state:verified
L slim-installer.proofs-c-runtime v1 -- PROOFS-c runtime contracts
-- @record {"chapter":"proofs-c-runtime","data":{"failure":"A successful response or existing receipt alone does not prove a managed action.","recovery":"Run the proofs-c-runtime startup adapter in a fresh isolated root; it verifies bytes, persistence, real subprocesses and refusal paths."},"key":"0","section":"pitfalls"}
X A successful response or existing receipt alone does not prove a managed action. -> Run the proofs-c-runtime startup adapter in a fresh isolated root; it verifies bytes, persistence, real subprocesses and refusal paths.
-- @record {"chapter":"proofs-c-runtime","data":"OCI authenticated evidence, trust removal, tampering, activation/rollback and interrupted-transaction recovery: retain all8 OCI cases until full real verifier journeys are migrated.","key":"0","section":"frontier"}
F OCI authenticated evidence, trust removal, tampering, activation/rollback and interrupted-transaction recovery: retain all8 OCI cases until full real verifier journeys are migrated.
-- @record {"chapter":"proofs-c-runtime","data":"Upstream GitHub availability is not claimed: declared metadata is served on owned loopback48487, then production parser and persisted cache run; no package downloads.","key":"1","section":"frontier"}
F Upstream GitHub availability is not claimed: declared metadata is served on owned loopback48487, then production parser and persisted cache run; no package downloads.
-- @record {"chapter":"proofs-c-runtime","data":"runtime.install.catalog: Catalog preserves every package tier and delivery state with exact current core/optional totals.","key":"0","section":"guidance"}
M slim-installer "runtime.install.catalog: Catalog preserves every package tier and delivery state with exact current core/optional totals." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.install.plan: Plan resolves profile inheritance, optional exclusions and ordered dependency closure; unfinished packages block readiness and execution remains disabled.","key":"1","section":"guidance"}
M slim-installer "runtime.install.plan: Plan resolves profile inheritance, optional exclusions and ordered dependency closure; unfinished packages block readiness and execution remains disabled." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.install.cycles: Registry rejects package or profile dependency cycles before constructing a selectable registry.","key":"2","section":"guidance"}
M slim-installer "runtime.install.cycles: Registry rejects package or profile dependency cycles before constructing a selectable registry." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.service.spec: Service declaration requires explicit loopback HTTP URLs, SHA256 pins, nonempty argv; environment content and inheritance participate in specification identity.","key":"3","section":"guidance"}
M slim-installer "runtime.service.spec: Service declaration requires explicit loopback HTTP URLs, SHA256 pins, nonempty argv; environment content and inheritance participate in specification identity." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.service.installation: Every start validates executable and required-file SHA256 hashes before process creation or reuse.","key":"4","section":"guidance"}
M slim-installer "runtime.service.installation: Every start validates executable and required-file SHA256 hashes before process creation or reuse." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.service.identity: Running status requires live PID, matching executable and specification, and endpoint health/identity. Foreign or changed identity cannot be stopped.","key":"5","section":"guidance"}
M slim-installer "runtime.service.identity: Running status requires live PID, matching executable and specification, and endpoint health/identity. Foreign or changed identity cannot be stopped." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.service.lifecycle: An installed exact healthy process is reused without spawning; an owned new process persists running identity and stops to a zero-PID state.","key":"6","section":"guidance"}
M slim-installer "runtime.service.lifecycle: An installed exact healthy process is reused without spawning; an owned new process persists running identity and stops to a zero-PID state." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.node.versions: OpenClaw supports Node22 from22.22.3, Node24 from24.15.0 and Node25 from25.9.0 or later; Node23 and None are excluded.","key":"7","section":"guidance"}
M slim-installer "runtime.node.versions: OpenClaw supports Node22 from22.22.3, Node24 from24.15.0 and Node25 from25.9.0 or later; Node23 and None are excluded." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.node.environment: Resolved Node directory leads PATH and NEYVIA_MANAGED_NODE_BIN; preserve original PATH suffix and other variables without mutating caller environment.","key":"8","section":"guidance"}
M slim-installer "runtime.node.environment: Resolved Node directory leads PATH and NEYVIA_MANAGED_NODE_BIN; preserve original PATH suffix and other variables without mutating caller environment." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.toolchain.integrity: Pinned executable receipts reflect actual streamed SHA256 bytes; platform-managed entries stay distinct and aggregate invalidTools/healthy exactly match rows.","key":"9","section":"guidance"}
M slim-installer "runtime.toolchain.integrity: Pinned executable receipts reflect actual streamed SHA256 bytes; platform-managed entries stay distinct and aggregate invalidTools/healthy exactly match rows." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.toolchain.discovery: Stable release discovery binds exact asset template, bounded positive size, official GitHub repository URL and SHA256 digest; absence of digest raises before a candidate is returned; summary and signed-release activation policy match all rows.","key":"10","section":"guidance"}
M slim-installer "runtime.toolchain.discovery: Stable release discovery binds exact asset template, bounded positive size, official GitHub repository URL and SHA256 digest; absence of digest raises before a candidate is returned; summary and signed-release activation policy match all rows." src:"authored manual" state:verified
-- @record {"chapter":"proofs-c-runtime","data":"runtime.toolchain.cache: Published discovery persists exact returned metadata; a fresh schema-compatible cache returns the same rows with cache=hit before any official release fetch.","key":"11","section":"guidance"}
M slim-installer "runtime.toolchain.cache: Published discovery persists exact returned metadata; a fresh schema-compatible cache returns the same rows with cache=hit before any official release fetch." src:"authored manual" state:verified
L slim-installer.proofs-e-host v1 -- Host behavior contracts and self-checks (PROOFS-e)
-- @record {"chapter":"proofs-e-host","data":{"failure":"A recorded prior action is mistaken for a new observation","recovery":"Reconcile the target and inspect its durable receipt before a separately identified action"},"key":"0","section":"pitfalls"}
X A recorded prior action is mistaken for a new observation -> Reconcile the target and inspect its durable receipt before a separately identified action
-- @record {"chapter":"proofs-e-host","data":"Local add-on import closures include transitive module dependencies with unique portable sorted paths","key":"0","section":"guidance"}
M slim-installer "Local add-on import closures include transitive module dependencies with unique portable sorted paths" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-host","data":"Self-check: neyvia verify --area proofs-e-host; real OS ownership, status-line process refresh, transitive pack and durable scratch file action.","key":"1","section":"guidance"}
M slim-installer "Self-check: neyvia verify --area proofs-e-host; real OS ownership, status-line process refresh, transitive pack and durable scratch file action." src:"authored manual" state:verified
L slim-installer.proofs-e-release v1 -- Release and capability observations (PROOFS-e)
-- @record {"chapter":"proofs-e-release","data":{"failure":"Metadata readiness or a scoped proof is mistaken for external execution or a published release","recovery":"Inspect the observed boundary and use the owning real activation or publication procedure"},"key":"0","section":"pitfalls"}
X Metadata readiness or a scoped proof is mistaken for external execution or a published release -> Inspect the observed boundary and use the owning real activation or publication procedure
-- @record {"chapter":"proofs-e-release","data":"No installer build, installation, publication, download or private signing-key provisioning is claimed.","key":"0","section":"frontier"}
F No installer build, installation, publication, download or private signing-key provisioning is claimed.
-- @record {"chapter":"proofs-e-release","data":"Enabled plugin metadata and native instruction linkage do not prove external MCP/plugin execution.","key":"1","section":"frontier"}
F Enabled plugin metadata and native instruction linkage do not prove external MCP/plugin execution.
-- @record {"chapter":"proofs-e-release","data":"The impact index proves static command wiring; it does not execute backend or desktop commands.","key":"2","section":"frontier"}
F The impact index proves static command wiring; it does not execute backend or desktop commands.
-- @record {"chapter":"proofs-e-release","data":"Both Ed25519 signatures bind the observed manifest bytes, signing identity and trusted comment","key":"0","section":"guidance"}
M slim-installer "Both Ed25519 signatures bind the observed manifest bytes, signing identity and trusted comment" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Release output remains a fresh directory inside the selected repository target; in-tree private key paths are rejected before reading","key":"1","section":"guidance"}
M slim-installer "Release output remains a fresh directory inside the selected repository target; in-tree private key paths are rejected before reading" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Actual artifacts and staged files determine missing-artifact, size, shell-only and forbidden-content failures","key":"2","section":"guidance"}
M slim-installer "Actual artifacts and staged files determine missing-artifact, size, shell-only and forbidden-content failures" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Every current external registry pack retains pinned official source inputs, summed sizes and explicit activation blockers","key":"3","section":"guidance"}
M slim-installer "Every current external registry pack retains pinned official source inputs, summed sizes and explicit activation blockers" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Self-check: neyvia verify --area proofs-e-release; scoped actual signing, scanner, metadata and static impact actions.","key":"4","section":"guidance"}
M slim-installer "Self-check: neyvia verify --area proofs-e-release; scoped actual signing, scanner, metadata and static impact actions." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-release","data":"Every Vite config evaluation uses the selected checkout physical web root, source alias and build output path","key":"5","section":"guidance"}
M slim-installer "Every Vite config evaluation uses the selected checkout physical web root, source alias and build output path" src:"authored manual" state:verified

-- @proof {"id":"p22.onboarding.external-source-readiness","phase":"pre","claim":"The seven authored external onboarding manifests preserve their declared platform tags and honest fail-closed readiness through the production status path; traversal paths and unsigned remote payload manifests are refused without network access or installation.","checkedAt":["grant_agent.proofs_onboarding_external_journey.self_check","config/onboarding_packs.json:manifests","config/onboarding_packs/pack.documents-office/manifest.json:files.source.platform","config/onboarding_packs/pack.ocr-local/manifest.json:files.source.platform","config/onboarding_packs/pack.android-lab/manifest.json:files.source.platform","config/onboarding_packs/pack.developer-toolchains/manifest.json:files.source.platform","config/onboarding_packs/pack.models-gpu/manifest.json:files.source.platform","config/onboarding_packs/pack.media-creative/manifest.json:files.source.platform","config/onboarding_packs/pack.mesh-control-plane/manifest.json:files.source.platform","config/neyvia_install_profiles.json:packages","grant_agent.install_profiles.InstallProfileRegistry.catalog_snapshot","grant_agent.neyvia_onboarding.pack_status -> grant_agent.neyvia_onboarding.load_pack_manifest","grant_agent.neyvia_onboarding.parse_manifest -> _safe_relative/_verify_manifest_signature","grant_agent.proofs_d_onboarding.check_pack_status"],"impact":["external onboarding pack readiness","declared platform/runtime metadata","manifest traversal and signature admission"]}
-- @proof {"checkedAt":["grant_agent.proofs_installer_extra.self_check","grant_agent.neyvia_onboarding.snapshot","grant_agent.neyvia_onboarding.load_catalog","grant_agent.neyvia_onboarding.pack_status","grant_agent.neyvia_onboarding.save_state","grant_agent.proofs_d_onboarding.check_pack_status/check_catalog/check_saved","config/onboarding_packs/pack.ocr-local/manifest.json","config/onboarding_packs/pack.creator-sdk/manifest.json","web/src/neyvia/next/nxOnboardingModel.js:packView"],"claim":"The first-run snapshot includes every validated app and pack, keeps an unsigned external source visibly failed but retryable, keeps an actual byte-verified local package available for staging, and reflects valid saved choices on a fresh read without changing delivery state.","id":"p22.onboarding.first-run-snapshot","impact":["onboarding snapshot","retryable add-on readiness","portable local package","saved setup choices"],"phase":"post"}
