CL 1
L video v1 -- Authored executable manual
-- @manual {"chapters":{"video":{"title":"Video: HyperFrames compositions as edit decision lists, LAYA video observers and outcome contracts"}},"clVersion":"1.1","id":"video","kind":"environment","proofs":{"area":"video"},"schema":"neyvia.manual.v1","schemas":{"neyvia.video.add":"live_schema_22","neyvia.video.caption":"live_schema_23","neyvia.video.contact_sheet":"live_schema_24","neyvia.video.contracts":"live_schema_25","neyvia.video.contracts_proof":"t13","neyvia.video.improve":"live_schema_26","neyvia.video.judge":"live_schema_27","neyvia.video.keyframe":"live_schema_28","neyvia.video.new":"live_schema_29","neyvia.video.remove":"live_schema_30","neyvia.video.render":"live_schema_31","neyvia.video.split":"live_schema_32","neyvia.video.studio":"live_schema_33","neyvia.video.timeline":"live_schema_34","neyvia.video.transcribe":"live_schema_35","neyvia.video.transition":"live_schema_36","neyvia.video.trim":"live_schema_37","neyvia.video.vote":"live_schema_38"},"tool_metadata":{"neyvia.video.add":{"mutability_class":"artifact_write"},"neyvia.video.caption":{"mutability_class":"artifact_write"},"neyvia.video.contact_sheet":{"mutability_class":"artifact_write"},"neyvia.video.contracts":{"mutability_class":"read"},"neyvia.video.contracts_proof":{"mutability_class":"read"},"neyvia.video.improve":{"mutability_class":"external_action"},"neyvia.video.judge":{"mutability_class":"read"},"neyvia.video.keyframe":{"mutability_class":"artifact_write"},"neyvia.video.new":{"mutability_class":"artifact_write"},"neyvia.video.remove":{"mutability_class":"artifact_write"},"neyvia.video.render":{"mutability_class":"external_action"},"neyvia.video.split":{"mutability_class":"artifact_write"},"neyvia.video.studio":{"mutability_class":"external_action"},"neyvia.video.timeline":{"mutability_class":"read"},"neyvia.video.transcribe":{"mutability_class":"read"},"neyvia.video.transition":{"mutability_class":"artifact_write"},"neyvia.video.trim":{"mutability_class":"artifact_write"},"neyvia.video.vote":{"mutability_class":"artifact_write"}}}
T live_schema_22 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"kind\":{\"enum\":[\"image\",\"video\",\"text\",\"caption\",\"audio\"]},\"start\":{\"type\":\"number\"},\"duration\":{\"type\":\"number\"},\"src\":{\"type\":\"string\",\"maxLength\":16000},\"text\":{\"type\":\"string\",\"maxLength\":16000},\"id\":{\"type\":\"string\",\"maxLength\":16000},\"track\":{\"type\":\"integer\"},\"fit\":{\"enum\":[\"card\",\"contain\",\"cover\"]},\"volume\":{\"type\":\"number\"},\"mediaStart\":{\"type\":\"number\"},\"fadeIn\":{\"type\":\"number\"},\"fadeOut\":{\"type\":\"number\"},\"tags\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":16000}},\"intent\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"project\",\"kind\",\"start\",\"duration\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_23 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"text\":{\"type\":\"string\",\"maxLength\":16000},\"start\":{\"type\":\"number\"},\"duration\":{\"type\":\"number\"},\"id\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"project\",\"text\",\"start\",\"duration\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"text\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_24 json:"{\"type\":\"object\",\"properties\":{\"video\":{\"type\":\"string\",\"maxLength\":16000},\"out\":{\"type\":\"string\",\"maxLength\":16000},\"count\":{\"type\":\"integer\",\"minimum\":4,\"maximum\":60}},\"required\":[\"video\",\"out\"],\"allOf\":[{\"properties\":{\"video\":{\"not\":{\"enum\":[\"\"]}},\"out\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_25 json:"{\"type\":\"object\",\"properties\":{\"video\":{\"type\":\"string\",\"maxLength\":16000},\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"brief\":{\"type\":[\"object\",\"string\"]}},\"required\":[\"video\"],\"allOf\":[{\"properties\":{\"video\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_26 json:"{\"type\":\"object\",\"properties\":{\"brief\":{\"type\":\"string\",\"maxLength\":16000},\"out\":{\"type\":\"string\",\"maxLength\":16000},\"maxRounds\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":24},\"master\":{\"type\":\"boolean\"}},\"required\":[\"brief\",\"out\"],\"allOf\":[{\"properties\":{\"brief\":{\"not\":{\"enum\":[\"\"]}},\"out\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_27 json:"{\"type\":\"object\",\"properties\":{\"video\":{\"type\":\"string\",\"maxLength\":16000},\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"brief\":{\"type\":[\"object\",\"string\"]}},\"required\":[\"video\"],\"allOf\":[{\"properties\":{\"video\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_28 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"id\":{\"type\":\"string\",\"maxLength\":16000},\"property\":{\"enum\":[\"scale\",\"x\",\"y\",\"opacity\"]},\"at\":{\"type\":\"number\"},\"value\":{\"type\":\"number\"},\"ease\":{\"enum\":[\"none\",\"power1.inOut\",\"power2.out\",\"power2.inOut\",\"power3.out\",\"sine.inOut\",\"expo.out\"]}},\"required\":[\"project\",\"id\",\"property\",\"at\",\"value\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_29 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"width\":{\"type\":\"integer\"},\"height\":{\"type\":\"integer\"},\"fps\":{\"type\":\"integer\"},\"duration\":{\"type\":\"number\"},\"background\":{\"type\":\"string\",\"maxLength\":16000},\"title\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_30 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"id\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"project\",\"id\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_31 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"output\":{\"type\":\"string\",\"maxLength\":16000},\"quality\":{\"enum\":[\"draft\",\"looks\",\"delivery\"]},\"workers\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":8}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_32 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"id\":{\"type\":\"string\",\"maxLength\":16000},\"at\":{\"type\":\"number\"}},\"required\":[\"project\",\"id\",\"at\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_33 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"port\":{\"type\":\"integer\",\"minimum\":49165,\"maximum\":49167},\"stop\":{\"type\":\"boolean\"}},\"required\":[\"project\",\"port\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_34 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"brief\":{\"type\":[\"object\",\"string\"]}},\"required\":[\"project\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_35 json:"{\"type\":\"object\",\"properties\":{\"video\":{\"type\":\"string\",\"maxLength\":16000},\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"brief\":{\"type\":[\"object\",\"string\"]},\"speech\":{\"enum\":[\"auto\",\"off\"]}},\"required\":[\"video\"],\"allOf\":[{\"properties\":{\"video\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_36 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"id\":{\"type\":\"string\",\"maxLength\":16000},\"kind\":{\"enum\":[\"none\",\"fade\",\"crossfade\",\"slide\",\"rise\",\"zoom\"]},\"seconds\":{\"type\":\"number\"},\"edge\":{\"enum\":[\"in\",\"out\"]}},\"required\":[\"project\",\"id\",\"kind\",\"seconds\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_37 json:"{\"type\":\"object\",\"properties\":{\"project\":{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"},\"id\":{\"type\":\"string\",\"maxLength\":16000},\"start\":{\"type\":\"number\"},\"duration\":{\"type\":\"number\"},\"mediaStart\":{\"type\":\"number\"}},\"required\":[\"project\",\"id\"],\"allOf\":[{\"properties\":{\"project\":{\"not\":{\"enum\":[\"\"]}},\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T live_schema_38 json:"{\"type\":\"object\",\"properties\":{\"a\":{\"type\":\"object\"},\"b\":{\"type\":\"object\"},\"winner\":{\"enum\":[\"a\",\"b\"]},\"reason\":{\"type\":\"string\",\"maxLength\":16000},\"user\":{\"type\":\"string\",\"maxLength\":16000}},\"required\":[\"a\",\"b\",\"winner\",\"reason\",\"user\"],\"allOf\":[{\"properties\":{\"reason\":{\"not\":{\"enum\":[\"\"]}},\"user\":{\"not\":{\"enum\":[\"\"]}}}}]}"
-- @proof {"checkedAt":["grant_agent.video_contracts.proof","grant_agent.laya_video.observe_file","grant_agent.scene_core.judge"],"claim":"A rendered fixture shows each fast outcome contract (render, duration/frames, black, frozen, clipping, caption safe area) catching its defect and passing the clean section.","id":"video.outcome-contracts","impact":["src/grant_agent/video_contracts.py","src/grant_agent/laya_video.py","src/grant_agent/video_hyperframes.py","manuals/cl/video.cl"],"phase":"invariant"}
T t1{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" width?:int height?:int fps?:int duration?:num background?:str#..16000 title?:str#..16000 ..}
T t2{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" kind:"image"|"video"|"text"|"caption"|"audio" start:num duration:num src?:str#..16000 text?:str#..16000 id?:str#..16000 track?:int fit?:"card"|"contain"|"cover" volume?:num mediaStart?:num fadeIn?:num fadeOut?:num tags?:[str#..16000] intent?:str#..16000 ..}
T t3{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 start?:num duration?:num mediaStart?:num ..}
T t4{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 at:num ..}
T t5{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 kind:"none"|"fade"|"crossfade"|"slide"|"rise"|"zoom" seconds:num edge?:"in"|"out" ..}
T t6{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" text:str#..16000 start:num duration:num id?:str#..16000 ..}
T t7{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 property:"scale"|"x"|"y"|"opacity" at:num value:num ease?:"none"|"power1.inOut"|"power2.out"|"power2.inOut"|"power3.out"|"sine.inOut"|"expo.out" ..}
T t8{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 ..}
T t9{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}" ..}
T t10{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" output?:str#..16000 quality?:"draft"|"looks"|"delivery" workers?:1..8 ..}
T t11{video:str#..16000 project?:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}" speech?:"auto"|"off" ..}
T t12{video:str#..16000 project?:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}" ..}
T t13{..}
T t14{brief:str#..16000 out:str#..16000 maxRounds?:0..24 master?:bool ..}
T t15{project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" port:49165..49167 stop?:bool ..}
T t16{video:str#..16000 out:str#..16000 count?:4..60 ..}
T t17{a:json:"{\"type\":\"object\"}" b:json:"{\"type\":\"object\"}" winner:"a"|"b" reason:str#..16000 user:str#..16000 ..}
T t18 json:"{\"type\":\"object\"}"
T t19 json:"{\"type\":\"object\",\"properties\":{}}"
T t20{project:str screen:str caption:str}
T t21{brief:str out:str}
L video.video v1 -- Video: HyperFrames compositions as edit decision lists, LAYA video observers and outcome contracts
-- @record {"chapter":"video","data":{"effect":"Create a HyperFrames video project driven by an edit decision list (EDL).","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.new","tool":"neyvia.video.new"},"key":"video-new","section":"actions"}
A neyvia.video.new(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" width?:int height?:int fps?:int duration?:num background?:str#..16000 title?:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Create a HyperFrames video project driven by an edit decision list (EDL).
F verify-video-new "No authored observer check is bound to neyvia.video.new" -> ask operator blocks:neyvia.video.new
-- @record {"chapter":"video","data":{"effect":"Place an image, video, text, caption or audio clip on the timeline; the composition recompiles.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.add","tool":"neyvia.video.add"},"key":"video-add","section":"actions"}
A neyvia.video.add(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" kind:"image"|"video"|"text"|"caption"|"audio" start:num duration:num src?:str#..16000 text?:str#..16000 id?:str#..16000 track?:int fit?:"card"|"contain"|"cover" volume?:num mediaStart?:num fadeIn?:num fadeOut?:num tags?:[str#..16000] intent?:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Place an image, video, text, caption or audio clip on the timeline; the composition recompiles.
F verify-video-add "No authored observer check is bound to neyvia.video.add" -> ask operator blocks:neyvia.video.add
-- @record {"chapter":"video","data":{"effect":"Trim a clip: new start, duration and/or source offset.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.trim","tool":"neyvia.video.trim"},"key":"video-trim","section":"actions"}
A neyvia.video.trim(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 start?:num duration?:num mediaStart?:num) -> json:"{\"type\":\"object\"}" ! -- Trim a clip: new start, duration and/or source offset.
F verify-video-trim "No authored observer check is bound to neyvia.video.trim" -> ask operator blocks:neyvia.video.trim
-- @record {"chapter":"video","data":{"effect":"Split a clip at an absolute time; the second half keeps the right source offset.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.split","tool":"neyvia.video.split"},"key":"video-split","section":"actions"}
A neyvia.video.split(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 at:num) -> json:"{\"type\":\"object\"}" ! -- Split a clip at an absolute time; the second half keeps the right source offset.
F verify-video-split "No authored observer check is bound to neyvia.video.split" -> ask operator blocks:neyvia.video.split
-- @record {"chapter":"video","data":{"effect":"Set a clip entrance or exit: fade, crossfade, slide, rise, zoom or none.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.transition","tool":"neyvia.video.transition"},"key":"video-transition","section":"actions"}
A neyvia.video.transition(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 kind:"none"|"fade"|"crossfade"|"slide"|"rise"|"zoom" seconds:num edge?:"in"|"out") -> json:"{\"type\":\"object\"}" ! -- Set a clip entrance or exit: fade, crossfade, slide, rise, zoom or none.
F verify-video-transition "No authored observer check is bound to neyvia.video.transition" -> ask operator blocks:neyvia.video.transition
-- @record {"chapter":"video","data":{"effect":"Add a plain caption for a time range.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.caption","tool":"neyvia.video.caption"},"key":"video-caption","section":"actions"}
A neyvia.video.caption(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" text:str#..16000 start:num duration:num id?:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Add a plain caption for a time range.
F verify-video-caption "No authored observer check is bound to neyvia.video.caption" -> ask operator blocks:neyvia.video.caption
-- @record {"chapter":"video","data":{"effect":"Keyframe scale, x, y or opacity on a clip (time relative to the clip).","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.keyframe","tool":"neyvia.video.keyframe"},"key":"video-keyframe","section":"actions"}
A neyvia.video.keyframe(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000 property:"scale"|"x"|"y"|"opacity" at:num value:num ease?:"none"|"power1.inOut"|"power2.out"|"power2.inOut"|"power3.out"|"sine.inOut"|"expo.out") -> json:"{\"type\":\"object\"}" ! -- Keyframe scale, x, y or opacity on a clip (time relative to the clip).
F verify-video-keyframe "No authored observer check is bound to neyvia.video.keyframe" -> ask operator blocks:neyvia.video.keyframe
-- @record {"chapter":"video","data":{"effect":"Remove a clip from the timeline.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.remove","tool":"neyvia.video.remove"},"key":"video-remove","section":"actions"}
A neyvia.video.remove(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" id:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Remove a clip from the timeline.
F verify-video-remove "No authored observer check is bound to neyvia.video.remove" -> ask operator blocks:neyvia.video.remove
-- @record {"chapter":"video","data":{"effect":"Observe the composition and timeline as a CL Scene (EDL, HyperFrames timeline and lint) and judge it before rendering.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.timeline","tool":"neyvia.video.timeline"},"key":"video-timeline","section":"actions"}
A neyvia.video.timeline(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}") -> json:"{\"type\":\"object\"}" -- Observe the composition and timeline as a CL Scene (EDL, HyperFrames timeline and lint) and judge it before rendering.
F verify-video-timeline "No authored observer check is bound to neyvia.video.timeline" -> ask operator blocks:neyvia.video.timeline
-- @record {"chapter":"video","data":{"effect":"Render the project to MP4 headless with HyperFrames.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.render","tool":"neyvia.video.render"},"key":"video-render","section":"actions"}
A neyvia.video.render(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" output?:str#..16000 quality?:"draft"|"looks"|"delivery" workers?:1..8) -> json:"{\"type\":\"object\"}" ! -- Render the project to MP4 headless with HyperFrames.
F verify-video-render "No authored observer check is bound to neyvia.video.render" -> ask operator blocks:neyvia.video.render
-- @record {"chapter":"video","data":{"effect":"Transcribe a rendered video into a CL Scene: shots, cuts, black/frozen runs, loudness, true peak, beats, Whisper words with timings, keyframe OCR, caption boxes from the composition DOM, LAYA glance and source audit of every screen.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.transcribe","tool":"neyvia.video.transcribe"},"key":"video-transcribe","section":"actions"}
A neyvia.video.transcribe(video:str#..16000 project?:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}" speech?:"auto"|"off") -> json:"{\"type\":\"object\"}" -- Transcribe a rendered video into a CL Scene: shots, cuts, black/frozen runs, loudness, true peak, beats, Whisper words with timings, keyframe OCR, caption boxes from the composition DOM, LAYA glance and source audit of every screen.
F verify-video-transcribe "No authored observer check is bound to neyvia.video.transcribe" -> ask operator blocks:neyvia.video.transcribe
-- @record {"chapter":"video","data":{"effect":"Judge a rendered video against the CL video predicates (and a brief); findings name their fixes.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.judge","tool":"neyvia.video.judge"},"key":"video-judge","section":"actions"}
A neyvia.video.judge(video:str#..16000 project?:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}") -> json:"{\"type\":\"object\"}" -- Judge a rendered video against the CL video predicates (and a brief); findings name their fixes.
F verify-video-judge "No authored observer check is bound to neyvia.video.judge" -> ask operator blocks:neyvia.video.judge
-- @record {"chapter":"video","data":{"effect":"Fast outcome contracts for a render: ok, duration and frame count, no black or frozen frames, no clipping, captions in safe areas.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":true,"schema":"neyvia.video.contracts","tool":"neyvia.video.contracts"},"key":"video-contracts","section":"actions"}
A neyvia.video.contracts(video:str#..16000 project?:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" brief?:json:"{\"type\":[\"object\",\"string\"]}") -> json:"{\"type\":\"object\"}" -- Fast outcome contracts for a render: ok, duration and frame count, no black or frozen frames, no clipping, captions in safe areas.
F verify-video-contracts "No authored observer check is bound to neyvia.video.contracts" -> ask operator blocks:neyvia.video.contracts
-- @record {"chapter":"video","data":{"effect":"Render (or reuse) a 3 s fixture with one clean and several defective sections and show each contract catches its defect.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"$cl_type":"t18"},"reversible":true,"schema":"neyvia.video.contracts_proof","tool":"neyvia.video.contracts_proof"},"key":"video-contracts_proof","section":"actions"}
A neyvia.video.contracts_proof() -> json:"{\"type\":\"object\"}" -- Render (or reuse) a 3 s fixture with one clean and several defective sections and show each contract catches its defect.
C neyvia.video.contracts_proof contracts-fixture:neyvia.video.contracts_proof() .passed == true
-- @record {"chapter":"video","data":{"effect":"LAYA edits by itself from a CL brief file: first draft from real captures -> preview render -> judge -> one named EDL fix per round, kept only on a strict finding reduction with exact rollback otherwise -> master render; every outcome is an episode.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.improve","tool":"neyvia.video.improve"},"key":"video-improve","section":"actions"}
A neyvia.video.improve(brief:str#..16000 out:str#..16000 maxRounds?:0..24 master?:bool) -> json:"{\"type\":\"object\"}" ! -- LAYA edits by itself from a CL brief file: first draft from real captures -> preview render -> judge -> one named EDL fix per round, kept only on a strict finding reduction with exact rollback otherwise -> master render; every outcome is an episode.
F verify-video-improve "No authored observer check is bound to neyvia.video.improve" -> ask operator blocks:neyvia.video.improve
-- @record {"chapter":"video","data":{"effect":"Serve HyperFrames Studio for a project headless (no window) on an explicit port 49165-49167, or stop it.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.studio","tool":"neyvia.video.studio"},"key":"video-studio","section":"actions"}
A neyvia.video.studio(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" port:49165..49167 stop?:bool) -> json:"{\"type\":\"object\"}" ! -- Serve HyperFrames Studio for a project headless (no window) on an explicit port 49165-49167, or stop it.
F verify-video-studio "No authored observer check is bound to neyvia.video.studio" -> ask operator blocks:neyvia.video.studio
-- @record {"chapter":"video","data":{"effect":"Write a contact sheet of evenly spaced frames of a video.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.contact_sheet","tool":"neyvia.video.contact_sheet"},"key":"video-contact_sheet","section":"actions"}
A neyvia.video.contact_sheet(video:str#..16000 out:str#..16000 count?:4..60) -> json:"{\"type\":\"object\"}" ! -- Write a contact sheet of evenly spaced frames of a video.
F verify-video-contact_sheet "No authored observer check is bound to neyvia.video.contact_sheet" -> ask operator blocks:neyvia.video.contact_sheet
-- @record {"chapter":"video","data":{"effect":"Record Paul's A/B preference between two judged cuts (two video Scenes) as personal taste episodes.","pre":"Project folder inside the workspace or D:/NeyviaRuns/video; HyperFrames CLI installed; nothing opens a window","returns":{"type":"object"},"reversible":false,"schema":"neyvia.video.vote","tool":"neyvia.video.vote"},"key":"video-vote","section":"actions"}
A neyvia.video.vote(a:json:"{\"type\":\"object\"}" b:json:"{\"type\":\"object\"}" winner:"a"|"b" reason:str#..16000 user:str#..16000) -> json:"{\"type\":\"object\"}" ! -- Record Paul's A/B preference between two judged cuts (two video Scenes) as personal taste episodes.
F verify-video-vote "No authored observer check is bound to neyvia.video.vote" -> ask operator blocks:neyvia.video.vote
-- @record {"chapter":"video","data":{"args":{},"expect":{"op":"eq","path":"passed","value":true},"tool":"neyvia.video.contracts_proof"},"key":"contracts-fixture","section":"checks"}
C neyvia.video.contracts_proof contracts-fixture:neyvia.video.contracts_proof() .passed == true
-- @record {"chapter":"video","data":{"goal":"Render (or reuse) the 3 s fixture and show render ok, duration/frames, black, frozen, clipping and caption safe-area contracts each catch their defect and pass the clean section","inputs":{"$cl_type":"t19"},"steps":[{"action":"video-contracts_proof","args":{},"check":"contracts-fixture","save":"proof"}]},"key":"prove-contracts","section":"procedures"}
P prove-contracts():proof=neyvia.video.contracts_proof() C contracts-fixture -- Render (or reuse) the 3 s fixture and show render ok, duration/frames, black, frozen, clipping and caption safe-area contracts each catch their defect and pass the clean section
V P prove-contracts -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"video","data":{"goal":"Build a short cut by hand: new project, one screen with a push, a caption, read the timeline Scene, render, run the outcome contracts","inputs":{"type":"object","properties":{"project":{"type":"string","maxLength":1000,"description":"Project folder (inside the workspace or D:/NeyviaRuns/video)"},"screen":{"type":"string","maxLength":16000},"caption":{"type":"string","maxLength":16000}},"required":["project","screen","caption"],"additionalProperties":false},"steps":[{"action":"video-new","args":{"duration":4,"project":{"$input":"project"}},"save":"project"},{"action":"video-add","args":{"duration":4,"id":"shot-1","kind":"image","project":{"$input":"project"},"src":{"$input":"screen"},"start":0},"save":"shot"},{"action":"video-keyframe","args":{"at":4,"id":"shot-1","project":{"$input":"project"},"property":"scale","value":1.04},"save":"push"},{"action":"video-caption","args":{"duration":3,"project":{"$input":"project"},"start":0.5,"text":{"$input":"caption"}},"save":"caption"},{"action":"video-timeline","args":{"project":{"$input":"project"}},"save":"timeline"},{"action":"video-render","args":{"project":{"$input":"project"}},"save":"render"}]},"key":"cut-from-screens","section":"procedures"}
P cut-from-screens(project:json:"{\"type\":\"string\",\"maxLength\":1000,\"description\":\"Project folder (inside the workspace or D:/NeyviaRuns/video)\"}" screen:str#..16000 caption:str#..16000): project=neyvia.video.new(duration:4 project:project); shot=neyvia.video.add(duration:4 id:"shot-1" kind:"image" project:project src:screen start:0); push=neyvia.video.keyframe(at:4 id:"shot-1" project:project property:"scale" value:1.04); caption=neyvia.video.caption(duration:3 project:project start:0.5 text:caption); timeline=neyvia.video.timeline(project:project); render=neyvia.video.render(project:project) -- Build a short cut by hand: new project, one screen with a push, a caption, read the timeline Scene, render, run the outcome contracts
V P cut-from-screens -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"video","data":{"goal":"LAYA edits by itself from a brief: plan v1, render, transcribe, judge, fix, re-render, keep only improvements, write episodes","inputs":{"type":"object","properties":{"brief":{"type":"string","maxLength":16000},"out":{"type":"string","maxLength":16000}},"required":["brief","out"],"additionalProperties":false},"steps":[{"action":"video-improve","args":{"brief":{"$input":"brief"},"out":{"$input":"out"}},"save":"report"}]},"key":"edit-from-brief","section":"procedures"}
P edit-from-brief(brief:str#..16000 out:str#..16000): report=neyvia.video.improve(brief:brief out:out) -- LAYA edits by itself from a brief: plan v1, render, transcribe, judge, fix, re-render, keep only improvements, write episodes
V P edit-from-brief -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"video","data":{"failure":"Studio or preview opens a browser window","recovery":"Always pass --no-open (video.studio does) and an explicit port 49165-49167 (track VIDEO block)."},"key":"0","section":"pitfalls"}
X Studio or preview opens a browser window -> Always pass --no-open (video.studio does) and an explicit port 49165-49167 (track VIDEO block).
-- @record {"chapter":"video","data":{"failure":"An edit made in HyperFrames Studio is overwritten","recovery":"Studio edits index.html; neyvia.video.* regenerates index.html from edl.json. Read the change back with video.timeline and mirror it into the EDL before the next EDL edit."},"key":"1","section":"pitfalls"}
X An edit made in HyperFrames Studio is overwritten -> Studio edits index.html; neyvia.video.* regenerates index.html from edl.json. Read the change back with video.timeline and mirror it into the EDL before the next EDL edit.
-- @record {"chapter":"video","data":{"failure":"Pixel-measured caption contrast reads low","recovery":"Anti-aliasing lowers measured contrast; the predicate uses 3:1 on pixels, not the 4.5:1 CSS rule."},"key":"2","section":"pitfalls"}
X Pixel-measured caption contrast reads low -> Anti-aliasing lowers measured contrast; the predicate uses 3:1 on pixels, not the 4.5:1 CSS rule.
-- @record {"chapter":"video","data":"Rendering uses a local chrome-headless-shell with a throwaway profile (HyperFrames has no connect-over-CDP); no window opens. The composition DOM (caption boxes, fonts) is read in headless Obscura.","key":"0","section":"frontier"}
F Rendering uses a local chrome-headless-shell with a throwaway profile (HyperFrames has no connect-over-CDP); no window opens. The composition DOM (caption boxes, fonts) is read in headless Obscura.
-- @record {"chapter":"video","data":"A 33 s cut renders at 640x360@12 in about 1-3 minutes for a judge round and at 1920x1080@60 for the master; the fast outcome contracts on an existing render take seconds.","key":"1","section":"frontier"}
F A 33 s cut renders at 640x360@12 in about 1-3 minutes for a judge round and at 1920x1080@60 for the master; the fast outcome contracts on an existing render take seconds.
-- @record {"chapter":"video","data":"Speech-to-text is local Whisper (base, cached; nothing is downloaded); segments the model marks as non-speech are dropped, words keep start and end. Music-only cuts transcribe to no words.","key":"2","section":"frontier"}
F Speech-to-text is local Whisper (base, cached; nothing is downloaded); segments the model marks as non-speech are dropped, words keep start and end. Music-only cuts transcribe to no words.
-- @record {"chapter":"video","data":"HyperFrames normalises each <audio> clip, so its own renders do not clip; audio-clipping still guards raw muxes and other editors (the contracts fixture muxes a clipped tone to prove it).","key":"3","section":"frontier"}
F HyperFrames normalises each <audio> clip, so its own renders do not clip; audio-clipping still guards raw muxes and other editors (the contracts fixture muxes a clipped tone to prove it).
-- @record {"chapter":"video","data":"Studio edits index.html; neyvia.video.* regenerates index.html from edl.json, so a hand edit in Studio must be mirrored into the EDL (read it back with video.timeline).","key":"4","section":"frontier"}
F Studio edits index.html; neyvia.video.* regenerates index.html from edl.json, so a hand edit in Studio must be mirrored into the EDL (read it back with video.timeline).
-- @record {"chapter":"video","data":"Taste is not a crisp predicate: Paul's A/B votes are written as personal episodes (video.vote); none were cast by agents.","key":"5","section":"frontier"}
F Taste is not a crisp predicate: Paul's A/B votes are written as personal episodes (video.vote); none were cast by agents.
-- @record {"chapter":"video","data":"An agent edits a video through the EDL (video.new/add/trim/split/transition/caption/keyframe/remove); every edit recompiles index.html in HyperFrames' own composition format, so HyperFrames Studio, lint, timeline and render all see the same project.","key":"0","section":"guidance"}
M video "An agent edits a video through the EDL (video.new/add/trim/split/transition/caption/keyframe/remove); every edit recompiles index.html in HyperFrames' own composition format, so HyperFrames Studio, lint, timeline and render all see the same project." src:"authored manual" state:verified
-- @record {"chapter":"video","data":"Observe before rendering with video.timeline (the composition and timeline as a Scene, judged with the video-edit predicates below), and after rendering with video.transcribe/video.judge: the one video judge (laya_video, vocabulary manuals/cl/laya-video.cl) measures shots, cuts, black and frozen runs, loudness and true peak, beats, Whisper words with start/end, keyframe OCR, caption DOM boxes and the LAYA glance plus source audit of every screen.","key":"1","section":"guidance"}
M video "Observe before rendering with video.timeline (the composition and timeline as a Scene, judged with the video-edit predicates below), and after rendering with video.transcribe/video.judge: the one video judge (laya_video, vocabulary manuals/cl/laya-video.cl) measures shots, cuts, black and frozen runs, loudness and true peak, beats, Whisper words with start/end, keyframe OCR, caption DOM boxes and the LAYA glance plus source audit of every screen." src:"authored manual" state:verified
-- @record {"chapter":"video","data":"Run video.contracts on any render for the fast outcome contracts; video.contracts_proof shows each contract catching its defect on a fixture.","key":"2","section":"guidance"}
M video "Run video.contracts on any render for the fast outcome contracts; video.contracts_proof shows each contract catching its defect on a fixture." src:"authored manual" state:verified
-- @record {"chapter":"video","data":"video.improve runs the whole loop from a CL brief (laya_video.improve_cut): one named EDL fix per round through scene_core.improve, kept only on a strict finding reduction with no guarded metric regression, otherwise edl.json and the re-observed Scene are restored exactly; every outcome is an episode.","key":"3","section":"guidance"}
M video "video.improve runs the whole loop from a CL brief (laya_video.improve_cut): one named EDL fix per round through scene_core.improve, kept only on a strict finding reduction with no guarded metric regression, otherwise edl.json and the re-observed Scene are restored exactly; every outcome is an episode." src:"authored manual" state:verified
-- @record {"chapter":"video","data":"Credit: HyperFrames by HeyGen (Apache-2.0) is the renderer and Studio; Neyvia adapts it through its CLI and file format, without a fork. The tools, free-form EDL, pre-render checks, contracts and Whisper word timings were written on track/laya-video; the judge, cut EDL, store entries and launch loop on track/video; both were reconciled into this one stack on 7 Oct.","key":"4","section":"guidance"}
M video "Credit: HyperFrames by HeyGen (Apache-2.0) is the renderer and Studio; Neyvia adapts it through its CLI and file format, without a fork. The tools, free-form EDL, pre-render checks, contracts and Whisper word timings were written on track/laya-video; the judge, cut EDL, store entries and launch loop on track/video; both were reconciled into this one stack on 7 Oct." src:"authored manual" state:verified

-- @bug {"type": "edit-duration-off", "domain": "video-edit", "node": "composition", "predicate": {"field": "measurements.durationErrorS", "op": "gt", "value": 0.05}, "fix": "edl.fit-duration", "severity": "error", "means": "Timeline length differs from the brief."}
-- @bug {"type": "edit-aspect", "domain": "video-edit", "node": "composition", "predicate": {"field": "measurements.aspectOk", "op": "eq", "value": false}, "fix": "edl.set-canvas", "severity": "error", "means": "Canvas aspect differs from the brief."}
-- @bug {"type": "visual-gap", "domain": "video-edit", "node": "composition", "predicate": {"field": "measurements.gaps", "op": "nonempty"}, "fix": "edl.fill-gap", "severity": "error", "means": "No visual clip covers part of the timeline (it will render black)."}
-- @bug {"type": "caption-collision", "domain": "video-edit", "node": "clip-caption", "predicate": {"field": "measurements.collidesWith", "op": "nonempty"}, "fix": "edl.retime-caption", "severity": "error", "means": "Two captions are on screen at once."}
-- @bug {"type": "edit-caption-too-long", "domain": "video-edit", "node": "clip-caption", "predicate": {"field": "measurements.wordsOver", "op": "gt", "value": 0}, "fix": "edl.caption-shorten", "severity": "warning", "means": "Caption longer than the brief allows."}
-- @bug {"type": "edit-caption-too-fast", "domain": "video-edit", "node": "clip-caption", "predicate": {"field": "measurements.charsPerSecond", "op": "gt", "value": 17}, "fix": "edl.caption-readable", "severity": "warning", "means": "Caption shown too briefly to read."}
-- @bug {"type": "edit-stock-phrase", "domain": "video-edit", "node": "clip-caption", "predicate": {"field": "measurements.stockPhrase", "op": "eq", "value": true}, "fix": "edl.plain-copy", "severity": "warning", "means": "Template copy in a caption."}
-- @bug {"type": "edit-overrun", "domain": "video-edit", "node": "timeline-clip", "predicate": {"field": "measurements.overrunS", "op": "gt", "value": 0.01}, "fix": "edl.fit-duration", "severity": "error", "means": "A clip ends after the composition."}
-- @bug {"type": "edit-lint-error", "domain": "video-edit", "node": "lint", "predicate": {"field": "measurements.errors", "op": "gt", "value": 0}, "fix": "video.lint", "severity": "error", "means": "HyperFrames lint reports errors."}
