CL 1
L workspace v1 -- Authored executable manual
-- @manual {"chapters":{"files":{"title":"files"},"overview":{"title":"Scoped files, hashes, diffs, terminal and receipts"},"proofs-e-frontend":{"title":"PROOFS-e frontend action contracts"},"proofs-e-host":{"title":"Host behavior contracts and self-checks (PROOFS-e)"},"proofs-e-wz":{"title":"PROOFS-e W-Z: live contracts and scratch self-checks"},"terminal":{"title":"terminal"}},"clVersion":"1.1","id":"workspace","kind":"environment","proofs":{"area":"workspace","manifests":["config/proofs/proofs-e-frontend.json","config/proofs/proofs-e-host.json","config/proofs/workspace-journey.json"],"startup":{"procedures":["permissions.persist-transfer-and-isolate"],"runner":"scripts/proofs-e-frontend.mjs","scratchRootRequired":true}},"schema":"neyvia.manual.v1","schemas":{"neyvia.terminal.list":"t1","neyvia.terminal.read":"t2","runtime.environment":"t3","terminal.exec":"t4","workspace.read":"t5","workspace.search":"t6","workspace.write":"t7","neyvia.artifact.publish":"t19","neyvia.artifact.get":"t20","neyvia.artifact.list":"t21","neyvia.artifact.open":"t20"},"tool_metadata":{"neyvia.terminal.list":{"mutability_class":"read"},"neyvia.terminal.read":{"mutability_class":"read"},"runtime.environment":{"mutability_class":"read"},"terminal.exec":{"mutability_class":"external_action"},"workspace.read":{"mutability_class":"read"},"workspace.search":{"mutability_class":"read"},"workspace.write":{"mutability_class":"file_write"},"neyvia.artifact.publish":{"mutability_class":"none"},"neyvia.artifact.get":{"mutability_class":"read"},"neyvia.artifact.list":{"mutability_class":"read"},"neyvia.artifact.open":{"mutability_class":"none"}}}
-- @proof {"checkedAt":["grant_agent.action_receipts._safe_result"],"claim":"Native callback observations omit unapproved raw bodies and nested credential-bearing fields before persistence or replay","id":"proofs-e-host.action-sanitization","impact":["host state and observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.action_receipts.NativeActionStore.execute"],"claim":"First and replayed action outcomes are bound to the durable request and exact saved result; replay never invokes the completed effect","id":"proofs-e-host.action-once","impact":["host state and observations"],"phase":"invariant"}
-- @proof {"checkedAt":["grant_agent.web_backend._save_conversation_state","grant_agent.proofs_e_wz.check_conversation_save","grant_agent.proofs_e_wz.self_check","grant_agent.web_backend._save_conversation_state_locked","grant_agent.proofs_e_wz.check_conversation_persistence"],"claim":"A save preserves its selected normalized storage marker and active session identity and writes the exact returned state with chronologically ordered transcript turns while the save lock remains held. A receipt-only response reports persisted session/transcript counts without echoing transcripts; a full response returns normalized stored state.","id":"proofs-e-wz.conversation-save","impact":["cross-device chat state","save response size"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend._conversation_session_state","grant_agent.proofs_e_wz.check_conversation_session","grant_agent.proofs_e_wz.self_check"],"claim":"Session revisions bind only semantic session fields and the returned turn page. Equal revisions return compact notModified responses; changed or invalid revisions return the exact session/page with accurate counts.","id":"proofs-e-wz.conversation-revision","impact":["chat polling","lazy transcript loading","cross-device revisions"],"phase":"post"}
-- @proof {"checkedAt":["grant_agent.web_backend._conversation_state_bootstrap","grant_agent.proofs_e_wz.check_conversation_bootstrap","grant_agent.proofs_e_wz.self_check"],"claim":"Bootstrap returns the complete session/transcript index, only the selected bounded active turn tail, accurate projection counts and the existing lazy session-detail command.","id":"proofs-e-wz.conversation-bootstrap","impact":["index-first cross-device chat loading","bounded initial transfer"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:normalizeWorkspacePermissionMode -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.normalize","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.normalize","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.normalize"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.normalize","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:workspacePermissionAllowsTools -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.tools","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.tools","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.tools"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.tools","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:supportsNativeWorkspacePermissionModes -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.runtime","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.runtime","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.runtime"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.runtime","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:buildWorkspacePermissionScope -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.scope","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.scope","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.scope"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.scope","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:workspacePermissionGrantForScope -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.grant","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.grant","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.grant"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.grant","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:readWorkspacePermissionModes -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.read","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.read","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.read"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.read","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:writeWorkspacePermissionMode -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.write","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.write","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.write"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.write","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:workspacePermissionModeForScope -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.get","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.get","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.get"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.get","impact":["workspaceToolAccess"],"phase":"post"}
-- @proof {"checkedAt":["web/src/neyvia/workspaceToolAccess.js:transferDraftWorkspacePermissionMode -> checkedFrontendAction","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.transfer","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.transfer","web/src/neyvia/neyviaFrontendContracts.js:FRONTEND_CONTRACTS.permission.transfer"],"claim":"Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","id":"permission.transfer","impact":["workspaceToolAccess"],"phase":"post"}
T t1{..}
T t2 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"chars\":{\"type\":\"integer\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t3 json:"{\"type\":\"object\",\"properties\":{}}"
T t4{command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000 ..}
T t5 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"maxChars\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":100000},\"offset\":{\"type\":\"integer\",\"minimum\":0},\"startLine\":{\"type\":\"integer\",\"minimum\":1},\"endLine\":{\"type\":\"integer\",\"minimum\":1},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t6 json:"{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"},\"includeGlob\":{\"type\":\"string\"},\"maxResults\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":200}},\"required\":[\"query\"],\"allOf\":[{\"properties\":{\"query\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t7 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"minLength\":1},\"content\":{\"type\":\"string\"},\"expectedSha256\":{\"type\":\"string\",\"pattern\":\"^[a-fA-F0-9]{64}$\"}},\"required\":[\"path\",\"content\"],\"allOf\":[{\"properties\":{\"content\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t8{path:str}
T t9 json:"{\"type\":\"object\"}"
T t10{sha256:str ~"^[a-fA-F0-9]{64}$" content:str ..}
T t11{sha256:str ~"^[a-fA-F0-9]{64}$" ..}
T t12{path:str phrase:str}
T t13{path:str#1.. content:str#..20000}
T t14{query:str includeGlob:str}
T t15{path:str#1.. content:str ..}
T t16{}
T t17 json:"{\"properties\":{\"command\":{\"minLength\":1,\"type\":\"string\"},\"cwd\":{\"type\":\"string\"},\"maxOutputChars\":{\"maximum\":50000,\"minimum\":128,\"type\":\"integer\"},\"shell\":{\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"],\"type\":\"string\"},\"timeoutMs\":{\"maximum\":120000,\"minimum\":1,\"type\":\"integer\"}},\"required\":[\"command\",\"shell\",\"cwd\",\"timeoutMs\",\"maxOutputChars\"],\"type\":\"object\"}"
-- @proof {"checkedAt":["grant_agent.proofs_workspace_journey.self_check","grant_agent.native_tools.NativeToolRegistry._workspace_write","grant_agent.neyvia_workspace_tools.WorkspaceTools._call_unchecked","grant_agent.neyvia_outputs.publish","grant_agent.neyvia_outputs.listing","grant_agent.neyvia_outputs.get","grant_agent.neyvia_outputs.call","grant_agent.neyvia_panes.open_artifact","grant_agent.cl.renderer_effects.show","grant_agent.ui_command_bus.UICommandBus.since"],"claim":"Writing a real workspace report and publishing it keeps the exact bytes and provenance, retries with the same request are idempotent, and a previous publication refuses to open after the report changes.","id":"p22.workspace.output-journey","impact":["workspace report delivery","Outputs list and preview","workspace compare-and-swap write"],"phase":"post"}
T t18 json:"{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}"
T t19 json:"{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]},\"title\":{\"type\":\"string\"},\"sessionId\":{\"type\":\"string\"},\"runId\":{\"type\":\"string\"},\"requestId\":{\"type\":\"string\"},\"metadata\":{\"type\":\"object\"}},\"required\":[\"path\"],\"allOf\":[{\"properties\":{\"path\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t20 json:"{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}},\"required\":[\"id\"],\"allOf\":[{\"properties\":{\"id\":{\"not\":{\"enum\":[\"\"]}}}}]}"
T t21 json:"{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]},\"sessionId\":{\"type\":\"string\"},\"runId\":{\"type\":\"string\"},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":200},\"offset\":{\"type\":\"integer\",\"minimum\":0}},\"required\":[]}"
T t23{path:str requestId:str}
L workspace.files v1 -- files
-- @record {"chapter":"files","data":{"args":{"path":{"$input":"path"}},"inputs":{"$cl_type":"t8"},"shape":{"$cl_type":"t9"},"tool":"workspace.read"},"key":"current","section":"state"}
S workspace.current:json:"{\"type\":\"object\"}"=workspace.read(path:path)
-- @record {"chapter":"files","data":{"effect":"Return bounded decoded text and full-byte SHA-256; nextOffset paginates text","pre":"Nonblank existing text file resolves under root; no NUL in first 8192 bytes; offset >=0","returns":{"$cl_type":"t10"},"reversible":true,"schema":"workspace.read","tool":"workspace.read"},"key":"workspace.read","section":"actions"}
A workspace.read(path:str maxChars?:1..100000 offset?:0.. startLine?:1.. endLine?:1.. expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> {sha256:str ~"^[a-fA-F0-9]{64}$" content:str ..} -- Return bounded decoded text and full-byte SHA-256; nextOffset paginates text
C workspace.read has-text:workspace.read(path:path) .content has phrase
-- @record {"chapter":"files","data":{"effect":"Search actual workspace text; complete=false means deadline stopped traversal, not absence","pre":"Query string; includeGlob narrows workspace; bounded maxResults","returns":{"$cl_type":"t9"},"reversible":true,"schema":"workspace.search","tool":"workspace.search"},"key":"workspace.search","section":"actions"}
A workspace.search(query:str includeGlob?:str maxResults?:1..200) -> json:"{\"type\":\"object\"}" -- Search actual workspace text; complete=false means deadline stopped traversal, not absence
F verify-workspace-search "No authored observer check is bound to workspace.search" -> ask operator blocks:workspace.search
-- @record {"chapter":"files","data":{"effect":"Atomically create or CAS-replace text, create parents and verify persisted bytes; refuses concurrent overwrite","pre":"Allowed write scope; root-confined path with no symlink/junction; UTF-8 <=1 MiB no NUL; existing file requires matching expectedSha256; absent file must omit it","returns":{"$cl_type":"t11"},"reversible":false,"schema":"workspace.write","tool":"workspace.write"},"key":"workspace.write","section":"actions"}
A workspace.write(path:str#1.. content:str expectedSha256?:str ~"^[a-fA-F0-9]{64}$") -> {sha256:str ~"^[a-fA-F0-9]{64}$" ..} ! -- Atomically create or CAS-replace text, create parents and verify persisted bytes; refuses concurrent overwrite
C workspace.write written-text:workspace.read(path:path) .content == content
-- @record {"chapter":"files","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"contains","path":"content","value":{"$input":"phrase"}},"tool":"workspace.read"},"key":"has-text","section":"checks"}
C workspace.read has-text:workspace.read(path:path) .content has phrase
-- @record {"chapter":"files","data":{"args":{"path":{"$input":"path"}},"expect":{"op":"eq","path":"content","value":{"$input":"content"}},"tool":"workspace.read"},"key":"written-text","section":"checks"}
C workspace.read written-text:workspace.read(path:path) .content == content
-- @record {"chapter":"files","data":{"goal":"Read a named text artifact and verify the required phrase","inputs":{"$cl_type":"t12"},"steps":[{"action":"workspace.read","args":{"path":{"$input":"path"}},"check":"has-text","save":"file"}]},"key":"read-and-confirm","section":"procedures"}
P read-and-confirm(path:str phrase:str):file=workspace.read(path:path) C has-text -- Read a named text artifact and verify the required phrase
V P read-and-confirm -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"goal":"Review and CAS-replace a text edit up to 20000 characters, then verify the full bounded readback","inputs":{"$cl_type":"t13"},"steps":[{"action":"workspace.read","args":{"path":{"$input":"path"}},"save":"before"},{"judge":"replace"},{"action":"workspace.write","args":{"content":{"$input":"content"},"expectedSha256":{"$result":"before.sha256"},"path":{"$input":"path"}},"check":"written-text","save":"written","when":{"judge":"replace","option":"replace"}}]},"key":"replace-and-read","section":"procedures"}
P replace-and-read(path:str#1.. content:str#..20000):before=workspace.read(path:path); J replace=replace; written=workspace.write(content:content expectedSha256:before.sha256 path:path) C written-text -- Review and CAS-replace a text edit up to 20000 characters, then verify the full bounded readback
V P replace-and-read -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"goal":"Search text under a targeted glob and decide whether match coverage is sufficient","inputs":{"$cl_type":"t14"},"steps":[{"action":"workspace.search","args":{"includeGlob":{"$input":"includeGlob"},"query":{"$input":"query"}},"save":"matches"},{"judge":"search-coverage"}]},"key":"find-source","section":"procedures"}
P find-source(query:str includeGlob:str):matches=workspace.search(includeGlob:includeGlob query:query); J search-coverage -- Search text under a targeted glob and decide whether match coverage is sufficient
V P find-source -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"goal":"Verify the actual effect through fresh owning observers","inputs":{"$cl_type":"t15"},"steps":[{"action":"workspace.write","args":{"content":{"$input":"content"},"path":{"$input":"path"}},"save":"effect"}]},"key":"verify-effect-workspace-write","section":"procedures"}
P verify-effect-workspace-write(path:str#1.. content:str):effect=workspace.write(content:content path:path) -- Verify the actual effect through fresh owning observers
V P verify-effect-workspace-write -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"effect":"Publish the bytes already written in the selected workspace and record their hash and session provenance","pre":"An existing report beneath the selected workspace and a stable request id","returns":{"type":"object","properties":{"artifact":{"type":"object","properties":{"id":{"type":"string"}}}}},"reversible":true,"schema":"neyvia.artifact.publish","tool":"neyvia.artifact.publish"},"key":"artifact.publish","section":"actions"}
A neyvia.artifact.publish(path:str kind?:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" title?:str sessionId?:str runId?:str requestId?:str metadata?:json:"{\"type\":\"object\"}") -> json:"{\"type\":\"object\",\"properties\":{\"artifact\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"}}}}}" -- Publish the bytes already written in the selected workspace and record their hash and session provenance
C neyvia.artifact.publish artifact-available:neyvia.artifact.get(id:result.artifact.id) .availability == "available"
-- @record {"chapter":"files","data":{"effect":"Read the publication and check its exact current bytes","pre":"Known publication id","returns":{"type":"object"},"reversible":true,"schema":"neyvia.artifact.get","tool":"neyvia.artifact.get"},"key":"artifact.get","section":"actions"}
A neyvia.artifact.get(id:str) -> json:"{\"type\":\"object\"}" -- Read the publication and check its exact current bytes
C neyvia.artifact.get artifact-available:neyvia.artifact.get(id:published.artifact.id) .availability == "available"
-- @record {"chapter":"files","data":{"effect":"List published workspace outputs newest first with an optional session or run filter","pre":"Selected workspace and bounded page size","returns":{"type":"object"},"reversible":true,"schema":"neyvia.artifact.list","tool":"neyvia.artifact.list"},"key":"artifact.list","section":"actions"}
A neyvia.artifact.list(kind?:json:"{\"type\":\"string\",\"enum\":[\"file\",\"diff\",\"image\",\"report\",\"receipt\"]}" sessionId?:str runId?:str limit?:1..200 offset?:0..) -> json:"{\"type\":\"object\"}" -- List published workspace outputs newest first with an optional session or run filter
F verify-artifact-list "No authored observer check is bound to neyvia.artifact.list" -> ask operator blocks:neyvia.artifact.list
-- @record {"chapter":"files","data":{"effect":"Refuse changed or missing bytes before requesting the existing artifact pane","pre":"Known publication whose saved bytes are unchanged","returns":{"type":"object"},"reversible":true,"schema":"neyvia.artifact.open","tool":"neyvia.artifact.open"},"key":"artifact.open","section":"actions"}
A neyvia.artifact.open(id:str) -> json:"{\"type\":\"object\"}" -- Refuse changed or missing bytes before requesting the existing artifact pane
F verify-artifact-open "No authored observer check is bound to neyvia.artifact.open" -> ask operator blocks:neyvia.artifact.open
-- @record {"chapter":"files","data":{"args":{"id":{"$result":"published.artifact.id"}},"expect":{"op":"eq","path":"availability","value":"available"},"tool":"neyvia.artifact.get"},"key":"artifact-available","section":"checks"}
C neyvia.artifact.get artifact-available:neyvia.artifact.get(id:published.artifact.id) .availability == "available"
-- @record {"chapter":"files","data":{"goal":"Publish, read back and request a guarded report preview","inputs":{"$cl_type":"t23"},"steps":[{"action":"artifact.publish","args":{"kind":"report","path":{"$input":"path"},"requestId":{"$input":"requestId"}},"check":"artifact-available","save":"published"},{"action":"artifact.get","args":{"id":{"$result":"published.artifact.id"}},"check":"artifact-available","save":"confirmed"},{"action":"artifact.open","args":{"id":{"$result":"published.artifact.id"}},"save":"opened"}]},"key":"publish-and-open-workspace-report","section":"procedures"}
P publish-and-open-workspace-report(path:str requestId:str):published=neyvia.artifact.publish(kind:"report" path:path requestId:requestId) C artifact-available; confirmed=neyvia.artifact.get(id:published.artifact.id) C artifact-available; opened=neyvia.artifact.open(id:published.artifact.id) -- Publish, read back and request a guarded report preview
V P publish-and-open-workspace-report -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"goal":"Create a new bounded text artifact and verify its complete readback; existing files require a separately reviewed CAS edit","inputs":{"$cl_type":"t13"},"steps":[{"action":"workspace.write","args":{"content":{"$input":"content"},"path":{"$input":"path"}},"check":"written-text","save":"written"}]},"key":"create-and-read","section":"procedures"}
P create-and-read(path:str#1.. content:str#..20000):written=workspace.write(content:content path:path) C written-text -- Create a new bounded text artifact and verify its complete readback; existing files require a separately reviewed CAS edit
V P create-and-read -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"files","data":{"constraints":"Read full current bytes/hash first; expectedSha256 comes from that observation. Existing content is overwritten only after explicit review. Relative paths remain beneath root and no symlink/junction path is allowed.","options":["replace","leave"],"question":"Does the replacement preserve the intended source and concurrent changes?"},"key":"replace","section":"judge"}
J replace replace|leave:"Does the replacement preserve the intended source and concurrent changes?" -- Read full current bytes/hash first; expectedSha256 comes from that observation. Existing content is overwritten only after explicit review. Relative paths remain beneath root and no symlink/junction path is allowed.
V J replace -> human:operator why:"explicit choice required"
-- @record {"chapter":"files","data":{"constraints":"Only complete=true establishes coverage for searched glob; maxResults truncation and complete=false require narrower glob/query or direct known path. Do not paste entire files into context.","options":["use-matches","narrow"],"question":"Is this bounded search enough to identify the intended file?"},"key":"search-coverage","section":"judge"}
J search-coverage use-matches|narrow:"Is this bounded search enough to identify the intended file?" -- Only complete=true establishes coverage for searched glob; maxResults truncation and complete=false require narrower glob/query or direct known path. Do not paste entire files into context.
V J search-coverage -> human:operator why:"explicit choice required"
-- @record {"chapter":"files","data":{"failure":"Existing file refused without expectedSha256","recovery":"Read full-byte SHA-256, review changes and retry matching intent"},"key":"0","section":"pitfalls"}
X Existing file refused without expectedSha256 -> Read full-byte SHA-256, review changes and retry matching intent
-- @record {"chapter":"files","data":{"failure":"Hash mismatch during staging","recovery":"Reread and merge current source; do not reuse stale hash"},"key":"1","section":"pitfalls"}
X Hash mismatch during staging -> Reread and merge current source; do not reuse stale hash
-- @record {"chapter":"files","data":{"failure":"Read truncated or search incomplete","recovery":"Continue nextOffset or narrow includeGlob; a bounded result cannot prove global absence. Local-only search runs in-process before any child launch; regex timeout returns complete=false. Literal queries work without optional dependencies; complex regex requires the cl dependency."},"key":"2","section":"pitfalls"}
X Read truncated or search incomplete -> Continue nextOffset or narrow includeGlob; a bounded result cannot prove global absence. Local-only search runs in-process before any child launch; regex timeout returns complete=false. Literal queries work without optional dependencies; complex regex requires the cl dependency.
-- @record {"chapter":"files","data":{"failure":"Write traverses symlink/junction or escapes root","recovery":"Choose a plain root-confined path; no bypass"},"key":"3","section":"pitfalls"}
X Write traverses symlink/junction or escapes root -> Choose a plain root-confined path; no bypass
-- @record {"chapter":"files","data":{"failure":"NUL/binary or >1 MiB content","recovery":"Use file-specific tools; workspace.write is bounded UTF-8 text"},"key":"4","section":"pitfalls"}
X NUL/binary or >1 MiB content -> Use file-specific tools; workspace.write is bounded UTF-8 text
-- @record {"chapter":"files","data":{"failure":"Mutation result differs between native HTTP and durable MCP gateway","recovery":"Gateway wraps operation data under toolResult; this procedure verifies fresh workspace.read bytes instead of assuming a mutation return shape."},"key":"5","section":"pitfalls"}
X Mutation result differs between native HTTP and durable MCP gateway -> Gateway wraps operation data under toolResult; this procedure verifies fresh workspace.read bytes instead of assuming a mutation return shape.
-- @record {"chapter":"files","data":"Atomic compare-and-swap is not general merge resolution","key":"0","section":"frontier"}
F Atomic compare-and-swap is not general merge resolution
-- @record {"chapter":"files","data":"Binary writes and outside-root files are not mapped by workspace tools","key":"1","section":"frontier"}
F Binary writes and outside-root files are not mapped by workspace tools
-- @record {"chapter":"files","data":"Larger writes remain supported by workspace.write, but simple host goals and create-and-confirm are bounded to 20000 characters. Author an explicit observer G for larger writes; existing-file CAS and full-byte SHA-256 still apply.","key":"2","section":"frontier"}
F Larger writes remain supported by workspace.write, but simple host goals and create-and-confirm are bounded to 20000 characters. Author an explicit observer G for larger writes; existing-file CAS and full-byte SHA-256 still apply.
-- @record {"chapter":"files","data":"Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py.","key":"0","section":"guidance"}
M workspace "Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py." src:"authored manual" state:verified
-- @record {"chapter":"files","data":"Simple workspace.write calls up to 20000 characters receive host-authored persisted-hash G when no broader goal is authored. The host binds the requested UTF-8 hash; explicit done rereads it. Native grants, root confinement and existing-file CAS remain required. Author G for other mutations using the layer's read-only observer, then retry.","key":"1","section":"guidance"}
M workspace "Simple workspace.write calls up to 20000 characters receive host-authored persisted-hash G when no broader goal is authored. The host binds the requested UTF-8 hash; explicit done rereads it. Native grants, root confinement and existing-file CAS remain required. Author G for other mutations using the layer's read-only observer, then retry." src:"authored manual" state:verified
L workspace.overview v1 -- Scoped files, hashes, diffs, terminal and receipts
-- @record {"chapter":"overview","data":{"args":{},"inputs":{"$cl_type":"t16"},"shape":{"$cl_type":"t9"},"tool":"runtime.environment"},"key":"current","section":"state"}
S workspace.current:json:"{\"type\":\"object\"}"=runtime.environment()
-- @record {"chapter":"overview","data":{"effect":"Read actual OS/workspace/executable environment; no command execution","pre":"Local runtime probe available","returns":{"$cl_type":"t9"},"reversible":true,"schema":"runtime.environment","tool":"runtime.environment"},"key":"runtime.environment","section":"actions"}
A runtime.environment() -> json:"{\"type\":\"object\"}" -- Read actual OS/workspace/executable environment; no command execution
F verify-runtime-environment "No authored observer check is bound to runtime.environment" -> ask operator blocks:runtime.environment
-- @record {"chapter":"overview","data":{"goal":"Read real environment before choosing an available shell/interpreter","inputs":{"$cl_type":"t16"},"steps":[{"action":"runtime.environment","args":{},"save":"environment"},{"judge":"execution-environment"}]},"key":"choose-present-runtime","section":"procedures"}
P choose-present-runtime():environment=runtime.environment(); J execution-environment -- Read real environment before choosing an available shell/interpreter
V P choose-present-runtime -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"overview","data":{"constraints":"Read interpreter/shell availability; do not install tools or silently change runtime/provider. Selected root remains the write boundary.","options":["use-present","stop"],"question":"Does the available local environment support the requested command?"},"key":"execution-environment","section":"judge"}
J execution-environment use-present|stop:"Does the available local environment support the requested command?" -- Read interpreter/shell availability; do not install tools or silently change runtime/provider. Selected root remains the write boundary.
V J execution-environment -> human:operator why:"explicit choice required"
-- @record {"chapter":"overview","data":{"failure":"Runtime name inferred without probing","recovery":"Read runtime.environment; use actual executable and report missing dependency"},"key":"0","section":"pitfalls"}
X Runtime name inferred without probing -> Read runtime.environment; use actual executable and report missing dependency
-- @record {"chapter":"overview","data":"Network/remote runtime readiness and service health are separate from local environment probe","key":"0","section":"frontier"}
F Network/remote runtime readiness and service health are separate from local environment probe
-- @record {"chapter":"overview","data":"Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py.","key":"0","section":"guidance"}
M workspace "Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py." src:"authored manual" state:verified
L workspace.proofs-e-frontend v1 -- PROOFS-e frontend action contracts
-- @record {"chapter":"proofs-e-frontend","data":{"failure":"Host/backend or rendered behavior has not been inspected.","recovery":"Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers."},"key":"0","section":"pitfalls"}
X Host/backend or rendered behavior has not been inspected. -> Run the matching feature proof before claiming that boundary; frontend helper receipts prove only the called production helpers.
-- @record {"chapter":"proofs-e-frontend","data":"Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.","key":"0","section":"frontier"}
F Covered helper receipts enforce only the production actions declared by these contracts. UI geometry, browser authority, service-worker lifecycle, backend dispatch and mutation are retained case by case until their own real action contracts and receipts exist.
-- @record {"chapter":"proofs-e-frontend","data":"permission.normalize: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"0","section":"guidance"}
M workspace "permission.normalize: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.tools: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"1","section":"guidance"}
M workspace "permission.tools: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.runtime: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"2","section":"guidance"}
M workspace "permission.runtime: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.scope: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"3","section":"guidance"}
M workspace "permission.scope: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.grant: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"4","section":"guidance"}
M workspace "permission.grant: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.read: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"5","section":"guidance"}
M workspace "permission.read: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.write: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"6","section":"guidance"}
M workspace "permission.write: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.get: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"7","section":"guidance"}
M workspace "permission.get: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"permission.transfer: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy.","key":"8","section":"guidance"}
M workspace "permission.transfer: Permission aliases, scope identity, per-chat persistence and draft transfer preserve the documented permission policy." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json","key":"9","section":"guidance"}
M workspace "Self-check: node scripts/proofs-e-frontend.mjs --root <scratch directory> --json" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-frontend","data":"Startup procedures: permissions.persist-transfer-and-isolate","key":"10","section":"guidance"}
M workspace "Startup procedures: permissions.persist-transfer-and-isolate" src:"authored manual" state:verified
L workspace.proofs-e-host v1 -- Host behavior contracts and self-checks (PROOFS-e)
-- @record {"chapter":"proofs-e-host","data":{"failure":"A recorded prior action is mistaken for a new observation","recovery":"Reconcile the target and inspect its durable receipt before a separately identified action"},"key":"0","section":"pitfalls"}
X A recorded prior action is mistaken for a new observation -> Reconcile the target and inspect its durable receipt before a separately identified action
-- @record {"chapter":"proofs-e-host","data":"Native callback observations omit unapproved raw bodies and nested credential-bearing fields before persistence or replay","key":"0","section":"guidance"}
M workspace "Native callback observations omit unapproved raw bodies and nested credential-bearing fields before persistence or replay" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-host","data":"First and replayed action outcomes are bound to the durable request and exact saved result; replay never invokes the completed effect","key":"1","section":"guidance"}
M workspace "First and replayed action outcomes are bound to the durable request and exact saved result; replay never invokes the completed effect" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-host","data":"Self-check: neyvia verify --area proofs-e-host; real OS ownership, status-line process refresh, transitive pack and durable scratch file action.","key":"2","section":"guidance"}
M workspace "Self-check: neyvia verify --area proofs-e-host; real OS ownership, status-line process refresh, transitive pack and durable scratch file action." src:"authored manual" state:verified
L workspace.proofs-e-wz v1 -- PROOFS-e W-Z: live contracts and scratch self-checks
-- @record {"chapter":"proofs-e-wz","data":{"failure":"A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement","recovery":"Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion"},"key":"0","section":"pitfalls"}
X A local fixture is mistaken for a real provider, signed desktop release or whole-suite replacement -> Read the source-bound receipt, per-case coverage map and unresolved frontier before retirement or promotion
-- @record {"chapter":"proofs-e-wz","data":"Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.","key":"0","section":"frontier"}
F Backend suite and paired-desktop controller scenarios remain pending unless every original predicate has a real action site and observed scratch procedure.
-- @record {"chapter":"proofs-e-wz","data":"Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.","key":"1","section":"frontier"}
F Hidden-process AST scanner self-tests protect test-only tooling and are retained pending lead retirement review; no source-text scan is relabeled as production proof.
-- @record {"chapter":"proofs-e-wz","data":"Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.","key":"2","section":"frontier"}
F Legacy desktop-ui/fluxioHelpers.js is absent; its workspace-selection tests remain pending impact/history review.
-- @record {"chapter":"proofs-e-wz","data":"The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.","key":"3","section":"frontier"}
F The original bootstrap test expected newest merged turn first; its coverage row explicitly supersedes that stale assertion with observed chronological ordering, preserving all other bootstrap/lazy-detail predicates.
-- @record {"chapter":"proofs-e-wz","data":"Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz","key":"0","section":"guidance"}
M workspace "Self-check entry: grant_agent.proofs_e_wz.self_check; CLI: neyvia verify --root <workspace> --area proofs-e-wz" src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action.","key":"1","section":"guidance"}
M workspace "Manifest: config/proofs/proofs-e-wz.json; host sites enforce these contracts on every corresponding real action." src:"authored manual" state:verified
-- @record {"chapter":"proofs-e-wz","data":"Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection.","key":"2","section":"guidance"}
M workspace "Fixtures use disposable SQLite stores, real owned Python child commands, localhost HTTP port 48503 and bounded source transport injection." src:"authored manual" state:verified
L workspace.terminal v1 -- terminal
-- @record {"chapter":"terminal","data":{"args":{},"inputs":{"$cl_type":"t16"},"shape":{"$cl_type":"t9"},"tool":"runtime.environment"},"key":"current","section":"state"}
S workspace.current:json:"{\"type\":\"object\"}"=runtime.environment()
-- @record {"chapter":"terminal","data":{"effect":"Read actual OS/workspace/executable environment; no command execution","pre":"Local runtime probe available","returns":{"$cl_type":"t9"},"reversible":true,"schema":"runtime.environment","tool":"runtime.environment"},"key":"runtime.environment","section":"actions"}
A runtime.environment() -> json:"{\"type\":\"object\"}" -- Read actual OS/workspace/executable environment; no command execution
F verify-runtime-environment "No authored observer check is bound to runtime.environment" -> ask operator blocks:runtime.environment
-- @record {"chapter":"terminal","data":{"effect":"Run local command with bounded timeout/output and return exit result; can mutate local files","pre":"External-action permission/approval; valid shell and cwd; nonempty command; timeoutMs 1–120000","returns":{"$cl_type":"t9"},"reversible":false,"schema":"terminal.exec","tool":"terminal.exec"},"key":"terminal.exec","section":"actions"}
A terminal.exec(command:str#1.. shell?:json:"{\"type\":\"string\",\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"]}" cwd?:str timeoutMs?:1..120000 maxOutputChars?:128..50000) -> json:"{\"type\":\"object\"}" ! -- Run local command with bounded timeout/output and return exit result; can mutate local files
C terminal.exec terminal-bytes:workspace.read(path:"manual-terminal-proof.txt") .content == "manual terminal returned 739"
C terminal.exec uifix2-1:workspace.read(path:"scripts/evidence/UIFIX2-1.json") .content has "\"passed\": true"
C terminal.exec uifix2-2:workspace.read(path:"scripts/evidence/UIFIX2-2.json") .content has "\"passed\": true"
C terminal.exec uifix2-3:workspace.read(path:"scripts/evidence/UIFIX2-3.json") .content has "\"passed\": true"
C terminal.exec uifix2-4:workspace.read(path:"scripts/evidence/UIFIX2-4.json") .content has "\"passed\": true"
C terminal.exec uifix2-5:workspace.read(path:"scripts/evidence/UIFIX2-5.json") .content has "\"passed\": true"
C terminal.exec uifix2-6:workspace.read(path:"scripts/evidence/UIFIX2-6.json") .content has "\"passed\": true"
C terminal.exec uifix2-7:workspace.read(path:"scripts/evidence/UIFIX2-7.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"effect":"Read open terminal IDs, folders, shell, alive state and last output time","pre":"Selected workspace terminal store is readable","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.terminal.list","tool":"neyvia.terminal.list"},"key":"terminal.list","section":"actions"}
A neyvia.terminal.list() -> json:"{\"type\":\"object\"}" -- Read open terminal IDs, folders, shell, alive state and last output time
F verify-terminal-list "No authored observer check is bound to neyvia.terminal.list" -> ask operator blocks:neyvia.terminal.list
-- @record {"chapter":"terminal","data":{"effect":"Read recent plain text output from that terminal without starting or typing into it","pre":"Existing terminal ID from terminal.list; chars bounds the requested tail","returns":{"$cl_type":"t9"},"reversible":true,"schema":"neyvia.terminal.read","tool":"neyvia.terminal.read"},"key":"terminal.read","section":"actions"}
A neyvia.terminal.read(id:str chars?:int) -> json:"{\"type\":\"object\"}" -- Read recent plain text output from that terminal without starting or typing into it
F verify-terminal-read "No authored observer check is bound to neyvia.terminal.read" -> ask operator blocks:neyvia.terminal.read
-- @record {"chapter":"terminal","data":{"args":{"path":"manual-terminal-proof.txt"},"expect":{"op":"eq","path":"content","value":"manual terminal returned 739"},"tool":"workspace.read"},"key":"terminal-bytes","section":"checks"}
C workspace.read terminal-bytes:workspace.read(path:"manual-terminal-proof.txt") .content == "manual terminal returned 739"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-1.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-1","section":"checks"}
C workspace.read uifix2-1:workspace.read(path:"scripts/evidence/UIFIX2-1.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-2.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-2","section":"checks"}
C workspace.read uifix2-2:workspace.read(path:"scripts/evidence/UIFIX2-2.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-3.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-3","section":"checks"}
C workspace.read uifix2-3:workspace.read(path:"scripts/evidence/UIFIX2-3.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-4.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-4","section":"checks"}
C workspace.read uifix2-4:workspace.read(path:"scripts/evidence/UIFIX2-4.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-5.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-5","section":"checks"}
C workspace.read uifix2-5:workspace.read(path:"scripts/evidence/UIFIX2-5.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-6.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-6","section":"checks"}
C workspace.read uifix2-6:workspace.read(path:"scripts/evidence/UIFIX2-6.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"args":{"path":"scripts/evidence/UIFIX2-7.json"},"expect":{"op":"contains","path":"content","value":"\"passed\": true"},"tool":"workspace.read"},"key":"uifix2-7","section":"checks"}
C workspace.read uifix2-7:workspace.read(path:"scripts/evidence/UIFIX2-7.json") .content has "\"passed\": true"
-- @record {"chapter":"terminal","data":{"goal":"Run fixed local Python in the selected scratch root and reread its artifact","inputs":{"$cl_type":"t16"},"steps":[{"action":"runtime.environment","args":{},"save":"environment"},{"judge":"command-scope"},{"action":"terminal.exec","args":{"command":"from pathlib import Path; Path('manual-terminal-proof.txt').write_text('manual terminal returned 739', encoding='utf-8')","shell":"python"},"check":"terminal-bytes","save":"command","when":{"judge":"command-scope","option":"run"}}]},"key":"prove-terminal","section":"procedures"}
P prove-terminal():environment=runtime.environment(); J command-scope=run; command=terminal.exec(command:"from pathlib import Path; Path('manual-terminal-proof.txt').write_text('manual terminal returned 739', encoding='utf-8')" shell:"python") C terminal-bytes -- Run fixed local Python in the selected scratch root and reread its artifact
V P prove-terminal -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"Execute one explicitly permitted bounded local command; fresh command completion and authored observer G must both pass","inputs":{"$cl_type":"t17"},"steps":[{"action":"terminal.exec","args":{"command":{"$input":"command"},"cwd":{"$input":"cwd"},"maxOutputChars":{"$input":"maxOutputChars"},"shell":{"$input":"shell"},"timeoutMs":{"$input":"timeoutMs"}},"save":"execution"}]},"key":"execute-scoped-command","section":"procedures"}
P execute-scoped-command(command:str#1.. cwd:str maxOutputChars:128..50000 shell:json:"{\"enum\":[\"auto\",\"powershell\",\"python\",\"bash\",\"cmd\"],\"type\":\"string\"}" timeoutMs:1..120000):execution=terminal.exec(command:command cwd:cwd maxOutputChars:maxOutputChars shell:shell timeoutMs:timeoutMs) -- Execute one explicitly permitted bounded local command; fresh command completion and authored observer G must both pass
V P execute-scoped-command -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"PDFs open where module workers don't, and are named by their file, never an encoded route.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](1))","shell":"python","timeoutMs":120000},"check":"uifix2-1","save":"receipt"}]},"key":"uifix2-1","section":"procedures"}
P uifix2-1():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](1))" shell:"python" timeoutMs:120000) C uifix2-1 -- PDFs open where module workers don't, and are named by their file, never an encoded route.
V P uifix2-1 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"The screen-control helper is found in a shared per-user runtime, and its absence reads plainly.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](2))","shell":"python","timeoutMs":120000},"check":"uifix2-2","save":"receipt"}]},"key":"uifix2-2","section":"procedures"}
P uifix2-2():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](2))" shell:"python" timeoutMs:120000) C uifix2-2 -- The screen-control helper is found in a shared per-user runtime, and its absence reads plainly.
V P uifix2-2 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"A chat source that can't be read becomes one plain line; raw errors stay in the tooltip.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](3))","shell":"python","timeoutMs":120000},"check":"uifix2-3","save":"receipt"}]},"key":"uifix2-3","section":"procedures"}
P uifix2-3():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](3))" shell:"python" timeoutMs:120000) C uifix2-3 -- A chat source that can't be read becomes one plain line; raw errors stay in the tooltip.
V P uifix2-3 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"Game Dev sessions are named in words and a reloaded Browser 3D scene stays selected.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](4))","shell":"python","timeoutMs":120000},"check":"uifix2-4","save":"receipt"}]},"key":"uifix2-4","section":"procedures"}
P uifix2-4():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](4))" shell:"python" timeoutMs:120000) C uifix2-4 -- Game Dev sessions are named in words and a reloaded Browser 3D scene stays selected.
V P uifix2-4 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"The tour proves state survives moves without typing fixture text into real fields.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](5))","shell":"python","timeoutMs":120000},"check":"uifix2-5","save":"receipt"}]},"key":"uifix2-5","section":"procedures"}
P uifix2-5():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](5))" shell:"python" timeoutMs:120000) C uifix2-5 -- The tour proves state survives moves without typing fixture text into real fields.
V P uifix2-5 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"No card over the App preview sample; prose fields wrap; CiteCraft hides internal ids.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](6))","shell":"python","timeoutMs":120000},"check":"uifix2-6","save":"receipt"}]},"key":"uifix2-6","section":"procedures"}
P uifix2-6():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](6))" shell:"python" timeoutMs:120000) C uifix2-6 -- No card over the App preview sample; prose fields wrap; CiteCraft hides internal ids.
V P uifix2-6 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"goal":"Library and Marketplace \"Open here\" open a real surface in the single shell; the audit reads that shell.","inputs":{"$cl_type":"t18"},"steps":[{"action":"terminal.exec","args":{"command":"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](7))","shell":"python","timeoutMs":120000},"check":"uifix2-7","save":"receipt"}]},"key":"uifix2-7","section":"procedures"}
P uifix2-7():receipt=terminal.exec(command:"import runpy; print(runpy.run_path('scripts/uifix2_contracts.py')['run'](7))" shell:"python" timeoutMs:120000) C uifix2-7 -- Library and Marketplace "Open here" open a real surface in the single shell; the audit reads that shell.
V P uifix2-7 -> script why:"typed manual runner; stops at every judgement"
-- @record {"chapter":"terminal","data":{"constraints":"This command writes only manual-terminal-proof.txt beneath selected cwd; Full access/explicit terminal approval is required. It is an artifact proof, not arbitrary-command authorization.","options":["run","leave"],"question":"Run the fixed scratch artifact command with existing external-action authority?"},"key":"command-scope","section":"judge"}
J command-scope run|leave:"Run the fixed scratch artifact command with existing external-action authority?" -- This command writes only manual-terminal-proof.txt beneath selected cwd; Full access/explicit terminal approval is required. It is an artifact proof, not arbitrary-command authorization.
V J command-scope -> human:operator why:"explicit choice required"
-- @record {"chapter":"terminal","data":{"failure":"Command started but timed out or output was truncated","recovery":"Inspect returned exit status and actual artifact; a process start is not completion"},"key":"0","section":"pitfalls"}
X Command started but timed out or output was truncated -> Inspect returned exit status and actual artifact; a process start is not completion
-- @record {"chapter":"terminal","data":{"failure":"External-action denied in workspace mode","recovery":"Request proper existing approval/scope; manual.run must not bypass gateway"},"key":"1","section":"pitfalls"}
X External-action denied in workspace mode -> Request proper existing approval/scope; manual.run must not bypass gateway
-- @record {"chapter":"terminal","data":"Long-job orchestration beyond 120-second terminal call requires a job API","key":"0","section":"frontier"}
F Long-job orchestration beyond 120-second terminal call requires a job API
-- @record {"chapter":"terminal","data":"No guarantee arbitrary shells have matching environment/dependencies","key":"1","section":"frontier"}
F No guarantee arbitrary shells have matching environment/dependencies
-- @record {"chapter":"terminal","data":"Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py.","key":"0","section":"guidance"}
M workspace "Source: src/grant_agent/native_tools.py (_workspace_read/_write/_search), native_commands.py and gateway permission guards; tests/test_native_tools.py." src:"authored manual" state:verified
