'use strict';
const fs=require('node:fs');const port=Number(process.argv[2]),out=process.argv[3];
if(port<48721||port>48729||!out||fs.existsSync(out))throw Error('Explicit assigned port and fresh receipt required');
const base=`http://127.0.0.1:${port}`,report={schema:'neyvia.C2f.routine-laya@1',startedAt:new Date().toISOString(),calls:[],paidModelCostUSD:0,tokens:0};let cookie,tab;
async function call(op,args={}){const t=performance.now();const r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)});const v=await r.json();report.calls.push({op,ms:performance.now()-t,ok:v.ok});if(!r.ok||v.ok===false)throw Error(JSON.stringify(v));return v;}
(async()=>{const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});cookie=r.headers.get('set-cookie').split(';')[0];report.healthBefore=await(await fetch('http://127.0.0.1:48724/v1/health')).json();tab=(await call('tab.open',{url:'https://docs.python.org/3/library/json.html',engine:'obscura'})).tabId;const o=await call('observe',{tabId:tab});
report.decision=await call('decide',{tabId:tab,question:'calibrated_advisory',context:{goal:'Choose the observed page topic.',decision_profile:'public_observed_fields@1',advisory_field:'title',options:[{id:'a',description:o.title},{id:'b',description:'An unrelated password reset page'}]}});
report.branch=report.decision.accepted_decision==='a'&&report.decision.decision_policy?.postcheck_passed?'read_result':'escalate';if(report.branch==='read_result')report.result={title:o.title,url:o.url,readiness:o.readyState};report.healthAfter=await(await fetch('http://127.0.0.1:48724/v1/health')).json();report.ok=report.branch==='read_result'&&report.healthAfter.requests_measured>report.healthBefore.requests_measured;
})().catch(e=>{report.error=e.stack;report.ok=false;process.exitCode=1;}).finally(async()=>{if(tab)await call('tab.close',{tabId:tab}).catch(e=>report.closeError=e.message);report.finishedAt=new Date().toISOString();fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:report.ok,branch:report.branch,decision:report.decision?.decision_policy,error:report.error}));});
