/* Causal loader proof: fast dependency survives a pending optional response. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const repo=path.resolve(__dirname,'..'),backendPort=48726,fixturePort=48727,enginePort=48728,base='http://127.0.0.1:'+backendPort;
const candidate=process.argv[2],out=process.argv[3];if(!candidate||!out||fs.existsSync(out))throw Error('Explicit fork executable and fresh receipt required');
const official=JSON.parse(fs.readFileSync('scripts/evidence/C2f-engine-upstream-v024-admission.json')).engineBinary.path;
const report={schema:'neyvia.C2f.engine-fetch-causality@1',ports:[backendPort,fixturePort,enginePort],at:new Date().toISOString(),mechanism:'Controlled pending external-script body; retain completed fast dependency under unchanged total deadline',stealth:false,runs:[],checks:[]};
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
let fixture,backend,cookie,root;const sockets=new Set();
async function call(op,args={}){const start=performance.now(),res=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)}),v=await res.json();report.runs.at(-1).calls.push({op,args,http:res.status,ms:performance.now()-start,result:v});save();if(!res.ok||v.ok===false)throw Error(JSON.stringify(v));return v;}
async function launch(executable){root=path.join(repo,'.agent_control/proofs/C2f/engine-fetch-'+crypto.randomUUID());fs.mkdirSync(path.join(root,'config'),{recursive:true});fs.writeFileSync(path.join(root,'config/neyvia_browser_authority.json'),JSON.stringify({schema:'neyvia.browser-authority.v1',proofPorts:report.ports}));
 const env={...process.env,PYTHONPATH:path.join(repo,'src'),PYTHONDONTWRITEBYTECODE:'1',NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_OBSCURA_EXE:executable,NEYVIA_WEB_PORT:String(backendPort),FLUXIO_WEB_PORT:String(backendPort),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_BASE:base,NEYVIA_CONNECTED_SERVICE_PORT:String(backendPort),NEYVIA_BROWSER_PROOF_PORTS:report.ports.join(','),NEYVIA_BROWSER_PROOF_SCOPE:'C2',NEYVIA_BROWSER_PROOF_ROOT:root,NEYVIA_TOOL_AUTO_UPDATE:'0',FLUXIO_RUNTIME_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',FLUXIO_LOCAL_SESSION_BOOTSTRAP:'1',NEYVIA_LAYA_URL:'http://127.0.0.1:48724'};
 const fd=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(backendPort),'--root',root,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',fd,fd]});fs.closeSync(fd);
 const end=performance.now()+60000;let ready=false;while(performance.now()<end){if(backend.exitCode!==null)throw Error('Owned proof backend exited');try{ready=(await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{}if(ready)break;await new Promise(r=>setTimeout(r,100));}if(!ready)throw Error('Owned backend readiness deadline');
 const res=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!res.ok)throw Error('Local session bootstrap failed');cookie=res.headers.get('set-cookie').split(';')[0];await call('headless.start',{port:enginePort,allowLocalFixtures:true});
}
async function halt(){if(!backend)return;try{await call('headless.stop');}finally{const exited=new Promise(resolve=>backend.once('exit',resolve));backend.kill();await Promise.race([exited,new Promise((_,reject)=>setTimeout(()=>reject(Error('Owned backend exit deadline')),10000))]);backend=null;cookie=null;}}
async function run(name,executable){const file=path.resolve(executable);if(!file.startsWith(path.join(repo,'.agent_control',path.sep)))throw Error('Task runtime boundary');const start=performance.now(),row={name,executable:path.relative(repo,file),sha256:sha(file),workerSha256:sha(path.join(path.dirname(file),'obscura-worker.exe')),calls:[]};report.runs.push(row);await launch(file);const tabId=(await call('tab.open',{url:'http://127.0.0.1:'+fixturePort+'/'+name,engine:'obscura'})).tabId;const observation=(await call('observe',{tabId}));row.fastDependencyExecuted=observation.text.includes('FAST_DEPENDENCY_EXECUTED');row.observation=observation;row.root=path.relative(repo,root);row.elapsedMs=performance.now()-start;await call('tab.close',{tabId});await halt();const log=path.join(root,'.neyvia/browser/obscura/engine.log');row.engineLog=path.relative(repo,log);row.engineLogSha256=sha(log);row.fetchDiagnostic=fs.readFileSync(log,'utf8').split(/\r?\n/).filter(line=>/fetch budget|fetch deadline|retaining completed|deadline reached/.test(line));save();}
(async()=>{fixture=http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url.startsWith('/fast.js')){res.setHeader('Content-Type','application/javascript');res.end("document.getElementById('proof').textContent='FAST_DEPENDENCY_EXECUTED';");}else if(req.url.startsWith('/slow.js')){res.setHeader('Content-Type','application/javascript');res.writeHead(200);res.write('// Deliberately pending controlled response; no timer or hidden success.\n');}else{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><title>Controlled loader deadline</title></head><body><h1 id="proof">Fast dependency not executed</h1><script defer src="/fast.js"></script><script defer src="/slow.js"></script></body></html>');}});fixture.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));});await new Promise((resolve,reject)=>{fixture.once('error',reject);fixture.listen(fixturePort,'127.0.0.1',resolve);});await run('official-v024',official);await run('retention-fork',candidate);report.checks=[{name:'Original deadline discards completed dependency',ok:report.runs[0].fastDependencyExecuted===false},{name:'Fork retains and executes actual fast dependency',ok:report.runs[1].fastDependencyExecuted===true},{name:'Fork logs explicit retained completed fetch diagnosis',ok:report.runs[1].fetchDiagnostic.some(line=>line.includes('retaining completed scripts'))}];report.ok=report.checks.every(c=>c.ok);if(!report.ok)process.exitCode=1;})().catch(error=>{report.ok=false;report.error=error.stack;process.exitCode=1;}).finally(async()=>{try{await halt();}catch(error){report.cleanupError=error.message;}for(const socket of sockets)socket.destroy();if(fixture)await new Promise(resolve=>fixture.close(resolve));report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify({ok:report.ok,checks:report.checks,error:report.error}));});
