// One measured end-to-end task: cold manual admission, then parameterized replay.
'use strict';
const fs=require('node:fs'), crypto=require('node:crypto');
const port=Number(process.argv[2]);if(!Number.isInteger(port)||port<48721||port>48729)throw Error('Explicit assigned backend port required');
const base=`http://127.0.0.1:${port}`, out=process.argv[3];if(!out||fs.existsSync(out)||['quantum computing','decision trees'].some(word=>fs.existsSync(out.replace(/\.json$/,'')+'-'+word+'.json')))throw Error('Fresh receipt and observation paths required');
const report={schema:'neyvia.C2f.profile@1',startedAt:new Date().toISOString(),port,calls:[],tasks:[],model:{calls:0,inputTokens:0,outputTokens:0,reasoningTokens:0,paidModelCostUSD:0},fixedSleeps:0};
let cookie;
function save(){fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');}
async function call(op,args={}){const start=performance.now(),row={op,args,at:new Date().toISOString()};report.calls.push(row);try{const r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)});const value=await r.json();row.ok=value.ok;row.status=r.status;row.error=value.error;if(!r.ok||value.ok===false){const e=Error(JSON.stringify(value));e.value=value;throw e;}return value;}catch(e){row.error=e.message;throw e;}finally{row.ms=performance.now()-start;save();}}
async function task(word,mode){const started=performance.now(),row={word,mode,callsBegin:report.calls.length};report.tasks.push(row);let tab;
 try{tab=(await call('tab.open',{url:'https://arxiv.org/',engine:'obscura'})).tabId;await call('tab.grant',{tabId:tab,enabled:true});let result;
 let m=await call('site.manual',{tabId:tab});let p=m.procedures.find(p=>p.kind==='search-first'&&p.steps.length===2);
 if(!p){const links=m.observation.elements.filter(e=>e.role==='link'&&e.name==='Search'&&e.href&&!e.secret);if(links.length!==1)throw Error('No unique observed search page');const previous=tab;tab=(await call('tab.open',{url:links[0].href,engine:'obscura'})).tabId;await call('tab.grant',{tabId:tab,enabled:true});await call('tab.close',{tabId:previous});m=await call('site.manual',{tabId:tab});p=m.procedures.find(p=>p.kind==='search-first'&&p.steps.length===2);}
 if(!p)throw Error('No uniquely observed search procedure');
 if(mode==='learn'){const steps=p.steps.map(s=>({...s,...(s.action==='submit'?{expect:{path:'/text',contains:'Showing'}}:{})}));result=await call('script.learn',{tabId:tab,name:'arxiv-search',inputs:{query:word},steps,checks:[{path:'/url',contains:'/search/'},{path:'/text',contains:'Showing'},{path:'/text',contains:{$input:'query'}}]});}
 else result=await call('script.run',{tabId:tab,name:'arxiv-search',inputs:{query:word}});
 row.result={status:result.status,tokens:result.tokens,modelCalls:result.modelCalls,durationMs:result.durationMs,earlyExit:result.earlyExit,verification:result.verification,receipts:result.receipts};
 const obs=result.observation;const bytes=JSON.stringify(obs)+'\n',observationPath=out.replace(/\.json$/,'')+'-'+word+'.json';fs.writeFileSync(observationPath,bytes,{flag:"wx"});row.observation={path:observationPath,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};
 row.success=result.verification.verified&&obs.text.includes('Submitted');row.answerExcerpt=obs.text.slice(0,8000);
 }catch(e){row.success=false;row.error=e.message;}finally{row.elapsedMs=performance.now()-started;row.browserCallMs=report.calls.slice(row.callsBegin).reduce((a,c)=>a+c.ms,0);row.executorMs=row.elapsedMs-row.browserCallMs;row.pageLoadMs=report.calls.slice(row.callsBegin).filter(c=>c.op==='tab.open').reduce((a,c)=>a+c.ms,0);row.modelMs=0;row.fixedWaitMs=0;row.retries=0;if(tab)await call('tab.close',{tabId:tab}).catch(e=>row.closeError=e.message);save();}}
(async()=>{const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});cookie=r.headers.get('set-cookie').split(';')[0];await task('quantum computing','learn');if(report.tasks[0].success)await task('decision trees','run');report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify(report.tasks.map(t=>({word:t.word,success:t.success,elapsedMs:t.elapsedMs,error:t.error}))));})().catch(e=>{report.fatal=e.stack;save();process.exitCode=1;console.error(e.message);});
