/* Owned headless runtime and actual React right-pane controls; no desktop GUI. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');
const repo=path.resolve(__dirname,'..'),base='http://127.0.0.1:48726',ports=[48726,48727,48728,48729];
const root=path.join(repo,'.agent_control/proofs/C2f/pane-'+crypto.randomUUID());
const report={schema:'neyvia.C2f.pane-proof@1',ports,root:path.relative(repo,root),checks:[],calls:[]};
report.engineAdmission=JSON.parse(fs.readFileSync(path.join(repo,'scripts/evidence/C2f-engine-admission.json')));
let backend,vite,fixture,browser,proofPage,cookie='';
const env={...process.env,PYTHONPATH:path.join(repo,'src'),PYTHONDONTWRITEBYTECODE:'1',NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_WEB_PORT:'48726',FLUXIO_WEB_PORT:'48726',NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_BASE:base,NEYVIA_CONNECTED_SERVICE_PORT:'48726',NEYVIA_BROWSER_PROOF_PORTS:ports.join(','),NEYVIA_BROWSER_PROOF_SCOPE:'C2',NEYVIA_BROWSER_PROOF_ROOT:root,NEYVIA_TOOL_AUTO_UPDATE:'0',FLUXIO_RUNTIME_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',FLUXIO_LOCAL_SESSION_BOOTSTRAP:'1',FLUXIO_WEB_BACKEND_URL:base,NEYVIA_LAYA_URL:'http://127.0.0.1:48724'};
delete env.NEYVIA_OBSCURA_EXE;
fs.mkdirSync(path.join(root,'config'),{recursive:true});
fs.writeFileSync(path.join(root,'config/neyvia_browser_authority.json'),JSON.stringify({schema:'neyvia.browser-authority.v1',proofPorts:ports}));
const check=(name,ok,detail)=>{report.checks.push({name,ok:!!ok,detail});if(!ok)throw Error(name)};
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const data=await r.json();report.calls.push({url:new URL(url).pathname,op:body.op||body.tool,status:r.status,data});return data;}
const call=(op,args={})=>post(base+'/api/ui/browser',{op,args});
const tool=async(name,args={})=>{const value=await post(base+'/api/ui/tools/call',{tool:'neyvia.'+name,arguments:args});return value.data?.result||value.result||value;};
async function ready(url,proc){const end=Date.now()+60000;while(Date.now()<end){if(proc.exitCode!==null)throw Error('Process exited');try{if((await fetch(url,{signal:AbortSignal.timeout(1000)})).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Readiness timeout');}
function launch(exe,args,file){const log=fs.openSync(path.join(root,file),'a'),proc=spawn(exe,args,{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);return proc;}
async function main(){
 backend=launch('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port','48726','--root',root,'--skip-runtime-auto-update','--skip-proof-self-check'],'backend.log');await ready(base+'/api/health',backend);
 const login=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});check('local task owner session',login.ok);cookie=login.headers.get('set-cookie').split(';')[0];
 fixture=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.end('<!doctype html><title>Pane fixture</title><label>Record<input id="record" aria-label="Record"></label><button onclick="document.getElementById(\'result\').textContent=\'Saved: \'+document.getElementById(\'record\').value">Save record</button><p id="result">Ready</p><canvas id="motion" width="120" height="40"></canvas><script>let n=0,c=document.getElementById("motion").getContext("2d");setInterval(()=>{c.clearRect(0,0,120,40);c.fillText(String(++n),10,20)},100)</script>');});await new Promise(r=>fixture.listen(48729,'127.0.0.1',r));
 const started=await call('headless.start',{port:48728,allowLocalFixtures:true});check('managed admitted engine starts without exe config',started.ok&&started.stealth===false&&started.port===48728);
 const opened=await call('tab.open',{url:'http://127.0.0.1:48729/',engine:'obscura'});check('real headless page opened',opened.ok);const tabId=opened.tabId;
 const shown=await tool('pane.show',{kind:'browser',target:tabId});check('pane queued before mount',(shown.result||shown).verified===false);
 const before=await tool('pane.state');check('renderer absent remains unverified',!(before.result||before).verified);
 const stale=await call('pane.ack',{tabId,sessionId:started.sessionId,revision:'stale'});check('stale renderer ack refused',stale.ok===false&&stale.error.code==='stale_projection');
 const frame=await call('frame',{tabId});check('real frame delivered',frame.ok&&frame.dataUrl?.startsWith('data:image/png;base64,'));
 const frameBytes=Buffer.from(frame.dataUrl.split(',')[1],'base64'),framePath='scripts/evidence/C2f-headless-frame.png';fs.writeFileSync(path.join(repo,framePath),frameBytes);delete frame.dataUrl;Object.assign(frame,{path:framePath,bytes:frameBytes.length,sha256:crypto.createHash('sha256').update(frameBytes).digest('hex')});report.frame=frame;
 const htmlPath=path.join(root,'pane.html');
 // Vite resolves bare React imports through the existing dependency junction, without writing there.
 const entryPath=path.join(root,'pane-entry.jsx');fs.writeFileSync(entryPath,`import React from 'react';import{createRoot}from'react-dom/client';import{NxShell}from'/src/neyvia/next/NxShell.jsx';createRoot(document.getElementById('root')).render(React.createElement(NxShell));`);
 fs.writeFileSync(htmlPath,`<!doctype html><body style="margin:0"><div id="root" class="nx" data-theme="forest" style="height:100vh"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/@fs/${entryPath.replaceAll('\\','/')}"></script>`);
 const config=path.join(root,'vite.config.mjs'),relative=path.relative(root,repo).replaceAll('\\','/');fs.writeFileSync(config,`import config from '${relative}/vite.config.mjs';import{resolve}from'node:path';export default env=>({...config(env),cacheDir:resolve(${JSON.stringify(path.join(repo,'.agent_control/C2f/pane-deps/node_modules/.vite'))})});`);
 vite=launch(process.execPath,[path.join(repo,'node_modules/vite/bin/vite.js'),'--config',config,'--configLoader','runner','--port','48727','--strictPort'],'vite.log');await ready('http://127.0.0.1:48727/',vite);
 const {chromium}=require('playwright');browser=await chromium.launch({headless:true});const context=await browser.newContext();const sep=cookie.indexOf('=');await context.addCookies([{name:cookie.slice(0,sep),value:cookie.slice(sep+1),domain:'127.0.0.1',path:'/'}]);
 const page=proofPage=await context.newPage();report.pageErrors=[];report.requestFailures=[];report.streamFrames=[];report.maxFrameInflight=0;let frameInflight=0;
 const isFrame=request=>request.url().endsWith('/api/ui/browser')&&request.postDataJSON()?.op==='frame';
 page.on('request',request=>{if(isFrame(request)){frameInflight++;report.maxFrameInflight=Math.max(report.maxFrameInflight,frameInflight);}});
 page.on('requestfinished',request=>{if(isFrame(request))frameInflight--;});
 page.on('response',async response=>{if(isFrame(response.request()))try{const data=await response.json();if(data.dataUrl)report.streamFrames.push({revision:data.revision,capturedAt:data.capturedAt,sha256:crypto.createHash('sha256').update(Buffer.from(data.dataUrl.split(',')[1],'base64')).digest('hex')});}catch{}});
 page.on('response',async response=>{if(response.request().url().endsWith('/api/ui/browser')&&response.request().postDataJSON()?.op==='frame.input')try{report.pointerResponse={request:response.request().postDataJSON(),result:await response.json()};}catch{}});
 page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('requestfailed',r=>report.requestFailures.push({url:r.url(),error:r.failure()}));await page.exposeFunction('c2fFramesReady',()=>report.streamFrames.some((frame,i)=>i>0&&frame.revision===report.streamFrames[i-1].revision&&frame.sha256!==report.streamFrames[i-1].sha256&&frame.capturedAt>report.streamFrames[i-1].capturedAt));await page.goto('http://127.0.0.1:48727/@fs/'+htmlPath.replaceAll('\\','/'),{waitUntil:'commit'});await page.getByText('Bus live',{exact:true}).waitFor({timeout:60000});await page.getByRole('button',{name:'Skip setup',exact:true}).click();await tool('pane.show',{kind:'browser',target:tabId});await page.getByRole('heading',{name:'Pane fixture'}).waitFor({timeout:30000});check('full NxShell mounts the right pane from real pane.show event',true);report.renderer='NxShell -> real UI event bus -> NxStage -> PaneView';
 await page.getByRole('textbox',{name:'Record',exact:true}).fill('pane input');await page.getByRole('button',{name:'Apply',exact:true}).click();
 await page.waitForFunction(()=>document.body.innerText.includes('pane input'));
 await page.waitForFunction(()=>{const image=document.querySelector('img[alt="Pane fixture"]');return image?.complete&&image.naturalWidth>0&&image.getBoundingClientRect().width>0});
 await page.waitForFunction(async()=>{const response=await fetch('/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'state'})});const state=await response.json();return Object.values(state.paneAcknowledgements||{}).some(ack=>ack.status==='observed');},{},{polling:250});
 const image=page.getByRole('img',{name:'Pane fixture',exact:true});const dimensions=await page.waitForFunction(()=>{const e=document.querySelector('img[alt="Pane fixture"]'),box=e?.getBoundingClientRect();return e?.complete&&e.naturalWidth>0&&box?.width>0&&box.height>0?{width:e.naturalWidth,height:e.naturalHeight,box:box.toJSON()}:false;});report.pointerImage=await dimensions.jsonValue();await dimensions.dispose();
 const live=await call('observe',{tabId}),save=live.elements.find(e=>e.role==='button'&&e.name==='Save record');check('pointer target has actual frame geometry',save?.bounds?.w>0&&save.bounds.h>0,save);
 await image.click({position:{x:report.pointerImage.box.width*(save.bounds.x+save.bounds.w/2)/report.pointerImage.width,y:report.pointerImage.box.height*(save.bounds.y+save.bounds.h/2)/report.pointerImage.height}});
 await page.waitForFunction(()=>document.body.innerText.includes('Saved: pane input'));check('real headless frame forwards pointer input',true);
 await page.getByRole('textbox',{name:'Record',exact:true}).fill('second input');await page.getByRole('button',{name:'Apply',exact:true}).click();await page.waitForFunction(()=>document.body.innerText.includes('second input'));await page.getByRole('button',{name:'Save record',exact:true}).click();await page.waitForFunction(()=>document.body.innerText.includes('Saved: second input'));
 await page.waitForFunction(async()=>window.c2fFramesReady(),{},{polling:250});check('pixel-only changes stream with unchanged DOM and capture backpressure',report.maxFrameInflight===1);
 await page.waitForFunction(async()=>{const response=await fetch('/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'state'})});const state=await response.json();return Object.values(state.paneAcknowledgements||{}).some(ack=>ack.status==='observed');},{},{polling:250});
 check('rendered pane forwards real user input',true);report.beforeNativeState=await call('state');
 const verifiedState=await page.waitForFunction(async()=>{const response=await fetch('/api/ui/tools/call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool:'neyvia.pane.state',arguments:{}})});const v=await response.json();const state=v.data?.result||v.result||v;return state.verified?state:false;},{},{polling:250,timeout:30000});const state=await verifiedState.jsonValue();await verifiedState.dispose();report.afterNativeState=await call('state');check('mounted content acknowledged',(state.result||state).verified===true,state);
 check('pane has no iframe or external escape',await page.locator('iframe,a[target="_blank"]').count()===0);await page.screenshot({path:path.join(repo,'scripts/evidence/C2f-pane-final.png'),fullPage:true});report.screenshot='scripts/evidence/C2f-pane-final.png';
 check('no React page errors',report.pageErrors.length===0);report.ok=true;
}
main().catch(e=>{report.error=e.stack;report.ok=false;process.exitCode=1}).finally(async()=>{if(proofPage)try{report.browserBody=await proofPage.locator('body').innerText({timeout:1000});await proofPage.screenshot({path:path.join(root,'last.png'),timeout:2000});}catch{}if(browser)await browser.close();try{await call('headless.stop')}catch{}if(vite)vite.kill();if(backend)backend.kill();if(fixture)await new Promise(r=>fixture.close(r));report.sources=Object.fromEntries(['src/grant_agent/browser_obscura.py','src/grant_agent/neyvia_browser.py','src/grant_agent/neyvia_panes.py','src/grant_agent/neyvia_workspace_tools.py','web/src/neyvia/next/NxPanes.jsx','web/src/neyvia/next/NxBrowserParts.jsx'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,p))).digest('hex')]));const raw=JSON.stringify(report,null,2)+'\n';fs.writeFileSync(path.join(root,'report.json'),raw);fs.writeFileSync(path.join(repo,'scripts/evidence/C2f-pane-attempt-'+path.basename(root)+'.json'),raw);if(report.ok)fs.writeFileSync(path.join(repo,'scripts/evidence/C2f-pane-proof.json'),raw);console.log(JSON.stringify({ok:report.ok,error:report.error,checks:report.checks,body:report.browserBody,failures:report.requestFailures}));});
