/* Run from the owned nx-c2-browser worktree after task-local admission/vendor.
 * Apply scripts/obscura-v024-C2g-capabilities.patch to official v0.2.4 sources.
 * Requires recorded V8 archive+bindings, vendor registry and installed MSVC/SDK.
 * No cargo network, toolchain install, stealth feature or public service access.
 */
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const receiptIndex=process.argv.indexOf('--receipt'),receiptName=receiptIndex<0?'C2g-engine-source-build.json':process.argv[receiptIndex+1];
if(!/^C2g-[a-zA-Z0-9-]+\.json$/.test(receiptName||''))throw Error('Build receipt needs a scoped C2g filename');
const receiptFile='scripts/evidence/'+receiptName;
const root=path.resolve('.agent_control/C2f'),source=path.join(root,'upstream-v0.2.4/obscura-0.2.4'),log=path.join(root,receiptName.replace('.json','.log')),cmake='C:/Program Files/Microsoft Visual Studio/18/Insiders/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin',clang=path.join(root,'libclang18/extracted/libclang-18.1.1.data/platlib/clang/native');
// Revalidate admitted local inputs; this helper never fetches a missing asset.
function admittedAsset(asset){const file=path.resolve(asset.path);if(!file.startsWith(root+path.sep)||fs.statSync(file).size!==asset.bytes)throw Error('Asset boundary/size mismatch: '+asset.path);if(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==asset.sha256)throw Error('Asset digest mismatch: '+asset.path);}
const readReceipt=name=>JSON.parse(fs.readFileSync('scripts/evidence/'+name));
readReceipt('C2f-v8-admission.json').assets.forEach(admittedAsset);
readReceipt('C2f-v8-simdutf-admission.json').assets.forEach(admittedAsset);
admittedAsset(readReceipt('C2f-libclang-admission.json'));
admittedAsset(readReceipt('C2f-engine-source-audit.json').archive);
const previous=fs.existsSync(receiptFile)?JSON.parse(fs.readFileSync(receiptFile)):null;
const actualVersions={cargo:cp.execFileSync('C:/Users/user/.rustup/toolchains/1.91.0-x86_64-pc-windows-msvc/bin/cargo.exe',['--version'],{windowsHide:true,encoding:'utf8'}).trim(),rustc:cp.execFileSync('C:/Users/user/.rustup/toolchains/1.91.0-x86_64-pc-windows-msvc/bin/rustc.exe',['--version'],{windowsHide:true,encoding:'utf8'}).trim()};
const resources=JSON.parse(cp.execFileSync('powershell.exe',['-NoProfile','-Command',"@{freeRamKiB=(Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory;logicalCores=(Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors} | ConvertTo-Json -Compress"],{windowsHide:true,encoding:'utf8'}));
const report={schema:'neyvia.C2g.engine-source-build@1',startedAt:new Date().toISOString(),source,pathBoundary:path.relative(process.cwd(),root),command:'cargo build --offline --locked --release -p obscura-cli --features render -j2 -vv',jobs:2,registryMode:process.argv.includes('--registry-cache')?'admitted official offline archive-cache':'admitted locked vendor directory',v8Feature:'simdutf matching enabled deno_core V8 ABI; identical base binding digest',v8Admission:'scripts/evidence/C2f-v8-simdutf-admission.json',toolchain:actualVersions,resources,stealth:false,cargoNetwork:false,systemInstall:false,priorAttempts:previous?[...(previous.priorAttempts||[]),{pid:previous.pid,startedAt:previous.startedAt,finishedAt:previous.finishedAt,exitCode:previous.exitCode,sourcePatch:previous.sourcePatch}]:[],sourcePatch:{file:'crates/obscura-browser/src/page.rs',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(source,'crates/obscura-browser/src/page.rs'))).digest('hex'),patchFile:'scripts/obscura-v024-C2g-capabilities.patch',mechanism:'retain completed external script fetches and reserve one-third total deadline, capped5secs, for document-order execution'},log:path.relative(process.cwd(),log)};
report.sourcePatch.mechanism='Routed incremental SSE resource with abort/backpressure, EventSource parser, CSS and matchMedia dark preference, same-document anchor navigation';
report.sourceHashes=Object.fromEntries(['Cargo.lock','crates/obscura-js/Cargo.toml','crates/obscura-js/src/lib.rs','crates/obscura-js/src/websocket.rs','crates/obscura-cdp/tests/page_websocket.rs','crates/obscura-js/src/ops.rs','crates/obscura-js/src/runtime.rs','crates/obscura-js/js/bootstrap.js','crates/obscura-browser/src/page.rs','crates/obscura-cdp/src/domains/emulation.rs','crates/obscura-render/src/css.rs'].map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(source,file))).digest('hex')]));
if(process.argv.includes('--fragment-render-key')){
  report.additionalPatches=[{path:'scripts/obscura-v024-C2g-fragment-render-key.patch',sha256:crypto.createHash('sha256').update(fs.readFileSync('scripts/obscura-v024-C2g-fragment-render-key.patch')).digest('hex'),mechanism:'Ignore only fragment in prepared screenshot resource-base comparison, retaining media and fonts'}];
}
const save=()=>fs.writeFileSync(receiptFile,JSON.stringify(report,null,2)+'\n');save();
const fd=fs.openSync(log,'a');const env={...process.env,CARGO_HOME:path.join(root,process.argv.includes('--registry-cache')?'cargo-home-registry-v024':'cargo-home-v024'),CARGO_TARGET_DIR:path.join(root,'target-v024'),CARGO_NET_OFFLINE:'true',RUSTY_V8_ARCHIVE:path.join(root,'v8-v150.4.0/rusty_v8_simdutf_release_x86_64-pc-windows-msvc.lib.gz'),RUSTY_V8_SRC_BINDING_PATH:path.join(root,'v8-v150.4.0/src_binding_simdutf_release_x86_64-pc-windows-msvc.rs'),LIBCLANG_PATH:clang,HTTP_PROXY:'http://127.0.0.1:48729',HTTPS_PROXY:'http://127.0.0.1:48729',ALL_PROXY:'http://127.0.0.1:48729',PATH:cmake+';'+process.env.PATH};
const vc='C:/Program Files/Microsoft Visual Studio/18/Insiders/VC/Tools/MSVC/14.50.35503',sdk='C:/Program Files (x86)/Windows Kits/10',sdkVersion='10.0.26100.0',toolchain='C:/Users/user/.rustup/toolchains/1.91.0-x86_64-pc-windows-msvc/bin';
Object.assign(env,{PATH:[toolchain,vc+'/bin/Hostx64/x64',sdk+'/bin/'+sdkVersion+'/x64',cmake,'C:/Program Files (x86)/Microsoft Visual Studio/Installer',process.env.PATH].join(';'),INCLUDE:[vc+'/include',sdk+'/Include/'+sdkVersion+'/ucrt',sdk+'/Include/'+sdkVersion+'/shared',sdk+'/Include/'+sdkVersion+'/um',sdk+'/Include/'+sdkVersion+'/winrt'].join(';'),LIB:[vc+'/lib/x64',sdk+'/Lib/'+sdkVersion+'/ucrt/x64',sdk+'/Lib/'+sdkVersion+'/um/x64'].join(';'),CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER:vc+'/bin/Hostx64/x64/link.exe',RUSTC:toolchain+'/rustc.exe',VCToolsInstallDir:vc+'/',WindowsSdkDir:sdk+'/',WindowsSDKVersion:sdkVersion+'/'});
env.CARGO_LOG='cargo::core::compiler::fingerprint=debug,cargo::core::resolver=info,cargo::sources::directory=debug';
fs.writeSync(fd,'\nC2f source build attempt: direct installed Cargo, explicit process-local SDK environment\n');
const websocketTests=process.argv.includes('--websocket-tests');
const buildArgs=[websocketTests?'test':'build','--offline',...(process.argv.includes('--refresh-lock')?[]:['--locked']),'--release','-p',websocketTests?'obscura-cdp':'obscura-cli',...(websocketTests?['--test','page_websocket','--no-run']:[]),'--features','render','-j2','-vv'];
report.command='cargo '+buildArgs.join(' ');report.refreshLock=process.argv.includes('--refresh-lock');save();
const child=cp.spawn(toolchain+'/cargo.exe',buildArgs,{cwd:source,env,windowsHide:true,stdio:['ignore',fd,fd]});fs.closeSync(fd);report.pid=child.pid;save();child.on('error',e=>{report.error=e.message;save();process.exitCode=1});child.on('exit',code=>{report.exitCode=code;report.finishedAt=new Date().toISOString();if(code===0&&!websocketTests){report.artifacts=['obscura.exe','obscura-worker.exe'].map(name=>{const file=path.join(root,'target-v024/release',name);return {path:path.relative(process.cwd(),file),bytes:fs.statSync(file).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')};});report.engineVersion=cp.execFileSync(path.join(root,'target-v024/release/obscura.exe'),['--version'],{windowsHide:true,encoding:'utf8'}).trim();}if(code===0&&websocketTests){const deps=path.join(root,'target-v024/release/deps');const binaries=fs.readdirSync(deps).filter(n=>/^page_websocket-[a-f0-9]+\.exe$/.test(n)).map(n=>path.join(deps,n)).sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);if(!binaries.length)throw Error('Compiled WebSocket test binary missing');report.testBinary={path:path.relative(process.cwd(),binaries[0]),sha256:crypto.createHash('sha256').update(fs.readFileSync(binaries[0])).digest('hex')};}save();console.log(JSON.stringify({code,receipt:receiptFile,log:report.log}));process.exitCode=code||0});

