'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const [portText,fixtureText,out]=process.argv.slice(2),port=Number(portText),fixturePort=Number(fixtureText);
if([port,fixturePort].some(p=>!Number.isInteger(p)||p<48721||p>48739)||port===fixturePort||!out||fs.existsSync(out))throw Error('Distinct explicit assigned ports and fresh receipt required');
const base=`http://127.0.0.1:${port}`,fixtureBase=`http://127.0.0.1:${fixturePort}`,report={schema:'neyvia.C2g.registered-cascade-proof@1',startedAt:new Date().toISOString(),ports:[port,fixturePort],boundary:'Actual controlled browser application, not a public frozen36 score',checks:[],calls:[]};let cookie,tab,fixture;
function save(){fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');}
async function call(op,args={}){const began=performance.now(),r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(op==='task.run'?160000:60000)});const v=await r.json();report.calls.push({op,args,response:v,http:r.status,ms:performance.now()-began});save();if(!r.ok)throw Error(JSON.stringify(v));return v;}
function checked(name,yes,details){report.checks.push({name,passed:!!yes,details});save();assert.ok(yes,name);}
(async()=>{
 fixture=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(`<!doctype html><html><head><title>Goal cascade workspace</title></head><body><label>Name<input aria-label="Name"></label><button onclick="document.querySelector('output').textContent='Saved: '+document.querySelector('input').value">Save</button><output>Not saved</output><a href="/captcha">Owner check</a></body></html>`);});await new Promise((resolve,reject)=>{fixture.on('error',reject);fixture.listen(fixturePort,'127.0.0.1',resolve);});
 const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});cookie=r.headers.get('set-cookie').split(';')[0];
 tab=(await call('tab.open',{url:fixtureBase,engine:'obscura'})).tabId;await call('tab.grant',{tabId:tab,enabled:true});
 const step=[{target:{role:'textbox',name:'Name'},action:'fill',value:{$input:'name'}},{target:{role:'button',name:'Save'},action:'click'}];
 const learned=await call('script.learn',{tabId:tab,name:'c2g-save',inputs:{name:'First',expected:'Saved: First'},steps:step,checks:[{path:'/text',contains:{$input:'expected'}}]});checked('First success admitted only after goal and effects',learned.verification?.verified&&learned.receipts.every(r=>r.verification?.verified),learned);
 const replay=await call('task.run',{tabId:tab,goal:'Save the supplied name Second',requirements:['The saved result is Second'],script:'c2g-save',inputs:{name:'Second',expected:'Saved: Second'},checks:[{path:'/text',contains:'Saved: Second'}],maxActions:2,allowModel:false});checked('Registered compiled task changed real page with zero model calls',replay.status==='done'&&replay.modelCalls===0&&replay.observation.text.includes('Saved: Second'),replay);
 const noModel=await call('task.run',{tabId:tab,goal:'Save the name Third',requirements:['The saved result is Third'],checks:[{path:'/text',contains:'Saved: Third'}],maxActions:2,allowModel:false});checked('Failed goal escalates instead of false success',noModel.status==='model_required'&&noModel.ok===false,noModel);
 const o=await call('observe',{tabId:tab}),buttons=o.elements.filter(e=>e.actions?.includes('click')&&!e.secret&&e.enabled!==false),saveButton=buttons.find(e=>e.name==='Save'),other=buttons.find(e=>e.name!=='Save');
 const context={goal:'Click button "Save".',decision_profile:'public_explicit_intent@1',options:[{id:'a',description:'Click button "Save".',args:{element:saveButton.id,action:'click'}},{id:'b',description:`Click ${other.role} "${other.name}".`,args:{element:other.id,action:'click'}}]};
 const fallback=await call('task.run',{tabId:tab,goal:'Read the current saved name; answer Second.',requirements:['Return the saved name'],checks:[{path:'/text',contains:'Saved: Second'}],layaContext:context,allowModel:true,maxActions:2,maxModelCalls:2});checked('Explicit goal early exit avoids unnecessary model',fallback.status==='done'&&fallback.modelCalls===0,fallback);
 const model=await call('task.run',{tabId:tab,goal:'Read the saved result and return its name.',requirements:['Return the currently saved name'],layaContext:context,allowModel:true,maxActions:0,maxModelCalls:2});checked('Low-confidence LAYA escalates to actual Luna and independent done judge',model.status==='done'&&model.modelCalls===2&&model.stages.some(s=>s.stage==='laya')&&model.stages.some(s=>s.stage==='luna')&&model.stages.some(s=>s.stage==='completion-judge'&&s.verdict)&&model.verification?.verified,model);
 const mutation=await call('task.run',{tabId:tab,goal:'Fill Name with Third, click Save, and return the saved result.',requirements:['The saved result is Third'],checks:[{path:'/text',contains:'Saved: Third'}],allowModel:true,maxActions:3,maxModelCalls:4});checked('Registered Luna path performs and verifies actual browser effects',mutation.status==='done'&&mutation.steps===2&&mutation.modelCalls>=2&&mutation.observation.text.includes('Saved: Third')&&mutation.verification?.verified,mutation);
 report.ok=true;
})().catch(e=>{report.ok=false;report.error=e.stack;process.exitCode=1;}).finally(async()=>{if(tab)await call('tab.close',{tabId:tab}).catch(e=>report.closeError=e.message);if(fixture)await new Promise(r=>fixture.close(r));report.finishedAt=new Date().toISOString();report.sourceHashes=Object.fromEntries(['src/grant_agent/browser_task.py','src/grant_agent/neyvia_browser.py','scripts/browser_luna.cjs','scripts/c2g_task_proof.cjs'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));save();console.log(JSON.stringify({ok:report.ok,checks:report.checks.map(({name,passed})=>({name,passed})),error:report.error}));});
