'use strict';
// BBC-owned feed discovery from observed controls and hrefs. Diagnostic only.
const fs = require('node:fs'), crypto = require('node:crypto');
const port = Number(process.argv[2]), out = process.argv[3];
if (!Number.isInteger(port) || port < 48721 || port > 48729 || !out || fs.existsSync(out)) throw Error('Explicit owned port and fresh receipt required');
const base = `http://127.0.0.1:${port}`, sha = b => crypto.createHash('sha256').update(b).digest('hex');
const report = {schema:'neyvia.C2g.bbc-feed-discovery@1', startedAt:new Date().toISOString(), startUrl:'https://www.bbc.com/news', stealth:false, diagnosticOnly:true, maxActions:20, steps:0, observations:[], flow:[], calls:[], publicSources:[], feeds:[]};
let cookie, tab;
const sleep = ms => new Promise(r => setTimeout(r,ms));
const save = () => fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
async function call(op,args={}) { const start=performance.now(),r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)}),v=await r.json(); report.calls.push({op,args,status:r.status,ms:performance.now()-start,ok:v.ok});save();if(!r.ok||v.ok===false)throw Error(JSON.stringify(v));return v; }
async function done(v) { if(v.status==='queued'||v.status==='running')v=await call('wait',{actionId:v.actionId||v.id,timeoutMs:30000});if(v.status==='failed')throw Error(JSON.stringify(v));return v.result?.observation||v.result||v; }
function snapshot(o) { const p=out.replace(/\.json$/,'')+`-observation-${report.observations.length}.json`,b=JSON.stringify(o)+'\n';fs.writeFileSync(p,b);report.observations.push({path:p,sha256:sha(b),url:o.url,revision:o.revision});save();return o; }
async function observe(){return snapshot(await done(await call('observe',{tabId:tab})));}
async function open(url,from) { if(report.steps>=20)throw Error('Action bound reached');report.flow.push({kind:'open-observed',url,from});const v=await call('tab.open',{url,engine:'webview2'}),old=tab;tab=v.tabId;await done(v);await done(await call('layout',{tabs:[{tabId:tab,x:0,y:0,width:1280,height:900,visible:true}]}));await sleep(1000);await done(await call('tab.grant',{tabId:tab,enabled:true}));if(old)await done(await call('tab.close',{tabId:old}));report.steps++;return observe(); }
async function act(o,e,action,value) { if(report.steps>=20)throw Error('Action bound reached');report.flow.push({kind:'observed-control',url:o.url,revision:o.revision,element:e.id,role:e.role,name:e.name,action,value});await done(await call('tab.grant',{tabId:tab,enabled:true}));await done(await call('action',{tabId:tab,revision:o.revision,element:e.id,action,...(value===undefined?{}:{value})}));report.steps++;await sleep(600);return observe(); }
const allowed = url => /^https?:$/.test(new URL(url).protocol)&&/^(?:[\w-]+\.)*(?:bbc\.com|bbc\.co\.uk|bbci\.co\.uk)$/.test(new URL(url).hostname);
async function publicSource(o) {const url=o.url;if(!allowed(url)||report.publicSources.some(s=>s.requestedUrl===url))return[];const r=await fetch(url,{signal:AbortSignal.timeout(30000)}),text=await r.text(),p=out.replace(/\.json$/,'')+`-source-${report.publicSources.length}.txt`;if(Buffer.byteLength(text)>2e6)throw Error('Bounded public source exceeded2MB');fs.writeFileSync(p,text);const links=[...text.matchAll(/(?:href|src)=["']([^"']+)["']/gi)].map(m=>{try{return new URL(m[1].replace(/&amp;/g,'&'),r.url).href}catch{return null}}).filter(Boolean).filter(allowed);const unique=[...new Set(links)];const feedLinks=unique.filter(u=>/\brss\b|\/feeds\//i.test(u)&&!/\.js(?:\?|$)/i.test(u));report.publicSources.push({requestedUrl:url,url:r.url,status:r.status,path:p,sha256:sha(text),bytes:Buffer.byteLength(text),discoveryBoundary:'Read-only public HTML of a browser-observed URL; only literal href/src values admitted',feedLinks});save();return feedLinks.sort((a,b)=>Number(/health/i.test(b))-Number(/health/i.test(a))||Number(/science|environment/i.test(b))-Number(/science|environment/i.test(a)));}
async function feed(url,source) { if(report.feeds.length>=8||report.feeds.some(f=>f.observedHref===url))return;await sleep(600);const r=await fetch(url,{signal:AbortSignal.timeout(30000)}),text=await r.text(),p=out.replace(/\.json$/,'')+`-feed-${report.feeds.length}.xml`;if(Buffer.byteLength(text)>2e6)throw Error('Feed exceeded2MB');fs.writeFileSync(p,text);const items=[...text.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>Object.fromEntries(['title','link','pubDate','description'].map(k=>{const z=m[1].match(new RegExp('<'+k+'[^>]*>([\\s\\S]*?)<\\/'+k+'>','i'));return[k,z?.[1].replace(/^<!\[CDATA\[|\]\]>$/g,'')]})));report.feeds.push({url:r.url,observedHref:url,source,status:r.status,path:p,sha256:sha(text),bytes:Buffer.byteLength(text),items});save();}
(async()=>{const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Local bootstrap unavailable');cookie=r.headers.get('set-cookie').split(';')[0];let o=await open(report.startUrl,'frozen BBC start URL');let links=await publicSource(o);for(const u of links)await feed(u,{observation:report.observations.at(-1),literalHref:u});
const searched=new Set(),visited=new Set([o.url]);let query='RSS feeds';
while(report.steps<20&&!report.feeds.some(f=>f.items.length&&/health/i.test(f.url))){
const feedLink=o.elements?.find(e=>e.href&&allowed(e.href)&&!new URL(e.href).hash&&!/search|sign-in|session|account/.test(new URL(e.href).pathname)&&/rss|feeds/i.test(e.name)&&!visited.has(e.href));if(feedLink){await feed(feedLink.href,{observation:report.observations.at(-1),element:feedLink.id,name:feedLink.name});visited.add(feedLink.href);o=await open(feedLink.href,{observation:report.observations.at(-1),element:feedLink.id,name:feedLink.name});links=await publicSource(o);for(const u of links)await feed(u,{observation:report.observations.at(-1),literalHref:u});continue;}
if(/\/search/.test(new URL(o.url).pathname)){if(!searched.has(query)){let input=o.elements.find(e=>['textbox','combobox','searchbox'].includes(e.role)&&e.actions?.includes('fill')&&/search/i.test(e.name));if(!input){report.frontier='No observed enabled search input';break;}o=await act(o,input,'fill',query);input=o.elements.find(e=>String(e.id)===String(input.id));if(input?.actions?.includes('submit'))o=await act(o,input,'submit');else{const btn=o.elements.find(e=>e.role==='button'&&/^search$/i.test(e.name));if(!btn){report.frontier='No observed unique submit control';break;}o=await act(o,btn,'click');}searched.add(query);continue;}
const candidates=o.elements.filter(e=>e.href&&allowed(e.href)&&!visited.has(e.href)&&!new URL(e.href).hash&&/rss|feeds/i.test(e.name)&&!/search|sign-in|session|account/.test(new URL(e.href).pathname));if(candidates.length){const e=candidates[0];visited.add(e.href);o=await open(e.href,{observation:report.observations.at(-1),element:e.id,name:e.name});links=await publicSource(o);for(const u of links)await feed(u,{observation:report.observations.at(-1),literalHref:u});continue;}if(query==='RSS feeds'){report.rssSearchCompleted=true;query='health RSS';}else{report.frontier='BBC search results expose no unvisited RSS/feed link; no date-filter/order control established';break;}}
const search=o.elements.find(e=>e.href&&allowed(e.href)&&!new URL(e.href).hash&&/\/search(?:\?|$)/.test(e.href));if(search){o=await open(search.href,{observation:report.observations.at(-1),element:search.id,name:search.name});continue;}const button=o.elements.find(e=>e.role==='button'&&/search/i.test(e.name)&&e.actions?.includes('click'));if(button){o=await act(o,button,'click');continue;}const guidance=o.elements.find(e=>e.href&&allowed(e.href)&&new URL(e.href).pathname==='/editorialguidelines/guidance/links-and-feeds'&&!visited.has(e.href));if(guidance){visited.add(guidance.href);o=await open(guidance.href,{observation:report.observations.at(-1),element:guidance.id,name:guidance.name});continue;}report.frontier='No observed BBC search/feed navigation control';break;
}
const health=report.feeds.find(f=>f.items.length&&/health/i.test(f.url));if(health){const dated=health.items.filter(i=>Number.isFinite(Date.parse(i.pubDate)));report.healthChronology={feed:health.url,datedItems:dated.length,orderedNewestFirst:dated.every((i,k)=>!k||Date.parse(dated[k-1].pubDate)>=Date.parse(i.pubDate)),newest:dated[0],scope:'BBC-published health RSS item set, not global BBC editorial completeness'};if(dated[0]?.link&&allowed(dated[0].link)){o=await open(dated[0].link,{feed:health.url,path:health.path,sha256:health.sha256,itemIndex:0,literalLink:dated[0].link});report.newestHealthArticle=report.observations.at(-1);}}
if(report.steps>=20&&!report.healthChronology)report.frontier='Twenty action discovery bound reached; no authoritative health chronology feed established';report.deforestationBoundary='No complete exact topic/date/order source established. Do not infer absence or latest from editorial/relevance order.';
})().catch(e=>{report.error=e.message;process.exitCode=1;}).finally(async()=>{if(tab)await done(await call('tab.close',{tabId:tab})).catch(e=>report.closeError=e.message);report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify({out,steps:report.steps,frontier:report.frontier,error:report.error,feeds:report.feeds.map(f=>({url:f.url,items:f.items.length})),healthChronology:report.healthChronology}));});
