'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),{taskPlan}=require('./c2f_site_flows.cjs'),{answer}=require('./c2f_answers.cjs');
const port=Number(process.argv[2]),out=process.argv[3]; if(!Number.isInteger(port)||port<48721||port>48729||!out||fs.existsSync(out))throw Error("Explicit owned port and fresh receipt path required"); const base="http://127.0.0.1:"+port;
const goal="Compare the prices and chips for the iPhone 14 Pro and iPhone 15 Pro models directly from Apple's website.";
const report={schema:'neyvia.C2g.actual-site-controls@1',startedAt:new Date().toISOString(),goal,startUrl:'https://www.apple.com/',engine:'webview2',stealth:false,steps:0,maxActions:20,observations:[],flow:[],calls:[]};let cookie,tab;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
async function call(op,args={}){const start=performance.now(),r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)}),v=await r.json();report.calls.push({op,args,status:r.status,ms:performance.now()-start,ok:v.ok});save();if(!r.ok||v.ok===false){const e=Error(JSON.stringify(v));e.value=v;throw e;}return v;}
async function done(v){if(v.status==='queued'||v.status==='running')v=await call('wait',{actionId:v.actionId||v.id,timeoutMs:30000});if(v.status==='failed')throw Error(JSON.stringify(v));return v.result?.observation||v.result||v;}
function snapshot(o){const p=out.replace(/\.json$/,'')+`-${report.observations.length}.json`,bytes=JSON.stringify(o)+'\n';fs.writeFileSync(p,bytes);report.observations.push({path:p,sha256:hash(bytes),url:o.url,revision:o.revision});save();return o;}
async function observe(){return snapshot(await done(await call('observe',{tabId:tab})));}
async function open(url){const v=await call('tab.open',{url,engine:'webview2'}),old=tab;tab=v.tabId;await done(v);await done(await call('layout',{tabs:[{tabId:tab,x:0,y:0,width:1280,height:900,visible:true}]}));await sleep(900);await done(await call('tab.grant',{tabId:tab,enabled:true}));if(old)await done(await call('tab.close',{tabId:old}));return observe();}
(async()=>{const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Local bootstrap unavailable');cookie=r.headers.get('set-cookie').split(';')[0];let o=await open(report.startUrl),context={asOf:report.startedAt,completedQueries:[]};const plans=new Set();
while(report.steps<20){if(new URL(o.url).pathname.includes('/newsroom/search')){for(let i=0;i<7&&!o.elements?.some(e=>e.href&&/\/newsroom\/20/.test(e.href));i++){await sleep(1000);o=await observe();}}
const plan=taskPlan(goal,o,context),key=JSON.stringify([o.url,plan.href,plan.steps]);if(!plan.ok){report.frontier=plan.frontier;break;}if(plans.has(key)){report.frontier='Repeated unchanged observed plan; no replay';break;}plans.add(key);report.flow.push({plan});save();
if(plan.kind==='follow'){o=await open(plan.href);report.steps++;}else{for(const step of plan.steps){o=await observe();const rows=o.elements.filter(e=>Object.entries(step.target).every(([k,v])=>e[k]===v));if(rows.length!==1)throw Error('Observed action target no longer unique');await done(await call('tab.grant',{tabId:tab,enabled:true}));const r=await call('action',{tabId:tab,revision:o.revision,element:rows[0].id,action:step.action,...(step.value===undefined?{}:{value:step.value})});await done(r);report.steps++;await sleep(300);o=await observe();}}
}
report.answer=answer(goal,report.observations.map(ref=>({ref,observation:JSON.parse(fs.readFileSync(ref.path))})));report.answerReturnedAt=new Date().toISOString();
})().catch(e=>{report.error=e.message;process.exitCode=1;}).finally(async()=>{if(tab)await done(await call('tab.close',{tabId:tab})).catch(e=>report.closeError=e.message);report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify({steps:report.steps,frontier:report.frontier,error:report.error,answer:report.answer}));});

