'use strict';
// Bounded diagnostic operator: only browser-observed BBC links and controls.
// Run with explicitport andfreshreceipt. Send JSON commands through <receipt>-control.json.
// Cookie staysinmemory. finish closes theownedtab; profile/space arediagnostic-only.
const fs=require('node:fs'),crypto=require('node:crypto');
const port=Number(process.argv[2]),out=process.argv[3];
if(!Number.isInteger(port)||port<48721||port>48729||!out||fs.existsSync(out))throw Error('Explicit task port and fresh receipt required');
const base=`http://127.0.0.1:${port}`,sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const report={schema:'neyvia.C2g.bbc-chronology@1',startedAt:new Date().toISOString(),diagnosticOnly:true,stealth:false,maxSourcePages:12,minNavigationIntervalMs:1500,sourcePages:0,observations:[],calls:[],flow:[],sources:[]};
let cookie,tab,current,lastNavigation=0,closed=false;
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
const allowed=u=>{try{const z=new URL(u);return /^https?:$/.test(z.protocol)&&/^(?:[\w-]+\.)*(?:bbc\.com|bbc\.co\.uk|bbci\.co\.uk)$/.test(z.hostname)}catch{return false}};
async function call(op,args={}){const r=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(60000)}),v=await r.json();report.calls.push({op,args,http:r.status,ok:v.ok,at:new Date().toISOString()});save();if(!r.ok||v.ok===false)throw Error(JSON.stringify(v));return v;}
async function done(v){if(v.status==='queued'||v.status==='running')v=await call('wait',{actionId:v.actionId||v.id,timeoutMs:30000});if(v.status==='failed')throw Error(JSON.stringify(v));return v.result?.observation||v.result||v;}
function snapshot(o){const path=out.replace(/\.json$/,'')+`-observation-${report.observations.length}.json`,b=JSON.stringify(o)+'\n';fs.writeFileSync(path,b);report.observations.push({path,sha256:sha(b),url:o.url,revision:o.revision});current=o;save();return o;}
function print(o){console.log(JSON.stringify({page:report.sourcePages,url:o.url,revision:o.revision,text:o.text?.slice(0,5000)||o.bodyText?.slice(0,5000),elements:o.elements?.filter(e=>e.role==='button'||e.actions?.includes('fill')||e.href&&/health|science|forest|index|rss|feeds|Next Page/i.test(e.name)).map(e=>({id:e.id,role:e.role,name:e.name,href:e.href,actions:e.actions,value:e.value})),commands:'{"open":elementId}, {"act":elementId,"action":"click|fill|submit|select","value":"..."}, {"observe":true}, {"source":true}, {"sourceOpen":index}, {"finish":"frontier"}'}));}
async function pace(){await sleep(Math.max(0,1500-(Date.now()-lastNavigation)));lastNavigation=Date.now();}
function countPage(){if(report.sourcePages>=12)throw Error('Twelve source-page bound reached');report.sourcePages++;}
async function observe(){return snapshot(await done(await call('observe',{tabId:tab})));}
async function open(url,from){if(!allowed(url))throw Error('Only observed BBC-owned URLs admitted');countPage();await pace();report.flow.push({kind:'open-observed',url,from});const v=await call('tab.open',{url,spaceId:report.spaceId,engine:'webview2'}),old=tab;tab=v.tabId;await done(v);await done(await call('layout',{tabs:[{tabId:tab,x:0,y:0,width:1280,height:900,visible:true}]}));await sleep(2500);await done(await call('tab.grant',{tabId:tab,enabled:true}));if(old)await done(await call('tab.close',{tabId:old}));return observe();}
async function source(){const url=current.url;if(!allowed(url))throw Error('Only observed BBC source');countPage();await pace();const r=await fetch(url,{signal:AbortSignal.timeout(30000)}),b=await r.text();if(Buffer.byteLength(b)>2000000)throw Error('Source exceeds2MB');const path=out.replace(/\.json$/,'')+`-source-${report.sources.length}.txt`;fs.writeFileSync(path,b);const links=[...b.matchAll(/(?:href|src)=["']([^"']+)["']/gi)].map(m=>{try{return new URL(m[1].replace(/&amp;/g,'&'),r.url).href}catch{return null}}).filter(allowed);const s={requestedUrl:url,url:r.url,status:r.status,path,sha256:sha(b),links:[...new Set(links)],boundary:'Literal href/src only; a redirect is not an invented route'};report.sources.push(s);save();console.log(JSON.stringify(s));}
async function close(){if(closed)return;closed=true;if(tab)await done(await call('tab.close',{tabId:tab})).catch(e=>report.closeError=e.message);report.finishedAt=new Date().toISOString();save();}
(async()=>{const r=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Local bootstrap unavailable');cookie=r.headers.get('set-cookie').split(';')[0];const p=await call('profile.create',{name:'C2g BBC chronology diagnostic'});report.profileId=p.id;const s=await call('space.create',{name:'C2g BBC chronology diagnostic',profileId:p.id});report.spaceId=s.id;print(await open('https://www.bbc.com/news','Frozen BBC task start URL'));
async function* commands(){const p=out.replace(/\.json$/,'')+'-control.json';let last='';for(;;){if(fs.existsSync(p)){const b=fs.readFileSync(p,'utf8');if(b!==last){last=b;yield b;}}await sleep(500);}}for await(const line of commands()){try{const c=JSON.parse(line);if(c.finish){report.frontier=c.finish;await close();break;}if(c.observe)print(await observe());else if(c.source)await source();else if(c.sourceOpen!==undefined){const s=report.sources.at(-1),url=s?.links[c.sourceOpen];if(!url)throw Error('No literal source link at index');print(await open(url,{source:s.path,sha256:s.sha256,literalHref:url}));}else if(c.open!==undefined){const e=current.elements?.find(e=>String(e.id)===String(c.open));if(!e?.href)throw Error('No observed href');print(await open(e.href,{observation:report.observations.at(-1),element:e.id,name:e.name}));}else if(c.act!==undefined){const e=current.elements?.find(e=>String(e.id)===String(c.act));if(!e||!e.actions?.includes(c.action))throw Error('Action not observed');const old=current.url;if(c.action!=='fill'){await pace();}report.flow.push({kind:'observed-control',observation:report.observations.at(-1),element:e.id,name:e.name,action:c.action,value:c.value});await done(await call('action',{tabId:tab,revision:current.revision,element:e.id,action:c.action,...(c.value===undefined?{}:{value:c.value})}));await sleep(1500);const o=await observe();if(o.url!==old)countPage();print(o);}else throw Error('Unknown command');}catch(e){report.errors=(report.errors||[]).concat({at:new Date().toISOString(),message:e.message});save();console.log(JSON.stringify({error:e.message}));}}
})().catch(e=>{report.error=e.message;process.exitCode=1;console.log(JSON.stringify({error:e.message}));}).finally(close);
