'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const [portText,out]=process.argv.slice(2),port=Number(portText);if(port<48721||port>48739||!out||fs.existsSync(out))throw Error('Owned port and fresh receipt required');
const report={schema:'neyvia.C2h.owner-handoff-proof@1',at:new Date().toISOString(),scope:'Disposable local wall fixture; actual retained Obscura tab and AgentLive component. No public challenge is solved.',calls:[]};let cleared=false,cookie,tab,pane;
async function clickResume(){for(let i=0;i<3;i++){const o=await call('observe',{tabId:pane});const e=o.elements.find(e=>e.name==='Resume task');if(!e)throw Error('Resume button absent');try{return await call('action',{tabId:pane,revision:o.revision,element:e.id,action:'click'});}catch(error){if(error.value?.error?.code!=='stale_projection')throw error;report.safePreDispatchRefreshes=(report.safePreDispatchRefreshes||0)+1;}}throw Error('Pane keeps changing before dispatch');}
const site=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.end('<!doctype html><title>Disposable owner wall</title><output>'+(cleared?'Owner fixture resolved. Product price is $42.':'Verify you are human. This disposable fixture needs owner help.')+'</output>');});
const ui=http.createServer(async(q,r)=>{if(q.url.startsWith('/api/')){const b=await new Promise(resolve=>{let s='';q.on('data',d=>s+=d);q.on('end',()=>resolve(s))});const v=await fetch('http://127.0.0.1:'+port+q.url,{method:q.method,headers:{'Content-Type':'application/json',Cookie:cookie},...(q.method==='POST'?{body:b}:{})});r.writeHead(v.status,{'Content-Type':'application/json'});r.end(await v.text());return;}const p=path.resolve('.agent_control/C2h/pane-dist',new URL(q.url,'http://127.0.0.1:48737').pathname.slice(1)||'index.html');if(!p.startsWith(path.resolve('.agent_control/C2h/pane-dist')+path.sep)){r.writeHead(403);r.end();return;}r.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');r.end(fs.readFileSync(p));});
async function call(op,args={}){const start=performance.now(),r=await fetch('http://127.0.0.1:'+port+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({op,args}),signal:AbortSignal.timeout(300000)}),v=await r.json();report.calls.push({op,ms:performance.now()-start,http:r.status,response:v});if(!r.ok)throw Object.assign(Error(JSON.stringify(v)),{value:v});return v;}
(async()=>{try{await Promise.all([new Promise(r=>site.listen(48732,'127.0.0.1',r)),new Promise(r=>ui.listen(48737,'127.0.0.1',r))]);const a=await fetch('http://127.0.0.1:'+port+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});cookie=a.headers.get('set-cookie').split(';')[0];tab=(await call('tab.open',{url:'http://127.0.0.1:48732/',engine:'obscura'})).tabId;await call('tab.grant',{tabId:tab,enabled:true});
 const args={tabId:tab,goal:'Return the observed product price.',requirements:['Return the observed product price'],allowModel:true,maxActions:0,maxModelCalls:2};const paused=await call('task.run',args);assert.equal(paused.status,'needs_owner');const state=await call('state');assert.equal(state.tabs.find(t=>t.id===tab).agentGranted,false);assert.equal(state.tabs.find(t=>t.id===tab).pinned,true);assert.equal(state.activeTabId,tab);assert.equal((await call('task.resume',{taskId:paused.taskId})).status,'needs_owner');
 pane=(await call('tab.open',{url:'http://127.0.0.1:48737/?tab='+tab,engine:'obscura'})).tabId;await call('tab.grant',{tabId:pane,enabled:true});let observed;for(let i=0;i<50;i++){observed=await call('observe',{tabId:pane});if(observed.elements.some(e=>e.name==='Resume task'))break;await new Promise(r=>setTimeout(r,100));}assert.match(observed.text,/This task needs your help/);const button=observed.elements.find(e=>e.name==='Resume task');assert.ok(button);await clickResume();for(let i=0;i<30;i++){observed=await call('observe',{tabId:pane});if(observed.text.includes('The page still needs your help.'))break;await new Promise(r=>setTimeout(r,100));}assert.match(observed.text,/The page still needs your help/);const image=await call('frame',{tabId:pane});fs.writeFileSync(out.replace(/\.json$/,'.png'),Buffer.from(image.dataUrl.split(',')[1],'base64'));report.renderedObservation=observed;
 // The fixture owner changes its supplied page; no challenge action is executed.
 cleared=true;await call('tab.navigate',{tabId:tab,url:'http://127.0.0.1:48732/resolved'});const resumed=await call('task.resume',{taskId:paused.taskId});assert.equal(resumed.status,'done');assert.equal(resumed.ownerHandoff,true);assert.match(resumed.answer,/42/);report.passed=true;report.taskId=paused.taskId;
 }catch(e){report.passed=false;report.error=e.stack;process.exitCode=1;}finally{if(pane)await call('tab.close',{tabId:pane}).catch(()=>{});if(tab)await call('tab.close',{tabId:tab}).catch(()=>{});site.close();ui.close();report.finishedAt=new Date().toISOString();fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,error:report.error}));}})();
