'use strict';
const fs=require('node:fs'),cp=require('node:child_process'),crypto=require('node:crypto');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),load=p=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null;
const runPath='scripts/evidence/C2h-frozen36.json',gradesPath='scripts/evidence/C2h-grades.json',run=load(runPath),grades=load(gradesPath);
const q=(a,p)=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?p===.5?(a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2:a[Math.min(a.length-1,Math.ceil(a.length*p)-1)]:null;};
const metric=a=>({samples:a.filter(Number.isFinite).length,p50Ms:q(a,.5),p95Ms:q(a,.95),quantile:'Median averages middle pair; p95 nearest rank'});
const calls=run?.calls||[],passes=grades?.grades||grades?.tasks||[];
const models=new Map();function visit(v){if(!v||typeof v!=='object')return;if(v.schema==='neyvia.browser-luna@1'){const id=v.events?.find(e=>e.type==='thread.started')?.thread_id;if(id)models.set(id,v.usage);return;}if(Array.isArray(v))v.forEach(visit);else Object.values(v).forEach(visit);}
for(const name of fs.readdirSync('scripts/evidence').filter(n=>/^C2h.*\.json$/.test(n)&&n!=='C2h.json')){try{visit(load('scripts/evidence/'+name));}catch{}}
const tokens=[...models.values()].reduce((sum,u)=>sum+(u?.input_tokens||0)+(u?.output_tokens||0),0);
const successIds=new Set(passes.filter(t=>t.success).map(t=>t.id));
const report={schema:'neyvia.C2h@1',updatedAt:new Date().toISOString(),status:grades&&!grades.draft?'graded':run?.finishedAt?'awaiting_independent_grade':run?'running_frozen36':'implementation_checkpoint',workspace:process.cwd(),branch:cp.execFileSync('git',['branch','--show-current'],{encoding:'utf8',windowsHide:true}).trim(),commits:cp.execFileSync('git',['log','76cfd4be6..HEAD','--reverse','--format=%h %s'],{encoding:'utf8',windowsHide:true}).trim().split(/\r?\n/),baseline:{gradedRun:'C2g repaired',passed:20,failed:14,needsOwner:2,obscuraOnlyPasses:12,webView2AssistedPasses:8},policy:{stealth:false,captchaOrBotCheckBypass:false,downloadsOver200MB:false,pushed:false,merged:false,nasSync:false,ports:'48721-48739',publicSiteConcurrency:1,persistedProfile:run?.persistedProfile||null},proofs:[],fresh36:{run:run?{path:runPath,sha256:hash(runPath),finishedAt:run.finishedAt||null,completedTasks:run.tasks.filter(t=>t.finishedAt).length,taskSetSha256:run.taskSetSha256,sourcesUnchanged:run.sourcesUnchanged??null}:null,grades:grades?{path:gradesPath,sha256:hash(gradesPath),summary:grades.summary}:null,obscuraOnlyPasses:grades?run.tasks.filter(t=>successIds.has(t.id)&&t.engine!=='webview2').length:null,webView2AssistedPasses:grades?run.tasks.filter(t=>successIds.has(t.id)&&t.engine==='webview2').length:null,ownerHandoffs:run?.tasks.filter(t=>t.ownerHandoff).map(t=>({id:t.id,...t.ownerHandoff}))||[]},latency:{pageToCl:metric(calls.map(c=>c.pageToClMs)),actionToVerified:metric(calls.flatMap(c=>[c.actionToVerifiedMs,...(c.verifiedActionSamples||[])])),scope:'Instrumented actual Obscura DOM-to-masked projection and dispatch-to-verified state. Navigation, model and unverified effects excluded.'},tokens:{meteredTypedPlannerAndEvaluator:tokens,uniqueReceipts:models.size,codexEngineeringTokens:null,totalAllModels:null,limitation:'Outer Codex token meter is unavailable; metered product calls are reported separately and never presented as a complete total.'},missing:[]};
for(const p of ['C2h-recovery-judge-dispatch.json','C2h-admitted-recovery-finish-proof.json','C2h-candidate-registered-proof.json','C2h-separate-grader-proof.json','C2h-handoff-styled-proof.json','C2h-websocket-owned-fixture-proof.json','C2h-websocket-cl-isolated.json','C2h-upstream-websocket-tests.json','C2h-engine-admission.json','C2h-native-sharing-recovery.json']){const f='scripts/evidence/'+p,r=load(f);if(r)report.proofs.push({path:f,sha256:hash(f),passed:r.passed??r.ok??(r.buildExitCode===0),boundary:r.scope||r.runtimeProof?.scope||r.boundary||null});}
const admission=load('scripts/evidence/C2h-engine-admission.json'),runtime=load('scripts/evidence/C2h-runtime-in-run.json');
report.engine={upstream:admission?.upstream,upstreamCommit:admission?.upstreamCommit,engineBinary:admission?.engineBinary,workerBinary:admission?.workerBinary,observedDuringRun:runtime?.headless||null,sameAdmittedBinary:runtime?.headless?.binarySha256===admission?.engineBinary?.sha256};
report.fresh36.webView2Attempts=run?.tasks.filter(t=>t.engine==='webview2').map(t=>({id:t.id,status:t.status}))||[];
report.fresh36.failures=passes.filter(t=>t.outcome==='failed').map(t=>({id:t.id,reason:t.reason,missingClauses:t.missingClauses}));
const rawGrades=load('scripts/evidence/C2h-grades-model.json'),review=load('scripts/evidence/C2h-review.json');
report.fresh36.separateEvaluator={rawSummary:rawGrades?.summary||null,rawGrades:rawGrades?{path:'scripts/evidence/C2h-grades-model.json',sha256:hash('scripts/evidence/C2h-grades-model.json')}:null,integrationReview:review?.integrationReview||null,identity:grades?.grader?.identity||null};
report.fresh36.executionSegments=run?.executionSegments||[];
report.manualContracts={source:'manuals/cl/browser.cl',sourceSha256:hash('manuals/cl/browser.cl'),chapter:'c2h-sockets',procedures:4,observerChecks:5,compiled:load('scripts/evidence/C2h-cl-compile.json')?.mode==='compile',checkMode:load('scripts/evidence/C2h-cl-check.json')?.mode==='check',newPythonOrMjsTestFilesAddedToday:0,scope:'Actual manual.run procedures verify echo, server push, error-before-close with no open on dead port, and blocked-origin policy refusal. Historical proof receipts remain preserved.'};
report.ownerHandoffBoundary='Actual retained-tab and AgentLive resume journey proved on a disposable wall fixture. A queued pane request alone does not prove that the attached Neyvia right pane rendered a public wall.';
report.finalRuntime=load('scripts/evidence/C2h-final-runtime.json');
report.objectiveAchieved=report.fresh36.obscuraOnlyPasses===36;
if(!run?.finishedAt)report.missing.push('Fresh frozen36 run incomplete');if(!grades||grades.draft)report.missing.push('Complete separate post-run grading pending');if(!load('scripts/evidence/C2h-upstream-websocket-tests.json')?.passed)report.missing.push('All13 upstream WebSocket integration cases pending');if(report.fresh36.ownerHandoffs.length)report.missing.push('Paul must resolve retained owner-wall pages; these tasks remain needs_owner');
if(grades?.summary?.failed)report.missing.push(grades.summary.failed+' independently failed tasks; see bound per-clause reasons');
if(report.fresh36.webView2AssistedPasses)report.missing.push('Obscura parity remains unmet: '+report.fresh36.webView2AssistedPasses+' passing tasks still required WebView2');
if(load('scripts/evidence/C2h-owner-pane-failed.json'))report.missing.push('Attached right pane cannot mount isolated runtime tabs; queued public owner handoffs have no rendered acknowledgement');
if(load('scripts/evidence/C2h-native-final-guard.json')?.closed)report.missing.push('Private WebView2 bridge closed after input-guard snapshot timeout; native owner page requires guarded restoration');
if(run?.finishedAt&&!run.sourcesUnchanged)report.missing.push('Executor source changed during frozen36');
fs.writeFileSync('scripts/evidence/C2h.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,completed:report.fresh36.run?.completedTasks,summary:grades?.summary,obscuraOnlyPasses:report.fresh36.obscuraOnlyPasses,webView2AssistedPasses:report.fresh36.webView2AssistedPasses,latency:report.latency,tokens:report.tokens,missing:report.missing}));
