#!/usr/bin/env node
// Explicit proof fixture port selection (int3_ports.py).
import { execFileSync as proofExecFileSync } from 'node:child_process';
import { fileURLToPath as proofFileURLToPath } from 'node:url';
const proofPortSelection = process.env.NEYVIA_PROOF_PORT_MAP === undefined ? null : JSON.parse(proofExecFileSync(
  process.env.NEYVIA_SYSTEM_PYTHON || process.env.PYTHON || 'python',
  [proofFileURLToPath(new URL('../src/grant_agent/proof_ports.py', import.meta.url))],
  { encoding: 'utf8', env: process.env }).trim());
function proofPort(original) { return proofPortSelection === null ? original : proofPortSelection[String(original)]; }
function proofText(text) { return text.replace(/(?<!\d)(48461|48462|48463|48465|48466|48467|48468|48469|48472|48473|48474|48475|48476|48477|48478|48479|48481|48487|48488|48489|48491|48492|48494|48495|48496|48497|48498|48499|48501|48502|48503|48508|48509)(?!\d)/g, value => String(proofPort(Number(value)))); }
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve, delimiter } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { checkedFrontendAction, FrontendContractError, frontendContractBefore, equalContractValue } from "../web/src/neyvia/neyviaFrontendContracts.js";
import { CHAT_CONTRACTS, checkedChatAction, ChatContractError, checkStreamTransition, checkPollDelivery } from "../web/src/neyvia/neyviaChatContracts.js";
import * as stream from "../web/src/neyvia/neyviaChatStream.js";
import * as activity from "../web/src/neyvia/neyviaRunActivity.js";
import * as visual from "../web/src/neyvia/neyviaToolVisuals.js";
import * as presentation from "../web/src/neyvia/neyviaToolCallPresentation.js";
import { WORKSPACE_SURFACES, WORKSPACE_SURFACE_IDS } from "../web/src/neyvia/workspaceModel.js";
const repository = fileURLToPath(new URL("../", import.meta.url));
const python = process.env.NEYVIA_PYTHON || "C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe";
export async function runProofsEChat({ root = resolve(repository, ".agent_control/proofs-e/chat") } = {}) {
  const started = performance.now(), failures = [], procedures = [], observers = [], manifest = JSON.parse(await readFile(resolve(repository, "config/proofs/proofs-e-chat.json"), "utf8"));
  const modules = Object.fromEntries(await Promise.all(Object.entries(manifest.modules).map(async ([key, path]) => [key, await import(new URL(`../${path}`, import.meta.url))]))), seen = new Map();
  await mkdir(root, { recursive: true });
  const require = (okay, msg) => { if (!okay) throw new Error(msg); };
  const reject = (name, action) => { let rejected = false; try { action(); } catch (e) { rejected = e instanceof ChatContractError && e.contract === `proofs-e.chat.${name}`; } observers.push({ id: `proofs-e.chat.${name}`, status: rejected ? "passed" : "failed", corrupt_result_rejected: rejected }); require(rejected, `Semantic corruption escaped ${name}`); };
  const check = (name, args, result, corrupt) => { checkedChatAction(name, args, result); reject(name, () => checkedChatAction(name, args, corrupt)); return result; };
  const procedure = async (id, execute) => { try { const calls = await execute(); procedures.push({ id, status: "passed", calls }); } catch (e) { failures.push({ id, error: e.message }); procedures.push({ id, status: "failed", error: e.message }); } };
  // Previously established recovery procedures use the same production guards.
  for (const p of manifest.procedures.filter(p => p.actions)) await procedure(p.id, async () => {
    let calls = 0;
    for (const action of p.actions) {
      const args = (action.args || []).map(v => v?.$ref ? seen.get(v.$ref) : v?.$set ? new Set(v.$set) : v), before = frontendContractBefore(action.contract, args), result = await modules[action.module][action.function](...args); calls++;
      for (const goal of action.goals || []) { const actual = goal.path ? goal.path.split(".").reduce((v, key) => v?.[key], result) : result; require(goal.match ? new RegExp(goal.match).test(String(actual)) : equalContractValue(actual, goal.value), `Recorded recovery goal ${goal.path || "result"} failed`); }
      if (action.saveAs) seen.set(action.saveAs, result);
      if (action.contract) { let rejected = false; const corrupt = action.corrupt ?? (typeof result === "boolean" ? !result : typeof result === "string" ? result + "\0" : Array.isArray(result) ? [...result, "invalid"] : { ...result, invalid: true }); try { checkedFrontendAction(action.contract, args, corrupt, before); } catch (e) { rejected = e instanceof FrontendContractError && e.contract === action.contract; } observers.push({ id: action.contract, status: rejected ? "passed" : "failed", corrupt_result_rejected: rejected }); require(rejected, `Recovery corruption escaped ${action.contract}`); }
    }
    return calls;
  });
  await procedure("chat.stream-answer-tools-and-receipt", () => {
    const initial = stream.createNeyviaChatStreamState(); check("streamState", [], initial, { ...initial, answer: "invented" });
    const state = stream.createNeyviaChatStreamState(), start = id => ({ kind: "runtime.answer_start", data: { responseId: id, itemId: "item", outputIndex: 0 } });
    stream.applyNeyviaChatStreamEvents(state, [start("first"), { kind: "runtime.answer_delta", message: "I will read." }, { kind: "runtime.reasoning_summary_delta", message: "Inspecting the page." }, { kind: "runtime.tool", data: { callId: "call-1", tool: "workspace_read", toolStatus: "started", input: '{"path":"README.md"}', eventType: "tool_called" } }]);
    require(state.toolCalls.length === 1 && state.toolCalls[0].input === JSON.stringify({ path: "README.md" }, null, 2), "Live tool input disappeared");
    stream.applyNeyviaChatStreamEvents(state, [{ kind: "runtime.tool", data: { callId: "call-1", tool: "workspace_read", toolStatus: "completed", output: "# Real result", eventType: "tool_output" } }, start("second"), { kind: "runtime.answer_delta", message: "État: 東京 " }, start("second"), { kind: "runtime.answer_delta", message: "☀️" }, { kind: "runtime.tool", data: { callId: "call-2", tool: "browser_navigate", toolStatus: "failed", error: "Navigation failed", eventType: "tool_error" } }]);
    require(state.answer === "État: 東京 ☀️" && state.reasoningSummary === "Inspecting the page." && state.toolCalls.length === 2 && state.toolCalls[0].output === "# Real result" && JSON.parse(state.toolCalls[0].input).path === "README.md" && state.toolCalls[1].error === "Navigation failed" && state.toolCalls[1].input === "", "Recorded output or Unicode answer was lost");
    const calls = stream.normalizeNeyviaChatStreamToolCalls(state.toolCalls); check("normalizedCalls", [state.toolCalls], calls, calls.map((c, i) => i === 0 ? { ...c, output: "invented" } : c));
    const before = stream.createNeyviaChatStreamState(), delta = { kind: "runtime.answer_delta", message: "Unicode 東京" }, after = stream.applyNeyviaChatStreamEvents(structuredClone(before), [delta]); reject("streamTransition", () => checkStreamTransition(before, delta, { ...after, answer: "Unicode" }));
    const live = { reasoningSummary: "Inspecting the page.", toolCalls: [{ id: "call-7", tool: "preview.taste", status: "completed", input: proofText('{"url":"http://127.0.0.1:48501"}'), output: "verified" }] }, projected = stream.neyviaChatTraceFields(live), restored = stream.neyviaChatTraceFields({ turnReceipt: { reasoningSummary: live.reasoningSummary, toolTimeline: [{ kind: "runtime.roundtrip", summary: "finished" }, { kind: "runtime.tool", callId: "call-7", tool: "preview.taste", toolStatus: "completed", input: live.toolCalls[0].input, output: "verified" }] } });
    require(equalContractValue(projected, restored), "Receipt replay did not restore the live trace"); check("trace", [live], projected, { ...projected, reasoningSummary: "invented" });
    const failed = stream.neyviaChatTraceFields({ turnReceipt: { toolTimeline: [{ kind: "runtime.tool", callId: "failure", tool: "preview.taste", toolStatus: "completed", output: '{"ok":false,"failure":{"message":"Artifact path invalid"}}' }] } });
    require(failed.toolCalls[0].status === "failed" && failed.toolCalls[0].error === "Artifact path invalid", "Legacy completed receipt hid a failed action");
    const fallback = stream.normalizeNeyviaChatStreamToolCalls([{ kind: "runtime.reasoning_summary", message: "Not a tool" }, { kind: "runtime.tool", data: { callId: "receipt", tool: "browser_navigate", toolStatus: "completed", input: "https://example.test", output: "Loaded" } }]); require(fallback.length === 1 && fallback[0].id === "receipt" && fallback[0].output === "Loaded", "Receipt tool filtering failed");
    return 15;
  });
  await procedure("chat.poll-recovery-and-late-stop", async () => {
    const previous = globalThis.window; globalThis.window = globalThis;
    try {
      let count = 0; const errors = [], state = stream.createNeyviaChatStreamState(); const poll = stream.startNeyviaChatStreamPoll({ turnId: "scratch-turn", intervalMs: 40, poll: async (_id, cursor) => { require(cursor === 0, "Failed poll advanced cursor"); if (++count === 1) throw new Error("bridge unavailable"); return { cursor: 20, events: [{ kind: "runtime.answer_delta", message: "Final text" }, { kind: "runtime.done" }] }; }, onError: e => errors.push(e), onEvents: e => stream.applyNeyviaChatStreamEvents(state, e) }); await poll.done; require(count === 2 && errors.join("|") === "bridge unavailable|" && state.answer === "Final text", "Polling failed to recover/finish");
      let release; const received = [], late = stream.startNeyviaChatStreamPoll({ turnId: "scratch-late", poll: () => new Promise(r => { release = r; }), onEvents: e => received.push(...e) }); await new Promise(r => setImmediate(r)); late.stop(); release({ cursor: 1, events: [{ kind: "runtime.answer_delta", message: "late" }] }); await late.done; require(received.length === 0, "Stopped poll delivered a late response");
      reject("pollDelivery", () => checkPollDelivery({ active: false, events: [{ kind: "runtime.answer_delta" }], cursor: 1, snapshot: { cursor: 1, events: [{ kind: "runtime.answer_delta" }] } })); return 4;
    } finally { if (previous === undefined) delete globalThis.window; else globalThis.window = previous; }
  });
  await procedure("chat.activity-outcomes-and-command-lifecycle", () => {
    for (const status of ["failed", "completed", "cancelled", "uncertain", "blocked", "waiting_approval"]) { const row = { status, tone: status === "failed" || status === "completed" ? "" : "good", pending: status === "failed" }, result = visual.inferNeyviaToolPhase(row); require(result === (status === "failed" ? "error" : status === "completed" ? "success" : "idle"), "Recorded phase was overruled by a hint"); check("phase", [row], result, "composing"); }
    const chip = { label: "tool result success", status: "failed" }, resolved = visual.resolveNeyviaMessageChip(chip); require(resolved.phase === "error" && visual.resolveNeyviaMessageChip("tool result").phase === "idle", "Tool chip inferred success without evidence"); check("chip", [chip], resolved, { ...resolved, phase: "success" });
    const event = { kind: "app_call", name: "mcp__notes__open_document", input: { file: "draft.txt", mode: "read" }, status: "completed" }, view = activity.presentRunActivity(event); require(view.category === "App" && view.title === "Notes · open document" && JSON.parse(view.input).file === "draft.txt" && view.phase === "success" && activity.presentRunActivity({ id: "duplicate" }, 1).key !== activity.presentRunActivity({ id: "duplicate" }, 2).key, "Activity card lost its input/category or identity"); check("activity", [event], view, { ...view, input: "invented" });
    const events = [{ kind: "runtime.answer_delta", message: "Hello" }, { kind: "runtime.progress", message: "Model is responding" }, { kind: "runtime.tool", itemId: "call", tool: "commandExecution", command: "rg --files", goal: "Locate project files", status: "started" }, { kind: "runtime.tool", itemId: "call", tool: "commandExecution", output: "a.txt", status: "completed" }], visible = activity.visibleRunActivityEvents(events), card = activity.presentRunActivity(visible[0]); require(visible.length === 1 && card.input === "rg --files" && card.inputLabel === "Command" && card.output === "a.txt" && card.summary === "Locate project files" && card.phase === "success", "Tool lifecycle split or lost evidence"); check("visibleActivity", [events], visible, [{ ...visible[0], command: "invented" }]);
    check("surfaces", [WORKSPACE_SURFACES], WORKSPACE_SURFACE_IDS, WORKSPACE_SURFACE_IDS.filter(id => id !== "ios-studio")); return 13;
  });
  await procedure("chat.command-file-diff-and-truncated-evidence", () => {
    const input = JSON.stringify({ command: "Get-ChildItem -Force; python --version", shell: "powershell", cwd: "C:/proof/workspace" }), output = JSON.stringify({ ok: true, status: "completed", toolResult: { ok: true, cwd: "C:/proof/workspace", exitCode: 0, durationMs: 1498, stdout: "Mode Length Name\r\n---- ------ ----\r\nPython 3.13.9\r\n", stderr: "" } }), call = { tool: "terminal.exec", status: "completed", input, output }, view = presentation.presentToolCall(call);
    require(view.kind === "command" && view.title === "Ran" && view.subject === "PowerShell" && view.command.cwdLabel === "workspace" && view.command.exitCode === 0 && view.command.durationMs === 1498 && view.command.stdout === "Mode Length Name\n---- ------ ----\nPython 3.13.9" && presentation.commandOutputSummary(view.command) === "exit 0 · 3 lines of output", "Command card hid recorded execution evidence"); check("presentation", [call], view, { ...view, command: { ...view.command, cwd: "C:/invented" } });
    const summary = presentation.commandOutputSummary(view.command); check("commandSummary", [view.command], summary, "exit 1 · 3 lines of output");
    const failed = presentation.presentToolCall({ tool: "terminal.exec", status: "failed", input: JSON.stringify({ command: "wsl.exe -e bash -lc uname", shell: "cmd" }), error: JSON.stringify({ ok: false, status: "failed", failure: { message: "Command exited with code 4294967295." }, toolResult: { exitCode: 4294967295, stderr: "boom" } }) }); require(failed.failed && failed.error === "Command exited with code 4294967295." && failed.command.stderr === "boom" && presentation.commandOutputSummary(failed.command) === "exit -1 · 1 line of output", "Failed command was shown as successful");
    const cut = '{"command":"Get-Content -Raw index.html; Write-Output \\"done\\"; Select-String -Pattern tools… [truncated]', truncated = presentation.presentToolCall({ tool: "neyvia_terminal_exec", status: "started", input: cut }); require(!truncated.command.complete && truncated.command.text === 'Get-Content -Raw index.html; Write-Output "done"; Select-String -Pattern tools', "Truncated command fabricated its missing tail");
    const created = presentation.presentToolCall({ tool: "workspace.write", status: "completed", input: JSON.stringify({ path: "web/index.html", content: "<!doctype html>\n<h1>Hi</h1>\n" }), output: JSON.stringify({ ok: true, status: "created", path: "web/index.html", linesAdded: 2, linesRemoved: 0 }) }); require(created.title === "Created" && created.subject === "index.html" && created.diffs[0].added === 2 && equalContractValue(created.diffs[0].lines.map(l => [l.type, l.number, l.text]), [["add", 1, "<!doctype html>"], ["add", 2, "<h1>Hi</h1>"]]), "Created file lines were not numbered");
    const diff = "--- a/api.py\n+++ b/api.py\n@@ -10,3 +10,4 @@\n def run():\n-    return 1\n+    return 2\n+    # done\n pass", edited = presentation.presentToolCall({ tool: "neyvia_workspace_write", status: "completed", input: JSON.stringify({ path: "api.py", content: "…", expectedSha256: "a".repeat(64) }), output: JSON.stringify({ ok: true, status: "updated", path: "api.py", diff, linesAdded: 2, linesRemoved: 1 }) }); require(edited.title === "Edited" && edited.diffs[0].added === 2 && edited.diffs[0].removed === 1 && equalContractValue(edited.diffs[0].lines.map(l => [l.type, l.number ?? null]), [["hunk", null], ["ctx", 10], ["del", 11], ["add", 11], ["add", 12], ["ctx", 13]]), "Recorded hunk line numbers changed");
    const parsed = presentation.parseUnifiedDiff(diff); check("diff", [diff], parsed, { ...parsed, lines: parsed.lines.map((l, i) => i === 2 ? { ...l, number: 12 } : l) });
    const pending = presentation.presentToolCall({ tool: "workspace.write", status: "started", input: JSON.stringify({ path: "api.py", content: "new body", expectedSha256: "b".repeat(64) }) }); require(pending.title === "Edited" && pending.diffs.length === 0, "An existing file was misrepresented as newly created");
    const replace = presentation.presentToolCall({ tool: "edit", status: "completed", input: JSON.stringify({ filePath: "src/a.js", oldString: "const a = 1;\nconst b = 2;", newString: "const a = 1;\nconst b = 3;" }) }); require(replace.diffs[0].lines.map(l => l.type).join() === "ctx,del,add", "String replacement lost unchanged context");
    const patch = presentation.presentToolCall({ tool: "apply_patch", status: "completed", input: JSON.stringify({ input: "*** Begin Patch\n*** Update File: src/b.js\n@@\n-old\n+new\n*** Add File: src/c.js\n+hello\n*** End Patch" }) }); require(patch.diffs.length === 2 && patch.subject === "b.js and 1 more" && patch.diffs[1].status === "created", "Patch files collapsed incorrectly");
    for (const [tool, family] of [["neyvia_workspace_read", "read"], ["command_execution", "command"], ["bash", "command"], ["mcp.neyvia.workspace_write", "write"], ["web.search", "search"]]) { require(presentation.toolFamily(tool) === family, "Harness prefix changed a tool family"); check("family", [tool], family, "generic"); }
    const read = presentation.presentToolCall({ tool: "neyvia_workspace_read", status: "completed", input: JSON.stringify({ path: "C:/proof/README.md" }), output: JSON.stringify({ tool: "workspace.read", ok: true, result: { path: "README.md", content: "# Title\nBody" } }) }); require(read.title === "Read" && read.subject === "README.md" && read.lineCount === 2, "Read card lost content line count");
    const damaged = " \u0000N\u0000A\u0000M\u0000E\u0000"; check("utf16", [damaged], presentation.repairUtf16Text(damaged), "NAME"); require(presentation.repairUtf16Text(damaged) === " NAME" && presentation.repairUtf16Text("plain") === "plain", "UTF-16 evidence was not repaired");
    const source = '{"path":"C:\\\\x\\\\y.txt"}', field = presentation.readJsonStringField(source, "path"); check("stringField", [source, "path"], field, { value: "C:/invented", complete: true }); require(field.value === "C:\\x\\y.txt" && field.complete && equalContractValue(presentation.readJsonStringField('{"path":"C:\\\\x\\', "path"), { value: "C:\\x", complete: false }) && presentation.readJsonStringField('{"other":"v"}', "path") === null && presentation.parseUnifiedDiff("@@ -1 +1 @@\n-a\n+b").added === 1, "Lenient field decoding lost escape boundaries"); return 23;
  });
  await procedure("chat.local-media-safety-and-desktop-cursor", async () => {
    const env = { ...process.env, PYTHONPATH: [resolve(repository, "src"), process.env.PYTHONPATH].filter(Boolean).join(delimiter), PYTHONDONTWRITEBYTECODE: "1", NEYVIA_UI_BACKEND_URL: proofText("http://127.0.0.1:48501"), NEYVIA_TOOL_AUTO_UPDATE: "0", FLUXIO_WATCHDOG_AUTOSTART: "0", NEYVIA_COORDINATOR_AUTOSTART: "0" };
    const code = `import json,sys,copy\nfrom grant_agent.chat_stream import safe_tool_display\nfrom grant_agent.proofs_e_chat import check_tool_display,check_read_snapshot,ChatContractViolation\nv=json.load(sys.stdin);old=copy.deepcopy(v);shown=safe_tool_display(v);decoded=json.loads(shown);assert decoded['image_url']=='[image/png payload omitted from activity]' and decoded['note']=='Rendered page' and decoded['api_key']=='[REDACTED]' and v==old and len(v['image_url'])==20022\nchecks=[]\nfor f in (lambda:check_tool_display(v,12000,shown.replace('Rendered page','Invented page')),lambda:check_read_snapshot('fixture-turn',0,b'{"kind":"runtime.answer_delta","message":"a"}\\n',{'events':[],'cursor':0,'ready':True})):\n try:f();checks.append(False)\n except ChatContractViolation:checks.append(True)\nassert all(checks)\nprint(json.dumps({'ok':True,'displayRejection':checks[0],'cursorRejection':checks[1]}))`;
    const safe = spawnSync(python, ["-c", code], { cwd: repository, input: JSON.stringify({ image_url: "data:image/png;base64," + "AAAA".repeat(5000), note: "Rendered page", api_key: "fixture-secret" }), encoding: "utf8", env, windowsHide: true }); require(safe.status === 0, "Backend display/cursor semantic guard failed");
    for (const name of ["safe-display", "desktop-stream"]) observers.push({ id: `proofs-e.chat.${name}`, status: "passed", corrupt_result_rejected: true });
    const directory = resolve(root, ".agent_control/chat_streams"); await mkdir(directory, { recursive: true }); const path = resolve(directory, "fixture_turn-1.jsonl"), firstRow = JSON.stringify({ kind: "runtime.answer_delta", message: "Déjà vu 🌈" }) + "\n", prefix = '{"kind":"runtime.answer_delta","message":"second'; await writeFile(path, firstRow + prefix);
    const poll = payload => spawnSync(python, ["-m", "grant_agent.desktop_bridge", "--root", resolve(root)], { cwd: repository, input: JSON.stringify({ command: "get_agent_chat_stream_command", payload }), encoding: "utf8", env, windowsHide: true, maxBuffer: 4 * 1024 * 1024 });
    const one = poll({ turnId: "fixture_turn-1", cursor: 0 }); require(one.status === 0, "Flat desktop poll failed"); const first = JSON.parse(one.stdout).data; require(first.events.length === 1 && first.events[0].message === "Déjà vu 🌈" && first.cursor === Buffer.byteLength(firstRow), "Desktop cursor consumed a partial UTF-8 row");
    await writeFile(path, firstRow + prefix + ' row"}\n'); const two = poll({ payload: { turnId: "fixture_turn-1", cursor: first.cursor } }); require(two.status === 0, "Wrapped desktop poll failed"); const second = JSON.parse(two.stdout).data; require(second.events.length === 1 && second.events[0].message === "second row" && second.cursor === Buffer.byteLength(await readFile(path)), "Wrapped desktop replay duplicated or lost events");
    const bad = poll({ payload: { turnId: "../outside", cursor: 0 } }); require(bad.status === 1 && /Invalid chat turn id/.test(JSON.parse(bad.stdout).error), "Unsafe turn id escaped the desktop stream boundary"); return 4;
  });
  for (const { id } of manifest.contracts) if (!observers.some(o => o.id === id && o.status === "passed")) failures.push({ id, error: "Missing real semantic rejection witness" });
  const report = { area: manifest.area, status: failures.length ? "failed" : "passed", ok: !failures.length, scratchRoot: resolve(root), contractCount: manifest.contracts.length, contracts: manifest.contracts.map(({ id }) => ({ id, status: observers.some(o => o.id === id && o.status === "passed") ? "passed" : "failed" })), procedures, observers, coverage: manifest.coverage, elapsedMs: Math.round((performance.now() - started) * 100) / 100, failures, boundary: manifest.frontier };
  await writeFile(resolve(root, "proofs-e-chat-receipt.json"), JSON.stringify(report, null, 2) + "\n"); return report;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { const args = process.argv.slice(2), at = args.indexOf("--root"); if (at >= 0 && !args[at + 1]) throw Error("--root requires directory"); const report = await runProofsEChat({ root: at >= 0 ? resolve(args[at + 1]) : undefined }); console.log(JSON.stringify(report, null, args.includes("--json") ? 0 : 2)); process.exitCode = report.ok ? 0 : 1; }
