/* Actual production Evolver UI over authenticated copy-only historical T13 state. Never runs a trial. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
const repo=path.resolve(__dirname,'..'),port=48668,cdp=48664,base=`http://127.0.0.1:${port}`;
const root=path.join(repo,'.agent_control/proofs/evolver-ui-'+Date.now()),staticRoot=path.join(root,'static');
const output=path.join(repo,'scripts/evidence/FIX-evolver-ui.json'),nativePath=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe');
const original=path.join(repo,'scripts/evidence/T13-runs/evolver.sqlite3'),copied=path.join(root,'.neyvia/evolver.sqlite3');
const sealed=JSON.parse(fs.readFileSync(path.join(repo,'scripts/evidence/T13-runs/state.json')));
const env={...process.env,PYTHONPATH:path.join(repo,'src'),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),PYTHONUNBUFFERED:'1'};
const receipt={scope:'FIX-evolver-ui',ports:[port,cdp],root,startedAt:new Date().toISOString(),boundary:'Actual production NxEvolver in disposable WebView2, authenticated real backend, byte-exact copy of sealed T13 SQLite state. Observation only: no trials, models, judge edits, incumbent edits or promotion. Historical results retain original T13 limits.',checks:[],pictures:[],calls:[],sources:{},nativeCommandAllowList:['evolver_state_command','evolver_lineage_command','evolver_receipt_command','evolver_genome_command','evolver_job_command']};
let backend,native,browser,page,cookie;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function save(){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');}
async function eventual(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await sleep(150);}throw Error('Expected real UI transition timed out');}
async function request(route,body){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await response.json();receipt.calls.push({route,body:body||{},status:response.status,data});return {response,data};}
async function command(command,payload={}){assert.ok(!command.includes('_run_'),'Trial calls prohibited');const {response,data}=await request('/api/backend',{command,payload});assert.equal(response.status,200,JSON.stringify(data));return data.data??data;}
async function check(name,fn){try{const detail=await fn();receipt.checks.push({name,ok:true,detail});save();return detail;}catch(e){receipt.checks.push({name,ok:false,error:e.stack});save();throw e;}}
async function picture(name){const target=path.join(repo,'scripts/evidence/fix/evolver-ui-'+name+'.png');await page.screenshot({path:target});receipt.pictures.push({path:path.relative(repo,target),sha256:hash(target)});save();}
async function kill(child){if(child&&child.exitCode===null&&child.signalCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
const snapshot=state=>state.domains.map(d=>({id:d.id,incumbent:d.incumbent,trials:d.trials,evaluations:d.evaluations,active_trial:d.active_trial,manifest_hash:d.manifest_hash,lineage:d.lineage,receipts:d.receipts,pareto_front:d.pareto_front}));
async function selectDomain(name){await page.getByRole('radiogroup',{name:'What is being improved',exact:true}).getByRole('radio',{name,exact:true}).click();await page.getByRole('heading',{name,exact:true}).waitFor();}
async function main(){
  fs.mkdirSync(path.dirname(copied),{recursive:true});fs.copyFileSync(original,copied);receipt.stateCopy={source:path.relative(repo,original),destination:copied,sha256:hash(original),copiedSha256:hash(copied)};assert.equal(hash(original),hash(copied));
  fs.mkdirSync(staticRoot,{recursive:true});fs.cpSync(path.join(repo,'.agent_control/fix/evolver-ui/dist'),staticRoot,{recursive:true});
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventual(async()=>{if(backend.exitCode!==null)throw Error('Backend exited '+backend.exitCode);try{return (await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},60000);
  await check('Unauthenticated historical Evolver observer is refused',async()=>{const {response,data}=await request('/api/ui/evolver');assert.equal(response.status,401);return {status:response.status,error:data.error};});
  const login=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.ok(login.ok);cookie=login.headers.get('set-cookie').split(';')[0];
  const before=await command('evolver_state_command');
  await check('Exact copied historical T13 state is served by real authenticated backend',async()=>{assert.deepEqual(snapshot(before),snapshot(sealed.state));assert.ok(before.domains.every(d=>!d.active_trial));return {domains:before.domains.map(d=>({id:d.id,trials:d.trials,incumbent:d.incumbent,frozen_lock:d.frozen_lock})),copy:receipt.stateCopy};});
  const connected=await request('/api/ui/browser',{op:'runtime.connect',args:{}});assert.equal(connected.data.ok,true);
  const nativeLog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(nativePath,[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.data.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/ui-proof.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:'evolver_state_command,evolver_lineage_command,evolver_receipt_command,evolver_genome_command,evolver_job_command',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`},windowsHide:true,stdio:['ignore',nativeLog,nativeLog]});fs.closeSync(nativeLog);
  await eventual(async()=>{if(native.exitCode!==null)throw Error('Native exited '+native.exitCode);try{return (await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},30000);
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventual(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().includes('/ui-proof.html')));
  receipt.console=[];page.on('pageerror',error=>receipt.console.push(error.message));
  await page.getByRole('radiogroup',{name:'What is being improved',exact:true}).waitFor({timeout:30000});
  await check('Domain switching shows separate current manual and CL historical outcomes',async()=>{
    await selectDomain('Notes manual');const manual=before.domains.find(d=>d.id==='manual_compression_v2');await page.locator('.nx-evo-hero').getByText('Accepted',{exact:true}).waitFor();assert.match(await page.locator('.nx-evo-hero').textContent(),new RegExp(manual.incumbent.slice(0,8)));await picture('manual-current');
    await selectDomain('Design CL-Skill');const cl=before.domains.find(d=>d.id==='cl_skill_v3');await page.locator('.nx-evo-hero').getByText('Rejected',{exact:true}).waitFor();assert.match(await page.locator('.nx-evo-hero').textContent(),new RegExp(cl.incumbent.slice(0,8)));await picture('cl-rejected');return {manualIncumbent:manual.incumbent,clIncumbent:cl.incumbent,clPromoted:cl.receipts.at(-1).promoted};
  });
  await check('Expanded real paired receipt preserves rejected CL verdict and measured seeds',async()=>{
    const trial=page.locator('.nx-evo-trial').filter({has:page.getByRole('button',{name:/Trial 1/})}).first();await trial.locator('.nx-evo-trial-head').click();await trial.getByRole('button',{name:/10 task pairs, same task and seed/}).last().click();const rows=trial.locator('.is-pairs tbody tr');assert.equal(await rows.count(),10);const cl=before.domains.find(d=>d.id==='cl_skill_v3');const last=cl.receipts.at(-1).stages.at(-1);assert.match(await rows.first().textContent(),new RegExp(String(last.pairs[0].seed)));await picture('paired-receipt');return {receiptId:cl.receipts.at(-1).id,state:cl.receipts.at(-1).state,pairs:await rows.count(),firstSeed:last.pairs[0].seed};
  });
  await check('Lineage reads hash-checked exact stored seed genome and candidate parent diff',async()=>{
    const d=before.domains.find(d=>d.id==='cl_skill_v3');const seed=d.lineage.find(n=>!n.parent),candidate=d.lineage.find(n=>n.parent);assert.ok(seed&&candidate);
    await page.locator('.nx-evo-node-row').filter({hasText:seed.genome.slice(0,8)}).click();const genome=await command('evolver_genome_command',{domain:d.id,genome:seed.genome});await page.locator('.nx-evo-text').waitFor();assert.equal(await page.locator('.nx-evo-text').textContent(),genome.genome.text);await picture('lineage-genome');
    await page.locator('.nx-evo-node-row').filter({hasText:candidate.genome.slice(0,8)}).click();await page.getByRole('region',{name:'Changes from the parent version',exact:true}).waitFor();assert.ok(await page.locator('.nx-evo-diff-line.is-add').count()>0);await picture('lineage-diff');return {seedGenome:seed.genome,candidateGenome:candidate.genome,parent:candidate.parent,exactSeedText:true};
  });
  await check('Historical version refusal disables trial control without dispatching a run',async()=>{
    await page.getByRole('radiogroup',{name:'Version',exact:true}).getByRole('radio',{name:'v1',exact:true}).click();await page.getByText(/Trials run only on the current version/).waitFor();assert.equal(await page.getByRole('button',{name:'Run a trial',exact:true}).isDisabled(),true);assert.match(await page.locator('.nx-evo-note-bar').textContent(),/not combined with v3/);await page.locator('.nx-evo').evaluate(e=>e.scrollTop=0);await picture('historical-lock');return {disabled:true,explanation:await page.locator('.nx-evo-budget-note').textContent(),trialCommandExcludedFromNativeAllowList:true};
  });
  await check('Reload preserves selected domain/version and real receipts without new trials',async()=>{
    await page.reload();await page.getByRole('heading',{name:'Design CL-Skill',exact:true}).waitFor();assert.equal(await page.getByRole('radio',{name:'v1',exact:true}).getAttribute('aria-checked'),'true');assert.equal(await page.getByRole('button',{name:'Run a trial',exact:true}).isDisabled(),true);
    const after=await command('evolver_state_command');assert.deepEqual(snapshot(before),snapshot(after));assert.equal(hash(copied),receipt.stateCopy.sha256);assert.equal(hash(original),receipt.stateCopy.sha256);assert.ok(!fs.existsSync(path.join(root,'.neyvia/evolver-jobs')));await picture('reload');return {unchangedExactState:true,unchangedDatabase:true,noJobCreated:true};
  });
  for(const file of ['web/src/neyvia/next/NxEvolver.jsx','web/src/neyvia/next/NxEvolverParts.jsx','web/src/neyvia/next/nxEvolverModel.js','web/src/neyvia/next/nxEvolver.css','web/src/neyvia/next/nxApi.js','src/grant_agent/neyvia_evolver.py','src/grant_agent/evolver_core.py','scripts/browser-probe/src/main.rs','scripts/prove_fix_evolver_ui_build.mjs','scripts/prove_fix_evolver_ui.cjs'])receipt.sources[file]=hash(path.join(repo,file));receipt.nativeBinarySha256=hash(nativePath);receipt.finishedAt=new Date().toISOString();receipt.ok=receipt.checks.every(c=>c.ok);save();
}
main().catch(e=>{receipt.error=e.stack;receipt.ok=false;save();process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await kill(native);await kill(backend);receipt.ownedProcessesStopped={native:!native||native.exitCode!==null||native.signalCode!==null,backend:!backend||backend.exitCode!==null||backend.signalCode!==null};save();});
