/* Production Browser components in an actual owned main WebView2, with real owner backend IPC. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
const repo=path.resolve(__dirname,'..'),port=48667,cdp=48664,base=`http://127.0.0.1:${port}`;
const root=path.join(repo,'.agent_control/proofs/browser-permissions-'+Date.now()),staticRoot=path.join(root,'static');
const output=path.join(repo,'scripts/evidence/FIX-browser-permissions.json');
const nativePath=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe');
const env={...process.env,PYTHONPATH:path.join(repo,'src'),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_BROWSER_PROOF_PORTS:String(port),NEYVIA_BROWSER_SHIELD_HOSTS:JSON.stringify(['localhost']),NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),PYTHONUNBUFFERED:'1'};
const receipt={scope:'FIX-browser-permissions',ports:[port,cdp],root,startedAt:new Date().toISOString(),boundary:'Actual production NxBrowser rendered in disposable native main WebView2. Isolated proof host forwards reviewed IPC to authenticated actual owner backend; no installed desktop/public release claim.',checks:[],pictures:[],calls:[],sources:{}};
let backend,native,browser,page,cookie;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sanitize=value=>JSON.parse(JSON.stringify(value,(k,v)=>/token|password|cookie/i.test(k)?'[masked]':v));
function save(){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');}
async function request(route,body){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await response.json();receipt.calls.push({route,body:sanitize(body||{}),status:response.status,data:sanitize(data)});return {response,data};}
async function op(op,args={}){const {response,data}=await request('/api/ui/browser',{op,args});assert.equal(response.status,200,JSON.stringify(data));assert.equal(data.ok,true,JSON.stringify(data));return data;}
async function eventual(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await sleep(150);}throw Error('Expected real UI transition timed out');}
async function complete(row){if(!row.actionId)return row;return eventual(async()=>{const data=await op('action.get',{actionId:row.actionId});if(data.status==='failed')throw Error(JSON.stringify(data));return data.status==='done'?data:false;});}
async function observe(tabId){const done=await complete(await op('observe',{tabId}));return done.result?.observation;}
async function stateTab(tabId){return (await op('state')).tabs.find(t=>t.id===tabId);}
async function check(name,fn){try{const detail=await fn();receipt.checks.push({name,ok:true,detail});save();return detail;}catch(e){receipt.checks.push({name,ok:false,error:e.stack});save();throw e;}}
async function picture(name){const target=path.join(repo,'scripts/evidence/fix/browser-permissions-'+name+'.png');await page.screenshot({path:target});receipt.pictures.push({path:path.relative(repo,target),sha256:hash(target)});save();}
async function kill(child){if(child&&child.exitCode===null&&child.signalCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
async function main(){
  fs.mkdirSync(staticRoot,{recursive:true});fs.cpSync(path.join(repo,'.agent_control/fix/browser-permissions/dist'),staticRoot,{recursive:true});
  fs.writeFileSync(path.join(staticRoot,'permission.html'),`<!doctype html><title>Native Notification consent fixture</title><h1>Notification consent fixture</h1><button id="request" onclick="ask()">Request notifications</button><p id="result">not requested</p><p id="ipc">IPC pending</p><p id="event">Event forgery pending</p><script>if(window.__TAURI_INTERNALS__)window.__TAURI_INTERNALS__.invoke('browser_page_event',{event:{type:'permission',requestId:'permission-page-forged',state:'allowed',nativeAcknowledged:true,savedInProfile:false}}).then(()=>document.querySelector('#event').textContent='native event forgery ALLOWED',()=>document.querySelector('#event').textContent='native event forgery denied');if(window.__TAURI_INTERNALS__)window.__TAURI_INTERNALS__.invoke('browser_call_command',{op:'permission.answer',args:{decision:'allow'}}).then(()=>document.querySelector('#ipc').textContent='foreign consent ALLOWED',()=>document.querySelector('#ipc').textContent='foreign consent denied');async function ask(){document.querySelector('#result').textContent='waiting for owner';try{const result=await Notification.requestPermission();document.querySelector('#result').textContent='Native Notification result: '+result+'; observed permission: '+Notification.permission}catch(e){document.querySelector('#result').textContent='Native error: '+e.message}};addEventListener('DOMContentLoaded',ask);</script>`);
  fs.writeFileSync(path.join(staticRoot,'next.html'),'<title>Different native navigation</title><h1>Different native page; no request</h1>');
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventual(async()=>{if(backend.exitCode!==null)throw Error('Backend exited '+backend.exitCode);try{return (await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},60000);
  const login=await request('/api/auth/local-session',{});cookie=login.response.headers.get('set-cookie').split(';')[0];
  const connected=await op('runtime.connect');const opened=await op('tab.open',{url:base+'/permission.html'});const tabId=opened.tabId;
  const nativeLog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(nativePath,[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/ui-proof.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:'browser_call_command',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`},windowsHide:true,stdio:['ignore',nativeLog,nativeLog]});fs.closeSync(nativeLog);
  await eventual(async()=>{if(native.exitCode!==null)throw Error('Native exited '+native.exitCode);try{return (await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},30000);
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventual(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().includes('/ui-proof.html')));
  receipt.console=[];page.on('pageerror',error=>receipt.console.push(error.message));
  await page.getByRole('button',{name:'Privacy for this site',exact:true}).waitFor({timeout:30000});await complete(opened);
  const pending=async(tabId)=>eventual(async()=>(await op('permissions',{tabId})).requests.find(r=>r.state==='pending'),20000);
  const decision=row=>({requestId:row.requestId,origin:row.origin,profileId:row.profileId,navigationEpoch:row.navigationEpoch});
  const outcome=async(tabId,expected)=>eventual(async()=>{const o=await observe(tabId);return o?.text.includes('Native Notification result: '+expected)?o:false},45000);
  let first;
  await check('Actual WebView2 Notification callback becomes a bounded owner UI request',async()=>{first=await pending(tabId);assert.equal(first.kind,'notifications');assert.equal(first.savedInProfile,false);assert.equal(first.origin,base);assert.equal(first.private,false);await page.getByLabel('Website permission requests').waitFor();await picture('pending');return first;});
  await check('Wrong profile and origin decisions refuse without consuming native request',async()=>{for(const args of [{...decision(first),profileId:'foreign'},{...decision(first),origin:'http://localhost:'+port}]){const bad=await request('/api/ui/browser',{op:'permission.answer',args:{...args,decision:'allow'}});assert.equal(bad.data.ok,false);assert.equal(bad.data.error.code,'wrong_permission_scope');}assert.equal((await pending(tabId)).requestId,first.requestId);return {pendingUnchanged:true};});
  await check('Discovered model pending read is read-only; a tab grant never supplies permission consent',async()=>{
    const catalog=await request('/api/ui/tools');const read=catalog.data.data.tools.find(t=>t.name==='neyvia.browser.permissions');assert.equal(read.mutability,'read');
    const answer=catalog.data.data.tools.find(t=>t.name==='neyvia.browser.permission_answer');assert.equal(answer.mutability,'external_action');
    await complete(await op('tab.grant',{tabId,enabled:true}));
    const observed=await request('/api/ui/tools/call',{tool:'neyvia.browser.permissions',arguments:{requestId:first.requestId}});assert.equal(observed.data.ok,true,JSON.stringify(observed.data));assert.match(JSON.stringify(observed.data),/pending/);
    const refused=await request('/api/ui/tools/call',{tool:'neyvia.browser.permission_answer',arguments:{...decision(first),decision:'allow'}});assert.equal(refused.data.ok,false);assert.match(JSON.stringify(refused.data),/owner|human|consent/i);
    assert.equal((await pending(tabId)).requestId,first.requestId);return {definition:read,modelRead:observed.data,modelRefusal:refused.data,tabGrantNotConsent:true};
  });
  await check('Actual foreign native page cannot invoke owner permission answering; anonymous/runtime forgeries refuse',async()=>{
    const projection=await observe(tabId);assert.match(projection.text,/foreign consent denied/);assert.match(projection.text,/native event forgery denied/);assert.equal((await op('permissions',{requestId:'permission-page-forged'})).requests.length,0);
    const anonymous=await fetch(base+'/api/ui/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'permission.answer',args:{...decision(first),decision:'allow'}})});assert.equal(anonymous.status,401);
    const forged=await request('/api/ui/browser/runtime',{token:'invalid-permission-runtime',op:'report',event:{type:'permission',requestId:first.requestId,state:'allowed'}});assert.equal(forged.response.status,403);
    return {projection,anonymous:anonymous.status,forgedRuntime:forged.data};
  });
  const manual=async(row,extra={},expectOk=true)=>{const result=await request('/api/ui/tools/call',{tool:'neyvia.manual.run',arguments:{id:'browser',chapter:'backend',procedure:'review-native-permission',inputs:{requestId:row.requestId},...extra}});assert.equal(result.data.ok,expectOk,JSON.stringify(result.data));return result.data.data.result??result.data.data;};
  await check('Authored CL human judgement cannot turn a pending native request into successful consent',async()=>{const run=await manual(first);assert.equal(run.status,'judge');const attempted=await manual(first,{runId:run.runId,decisions:{'website-consent':'allow'}},false);assert.equal(attempted.status,'failed');assert.equal((await pending(tabId)).requestId,first.requestId);return {run,attempted};});
  await check('Production owner Allow reaches the held native callback and real Notification promise',async()=>{await page.getByRole('button',{name:'Allow notifications for '+base,exact:true}).click();const projection=await outcome(tabId,'granted');const row=await eventual(async()=>(await op('permissions',{requestId:first.requestId})).requests.find(r=>r.state==='allowed'));assert.equal(row.nativeAcknowledged,true);await picture('allowed');return {row,projection};});
  await check('Authored CL independently verifies the actual acknowledged owner decision',async()=>{const run=await manual(first);assert.equal(run.status,'judge');const completed=await manual(first,{runId:run.runId,decisions:{'website-consent':'allow'}});assert.equal(completed.status,'completed',JSON.stringify(completed));return completed;});
  await check('Reload requires a new native consent and production owner Deny reaches the actual promise',async()=>{await complete(await op('tab.reload',{tabId}));const row=await pending(tabId);assert.notEqual(row.requestId,first.requestId);await page.getByRole('button',{name:'Deny notifications for '+base,exact:true}).click();const projection=await outcome(tabId,'denied');const result=await eventual(async()=>(await op('permissions',{requestId:row.requestId})).requests.find(r=>r.state==='denied'));assert.equal(result.nativeAcknowledged,true);await picture('denied');return {result,projection,notRemembered:true};});
  await check('Navigation invalidates pending consent; old Allow cannot grant a different page',async()=>{await complete(await op('tab.reload',{tabId}));const row=await pending(tabId);await complete(await op('tab.navigate',{tabId,url:base+'/next.html'}));await eventual(async()=>{const tab=await stateTab(tabId);return !tab.loading&&tab.url.endsWith('/next.html')});const refused=await request('/api/ui/browser',{op:'permission.answer',args:{...decision(row),decision:'allow'}});assert.equal(refused.data.ok,false);assert.equal(refused.data.error.code,'stale_permission');return {refused:refused.data,request:(await op('permissions',{requestId:row.requestId})).requests,projection:await observe(tabId)};});
  await check('Pending native request expires to actual deny, with no blanket default grant',async()=>{await complete(await op('tab.navigate',{tabId,url:base+'/permission.html?timeout=1'}));const row=await pending(tabId);const projection=await outcome(tabId,'denied');const result=(await op('permissions',{requestId:row.requestId})).requests[0];assert.equal(result.state,'denied');assert.match(result.reason,/expired/);assert.equal(result.nativeAcknowledged,true);return {result,projection};});
  await check('Private pending request stays isolated and closing removes profile and request state',async()=>{const opened=await op('tab.open',{url:base+'/permission.html?private=1',private:true});await complete(opened);const row=await pending(opened.tabId);assert.equal(row.private,true);await complete(await op('tab.close',{tabId:opened.tabId}));assert.equal((await op('permissions',{tabId:opened.tabId})).requests.length,0);assert.equal(fs.existsSync(path.join(root,'.neyvia/browser/private',opened.tabId)),false);const saved=JSON.parse(fs.readFileSync(path.join(root,'.neyvia/browser/state.json')));assert.equal(Object.hasOwn(saved,'permissions'),false);return {privateRequestId:row.requestId,profileRemoved:true,requestsNotPersisted:true};});
  for(const file of ['src-tauri/src/browser_runtime.rs','scripts/browser-probe/src/main.rs','src/grant_agent/neyvia_browser.py','web/src/neyvia/next/NxBrowser.jsx','web/src/neyvia/next/NxBrowserParts.jsx','web/src/neyvia/next/nxBrowserApi.js','web/src/neyvia/next/nxBrowser.css','src/grant_agent/neyvia_workspace_tools.py','manuals/cl/browser.cl','scripts/prove_fix_browser_permissions_build.mjs','scripts/prove_fix_browser_permissions.cjs'])receipt.sources[file]=hash(path.join(repo,file));receipt.nativeBinarySha256=hash(nativePath);receipt.finishedAt=new Date().toISOString();receipt.ok=receipt.checks.every(c=>c.ok);save();
}
main().catch(e=>{receipt.error=e.stack;receipt.ok=false;save();process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await kill(native);await kill(backend);receipt.ownedProcessesStopped={native:!native||native.exitCode!==null||native.signalCode!==null,backend:!backend||backend.exitCode!==null||backend.signalCode!==null};save();});
