/* Production Browser components in an actual owned main WebView2, with real owner backend IPC. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
const repo=path.resolve(__dirname,'..'),port=48668,cdp=48664,base=`http://127.0.0.1:${port}`;
const root=path.join(repo,'.agent_control/proofs/browser-ui-'+Date.now()),staticRoot=path.join(root,'static');
const output=path.join(repo,'scripts/evidence/FIX-browser-ui.json');
const nativePath=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe');
const env={...process.env,PYTHONPATH:path.join(repo,'src'),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_BROWSER_PROOF_PORTS:String(port),NEYVIA_BROWSER_SHIELD_HOSTS:JSON.stringify(['localhost']),NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),PYTHONUNBUFFERED:'1'};
const receipt={scope:'FIX-browser-ui',ports:[port,cdp],root,startedAt:new Date().toISOString(),boundary:'Actual production NxBrowser rendered in disposable native main WebView2. Isolated proof host forwards reviewed IPC to authenticated actual owner backend; no installed desktop/public release claim.',checks:[],pictures:[],calls:[],sources:{}};
let backend,native,browser,page,cookie;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sanitize=value=>JSON.parse(JSON.stringify(value,(k,v)=>/token|password|cookie/i.test(k)?'[masked]':v));
function save(){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');}
async function request(route,body){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await response.json();receipt.calls.push({route,body:sanitize(body||{}),status:response.status,data:sanitize(data)});return {response,data};}
async function op(op,args={}){const {response,data}=await request('/api/ui/browser',{op,args});assert.equal(response.status,200,JSON.stringify(data));assert.equal(data.ok,true,JSON.stringify(data));return data;}
async function eventual(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await sleep(150);}throw Error('Expected real UI transition timed out');}
async function complete(row){if(!row.actionId)return row;return eventual(async()=>{const data=await op('action.get',{actionId:row.actionId});if(data.status==='failed')throw Error(JSON.stringify(data));return data.status==='done'?data:false;});}
async function observe(tabId){const done=await complete(await op('observe',{tabId}));return done.result?.observation;}
async function stateTab(tabId){return (await op('state')).tabs.find(t=>t.id===tabId);}
async function check(name,fn){try{const detail=await fn();receipt.checks.push({name,ok:true,detail});save();return detail;}catch(e){receipt.checks.push({name,ok:false,error:e.stack});save();throw e;}}
async function picture(name){const target=path.join(repo,'scripts/evidence/fix/browser-ui-'+name+'.png');await page.screenshot({path:target});receipt.pictures.push({path:path.relative(repo,target),sha256:hash(target)});save();}
async function kill(child){if(child&&child.exitCode===null&&child.signalCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
async function main(){
  fs.mkdirSync(staticRoot,{recursive:true});fs.cpSync(path.join(repo,'.agent_control/fix/browser-ui/dist'),staticRoot,{recursive:true});
  fs.writeFileSync(path.join(staticRoot,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="green"/></svg>');
  fs.writeFileSync(path.join(staticRoot,'tracker.js'),'document.querySelector("#network").textContent="tracker loaded";');
  fs.writeFileSync(path.join(staticRoot,'page.html'),`<!doctype html><title>Private protection fixture</title><link rel="icon" href="${base}/favicon.svg"><style>body{font:24px system-ui;padding:40px;background:#e9f3ed;color:#123b28}</style><h1>Real page behind Browser UI</h1><p id="network">request pending</p><script>const tracker=document.createElement('script');tracker.src='http://localhost:${port}/tracker.js?nonce='+Date.now();tracker.onerror=()=>document.querySelector('#network').textContent='tracker blocked';document.head.append(tracker);</script>`);
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventual(async()=>{if(backend.exitCode!==null)throw Error('Backend exited '+backend.exitCode);try{return (await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},60000);
  const login=await request('/api/auth/local-session',{});cookie=login.response.headers.get('set-cookie').split(';')[0];
  const connected=await op('runtime.connect');const opened=await op('tab.open',{url:base+'/page.html'});const tabId=opened.tabId;
  const nativeLog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(nativePath,[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/ui-proof.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:'browser_call_command',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`},windowsHide:true,stdio:['ignore',nativeLog,nativeLog]});fs.closeSync(nativeLog);
  await eventual(async()=>{if(native.exitCode!==null)throw Error('Native exited '+native.exitCode);try{return (await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},30000);
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventual(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().includes('/ui-proof.html')));
  receipt.console=[];page.on('pageerror',error=>receipt.console.push(error.message));
  await page.getByRole('button',{name:'Privacy for this site',exact:true}).waitFor({timeout:30000});await complete(opened);
  await check('Native favicon is actually rendered in the production tab row',async()=>{await eventual(async()=>{const s=await stateTab(tabId);return s.favicon===base+'/favicon.svg';});const image=page.locator(`.nx-br-tab img[src="${base}/favicon.svg"]`);await image.waitFor({state:'visible'});assert.equal(await eventual(()=>image.evaluate(e=>e.complete&&e.naturalWidth>0)),true);return {tabId,nativeFavicon:(await stateTab(tabId)).favicon,imageLoaded:true};});
  await check('Actual privacy popover shows native blocked count and sends site allowance to the backend',async()=>{await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();const counter=page.getByLabel('Blocked requests',{exact:true});await counter.waitFor({state:'visible'});assert.ok(Number(await counter.textContent())>=1);await page.getByLabel('Allow requests on this site',{exact:true}).click();await eventual(async()=>{const t=await stateTab(tabId);return t.shield.allowSites.includes('127.0.0.1');});await eventual(()=>page.getByLabel('Allow requests on this site',{exact:true}).isChecked());await picture('shield-allowed');await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();await page.getByRole('button',{name:'Reload',exact:true}).click();const observed=await eventual(async()=>{const t=await stateTab(tabId);if(t.loading)return false;const o=await observe(tabId);return /tracker loaded/.test(o.text)?o:false;});return {actualObservation:observed,shield:(await stateTab(tabId)).shield};});
  await check('Protection checkbox changes real native filtering and preserves owner state',async()=>{await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();await page.getByLabel('Allow requests on this site',{exact:true}).click();await eventual(async()=>!(await stateTab(tabId)).shield.allowSites.includes('127.0.0.1'));await page.getByLabel('Block known trackers',{exact:true}).click();await eventual(async()=>!(await stateTab(tabId)).shield.enabled);await eventual(async()=>!(await page.getByLabel('Block known trackers',{exact:true}).isChecked()));await page.getByLabel('Block known trackers',{exact:true}).click();await eventual(async()=>(await stateTab(tabId)).shield.enabled);await eventual(()=>page.getByLabel('Block known trackers',{exact:true}).isChecked());await picture('shield-protected');await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();return {shield:(await stateTab(tabId)).shield};});
  await check('Private-tab menu opens a real temporary native profile and closes it through the production UI',async()=>{await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('menuitem',{name:'New private tab',exact:true}).click();const input=page.getByRole('combobox',{name:'Search or type an address',exact:true});await input.fill(base+'/page.html?private=ui');await input.press('Enter');const tab=await eventual(async()=>{const s=await op('state');return s.tabs.find(t=>t.private&&t.url.includes('private=ui')&&t.live);});await page.locator('.nx-br-tab').filter({has:page.getByText('Private',{exact:true})}).waitFor({state:'visible'});assert.ok(fs.existsSync(path.join(root,'.neyvia/browser/private',tab.id)));await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();await page.getByText(/Private tab: its temporary profile is deleted/).waitFor();await picture('private');await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();await page.locator('.nx-br-tab').filter({has:page.getByText('Private',{exact:true})}).getByRole('button',{name:'Close Private protection fixture',exact:true}).click();await eventual(async()=>!(await op('state')).tabs.some(t=>t.id===tab.id));assert.ok(!fs.existsSync(path.join(root,'.neyvia/browser/private',tab.id)));return {privateId:tab.id,deletedOnUiClose:true};});
  await check('Owner history-clear menu removes this profile history with native acknowledgment',async()=>{await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('menuitem',{name:"Clear this profile's history",exact:true}).click();await eventual(async()=>!(await op('history')).history.some(x=>x.profileId==='default'));return {history:(await op('history')).history};});
  await check('Browser view reporter stores the actual layout on the bot side',async()=>{await page.getByRole('button',{name:'Tabs on top',exact:true}).click();await page.getByRole('tablist',{name:'Tabs',exact:true}).waitFor();await sleep(600);const state=await request('/api/ui/state');assert.match(JSON.stringify(state.data),/tabsPlacement.*top/);await picture('top-tabs');return {uiState:state.data};});
  await page.locator('.nx-root').evaluate(e=>e.setAttribute('data-nx-theme','light'));await picture('light');
  await check('Real backend outage produces an actionable privacy error and keeps protection unchanged',async()=>{
    await page.getByRole('button',{name:'Privacy for this site',exact:true}).click();
    await kill(backend);
    await page.getByLabel('Block known trackers',{exact:true}).click();
    const alert=page.getByRole('alert');await alert.waitFor({state:'visible'});
    const message=await alert.textContent();assert.match(message,/error sending request|can't be reached|connection/i);
    assert.equal(await page.getByLabel('Block known trackers',{exact:true}).isChecked(),true);
    const saved=JSON.parse(fs.readFileSync(path.join(root,'.neyvia/browser/state.json')));
    assert.equal(saved.tabs.find(t=>t.id===tabId).shield.enabled,true);
    await picture('real-outage');return {message,protectionUnchanged:true,backendActuallyStopped:true};
  });
  for(const file of ['src-tauri/src/browser_runtime.rs','scripts/browser-probe/src/main.rs','src/grant_agent/neyvia_browser.py','web/src/neyvia/next/NxBrowser.jsx','web/src/neyvia/next/NxBrowserParts.jsx','web/src/neyvia/next/nxBrowserApi.js','scripts/build_fix_browser_ui.mjs','scripts/verify_fix_browser_ui.cjs'])receipt.sources[file]=hash(path.join(repo,file));receipt.nativeBinarySha256=hash(nativePath);receipt.finishedAt=new Date().toISOString();receipt.ok=receipt.checks.every(c=>c.ok);save();
}
main().catch(e=>{receipt.error=e.stack;receipt.ok=false;save();process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await kill(native);await kill(backend);receipt.ownedProcessesStopped={native:!native||native.exitCode!==null||native.signalCode!==null,backend:!backend||backend.exitCode!==null||backend.signalCode!==null};save();});
