// Real full NxShell, fresh native WebView2 or installed Chromium and scoped CLI.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
import {chromium} from 'playwright';
const repo=path.resolve(import.meta.dirname,'..'),[port,cdp]=process.argv.slice(2).map(Number);
const fixtureSource=process.env.FIX_SIDEBAR_UI_FIXTURE_SOURCE;
const browserExecutable=process.env.FIX_SIDEBAR_UI_BROWSER_EXECUTABLE;
assert.equal(port,48668);assert.equal(cdp,48663);
const base=`http://127.0.0.1:${port}`,proofRoot=path.join(repo,'.agent_control/proofs',`FIX-sidebar-ui-${Date.now()}`),buildRoot=path.join(proofRoot,'build');
fs.mkdirSync(proofRoot,{recursive:true});
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const originalBinary=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe'),binary=path.join(proofRoot,'sidebar-native.exe');
fs.copyFileSync(originalBinary,binary);assert.equal(sha(binary),sha(originalBinary));
const receipt={schema:'neyvia.FIX.sidebar-ui.v1',startedAt:new Date().toISOString(),ports:[port,cdp],definition:'Cold request starts at the first production connected_sessions_list_command IPC invocation in a fresh process/profile. End is the second requestAnimationFrame after at least50 real sidebar leaf DOM nodes exist; all-returned rows render is recorded separately. Navigation/resource/DOM timings and process start-to-render are independently reported. No prior list/sidebar observation call is issued.',boundary:'Full production NxShell in actual native WebView2 with real read IPC forwarding and authenticated HTTP mutations/SSE,900 durable native chats/1800turns/50Git folders per fresh backend. Native-only adapter scope; no protected external histories. Compiled full shell build cost, host bootstrap and WebView startup are explicitly outside request-to-render budget and separately reported; no installed desktop release claim.',samples:[],pictures:[],nativeBinary:{path:path.relative(repo,binary),sha256:sha(binary),compiledOriginalSha256:sha(originalBinary)},buildMs:null};
receipt.definition='Primary cold budget is navigation performance.startTime=0 through the second requestAnimationFrame with six default No-folder rows visibly rendered and the real900total/300returned summary list loaded. Fresh backend process/database and native WebView profile; no prior list/sidebar call. IPC-startâ†’default rows and service duration are secondary. Real Show294more expansion is a separate user step with its own start/render timing, never the primary budget.';
receipt.budgetMs=2000;
if(browserExecutable){
 assert(fs.existsSync(browserExecutable),'Use an already installed browser; no download');
 receipt.boundary='Full production NxShell in an isolated installed Chromium profile through real authenticated HTTP;900 durable native chats/1800turns/50Git folders per fresh backend. No mocked IPC, protected provider history, native desktop or installed release claim. Process startup is reported separately from navigation-to-render.';
 receipt.browserBinary={path:browserExecutable,sha256:sha(browserExecutable)};
 delete receipt.nativeBinary;
}
const env={...process.env,PYTHONPATH:path.join(repo,'src'),PYTHONUTF8:'1',NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_BROWSER_PROOF_PORTS:`${port},${cdp}`,NEYVIA_PROOF_ALLOWED_PORTS:JSON.stringify([port,cdp]),NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),NEYVIA_WEB_PORT:String(port),FLUXIO_LOCAL_SESSION_BOOTSTRAP:'1'};
const python='C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',wrapper='scripts/verify_fix_sidebar_ui.py';
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function eventually(fn,timeout=120000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await pause(75);}throw Error('Owned sidebar UI deadline exceeded');}
async function stop(child){if(child&&child.exitCode===null&&child.signalCode===null){child.kill();await eventually(()=>child.exitCode!==null||child.signalCode!==null,20000);}}
function launch(exe,args,root,name,extra={}){const fd=fs.openSync(path.join(root,name+'.log'),'a');const p=spawn(exe,args,{cwd:repo,env:{...env,...extra},windowsHide:true,stdio:['ignore',fd,fd]});fs.closeSync(fd);return p;}
async function completed(child){await eventually(()=>child.exitCode!==null||child.signalCode!==null,600000);assert.equal(child.exitCode,0);}
const commands=new Set(['connected_sessions_list_command','connected_events_poll_command','sidebar_state_command']);
function collect(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())collect(p);else if(/\.(jsx|js|tsx|ts)$/.test(p))for(const m of fs.readFileSync(p,'utf8').matchAll(/["']((?:get|list|read|describe|search)_[a-z0-9_]+_command)["']/g))commands.add(m[1]);}}collect(path.join(repo,'web/src/neyvia'));
fs.writeFileSync(path.join(proofRoot,'index.html'),'<!doctype html><html><head><meta charset="utf-8"><title>Actual900 sidebar proof</title></head><body style="margin:0"><div id="root"></div><script type="module" src="/entry.jsx"></script></body></html>');
const shell=path.join(repo,'web/src/neyvia/next/NxShell.jsx').replaceAll('\\','/');
fs.writeFileSync(path.join(proofRoot,'entry.jsx'),`import React from'react';import{createRoot}from'react-dom/client';import{NxShell}from'${shell}';import{loadList,getNx}from'${shell.replace('NxShell.jsx','nxStore.js')}';
window.__sidebarProof={calls:[],entryAt:performance.now(),loadList,readList:getNx};
const proof=window.__sidebarProof;
const observer=new MutationObserver(()=>{const count=document.querySelectorAll('.nx-side [data-session-id]').length;if(count>=6&&!proof.defaultPending){proof.defaultPending=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{proof.defaultRenderedAt=performance.now();proof.defaultCount=document.querySelectorAll('.nx-side [data-session-id]').length;}));}if(count>=50&&!proof.paintPending){proof.paintPending=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{proof.fiftyRenderedAt=performance.now();proof.fiftyCount=document.querySelectorAll('.nx-side [data-session-id]').length;}));}if(proof.first&&count>=proof.first.count&&!proof.allPending){proof.allPending=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{proof.allRenderedAt=performance.now();proof.allCount=document.querySelectorAll('.nx-side [data-session-id]').length;}));}});observer.observe(document.getElementById('root'),{subtree:true,childList:true});
await fetch('/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',credentials:'include'}).then(r=>{if(!r.ok)throw Error('Owner session failed')});createRoot(document.getElementById('root')).render(<NxShell/>);`);
let backend,native,browser,page,fixtureProcess;
const sourcePaths=['scripts/verify_fix_sidebar_ui.mjs','scripts/verify_fix_sidebar_ui.py','scripts/verify_fix_sidebar.py','web/src/neyvia/next/NxShell.jsx','web/src/neyvia/next/nxShell.css','web/src/neyvia/next/nxTokens.css','web/src/neyvia/next/nxSidebar.css','web/src/neyvia/next/NxSidebar.jsx','web/src/neyvia/next/NxSidebarParts.jsx','web/src/neyvia/next/NxSettings.jsx','web/src/neyvia/next/NxNewChat.jsx','web/src/neyvia/next/nxPrimitives.jsx','web/src/neyvia/NeyviaPromptEditorDialog.jsx','web/src/neyvia/next/nxStore.js','web/src/neyvia/next/nxSidebarObserve.js','web/src/neyvia/next/nxApi.js','web/src/neyvia/next/nxBus.js','src/grant_agent/web_backend.py','src/grant_agent/local_network_policy.py','src/grant_agent/connected_sessions/broker.py','src/grant_agent/connected_sessions/runs.py','src/grant_agent/connected_sessions/neyvia.py','src/grant_agent/neyvia_sidebar_projection.py','scripts/browser-probe/src/main.rs','src-tauri/src/browser_runtime.rs'];
const executedSources=sourcePaths.map(p=>({path:p,sha256:sha(path.join(repo,p))}));
try{
 const timingPlugin={name:'proof-only-real-call-timing',transform(code,id){if(id.replaceAll('\\','/').endsWith('/neyvia/next/nxApi.js'))return code.replace('export async function callNx(', 'async function actualCallNx(')+`\nexport async function callNx(command,...args){const p=window.__sidebarProof;if(!p)return actualCallNx(command,...args);const c={command,start:performance.now()};p.calls.push(c);if(command==='connected_sessions_list_command'&&!p.first)p.first=c;try{const r=await actualCallNx(command,...args);c.end=performance.now();c.total=r?.total;c.count=r?.sessions?.length;c.ids=r?.sessions?.map(x=>x.id);return r;}catch(e){c.end=performance.now();c.error=String(e);throw e;}}`;}};
 receipt.instrumentation='Proof-build-only wrapper around exported production callNx; forwards command,args,result/errors unchanged to unchanged real implementation. No mocked IPC or HTTP results.';
 const buildStart=performance.now();await build({configFile:false,root:proofRoot,plugins:[react(),timingPlugin],cacheDir:path.join(proofRoot,'vite-cache'),define:{'import.meta.env.VITE_FLUXIO_BACKEND_URL':JSON.stringify(base)},build:{outDir:buildRoot,emptyOutDir:true,target:'esnext'}});receipt.buildMs=performance.now()-buildStart;
 for(let i=1;i<=Number(process.env.FIX_SIDEBAR_UI_SAMPLES||3);i++){
  const root=path.join(proofRoot,`sample${i}`);fs.mkdirSync(root,{recursive:true});const sample={index:i,root,checks:[],console:[]};receipt.samples.push(sample);
  if(fixtureSource){fs.mkdirSync(path.join(root,'.agent_control'),{recursive:true});const sourceDb=path.join(fixtureSource,'.agent_control/crashproof.sqlite3');fs.copyFileSync(sourceDb,path.join(root,'.agent_control/crashproof.sqlite3'));sample.fixtureSource={path:fixtureSource,sha256:sha(sourceDb),boundary:'900/1800 durable native fixture records cloned into independent database roots;50 real canonical Git folders remain referenced by their actual absolute fixture paths. No list/sidebar cache or browser profile copied.'};
   const setup=path.join(fixtureSource,'.agent_control/onboarding/state.json');
   if(fs.existsSync(setup)){const saved=JSON.parse(fs.readFileSync(setup));assert.equal(saved.dismissed,true);const target=path.join(root,'.agent_control/onboarding/state.json');fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(setup,target);sample.fixtureSource.setup={path:setup,sha256:sha(setup),boundary:'Previously dismissed setup, saved by authenticated production owner command before any list observation.'};}
  }else{fixtureProcess=launch(python,[wrapper,'fixture','--root',root,'--port',String(port),'--static-root',buildRoot],root,'fixture');await completed(fixtureProcess);fixtureProcess=null;}
  const hostStarted=performance.now(),hostStartAt=Date.now();backend=launch(python,[wrapper,'serve','--root',root,'--port',String(port),'--static-root',buildRoot],root,'backend', {NEYVIA_SIDEBAR_ALLOWED_ROOTS:JSON.stringify(fixtureSource?[root,fixtureSource]:[root])});
  await eventually(async()=>{if(backend.exitCode!==null)throw Error(fs.readFileSync(path.join(root,'backend.log'),'utf8'));try{return(await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}});sample.backendHealthyMs=performance.now()-hostStarted;
  const login=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];
  async function request(route,body){const r=await fetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});const v=await r.json();assert.equal(r.ok,true,JSON.stringify(v));return v.data??v;}
  const nativeStarted=performance.now(),nativeStartAt=Date.now();
  if(browserExecutable){
   browser=await chromium.launch({executablePath:browserExecutable,headless:true,args:[`--remote-debugging-port=${cdp}`]});
   const context=await browser.newContext({viewport:{width:1280,height:800}});page=await context.newPage();await page.goto(base+'/index.html');
  }else{
  const connected=await request('/api/ui/browser',{op:'runtime.connect',args:{}});assert.equal(connected.ok,true);
  native=launch(binary,[],root,'native',{NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/index.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:[...commands].join(','),WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`});
  await eventually(async()=>{if(native.exitCode!==null)throw Error(fs.readFileSync(path.join(root,'native.log'),'utf8'));try{return(await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}});
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventually(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url()===base+'/index.html'));
  }
  page.on('console',m=>sample.console.push({type:m.type(),text:m.text()}));page.on('pageerror',e=>sample.console.push({type:'pageerror',text:String(e)}));
  const initial=await eventually(()=>page.evaluate(()=>{const p=window.__sidebarProof;return p?.first?.end&&p.defaultRenderedAt?{first:p.first,defaultRenderedAt:p.defaultRenderedAt,defaultCount:p.defaultCount,timeOrigin:performance.timeOrigin,calls:p.calls,navigation:performance.getEntriesByType('navigation')[0]?.toJSON(),resources:performance.getEntriesByType('resource').map(x=>x.toJSON()),paint:performance.getEntriesByType('paint').map(x=>x.toJSON())}:null;}));sample.initialMeasurements=initial;sample.coldDefaultRenderMs=initial.defaultRenderedAt-initial.first.start;sample.navigationToDefaultRenderMs=initial.defaultRenderedAt;sample.defaultCount=initial.defaultCount;sample.hostStartToDefaultMs=initial.timeOrigin+initial.defaultRenderedAt-hostStartAt;sample[browserExecutable?'browserStartToDefaultMs':'nativeStartToDefaultMs']=initial.timeOrigin+initial.defaultRenderedAt-nativeStartAt;await picture('default');
  if(browserExecutable){sample.browserStartToDefaultMs=sample.nativeStartToDefaultMs;delete sample.nativeStartToDefaultMs;}
  sample.expansionClickAt=await page.evaluate(()=>performance.now());await page.getByRole('button',{name:'Show 294 more',exact:true}).click();
  const measured=await eventually(()=>page.evaluate(()=>{const p=window.__sidebarProof;if(!p?.first||!p?.allRenderedAt)return null;return {first:p.first,fiftyRenderedAt:p.fiftyRenderedAt,allRenderedAt:p.allRenderedAt,fiftyCount:p.fiftyCount,allCount:p.allCount,entryAt:p.entryAt,calls:p.calls,navigation:performance.getEntriesByType('navigation')[0]?.toJSON(),paint:performance.getEntriesByType('paint').map(x=>x.toJSON())};}));sample.measurements=measured;sample[browserExecutable?'browserStartToMeasuredMs':'nativeStartToMeasuredMs']=performance.now()-nativeStarted;sample.hostStartToMeasuredMs=performance.now()-hostStarted;sample.expansionTo300RenderMs=measured.allRenderedAt-sample.expansionClickAt;
  sample.cold50RenderMs=measured.fiftyRenderedAt-measured.first.start;sample.coldAllReturnedRenderMs=measured.allRenderedAt-measured.first.start;sample.serviceMs=measured.first.end-measured.first.start;sample.navigationTo50RenderMs=measured.fiftyRenderedAt;sample.budgetPassed=sample.navigationToDefaultRenderMs<2000;sample.requestBudgetPassed=sample.coldDefaultRenderMs<2000;sample.initialListCalls=initial.calls.filter(c=>c.command==='connected_sessions_list_command').length;
  assert.equal(measured.first.total,900);assert.equal(measured.first.count,300);assert.equal(measured.allCount,300);assert.equal(new Set(measured.first.ids).size,300);sample.checks.push({name:'900 durable chats, actual production300-row list; default6 No-folder rows and real Show294more expands300',ok:true,groups:await page.locator('.nx-side-section').count()});
  async function picture(name){const label=path.basename(proofRoot);const p=path.join(repo,'scripts/evidence/fix',`${label}-${i}-${name}.png`);fs.mkdirSync(path.dirname(p),{recursive:true});await page.screenshot({path:p});receipt.pictures.push({path:path.relative(repo,p),sha256:sha(p)});}
  await picture('cold');
  if(i===1&&!process.env.FIX_SIDEBAR_UI_TIMING_ONLY){
   const id=measured.first.ids[0],leaf=page.locator(`[data-session-id="${id}"]`);await leaf.hover();await leaf.getByRole('button',{name:'Pin',exact:true}).click();await eventually(()=>page.getByRole('group',{name:'Pinned',exact:true}).locator(`[data-session-id="${id}"]`).count());const persisted=await request('/api/ui/sidebar?limit=50');assert.equal(persisted.sessions.find(x=>x.id===id)?.pinned,true);sample.checks.push({name:'Visible Pin button persists through real HTTP owner and bus',ok:true,id});await picture('pin');
   await page.getByRole('searchbox',{name:'Search chats'}).fill('FOLLOW fixture conversation 1');await eventually(()=>page.evaluate(()=>window.__sidebarProof.calls.some(c=>c.command==='connected_sessions_list_command'&&c.count>0&&c.count<300)));const searched=await page.locator('.nx-row-title').allTextContents();assert(searched.length>0&&searched.every(t=>t.includes('FOLLOW fixture conversation 1')));sample.checks.push({name:'Actual server search updates visible rows',ok:true,visible:searched.length});await picture('search');
   const concurrency=await page.evaluate(async()=>{const p=window.__sidebarProof,n=p.calls.length;const a=p.loadList({query:'FOLLOW fixture conversation 1'}),b=p.loadList({query:'FOLLOW fixture conversation 1'}),c=p.loadList({query:'FOLLOW fixture conversation 2'});const shared=a===b,different=a!==c;await Promise.all([a,b,c]);const s=p.readList();return{shared,different,status:s.list.status,titles:s.order.map(id=>s.sessions[id].title),listCalls:p.calls.slice(n).filter(x=>x.command==='connected_sessions_list_command').length};});assert.equal(concurrency.shared,true);assert.equal(concurrency.different,true);assert.equal(concurrency.listCalls,2);assert(concurrency.titles.length>0&&concurrency.titles.every(t=>t.includes('FOLLOW fixture conversation 2')));sample.checks.push({name:'Actual production store shares identical promise, retains parallel different query and newest response',ok:true,detail:concurrency});
   await page.getByRole('searchbox',{name:'Search chats'}).fill('never-matches-sidebar-proof');await page.getByText('No chats match',{exact:true}).waitFor();await stop(backend);await page.getByRole('searchbox',{name:'Search chats'}).fill('offline-unmatched-sidebar-proof');await page.getByRole('alert').filter({hasText:/Chats didn't load|Can't reach your PC/}).waitFor();sample.failureText=await page.getByRole('alert').filter({hasText:/Chats didn't load|Can't reach your PC/}).innerText();sample.checks.push({name:'Stopped real host produces visible refusal and retry, no fake response',ok:true,text:sample.failureText});await picture('offline');
   const retries=await page.evaluate(async()=>{const p=window.__sidebarProof,a=p.loadList();await a;const b=p.loadList();await b;return{cleared:a!==b,status:p.readList().list.status};});assert.equal(retries.cleared,true);assert.equal(retries.status,'error');sample.checks.push({name:'Real failed owner requests clear single-flight state and can retry',ok:true,detail:retries});
   const beforeRetry=await page.evaluate(()=>window.__sidebarProof.calls.length);await page.getByRole('button',{name:'Try again',exact:true}).click();await eventually(()=>page.evaluate(n=>window.__sidebarProof.calls.length>n&&window.__sidebarProof.readList().list.status==='error',beforeRetry));sample.checks.push({name:'Visible Try again sends a real retry while the host remains stopped',ok:true});
   backend=launch(python,[wrapper,'serve','--root',root,'--port',String(port),'--static-root',buildRoot],root,'backend-restarted',{NEYVIA_SIDEBAR_ALLOWED_ROOTS:JSON.stringify(fixtureSource?[root,fixtureSource]:[root])});await eventually(async()=>{try{return(await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}});const retry=page.getByRole('button',{name:'Try again',exact:true});if(await retry.count()){try{await retry.click({timeout:1500});}catch(error){assert.equal(await page.evaluate(()=>window.__sidebarProof.readList().list.status),'ready',String(error));}}await page.getByText('No chats match',{exact:true}).waitFor();await page.getByRole('searchbox',{name:'Search chats'}).fill('FOLLOW fixture conversation 2');await eventually(async()=>{const titles=await page.locator('.nx-row-title').allTextContents();return titles.length>0&&titles.every(t=>t.includes('FOLLOW fixture conversation 2'));});sample.checks.push({name:'Actual restarted host recovers via stream refresh or visible retry with the same durable root',ok:true});await picture('recovered');
  }
  await browser.close();browser=null;await stop(native);native=null;await stop(backend);backend=null;page=null;sample.cleanup=true;
 }
 receipt.ok=true;receipt.budgetPassed=receipt.samples.every(s=>s.budgetPassed);if(!receipt.budgetPassed)process.exitCode=2;
}catch(e){receipt.ok=false;receipt.error=String(e.stack??e);process.exitCode=1;if(page&&!page.isClosed())receipt.failureUi=await page.locator('body').innerText().catch(()=>null);}
finally{await browser?.close().catch(()=>{});await stop(native);await stop(backend);await stop(fixtureProcess);receipt.cleanup=true;receipt.finishedAt=new Date().toISOString();receipt.sources=executedSources;receipt.sourceStable=executedSources.every(row=>sha(path.join(repo,row.path))===row.sha256);if(!receipt.sourceStable){receipt.ok=false;receipt.error=receipt.error||"Source changed during proof";process.exitCode=1;};receipt.buildArtifacts=fs.existsSync(buildRoot)?fs.readdirSync(path.join(buildRoot,'assets')).filter(p=>/\.(js|css)$/.test(p)).map(p=>({path:path.relative(repo,path.join(buildRoot,'assets',p)),sha256:sha(path.join(buildRoot,'assets',p))})):[];fs.writeFileSync(path.join(repo,'scripts/evidence/FIX-sidebar-ui.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({ok:receipt.ok,budgetPassed:receipt.budgetPassed,samples:receipt.samples.map(s=>({coldDefaultRenderMs:s.coldDefaultRenderMs,navigationToDefaultRenderMs:s.navigationToDefaultRenderMs,serviceMs:s.serviceMs,initialListCalls:s.initialListCalls})),error:receipt.error}));}
