/* Real authenticated backend and actual product browser_runtime.rs in isolated Tauri shell. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn,spawnSync}=require('node:child_process');
const repo=path.resolve(__dirname,'..'),port=48668,base=`http://127.0.0.1:${port}`;
const root=path.join(repo,'.agent_control/proofs/native-browser-'+Date.now()),staticRoot=path.join(root,'fixture');
const output=path.join(repo,'scripts/evidence/FIX-native-browser.json');
const nativePath=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe');
const env={...process.env,PYTHONPATH:path.join(repo,'src'),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_BROWSER_PROOF_PORTS:String(port),NEYVIA_BROWSER_SHIELD_HOSTS:JSON.stringify(['localhost']),NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),PYTHONUNBUFFERED:'1'};
const receipt={scope:'FIX-native-browser',port,root,startedAt:new Date().toISOString(),boundary:'Authenticated full backend + product Rust runtime in real disposable Tauri/WebView2 shell; no installed desktop/public release claim',checks:[],calls:[],sources:{}};
let backend,native,cookie;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sanitize=value=>JSON.parse(JSON.stringify(value,(k,v)=>/token|password|cookie/i.test(k)?'[masked]':v));
function save(){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');}
function restoredTabIds(){const restored=spawnSync('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['-c','import sys,json;from pathlib import Path;from grant_agent.proof_credential_guard import install;install(Path(sys.argv[1]));from grant_agent.neyvia_browser import BrowserService;print(json.dumps([t["id"] for t in BrowserService(sys.argv[1]).state["tabs"]]))',root],{cwd:repo,env,windowsHide:true,encoding:'utf8',timeout:30000});assert.equal(restored.status,0,restored.stderr);return JSON.parse(restored.stdout);}
async function request(route,body){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await response.json();receipt.calls.push({route,body:sanitize(body||{}),status:response.status,data:sanitize(data)});return {response,data};}
async function browser(op,args={}){const {response,data}=await request('/api/ui/browser',{op,args});assert.equal(response.status,200,JSON.stringify(data));assert.equal(data.ok,true,JSON.stringify(data));return data;}
async function eventual(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await sleep(120);}throw Error('Expected native transition timed out');}
async function complete(row){if(!row.actionId)return row;return eventual(async()=>{const data=await browser('action.get',{actionId:row.actionId});if(data.status==='failed')throw Error(JSON.stringify(data));return data.status==='done'?data:false;});}
async function observe(tabId){return eventual(async()=>{const done=await complete(await browser('observe',{tabId}));const obs=done.result?.observation;return obs?.readyState==='complete'?obs:false;});}
async function tabState(tabId){return (await browser('state')).tabs.find(t=>t.id===tabId);}
async function check(name,fn){try{const detail=await fn();receipt.checks.push({name,ok:true,detail});save();return detail;}catch(e){receipt.checks.push({name,ok:false,error:e.stack});save();throw e;}}
async function kill(child){if(child&&child.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
async function main(){
  fs.mkdirSync(staticRoot,{recursive:true});
  fs.writeFileSync(path.join(staticRoot,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="green"/></svg>');
  fs.writeFileSync(path.join(staticRoot,'tracker.js'),'window.fixtureTrackerLoaded=true;document.querySelector("#network").textContent="tracker loaded";');
  fs.writeFileSync(path.join(staticRoot,'index.html'),`<!doctype html><title>FIX native browser fixture</title><link rel="icon" href="${base}/favicon.svg"><style>body{font:24px system-ui;padding:40px;background:#e9f3ed;color:#123b28}</style><h1>Real WebView2 privacy proof</h1><p id="network">request pending</p><p id="storage"></p><p id="ipc">IPC pending</p><script>
  document.querySelector('#storage').textContent='Previous storage: '+(localStorage.getItem('private-canary')||'empty');localStorage.setItem('private-canary','written');
  const tracker=document.createElement('script');tracker.src='http://localhost:${port}/tracker.js?nonce='+Date.now();tracker.onerror=()=>document.querySelector('#network').textContent='tracker blocked';document.head.append(tracker);
  if(window.__TAURI_INTERNALS__)window.__TAURI_INTERNALS__.invoke('browser_runtime_stop').then(()=>document.querySelector('#ipc').textContent='shell shutdown ALLOWED',()=>document.querySelector('#ipc').textContent='shell shutdown denied');
  </script>`);
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventual(async()=>{if(backend.exitCode!==null)throw Error('Backend exited '+backend.exitCode);try{return (await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},180000);
  const login=await request('/api/auth/local-session',{});assert.equal(login.response.status,200);cookie=login.response.headers.get('set-cookie').split(';')[0];
  const connected=await browser('runtime.connect');assert.equal(connected.baseUrl,base);
  const nativeLog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(nativePath,[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.token},windowsHide:true,stdio:['ignore',nativeLog,nativeLog]});fs.closeSync(nativeLog);
  await eventual(async()=>{if(native.exitCode!==null)throw Error('Native exited '+native.exitCode);return (await browser('state')).runtime.connected;});
  const opened=await complete(await browser('tab.open',{url:base+'/index.html'})),tabId=opened.tabId;
  await complete(await browser('layout',{tabs:[{tabId,x:0,y:0,width:1200,height:730,visible:true}]}));
  await check('WebView2 shield blocks actual tracker subresource before first page request',async()=>{await eventual(async()=>{const s=await tabState(tabId);return s.shield.blockedCount>=1?s:false;});const obs=await observe(tabId);assert.match(obs.text,/tracker blocked/);return {tabId,observation:obs,shield:(await tabState(tabId)).shield};});
  await check('WebView2 favicon callback reaches shared tab state',async()=>{const state=await eventual(async()=>{const s=await tabState(tabId);return s.favicon===base+'/favicon.svg'?s:false;});return {favicon:state.favicon};});
  await check('Site allowance permits same real tracker request without disabling global shield',async()=>{await complete(await browser('shield',{tabId,allowSite:true}));await complete(await browser('tab.reload',{tabId}));const obs=await eventual(async()=>{const o=await observe(tabId);return /tracker loaded/.test(o.text)?o:false;});const state=await tabState(tabId);assert.equal(state.shield.enabled,true);assert.ok(state.shield.allowSites.includes('127.0.0.1'));return {observation:obs,shield:state.shield};});
  await check('Re-enable site protection blocks again and disabled shield permits',async()=>{await complete(await browser('shield',{tabId,allowSite:false}));const count=(await tabState(tabId)).shield.blockedCount;await complete(await browser('tab.reload',{tabId}));await eventual(async()=>{const s=await tabState(tabId);return s.shield.blockedCount>count;});await complete(await browser('shield',{tabId,enabled:false}));await complete(await browser('tab.reload',{tabId}));const obs=await eventual(async()=>{const o=await observe(tabId);return /tracker loaded/.test(o.text)?o:false;});return {observation:obs,shield:(await tabState(tabId)).shield};});
  const otherProfile=await browser('profile.create',{name:'Protected keeper'}),otherSpace=await browser('space.create',{name:'Keeper',profileId:otherProfile.id});
  let other=await complete(await browser('tab.open',{url:base+'/index.html?keeper=1',spaceId:otherSpace.id}));await observe(other.tabId);
  await check('History clear invokes native per-profile callback and preserves other profile history',async()=>{const before=await browser('history');assert.ok(before.history.some(x=>x.profileId==='default'));assert.ok(before.history.some(x=>x.profileId===otherProfile.id));const cleared=await complete(await browser('history.clear',{profileId:'default'}));assert.equal(cleared.result.historyCleared,true);const after=await browser('history');assert.ok(!after.history.some(x=>x.profileId==='default'));assert.ok(after.history.some(x=>x.profileId===otherProfile.id));assert.ok(!(await browser('state')).profiles.find(p=>p.id==='default').historyClearPending);return {before:before.history,after:after.history,nativeResult:cleared.result};});
  await check('Closed-profile native history clear stays pending until real open clears before navigation',async()=>{await complete(await browser('tab.close',{tabId:other.tabId}));const pending=await browser('history.clear',{profileId:otherProfile.id});assert.equal(pending.status,'native_cleanup_pending');assert.equal((await browser('state')).profiles.find(p=>p.id===otherProfile.id).historyClearPending,true);other=await complete(await browser('tab.open',{url:base+'/index.html?keeper=2',spaceId:otherSpace.id}));assert.equal(other.result.historyCleared,true);assert.ok(!(await browser('state')).profiles.find(p=>p.id===otherProfile.id).historyClearPending);return {pendingStatus:pending.status,nativeOpenResult:other.result};});
  const keeper=path.join(root,'.neyvia/browser/profiles/default/keeper.txt');fs.mkdirSync(path.dirname(keeper),{recursive:true});fs.writeFileSync(keeper,'preserve ordinary profile\n');
  await check('Agent tool cannot change owner shield or clear owner history',async()=>{const shield=await request('/api/ui/tools/call',{tool:'neyvia.browser.shield',arguments:{tabId,enabled:true}});assert.match(JSON.stringify(shield.data),/owner_required|Only the PC owner/);const history=await request('/api/ui/tools/call',{tool:'neyvia.browser.history_clear',arguments:{profileId:'default'}});assert.match(JSON.stringify(history.data),/owner_required|Only the PC owner/);return {shield:shield.data,history:history.data};});
  await check('Private WebView2 isolated storage, no history/save/restore, exact profile deleted on acknowledged close',async()=>{const opened=await complete(await browser('tab.open',{url:base+'/index.html?private=1',private:true}));const privateId=opened.tabId,profile=path.join(root,'.neyvia/browser/private',privateId);const obs=await observe(privateId);assert.match(obs.text,/Previous storage: empty/);assert.ok(fs.existsSync(profile));const statePath=path.join(root,'.neyvia/browser/state.json');assert.ok(!JSON.parse(fs.readFileSync(statePath)).tabs.some(t=>t.id===privateId));const restored=restoredTabIds();assert.ok(!restored.includes(privateId));assert.ok(!(await browser('history')).history.some(t=>t.tabId===privateId));const closed=await complete(await browser('tab.close',{tabId:privateId}));assert.equal(closed.result.privateProfileDeleted,true);assert.ok(!fs.existsSync(profile));assert.equal(fs.readFileSync(keeper,'utf8'),'preserve ordinary profile\n');const opened2=await complete(await browser('tab.open',{url:base+'/index.html?private=2',private:true}));const obs2=await observe(opened2.tabId);assert.match(obs2.text,/Previous storage: empty/);await complete(await browser('tab.close',{tabId:opened2.tabId}));return {privateId,observation:obs,restoredIdsInFreshProcess:restored,closed:closed.result,reopenedObservation:obs2,ordinaryProfilePreserved:true,persistedTabsExcludePrivate:true};});
  await check('Native page cannot invoke shell browser shutdown',async()=>{const obs=await observe(tabId);assert.match(obs.text,/shell shutdown denied/);return {observation:obs,actualPrivilegedCallDenied:true};});
  const captured=await complete(await browser('capture',{tabId}));assert.ok(captured.result.bytes>100);const capturedProof=path.join(repo,'scripts/evidence/fix/native-browser.png');fs.copyFileSync(captured.result.path,capturedProof);receipt.capture={path:capturedProof,bytes:captured.result.bytes,sha256:hash(capturedProof)};
  await complete(await browser('tab.close',{tabId}));await complete(await browser('tab.close',{tabId:other.tabId}));
  for(const file of ['src-tauri/src/browser_runtime.rs','scripts/browser-probe/src/main.rs','src/grant_agent/neyvia_browser.py','scripts/verify_fix_native_browser.cjs'])receipt.sources[file]=hash(path.join(repo,file));receipt.nativeBinarySha256=hash(nativePath);receipt.finishedAt=new Date().toISOString();receipt.ok=receipt.checks.every(c=>c.ok);save();
}
main().catch(e=>{receipt.error=e.stack;receipt.ok=false;save();process.exitCode=1;}).finally(async()=>{await kill(native);await kill(backend);receipt.ownedProcessesStopped={native:!native||native.exitCode!==null||native.signalCode!==null,backend:!backend||backend.exitCode!==null||backend.signalCode!==null};save();});
