// Proof-only stage of the actual full NxShell, real HTTP owners and native IPC.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
import {chromium} from 'playwright';
const repo=path.resolve(import.meta.dirname,'..');
const [port,cdp]=process.argv.slice(2).map(Number);assert.equal(port,48667);assert.equal(cdp,48664);
const base=`http://127.0.0.1:${port}`,root=path.join(repo,'.agent_control/proofs',`FIX-navigation-ui-${Date.now()}`),staticRoot=path.join(root,'build');fs.mkdirSync(root,{recursive:true});
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function uiSources(dir=path.join(repo,'web/src/neyvia')){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{const p=path.join(dir,entry.name);return entry.isDirectory()?uiSources(p):/\.(?:jsx?|tsx?|css|svg|json)$/.test(p)?[{path:path.relative(repo,p).replaceAll('\\','/'),sha256:sha(p)}]:[];}).sort((a,b)=>a.path.localeCompare(b.path));}
const source=path.join(repo,'web/src/neyvia/next').replaceAll('\\','/');
fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><html><head><meta charset="utf-8"><title>Actual Neyvia navigation proof</title></head><body style="margin:0"><div id="root"></div><script type="module" src="/entry.jsx"></script></body></html>');
fs.writeFileSync(path.join(root,'entry.jsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{NxShell}from'${source}/NxShell.jsx';await fetch('/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',credentials:'include'}).then(r=>{if(!r.ok)throw Error('Owned session failed')});createRoot(document.getElementById('root')).render(<NxShell/>);`);
fs.writeFileSync(path.join(root,'output.txt'),'Real published navigation output\nAn exact native-rendered file preview.\n');
fs.writeFileSync(path.join(root,'report.txt'),'Actual perception navigation file\n');
const receipt={schema:'neyvia.FIX.navigation-ui.v1',startedAt:new Date().toISOString(),ports:[port,cdp],root,boundary:'Actual full production NxShell in isolated WebView2; real authenticated HTTP tool/CL bus events and actual desktop-backend forwarding. Keyboard proof covers launcher/focus/form/reduced motion only, not full accessibility readiness. No installed desktop, external providers, signing, microphone or NAS claim.',checks:[],pictures:[],console:[],calls:[],httpFailures:[]};
let backend,native,browser,ownedContext,page,cookie='';
const env={...process.env,PYTHONPATH:path.join(repo,'src'),PYTHONUTF8:'1',NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_BROWSER_PROOF_PORTS:`${port},${cdp}`,NEYVIA_PROOF_ALLOWED_PORTS:JSON.stringify([port,cdp]),NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),NEYVIA_WEB_PORT:String(port),FLUXIO_LOCAL_SESSION_BOOTSTRAP:'1'};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function eventually(fn,timeout=180000){const until=Date.now()+timeout;while(Date.now()<until){const v=await fn();if(v)return v;await pause(150);}throw Error('Owned navigation deadline exceeded');}
async function request(route,body){const response=await fetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});const result=await response.json();receipt.calls.push({route,status:response.status,operation:body?.tool||body?.command||body?.op||body?.app});return{status:response.status,...result};}
async function tool(name,args={}){const r=await request('/api/ui/tools/call',{tool:`neyvia.${name}`,arguments:args});assert.equal(r.ok,true,JSON.stringify(r));const result=r.data.result??r.data;assert.notEqual(result.ok,false,JSON.stringify(result));return result;}
async function check(name,fn){const detail=await fn();receipt.checks.push({name,ok:true,detail});console.log('PASS',name);}
async function picture(name){const p=path.join(repo,'scripts/evidence/fix',`navigation-ui-${name}.png`);fs.mkdirSync(path.dirname(p),{recursive:true});await page.screenshot({path:p});receipt.pictures.push({path:path.relative(repo,p),sha256:sha(p)});}
async function stop(child){if(child&&child.exitCode===null&&child.signalCode===null){child.kill();await eventually(()=>child.exitCode!==null||child.signalCode!==null,15000);}}
try{
  receipt.buildSources=uiSources();
  await build({configFile:false,root,plugins:[react()],cacheDir:path.join(root,'vite-cache'),define:{'import.meta.env.VITE_FLUXIO_BACKEND_URL':JSON.stringify(base)},build:{outDir:staticRoot,emptyOutDir:true,target:'esnext'}});
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventually(async()=>{if(backend.exitCode!==null)throw Error(fs.readFileSync(path.join(root,'backend.log'),'utf8'));try{return(await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}});
  console.log('READY owned backend',port);
  const login=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
  const connect=await request('/api/ui/browser',{op:'runtime.connect',args:{}});assert.equal(connect.ok,true);
  // A read-only allowlist extracted from actual frontend command names; no mutation handlers are granted.
  const commands=new Set(['connected_sessions_list_command','connected_events_poll_command',...(process.env.NEYVIA_FIX_ACCESSIBILITY?['save_agent_prompt_library_command']:[])]);
  function collect(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())collect(p);else if(/\.(jsx|js|tsx|ts)$/.test(p)){for(const m of fs.readFileSync(p,'utf8').matchAll(/["']((?:get|list|read|describe|search)_[a-z0-9_]+_command)["']/g))commands.add(m[1]);}}}collect(path.join(repo,'web/src/neyvia'));
  receipt.nativeForwardedReadCommands=[...commands].sort();
  if(process.env.NEYVIA_FIX_CHROME_EXE){
    const executable=process.env.NEYVIA_FIX_CHROME_EXE;
    assert.ok([chromium.executablePath(),'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].includes(executable));assert.ok(fs.existsSync(executable));
    receipt.renderingMechanism='Actual production web branch in existing Chromium, isolated owned profile, authenticated HTTP; no Tauri IPC emulation';receipt.browserExecutable={path:executable,sha256:sha(executable)};
    receipt.boundary='Actual full production NxShell in existing Chromium with an isolated owned profile; real authenticated HTTP tool/CL bus events and backend owner calls. No native IPC, installed desktop, physical picker, external provider, signing, microphone or NAS claim.';receipt.nativeBinaryExecuted=false;delete receipt.nativeForwardedReadCommands;
    console.log('LAUNCH existing Chromium browser branch');ownedContext=await chromium.launchPersistentContext(path.join(root,'web-profile'),{executablePath:executable,headless:true,args:[`--remote-debugging-port=${cdp}`],viewport:{width:1280,height:800}});browser=ownedContext.browser();page=ownedContext.pages()[0]||await ownedContext.newPage();await page.goto(base+'/index.html');
  }else{
  const nlog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe'),[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connect.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/index.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:[...commands].join(','),WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`},windowsHide:true,stdio:['ignore',nlog,nlog]});fs.closeSync(nlog);
  console.log('WAIT owned native browser CDP',cdp);
  await eventually(async()=>{if(native.exitCode!==null)throw Error(fs.readFileSync(path.join(root,'native.log'),'utf8'));try{return(await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}});
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventually(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url()===base+'/index.html'));
  receipt.renderingMechanism='Actual production desktop branch in owned native WebView2, real authenticated backend forwarding';
  receipt.nativeBinaryExecuted=true;
  }
  page.on('console',m=>receipt.console.push({type:m.type(),text:m.text()}));page.on('pageerror',e=>receipt.console.push({type:'pageerror',text:String(e)}));page.on('response',r=>{if(r.status()>=400)receipt.httpFailures.push({route:new URL(r.url()).pathname,status:r.status()});});
  page.on('request',r=>{const u=new URL(r.url());if(/^https?:$/.test(u.protocol)&&['127.0.0.1','localhost'].includes(u.hostname)&&!['48667','48664'].includes(u.port))receipt.console.push({type:'forbidden-port',url:u.origin});});
  const [name,...val]=cookie.split('=');await page.context().addCookies([{name,value:val.join('='),url:base}]);await page.reload();
  await page.locator('.nx-root').waitFor({timeout:30000});
  if(ownedContext){await page.getByRole('button',{name:'Skip setup',exact:true}).waitFor({timeout:30000});await picture('fresh-setup');await page.getByRole('button',{name:'Skip setup',exact:true}).click();await page.locator('.nx-onb-scrim').waitFor({state:'hidden'});await check('Actual first-run setup is dismissed through the owner UI',async()=>({action:'Skip setup',scrimRemoved:true}));}
  if(process.env.NEYVIA_FIX_ACCESSIBILITY){const{verifyAccessibility}=await import('./verify_fix_accessibility_ui.mjs');await verifyAccessibility({page,tool,request,root,repo,base,renderingMechanism:receipt.renderingMechanism,buildSources:receipt.buildSources,nativeBinarySha256:sha(path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe'))});}
  if(process.env.NEYVIA_FIX_ACCESSIBILITY_ONLY){receipt.scope='accessibility-and-prompt-import-only';receipt.boundary+=' Scope is the recorded accessibility and prompt-import journeys; no classic runtime-audit completion claim.';}
  if(!process.env.NEYVIA_FIX_ACCESSIBILITY_ONLY){
  await check('Real CL Outputs request is consumed and rendered by the full production shell',async()=>{const result=await tool('manual.run',{id:'outputs',chapter:'navigation',procedure:'request-pane',inputs:{target:'all'}});assert.equal(result.status,'completed');await page.getByRole('region',{name:'Outputs',exact:true}).waitFor();await page.getByText('Nothing published yet',{exact:true}).waitFor();await picture('outputs-empty');return{procedure:result.status,pane:(await tool('state')).pane};});
  await check('Actual Outputs form refuses a missing file and restores keyboard focus to its field',async()=>{await page.getByRole('button',{name:'Add',exact:true}).click();const form=page.getByRole('form',{name:'Add an output'}),file=form.getByLabel('File',{exact:true});await file.waitFor();assert.equal(await file.evaluate(e=>e===document.activeElement),true);await file.fill('missing.txt');await form.getByRole('button',{name:'Add',exact:true}).click();await form.getByRole('alert').waitFor();const refusal=await form.getByRole('alert').innerText();assert.match(refusal,/doesn't exist/i);await picture('output-refusal');return{focus:true,refusal};});
  await check('Real UI publication persists and previews exact fixture bytes',async()=>{const form=page.getByRole('form',{name:'Add an output'});await form.getByLabel('File',{exact:true}).fill('output.txt');await form.getByLabel('Title',{exact:true}).fill('Actual navigation output');await form.getByRole('button',{name:'Add',exact:true}).click();await form.waitFor({state:'hidden'});await page.locator('.nx-ap-text').filter({hasText:'An exact native-rendered file preview.'}).waitFor();const r=await request('/api/ui/outputs',{op:'list',args:{}});assert.equal(r.ok,true);await picture('output-preview');return{preview:await page.locator('.nx-ap-text').innerText(),registry:r};});
  await check('Outputs opens the actual revision-checked artifact and its editable source pane',async()=>{await page.locator('.nx-out-detail').getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('region',{name:'Artifact',exact:true}).waitFor();await page.locator('.nx-ap-text').filter({hasText:'Real published navigation output'}).waitFor();const artifactPane=(await tool('state')).pane;await page.getByRole('button',{name:'Edit source',exact:true}).click();await page.getByRole('region',{name:'File',exact:true}).waitFor();await page.getByRole('textbox',{name:'File text',exact:true}).waitFor();assert.match(await page.getByRole('textbox',{name:'File text',exact:true}).inputValue(),/An exact native-rendered file preview/);await picture('file-pane');return{artifactPane,renderedFileText:true};});
  await check('Real CL perception pane shows the actual local file layer',async()=>{const result=await tool('manual.run',{id:'perception',chapter:'navigation',procedure:'request-pane',inputs:{target:'file:report.txt'}});assert.equal(result.status,'completed');await page.getByRole('region',{name:'What the agent sees',exact:true}).waitFor();await page.getByText(/Actual perception navigation file/).first().waitFor();await picture('perception');return{procedure:result.status,rendered:await page.locator('.nx-stage').innerText()};});
  for(const [app,title,command] of [['marketplace','Marketplace','get_neyvia_application_registry_command'],['office-suite','Office tools','describe_tool_suite_command'],['personal-mesh','Personal mesh','get_nearby_receiver_sidecar_status_command'],['security','Security tools','get_security_runtime_audit_command'],['mcp-broker','MCP servers','get_mcp_broker_snapshot_command']])await check('Named app.open reaches the real classic screen: '+app,async()=>{const result=await tool('app.open',{app});await page.getByRole('region',{name:title,exact:true}).waitFor();await eventually(async()=>{const text=await page.locator('.nx-stage-body').innerText();return text&&!/Loading Personal Mesh state|Refreshing…|Auditing…|Loading broker|Loading MCP/i.test(text)&&text;},45000);const owner=await request('/api/backend',{command,payload:app==='office-suite'?{toolId:'tool.libreoffice'}:{}});await picture(app);const screen=await page.locator('.nx-stage').innerText();return{requested:result,screen,readOwner:{command,status:owner.status,ok:owner.ok,error:owner.error??owner.data?.error??null},boundary:'Navigation and settled honest owner state only; external action success is not inferred',visibleRefusals:screen.split('\n').filter(line=>/unavailable|refus|not ready|not installed|incomplete|not implemented|could not|cannot|missing/i.test(line))};});
  await check('Keyboard launcher focuses search, traps focus, selects Outputs and restores focus on Escape',async()=>{await page.getByRole('button',{name:'Close MCP servers',exact:true}).focus();await page.keyboard.press('Control+Space');const dialog=page.getByRole('dialog',{name:'Apps and search'}),search=dialog.getByRole('combobox',{name:'Search'});await search.waitFor();await eventually(()=>search.evaluate(e=>e===document.activeElement),5000);await page.keyboard.press('Shift+Tab');assert.equal(await dialog.evaluate(e=>e.contains(document.activeElement)),true);await search.focus();await search.fill('Outputs');await page.keyboard.press('Enter');await page.getByRole('region',{name:'Outputs',exact:true}).waitFor();await page.getByRole('button',{name:'Close Outputs',exact:true}).focus();await page.keyboard.press('Control+Space');await search.waitFor();await eventually(async()=>(await search.inputValue())==='',5000);await search.fill('Explicit search to clear');await page.keyboard.press('Escape');await eventually(async()=>(await search.inputValue())==='',5000);assert.equal(await dialog.isVisible(),true);await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});await eventually(()=>page.getByRole('button',{name:'Close Outputs',exact:true}).evaluate(e=>e===document.activeElement),5000);return{searchFocused:true,focusContained:true,keyboardSelected:'Outputs',firstEscapeClearsSearch:true,secondEscapeCloses:true,focusRestored:true};});
  await check('Reduced-motion preference limits actual shell animation and transitions to1ms',async()=>{await page.emulateMedia({reducedMotion:'reduce'});const observed=await page.evaluate(()=>({requested:matchMedia('(prefers-reduced-motion: reduce)').matches,root:document.querySelector('.nx-root')?.getAttribute('data-nx-motion'),animation:getComputedStyle(document.querySelector('.nx-stage')).animationDuration,transition:getComputedStyle(document.querySelector('.nx-stage')).transitionDuration}));assert.equal(observed.requested,true);assert.equal(observed.animation,'0.001s');assert.equal(observed.transition,'0.001s');await picture('keyboard-reduced-motion');return observed;});
  }
  assert.deepEqual(uiSources(),receipt.buildSources,'Production UI source changed during this real build/journey');receipt.buildSourcesUnchanged=true;
  assert.equal(receipt.console.filter(x=>x.type==='forbidden-port').length,0);receipt.ok=true;
}catch(error){receipt.ok=false;receipt.error=String(error.stack??error);if(page&&!page.isClosed()){receipt.failureUi=await page.locator('body').innerText().catch(()=>null);await picture('failure').catch(()=>{});}process.exitCode=1;}
finally{await browser?.close().catch(()=>{});await stop(native);await stop(backend);receipt.cleanup={nativeStopped:!native||native.exitCode!==null||native.signalCode!==null,backendStopped:!backend||backend.exitCode!==null||backend.signalCode!==null};receipt.sources=['web/src/neyvia/next/NxShell.jsx','web/src/neyvia/next/NxStage.jsx','web/src/neyvia/next/NxClassicScreens.jsx','web/src/neyvia/next/NxOutputs.jsx','web/src/neyvia/next/NxPanes.jsx','web/src/neyvia/next/NxPerception.jsx','web/src/neyvia/next/NxLauncher.jsx','web/src/neyvia/next/nxPrimitives.jsx','web/src/neyvia/next/nxTokens.css','web/src/neyvia/next/nxMotion.css','web/src/neyvia/next/nxBus.js','web/src/neyvia/next/nxOsStore.js','web/src/neyvia/NeyviaMarketplacePanel.jsx','web/src/neyvia/neyviaMarketplaceModel.js','web/src/neyvia/neyviaApplicationContract.js','web/src/neyvia/NeyviaOfficeSuitePanel.jsx','web/src/neyvia/neyviaOfficeSuiteModel.js','web/src/neyvia/NeyviaPersonalMeshPanel.jsx','web/src/neyvia/NeyviaSecurityRuntimePanel.jsx','web/src/neyvia/NeyviaMcpBrokerPanel.jsx','src/grant_agent/desktop_bridge.py','src/grant_agent/neyvia_ui_api.py','manuals/cl/outputs.cl','manuals/cl/perception.cl','scripts/verify_fix_navigation_ui.mjs'].map(p=>({path:p,sha256:sha(path.join(repo,p))}));receipt.nativeBinarySha256=sha(path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe'));receipt.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(repo,'scripts/evidence/FIX-navigation-ui.json'),JSON.stringify(receipt,null,2)+'\n');}
