/* Real Reader control -> authenticated native queue -> actual article -> safe plaintext overlay. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
const repo=path.resolve(__dirname,'..'),port=48668,cdp=48664,base=`http://127.0.0.1:${port}`;
const root=path.join(repo,'.agent_control/proofs/reader-ui-'+Date.now()),staticRoot=path.join(root,'static');
const output=path.join(repo,'scripts/evidence/FIX-reader-ui.json'),nativePath=path.join(repo,'scripts/browser-probe/target/debug/browser-proof.exe');
const env={...process.env,PYTHONPATH:path.join(repo,'src'),NEYVIA_UI_BACKEND_URL:base,NEYVIA_BROWSER_PROOF_SCOPE:'FIX',NEYVIA_PROOF_CREDENTIAL_GUARD:'1',NEYVIA_TOOL_AUTO_UPDATE:'0',NEYVIA_COORDINATOR_AUTOSTART:'0',FLUXIO_WATCHDOG_AUTOSTART:'0',NEYVIA_CONNECTED_SERVICE_PORT:String(port),PYTHONUNBUFFERED:'1'};
const receipt={scope:'FIX-reader-ui',ports:[port,cdp],root,startedAt:new Date().toISOString(),boundary:'Actual production NxBrowser Reader control rendered in real disposable WebView2, authenticated full backend, actual separate native article. Text extraction reuses production observer revision; no installed desktop/public deployment claim.',checks:[],pictures:[],calls:[],sources:{}};
let backend,native,browser,page,cookie;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sanitize=value=>JSON.parse(JSON.stringify(value,(k,v)=>/token|password|cookie/i.test(k)?'[masked]':v));
function save(){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');}
async function eventual(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await sleep(150);}throw Error('Expected real UI transition timed out');}
async function request(route,body){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)});const data=await response.json();receipt.calls.push({route,body:sanitize(body||{}),status:response.status,data:sanitize(data)});return {response,data};}
async function op(op,args={}){const {response,data}=await request('/api/ui/browser',{op,args});assert.equal(response.status,200,JSON.stringify(data));assert.equal(data.ok,true,JSON.stringify(data));return data;}
async function complete(row){if(!row.actionId)return row;return eventual(async()=>{const data=await op('action.get',{actionId:row.actionId});if(data.status==='failed')throw Error(JSON.stringify(data));return data.status==='done'?data:false;});}
async function stateTab(tabId){return (await op('state')).tabs.find(t=>t.id===tabId);}
async function check(name,fn){try{const detail=await fn();receipt.checks.push({name,ok:true,detail});save();return detail;}catch(e){receipt.checks.push({name,ok:false,error:e.stack});save();throw e;}}
async function picture(name){const target=path.join(repo,'scripts/evidence/fix/reader-ui-'+name+'.png');await page.screenshot({path:target});receipt.pictures.push({path:path.relative(repo,target),sha256:hash(target)});save();}
async function kill(child){if(child&&child.exitCode===null&&child.signalCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
async function navigate(url){const input=page.getByRole('combobox',{name:'Address and search',exact:true});await input.fill(url);await input.press('Enter');}
function fixtures(){
  fs.writeFileSync(path.join(staticRoot,'reader-article.html'),`<!doctype html><title>Native reader document</title><style>body{font:20px system-ui;padding:30px} .hidden{display:none} /* STYLE_CANARY_FIX */</style><nav>NAV_CANARY_FIX</nav><main><article><h1>Reader field notes</h1><p>The native article contains a real paragraph for the reader to display exactly.</p><h2>A useful section</h2><p>Safe plain text includes &lt;img src=x onerror="window.readerHtmlExecuted=true"&gt; as literal text.</p><form>FORM_CANARY_FIX<input type=password value=PASSWORD_CANARY_FIX><input type=hidden name=access_token value=TOKEN_CANARY_FIX><textarea>FORM_VALUE_CANARY_FIX</textarea></form><p>Mirrored secrets: PASSWORD_CANARY_FIX and TOKEN_CANARY_FIX.</p><p class=hidden>HIDDEN_CANARY_FIX</p><aside>ASIDE_CANARY_FIX</aside></article></main><script>window.fixtureScript='SCRIPT_CANARY_FIX';</script>`);
  fs.writeFileSync(path.join(staticRoot,'reader-empty.html'),'<!doctype html><title>No article here</title><nav>Navigation only</nav><form>Login only<input type=password value=PASSWORD_CANARY_FIX></form>');
  fs.writeFileSync(path.join(staticRoot,'reader-next.html'),'<!doctype html><title>Next reader document</title><main><article><h1>The second article</h1><p>New navigation replaced the first article completely.</p></article></main>');
  fs.writeFileSync(path.join(staticRoot,'reader-private-root.html'),'<!doctype html><title>Private root</title><body data-private><p>PRIVATE_ROOT_CANARY_FIX is private content that must not enter Reader.</p></body>');
  fs.writeFileSync(path.join(staticRoot,'reader-editable-root.html'),'<!doctype html><title>Editable root</title><body contenteditable=true><p>EDITABLE_ROOT_CANARY_FIX is editable content that must not enter Reader.</p></body>');
  fs.writeFileSync(path.join(staticRoot,'reader-long.html'),`<!doctype html><title>Bounded article</title><article><h1>Long article</h1>${'<p>'+('Bounded text is readable. '.repeat(300))+'</p>'.repeat(1)}${Array.from({length:30},()=>'<p>'+('More article text. '.repeat(300))+'</p>').join('')}</article>`);
}
async function main(){
  fs.mkdirSync(staticRoot,{recursive:true});fs.cpSync(path.join(repo,'.agent_control/fix/browser-ui/dist'),staticRoot,{recursive:true});fixtures();
  const log=fs.openSync(path.join(root,'backend.log'),'a');backend=spawn('C:/Users/user/AppData/Local/Programs/Python/Python313/python.exe',['scripts/run_web_backend.py','--host','127.0.0.1','--port',String(port),'--root',root,'--static-root',staticRoot,'--skip-runtime-auto-update','--skip-proof-self-check'],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);
  await eventual(async()=>{if(backend.exitCode!==null)throw Error('Backend exited '+backend.exitCode);try{return (await fetch(base+'/api/health',{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},60000);
  const login=await fetch(base+'/api/auth/local-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.ok(login.ok);cookie=login.headers.get('set-cookie').split(';')[0];
  const connected=await op('runtime.connect'),opened=await op('tab.open',{url:base+'/reader-article.html'}),tabId=opened.tabId;
  const nativeLog=fs.openSync(path.join(root,'native.log'),'a');native=spawn(nativePath,[],{cwd:repo,env:{...env,NEYVIA_BROWSER_BASE:base,NEYVIA_BROWSER_TOKEN:connected.token,NEYVIA_BROWSER_PROOF_UI_URL:base+'/ui-proof.html',NEYVIA_BROWSER_PROOF_UI_PROFILE:path.join(root,'ui-profile'),NEYVIA_BROWSER_PROOF_OWNER_COOKIE:cookie,NEYVIA_BROWSER_PROOF_COMMANDS:'browser_call_command',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${cdp}`},windowsHide:true,stdio:['ignore',nativeLog,nativeLog]});fs.closeSync(nativeLog);
  await eventual(async()=>{if(native.exitCode!==null)throw Error('Native exited '+native.exitCode);try{return (await fetch(`http://127.0.0.1:${cdp}/json/version`,{signal:AbortSignal.timeout(500)})).ok;}catch{return false;}},30000);
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`);page=await eventual(()=>browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().includes('/ui-proof.html')));receipt.console=[];page.on('pageerror',error=>receipt.console.push(error.message));
  await page.getByRole('button',{name:'Reader mode',exact:true}).waitFor({timeout:30000});await complete(opened);
  await check('Reader control renders actual native title and exact article text at acknowledged observer revision',async()=>{
    await page.getByRole('button',{name:'Reader mode',exact:true}).click();await page.getByRole('heading',{name:'Reader field notes',exact:true}).waitFor({timeout:20000});assert.equal(await page.locator('.nx-br-reader p').filter({hasText:'The native article contains'}).textContent(),'The native article contains a real paragraph for the reader to display exactly.');
    const read=await op('reader',{tabId,cached:true});assert.equal(read.available,true);assert.equal(read.title,'Reader field notes');assert.ok(read.revision);await picture('article');return {reader:read,tabId};
  });
  await check('Reader omits secret fields, scripts, styles, navigation and hidden text; HTML stays plain text',async()=>{
    const read=await op('reader',{tabId,cached:true}),text=await page.locator('.nx-br-reader').textContent();for(const canary of ['PASSWORD_CANARY_FIX','TOKEN_CANARY_FIX','NAV_CANARY_FIX','SCRIPT_CANARY_FIX','STYLE_CANARY_FIX','FORM_CANARY_FIX','FORM_VALUE_CANARY_FIX','HIDDEN_CANARY_FIX','ASIDE_CANARY_FIX']){assert.ok(!text.includes(canary),canary);assert.ok(!JSON.stringify(read).includes(canary),canary);}
    assert.match(text,/Mirrored secrets: \[redacted\] and \[redacted\]/);assert.match(text,/<img src=x/);assert.equal(await page.locator('.nx-br-reader img').count(),0);assert.equal(await page.evaluate(()=>window.readerHtmlExecuted),undefined);return {allCanariesAbsent:true,mirroredSecretsRedacted:true,noArticleHtmlExecuted:true};
  });
  await check('Reader toggles back to actual native page and on again',async()=>{
    await page.getByRole('button',{name:'Show the page',exact:true}).click();await page.getByRole('button',{name:'Reader mode',exact:true}).waitFor();assert.equal(await page.locator('.nx-br-reader').count(),0);const nativeObserve=await complete(await op('observe',{tabId}));assert.match(nativeObserve.result.observation.text,/The native article contains/);
    await page.getByRole('button',{name:'Reader mode',exact:true}).click();await page.getByRole('heading',{name:'Reader field notes',exact:true}).waitFor();return {nativeObservationRevision:nativeObserve.result.observation.revision,toggledOffAndOn:true};
  });
  await check('Navigation invalidates prior Reader and shows only fresh native article',async()=>{
    const previous=await op('reader',{tabId,cached:true});await navigate(base+'/reader-next.html');await page.getByRole('heading',{name:'The second article',exact:true}).waitFor({timeout:20000});const read=await op('reader',{tabId,cached:true});assert.notEqual(read.revision,previous.revision);assert.equal(read.url,base+'/reader-next.html');assert.equal(await page.locator('.nx-br-reader').getByText('New navigation replaced the first article completely.',{exact:true}).count(),1);assert.ok(!(await page.locator('.nx-br-reader').textContent()).includes('Reader field notes'));await picture('navigation');return {oldRevision:previous.revision,newReader:read};
  });
  await check('Empty real page gives actionable Reader refusal and recovery control',async()=>{
    await navigate(base+'/reader-empty.html');await page.getByText("Reader mode couldn't read this page",{exact:true}).waitFor({timeout:20000});await page.getByText(/no readable article text/).waitFor();await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByText(/no readable article text/).waitFor();await picture('empty-refusal');return {message:await page.locator('.nx-br-center').textContent(),realPage:base+'/reader-empty.html'};
  });
  await check('Oversized actual article is bounded and shortening is disclosed',async()=>{
    await navigate(base+'/reader-long.html');await page.getByRole('heading',{name:'Long article',exact:true}).waitFor({timeout:20000});const read=await op('reader',{tabId,cached:true});assert.equal(read.truncated,true);assert.ok(read.text.length<=40500);assert.ok(read.blocks.length<=200);await page.getByText(/text shortened/).waitFor();await picture('bounded');return {length:read.text.length,blocks:read.blocks.length,truncated:read.truncated};
  });
  const deniedRoots=[['reader-private-root.html','PRIVATE_ROOT_CANARY_FIX'],['reader-editable-root.html','EDITABLE_ROOT_CANARY_FIX']];
  if(process.argv.includes('--root-counterexample')){
    receipt.counterexample=[];
    for(const [route,canary] of deniedRoots){await navigate(base+'/'+route);await page.locator('.nx-br-reader p').filter({hasText:canary}).waitFor();const leaked=await op('reader',{tabId,cached:true});assert.ok(leaked.text.includes(canary));await picture(route.replace('.html','')+'-before');receipt.counterexample.push({actualNativePage:base+'/'+route,leakedReader:leaked});save();}
    throw Error('Actual native Reader serialized both known-private and editable source roots before repair');
  }
  for(const [route,canary] of deniedRoots)await check('Denied native root refuses Reader and recovers: '+route,async()=>{
    await navigate(base+'/'+route);await page.getByText("Reader mode couldn't read this page",{exact:true}).waitFor({timeout:12000});const message=await page.locator('.nx-br-center').textContent();assert.match(message,/private|editable|hidden|readable/i);assert.equal(await page.locator('.nx-br-reader').count(),0);assert.ok(!message.includes(canary));const cached=await request('/api/ui/browser',{op:'reader',args:{tabId,cached:true}});assert.equal(cached.data.ok,false);assert.ok(!JSON.stringify(cached.data).includes(canary));await picture(route.replace('.html','')+'-refusal');
    await navigate(base+'/reader-next.html');await page.getByRole('heading',{name:'The second article',exact:true}).waitFor();return {message,privateRootNotSerializedToReader:true,cachedReaderRefused:cached.data,recoveredToOrdinaryArticle:true};
  });
  if(process.argv.includes('--backend-proof'))await check('Independent real model/backend Reader journey',async()=>{
    const log=fs.openSync(path.join(root,'model-reader-proof.log'),'a');const child=spawn(process.execPath,['scripts/verify_fix_reader.mjs','--base',base,'--root',root],{cwd:repo,env,windowsHide:true,stdio:['ignore',log,log]});fs.closeSync(log);const status=await new Promise(resolve=>child.once('exit',resolve));assert.equal(status,0,fs.readFileSync(path.join(root,'model-reader-proof.log'),'utf8'));const backendReceipt=JSON.parse(fs.readFileSync(path.join(repo,'scripts/evidence/FIX-reader.json')));assert.equal(backendReceipt.ok,true);return {receipt:'scripts/evidence/FIX-reader.json',checks:backendReceipt.checks.length};
  });
  await check('Disconnected real runtime gives actionable Reader failure',async()=>{
    await op('runtime.disconnect');await page.locator('.nx-br-bar').getByRole('button',{name:'Show the page',exact:true}).click();await page.locator('.nx-br-bar').getByRole('button',{name:'Reader mode',exact:true}).click();await page.getByText("Reader mode couldn't read this page",{exact:true}).waitFor({timeout:20000});const text=await page.locator('.nx-br-center').textContent();assert.match(text,/desktop app|runtime|connect|open/i);await picture('runtime-unavailable');return {message:text,runtimeActuallyDisconnected:true};
  });
  for(const file of ['src-tauri/src/browser_runtime.rs','src-tauri/src/browser_projection.js','scripts/browser-probe/src/main.rs','src/grant_agent/neyvia_browser.py','web/src/neyvia/next/NxBrowser.jsx','web/src/neyvia/next/NxBrowserParts.jsx','web/src/neyvia/next/nxBrowserApi.js','scripts/verify_fix_reader_ui.cjs'])receipt.sources[file]=hash(path.join(repo,file));receipt.nativeBinarySha256=hash(nativePath);receipt.finishedAt=new Date().toISOString();receipt.ok=receipt.checks.every(c=>c.ok);save();
}
main().catch(e=>{receipt.error=e.stack;receipt.ok=false;save();process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await kill(native);await kill(backend);receipt.ownedProcessesStopped={native:!native||native.exitCode!==null||native.signalCode!==null,backend:!backend||backend.exitCode!==null||backend.signalCode!==null};save();});
